### ISSUE TITLE
Session expiration

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/Ampersand#1002]
When a session expires in a prototype, and thereafter a user picks up and continues to interact, a red error message appears that is meaningless to most users. 

Can we have a prototype jump to a (preconfigured) 'session has expired'-page, which (I guess) would allow for the proper restarting of a session (in the background)

**Comment by Michiel-s** [comment]
Stale issue.
I'll close this one because insufficient information available to diagnose this issue. Please provide at least an error message, including call stack.
Possibly a duplicate of #1009
