### ISSUE TITLE
non-existing interfaces prohibit reinstallation of prototype

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/Ampersand#1005]
When developing prototypes, I regularly make changes to INTERFACEs. More often that in earlier days, this requires prototypes to be reinstalled (which is something we currently cannot avoid). When you do not reinstall yourself, an error message is provided saying that some interface cannot be found, which reminds me that I have to do this. 

However, when you arrive at this point, there is no way to reinstall the prototype: it keeps popping up with this message:

![afbeelding](https://user-images.githubusercontent.com/8522589/63147161-9d684c00-bffd-11e9-96e5-7da6a3f397ee.png)

As an &-developer, I am now stuck. Can this be fixed?

A workaround is to start phpMyAdmin find the database, and manually remove it.

**Comment by Michiel-s** [comment]
@RieksJ please always open the error message and copy paste the stack trace in the issue. That really helps to find where the bug is coming from.
I think I know what is happening and will come with a fix in a few moments.
