### ISSUE TITLE
Bug in matching concepts of interface expressions in Ampersand framework

### ISSUE THREAD

**Issue by Michiel-s** [AmpersandTarski/Ampersand#1015]
Consider the following script:

```adl
CLASSIFY A ISA B
RELATION prop[A*A] [PROP]
RELATION bName[B*Name] [UNI]

INTERFACE "Test" : I[B] BOX
  [ "no-prop" : I[A]-prop BOX
    [ "name" : bName CRUD
    ]
  ]
```

Although an epsilon is applied for expression `bName`, the Ampersand framework (back-end) throws an exception when editing the relation because concept of provided src atom (e.g. a1[A]) does not match the src concept of `bName[B*Name]`. Currently specialization are allowed, but not generatlizations.

**Comment by hanjoosten** [comment]
Nice catch. I guess all info you need is available in the json files?

**Comment by Michiel-s** [comment]
I cannot reproduce this error anymore...
