### ISSUE TITLE
Invariant violation in metapopulation in Prototype Framework

### ISSUE THREAD

**Issue by stefjoosten** [AmpersandTarski/Ampersand#1016]
When adding e.g. a TOT constraint on a relation with src concept Role (= meta concept), the prototype framework gives a invariant violation during the metapopulation installer phase.

For RAP3 we've seen this for the TOT constraint on `RELATION name[Role*RoleName]`

**Comment by hanjoosten** [comment]
The idea of the metapopulation is that it is added in a single database transaction. Not sure if that helps with diagnosing this issue.

**Comment by RieksJ** [comment]
I've recently added `SIAMv4_Stubs.adl` to the SIAMv4 module that takes care of this/similar issue(s) that I've come across (that's in case you don't want to use SIAM). If you do want to use SIAM, then SIAMv4 will automatically take care of this.
