### ISSUE TITLE
fatal in FSpecAux, related to different interpretation of SESSION and Session

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/Ampersand#1018]
I use `Ampersand-v3.17.2 [development:254cacd10]` to compile the script
~~~
CONTEXT Bug

INTERFACE "Test": V[Session*X] BOX [ "line": TXT "soemthing" ]

ENDCONTEXT
~~~
I expect this to compile correctly, and indeed, `ampersand --daemon` does not complain.
However, when attempting to create a prototype from this script, I get the error
~~~
No plug found for concept 'Session'.
CallStack (from HasCallStack):
  fatal, called at src/Ampersand\FSpec\FSpecAux.hs:26:14 in ampersand-3.17.2-LJnFxYbq5oF9ViOfLtHvrp:Ampersand.FSpec.FSpecAux
~~~
The error is obvious: the text `Session` in the script should have been capitalized.
But the bug has a different nature: it does not provide a good error message for the developer. So that is what this issue calls for fixing.

**Comment by hanjoosten** [comment]
I did some diagnosis. When `Session` is substituted by `Y`, the fatal remains:

```
No plug found for concept 'Y'.
CallStack (from HasCallStack):
  fatal, called at src/Ampersand\FSpec\FSpecAux.hs:26:14 in ampersand-4.0.0-KLSa3YaKdfkKUY9QcbofLu:Ampersand.FSpec.FSpecAux
2019-12-23 16:36:20.984240: [error] ExitFailure 2
```

**Comment by hanjoosten** [comment]
The fix removes the fatal. The script is valid. A prototype will be generated. A warning will be thrown because there are two concepts, `SESSION` and `Session`, which will be treated as two concepts, not one.
