### ISSUE TITLE
Cleanup Archimate_Extention branch and make pull request.

### ISSUE THREAD

**Issue by hanjoosten** [AmpersandTarski/Ampersand#1027]
This branch has several files that must be removed, or the purpose should be made clear:

- [x] ArchiExtension/**  (This looks to me like old obsolete stuff)
- [x] docker stuff, like Dockerfile  and docker/** This must be integrated with current development in Ampersand. My guess is that there is no need at all to have specific stuff for Archimate
- [x] texlive.profile . This is the same as docker/texlive/texlive.profile

**Comment by hanjoosten** [comment]
This is a prerequisite for #1026

**Comment by hanjoosten** [comment]
@stefjoosten Once you did this cleanup, please create a pull request to pull this branch into development. Make me a reviewer.

**Comment by Michiel-s** [comment]
Keep in mind that I also cleaned up some stuff in the github-ci branch related to docker files and the texlive file you mentioned. Maybe first merge #1025, update the Archimate branche and then merge.
