### ISSUE TITLE
Different rules with the same name should not be allowed

### ISSUE THREAD

**Issue by hanjoosten** [AmpersandTarski/Ampersand#1029]
Consider the following script:

~~~
CONTEXT Issue1029

RULE "aap": I[A]

PATTERN Dummy1
  RULE "aap": I[B] 
ENDPATTERN

PATTERN Dummy2
  RULE "aap": I[C] 
ENDPATTERN

ENDCONTEXT
~~~

#### Version of ampersand that was used 
Ampersand-v4.0.0 [development:a0be40614*]

#### What I expected
I expected the script to fail, because it contains different rules with the same name

#### What happened instead
It succeeded

#### Steps to reproduce
1. Just try to compile the above script. This error must have been there for ages. 
2.
3.
4.

**Comment by Michiel-s** [comment]
Indeed, this is not correct.
When I run `ampersand proto above-script.adl`
It produces one rule and only one conjunct, in this case the one for `I[B]`
```sql
select distinct "concept0"."B" as src, "concept1"."B" as tgt 
from "B" as "concept0", "B" as "concept1" 
where "concept0"."B" <> "concept1"."B"
```
