### ISSUE TITLE
multiple rows of menu items overlap notifications

### ISSUE THREAD

**Issue by hanjoosten** [AmpersandTarski/Ampersand#103]
When a lot of interfaces are available, there may be multiple lines of menu items. In that case, messages in the notification area become (partly) invisible:
![schermafdruk 2015-06-11 09 32 07](https://cloud.githubusercontent.com/assets/1159672/8102041/476b771c-101d-11e5-9497-19aabe7071d5.png)

**Comment by Michiel-s** [comment]
Issue niet opgelost. Controleer bij rollen of interfaces niet overlopen op 2e regel. Bij kleinere schermen (bv. tablets) wordt het menu nu wel samengedrukt onder 1 knop.
Wanneer we submenu structuren gaan ondersteunen is het niet meer nodig.

**Comment by Michiel-s** [comment]
Possible solution: lib http://ngmodules.org/modules/ng-bootstrap-submenu

**Comment by hanjoosten** [comment]
@Michiel-s , Ik heb nu een model met veel top-level interfaces, waarbij ik bij een breed scherm last heb zoals beschreven. Ik kan het scherm minder breed maken, dan heb ik op een gegeven moment het kantelpunt. Is dat eenvoudig instelbaar te maken?

**Comment by RieksJ** [comment]
Suggesties voor workarounds:
- gebruik kortere interfacenamen
- verzin rollen en hang aan elke rol slechts een paar interfaces (rollen dienen zo als een soort submenu selector)

**Comment by stefjoosten** [comment]
Students and novices, who run into this for the first time, will not immediately understand what is going on here. For them, this can be a serious obstacle.
