### ISSUE TITLE
Interface with label 'PF_MenuItems' is not defined

### ISSUE THREAD

**Issue by stefjoosten** [AmpersandTarski/Ampersand#1033]
#### Version of ampersand that was used 

I built RAP3 from AmpersandTarski/RAP@33d315dca8643e5db055deb8d61d6245dac75c22, which uses the development branch of Ampersand 4.0.0.

#### What I expected
I expected RAP to appear on http://rap.localhost.

#### What happened instead
After starting completely afresh (even flushing the browser cache) I got the following result (Screenshot):
<img width="1792" alt="Schermafdruk 2019-12-31 11 38 48" src="https://user-images.githubusercontent.com/275768/71618946-42a54a80-2bc2-11ea-94eb-09da7a91c78b.png">

**Comment by stefjoosten** [comment]
# Analysis
1. The interface PF_MenuItems is defined in file `Navbar.ifc` as `API "PF_MenuItems" FOR SYSTEM`. This file is seen by the Ampersand compiler when generating RAP:
<img width="663" alt="Schermafdruk 2019-12-31 11 49 54" src="https://user-images.githubusercontent.com/275768/71619233-b005ab00-2bc3-11ea-8e43-063dcb37c8a9.png">

**Comment by hanjoosten** [comment]
I remember. This is tightly related to #979. I have a good idea for a workaround. Let's discuss that over the phone first.

**Comment by Michiel-s** [comment]
It's something different I think. When looking at the generated json files, I don't see the mentioned interface in the definition files, while it should be there.

This issue occurs as of Ampersand v4.0.0

When I look at [this line of code](https://github.com/AmpersandTarski/Ampersand/blob/a994135b9cafd46fa20d090ac0456bfeb801e5cf/src/Ampersand/Misc/Commands.hs#L335) I only see that the user script is grinded with the proto context, but the proto context itself is not added. @hanjoosten can you confirm that this is indeed the case and that somewhere else in the code the prototypecontext is not added.
We DO require the protocontext to be merged into the userscript when generating a prototype.

**Comment by hanjoosten** [comment]
True. This has everything to do with the way the recipe's for building the FSpec works currently. Today I had a good idea to make this all more simple. This wil also fix this bug. Expect this fix to be part of my current work in branch feature/enableAtlas.

**Comment by hanjoosten** [comment]
This should be fixed now in commit fed559c5fe031408293083bef5eb2af2713b342d

**Comment by Michiel-s** [comment]
Great, when can we expect this branch to be ready? The reason I ask is because we can’t create prototypes with Ampersand v4 at this moment due to this issue.

**Comment by hanjoosten** [comment]
I am still working on some failed tests. This has to do with meatgrinder stuff, not with the prototype. I am investigating still. If these are too hard, I am going to disable those tests temporarily. So expect this branch to be merged very soon.

**Comment by hanjoosten** [comment]
@stefjoosten or @Michiel-s , please close this ticket as soon as you validated that this works now in the development branch. It should be fixed with PR https://github.com/AmpersandTarski/Ampersand/pull/1034
