### ISSUE TITLE
DataAnalysis functionality is unreliable

### ISSUE THREAD

**Issue by hanjoosten** [AmpersandTarski/Ampersand#1037]
With the implementation of `dataAnalysis`, P_Population became an instance of Named. This is wrong, especially the way it was implemented:

~~~.haskell
instance Named P_Population where
name P_RelPopu{p_nmdr = nr} = name nr
name P_CptPopu{p_cnme = nm} = nm
~~~

I stumbled upon this during my investigation of the meatgrinder. In that branch, I removed the above statements and introduced a local function nameFIXME. This is local to the `dataAnalisys` functionality. 
@stefjoosten, please fix this, or the dataAnalisys will be very unreliable, because it does not take into account overloaded relations.

**Comment by stefjoosten** [comment]
Please explain why P_Population must not be an instance of Named.

(I do not understand how dataAnalysis will be unreliable, when it does not take into account overloaded relations.)

**Comment by stefjoosten** [comment]
I have committed the change in branch `fixAtlasComplete` (commit 0e7496b6b5bfd2c97dfbd1b331ec72e2c93702ec)

**Comment by hanjoosten** [comment]
So I see. You are right that name could be used. I think I raised this issue because there also was Eq defined on the name, Not sure though. Is'nt important anymore.

**Comment by stefjoosten** [comment]
Well, if there is no particular reason for `P_Population` not being an instance of `Named`, I'd like to revert this change for the sake of maintainability (I understand the code better if `name` is used instead of a mixture of `p_nmdr` and `p_cnme` combined with `name`. So if it is all the same to you I will revert it.
