### ISSUE TITLE
Prototype cannot be generated while script is valid

### ISSUE THREAD

**Issue by hanjoosten** [AmpersandTarski/Ampersand#1045]
Script of this example:

~~~
CONTEXT "Issue1045"

  RELATION fulfilled [Role * Department] [TOT]
  MEANING "Every role is fulfilled by at least one department"

ENDCONTEXT
~~~

#### Version of ampersand that was used 
Ampersand-v3.17.5 [master-v3x:e93df046b]

#### What I expected
I expect that a prototype can be generated from any correct script.

#### What happened instead
The above script is correct. When just checking this script it says:
~~~
Processing your model...
Finished processing your model
Your script has no errors and no warnings
~~~

However, when a prototype is being generated, the following error occurs:
~~~
Processing your model...
Violations of rule RULE TOT fulfilled[Role*Department]: EInc (EDcI Role,ECps (EDcD fulfilled[Role*Department],EFlp (EDcD fulfilled[Role*Department]))):
    [ ("Administrator","Administrator")
    , ("Anonymous","Anonymous")
    , ("ExecEngine","ExecEngine")
    , ("SYSTEM","SYSTEM")
    ]
ERROR: No prototype generated because of rule violations.
~~~

**Comment by RieksJ** [comment]
I expect that a similar error would have occurred if the relation `fulfilled` would have been specified as `fulfilled[SESSION*Department] [TOT]`. The concept `Role`, like `SESSION`  is special in that it is used in the interaction between the frontend and the application as defined in the user script. Developers should be aware of this interaction, and the concepts/relations that are involved. 

Fixing this particular issue is straightforward. Possible solutions:
- add `POPULATION` statements that define Departments to these four roles
- rename the concept `Role`
- replace the rule `TOT` with `I[Role] - systemRole |- fulfilled;fulfilled~`, because that's why we have the relation `systemRole` (I think its called that, or else it is something similar).

Related issues: #935, #957, #979, #1046.

**Comment by hanjoosten** [comment]
> a Role in Ampersand has well-defined semantics
I disagree. It depends on the context. In the context of formalAmpersand a `Role` is well-defined. And so it is in the context of PrototypeContext. However, these are not the same. In the context of FormalAmpersand, we have a rule `name[Role*RoleName][TOT]`. In the context of PrototypeContext, we have the rule `label[Role*Label][TOT]`. Both rules are only valid in the specific context. Hence, it cannot be said that both concepts are equivalent. 

You suggestion is that the user should modify her script in some way or the other. This means that either we should generate an error when the initial check is done (I do not like this option), or we have to drop the rule that we can generate a prototype from any correct script. (I do not like this option as well).

As has been shown in the motivation why I disagree about the universal semantics of Role, I would say that the concepts in any context are disjunct from the concepts in another context, unless explicitly specified that they are related (equal or related via classify). 
This is where namespaces come in.

**Comment by RieksJ** [comment]
I agree that namespaces should be supported. 

Until then, however, a prototype has only one context, (regardless of whatever `CONTEXT` statements a developer must, or wants to specify). In order for me to agree with the statement that we should be able to generate a prototype from any correct script (which I very much like to), we currently need the phrase 'correct script' to mean 'correct set of scripts, which consist of scripts supplied by the developer and those supplied by the &-tool'.

**Comment by hanjoosten** [comment]
This is indeed what we intend to do. @Michiel-s and I discussed that until namespaces are properly implemented, we will ensure that the prototype context will be as invisible as possible for the user. That means that all names used in the `prototypeContext` will be prefixed manually with "pf_", including the concept that was named "Role". This wil cloak the elements of the prototypeContext enough for now. Regular users will be unaware of the required additions made to make the prototype work.

**Comment by RieksJ** [comment]
Did you actually modify stuff in the prototypeContext? That would certainly explain why several of my applications no longer work. If so, can you specify the changes you have made?

**Comment by hanjoosten** [comment]
No, not that I am aware of. You might want to doublecheck using Git.

**Comment by hanjoosten** [comment]
This problem is evidence of the problem discussed in issue #1046

**Comment by Michiel-s** [comment]
As concluded in #1099, we're not going to solve the issue with naming conflict with Prototype context now.

> We have considered the following options:
> 1. either say CLASSIFY PF_Role ISA Role or say CLASSIFY Role ISA PF_Role. We'd have to figure this out - it isn't trivial.
> 2. say CLASSIFY PF_Role IS Role, which equates both concepts. We recall some earlier discussions on whether or not such a statement actually works. However, #851 assumes it does.
> 3. wait for namespaces/contexts to be implemented. This requires a refactoring of everything anyway, and we can solve the issue in the process."
