### ISSUE TITLE
The problem of combining contexts

### ISSUE THREAD

**Issue by hanjoosten** [AmpersandTarski/Ampersand#1046]
# Introduction
During the development of ampersand 4, we are exploring new terrains. One of them is to combine contexts. The way it is done at this moment [leads to problems](https://travis-ci.org/AmpersandTarski/Ampersand/jobs/634420302#L4954). 

The purpose of this issue is not to solve the problem (which is related to the namespaces discussion), but to get a proper analisys of the problem. Only after we have such analisys done, we should think about solutions. 

# Example of the problem
In ampersand 3 we also combine contexts. When a prototype is being generated based on a user's sctipt, the user's context is combined with a special prototypeContext, in order to get the navigation bar of the prototype correct. The implemented solution also contains the problem. That can be observed in issue #1045 .

# Approach
I suggest to do the analisys at [this page in the wiki](https://github.com/AmpersandTarski/Ampersand/wiki/Combining-Contexts), so we can all contribute in a version controlled document.

**Comment by Michiel-s** [comment]
@hanjoosten, I believe this issue is not relevant anymore after you refactored the build recipes right? We do have our feature request for namespacing #850 which will make combining context also more easy and predictable.

I say let's close the issue here.
