### ISSUE TITLE
Documentation for HTML templates needed

### ISSUE THREAD

**Issue by stefjoosten** [AmpersandTarski/Ampersand#1050]
When writing and maintaining the Ampersand application I badly needed some documentation for the HTML-extensions for views and boxes.

### Version of ampersand that was used 
Ampersand 4.0.0

### What I expected
I expected to see usage instructions on GitBook, but there weren't any.

### What happened instead
I had to reconstruct it by code inspection, but failed miserably...

**Comment by stefjoosten** [comment]
@RieksJ, would you have a first go at this?

**Comment by RieksJ** [comment]
which HTML-extensions specifically are you referring to? AFAIK, @Michiel-s does not agree to port the HTML-extensions that we use internally into the prototype repo, because of his intentions to rework the frontend stuff, and adding HTML extensions would increase the burden of doing that.

**Comment by stefjoosten** [comment]
I am referring to:
Atomic-ALPHANUMERIC.html
Atomic-FLOAT.html
Atomic-TYPEOFONE.html
Box-GRID.html
Box-PROPBUTTON.html
Box-SHCOLS.html
View-STRONG.html
Atomic-BIGALPHANUMERIC.html
Atomic-HUGEALPHANUMERIC.html
Box-CDIV.html
Box-HCOLS.html
Box-RDIV.html
Box-TABS.html
View-URL.html
Atomic-BOOLEAN.html
Atomic-INTEGER.html
Box-COLS.html
Box-HROWS.html
Box-ROWS.html
View-FILEOBJECT.html
interface.controller.js
Atomic-DATE.html
Atomic-OBJECT.html
Box-COLSNL.html
Box-HROWSNL.html
Box-ROWSNL.html
View-LINKTO.html
interface.html
Atomic-DATETIME.html
Atomic-PASSWORD.html
Box-DIV.html
Box-PANELS.html
Box-SCOLS.html
View-PROPERTY.html
routeProvider.config.js

The problem to solve here is how to reuse useful stuff. This is most likely specific for Prototype and not Ampersand, (After all, these extensions will not work in another (fictitious) front-end framework.) By the way, all templates reside in the Prototype-repo and none of them are in the Ampersand-repo.

Still, the current Ampersand user who wishes to decorate her prototypes with html- or js-extensions need help in using them. The issue here is how to help these users (of which I am one).

Could it be an idea to put a user instruction for each extension in the code itself? In the Ampersand documentation we can then give the location (in the Prototype-repo) and mention that the components are (or should be) self-explaining.

**Comment by hanjoosten** [comment]
This issue is related with #1084 . That ticket highly reduces the need of a lot of different templates. The templates that remain will be documented in the `README.md` file that comes with the templates. 
Currently, it can be found [here](https://github.com/AmpersandTarski/prototype/tree/feature/box-attributes/templates), within time, it will be part of master branch, [here](https://github.com/AmpersandTarski/prototype/tree/master/templates).

**Comment by RieksJ** [comment]
It now has become part of the master branch and can be found in (the readme file in) the [templates directory](https://github.com/AmpersandTarski/prototype/tree/development/templates) of the prototype.
