### ISSUE TITLE
Request to create a 'Hello World' application

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/Ampersand#1052]
People such as myself, that have some experience with ampersand projects in the pre-docker era, need guidance/support to make the change to the docker-era.

I would like to see the following items added to this repository:

- [ ] a step-by-step instruction for setting up a working Docker environment, and testing it for its correct functioning.
- [ ] an ampersand script from which a prototype can be generated and that developers can use to test whether or not their docker setup functions properly.
- [ ] a step-by-step instruction for compiling this Ampersand script, and running it, for the purpose of verifying that the development cycle can be executed.
- [ ] a set of suggestions/best practices for novices to the docker era.

**Comment by hanjoosten** [comment]
I think this is a very good idea. We might want to focus on documenting what we currently have in the next period. There is a need for good documentation all over the place.

**Comment by stefjoosten** [comment]
Yep, we need it.  How does https://ampersandtarski.gitbook.io/documentation/installing-ampersand/deploying-your-prototype fit your needs?

**Comment by Michiel-s** [comment]
@stefjoosten, I think you refer to the project template repo. See https://github.com/AmpersandTarski pinnend repo’s at the top of the page.

That’s not an example project. I do have the project administration example available: https://github.com/Michiel-s/Project-administration
