### ISSUE TITLE
Ampersand cli - only write errors and warnings to stderr

### ISSUE THREAD

**Issue by Michiel-s** [AmpersandTarski/Ampersand#1053]
Currently all log output from Ampersand cli is written to `stderr`. This causes that e.g. in the docker build output all ampersand logs are colored red in the console.

Request to:
debug, info, notice -> stdout
warning, error -> stderr

**Comment by hanjoosten** [comment]
We might want to consider using json as log format. Specially in a docker environment, we could add a log service (e.g. https://www.npmjs.com/package/json-log-viewer). 
In that case we should log to such service.

**Comment by stefjoosten** [comment]
Good point Michiel. Docker automatically forwards all standard output from containers to the built-in logging driver. To take advantage of this, applications running in our Docker containers should write all log events to STDOUT and STDERR.
The standard logging driver reads JSON, but this can be configured. That is where Han's remark comes in. But that implies that our applications are logging their events in a fit-for-containers way.

**Comment by Michiel-s** [comment]
@hanjoosten, As we are moving towards containarizing the application, we shouldn’t add our own logging solution. Just write to stdout and stderr and the container runnner (eg. Docker) will do the rest. No need for further formatting.

The issue I raised here is to write ‘debug, info and notice’ log levels to stdout and warning and error to stderr. This will allow Docker to color the logs automatically in the right color in the console (or any other configured log handler). White for stdout and red for stderr

**Comment by hanjoosten** [comment]
The point is that RIO out-of-the-box solution writes everything to a single handle. I could write wrappers for every type of log function, to fulfill your request. I could instead write code to spit it out as json, I think both are more or less equivalent in the amount of work.

**Comment by Michiel-s** [comment]
Ok. It’s not urgent.
I don’t understand where the json comment comes from. Docker can already store logs if needed. So waste of time in my opinion

**Comment by Michiel-s** [comment]
Current implementation is sufficient. I withdraw my issue.
