### ISSUE TITLE
Ampersand daemon does not report type errors.

### ISSUE THREAD

**Issue by hanjoosten** [AmpersandTarski/Ampersand#1054]
#### Version of ampersand that was used 
Ampersand-v4.0.0 [feature/aliasing:dcc2c1d38]

#### What I expected
I expect that ampersand daemon finds all static errors that may occur.

#### What happened instead
In the supplied script, `ampersand daemon` says everything is good, while `ampersand check` finds an error. 

#### Context / Source of ampersand script

```
CONTEXT Issue1054
   RELATION r [A * B] [UNI,INJ, SUR,TOT,SYM,ASY,TRN,RFX,IRF,PROP]
ENDCONTEXT
```

**Comment by stefjoosten** [comment]
Is this problem caused by a version mismatch?

**Comment by hanjoosten** [comment]
No. I observed this behaviour using the same version of ampersand. I have to investigate what exactly causes this.

**Comment by hanjoosten** [comment]
I diagnosed the problem, and it is caused by a technical small mistake.
