### ISSUE TITLE
Functionality of `ampersand check`-command

### ISSUE THREAD

**Issue by stefjoosten** [AmpersandTarski/Ampersand#1063]
# What happened
I wanted to check my script for semantic violations. So I used a script with errors and ran `ampersand check`. However, this command only gave me a type check and no violations

# What I expected
I expected that `ampersand check` would provide me a full list of violations without further ado.

# Version of ampersand that was used
Ampersand-v4.0.0

# Steps to reproduce

1. Use any script that contains errors. For example:
```
CONTEXT Issue298 IN DUTCH

{- This scipt should fail to produce a prototype.
   "thisShouldFail" is not in Even and is not in Odd.
-}
RULE ruleOne : I[Natural] |- I[Even] \/ I[Odd]
CLASSIFY Even ISA Natural
CLASSIFY Odd  ISA Natural

POPULATION Natural CONTAINS ["thisShouldFail" , "one" , "two"]
POPULATION Even    CONTAINS ["two"]
POPULATION Odd     CONTAINS ["one"]

ENDCONTEXT
```
(This example is the content of So I used `Ampersand/testing/Sentinel/Tests/ShouldFail/Issue298.adl`.)

2. 
```
sjo00577@BA92-C02T81JCGTDY ShouldFail % pwd
/Users/sjo00577/git/Ampersand/testing/Sentinel/Tests/ShouldFail
sjo00577@BA92-C02T81JCGTDY ShouldFail % ampersand check Issue298.adl
Reading file /Users/sjo00577/git/Ampersand/testing/Sentinel/Tests/ShouldFail/Issue298.adl
This script of Issue298 contains no type errors.
sjo00577@BA92-C02T81JCGTDY ShouldFail % 
```

**Comment by stefjoosten** [comment]
## Proposal
1. I propose that the command `ampersand check` gives an unlimited check on the semantics, which means it checks all violations unless there are errors that cause violations to be undefined.
2. I propose there be an option to restrict checking to type checking, which is useful if I'm not interested in seeing violations.

**Comment by hanjoosten** [comment]
That shouldn't be too hard to implement. I'll have a shot at it

**Comment by hanjoosten** [comment]
this is related with issue #728

**Comment by hanjoosten** [comment]
The option of restricting this check is allready available: --ignore-invariant-violations. This option was only available for the proto command. It will be available now for all commands that build an FSpec.
