### ISSUE TITLE
!Fatal 55 - No plug found for concept 'Session' in Ampersand [master:3f4f705*]

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/ampersand#108]
The script specified below yields the following error:

     ampersand.exe: !fatal 55 (module FSpecAux) Ampersand v3.1.0[master:3f4f705*]
     No plug found for concept 'SESSION'.

Here is the script:

     CONTEXT Test IN ENGLISH
     
     portIsBidir :: IOPort * IOPort [PROP]
     portIsInput :: IOPort * IOPort [PROP]
     portIsOutput :: IOPort * IOPort [PROP]
     
     RULE "IOPort integrity": 
        I |-    (portIsBidir  /\ -portIsInput  /\ -portIsOutput)
             \/ (portIsOutput /\ -portIsBidir  /\ -portIsInput)
             \/ (portIsInput  /\ -portIsOutput /\ -portIsBidir)
     MEANING "A port must be one and only one of the following: Bidir, Input, or Output"
     VIOLATION (TXT "Input:",    SRC (portIsInput; V;'T'[Message] \/ (I-portIsInput); V;'F'[Message])
               ,TXT ", Output:", SRC (portIsOutput;V;'T'[Message] \/ (I-portIsOutput);V;'F'[Message])
               ,TXT ", Bidir:",  SRC (portIsBidir; V;'T'[Message] \/ (I-portIsBidir); V;'F'[Message])
               )
     
     POPULATION portIsBidir  CONTAINS [ ("Bidir1", "Bidir1") ]
     POPULATION portIsBidir  CONTAINS [ ("Bidir2", "Bidir2") ]
     POPULATION portIsBidir  CONTAINS [ ("Bidir3", "Bidir3") ]
     
     POPULATION portIsInput  CONTAINS [ ("Input1", "Input1") ]
     POPULATION portIsInput  CONTAINS [ ("Input2", "Input2") ]
     POPULATION portIsInput  CONTAINS [ ("Input3", "Input3") ]
     
     POPULATION portIsOutput  CONTAINS [ ("Output1", "Output1") ]
     POPULATION portIsOutput  CONTAINS [ ("Output2", "Output2") ]
     POPULATION portIsOutput  CONTAINS [ ("Output3", "Output3") ]
     
     INTERFACE "Ports" : V[SESSION*IOPort]
     COLS[ "Port": I
         , "Bidir" : portIsBidir
         , "Input" : portIsInput
         , "Output": portIsOutput
         ]
     
     INTERFACE "Port" (portIsBidir, portIsInput, portIsOutput) : I[IOPort]
     COLS[ "Port": I
         , "Bidir" : portIsBidir
         , "Input" : portIsInput
         , "Output": portIsOutput
         ]
     
     ENDCONTEXT

**Comment by RieksJ** [comment]
Als je de `INTERFACE "Ports"` eruitgooit, dan is de fout weg.

**Comment by RieksJ** [comment]
The following `INTERFACE` definition would solve it:

     INTERFACE "Ports" : '_SESSION';V[SESSION*IOPort]
     COLS[ "Port": I
         , "Bidir" : portIsBidir
         , "Input" : portIsInput
         , "Output": portIsOutput
         ]

**Comment by hanjoosten** [comment]
Solved
