### ISSUE TITLE
RIO transition not complete

### ISSUE THREAD

**Issue by stefjoosten** [AmpersandTarski/Ampersand#1080]
# What happened
The code of `fSpec2Haskell` generates Haskell source code. This generated code still refers to `IO` instead of `RIO`. I read:
```
fSpec2Haskell env now fSpec
    = T.intercalate "\n" $
        [ "{-# OPTIONS_GHC -Wall #-}"
        , "{-Generated code by "<>ampersandVersionStr<>" at "<>tshow now<>"-}"
        , "module Main"
        , "where"
        , ""
        , "import Ampersand"
        , "import Text.Pandoc hiding (Meta)"
        , ""
        , "main :: IO ()"
        , "main = do env <- getOptions"
        , "          say (showHS env \"\\n  \" fSpec_"<>(T.pack $ baseName env)<>")"
        , ""
        , "fSpec_"<>(T.pack $ baseName env)<>" :: FSpec"
        , "fSpec_"<>(T.pack $ baseName env)<>" =\n  "<>showHS env "\n  " fSpec
        ]
```
I suspect this means that the generated code will not compile.

# What I expected
I expected to see code with `main = do env <- ask`, but I didn't look into it any further.

# Version of ampersand that was used
Ampersand-v4.0.0 [archi-parser:9150a06c3*]

**Comment by hanjoosten** [comment]
This code has served it's purpos, but is not being actively maintained. It has bitrotted over 5 years. No need to port this to RIO.
