### ISSUE TITLE
Disable invariant checking for documentation

### ISSUE THREAD

**Issue by stefjoosten** [AmpersandTarski/Ampersand#1081]
@hanjoosten I need some help here. I find myself unable to figure this out on my own.

I want to create Ampersand documentation **before** invariants are checked, so I can report the violations inside the documentation.

# What happened
In file `Commands.hs` I have found the `documentationCmd`:
```
documentationCmd :: DocOpts -> RIO Runner ()
documentationCmd docOpts =
    extendWith docOpts $ do
        env <- ask
        let recipe = recipeBuilder False env
        mFSpec <- createFspec recipe
        doOrDie mFSpec doGenDocument
```
Somehow, I want to switch off `allowInvariantViolationsL env`, so I can generate the proper documentation. It should be a little thing, but it is very hard to find out how.

# What I expected
I expected it to be an easy change. So that is why I need a little help

# Version of ampersand that was used
Ampersand-v4.0.0 [archi-parser:9150a06c3*]

**Comment by hanjoosten** [comment]
fixed with PR #1082
