### ISSUE TITLE
Daemon no longer recognizes `--#IF`

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/Ampersand#1085]
Using Ampersand-v3.17.2 [development:254cacd10], I try to compile a script that contains the following code:
~~~
--#IF ExtendedCredTypeSelection -- Later, we can select with more detail
    INCLUDE "./cc_selecting_credtypes.adl"
--#ELSE -- For now, we select with simple means
-- here we put the simple selection code
--#ENDIF
~~~

I expected this to compile without an error, as it would have a few months ago (I've not worked with & for a few months). Specifically, since `ExtendedCredTyepSelection` is false, the text `INCLUDE "./cc_selecting_credtypes.adl" should have been treated as comment. 

Instead, the daemon shows the following error:
![image](https://user-images.githubusercontent.com/8522589/85001883-81b95f00-b154-11ea-8f27-33f6215d491b.png)

This issue requests to fix the daemon.

**Comment by hanjoosten** [comment]
There is no support for the preprosessor hack in  the daemon. There has never been support for that. The daemon sees the preprocessor stuff as comments. It is very unlikely that is going to change.

**Comment by RieksJ** [comment]
(Why) is this a big deal?

**Comment by hanjoosten** [comment]
Yes, this would mean a really big amout of work.
