### ISSUE TITLE
Unhelpful error message: "expecting Keyword "BYPLUG""

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/ampersand#109]
Consider the following script: 

     CONTEXT Test IN ENGLISH
     
     portIsBidir  :: IOPort * IOPort [PROP]
     portIsInput  :: IOPort * IOPort [PROP]
     portIsOutput :: IOPort * IOPort [PROP]
     
     CONCEPT SESSION
     
     INTERFACE "Ports": '_SESSION';V[SESSION*IOPort]
     COLS[ "Port": I
         , "Bidir" : portIsBidir
         , "Input" : portIsInput
         , "Output": portIsOutput
         ]
     
     ENDCONTEXT

This script produces the error 

     Error(s) found:
     "testfile.adl" (line 9, column 1):
     unexpected Keyword "INTERFACE"
     expecting Keyword "BYPLUG"

However, the error is that the `CONCEPT` declaration lacks a text.

**Comment by hanjoosten** [comment]
True, The CONCEPT statement hasn't finished, but maybe also the RELATION definition statement. That one has a lot of optional extensions, like BYPLUG. So that is a valid keyword to expect. 
Maybe @DanielSchiavini or @MaartenBaertsoen could comment on this one, but I do not agree that it is a bug.

**Comment by DanielSchiavini** [comment]
If this is the complete error, it looks like a bug. The EBNF is:
'CONCEPT' ConceptName 'BYPLUG'? String ('TYPE' String)? String?

So after ConceptName we should expect either BYPLUG or String.
The message should then be something like: unexpected Keyword "INTERFACE" / expecting Keyword "BYPLUG" or String

Since BYPLUG is optional, the following error seems acceptable as well: unexpected Keyword "INTERFACE" / expecting String

**Comment by RieksJ** [comment]
It would be quite helpful if the error messages would not only refer to the keyword/text that triggered the error (in this case "INTERFACE") and the text that it has expected (in this case "BYPLUG or String"), but also to the structure that is being parsed (in this case: 'CONCEPT'). This would help the user to pinpoint the cause of the error more quickly. Does that make sense?

@DanielSchiavini Would you be the one taking this on?

@hanjoosten: The issue here is that the current errormessage points users like me in the wrong direction. The current errormessage increases the time I need to solve the error that the message tries to point out rather than that it helps to reduce that time. I am only interested in discussions of whether or not that should be labeled a bug if such a discussion contributes to actually solving this issue (which currently it does not).

**Comment by DanielSchiavini** [comment]
@RieksJ I can fix the bug indeed. I'm not sure if it's possible to add CONCEPT to the error though. I'm not sure it's a good idea either. How should the message be, in your opinion?

**Comment by RieksJ** [comment]
Currently, the generated error is as follows:

     "C:\Ampersand\Git\tno-models\PRACO\PRACO.ifc" (line 13, column 1):
     unexpected Keyword "INTERFACE"
     expecting Keyword "BYPLUG"

Note that in this error message, the line number is that where the keyword `INTERFACE` is found. 
I imagine an errormessage such as the following would be more helpful:

     Error is in "<filename>" 
     while parsing structure <structword> at line <linenr>, column <columnnr>
     Parsing stumbled upon keyword "<keyword>"
     at that point expecting keyword(s) "<keywordlist>" 

where:
- <filename> is the path and name of the file, as it is currently.
- <structword> is the kind of structure that is trying to be completed. In the example, that would be `CONCEPT`.
- <linenr> and <columnr> are the location of the <structword> (rather than the <keyword> where the parser stumbled).
- <keyword> is as is current (in the example, that is `INTERFACE`)
- <keywordlist> is also as is current (which in the example would be `BYPLUG or String`)

How is that?

**Comment by DanielSchiavini** [comment]
@RieksJ, we are delivering the parser documentation and giving a presentation in the coming days. It won't be possible for us to research this before the delivery. But I'll check what we can do to improve the message after that (besides fixing the bug, of course).

**Comment by DanielSchiavini** [comment]
The original issue has been solved. The current error is:

    Error(s) found:
    In file "AmpersandData\FormalAmpersand\Issue109.adl" (line 9, column 2):
    Parsing stumbled upon keyword "INTERFACE"
    at that point expecting keyword "BYPLUG" or concept definition (string)

If adding the "CONCEPT" structure is really necessary, please create another issue and I'll research whether it's possible.
