### ISSUE TITLE
Show of ScriptDateTime doesn't pass the roundtrip.

### ISSUE THREAD

**Issue by hanjoosten** [AmpersandTarski/Ampersand#1090]
https://github.com/ampersandtarski/ampersand/blob/a7160873597bb65f6db47d3e244a2ae9c1b937c6/src/Ampersand/Test/Parser/ArbitraryTree.hs#L272-L272

**Comment by hanjoosten** [comment]
This never worked, but has emerge while I was creating better arbitrary instances for the roundtrip. See [this error message on travis-ci](https://travis-ci.org/github/AmpersandTarski/Ampersand/jobs/708615547#L4715).

NB: This issue was created by clicking the TODO text on the source from within VS-Code 😄

**Comment by hanjoosten** [comment]
The roundtrip has been enabled again and fixed with issue https://github.com/AmpersandTarski/Ampersand/issues/1321

**Comment by Michiel-s** [comment]
Great. Is this issue fixed then?

**Comment by hanjoosten** [comment]
yes, indeed :)
