### ISSUE TITLE
Make prototype framework code a dependency for prototypes

### ISSUE THREAD

**Issue by Michiel-s** [AmpersandTarski/Ampersand#1093]
There are currently two methods in which the prototype framework code (both backend and frontend) is deployed:
1. With Docker (all code is included in the image `docker.pkg.github.com/ampersandtarski/prototype/prototype-framework`. Simply  extend this image for your own project, e.g. [this Dockerfile](https://github.com/AmpersandTarski/project-template/blob/master/docker/prototype.Dockerfile)
2. Generate prototype using the Ampersand compiler using command `ampersand proto`. One of the executed steps is downloading the required version of the prototype framework from Github to the output directory.

For both methods, extending the prototype framework is not that straightforward. E.g. for the backend code (written in PHP) if you want to add another library, you'll need to adapt and overwrite the composer.json file to have that package included. Note that this composer file needs to be synced manually when dependencies (and versions) for the prototype framework change.

Recently the prototype framework code is published on [Packagist](https://packagist.org/packages/ampersandtarski/prototype), the default package repository for PHP composer. This allows to make the prototype framework a dependency for a project, just like any other library/package/..

This issue request to refactor the prototype framework code to allow for this. Special attention is need for bootstrapping the framework and the location of the Slim API methods.

Thereby method 2 (Ampersand compiler downloads code) can and SHOULD be removed.

Benefits:
* We automatically get offline/cache support for downloading the prototype framework (built-in PHP Composer) which is now not the case.
* Extending the prototype framework becomes easier from a developers perspective, e.g.: 
  * Code completion that can be added to your project.
  * Not needed to sync the composer.json anymore

**Comment by Michiel-s** [comment]
Hi @hanjoosten,

I have the following proposal for this issue and would like to hear your opinion and idea.

In de current version of the Ampersand compiler, when you generate a prototype application, the prototype framework is downloaded from github. The compiler knows which version to download by default and this can be set by the user using the `prototype-framework-version` option. E.g. Ampersand compiler v4.0.2 defaults to prototype framework version v1.3.1

Wat we want is do change this. To generate a prototype application you:
1. start with getting the prototype framework, by checking out the git repo (from Github), using the docker image (from Docker hub) or as php requirement (using composer and [Packagist](https://packagist.org/packages/ampersandtarski/prototype))
2. the prototype framework defines the required Ampersand compiler version as a range using semantic versioning (x.y.z with rules). I propose to define a file in the `./generics` folder to specify this. The generics folder is where the compiler must put its output, so it is convenient to have it here.
3. the compiler places the generated files only. No downloading of the framework anymore. A check is done by the compiler for version compatibility.

In case of working with a Docker image, I propose to add the correct Ampersand compiler as a binary in the image. This is already the setup we now have.

- [ ] We need to agree on a version range syntax. Let's use one that fits a library for Haskell. Maybe this one helps? https://hackage.haskell.org/package/semver. I like how this cheat sheet explains the semver ranges: https://devhints.io/semver. E.g. a carrot can be used to specify `^1.2.3` = `>=1.2.3 <2.0.0`. But we could also keep it very simple and just use the regular comparison operations `>=`, `=`, `>`, `<`, `<=`, ..

- [ ] Furthermore, I think it is useful to have an option to ignore the compiler version check for development purposes. E.g. `--ignore-required-version`.

**Proposal for required version file**
`./generics/compiler-version.txt`

```
>= 4.0.2
< 5.0.0
```
Each line specifies a requirement that MUST be satisfied. In this case the prototype framework requires a compiler version >= 4.0.2. AND < 5.0.0

**Comment by Michiel-s** [comment]
Currently the ampersand proto command 1) extracts the prototype framework from Github and 2) generates model files in generics folder. It assumes you have a webserver (Apache) and database (MariaDB) running on your host.
However, we directed our work towards containerization (Docker), so this setup is outdated.

What I think would make sense is to let the ampersand proto command add a Dockerfile and docker-compose.yaml to your working directory. After that you can simply run docker-compose up -d --build and you're good to go.

**Comment by stefjoosten** [comment]
That sounds wonderful. It gives us back the possibility of smoothly running from a laptop.

**Comment by hanjoosten** [comment]
@Michiel-s , I merged the development branch in the [branch we have for this issue](https://github.com/AmpersandTarski/Ampersand/tree/1093-prototype-dependency). I had quite some merge conflicts, which I resolved. I think it would be good to finish this work soon, if possible.

**Comment by Michiel-s** [comment]
Now also added the relevant parts in the prototype framework. As of Ampersand compiler v5.x we'll have a check for compiler version compatibility with the deployed prototype framework.
