### ISSUE TITLE
Error in ampersand.cabal 'field missing'

### ISSUE THREAD

**Issue by stefjoosten** [AmpersandTarski/Ampersand#1094]
# What happened
I got an error in VS-code, saying:
```
CradleError (ExitFailure 1) ["Failed to parse result of calling stack","/Users/sjo00577/git/Ampersand/ampersand.cabal was modified manually. Ignoring /Users/sjo00577/git/Ampersand/package.yaml in favor of the cabal file.","If you want to use the package.yaml file instead of the cabal file,","then please delete the cabal file.","Unable to parse cabal file from package /Users/sjo00577/git/Ampersand/ampersand.cabal","","- 0:0: \"name\" field missing",""]
```
I did what was asked: I deleted the ampersand.cabal file and recompiled (in the CLI, using stack install).
It didn't help...

As a consequence, my ghcide does not work anymore. When I (re)started ghcide, I got this:
![Schermafbeelding 2020-07-19 om 06 57 43](https://user-images.githubusercontent.com/275768/87867460-282f9480-c98d-11ea-9b75-e3cbb4849450.png)

Then I restarted VS-code. That gave me half of ghcide's functionality back: errors are shown but not updated in real time. For that I have to run stack install manually.

Half an hour later the whole thing seems to work again...   Leaving me puzzled.

# What I expected
I expected the compilation process to proceed in a bug-free manner.

# Version of ampersand that was used
Ampersand-v4.0.0 [feature/documentation:6f48d7172*]

# Steps to reproduce
I'm not sure how to reproduce this. It just popped up quite unexpectedly.

# Screenshot / Video
![Schermafdruk 2020-07-19 06 41 06](https://user-images.githubusercontent.com/275768/87867184-dd148200-c98a-11ea-8b79-8c800a809aee.png)

# Context / Source of ampersand script

**Comment by hanjoosten** [comment]
The ampersand daemon and ghcide art two totally different applications. They are unrelated. And yes, ghcide is very promissing, and has very nice functionality already, it is stil in alpha stage. 

When I use ghcide, I notice that after spinning up vscode, it takes a while to become active. Initially, it starts with running setup:

![image](https://user-images.githubusercontent.com/1159672/87875836-56849280-c9d4-11ea-838a-48fb2c500874.png)

After half a minute or sometimes even longer, it starts to compile the rest of Ampersand:

![image](https://user-images.githubusercontent.com/1159672/87875854-6f8d4380-c9d4-11ea-970d-021bb27b9dcb.png)

Ocasionally, it crashes. It tells so in the log (see the output view in VS-code). Over the last couple of weeks I definetly see an improvement, both in performance (speed) as well as stability.
