### ISSUE TITLE
RAW template should, but is not, a 1-1 replacement for DIV and CDIV

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/Ampersand#1102]
The (old) `DIV` and `CDIV` templates used to provide a box without margins, without titles, without labels, etc.

Their replacements, `RAW` and `RAW table` may not provide margins, but the do provide labels and perhaps other stuff.

This issue requests:
- [x] that RAW templates have their 'old' functions again - i.e. ONLY provide contents, nothing else
- [x] that the attribute `form` is recognized, even though it does nothing other than allow the `RAW form` syntax, which may enhance readability.

**Comment by Michiel-s** [comment]
Fixed as part/task of #1104
