### ISSUE TITLE
Request for attribute in templates for having/removing hamburger-menu

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/Ampersand#1103]
The current templates show a hamburger-menu at the top-right corner of their BOX. This is not (always) appropriate.

## Analysis

The contents of the hamburger menu cannot be influenced other than by (not) specifying certain INTERFACES. While this feature may be useful in the development stage of applications, in the operational (deployed) state it usually contains (way) too many entries that confuse the user.

## Request

I suggest to not show these hamburgers by default, and add a box-attribute, e.g. `showMenu` that allows developers to have such a menu if and where they want it.

**Comment by Michiel-s** [comment]
I fully agree. Nice request. I'll see if I can find time to fix this soon.
