### ISSUE TITLE
Cannot build with stack on Windows.

### ISSUE THREAD

**Issue by hanjoosten** [AmpersandTarski/Ampersand#1105]
When building everything from scratch using `stack`, we run into a linker error. It seems that this is due to a known bug in ghc, which will be solved with ghc 8.8.4. However, this is not on stackage. Hopefully, that will be there soon. 

More details can be found [here](https://github.com/haskell/haskell-ide-engine/issues/1779)

**Comment by hanjoosten** [comment]
Because of this issue, I will downgrade to ghc 8.6.5 for now (stack LTS-14.27). Hopefully, the issue with ghc is fixed soon.

**Comment by Michiel-s** [comment]
@hanjoosten can we close this issue? We build with linux/WSL or macOS all now.
