### ISSUE TITLE
Revisiting issue 'Unhelpful error message' (#109)

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/Ampersand#111]
Consider the following script:

```
 CONTEXT Test IN ENGLISH

 portIsBidir  :: IOPort * IOPort [PROP]
 portIsInput  :: IOPort * IOPort [PROP]
 portIsOutput :: IOPort * IOPort [PROP]

 CONCEPT SESSION

 INTERFACE "Ports": '_SESSION';V[SESSION*IOPort]
 COLS[ "Port": I
     , "Bidir" : portIsBidir
     , "Input" : portIsInput
     , "Output": portIsOutput
     ]

 ENDCONTEXT
```

This script produces the error 

```
 Error(s) found:
 In file "AmpersandData\FormalAmpersand\Issue109.adl" (line 9, column 2):
 Parsing stumbled upon keyword "INTERFACE"
 at that point expecting keyword "BYPLUG" or concept definition (string)
```

It woud be helpful to users (i.e. save them time/prevent them from looking at the wrong location, wondering what is wrong with the `INTERFACE`-syntax) if the error message would point the users where to look. This calls for the following two changes:

1) before the line that starts with `Parsing stumbled upon`, insert the line

```
 while parsing structure CONCEPT (line 7, column ...)
```

2) remove the `(line 9, column 2)` as it is the location of `INTERFACE`

Would that be possible?

**Comment by DanielSchiavini** [comment]
1) I'm researching if that's possible.
2) Actually the error is the INTERFACE keyword being there, so I consider that to be the right place for the error. When the parser cannot match a token, should we give the position of the incorrect token or the last correct one? I can imagine that choosing to show the position of the last correct token would introduce more confusing errors than clarifying them.

**Comment by RieksJ** [comment]
While I agree that the error is the INTERFACE keyword being there, I do not follow the implication that hence this would also be the right place for the error, for the following reasons.

First, there are two errors here. The first one is the appearance of the word `INTERFACE` at that particular location, which we agree is an error. The second one is the ommission of the string, that would have been the intention of the user. This is obviously an error, and it differs from the first. Since there are multiple errors, why would the first one be the right one?

Secondly, I believe that the purpose of an error message is to assist the person that made the error to find and correct the error that he made (which is not necessarily the error upon which the parser stumbled) in the most efficient way. From where I stand, a message pointing out the omission of the string would in this case have been the most effective one. But I do realise that it is hard - if not impossible, to always come up with such a message as the parser does not (always) know about the intentions of the user.

Considering the above, I argue that an effective error message would point the user to the structure in which the error has been made, as it is quite likely that the user's intentions are focused there. In any case, it would point the user to the start of the text that he needs to review. I do not object to also point out where the parser stumbled, as it points the user to the end of the text that he needs to consider. For the same reason, I gather it helps the user if he is given a clue as to the structure that the parser is trying to complete.

**Comment by hanjoosten** [comment]
We all agree that it is impossible to know the intention of the user. The
place where the error should be pointing at, is the place where the string
is missing. This is the exact same place where the INTERFACE keyword shows,
for if at that place a string was found by the parser, there wouldn't be an
error....
So I guess the place is right, even though I agree with Rieks that that
isn't the intention of the user...



2015-06-29 5:43 GMT+02:00 Rieks <notifications@github.com>:

**Comment by RieksJ** [comment]
So what do you propose that is (not) being done, and that is helpful for the purpose for which messages are generate?

**Comment by DanielSchiavini** [comment]
The issue here is that the user forgot a string and that missing string has no location. It just isn't there. So you could think of giving the position at the end of "SESSION", but that may even be more confusing. Besides, nothing in the grammar says the string cannot be 2 lines later.

A user who forgot such a string is probably not completely familiar with the grammar. I think it would be useful to say that the error is in the CONCEPT construct, when encountering INTERFACE. The location of CONCEPT shouldn't be hard for the user to find.

**Comment by RieksJ** [comment]
That sounds as a good improvement. Looking forward to it...

**Comment by Michiel-s** [comment]
Situation is still the same. Any change we're picking up this issue? Otherwise I suggest to close it without solution.
