### ISSUE TITLE
cursus RAP3 prototype generation triggers error on git access

### ISSUE THREAD

**Issue by LloydRutledge** [AmpersandTarski/Ampersand#1110]
It looks like the RAP server tries to download github.com:443/AmpersandTarski/Prototype/archive/v1.0.1.zip when generating a prototype but gets no response.

The Rule-based Design course uses this server in three months. About 20 students are already registered and have access to the course material. With this bug, the students cannot make a prototype with the course RAP server.

This is on http://rap.cs.ou.nl/RAP3. I started by copying the enrollment example script code from the tutorial and made the name of the CONTEXT unique.  After compiling a script (and diagnosis and spec) I then click prototype and get an error message under "Message" instead of a prototype. 

I can simply download github.com:443/AmpersandTarski/Prototype/archive/v1.0.1.zip on my browser so the problem is on the RAP server side.

Here is a screenshot:

![image](https://user-images.githubusercontent.com/1098321/92742171-aef66180-f37f-11ea-81c3-110f9889ed98.png)

The text of the message is:

Generating frontend..
Error encountered during deployment of prototype framework:
HttpExceptionRequest Request {
  host                 = "github.com"
  port                 = 443
  secure               = True
  requestHeaders       = []
  path                 = "/AmpersandTarski/Prototype/archive/v1.0.1.zip"
  queryString          = ""
  method               = "GET"
  proxy                = Nothing
  rawBody              = False
  redirectCount        = 10
  responseTimeout      = ResponseTimeoutDefault
  requestVersion       = HTTP/1.1
}
 (ConnectionFailure Network.Socket.getAddrInfo (called with preferred socket type/protocol: AddrInfo {addrFlags = [AI_ADDRCONFIG], addrFamily = AF_UNSPEC, addrSocketType = Stream, addrProtocol = 6, addrAddress = <assumed to be undefined>, addrCanonName = <assumed to be undefined>}, host name: Just "github.com", service name: Just "443"): does not exist (Temporary failure in name resolution))

Regards,
Lloyd

**Comment by stefjoosten** [comment]
This is an infrastructure problem. It has nothing to do with Ampersand or RAP3.
### Diagnosis
Each time a user generates a prototype, it downloads a runtime framework ("/AmpersandTarski/Prototype/archive/v1.0.1.zip") from GitHub. In the course of time, however, certificates in the infrastructure have expired and substituted by other certificates, causing the download to fail. 
### Solution
The OU has reinitialized the DNS-server and I have reinitialized RAP3. That has solved the problem. For now, that is. This condition might reoccur in the future.
In the next release of RAP we will eliminate downloading from GitHub, eliminating the chance of this bug to happen again.
