### ISSUE TITLE
Travis-ci.org will be discontinued by the end of 2020.

### ISSUE THREAD

**Issue by hanjoosten** [AmpersandTarski/Ampersand#1113]
In order to maintain our automatic regression tests, we need to migrate away from Travis-ci.org. We could either go with Travis-ci.com, or leave Travis-ci and go for github actions. 

Here is the [documentation to migrate to Travis-ci.com](https://docs.travis-ci.com/user/migrate/open-source-repository-migration).

**Comment by Michiel-s** [comment]
Github actions!

**Comment by hanjoosten** [comment]
yep
