### ISSUE TITLE
TABS template does not nest properly

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/Ampersand#1115]
I nicely compile the [TText application](https://github.com/AmpersandTarski/ampersand-models/tree/master/TText) using the corresponding [dockerfile](https://github.com/AmpersandTarski/ampersand-models/blob/master/TText/Dockerfile), and subsequently run it in docker containers (so no need to refer to all sorts of ampersand versions or prototype versions).

To reproduce the situation I want to refer to you do the following:
- (re)install the database.
- click on the menu-item `Portal`.
- click on the button `Login or Register`.
- click on the button `Show Accounts`.
- login with the admin account (userid=ad, actorRef=admin)
- activate the role 'Developer' in the role menu (under the person-glyph-icon at the top right of the navbar)
- click on the `[Dev]` interface (which may be under the hamburger-glyph-icon in the navbar)

This interface is defined in [TText_Developer.ifc](https://github.com/AmpersandTarski/ampersand-models/blob/master/TText/TText_module/TText_Developer.ifc), as follows:
~~~
INTERFACE "[Dev]" FOR Developer: "_SESSION"[SESSION] cRud BOX <TABS>
[ "TTexts": I INTERFACE "[TText_Developer]"
, "SIAMv4": I INTERFACE "[SIAMv4_Developer]"
]
~~~
and
~~~
INTERFACE "[TText_Developer]" FOR Developer: "_SESSION"[SESSION] cRud BOX <TABS>
[ "Scopes": I INTERFACE "[Scopes]"
, "TTexts": I INTERFACE "[TTexts]"
, "Assignments": I INTERFACE "[Assignments]"
, "Computations": I INTERFACE "[Computations]"
]
~~~
and `INTERFACE "[SIAMv4_Developer]"` is defined in [SIAM_Developer.ifc](https://github.com/AmpersandTarski/SIAM/blob/master/src/SIAM_Developer.ifc) (from the new SIAM module), as follows:
~~~
INTERFACE "[SIAMv4_Developer]" FOR Developer: "_SESSION" cRud BOX <TABS>
[ "Accounts": V[SESSION*Account] cRud BOX <TABLE sortable>
   [ "id": I[Account] cRud <AccountId>
   , "Userid": accUserid cRud
-- etcetera.
~~~
as you can see, this presents a nesting of multiple `BOX <TABS>`, which are rendered incorrectly as shown by the following screenshot:
![image](https://user-images.githubusercontent.com/8522589/93642955-49e5e000-f9ff-11ea-8838-f9ba9a2045ba.png)

What is wrong here is 

1) that at the bottom of the screen, we see a bullet followed by (the clickable link with) the text `SIAMv4`, where I would have expected that text to appear on a tab at the top of the page (next to the tab on the top row of tabs, labeled `TTexts`). 
2) when I click the `SIAMv4` link, I see the correct interface labels (for Accounts), but I do not see the population that is there (after all, I could only have logged in because there are Accounts) - as shown by the following screenshot

![image](https://user-images.githubusercontent.com/8522589/93643296-06d83c80-fa00-11ea-8c76-a19f567c8eef.png)

This issue calls for fixing the bug that apparently is in the TABS template of the prototype framework.

**Comment by Michiel-s** [comment]
Ok. The issue was not in the TABS template, but in the Box-PROPBUTTON @RieksJ added/changed.
It took me quite some time to find a missing end tag `</div>`.
