### ISSUE TITLE
DEBUG_MODE=false in docker-compose.yml makes the prototype fail to run.

### ISSUE THREAD

**Issue by stefjoosten** [AmpersandTarski/Ampersand#1119]
I built an app, [Enroll](https://github.com/AmpersandTarski/RAP/tree/deploy-2020/Demos/Enroll), and launched it with [docker-compose.yml](https://github.com/AmpersandTarski/RAP/blob/deploy-2020/docker-compose.yml) from AmpersandTarski/RAP@b03b4861534d80ff637f3f39f8f0d71a4b51814a (the RAP-repo), which I ran locally on my MacBook Pro.
I found two environment variables in `docker-compose.yml`, `AMPERSAND_DEBUG_MODE` on line 120, and `AMPERSAND_PRODUCTION_MODE` on line 121, which influence the behavior that cripples enroll.

# What happened
I ran 4 experiments:

1. AMPERSAND_DEBUG_MODE=false and AMPERSAND_PRODUCTION_MODE=true
2. AMPERSAND_DEBUG_MODE=true and AMPERSAND_PRODUCTION_MODE=true
3. AMPERSAND_DEBUG_MODE=false and AMPERSAND_PRODUCTION_MODE=false
4. AMPERSAND_DEBUG_MODE=true and AMPERSAND_PRODUCTION_MODE=false

The app runs fine when AMPERSAND_DEBUG_MODE=true in experiments 2 and 4.

In experiment 1, I get an immediate failure:
<img width="434" alt="Schermafbeelding 2020-10-21 om 10 18 54" src="https://user-images.githubusercontent.com/275768/96692959-f8769b00-1386-11eb-821f-3e61df48b726.png">
The log file shows `API.ERROR: Cannot connect to the databse [] {"request_id":"7ce4b848f2","ip":"192.168.96.2","method":"GET","url":"/api/v1/app/navbar"}`.

Experiment 3 is even stranger. It makes me wait a long time before giving me a virtually empty screen.
Below is the log-file. Notice that I have been waiting from 07:44:47 till 08:05:30 (9 minutes) before the system fails because of an `API.ERROR: Database enroll does not exist`.

So apparently the variable `AMPERSAND_PRODUCTION_MODE` is also consequential for this bug.
```
sjo00577@BA92-C02T81JCGTDY RAP % docker-compose logs -f enroll                   
Attaching to enroll
enroll                     | AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.22.0.5. Set the 'ServerName' directive globally to suppress this message
enroll                     | AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.22.0.5. Set the 'ServerName' directive globally to suppress this message
enroll                     | [Wed Oct 21 07:44:38.017697 2020] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.38 (Debian) PHP/7.4.9 configured -- resuming normal operations
enroll                     | [Wed Oct 21 07:44:38.017809 2020] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
enroll                     | 192.168.96.2 - - [21/Oct/2020:07:44:47 +0000] "GET / HTTP/1.1" 200 948 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.80 Safari/537.36"
enroll                     | 192.168.96.2 - - [21/Oct/2020:07:44:47 +0000] "GET /app/project/ifcEdit_32_interface.controller.js?8130180173028865371 HTTP/1.1" 200 1075 "http://enroll.localhost/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.80 Safari/537.36"
enroll                     | 192.168.96.2 - - [21/Oct/2020:07:44:47 +0000] "GET /app/project/ifcEdit_32_menu_32_item.controller.js?8130180173028865371 HTTP/1.1" 200 1086 "http://enroll.localhost/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.80 Safari/537.36"
enroll                     | 192.168.96.2 - - [21/Oct/2020:07:44:47 +0000] "GET /app/project/ifcOverview.controller.js?8130180173028865371 HTTP/1.1" 200 1052 "http://enroll.localhost/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.80 Safari/537.36"
enroll                     | 192.168.96.2 - - [21/Oct/2020:07:44:47 +0000] "GET /app/project/ifcEdit_32_navigation_32_menu.controller.js?8130180173028865371 HTTP/1.1" 200 1105 "http://enroll.localhost/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.80 Safari/537.36"
enroll                     | 192.168.96.2 - - [21/Oct/2020:07:44:47 +0000] "GET /app/project/ifcList_32_all_32_interfaces.controller.js?8130180173028865371 HTTP/1.1" 200 1089 "http://enroll.localhost/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.80 Safari/537.36"
enroll                     | 192.168.96.2 - - [21/Oct/2020:08:05:30 +0000] "GET / HTTP/1.1" 200 948 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.80 Safari/537.36"
enroll                     | 192.168.96.2 - - [21/Oct/2020:08:05:31 +0000] "GET /app/project/routeProvider.config.js?8130180173028865371 HTTP/1.1" 200 690 "http://enroll.localhost/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.80 Safari/537.36"
enroll                     | 192.168.96.2 - - [21/Oct/2020:08:05:31 +0000] "GET /app/project/ifcEdit_32_menu_32_item.controller.js?8130180173028865371 HTTP/1.1" 200 1086 "http://enroll.localhost/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.80 Safari/537.36"
enroll                     | 192.168.96.2 - - [21/Oct/2020:08:05:31 +0000] "GET /app/project/ifcEdit_32_interface.controller.js?8130180173028865371 HTTP/1.1" 200 1075 "http://enroll.localhost/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.80 Safari/537.36"
enroll                     | 192.168.96.2 - - [21/Oct/2020:08:05:31 +0000] "GET /app/project/ifcList_32_all_32_interfaces.controller.js?8130180173028865371 HTTP/1.1" 200 1089 "http://enroll.localhost/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.80 Safari/537.36"
enroll                     | 192.168.96.2 - - [21/Oct/2020:08:05:31 +0000] "GET /app/project/ifcOverview.controller.js?8130180173028865371 HTTP/1.1" 200 1052 "http://enroll.localhost/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.80 Safari/537.36"
enroll                     | 192.168.96.2 - - [21/Oct/2020:08:05:31 +0000] "GET /app/project/ifcEdit_32_navigation_32_menu.controller.js?8130180173028865371 HTTP/1.1" 200 1105 "http://enroll.localhost/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.80 Safari/537.36"
enroll                     | [2020-10-21 08:05:31] APPLICATION.INFO: Loading configuration from /var/www/src/Ampersand/Misc/defaultSettings.yaml [] {"request_id":"909be83bfc","ip":"192.168.96.2","method":"GET","url":"/api/v1/app/navbar"}
enroll                     | [2020-10-21 08:05:31] APPLICATION.INFO: Loading settings from Ampersand compiler [] {"request_id":"909be83bfc","ip":"192.168.96.2","method":"GET","url":"/api/v1/app/navbar"}
enroll                     | [2020-10-21 08:05:31] APPLICATION.INFO: Loading configuration from /var/www/config/project.yaml [] {"request_id":"909be83bfc","ip":"192.168.96.2","method":"GET","url":"/api/v1/app/navbar"}
enroll                     | [2020-10-21 08:05:31] APPLICATION.INFO: Loading env settings [] {"request_id":"909be83bfc","ip":"192.168.96.2","method":"GET","url":"/api/v1/app/navbar"}
enroll                     | [2020-10-21 08:05:31] APPLICATION.INFO: Initialize Ampersand application [] {"request_id":"909be83bfc","ip":"192.168.96.2","method":"GET","url":"/api/v1/app/navbar"}
enroll                     | [2020-10-21 08:05:31] TRANSACTION.WARNING: ExecEngine role 'ExecEngine' configured, but role is not used/defined in &-script [] {"request_id":"909be83bfc","ip":"192.168.96.2","method":"GET","url":"/api/v1/app/navbar"}
enroll                     | [2020-10-21 08:05:31] TRANSACTION.INFO: Opening transaction: 1650245385 [] {"request_id":"909be83bfc","ip":"192.168.96.2","method":"GET","url":"/api/v1/app/navbar"}
enroll                     | [2020-10-21 08:05:31] TRANSACTION.WARNING: ExecEngine role 'ExecEngine' configured, but role is not used/defined in &-script [] {"request_id":"909be83bfc","ip":"192.168.96.2","method":"GET","url":"/api/v1/app/navbar"}
enroll                     | [2020-10-21 08:05:31] TRANSACTION.INFO: Request to cancel transaction: 1650245385 [] {"request_id":"909be83bfc","ip":"192.168.96.2","method":"GET","url":"/api/v1/app/navbar"}
enroll                     | [2020-10-21 08:05:31] API.ERROR: Database enroll does not exist [] {"request_id":"909be83bfc","ip":"192.168.96.2","method":"GET","url":"/api/v1/app/navbar"}
enroll                     | [2020-10-21 08:05:31] API.ERROR: Database enroll does not exist [] {"request_id":"909be83bfc","ip":"192.168.96.2","method":"GET","url":"/api/v1/app/navbar"}
enroll                     | [2020-10-21 08:05:31] PERFORMANCE.INFO: Peak memory used: 4.28 Mb [] {"request_id":"909be83bfc","ip":"192.168.96.2","method":"GET","url":"/api/v1/app/navbar"}
enroll                     | [2020-10-21 08:05:31] PERFORMANCE.INFO: Execution time  : 0.12 Sec [] {"request_id":"909be83bfc","ip":"192.168.96.2","method":"GET","url":"/api/v1/app/navbar"}
enroll                     | 192.168.96.2 - - [21/Oct/2020:08:05:31 +0000] "GET /api/v1/app/navbar HTTP/1.1" 500 623 "http://enroll.localhost/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.80 Safari/537.36"
```
# What I expected
I expected that I can freely choose the value of variables `AMPERSAND_DEBUG_MODE` and `AMPERSAND_PRODUCTION_MODE`.

# Version of Ampersand that was used
The app was compiled with Ampersand-v4.0.2 [03af6695e24b1d825d2f0da44b2115fb2c52d022:refs/heads/development] by using the docker-image `ampersandtarski/prototype-framework:v1.7.0`.

# Steps to reproduce

1. Clone AmpersandTarski/RAP@b03b4861534d80ff637f3f39f8f0d71a4b51814a (the RAP-repo) to your laptop.
2. cd to the root of RAP and spin it up with `docker-compose up -d`.
3. Verify (with `docker ps` that the service `enroll` is running.
4. In your browser, navigate to `http://enroll.localhost`.

# Context / Source code
```docker-compose
  enroll:
    image: ampersandtarski/enroll:latest
    container_name: enroll
    build:
      context: Demos/Enroll
    restart: unless-stopped
    depends_on:
      - db
      - traefik
    networks:
      - proxy
      - db
    environment:
      - AMPERSAND_LOG_CONFIG=logging.yaml
      - AMPERSAND_DEBUG_MODE=false
      - AMPERSAND_PRODUCTION_MODE=true # false => e.g. enables database reset (in production mode not possible)
      - AMPERSAND_DBHOST=db # refers to database service below
      - AMPERSAND_DBUSER=${MYSQL_USER} # from .env file, which must be in the build environment
      - AMPERSAND_DBPASS=${MYSQL_PASSWORD} # from .env file
      - AMPERSAND_DBNAME=enroll
      - AMPERSAND_SERVER_URL=https://${SERVER_HOST_NAME} # from .env file
    labels:
      traefik.enable: "true"
      traefik.http.routers.enroll-insecure.rule: Host(`enroll.${SERVER_HOST_NAME}`)
      # more labels added for production, see ./docker-compose.prod.yml file
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "100"
```

**Comment by Michiel-s** [comment]
The `AMPERSAND_DEBUG_MODE` and `AMPERSAND_PRODUCTION_MODE` have different meaning and impact. You can mix them however you like, so all experiments should work. However, be informed about the meaning of those settings:

1. AMPERSAND_PRODUCTION_MODE (default: false)
This setting determines which management functions are (not) allowed. Most important one is that in production mode reinstalling the database is not allowed, never! This ensures that by accident all data is lost.
This means that when you start the application in production mode (true), and the database doesn't exist or is outdated (new tables/columns are needed), an exception is thrown. And you are stuck.
This is what you see in the log output above `[2020-10-21 08:05:31] API.ERROR: Database enroll does not exist`

2. AMPERSAND_DEBUG_MODE (default: true)
This setting determines how much debug information is provided to the user. When set to true, the detailed error message, including full stack trace is provided by the api and shown in the frontend. You can view the stack trace by opening (clicking on) the red error message. See screenshot below.
When you set the debug mode to false, error details are not displayed and the message states: `An error occured (debug information in server log files). So an end user doesn't see what's wrong, but the application administrator can inspect the logs to see what's wrong.

To make it easy: when developing use: AMPERSAND_PRODUCTION_MODE=false, AMPERSAND_DEBUG_MODE=true

For RAP3 in production use: AMPERSAND_PRODUCTION_MODE=true, AMPERSAND_DEBUG_MODE=false

For **RAP3 student prototypes** use AMPERSAND_PRODUCTION_MODE=false, AMPERSAND_DEBUG_MODE=false
Because you want to allow students to reinstall their application, but don't want to give detailed server debugging.

![image](https://user-images.githubusercontent.com/7961582/96706045-5a8acc80-1396-11eb-9051-a1889322f833.png)

I'll add this explanation to the config readme of the prototype framework here: https://github.com/AmpersandTarski/prototype/tree/development/config

**Comment by Michiel-s** [comment]
@stefjoosten I think this should give you enough information to determine the rights settings. Please reopen if you are still experiencing issues.

**Comment by stefjoosten** [comment]
I guess that we need to do something special at deploy-time when no database exists. In that case RAP gets AMPERSAND_PRODUCTION_MODE=false, so we can (re-)install to a fresh database.  Then change `docker-compose.yml` so that RAP gets AMPERSAND_PRODUCTION_MODE=true and redo `docker-compose up -d`. @Michiel-s  is that correct?

**Comment by Michiel-s** [comment]
Yes! You need to disable production mode temporary to be able to initiate the database. Another solution is to prepare the database somewhere else and import e.g. via phpmyadmin.

**Comment by Michiel-s** [comment]
I need to correct an earlier comment. The combination production mode false and debug mode false is not intuitive for students, because detailed error (e.g. database does not exist) is not shown and the reinstall UI neither.
Therefore I set the student prototypes at: production mode false, debug mode true.
