### ISSUE TITLE
Use UUIDs for automatically creating atom identifiers in the prototype framework. Instead of a timestamp

### ISSUE THREAD

**Issue by Michiel-s** [AmpersandTarski/Ampersand#1125]
After reading the article [Don't Use Database Generated IDs](https://link.medium.com/RRxfyDQTnab), I was triggered to create this issue.

We already use backend generated identifier (nothing done by database), but some improvement is needed. The current identifiers are of scheme `<Concepttype>_<epoch seconds>_<micro seconds>`, e.g. `ChangeRequest_1592313761_00893227`

Of course this is a bad implementation, because of many reasons, including that is give away when resources are created and allows to easily brute force resource identifiers.

There's a good library that we can use instead: https://uuid.ramsey.dev/en/latest/database.html

This issue request to implement that library, and more specifically the UUID v4 string implementation

```php
use Ramsey\Uuid\Uuid;

$uuid = Uuid::uuid4()->toString();
```

**Comment by Michiel-s** [comment]
Implemented

**Comment by stefjoosten** [comment]
Sounds great. Does this mean we have resolved a potential security vulnerability in generated code?

**Comment by Michiel-s** [comment]
I'm not sure if it was a potential security issue. The session identifier was already a randomly created id by the backend (php internal function).
But anyhow, this is an improvement and makes brute force checking existence of certain atoms way harder.
