### ISSUE TITLE
.xlsx parser should supply more details to the typechecker.

### ISSUE THREAD

**Issue by hanjoosten** [AmpersandTarski/Ampersand#1127]
When working on RAP recently, I got the following error message:

~~~
/home/han/hanGit/RAP/RAP4/src/RAP4.xlsx:
   Sheet: Identity Provider data, Cell: B22.  error:
  An ambiguity arises in trying to match name .
    Be more specific by using one of the following matching expressions:
    - name [Concept*ConceptName]
    - name [Relation*RelationName]
~~~

The error message is due to polymorphism of `name`. However, the .xlsx file clearly states the source and target concepts of the relation, as can be seen here:
![image](https://user-images.githubusercontent.com/1159672/101179519-9cbc5480-364a-11eb-9705-7b4a3336ef43.png)

There is no way the user could be more specific on what he means. It is clear that the relation name[Role*RoleName] is the intended one.

**Comment by RieksJ** [comment]
In my experience, errors generated by the type-checker can be notoriously hard to fix as they do not always point the developer into the direction of a solution. For starters, it helps to carefully read the message (really carefully), and then compare it with what you think might have caused the error. If I do that here, I notice that what you say the user intended, i.e. `name[Role*RoleName]`, is not in the list of suggestions that the error message has provided. One reason for that might be that the user has not declared `name[Role*RoleName]` as a relation in his script.

**Comment by hanjoosten** [comment]
Ah I see what is going on now. The spreadsheet tries to populate a relation `name[Role\*RoleName]`. However, in the Ampersand script, such relation isn't defined. There is some overloading of the name of the relation `name`. It is defined twice, with different source and target concepts, but none that matches `name[Role\*RoleName]`.

The problem is because we intentionally do not implicitly define a relation if it is used in a population statement. We might want to reconsider this.

**Comment by hanjoosten** [comment]
As @sjcjoosten points out in #1137, this could indeed become complicated. We might as well consider if we could do better on the error message: Instead of having only one suggestion that points (in this case) to the wrong direction, I wonder if it would be possible to have something like *A relation is used that is not explicitly defined: `name[Role*RoleName]`*, in addition to the current message:

~~~
/home/han/hanGit/RAP/RAP4/src/RAP4.xlsx:
   Sheet: Identity Provider data, Cell: B22.  error:
  An ambiguity arises in trying to match name .
    Be more specific by using one of the following matching expressions:
    - name [Concept*ConceptName]
    - name [Relation*RelationName]
~~~

I am not sure if we have the original source and target concepts available in the typechecker, at the place where the error is currently triggered. @sjcjoosten , would this be easy to do?

**Comment by sjcjoosten** [comment]
Yes, this error message would be possible in the current setup! This may also influence the error message in rules and other places.
There's something of a "Maybe" type (or something non-total in any case) in the code there, so we may need to render something along these lines in similar cases:

```
A relation is used that is not explicitly defined: name[Role*???].
```

(I would suggest a wildcard type `*` but `[Role**]` looks weird).

**Comment by hanjoosten** [comment]
If you  like, could you give it a try?

**Comment by sjcjoosten** [comment]
Yes, code still compiling (since 3 hours ago. Progress is 176/179 right now), I may continue tomorrow. Will work in the Issue1127 branch.
