### ISSUE TITLE
Removing ROWS and COLS from the parser

### ISSUE THREAD

**Issue by stefjoosten** [AmpersandTarski/Ampersand#1131]
In July we implemented template features for interface boxes (issue #1084)

_@Michiel-s commented in issue #1087 ([comment](https://github.com/AmpersandTarski/Ampersand/issues/1087#issuecomment-659009531))
@hanjoosten, what do you think? As this PR will be a breaking change, I think this is the time to remove the ROWS, COLS, and TABS keywords in the parser. Only the TABS template name stays the same, ROWS are renamed to FORM and COLS to TABLE. So using ROWS and COLS is allowed by the parser, but no built-in template will be found, so an error is returned when generating a prototype.

We have never removed the ROWS, COLS, and TABS keywords in the parser. This has caused issue https://github.com/AmpersandTarski/RAP/issues/109. That could have been prevented if we had done our homework. So let's do this without delay.

**Comment by hanjoosten** [comment]
True. This needs fixed, otherwise users could run into trouble : https://github.com/AmpersandTarski/RAP/issues/109 . Such behaviour is obvious unacceptable.

Tip: If you fix the parser, don't forget to modify ArbitraryTree.hs as well, or Travis will likely fail the regressiontest.

**Comment by RieksJ** [comment]
I suggest to also remove TABS, since it is the only exception to the rule that you now always must use `BOX`. To do TABS, you then write BOX <TABS>.

**Comment by hanjoosten** [comment]
good point. I am in favour.

**Comment by stefjoosten** [comment]
Consider it done.

Stef

Van: Rieks <notifications@github.com>
Beantwoorden - Aan: AmpersandTarski/Ampersand <reply@reply.github.com>
Datum: maandag 4 januari 2021 om 07:50
Aan: AmpersandTarski/Ampersand <Ampersand@noreply.github.com>
CC: Stef Joosten <Stef.Joosten@ou.nl>, Author <author@noreply.github.com>
Onderwerp: Re: [AmpersandTarski/Ampersand] Removing ROWS and COLS from the parser (#1131)


I suggest to also remove TABS, since it is the only exception to the rule that you now always must use BOX. To do TABS, you then write BOX .

**Comment by RieksJ** [comment]
This will leave developers with the task of renaming their `ROWS`, `COLS` and `TABS`, as well as the derived stuff such as `SHCOLS`, `COLSNL` etc. to the new syntax. For developers that use VSCode and that do not mind installing the extension 'batch replacer', there is a way to simply convert all of such occurrences throughout an entire workspace - see #1134.
