### ISSUE TITLE
Support CSV format for importing (initial) population

### ISSUE THREAD

**Issue by jpwijbenga** [AmpersandTarski/Ampersand#1135]
Excel or ODS are the only ways to add meta-population.
In GIT these files are not well managed, when they change.
Could we add CSV files as an option (as compared to a single sheet excel file functionally)? I don't think the sheet name is used for anything, right?

**Comment by hanjoosten** [comment]
This could indeed be a nice idea. However, it contains one header row only. We should think very carefully about how to specify some population with a CSV file. I do not think this is trivial. Also, looking at our current resoursed, I do not think this is high on the priority list. As a workaround, it shoudn't be too much work to manually convert a CSV file into an .xlsx file.

**Comment by Michiel-s** [comment]
@jpwijbenga, for prototypes there are three ways to specify/import population:
1. Using an POPULATION statement in your ADL file. See https://ampersandtarski.gitbook.io/documentation/the-language-ampersand/the-population-statement
2. Using an INCLUDE statement in your ADL file that points to a spreadsheet.
3. Using the runtime population import functionality in the prototype application (see screenshot below). Here you can upload two types of documents: xlsx spreadsheets (same syntax as in 2) ór json files (example syntax below)

I hope this helps.

![image](https://user-images.githubusercontent.com/7961582/106325270-d68c8e80-627a-11eb-9608-fdeac0f9b172.png)

**Example of json population syntax**
```json
{
  "atoms": [
    { "concept": "B", "atoms": ["b1", "b2"] },
    { "concept": "A", "atoms": ["a1"] }
  ],
  "links": [
    {
      "relation": "r[A*B]",
      "links": [
        {
          "src": "a1",
          "tgt": "b1"
        },
        {
          "src": "a1",
          "tgt": "b2"
        }
      ]
    }
  ]
}
```

**Comment by stefjoosten** [comment]
In the past, we have rejected conversion from `.csv` because it is an ambiguous format, which exists in many different versions. For example, it has a large choice of separator characters. This causes error-prone code and many support requests. That is why we have chosen to parse `.xlsx`-files instead. This turned out well because the `.xlsx`-parser is now a stable asset in the Ampersand-software, which has caused little trouble in maintenance.

**Comment by stefjoosten** [comment]
@jpwijbenga Please check out the post [Excel Version Control with Git](http://dailydoseofexcel.com/archives/2018/05/02/excel-version-control-with-git/) by Dick Kusleika. That might help you tackle the root cause of your problem.
