### ISSUE TITLE
Support hidden column for sorting in <TABLE> and <RAW table> templates

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/Ampersand#1136]
The current `BOX <TABLE>` template supports sorting, using the `sortable` and `sortBy="labelname"` attributes. However, I would like to be able to sort the contents of the table based on an interface field that is NOT shown to the user.

There are various ways in which this can be done:
- define a label, e.g. `sortindex` that, when encountered, will implicitly serve as a `sortBy` labelname, but won't be shown.
- define a template-attribute, e.g. `hideSortColumn` the effect of which is that the sorting column isn't shown.

@Michiel-s: perhaps this is something that Peter Langenkamp could do (including the update of the documentation)?

**Comment by Michiel-s** [comment]
I think you need to create a custom template for this. In my opinion this is way to specific use case and would also add more technical dept to the templates.

Also, the default sorting functionality allows the user to change how the table is sorted. When the table stays sorted based on a hidden column (which you cannot change, this might be confusing to the user. Disabling the user to change the sorting is not part of the external UI library we use. So this would require even more work.

I propose to not do this feature. @RieksJ you can develop the functionality anyhow for your project, but let's not add it to the framework.

**Comment by RieksJ** [comment]
The idea is to NOT allow the user to change the sorting, but provide the developer with the ability to specify a simple way of sorting records for which (s)he'd otherwise need to do extra &-coding (or create a custom template like you suggest. I guess if I would be the only one using this feature and the implementation is complex then that's a good argument for not having it in the framework.
