### ISSUE TITLE
Installer doesn't always work - refuses to discard the database

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/Ampersand#1139]
Using the current prototype development stuff (v1.8.4), I often run into the problem that reinstalling the database doesn't work, as shown in the figure:

![image](https://user-images.githubusercontent.com/8522589/105728569-9a7cc500-5f2c-11eb-800c-f8de6ef90372.png)

This happens when I recompile an application and restart it in the docker container while a database (other docker container) is also running. This forces me to also run phpmyadmin in order to remove the database by hand.

**Comment by stefjoosten** [comment]
Can you make an analysis, so we can diagnose this problem?

**Comment by stefjoosten** [comment]
Can you check the environment variable `AMPERSAND_PRODUCTION_MODE` in the run time environment? It should be false if you want to reset the database.

**Comment by RieksJ** [comment]
It is false. It must be, because sometimes resetting works just fine. And it is getting annoying...

**Comment by Michiel-s** [comment]
The thing that is happening here is that the prototype application always needs a session with the user. That session is inserted in the database and the exec engine is run before closing the transaction. However, here the problem, a session atom is added, so all session related rules are checked. There is probably a rule that included the relation `sessionIsMandaatBeheer` (this can be the UNI rule e.g.), but no column/table is there yet. So re-install is needed, but to reinstall the prototype requires a session. Deadlock.

I need to fix this in the prototype framework. In the meantime, the only solution is to delete the entire database scheme manually. Sorry for that.

**Comment by Michiel-s** [comment]
Hi @RieksJ,

I put effort in trying to reproduce your error, but in all cases reinstalling using the UI works fine.

Cases I tried:
1 Adding a new session relation, e.g. `RELATION sessionProp[SESSION] [PROP]`
2 Adding a new session relation AND related invariant rule
3 Adding a new session relation AND exec engine rule
4 Same as 3 AND starting the application without my existing session in database

In all cases I got the red error `Unknown column '<rel>' in 'field list'. Try reinstalling the application`. When clicking reinstall this just works fine.

Please reopen issue when you have more information/context/diagnosis that I can act upon.
