### ISSUE TITLE
Build with cabal is broken, build with stack works fine

### ISSUE THREAD

**Issue by hanjoosten** [AmpersandTarski/Ampersand#1142]
Recently I have been trying to set the build of Ampersand up by using  github actions. I use a matrix to build both with stack and with cabal. I use the same version of ghc. 

A recent build can be seen [here.](https://github.com/AmpersandTarski/Ampersand/runs/1756887612)

As one can see, the build with cabal is broken, while the build with stack is fine. [I asked a question about this in Haskell-Cafe](https://mail.haskell.org/pipermail/haskell-cafe/2021-January/133363.html), where I got a [swift response (Thanks Simon Jakobi !)](https://mail.haskell.org/pipermail/haskell-cafe/2021-January/133364.html).

This response not only gave me some clues to diagnose further, but it also explained where this instance of the trouble came from.

**Comment by Michiel-s** [comment]
@hanjoosten can we close this issue as we have our CICD with GitHub Actions working fine now?
