### ISSUE TITLE
FORM/TABLE/TABS templates - request for attribute `hide(Row|Col|Tab)OnNoPopulation`

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/Ampersand#1144]
Whereas the `hideOnNoRecords` attribute will hide an entire FORM/TABLE (and later perhaps also TABS) if there is no population to show, this property would also be helpful on the elements of such templates (hide a row in a FORM if there is no population, hide a column in a TABLE if there is no population, and hide a tab in a TABS if there is no population).

Consider the following construct in an INTERFACE:
~~~
    , "Records": I[Record] cRud BOX <FORM hideLabels hideRowOnNoPopulation>
        [ "Error message": TXT "There are no records to show." 
        , "Show Records": I-myRecords INTERFACE "ShowRecords"
        , "Edit Records":   myRecords INTERFACE "EditRecords"
        ]
~~~
This would show the error message line only if there are no records.
It also only shows the `ShowRecords` interface if there are records that are not mine (to edit)
It also only shows the `EditRecords` interface if there are records that ARE mine to edit.

Because I believe this to be a real benefit, this issue calls for the implementation of such attribute

**Comment by Michiel-s** [comment]
Interesting feature I think. Let's give the attribute a generic name: `hideSubOnNoRecords`. The `Sub` is short for `SubInterface`.

I'll implement this for `TABS` and `FORM`. Not for `TABLE` because we shouldn't hide a complete column when a single (or few) rows don't have a result in that column.

**Comment by RieksJ** [comment]
Can you also implement it for `RAW` (i.e.: `<RAW form>`)?
