### ISSUE TITLE
How to invite contributors

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/Ampersand#1145]
@hanjoosten : ik wil een collega mee laten doen (email=peter.langenkamp@tno.nl,  github username=peterlangenkamp) maar ik krijg dat niet voor elkaar. Zou je hem kunnen toevoegen en ook aan kunnen aangeven hoe we dat hier in zijn algemeenheid voormekaar kunnen krijgen?

**Comment by hanjoosten** [comment]
I sent an invite to Peter. The way to do it is probably somewhere in the github docs, but [this link] should do the job too.
