### ISSUE TITLE
'hideOnNoRecords' shows title even when there are no records to show

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/Ampersand#1146]
In the template for `TABLE`s, the semantics of the attribute `hideOnNoRecords` [is specified](https://github.com/AmpersandTarski/prototype/tree/development/templates#table) to not show (anything of) the table if there are no records to show. So when this attribute is used in combination with the attribute `title="my title text"`, I would expect this title only to be shown if there are records to show. This is not the case: the title is shown anyway. 

This issue calls for fixing the TABLE template as well as the TABS template that suffers the same issue.

**Comment by Michiel-s** [comment]
True for `TABLE`. I'll fix this.

The interpretation for `TABS` is different, as is also written in the README: `hides a certain tab (i.e. sub interface) when that expression has no target atoms`

**Comment by Michiel-s** [comment]
Together with #1144 I think we should change the behavior of `hideOnNoRecords` for `TABS`. You suggest adding another attribute for the meaning that is currently already implemented for `TABS`. I like this. It's more consistent. Let's do so.
