### ISSUE TITLE
Request to to add the `title=` attribute to the `RAW` template

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/Ampersand#1149]
After one gets used to a new feature and it is good, it tastes like more. An example is the `title=` attribute that has been added to the interface templates `FORM`, `TABLE` and `TABS`. It would be nice to be able to also use this feature in the `RAW` template. 

This issue requests to add the `title=` attribute to the `RAW` template

**Comment by Michiel-s** [comment]
Discussed with @RieksJ, we don't have a use case for this right now.
