### ISSUE TITLE
Something wrong with Travis?

### ISSUE THREAD

**Issue by stefjoosten** [AmpersandTarski/Ampersand#1150]
# What happened
A travis run failed (while I was trying to pull a relatively innocent change through the build chain):
![image](https://user-images.githubusercontent.com/275768/108625779-03346000-744d-11eb-9092-c8bac7f96317.png)
This was the message:
![image](https://user-images.githubusercontent.com/275768/108625805-2232f200-744d-11eb-8565-304d1127fd8a.png)

# What I expected
I didn't expect Travis to quit so soon in the process...

**Comment by RieksJ** [comment]
See #1113?
