### ISSUE TITLE
Expressie met meervoudige target in `VIOLATION`-statement

### ISSUE THREAD

**Issue by stefjoosten** [AmpersandTarski/Ampersand#1152]
versie informatie: Ampersand-v4.1.3 [no git info], build time: 13-Dec-20 22:17:37 UTC.
FROM ampersandtarski/prototype-framework:v1.8.4
RAP commit  00e95c80a8a9ef7a402a84ac505447f13acf72d2 (hij heeft tag Deployed-on-rap.ou.cs.nl-on-Feb-9th,-2021)
#### De situatie

Gegeven het volgende script:
```Ampersand
CONTEXT Hawaii IN ENGLISH
PURPOSE CONTEXT Hawaii
{+ Once in their school career, students get to go on a field trip abroad.
   However, the organizer of the field trip may require that you have completed specific courses.
   This application gives overviews of students and the trips for which they qualify.
   The application illustrates the use of residuals.
+}

RELATION required[Subject*Destination]
MEANING "A subject that you must have passed to qualify for the school trip to a destination"

POPULATION required CONTAINS
   [ ("Surfing", "Hawaii")
   ; ("Latin", "Rome")
   ; ("World Religions", "Rome")
   ]

RELATION passed[Subject*Student]
MEANING "The subjects that have been passed by specific students"

POPULATION passed CONTAINS
   [ ("Surfing", "Brown")
   ; ("Surfing", "Conway")
   ; ("Latin", "Brown")
   ; ("World Religions", "Applegate")
   ; ("World Religions", "Brown")
   ]

RELATION registered[Student*Destination]
-- equivalent rule:  required;registered~ |- passed
PURPOSE RULE guardPrerequisites {+ This rule prevents students from registering for a trip without having passed the required courses. +}
RULE guardPrerequisites : registered~ |- required\passed
MEANING "A student can only attend a trip, if the student passed all the required courses for that destination."
MESSAGE "Attempt to register student(s) for a trip without the proper qualification."
VIOLATION (TXT "Student ", TGT I, TXT " cannot go to ", SRC I, TXT " without passing ", SRC required~)

POPULATION Destination CONTAINS  [ "Amsterdam" ]

INTERFACE Overview : "_SESSION"                       cRud
BOX <TABS>
     [ Students     : V[SESSION*Student]              cRuD
       BOX <TABLE>
            [ "Student" : I[Student]                  cRud
            , "passed" : passed~                      CRUD
            , "Qualify for" : passed~/required~       cRud
            , "registered" : registered               CRUd
            ]
     , Subjects     : V[SESSION*Subject]              cRuD
       BOX <TABLE>
            [ "Subject" : I                           cRud
            , "required for trip" : required          CRUD
            , "students that passed" : passed         CRUD
            ]
     , Destinations : V[SESSION*Destination]          cRuD
       BOX <TABLE>
            [ "Destination" : I                       cRud
            , "required subject" : required~          CRUD
            , "Qualifying students" : required\passed cRud
            , "registered" : registered~              cRUd
            ]
     ]

ENDCONTEXT
```
#### Wat er gebeurde er en wat had je verwacht?
Ik heb van dit script een prototype gegenereerd en gedraaid. Deze regel heeft één overtreding: `("Rome", "Applegate")`. Het probleem zit wellicht in de expressie `SRC required~` (nl. segment 5) binnen het `VIOLATION`-statement. De populatie daarvan is namelijk `("Rome", "Latin")` en `("Rome", "World Religions")`. De foutmelding geeft aan dat het prototype niet in staat is om de combinatie van `"Latin"` en `"World Religions"` af te drukken. Dit vermoeden houdt stand als ik segment 5 uit het `VIOLATION`-statement verwijder. Ik krijg dan alleen de melding:
![afbeelding](https://user-images.githubusercontent.com/275768/107984592-8591cf80-6fc8-11eb-9521-0eb151fec423.png)

#### Stappen om dit te reproduceren
1. Inloggen op `rap.cs.ou.nl`
2. Nieuw script maken met naam: Hawaii
3. De inhoud (hierboven) in de editor plakken
4. Compile-knop
5. Prototype-knop
6. `Open prototype` aanklikken
7. Database initialiseren indien nodig (alleen de eerste keer)
8. In interface `Overview`, in tabblad `Students` proberen om student `Applegate` te registreren voor een trip naar `Rome`.

Dit geeft de volgende foutmelding
#### Screenshot / Video
![afbeelding](https://user-images.githubusercontent.com/275768/107981975-73616280-6fc3-11eb-9015-059bdea0fce9.png)

**Comment by stefjoosten** [comment]
Het lijkt me prima om dit met een een komma-spatie gescheiden lijst te doen.

**Comment by Michiel-s** [comment]
Will be available in next release of prototype framework
