### ISSUE TITLE
Copying a text fragment from an error message in a prototype.

### ISSUE THREAD

**Issue by stefjoosten** [AmpersandTarski/Ampersand#1154]
# What happened
I wanted to copy (by ^C) a text from the screen of an application generated by Ampersand. This concerns the text "Every BindedRelation must have ..." from the screenshot below. However, copying does not work from that spot.

# What I expected
I expected I could copy the text, so I might use it for instance to write an Ampersand Issue on Github...

# Version of ampersand that was used

# Steps to reproduce

1. Run a prototype (I presume an arbitrary one, otherwise use rap.cs.ou.nl
2. use it until you get a red message
3. Try to ^C the title of that message

# Screenshot / Video
![Schermafbeelding 2021-03-10 om 08 39 04](https://user-images.githubusercontent.com/275768/110593689-2d3f8f00-817c-11eb-8a3a-5906ca20145d.png)

**Comment by Michiel-s** [comment]
Won't fix. Currently I'm working on implementing the new Angular frontend. Errors, warnings, rule violations all get new html components.
