### ISSUE TITLE
Possible bug in ADL2Plug.hs

### ISSUE THREAD

**Issue by stefjoosten** [AmpersandTarski/Ampersand#1157]
# What happened
While inspecting the code of ADL2Plug.hs, I found a piece of suspect code.

![Schermafbeelding 2021-03-14 om 10 15 01](https://user-images.githubusercontent.com/275768/111063434-bfae9e00-84ae-11eb-8766-abd9c6f90e04.png)

# What I expected
I expected the `source` on line 169 to be the same as `target` on line 170, so either both `source` or both `target`.

# Analysis
I tried to analyze this situation but got stuck for lack of documentation around this code. It is written by @hanjoosten, so I call on him for help. If it is incorrect, we should fix it. But I also want to know why this bug never showed up in the past 4 years. If it is correct, there may be a bug in `tgtAtt`. If the code is correct I would like to see some comment around this code to explain what is going on and for what purpose.

**Comment by stefjoosten** [comment]
We talked on the phone and agreed that this is a bug. We didn't finish the analysis but we have a strong sense that this is redundant code.

**Comment by Michiel-s** [comment]
I've checked this one and in commit 4f49e71566bcda3c76359d86617ff138cfc03961 it is already fixed. We can close this issue.
