### ISSUE TITLE
Why does the lexer allow relations that start with an underscore?

### ISSUE THREAD

**Issue by stefjoosten** [AmpersandTarski/Ampersand#1163]
# What happened
I noticed that a relation name in Ampersand may start with an underscore. The compiler accepts the following code fragment:
```Ampersand
RELATION _takes [Student*Course]
MEANING "A student takes a complete course"
```
The compiler lets me work with this underscored identifier without problems.
# What I expected
I expected an error because the documentation states clearly that relation names start with a lower case letter. 

# Version of ampersand that was used
Ampersand-v4.1.4 [no git info], build time: 10-Mar-21 13:53:13 UTC

# Steps to reproduce

1. Log into RAP4
2. compile an arbitrary script that has a relation with a name that starts with an underscore.

# Analysis
I found this error by code inspection.
I traced it back to the lexer, in the function isIdStart:
![image](https://user-images.githubusercontent.com/275768/113678501-f8f9b880-96be-11eb-9e01-e940f13c59a0.png)
It is used in the following code fragment in file `lexer.hs`:
```Ampersand
mainLexer p cs@(c:s)
     | isIdStart c || isUpper c
         = let (name', p', s')    = scanIdent (addPos 1 p) s
               name''               = c:name'
               tokt   | iskw name'' = LexKeyword name''
                      | otherwise = if isIdStart c
                                    then LexVarId name''
                                    else LexConId name''
           in returnToken tokt p mainLexer p' s'
```
It is clear that the function `isIdStart` is deliberate. So I wonder why it was inserted. Maybe @DanielSchiavini  knows?
In the meantime I suggest we treat this like an error and fix it. I propose the following change:

![image](https://user-images.githubusercontent.com/275768/113679189-c8fee500-96bf-11eb-958f-c86015780406.png)

This change is ready for testing in commit 7c4d1acd9b1f3f9755b68fb94a77e645fa052a16

**Comment by DanielSchiavini** [comment]
@stefjoosten I think it was a wrong assumption on my side as most programming languages accept underlines.

**Comment by stefjoosten** [comment]
Thanks, @DanielSchiavini, we'll fix it.

**Comment by hanjoosten** [comment]
@stefjoosten , I fixed the readability of the error message that is thrown due to your latest change (https://github.com/AmpersandTarski/Ampersand/commit/02e04a06b631776f0e043d7f2934415bd769367b). Please fix this bug yourself, and make the ci pipeline happy 😃.
