### ISSUE TITLE
Cannot define relations on `ONE`

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/Ampersand#1168]
I want to use a relation `r :: ONE * Counter`

When I define this relation in a script, this produces the error
~~~
  unexpected keyword "ONE"
  expecting upper case identifier or string
~~~

This is obviously a bug.

**Comment by stefjoosten** [comment]
# Analysis
I can reproduce this bug on rap.cs.ou.nl. That's good.

Strangely enough the following works:
```Ampersand
RELATION r[ONE*Counter]
```
