### ISSUE TITLE
Duplicate labels in VIEW

### ISSUE THREAD

**Issue by stefjoosten** [AmpersandTarski/Ampersand#1171]
I encountered this issue in Ampersand-v4.1.4.

#### Observation
I defined a view as follows

```Ampersand
VIEW "Relation": Relation DEFAULT
   { name   : name[Relation*RelationName]
   , lpar   : TXT "["
   , source : source;name
   , lpar   : TXT "*"
   , target : target;name
   , lpar   : TXT "]"
   }
ENDVIEW
```
I expected to see the relation with its signature in brackets with an asterisk (`name[Relation*RelationName]`). However, this is what I got:
<img width="654" alt="afbeelding" src="https://user-images.githubusercontent.com/275768/116569203-7359d900-a909-11eb-915c-4d839ea95f0d.png">

Then I changed the script:
```Ampersand
VIEW "Relation": Relation DEFAULT
   { name   : name[Relation*RelationName]
   , lpar   : TXT "["
   , source : source;name
   , ast    : TXT "*"
   , target : target;name
   , rpar   : TXT "]"
   }
ENDVIEW
```
This attempt produced the expected result:
<img width="662" alt="afbeelding" src="https://user-images.githubusercontent.com/275768/116569009-47d6ee80-a909-11eb-9f30-e7baef91fddc.png">

#### Analysis
In retrospect, my first attempt should have been signalled by the compiler because it has duplicate labels.

**Comment by hanjoosten** [comment]
The compiler will warn you from now on.

**Comment by Michiel-s** [comment]
Fixed by #1179

**Comment by Michiel-s** [comment]
@hanjoosten you've implemented a warning for this situation? Why not a hard exception? I cannot think of a reason why we need two view data elements with the same key. In the prototype framework the value of the latter will overwrite the former anyhow.

**Comment by stefjoosten** [comment]
> @hanjoosten you've implemented a warning for this situation? Why not a hard exception? I cannot think of a reason why we need two view data elements with the same key. In the prototype framework, the value of the latter will overwrite the former anyhow.

@Michiel-s I can think of that reason. In the example above the labels don't matter so there is no reason to forbid duplicate labels. In Ampersand we want to allow things as much as possible. The argument "I cannot think of a reason why we need two view data elements with the same key" is not valid in Ampersand because we don't need a reason for allowing things.

The real reason for this issue lies in the implementation. The prototype framework cannot cope with it, so we want to forbid it.

**Comment by stefjoosten** [comment]
I think we can close this issue, because it was merged in PR #1202

**Comment by Michiel-s** [comment]
If the labels don't matter (i.e. you don't use a custom template where you refer to them) then just leave them out:
```adl
VIEW "Relation": Relation DEFAULT
   { name[Relation*RelationName]
   , TXT "["
   , source;name
   , TXT "*"
   , target;name
   , TXT "]"
   }
ENDVIEW
```

We also don't allow duplicate labels in `INTERFACES`. And because interfaces and views are more of the same (see #133), for the sake of consistency, I would opt to forbid duplicate labels.

As far as I understood, #1202 implemented a warning (outputted to the console) and not forbids duplicate labels. @hanjoosten, @stefjoosten, I'll let you decide what to do.

**Comment by hanjoosten** [comment]
In VIEW statements, the label is optional according to the current implementation. The PR #1202  that I merged into development this morning will cause an error when there are two or same labels.

**Comment by hanjoosten** [comment]
An example of such a statement can be seen in https://github.com/AmpersandTarski/Ampersand/blob/development/testing/Travis/testcases/prototype/ISAtest/ISAtest2.adl#L48

**Comment by RieksJ** [comment]
Sometimes, labels are not needed, e.g. when the 'content' is a text (as in the example provided by this issue). I suggest to forbid duplicate labels only for fields in which the value comes from an expression, and disregard names (if present at all) that appear for 'fields' that have fixed texts.

**Comment by hanjoosten** [comment]
> Sometimes, labels are not needed, e.g. when the 'content' is a text (as in the example provided by this issue). I suggest to forbid duplicate labels only for fields in which the value comes from an expression, and disregard names (if present at all) that appear for 'fields' that have fixed texts.

This issue is closed, and by now merged into development. Either this comment doesn't make sence, or I do not understand what you mean by this. Feel free to play around with the new implementation. If you have a concrete example where the error hinders you, feel free to raise a new ticket for that.

**Comment by Michiel-s** [comment]
I think it is good now. The curly bracket syntax `{ ... }` is introduced for VIEWs that have a template. The much older VIEW syntax with parentheses `( ... )` can be used for views where only the label is used. Both is supported now!

**Comment by stefjoosten** [comment]
In (a subset of) interfaces, duplicate field labels are forbidden only for an implementation reason: We use the label to select the appropriate field. The user interface presents those fields in the same order as the Ampersand source code. So one might just as well state that all fields are selected based on the order they have in the source code. (Implementation by numbering the fields rather than selecting field names). This definition has the advantage that labels are now devoid of any semantics, so we can use them exclusively for presentation purposes (separation of concerns).  Another advantage is that the definition holds for all interfaces with no strings attached.
