### ISSUE TITLE
Rework on issue 260

### ISSUE THREAD

**Issue by stefjoosten** [AmpersandTarski/Ampersand#1182]
# What happened
I got an unexpected error on the following script
<img width="741" alt="afbeelding" src="https://user-images.githubusercontent.com/275768/121885578-9c48f880-cd14-11eb-8d00-89775e53ba79.png">
However, the error can be resolved as follows:
<img width="741" alt="afbeelding" src="https://user-images.githubusercontent.com/275768/121884332-18424100-cd13-11eb-9f75-fe282034bd5a.png">

# What I expected
I expected the compiler to accept this script because `2` is a valid integer.

# Analysis
It may not seem a big thing, but issues arise from under the surface wrt Quickcheck.

The writer of an Ampersand-lexer has a problem with atoms. In Ampersand they can be strings, integers, floats, dates, negative integers, etcetera. The lexer must distinguish `-34` (an integer) from `-r[A*B]` (where `-` is a prefix operator). That's hard given the possibilities that must be checked. Apparently, Ampersand uses information from the `REPRESENT` statement to tell the lexer how to parse an atom. This relates to issue #713.

Of course, the Ampersand programmer has a workaround with the `REPRESENT` statement. However, this workaround does not work for the writer of Quickcheck-tests. He should avoid writing numbers as atoms if he wants to avoid this error to pop up. Obviously, that is a VERY undesirable situation, because this affects the completeness of Quickcheck-tests.

This looks very similar to issue #260, which was fixed in commit 395fc96eb by @sjcjoosten on 22 Jan 2016 at 11:55. I think we have rework here...

# Context / Source of ampersand script
```
CONTEXT Issue IN ENGLISH

POPULATION C CONTAINS [2]

ENDCONTEXT
```

I found this error when working on issue #1163.

**Comment by sjcjoosten** [comment]
I thought the choice to have concepts be of type Object by default was deliberate.

If so, the error message is correct (for reasons explained in the message) and we should not be fixing issues we have with quick-check by changing the behavior of what our users face. If the error is a fatal (as suggested in the old title), then of course we should still fix that. Is the error a fatal? If so, would turning the fatal into a proper message fix the issues you face with Quick-check?

I'd be in favor of changing the way our Quick-check generator works, such that we can generate atoms that are numbers as well as atoms that are not. I don't believe changing the Ampersand language is the route to take here. Perhaps you can explain the Quick-check issue?

**Comment by sjcjoosten** [comment]
When I look at the error message of this page https://github.com/AmpersandTarski/Ampersand/runs/2819724540
it seems like the error arises on the first occurrence of `"` on the line:
```
{-0232-} POPULATION XM3 CONTAINS ["","0M","<",""]
```

Since XM3 does not occur elsewhere in the script, the type of XM3 is implicitly 'Object' and the error is unlikely to be caused by a missing REPRESENT statement. If you are trying to get CI to pass, the root cause might lie elsewhere.

**Comment by hanjoosten** [comment]
Do we allow the empty string to be an atom? We used to do so, but one of the commits of @stefjoosten today might have broken that.

**Comment by stefjoosten** [comment]
I think an empty string can be an atom, but it cannot be a label (of an interface, rule, etc.).

**Comment by hanjoosten** [comment]
The parser round-trip is what we aim to test with QuickCheck. There must be no typechecking involved there.

**Comment by stefjoosten** [comment]
> I thought the choice to have concepts be of type Object by default was deliberate.
> 
> If so, the error message is correct (for reasons explained in the message) and we should not be fixing issues we have with quick-check by changing the behavior of what our users face. If the error is a fatal (as suggested in the old title), then of course we should still fix that. Is the error a fatal? If so, would turning the fatal into a proper message fix the issues you face with Quick-check?
> 
> I'd be in favor of changing the way our Quick-check generator works, such that we can generate atoms that are numbers as well as atoms that are not. I don't believe changing the Ampersand language is the route to take here. Perhaps you can explain the Quick-check issue?

I don't understand this answer. It seems to me that the lexer should pick up one atom at a time, whether it is a number, a password, a float, a datetime, or whatever. It is the job of a type checker to say that a number is incorrect if a string is wanted. The error, however, does not come from the type checker.

By the way, the error is not a fatal. It is generated by Ampersand (as it should).  Today I ran into a similar thing:
```
Starting Quickcheck tests.
❗❗❗ ERROR: There is something wrong with the parser and/or with the
           way an arbitrary P_Context is defined. (See ArbitraryTree.hs)
           Below file at position:33:35 error:
             way an arbitrary P_Context is defined. (See ArbitraryTree.hs)
             Below file at position" (line 33, column 35):
  unexpected float 0.36829616652026353
  expecting symbol '(' or symbol ']' :| []
```
I'm sure it has to do with my fiddling around in Quickcheck. I noticed that there are discrepancies between the Quickcheck code and the parser. I'm studying the code but I cannot figure out what is going on... (yet)

**Comment by stefjoosten** [comment]
I'm stopping work on issue #1163 for now. I'm convinced that I tripped into a can of worms. My conclusions:
1. The Quickcheck modules need refactoring. I'll make a new issue for that. I see this as technical debt.
2. The problem with leaving issue #1163 unsolved is not a big problem, and I have other priorities.
3. I'll place a tag on this branch and delete the branch, so we can pick it up some day in Everland.
4. I'm also closing this issue. When work resumes we can reopen it.

**Comment by sjcjoosten** [comment]
> I don't understand this answer. It seems to me that the lexer should pick up one atom at a time, whether it is a number, a password, a float, a datetime, or whatever. It is the job of a type checker to say that a number is incorrect if a string is wanted. The error, however, does not come from the type checker.

My answer was in response to the top first post, in which you complain about an error that comes from the type checker.
