### ISSUE TITLE
Feature Request: {+ +} notation in concept definition.

### ISSUE THREAD

**Issue by stefjoosten** [AmpersandTarski/Ampersand#1183]
# The feature
Currently, we may write texts in `PURPOSE` and `MEANING` statements with the `{+ +}`-notation. For example:
```
MEANING
{+ This defines the meaning of `foo` in natural language. +}
```
In a concept definition I would like to do the same:
```
CONCEPT Foo
MEANING
{+ This defines the meaning of `Foo` in natural language. +}
```

# Motivation
This makes life easier for longer meanings. Sometimes I want to elaborate a little on a meaning, or even combine it with purposeful remarks. The fact that it is a string (in the current syntax) forces me to keep it short. And sometimes too short. I don't mind being forced to keep it short, but not by a computer!
Besides, it is nice that the same mechanism (the `{+ +}`-notation) is available in similar situations. Currently, it is available for meanings, but not for concept definitions.

# Proposal
The following syntax yields upwards compatibility:
```EBNF
ConceptDef
  ::= 'CONCEPT' Id ( 'MEANING' LanguageRef? TextMarkup? Expl
                   | String String? )
```

# Details
For reasons of upward compatibility, a user may write the old syntax or the new syntax, but not a mixture. So both of the following concept definitions are allowed:
```Ampersand
CONCEPT Foo "part 1 of the meaning in natural language." "reference"

CONCEPT Foo
MEANING
{+ This defines the meaning of `Foo` in the new syntax. +}
```
This has the additional advantage that the user can specify language and markup:
```Ampersand
CONCEPT Foo
MEANING IN ENGLISH MARKDOWN
{+ This defines the meaning of `Foo` in the new syntax. +}
```

**Comment by RieksJ** [comment]
Remaining fully backward compatible should be a MUST.
So syntax: CONCEPT "RequiredConcept" "optional one-line definition" "optional ref" {+optional other stuff+}
where quotes around 'RequiredConcept' are optional if it does not include whitespace.

**Comment by hanjoosten** [comment]
I had a talk with @stefjoosten the other day about this request. In order to have a somewhat logical syntax, we concluded that we would add an optional MEANING part to the CONCEPT statement, like we allready have in the RELATION statement and the RULE statement. I will take a shot at the implementation of this.

**Comment by stefjoosten** [comment]
This comment 

I have tested with Ampersand-v4.1.5 [feature/Issue1183:5bb9e818d*]. I made [a test file](https://github.com/AmpersandTarski/Ampersand/blob/feature/Issue1183/testing/Travis/testcases/FuncSpec/testIssue1183.adl) with the following contents:
```Ampersand
CONTEXT TestIssue1183

PATTERN FOO
CONCEPT A123  "string 1"  "ref"
MEANING {+ string 2 +}

CONCEPT A123L  "string 1"  "ref"
MEANING LATEX {+ string 2 +}

CONCEPT A13  "string 1"
MEANING {+ string 2 +}

CONCEPT A13L  "string 1"
MEANING LATEX {+ string 2 +}

CONCEPT A12  "string 1"  "ref"

CONCEPT A1  "string 1"

CONCEPT A123  "string 3"  "ref"
MEANING {+ string 4 +}

RELATION foo[A123 * A123L]
RELATION foo[A133 * A13L]
RELATION foo[A1 * A12]
ENDPATTERN

ENDCONTEXT
```
The following statements are not allowed, but I would like them to be allowed
```Ampersand
CONCEPT A3
MEANING {+ string 5 +}

CONCEPT A3L
MEANING LATEX {+ string 6 +}
```
To make that happen, we'll have to sacrifice a little syntax. I propose we introduce the keyword `REF` for the reference bit. The best way is to make it as much as `PURPOSE` and `MEANING` as we can. In that case, the original file must be adapted to:
```Ampersand
CONTEXT TestIssue1183

PATTERN FOO
CONCEPT A123  "string 1" 
MEANING REF "ref"
{+ string 2 +}

CONCEPT A123L  "string 1"
MEANING LATEX REF "ref" {+ string 2 +}

CONCEPT A13  "string 1"
MEANING {+ string 2 +}

CONCEPT A13L  "string 1"
MEANING LATEX {+ string 2 +}

CONCEPT A12  "string 1"
MEANING REF "ref"

CONCEPT A1  "string 1"

CONCEPT A123  "string 3"
MEANING  REF "ref" {+ string 4 +}

RELATION foo[A123 * A123L]
RELATION foo[A133 * A13L]
RELATION foo[A1 * A12]
ENDPATTERN

ENDCONTEXT
``` 
It means that we get the syntax:
```EBNF
ConceptDef ::= 'CONCEPT' Id String? 'MEANING' LanguageRef? TextMarkup? ('REF' String)? Expl?
```
This is **NOT** upwards compatible in the syntax. I just hope that Rieks is not in the habit of writing references in his `CONCEPT` statements. Maybe @RieksJ can comment on whether he can live with this. Then I'll make a decision on whether this is a good idea. Personally, I think the extra functionality (documenting concepts with language and markup is worth it.

**Comment by stefjoosten** [comment]
> Remaining fully backward compatible should be a MUST.
> So syntax: CONCEPT "RequiredConcept" "optional one-line definition" "optional ref" {+optional other stuff+}
> where quotes around 'RequiredConcept' are optional if it does not include whitespace.

Consider it done. The current proposal is fully upwards compatible.

**Comment by RieksJ** [comment]
Happy to see this is backwards/upwards compatible.

**Comment by stefjoosten** [comment]
It is not quite done yet. The following script doesn't compile while it should:
```Ampersand
CONTEXT TestIssue1183

PATTERN Foo
CONCEPT Foo
MEANING IN ENGLISH MARKDOWN REF "reference"
{+ This defines the meaning of `Foo` in the new syntax. +}
ENDPATTERN

ENDCONTEXT
```
This results in:
```bash
sjo00577@BA92-C02T81JCGTDY FuncSpec % ampersand documentation --format docx testIssue1183.adl
/Users/sjo00577/git/Ampersand/testing/Travis/testcases/FuncSpec/testIssue1183.adl:5:29 error:
  unexpected keyword "REF"
  expecting double quoted string or markup
ExitFailure 10
sjo00577@BA92-C02T81JCGTDY FuncSpec % 
```

Secondly, the following script compiles while it shouldn't, because it is in mixed syntax:
```Ampersand
CONTEXT TestIssue1183

PATTERN Foo
CONCEPT A123L  "string 1"  "ref"
MEANING LATEX {+ streng 2 +}
ENDPATTERN

ENDCONTEXT
```
It allows the mixed syntax, but semantically (in the generated documentation) it seems to "prefer" the old syntax:
![image](https://user-images.githubusercontent.com/275768/124395341-e580dc80-dd03-11eb-849e-5643614f434f.png)

**Comment by hanjoosten** [comment]
I see no reason why this issue is reopend. If there is a reason, please either make clear what still has to be done. Maybe even better to file a fresh issue for that.
