### ISSUE TITLE
Feature request: DEFAULT SRC/TGT atoms for RELATION statement

### ISSUE THREAD

**Issue by Michiel-s** [AmpersandTarski/Ampersand#1189]
## Context
Working with Ampersand prototype in practices, I recognize that often I add an exec-engine rule to fill a default tuple for a relation when a new src or tgt is instantiated. This holds in particular for [reification](https://en.wikipedia.org/wiki/Reification_(computer_science)) of relations. Let me give an example:

Suppose I have a `membership` relation between `Person` and `Project`. Now I want to register the `role` and `startdate` for that `membership`. What I do is I reify the `membership` relation into a `Membership` concept like this:

```adl
CONCEPT ProjectMembership ""
RELATION person[ProjectMembership*Person] [UNI,TOT]
RELATION project[ProjectMembership*Project] [UNI,TOT]
```
And then I add the additional data requirements, like this:
```
RELATION role[ProjectMembership*Role] [UNI,TOT]
RELATION startdate[ProjectMembership*DateTime] [UNI,TOT]
```

## Problem statement
A problem now is that I have to deal with the two new functional relationships and provide editable fields in the UI to allow for new ProjectMemberships to be created.
However, the start date can be filled automatically and the role can have a default value (e.g. 'Participant', 'Projectleader').

Then I create a new exec-engine rule to fill those in, like this:
```adl
ROLE ExecEngine MAINTAINS "Set default role for new ProjectMemberships"
RULE "Set default role for new ProjectMemberships": I[ProjectMembership] |- role;role~
VIOLATION (TXT "{EX}InsPair;role;ProjectMembership;", SRC I, TXT ";Role;Participant")

ROLE ExecEngine MAINTAINS "Set tsAdded for new ProjectMemberships"
RULE "Set tsAdded for new ProjectMemberships": I[ProjectMembership] |- tsAdded;tsAdded~
VIOLATION (TXT "{EX}InsPair;tsAdded;ProjectMembership;", SRC I, TXT ";DateTime;{php}date(DATE_ISO8601)")
```

This requires additional queries (=performance) to check/verify these rules and more boilerplate code in the ADL files.

## Feature request
How about allowing to specify default src/tgt values at the relation definitions, e.g.

```adl
RELATION role[ProjectMembership*Role] [UNI,TOT] DEFAULT TGT "Participant"
```
This means that when a ProjectMembership is instantiated, by default the pair ("<new ProjectMembership>","Participant") is populated in the relationship.

Both default SRC and TGT can be specified, e.g.:
 ```
RELATION role[ProjectMembership*Role] [UNI,TOT] DEFAULT SRC "Test" TGT "Participant"
```
In this case, additionally, if a new Role is instantiated, the Test project is bound.

## Allow for defaults by the exec-engine
To support the case where the current date timestamp needs to be inserted, I propose to accept also TXT statements that can be parsed by the exec-engine just like with the rule violations. Like this:

```adl
RELATION tsAdded[ProjectMembership*DateTime] DEFAULT TGT TXT "{EX}{php}date(DATE_ISO8601)"
```
Note the TXT in between. This is the same as we do in the VIOLATION and INTERFACES statements.
This allows for flexibility.

## Considerations
* I think it is best to NOT add the specified atoms in the default statements to the default population of a script.

**Comment by Michiel-s** [comment]
@hanjoosten, what do you think? Any idea about implementation effort?

I think the output is best added to the relations.json like so:

```json

{
        "affectedConjuncts": [],
        "inj": false,
        "mysqlTable": {
            "name": "ProjectMembership",
            "srcCol": {
                "name": "ProjectMembership",
                "null": false,
                "unique": true
            },
            "tableOf": "src",
            "tgtCol": {
                "name": "tsAdded",
                "null": true,
                "unique": false
            }
        },
        "name": "tsAdded",
        "prop": false,
        "signature": "tsAdded[ProjectMembership*DateTime]",
        "srcConceptId": "ProjectMembership",
        "sur": false,
        "tgtConceptId": "DateTime",
        "tot": true,
        "uni": true,
        "defaultSrc" : null,
        "defaultTgt" : "{EX}{php}date(DATE_ISO8601)"
    },
```
See fields `defaultSrc` and `defaultTgt`. No needs to distinguish between Atoms or TXT statements. If it starts with {EX} then the exex-engine kicks in (just like with VIOLATION statements). Otherwise the value is considered an Atom.

**Comment by hanjoosten** [comment]
This is an interesting idea. However, since it is an addition to the syntax of Ampersand, we have to be careful. In general, syntax is added easily, but removal of it is hard. 

That said, here are some initial thoughts about this proposal:

- We need to have @stefjoosten on board.
- I see no need to specify the concepts again in the DEFAULT part. Maybe because I am confused by your example. Did you make a typo there: ?

~~~
RELATION role[ProjectMembership*Role] [UNI,TOT] DEFAULT SRC "Test"[Project] TGT "Participant"[Role]
~~~
 
- We have to take care of the typechecker too: We have to check that the TYPE of the concept and the given value match. 
- The extention to `relations.json` is very much the least part of the implementation.

**Comment by RieksJ** [comment]
While I can see that this could be useful, I'm not convinced that this is a serious problem. Of course, there is additional queries and boilerplate code here, but if that is going to be a real problem, then my guess is there are lots of other problems as well. 

More to the point perhaps, it isn't clear (yet) what 'DEFAULT' means. 
- It could mean 'initial', which means that when the relation is populated, then so is its SRC or TGT value, and (if the relation isn't TOT) then depopulation wouldn't lead to a re-initialization. 
- It could also mean 'when there is no population', which obviously is the case straight after the creation of the relation, but also when the relation is completely depopulated. 
- What should happen if the value with which the SRC/TGT atom is to be filled doesn't exist, e.g. if it is an expression? Would that lead to continuous attempts to write it (consuming CPU cycles)? And what if the expression is populated? And what if the expression isn't necessarily UNI?
- And then there is the database creation, where it matters if the DEFAULT is executed before or after installing the (default) population. 

Also, default values are not always that simple. Consider the following:
~~~
CLASSIFY Person, Organization ISA Party
claimPhoneNr :: Claim * PhoneNr  -- 'Claim' is a case in which a party (person or organization) claims some damages.
claimHolder :: Claim * Party [UNI,TOT]  -- the party that has entered the claim and wants it processed.
personPhoneNr :: Person * PhoneNr -- phone number by which the Person can be reached.

ROLE ExecEngine MAINTAINS "InsPair claimPhoneNr "
RULE "InsPair claimPhoneNr ": (I-claimPhoneNr ;claimPhoneNr ~);claimHolder;personPhoneNr |- claimPhoneNr 
VIOLATION (TXT "{EX} InsPair;claimPhoneNr ;ClaimCase;", SRC I, TXT ";PhoneNr;", TGT I)
~~~
Here, initialization of `claimPhoneNr` is initialized _conditionally_, i.e. only if `claimHolder;personPhoneNr` exists. Do we need to instruct developers that they cannot use `DEFAULT` for this?

**Comment by Michiel-s** [comment]
@hanjoosten, you're right, I made a mistake, the line I meant is: `RELATION role[ProjectMembership*Role] [UNI,TOT] DEFAULT SRC "Test"[ProjectMembership] TGT "Participant"[Role]`

**Comment by Michiel-s** [comment]
@RieksJ, I think you are missing the point here. It is not about when RELATIONs are populated, but how to populate certain relations when either the src or tgt atoms are inserted in the CONCEPT population.

I recognize that the default values are not always that simple; for situations that require a more complex expression, the regular way using the exec-engine still works.
My issue/proposal here is to add syntax for those situations where a simple default value is applicable. Like you can specify in [database schema constructs](https://mariadb.com/kb/en/default/).

In reaction to specific questions:
> What should happen if the value with which the SRC/TGT atom is to be filled doesn't exist, e.g. if it is an expression? 

I think we shouldn't allow expressions, only atom values (singletons) or TXTs that can be processed by backend (incl. exec-engine).

> And then there is the database creation, where it matters if the DEFAULT is executed before or after installing the (default) population.

DEFAULTS as I propose them now are directly inserted after inserting a new atom.

**Comment by RieksJ** [comment]
Thanks for clarifying. I'm still not convinced though that the benefits of having it outweigh the trouble of implementing and maintaining it. 

I'm also not sure I understand the actual problem that you are trying to solve: 
- In the first line of the problem statement, you say "A problem now is that I have to deal with the two new functional relationships and provide editable fields in the UI to allow for new ProjectMemberships to be created." I'm quite sure that is _not_ the problem at hand. 
- If performance is the issue, I'd like to see data to underpin that there's really some significant improvement to be gained e.g. when initializing an application (but even then, you do this once and it's gone), or what a user would notice when he creates some atom. From what I see in logfiles, I have trouble imagining any significant improvements, but I'm open to other data.
- If the amount of boilerplate code is the issue, I'd like to see who had actual trouble with that, or where actual trouble might arise in the (near) future. And why the suggested feature would resolve that issue better than anything else.
- If developer effort is the issue (i.e. developers do not want to write the associated exec-engine rule), then there is significantly much more to be gained by implementing the EQV construct as I mentioned earlier.

**Comment by hanjoosten** [comment]
@RieksJ , I guess that the issue you couldn't find is https://github.com/AmpersandTarski/Ampersand/issues/311. The value of that issue is higher than this issue, however the estimated implementation effort is much higher as well. 
For your understanding: The default for this issue can be thought of as similar to the [default in SQL statements](https://www.w3schools.com/sql/sql_default.asp). However, the intention here is to implement it not at the database level, but at the frontend level. This has no effect at all for the initial population, but it effects runtime behaviour.

**Comment by sjcjoosten** [comment]
Having defaults at the frontent level is a great idea and that's also where they belong. I predict that we'll want different defaults for different interfaces soon, but that's all to be part of #311 and this could be a more manageable small step.

For syntax, I observe that this ties to the TOT (or SUR) rule that is implicitly created in the declaration of the relation. One could imagine having some notation to indicate which atoms to use for any existential quantifier (the implicit \exists that arise at ;), but that would be a big step instead of a small step, seeing this work first might make it easier to think of how to do that big step too. I also have no idea on how to make the connection with the TOT rule more visible in the syntax, so I'm happy to go with what is proposed.
I do suggest dropping the 'TXT' token in the syntax of ``DEFAULT TGT TXT "{EX}{php}date(DATE_ISO8601)"``. If you wish to only allow atoms, then there is no need for TXT: there are equally many occurrences of 'TXT' in the VIOLATION statement that this proposal tries to mimic.

**Comment by RieksJ** [comment]
Since default values are going to be simple values, we could perhaps go for syntax such as `[UNI, TOT, SRC="somevalue"]` which would suggest there's a multiplicity relation implied. 

Syntax such as `[UNI, TGT=EVAL(date(DATE_ISO8601)]` might be used to specify the result of a function as a default value (which I think is appropriate).

**Comment by hanjoosten** [comment]
Glad you give the syntax some thought too. However, the place you suggest for the default values is a list of properties, which in fact are restrictions on the population of the relation. The default values for atoms are something else. So we start with the keyword "DEFAULT". this will be followed by an optional SRC part, then an optional TGT part. 
The SRC and TGT parts are identical, exept for their keywords. 

After the keyword we will expect either:

- a value of an atom, which will be typechecked to match the TYPE of that relation. 
- the keyword EVAL, followed by a double-quoted string that could be processed by the exec-engine

Some examples:

~~~
RELATION role[ProjectMembership*Role] [UNI,TOT] DEFAULT TGT "Participant"

RELATION membership[Project*ProjectMembership] [INJ,SUR] DEFAULT SRC "Test"

RELATION startdate[ProjectMembership*DateTime] [UNI,TOT] DEFAULT TGT EVAL "{php}date(DATE_ISO8601)"
~~~
 
notes:

1. The optional DEFAULT part will be **after** the optional property list, and **before** the optional PRAGMA part. 
2. If the relation is declared multiple times (for example in different files) an error will be raised if the defaults in those statements conflict with each other.
3. The prefix `{EX}` is not part any more of this syntax. If used, the exec-engine is likely to choke on it.

**Comment by RieksJ** [comment]
I know that the place I suggest is in the existing list of properties, thereby following up on the remark by @sjcjoosten who stated that having a default value _implies_ such properties. If (not saying: 'when') we follow up on that remark, would it make more sense to consider syntax such as `[INJ, SUR="src-value", TOT="tgt-value"]`? 

I appreciate that having separate syntax as you suggest is easier to implement, and that could be a valid consideration too.

**Comment by hanjoosten** [comment]
Ah, good point. I didn't get that before. If we go this way, it seems to me we could also skip the keywords `DEFAULT`, `SRC` and `TGT`.  The properties TOT and SUR will then get an optional part, being either the value of an atom or the keyword `EVAL` followed by a string. My earlier examples would then be denoted as:

~~~
RELATION role[ProjectMembership*Role] [UNI,TOT "Participant" ] 

RELATION membership[Project*ProjectMembership] [INJ,SUR "Test"]

RELATION startdate[ProjectMembership*DateTime] [UNI,TOT EVAL "{php}date(DATE_ISO8601)"]
~~~
Notes: The value given with TOT is by definition ment to populate the target concept, and the value given with SUR is by definition ment for the source concept. Hence, there is no need for a specific keyword.

I like this idea. What do @Michiel-s , @sjcjoosten and @stefjoosten think ?

**Comment by hanjoosten** [comment]
I am not sure about the amount of work of implementing Rieks's idea vs my initial idea. I will give that a thought, but beside of that, I would like to know what the others like most.

**Comment by sjcjoosten** [comment]
What I like is that this ties in very well with the UNI/TOT rules. I also very much like changing the prefix "{EX}" within the string to a keyword EXEC. What I dislike is that it encourages defaults to be specified at the place in the script where RELATIONs are declared: the conceptual model is conceptually far away from tweaking interface behavior so it would be nice if the syntax would naturally separate the two as well. If I as a modeler decide to change a relation to no longer have TOT, I'd like to see a warning/error about the DEFAULT rule I wrote in another file (and not have a DEFAULT rule add the TOT property back because of syntax).

Given these likes and dislikes, I'd say let's go with the EXEC idea regardless. Apart from that, the two are about equal to me.

**Comment by hanjoosten** [comment]
This issue very much relates with the implementation of the ENFORCE statement (Issue #1204). This is currently in the review phase, and I expect it to be into development shortly. 
I expect that the new implementation of the ENFORCE statement has made it quite easy to implement the ideas I wrote down in in [this comment earlier](https://github.com/AmpersandTarski/Ampersand/issues/1189#issuecomment-879750460).

@Michiel-s , Do you think such syntax will solve your original problem?
@stefjoosten , can you bless that syntax?

**Comment by hanjoosten** [comment]
Just for a refference, I now think the syntax boils down to:

~~~.ebnf
Property
    ::= ("SUR" | "TOT") ( '<AtomValue>' | "EVALPHP" '<DoubleQuotedString>')?
      | ("ASY" | "INJ" | "IRF" | "PROP" | "RFX" | "SYM" | "TRN" | "UNI") 
~~~
Which can be [visualized](https://bottlecaps.de/rr/ui) as
![image](https://user-images.githubusercontent.com/1159672/132169054-91a63860-bcef-44ce-a580-ea0cffc06b03.png)

Some notes:

1. I'd rather have a keyword `EVALPHP`, not `EVAL`. Then the modeller is not required to prefix the `DoubleQuotedString` with `{php}`. If required by the backend, the generator will take care of that. This leaves room for other keywords, depending on the language supported by the backend.
2. Also note the `AtomValue`. The provided value will be typechecked against the TTYPE of it's Concept.
3. The typechecker will check that no different default values are given, even when the RELATION is declared multiple times.
4. When using the "EVALPHP" keyword, the user is on it's own to make sure that the type is correct.

**Comment by hanjoosten** [comment]
I just had a chat with @stefjoosten . He suggested to enable the use of an expression, at the place where the atomvalue can be given. So we still need some more thinking of the syntax.

**Comment by sjcjoosten** [comment]
I like the idea of allowing an expression in the place of '<AtomValue>'.
I believe that the expression corresponding to '<AtomValue>' is also '<AtomValue>'.
In other words, if we compare these two syntaxes:

```.ebnf
Property
    ::= ("SUR" | "TOT") ( '<AtomValue>' | "EVALPHP" '<DoubleQuotedString>')?
      | ("ASY" | "INJ" | "IRF" | "PROP" | "RFX" | "SYM" | "TRN" | "UNI") 
```
(Han's earlier proposal)

and:
```.ebnf
Property
    ::= ("SUR" | "TOT") (Expression | "EVALPHP" '<DoubleQuotedString>')?
      | ("ASY" | "INJ" | "IRF" | "PROP" | "RFX" | "SYM" | "TRN" | "UNI") 
```

then the second would subsume the first. We might be inclined to think that building the first of these two will not hinder us from ever building the second of these two. That suggests, however, that the type of Expression and the type of '<AtomValue>' will match, and I think they might not.

For ``r :: A * B [TOT]``, I believe the type of Expression should be ``A * B'``, where ``B'`` denotes that ``B`` may be generalized to allow for new concepts to be inserted. The ``A`` is there so that all violations of the ``TOT`` rule (these are of type ``A*A``) can each get their own atom from ``B'``: without ``A`` we cannot make such distinctions. Here's an example use (using expression syntax as above):

```.ampersand
company :: Account * Company [UNI, TOT EVALPHP '"getSessionCompany()"'] -- every account belongs to a company, the getSessionCompany() is custom-built for this application
defaultAccount :: Company * AccountType -- allow companies to set a default account type
accountType :: Account * AccountType [TOT company;defaultAccount]
```

The generalization of ``B`` is tricky: we might want things to be inserted that don't belong to any concept yet, i.e. that aren't properly typed Atoms. For that reason, I'd suggest to implement this in steps, i.e. deal with expressions (and possibly EVALPHP) later. Regardless of when we implement what, what would the equivalent to ``'<AtomValue>'`` look like as an expression? It would be ``V[A*B'];'<AtomValue>'`` (user would need to write ``V;'AtomValue'`` because ``B'`` might not be a concept. That's already different from a plain ``'<AtomValue>'``. For this reason, it could be a good idea to give expressions and atom-values a keyword, just like `EVALPHP`, so we can separate them.

**Comment by RieksJ** [comment]
What  happens when`defaultAccount` has 2 tgt atoms for a single sec atom?

**Comment by sjcjoosten** [comment]
> Cool! But what happens when`defaultAccount` has 2 tgt atoms for a single sec atom?

Good question! I can think of only one kind of behavior, which is consistent with what the exec-engine would do: both defaults would get inserted. If ``accountType`` is additionally ``UNI`` (while ``defaultAccount`` is not) then this could result in a bug that is horribly difficult to debug violation of its ``UNI`` rule, but perhaps we'll see some decent feedback as these defaults float to the interface.

**Comment by RieksJ** [comment]
I agree that this should be the behaviour.

Regarding error messages, I can see that in an implementation, such exceptions could somehow be caught and the necessary guidance for helping out the developer out could be added. One way would be to handle ENFORCE statements (and thereafter any associated UNI/INJ checks - but also any SUR/TOT checks, because there is also no guarantee that there will be a TGT atom - in a designated context (we used to call a SERVICE), which has its own execengine run and error message generation.

**Comment by hanjoosten** [comment]
@sjcjoosten , good point, allowing an `<Expression>` too does require a keyword to separate the `<Expression>` from the `<AtomValue>`. Indeed, it makes sence that when an `<Expression>` is used, the source of that expression should match the atom that causes the violation. So we need some keyword in front of the `<AtomValue>`.

Having said that, there is more to think about w.r.t. the `<Expression>`. Your example of `V;<AtomValue>` will not work as one might expect, unless `<AtomValue>` is already an element of the population of the target concept (See issue #166). I think that eventually we might agree on some type of behaviour for the `<Expression>` part, but that needs more thinking. (And we currently have an alternative for the expression). I propose not to implement the `<Expression>` part right now, leave that for sometime later. Only ensure we will then be backwards compatible by introducin some keyword in front of the `<AtomValue>` part:
~~~.ebnf
Property
    ::= ("SUR" | "TOT") ( "VALUE" '<AtomValue>' | "EVALPHP" '<DoubleQuotedString>')?
      | ("ASY" | "INJ" | "IRF" | "PROP" | "RFX" | "SYM" | "TRN" | "UNI") 
~~~

which can be [visualized](https://bottlecaps.de/rr/ui) as
![image](https://user-images.githubusercontent.com/1159672/132298985-c692333b-0aba-4879-8818-f08d3b82b75f.png)

**Comment by RieksJ** [comment]
I suggest
~~~
Property
    ::= ("SUR" | "TOT") ( "VALUE" '<AtomValue>' | "EVALPHP" '<DoubleQuotedString>' | "EXPR" <expression> )?
      | ("ASY" | "INJ" | "IRF" | "PROP" | "RFX" | "SYM" | "TRN" | "UNI") 
~~~

**Comment by sjcjoosten** [comment]
> Having said that, there is more to think about w.r.t. the `<Expression>`. Your example of `V;<AtomValue>` will not work as one might expect, unless `<AtomValue>` is already an element of the population of the target concept

I was thinking of this when I wrote that the generalization of ``B`` is tricky, but we can generalize it all the way to its Ttype. I also like the VALUE keyword.

**Comment by hanjoosten** [comment]
@Michiel-s You have been quiet for a long time. Do you think this is going the right way?

**Comment by hanjoosten** [comment]
@RieksJ  wrote earlier:
> I would much rather have EQV constructs (I'm sure there has been an issue for this but I cannot find it any more), which computes the value of a relation as the contents of an expression, e.g. r EQV s;t /\ u;v.

This is done! See issue #1204. It is in development, will be released next friday.

**Comment by hanjoosten** [comment]
- [x] Add this feature in the Ampersand repository
- [ ] Add this feature in the Prototype repository

**Comment by hanjoosten** [comment]
@Michiel-s , I realized that the violation itself will probably be required, as well as the fact that in these cases there must be a `Role`. I added `ExecEngine` as `Role`.  See the branch called `feature/issue1189`.

**Comment by Michiel-s** [comment]
> @Michiel-s , I realized that the violation itself will probably be required, as well as the fact that in these cases there must be a `Role`. I added `ExecEngine` as `Role`.  See the branch called `feature/issue1189`. 

This is a comment regarding #1204 I think. Not for here

**Comment by Michiel-s** [comment]
> @Michiel-s You have been quiet for a long time. Do you think this is going the right way?

I really like this. I still have to take a look at the generated output in json files and implement the prototype framework part.

**Comment by Michiel-s** [comment]
> In the middle of the discussion you probably missed out. So let's see what can/should be done now
That's true, I didn't contribute to large part of the discussion, that's my bad.

1. Ok, let's discuss indeed. Maybe first by phone. We're almost working towards a 5.0 version of the compiler, so I would say this is the right moment. Btw, I don't think anybody has used this feature, as it doesn't have any affect in the prototypes yet. I agree that there is a purpose to have the default tight to the TOT/SUR rules, but that is a subset of the feature I proposed. My proposal is to keep the feature functionally, but change the implementation to have it also work for non-TOT and non-SUR relations.

2. Frontend (=UI), backend (= API + backend + database), exec-engine (= part of the backend). My intention is NOT about the frontend as you described, also NOT syntactical sugar for the exec-engine, but a functionality that the backend implementation can take care of.

3. I understand that there could be different TYPES that all need to be casted to a string. That's no problem. Escaping double quotes is needed (and also part of the json syntax spec) so after decoding the json file those are removed anyway. My issue here is that the value should only be the value. See example output below, the defaultSrc field contains: `AAVString {aavhash = 723817982351009968, aavtyp = OBJECT, aavtxt = \"test2\"}`.

```json
{
        "affectedConjuncts": [
            "conj_54",
            "conj_56"
        ],
        "defaultSrc": "AAVString {aavhash = 723817982351009968, aavtyp = OBJECT, aavtxt = \"test2\"}",
        "defaultTgt": "AAVString {aavhash = -4513705105538940906, aavtyp = OBJECT, aavtxt = \"test\"}",
        "inj": false,
        "mysqlTable": {
            "name": "r",
            "srcCol": {
                "name": "A",
                "null": false,
                "unique": false
            },
            "tableOf": null,
            "tgtCol": {
                "name": "B",
                "null": false,
                "unique": false
            }
        },
        "name": "r",
        "prop": false,
        "signature": "r[A*B]",
        "srcConceptId": "A",
        "sur": false,
        "tgtConceptId": "B",
        "tot": false,
        "uni": false
    },
```

**Comment by Michiel-s** [comment]
Hi @hanjoosten, I'm currently testing feature branch `feature/RelationDefaultValues_issue1189`.

1. Output in generated relation.json is good! I can work with that in the prototype framework.

2. Testing out the syntax in ADL doesn't look intuitive if you would ask me. What do you think? See below

E.g. this script is how it now looks like:
```adl
RELATION projectStatus[Project*Status] [UNI] TGT VALUE "In preparation" MEANING "The current status of a project according to the 4 stages described in our project management handbook"
```
Somehow to me the part `TGT VALUE "In preparation"` dangles. The props are nicely between brackets, the relation signature is the identifier paired with the keyword RELATION and the meaning is after the MEANING keyword.

My suggestion is to add the keyword DEFAULT:
```adl
RELATION projectStatus[Project*Status] [UNI] DEFAULT TGT VALUE "In preparation" MEANING "The current status of a project according to the 4 stages described in our project management handbook"
```

Using newlines this can look like:
```adl
RELATION projectStatus[Project*Status] [UNI] 
    DEFAULT TGT VALUE "In preparation"
    MEANING "The current status of a project according to the 4 stages described in our project management handbook"
```
This reads like "the default target value is ..." or if multiple, "the default target values are ..."

Furthermore I propose to add a comma `,` between the different default values. This is more in line with the syntax we have in VIOLATIONS, VIEWS, INTERFACE and POPULATIONS.

```adl
RELATION projectStatus[Project*Status]
    DEFAULT TGT VALUE "In preparation", TGT VALUE "New"
    MEANING "The current status of a project according to the 4 stages described in our project management handbook"
```

This results in:
`RelationDef ::= (RelationNew | RelationOld) Props? ('DEFAULT' Defaults)? ('PRAGMA' Text+)? Meaning* ('=' Content)? '.'?`
![image](https://user-images.githubusercontent.com/7961582/140185770-c2b4d895-71f3-42c6-8ecd-eca39baf1511.png)

and
`Defaults ::= ( 'SRC' | 'TGT' ) ( 'VALUE' '<AtomValue>' | 'EVALPHP' '<DoubleQuotedString>' ) ( ',' ( 'SRC' | 'TGT' ) ( 'VALUE' '<AtomValue>' | 'EVALPHP' '<DoubleQuotedString>' ) )*`
![image](https://user-images.githubusercontent.com/7961582/140187066-847a0e94-8220-4e1e-9a8d-b6ae7256aa90.png)


I tried to edit the parser myself to demonstrate what I propose, but I got stuck hopelessly. Really need your help, but I do want to learn.

**Comment by hanjoosten** [comment]
@Michiel-s , No sweat. This will be a relative easy change. It only affects the parser and prettyprinter. I would gladly help you do this yourself, during a pair programming session.

**Comment by sjcjoosten** [comment]
```
RELATION projectStatus[Project*Status]
    DEFAULT TGT VALUE "In preparation", TGT VALUE "New"
    MEANING "The current status of a project according to the 4 stages described in our project management handbook"
```

Not sure what the meaning is of two defaults?  I get how a project can get two statuses, so the example clarifies a lot, but my understanding is that ``EVALPHP`` will return a function that yields a list of values (for otherwise it won't be possible to have a default with an arbitrary number of elements, as one would for the ``RELATION position[CharAtPos*String] MEANING "The string at which a character occurs in a certain position. For example the String 'abc' will have character-positions (a,0), (b,1) and (c,2)."``). So what would be the meaning of ``DEFAULT TGT EVALPHP "f1", TGT EVALPHP "f2"``? Is there a compelling reason to take the union (or any other operation) here rather than use ``DEFAULT TGT EVALPHP "phpUnion(f1,f2)"``?

If not, perhaps the syntax could read ``DEFAULT TGT VALUE "In preparation", "New"``, to communicate more clearly that one has a set of values as a default (rather than that the computer will make some choice between different values):

```
Defaults ::= ( 'SRC' | 'TGT' ) ( 'VALUE' <AtomValue> | 'EVALPHP' <DoubleQuotedString> ) ( ',' ( 'SRC' | 'TGT' ) ( 'VALUE' <AtomValue> (',' 'VALUE' <AtomValue>)* | 'EVALPHP' <DoubleQuotedString> ) )*
```

**Comment by hanjoosten** [comment]
The idea here is quite simple: Since the relation is not restricted to be UNI, why then restrict the amount of defaults to one?

**Comment by sjcjoosten** [comment]
> The idea here is quite simple: Since the relation is not restricted to be UNI, why then restrict the amount of defaults to one?

I agree with this point (I should argue that we might even want to allow the default to be defined as zero). I was merely proposing to use the syntax ``DEFAULT TGT VALUE "In preparation", "New"`` to express this more clearly.

**Comment by hanjoosten** [comment]
Ah, I see. That leads us to something like 
~~~.ebnf
Defaults ::= ( 'DEFAULTS'
             ( 'SRC' | 'TGT' ) ( ('VALUE' '<AtomValue>' | 'EVALPHP' '<DoubleQuotedString>') (',' ('VALUE' '<AtomValue>' | 'EVALPHP' '<DoubleQuotedString>') )*)
       ( ',' ( 'SRC' | 'TGT' ) ( ('VALUE' '<AtomValue>' | 'EVALPHP' '<DoubleQuotedString>') (',' ('VALUE' '<AtomValue>' | 'EVALPHP' '<DoubleQuotedString>') )*))* )?
~~~
![image](https://user-images.githubusercontent.com/1159672/140335120-fc6330af-2d8b-4a7f-ad04-fed36eabe1ff.png)

**Comment by hanjoosten** [comment]
I see what you mean. I edited above syntax. This leaves us with the name of the keyword `DEFAULT` or `DEFAULTS` Maybe we should accept both.

There is no way that Ampersand itself knows what the result will be of the PHP expression. It could be a single atom, but it could be a set as well. @Michiel-s , can that become a problem? In any case, the modeler should know what she is doing.

**Comment by Michiel-s** [comment]
Yes no worries, if a eval returns a list, we have multiple defaults.

I like the simpler syntax proposal by @sjcjoosten to specify multiple values. Great!

**Comment by Michiel-s** [comment]
> This leaves us with the name of the keyword `DEFAULT` or `DEFAULTS` Maybe we should accept both.

My personal preference goes to DEFAULT (single). Because you default to a single or you default to a list of values. No need to specify plural option, which is not always, and most often not the case.

Other argumentation is possible of course. I wouldn't allow both, that's only for those who can't come to an understanding and I think we can😁

**Comment by stefjoosten** [comment]
Michiel said: "I think it is best to NOT add the specified atoms in the default statements to the default population of a script."
I agree. See issue #166

**Comment by sjcjoosten** [comment]
> > This leaves us with the name of the keyword `DEFAULT` or `DEFAULTS` Maybe we should accept both.
> 
> My personal preference goes to DEFAULT (singular). Because you default to a single or you default to a set of values.

I completely agree. I believe we may want to (at some point in the distant future) talk about having a certain default for one interface (which may be a set) and use a different default in a different interface. I'd want to use the word 'DEFAULTs' to refer to those cases (not as part of Ampersand syntax, but in the same informal way we can talk about 'POPULATIONs' when referring to all the different sources we get the initial population from; Note that the POPULATION keyword is also singular)

**Comment by hanjoosten** [comment]
Thanks guys for this discussion. Now @Michiel-s can fix this ;)

**Comment by Michiel-s** [comment]
Minor change in syntax compaired to @hanjoosten's latest proposal.

![image](https://user-images.githubusercontent.com/7961582/140659400-b1861f30-d57d-41e0-a102-7c15fbb009e4.png)
```
Defaults ::= ( 'DEFAULT' 
             ( 'SRC' | 'TGT' ) ( 'VALUE' '<AtomValue>' ( ',' '<AtomValue>' )* | 'EVALPHP' '<DoubleQuotedString>' )
       ( ',' ( 'SRC' | 'TGT' ) ( 'VALUE' '<AtomValue>' ( ',' '<AtomValue>' )* | 'EVALPHP' '<DoubleQuotedString>' ) )* )?

````

**Comment by Michiel-s** [comment]
Fixed
