### ISSUE TITLE
Multiple files on the command line of the ampersand compiler

### ISSUE THREAD

**Issue by hanjoosten** [AmpersandTarski/Ampersand#1196]
@stefjoosten requested me to investigate the possibility to have multiple root files when calling the ampersand generator. The required behaviour shoud be as if the extra files were INCLUDEd in the first one. 

@stefjoosten , could you elaborate on the use-case for this request?

**Comment by stefjoosten** [comment]
# Why this change?
Sometimes, a computer calls Ampersand to compile a script from an unknown source. An example is RAP, which compiles scripts made by students. If we want to include an extra population in such a script, we cannot change that script. An elegant way would be to allow multiple files on the command line of the Ampersand compiler. That is the use case that motivates this issue.
