### ISSUE TITLE
A-structure and P-structure isomorphism

### ISSUE THREAD

**Issue by sjcjoosten** [AmpersandTarski/Ampersand#123]
Create functions to create a P-structure from a given A-structure.

**Comment by hanjoosten** [comment]
For this to work, we need some more information in the A-structure, like information of explicit types that the user added to her script. (types could be derived by the typechecker too)

**Comment by sjcjoosten** [comment]
Would that be preferable to just putting in the types everywhere? The purpose of this ticket is to enable some round-trip for better testing, not to get a really nice and readable P-structure, right?

**Comment by hanjoosten** [comment]
We currently have A2P conversion as well as P2A conversion. However, we lose information both ways, so there is no proper roundtrip.
