### ISSUE TITLE
Error in Documentation

### ISSUE THREAD

**Issue by MiguelVerweijSogeti** [AmpersandTarski/Ampersand#1230]
# What happened
The documentation is mentioning a [TOT] statement in the takes relationship. The sample code doesn't contain this [TOT] statement. 

# What I expected
the [TOT] to be in the sample code.

# Version of ampersand that was used
4

# Steps to reproduce

Follow the tutorial steps.

# Screenshot / Video

# Context / Source of ampersand script
https://ampersandtarski.gitbook.io/documentation/tutorial-rap3/example-system-enrollment

Found by doing the tutorial, which is part of the RBD course.

**Comment by hanjoosten** [comment]
Thanks for reporting! I fixed the sample code.
