### ISSUE TITLE
Improve --haskell switch

### ISSUE THREAD

**Issue by sjcjoosten** [AmpersandTarski/Ampersand#124]
Make the --haskell switch such that it generates runnable code. Create a round-trip test bench for it.

Preferable solution:
generate a directory (in the style of --proto) with the necessary cabal installer files and Ampersand files, such that the directory is compilable.

**Comment by hanjoosten** [comment]
There is a price to pay: We need ampersand as a library too, to enable the haskell file to be compiled by GHC. Having a library requires a lot more build time every time you build ampersand. I am not sure if this is worth the benefits.

**Comment by sjcjoosten** [comment]
I'm not sure that's true, we could use the same setup as with `--proto`:

* add all Haskell source-files in the directory `src/Database/Design/Ampersand` to the StaticFiles_Generated.hs (making sure not to add StaticFiles_Generated.hs itself), so that they can be part of what is generated.
* We generate a separate version of Main.hs that does not call `createFSpec` but instead just runs `generateAmpersandOutput fSpec` where `fSpec` is defined by what is now the output of the `--haskell` switch.
* Set up in this way, the new executable will ignore its parameters and just generate the same output again. It would be really cool if we could work with switches again, by splitting `createFSpec` into a part that actually reads the fspec (`pCtx2Fspec userP_Ctx`) and a part that performs the output (`genFiles userP_Ctx >> genTables userP_Ctx`). See `Database.Design.Ampersand.FSpec.ToFSpec.CreateFspec` for what I mean by this.

**Comment by hanjoosten** [comment]
@sjcjoosten do you still plan to do this? If not, please close the issue.
