### ISSUE TITLE
Automate releasenotes to each release

### ISSUE THREAD

**Issue by hanjoosten** [AmpersandTarski/Ampersand#1267]
As someone that uses Ampersand directly from the releases page, it is hard to find the releasenotes. I suggest to add the releasenotes as a separate asset to each release. This can be done automatically :)

**Comment by Michiel-s** [comment]
I don't understand.. the release notes are there with the release:

![image](https://user-images.githubusercontent.com/7961582/144608942-3e232be2-2cfb-41d7-a12e-07a6d3573bc6.png)

**Comment by hanjoosten** [comment]
True, but these are only the notes of THIS release. In earlier releases, a link to the releasnotes was provided:
![image](https://user-images.githubusercontent.com/1159672/144615727-1180e879-ac94-4c67-a2d1-8a9953b321ec.png)
However, since we changed from branch `master` to `main`, these links are all broken. 
My idea is to add the releasenotes.md file as an asset. Just for convenience.
