### ISSUE TITLE
restrict relations identifiers

### ISSUE THREAD

**Issue by stefjoosten** [AmpersandTarski/Ampersand#1280]
# What happened
I defined a relation whose name has a diacritic in it: "allergieën". The compile and build towards a prototype went smoothly, but the database falls over:
![Screenshot 2022-03-13 at 07 31 15](https://user-images.githubusercontent.com/275768/158048235-f6871d4a-d181-47ab-aec1-0405c37ebd08.png)

# What I expected
I expected one of the following:
1. It works
2. It doesn't work and it is signalled to me by an error at compile-time (That would have been perfectly fine. I suggest we implement this alternative.)

# Version of ampersand that was used
I used Ampersand-v4.6.2

**Comment by hanjoosten** [comment]
I ran into this very issue last month, when I fixed the bitrot of the validate functionality. It has been fixed. Make sure you have the latest version of the ampersand generator.
