### ISSUE TITLE
Refactor PredLogic

### ISSUE THREAD

**Issue by stefjoosten** [AmpersandTarski/Ampersand#129]
Currently, predicate logic is generated from relation algebra in a troubled way, littered with some bitrot.
The predicate logic is required not only to generate predicate logic, but also to generate pidgin-english natural languages.

**Comment by sjcjoosten** [comment]
Stef can you elaborate on what needs to be improved?

**Comment by hanjoosten** [comment]
In the current effort of making the generated document (--FSpec ) less LaTeX only, I decided to get rid of the predicate logic all together. It will be far more easy to create it from scratch than to refactor this very old, unmaintanable code. I will take care of this some day.

**Comment by stefjoosten** [comment]
This issue is deprecated and is taken up in issue #842.

**Comment by Michiel-s** [comment]
In that case we can close this issue

**Comment by stefjoosten** [comment]
I have revived predicate logic in commit 6f48d71723311cc9d7320075158a9afc1bfb0e70, reverting [Han's observation](https://github.com/AmpersandTarski/Ampersand/issues/129#issuecomment-250083837). It is definitely more work to reinvent this module. Refactoring, however is best done in pair programming.
