### ISSUE TITLE
  <repo>/mirrors.json is expired

### ISSUE THREAD

**Issue by stefjoosten** [AmpersandTarski/Ampersand#1294]
I am running a little test on a separate branch called [Issue](https://github.com/AmpersandTarski/Ampersand/tree/Issue) on commit [4403e0eb](https://github.com/AmpersandTarski/Ampersand/commit/4403e0eb0d68965aead3de33ee9e8a585438b784). The entire log sits [here](https://github.com/AmpersandTarski/Ampersand/runs/6709144210). Here is an exerpt:
<img width="875" alt="image" src="https://user-images.githubusercontent.com/275768/171791542-9d48fa81-cccc-411d-ad4a-187ab121bc2b.png">

@hanjoosten or @Michiel-s, can either one of you diagnose and fix this?

This issue is weakly related to issue #1293.

**Comment by Michiel-s** [comment]
No clue where to start looking for this issue. Except that I would Google it and look on stackoverflow;)

I think this one is for @hanjoosten

**Comment by hanjoosten** [comment]
I am clueless as well. Somehow `ReleaseNotes.md` couldn't be found. Not sure where that comes from. Maybe something wrong with a cache? The next time that branch was built, this behaviour wasn't repeated. So nothing wrong. Probably a glitch of the universe. If we see this again, let's reopen the issue.
