### ISSUE TITLE
Proving software correct (--proofs)

### ISSUE THREAD

**Issue by stefjoosten** [AmpersandTarski/Ampersand#130]
The most difficult part of generating software is to make software that maintains rules, i.e. that keeps rules true. In the past, we have made ECA-rules by generating their proofs first, and harvesting the ECA-rules at the end of the process. The advantage was a high degree of certainty that the ECA-rules will generate correct software.

Since that time, thinking has advanced a lot, so the derivation of ECA-rules can be improved and simplified. In fact, the thing should be rebuilt from scratch, using the new insights together with the experience of generating proofs in Ampersand.

**Comment by sjcjoosten** [comment]
Several tickets address this issue, I'm closing it as this ticket seems to be much less specific than the others.
