### ISSUE TITLE
Disambiguation is too strong

### ISSUE THREAD

**Issue by stefjoosten** [AmpersandTarski/Ampersand#1306]
# What happened
I tried to compile the following script
```Ampersand
CONTEXT "Issue1306"
    RELATION triggering[BusinessProcess*BusinessProcess]  -- from ArchiMetaModel.adl
    RELATION assignment[BusinessActor*BusinessProcess]  -- from ArchiMetaModel.adl
    RELATION assignment[BusinessRole*BusinessProcess]  -- from ArchiMetaModel.adl

    CLASSIFY BusinessActor IS BusinessRole

    RULE SubsequentSteps : triggering[BusinessProcess] |- assignment~;assignment

ENDCONTEXT
```
I got the following error messages from the compiler:
```
% ampersand check Issue1306.adl
/Users/sjo00577/surfdrive/publicaties in aanbouw/ArchiChecker-in-sn-article-template- 10-09-2022/Issue1306.adl:8:55 error:
  Cannot disambiguate the relation: assignment 
    Please add a signature (e.g. [A*B]) to the relation.
    Relations you may have intended:
    assignment [BusinessActor*BusinessProcess] (/Users/sjo00577/surfdrive/publicaties in aanbouw/ArchiChecker-in-sn-article-template- 10-09-2022/Issue1306.adl:3:1)
    assignment [BusinessRole*BusinessProcess] (/Users/sjo00577/surfdrive/publicaties in aanbouw/ArchiChecker-in-sn-article-template- 10-09-2022/Issue1306.adl:4:1)
  Note: Some cases are not disambiguated fully by design. You can read about
    this at https://github.com/AmpersandTarski/Ampersand/issues/980#issuecomment-508985676==============================
/Users/sjo00577/surfdrive/publicaties in aanbouw/ArchiChecker-in-sn-article-template- 10-09-2022/Issue1306.adl:8:67 error:
  Cannot disambiguate the relation: assignment 
    Please add a signature (e.g. [A*B]) to the relation.
    Relations you may have intended:
    assignment [BusinessActor*BusinessProcess] (/Users/sjo00577/surfdrive/publicaties in aanbouw/ArchiChecker-in-sn-article-template- 10-09-2022/Issue1306.adl:3:1)
    assignment [BusinessRole*BusinessProcess] (/Users/sjo00577/surfdrive/publicaties in aanbouw/ArchiChecker-in-sn-article-template- 10-09-2022/Issue1306.adl:4:1)
  Note: Some cases are not disambiguated fully by design. You can read about
    this at https://github.com/AmpersandTarski/Ampersand/issues/980#issuecomment-508985676
ExitFailure 10
% 
```
# What I expected
I expected that this script is correct, because the declaration `CLASSIFY BusinessActor IS BusinessRole` would make `BusinessActor` and `BusinessRole` 100% synonym. This implies that relations `assignment[BusinessActor*BusinessProcess]` and `assignment[BusinessRole*BusinessProcess]` are provably the same relations. Hence, there is nothing to disambiguate.

# Version of ampersand that was used
Ampersand-v4.6.3 [feature/typecheck-ENFORCE:b7df07b3c*]

**Comment by sjcjoosten** [comment]
I disagree that this might be a bug (for now), quoting from FormalAmpersand (two parts of Relations.adl):

```
RELATION sign[Relation*Signature] [UNI] 
MEANING "The signature of a relation."

IDENT Relation: Relation( name, sign[Relation*Signature];src, sign[Relation*Signature];tgt[Signature*Concept] , relsDefdIn[Relation*Context])
RULE "eq relation": name[Relation*RelationName];name[Relation*RelationName]~ 
                 /\ sign[Relation*Signature];src[Signature*Concept];(sign[Relation*Signature];src[Signature*Concept])~ 
                 /\ sign[Relation*Signature];tgt[Signature*Concept];(sign[Relation*Signature];tgt[Signature*Concept])~ 
                 |- I[Relation]
MEANING "The unique signature of a relation consists of a relation name, a source concept, and a target concept."
```

I read this as saying that a relation can have at most one signature (by UNI) so the two different signatures for assignment make it that these must be different relations. They can therefore have different populations too. Second reason is going off the "eq relation" rule, which doesn't formally specify the same thing, but in its meaning that same train of thought seems to be implied.

Third reason: you might wish to express the following in your script:

```
RULE "eq assignment": assignment[BusinessActor*BusinessProcess] = assignment[BusinessRole*BusinessProcess]
```

If the two relations were the same, the rule would be trivially true and therefore not expressible (that is, in a formal sense: writing 'True' as a rule would have the same formal meaning).

**Comment by stefjoosten** [comment]
Your suggestion to add `RULE "eq assignment"` does not solve the error message, because that is a type error.
Besides, `RULE "eq assignment"` is already satisfied by the following proof:

1. Let `A`,`B` be concepts and let $A$ be the set of atoms in `A` and let $B$ be the set of atoms in `B`.
2. The statement `CLASSIFY A IS B` means that `A`$=$`B`, i.e. $\forall x: x\in A\ \Leftrightarrow\ x\in B$.
3. `RULE "eq relation"` means:
$name(r)=name(s)\ \wedge\ src(sign(r))=src(sign(s))\ \wedge\ tgt(sign(r))=tgt(sign(s))\ \Rightarrow\ r=s$
4. So, 
   ```
    RELATION assignment[BusinessActor*BusinessProcess]
    RELATION assignment[BusinessRole*BusinessProcess]
    CLASSIFY BusinessActor IS BusinessRole
   ```
   means that `assignment[BusinessActor*BusinessProcess]`$=$`assignment[BusinessRole*BusinessProcess]`, i.e. $\forall (p,q): (p,q)\in$`assignment[BusinessActor*BusinessProcess]`$\ \Leftrightarrow\ (p,q)\in$`assignment[BusinessRole*BusinessProcess]`.

Both relations are the same, simply because `BusinessActor` and `BusinessRole` are the same. Note that the implementation in the database is already consistent with this.

So maybe you could reconsider your answer...?

(@sjcjoosten,  Did you accidentally read the implication in `RULE "eq relation"` the other way around?)
Note that the `MEANING` of `RULE "eq relation"` in FormaLAmpersand is wrong and confusing. There is nothing unique about the signature.

**Comment by stefjoosten** [comment]
Aha, I see! The culprit of our misunderstanding is in FormalAmpersand:
```Ampersand
RELATION sign[Relation*Signature] [UNI]
```
This is wrong. It should not be univalent at all.

**Comment by hanjoosten** [comment]
> Aha, I see! (The quarter has fallen...). The culprit of our misunderstanding is in FormalAmpersand:
> 
> ```
> RELATION sign[Relation*Signature] [UNI]
> ```
> 
> This is wrong. It should not be univalent at all.

Interesting. This has consequences for EQ on relations. @stefjoosten, please explain what the EQ on relations should be?

**Comment by stefjoosten** [comment]
Yeah, you are right. My comment "The quarter has fallen" is nonsense. Please ignore. 
Surely, `RELATION sign[Relation*Signature]` is univalent for the same reason: `A`$=$`B` implies that `[A*C]`$=$`[B*C]`.
So let us leave FormalAmpersand as it is. Sorry for generating noise.

**Comment by hanjoosten** [comment]
By the way, I believe that FormalAmpersand isn't strict enough: The relation  `sign[Relation*Signature]` should be total as well, but I do not want to interfere with the discussion between @sjcjoosten and @stefjoosten

**Comment by sjcjoosten** [comment]
I don't think it is a good idea to interpret ``CLASSIFY A IS B`` as ``A = B``. I'd rather interpret it as saying that the population of ``A`` and ``B`` are equal whenever the database is stable/consistent. So I agree with $\forall x: x\in P(A)\ \Leftrightarrow\ x\in P(B)$ (I read the $P$ as 'Population at some point in time', and I intend universal quantification over all such populations).

Consider this script:

```
CONCEPT Actor MEANING "An organizational entity that is capable of performing behavior."
CONCEPT Role
CLASSIFY Actor IS Role
```

I believe that Role should not carry the meaning ``An organizational entity that is capable of performing behavior.``.

**Comment by stefjoosten** [comment]
We need to discuss this...

**Comment by stefjoosten** [comment]
Thanks for a good discussion, @sjcjoosten.

We've brought this down to the following use case. Let me summarize my lessons learned and close this issue.

Suppose we have two different concepts $A$ and $B$, both with different `MEANING`:
```Ampersand
CONCEPT A "This is the meaning of A."
CONCEPT B "This is the meaning of B."
```
Now we want to state that their populations are equal:
```Ampersand
CLASSIFY A, B ISA C
RULE I[A]=I[B]
```
This keeps the type checker happy. However, if we add some population we can see that something is missing:
```Ampersand
CONTEXT Issue1306

CONCEPT A "This is the meaning of A."
CONCEPT B "This is the meaning of B."

CLASSIFY A, B ISA C
RULE I[A]=I[B]

POPULATION A CONTAINS ["a5", "a2"]
POPULATION B CONTAINS ["b5"]

ENDCONTEXT
```
This produces 3 violations of `RULE I[A]=I[B]`:
```
    ("a5", "a5")
    ("a2", "a2")
    ("b5", "b5")
```
So, the populations of concepts $A$ and $B$ are different. However, if we add
```Ampersand
CLASSIFY C ISA A
CLASSIFY C ISA B
```
The type checker is happy and `RULE I[A]=I[B]` too is satisfied.

# Solution
the script that started this issue should have been written as:
```Ampersand
CONTEXT "Issue1306"
    RELATION triggering[BusinessProcess*BusinessProcess]  -- from ArchiMetaModel.adl
    RELATION assignment[BusinessActor*BusinessProcess]  -- from ArchiMetaModel.adl
    RELATION assignment[BusinessRole*BusinessProcess]  -- from ArchiMetaModel.adl

    CLASSIFY BusinessActor, BusinessRole ISA B
    CLASSIFY B ISA BusinessActor
    CLASSIFY B ISA BusinessRole

    RULE SubsequentSteps : triggering[BusinessProcess] |- assignment~;assignment

ENDCONTEXT
```
This keeps the type checker happy and `RULE SubsequentSteps` treates business actors and business roles as the same concept (which was the intention of the author in this situation).
