### ISSUE TITLE
DocuGen repo: Setup initial Docusaurus website

### ISSUE THREAD

**Issue by basplijnaer** [AmpersandTarski/Ampersand#1318]
To create a working base website we want to have something running to build upon.

- [x] Create a simple hello world Docusaurus website
- [x] Deploy to github pages

**Comment by stefjoosten** [comment]
I would expect that [GitHub pages](https://github.com/AmpersandTarski/Ampersand/settings/pages) is the way to do this. Please disagree if you think otherwise.

**Comment by hanjoosten** [comment]
Github pages is indeed the way to go to serve the 1-page-website. 
To generate that site from whatever content we have, we need source depending on the tool we use to generate it. If we go for docusaurus, we need to generate a website as explained [here](https://docusaurus.io/docs#fast-track). The result of such website should be stored in a new repo at AmpersandTarski. If that is done, we have to see how the docs directories of Ampersand and prototype fit in that repo, so together they can be used to let docusaurus generate the 1-page-website.

**Comment by hanjoosten** [comment]
BTW, I saw that we are not the only project to move away from Gitbook. [Redux](https://redux.js.org/) did this. You can read about there whereabouts over [here](https://github.com/reduxjs/redux/issues/3161). They have a nice thread about their motivation and what they did. Could be insirational for the team.

**Comment by Michiel-s** [comment]
As example, here's a Dockerfile we used to create a static Docusaurus website that can be served by any webserver. In the setup below we use NGINX image as webserver, but that will be Github pages then.

The `npm run build` cmd kicks of the Docusaurus build script.

```yaml
FROM node:lts as build

WORKDIR /app

COPY package.json package-lock.json /app/

RUN npm install

COPY ./ /app/

RUN npm run build

FROM nginx:stable-alpine

COPY --from=build /app/build /usr/share/nginx/html
COPY ./nginx-conf /etc/nginx/conf.d

```

**Comment by basplijnaer** [comment]
The Docusaurus website is available at: https://ampersandtarski.github.io/DocuGen/
