### ISSUE TITLE
Documentation repo: Classify documentation

### ISSUE THREAD

**Issue by basplijnaer** [AmpersandTarski/Ampersand#1320]
It is difficult to tell what documentation files should be moved to [Ampersand](https://github.com/AmpersandTarski/Ampersand) and what files should be moved to [Prototype](https://github.com/AmpersandTarski/Prototype). It would be helpful if the files were labeled as either "Prototype" or "Ampersand".

**Comment by stefjoosten** [comment]
For now: Everything in gitbook "Documentation" goes to Ampersand.
Everything in gitbook "The tools we use" goes to Ampersand.
Everything in Prototype (just a few pages, I have heard) stays in Prototype. (Ask @Michiel-s about this).
