### ISSUE TITLE
Docusaurus: Onderzoeken/spelen

### ISSUE THREAD

**Issue by NiekNieuwenhuisen** [AmpersandTarski/Ampersand#1324]
Gezien de focus op Docusaurus willen wij als ontwikkelaars eerst uitzoeken wat Docusaurus voor rol speelt in het project en er mee spelen om uit te vogelen hoe het werkt. 

- [ ] Indien de uitvoerder tegen problemen aanloopt tijdens het het onderzoek dit gedocumenteerd worden.

https://docusaurus.io/

**Comment by basplijnaer** [comment]
- There is a choice between the standard version and a version with typescript support

**Comment by stefjoosten** [comment]
Are both alternatives 100% Free Open Source Software?
