### ISSUE TITLE
How to run linux on Ordina hardware

### ISSUE THREAD

**Issue by JesseZwitserlood** [AmpersandTarski/Ampersand#1332]
Currently it is not allowed to install WSL2 (running linux in windows) on a ordina laptop. However you need to be able to run linux to use the application. this issue makes it so that contributers cant test the application.

- [ ] figuring out a way to run linux on windows thats permited by ordina.

suggestions:

1. Using a virtual azure machine to run Linux
2. Using a local virtual machine to run Linux (this might have bios restrictions)

**Comment by hanjoosten** [comment]
Who says so? I run WSL2 on a Ordina laptop ???
