### ISSUE TITLE
test issue

### ISSUE THREAD

**Issue by basplijnaer** [AmpersandTarski/Ampersand#1356]
- [ ] test for child issue

**Comment by stefjoosten** [comment]
This issue is not self-contained. Please remove this issue or rephrase and elaborate.
(Whenever you make an issue, make sure that someone can pick it up after it has been stale for three years...)

**Comment by hanjoosten** [comment]
Ik neem aan van wel. Zo niet, dan gewoon heropenen, en even toelichten
