### ISSUE TITLE
Development branch disappeared 

### ISSUE THREAD

**Issue by basplijnaer** [AmpersandTarski/Ampersand#1357]
# What happened
The deployment of Docusaurus failed because the docker could not access the Ampersand documentation on the development branch: 

` => ERROR https://github.com/AmpersandTarski/Ampersand/archive/refs/heads/development.zip                                                              0.9s `

# What I expected
`Container ampersandtarskigithubio-docusaurus-1  Started`

# Version of ampersand that was used

# Steps to reproduce

1. clone this repository
2. switch to feature/drafts branch
3. run `docker-compose up --build -d`

# Screenshot / Video
Error message:
![image](https://user-images.githubusercontent.com/13163139/196909692-50134626-067a-49c8-858c-0e95c8bbd90a.png)

Development missing:
![image](https://user-images.githubusercontent.com/13163139/196909772-b9f445aa-2e19-4397-8bf6-3993ab172891.png)

# Context / Source of ampersand script

From Dockerfile: 
```
ADD https://github.com/AmpersandTarski/Ampersand/archive/refs/heads/feature/drafts.zip /tmp/Ampersand.zip
ADD https://github.com/AmpersandTarski/prototype/archive/refs/heads/main.zip /tmp/prototype.zip
ADD https://github.com/AmpersandTarski/TheToolsWeUse/archive/refs/heads/development.zip /tmp/TheToolsWeUse.zip

RUN mkdir -p /app/docs

# For local testing, this is the place to local edit this docerfile. 
# 1) Comment out the specific RUN statement(s) for the repo you want to test your local changes:
RUN unzip /tmp/Ampersand.zip 'Ampersand-feature-drafts/docs/*' -d /tmp/Ampersand/ \
    && cp -R /tmp/Ampersand/Ampersand-feature-drafts/docs/ /app/docs/Ampersand
RUN unzip /tmp/prototype.zip 'prototype-main/docs/*' -d /tmp/prototype/ \
    && cp -R /tmp/prototype/prototype-main/docs/ /app/docs/Prototype
RUN unzip /tmp/TheToolsWeUse.zip 'TheToolsWeUse-development/*' -d /tmp/TheToolsWeUse/ \
    && cp -R /tmp/TheToolsWeUse/TheToolsWeUse-development/ /app/docs/TheToolsWeUse
```

**Comment by Michiel-s** [comment]
Sorry my bad. I've just restored the branch.
