### ISSUE TITLE
Unwanted change in loading of initial population from ADL script

### ISSUE THREAD

**Issue by Michiel-s** [AmpersandTarski/ampersand#136]
Han,

As of a recent commit (from last weekend I guess), atoms from the initial population in an ADL script are inserted with double quotes in the database. For example:
`POPULATION A CONTAINS ["a"]` is inserted as `"a"` while it should be `a`

Could you fix this issue? Michiel

**Comment by hanjoosten** [comment]
Should work now. (I am also testing the board on waffle.io/AmpersandTarski/ampersand )
