### ISSUE TITLE
Possible Inconsistency between Context elements and Pattern elements

### ISSUE THREAD

**Issue by TAA-github** [AmpersandTarski/Ampersand#1377]
Possible Inconsistency:
 
Context elements

<gen> a statement that specifies generalization/specialization of concepts
 

Pattern elements
<classify> a statement that specifies generalization/specialization of concepts

**Comment by TAA-github** [comment]
Pages:


https://ampersandtarski.gitbook.io/documentation/the-language-ampersand/context#context-elements

https://ampersandtarski.gitbook.io/documentation/the-language-ampersand/patterns#syntax

**Comment by hanjoosten** [comment]
I see no inconsistency. An Ampersand specification always specifies a single context. As such, any .adl script always has the [form](https://ampersandtarski.gitbook.io/documentation/the-language-ampersand/context#syntax-and-meaning)

~~~
CONTEXT <name> 

<statements>

ENDCONTEXT
~~~

One of the statements is the [PATTERN statement](https://ampersandtarski.gitbook.io/documentation/the-language-ampersand/patterns#syntax). That statement can hold most of the statements that could be defined directly inside the CONTEXT statement. The PATTERN statement is most useful to group statements that are about the same theme. The content of a pattern is shown in the generated documentation as a separate chapter. 
The text you are reffering to is about [a statement](https://ampersandtarski.gitbook.io/documentation/the-language-ampersand/the-classify-statement) that may be defined inside a PATTERN or directly inside the CONTEXT. For the effect on the generated software there is no difference.

**Comment by hanjoosten** [comment]
@TAA-github , please don't hesitate to reopen this issue if you think I misunderstood you. And thanks again for the comment.

**Comment by TAA-github** [comment]
Sorry, something was lost in the format:
Context elements
"<gen>"
a statement that specifies generalization/specialization of concepts
 
Pattern elements
"<classify>"
a statement that specifies generalization/specialization of concepts

**Comment by TAA-github** [comment]
again losed

Context elements
gen
a statement that specifies generalization/specialization of concepts
 
Pattern elements
classify
a statement that specifies generalization/specialization of concepts

**Comment by TAA-github** [comment]
to refer to the same statements: in one plase the GEN text is used and in other the CLASIFFY text

**Comment by hanjoosten** [comment]
I see what you mean now. There is no GEN statement, but it is about generalisation and specialisation of concepts. See the [CLASSIFY statement](https://ampersandtarski.gitbook.io/documentation/the-language-ampersand/the-classify-statement) on how this works. 
We are busy migrating the documentation to another site. I will make sure the documentation on the new site will be fixed with regard to the GEN text.
