### ISSUE TITLE
Created new repo for storing WIKI content (media) files

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/ampersand#140]
In order to refer to files (e.g. pictures, slides, documents, etc.) from within the Ampersand wiki (https://github.com/AmpersandTarski/ampersand/wiki/), a storage location was needed for such files.

I have created a repo for doing so, located at https://github.com/RieksJ/wiki-materials.

Please read the readme file there before using it.

**Comment by hanjoosten** [comment]
I just created a new repo for useage like this. However, it is a repo at ampersandTarski, which is better for maintenance. Please use this one.

**Comment by RieksJ** [comment]
Ok. Done so. I have deleted the repo at https://github.com/RieksJ/wiki-materials.
