### ISSUE TITLE
Transitive Closure does not work anymore

### ISSUE THREAD

**Issue by stefjoosten** [AmpersandTarski/Ampersand#1407]
# What happened
I was experimenting with the transitive closure script on the ampersand-models repo.
It contains calls to `RerunExecEngine` and `TransitiveClosure` from the PHP-environment.

# What I expected
I expected this script to work, but I got this message: 
_Invalid exec engine function call as defined in /usr/local/project/TransitiveClosure.adl:27:1. Function call 'TransitiveClosure(trn,Concept,trnCopy,trnStar)'. Unknown 'tableOf' option for relation 'trnCopy[Concept*Concept]'_

# Version of Ampersand that was used
docker build is running `FROM ampersandtarski/prototype-framework:v1.14`.

# Steps to reproduce

1. copy the stuff from ampersand-models/TransitiveClosure into a fresh working directory
2. compile with `docker compose build`
3. run with `docker compose up-d`
4. view the result in `localhost` and install the database.
5. fill field `trn` with the atom `noot`  to add the pair `("aap","not") to the relation `trn` interactively.

# Screenshot / Video
<img width="720" alt="afbeelding" src="https://user-images.githubusercontent.com/275768/236436263-f959086a-75bc-4241-a7c4-c55072d8af0b.png">

# Context / Source of ampersand script
I found this bug when experimenting with an old script. Here is the source code:
```Ampersand
CONTEXT TransitiveClosure IN ENGLISH
PURPOSE CONTEXT TransitiveClosure
{+ Currently, the `*`-operator (transitive closure) is not operational in Ampersand.
To work around this omission, change all occurrences of 
- `trn` into the name of the relation as you use it, and
- `Concept` into the name of the source and target concept of that relation.

We assume you have a relation `trn[Concept*Concept]`
for which you want to dispose of its transitive closure `trn*`.
To do so, you define a relation, e.g. `trnStar[Concept*Concept]` that will contain this population:
+}
RELATION trn[Concept*Concept]     -- some endo-relation

{-This alternative requires that the function `TransitiveClosure` has been defined, which
- discards the existing populations of `trnStar` and `trnCopy`, 
- recomputes `trnStar` from `trn` using the Warshall algorithm, and
- copies `trn` to `trnCopy`.
-}
RELATION trnCopy[Concept*Concept] -- a relation that we use to detect changes in the population of `trn`
RELATION trnStar[Concept*Concept] -- the transitive closure of `trn`.
ROLE ExecEngine MAINTAINS "Compute `trnStar` after the population of `trn` has changed"
RULE "Compute `trnStar` after the population of `trn` has changed": trnCopy = trn
VIOLATION (TXT "{EX} TransitiveClosure;trn;Concept;trnCopy;trnStar") -- This updates relations `trnCopy` and `trnStar`.  --}

POPULATION "Concept" CONTAINS [ "aap", "noot", "mies" ]

INTERFACE "Transitive Closure" : "_SESSION";V[SESSION*Concept] BOX
   [ Id : I
   , trn : trn
   , trnStar : trnStar
   ]

INTERFACE Concept : I[Concept] BOX
   [ Concept : I
   , trn : trn
   , trnStar : trnStar
   , flipped : trnStar~
   ]

ENDCONTEXT
```

**Comment by hanjoosten** [comment]
As far as I know this has never been implemented. So the conclusion that it still does'nt work is valid.

**Comment by stefjoosten** [comment]
I'm quite sure it has been implemented, but of course I could be wrong...

**Comment by stefjoosten** [comment]
The situation seems to have resolved itself. Don't know why and don't intend to find out...
