### ISSUE TITLE
Devcontainer from docker hub

### ISSUE THREAD

**Issue by stefjoosten** [AmpersandTarski/Ampersand#1421]
# Problem
To build the devcontainer for VS-code takes over an hour. As a result, I don't use it. When I need to do something in Ampersand I just don't find the time to wait for the devcontainer to build. Yet, I do want to use all the goodies that @hanjoosten has built.

# Desired solution
As a developer, I want the devcontainer image to reside on docker-hub, so I merely have to wait for loading.

**Comment by stefjoosten** [comment]
# Solution
I have made the docker file in the `.devcontainer` directory merely import the correct image.
We then need to publish that image by means of a github action, so that the most recent image is always available.

**Comment by hanjoosten** [comment]
@stefjoosten , we already had a branch that contain this work. You created a branch from `development` branch, which you should delete! 
There is a PR (https://github.com/AmpersandTarski/Ampersand/pull/1423) now, to get this stuff into main asap.

**Comment by hanjoosten** [comment]
After https://github.com/AmpersandTarski/Ampersand/pull/1423 has been merged, we still need a way to automatically update dockerhub.

**Comment by stefjoosten** [comment]
There is a complication. When `stack` is building Ampersand, it calls GitHub to obtain a version number. It needs a pair of SSH keys to get access to the Ampersand repo. That is why `stack build` failed in the container. However, I don't like putting an SSH key pair into the repo because the repo is visible to the world.

So how do we do this?

**Comment by hanjoosten** [comment]
Fixed by todays PR.
