### ISSUE TITLE
Readers of our documentation can no longer give their feedback on ampersandtarski.github.io

### ISSUE THREAD

**Issue by stefjoosten** [AmpersandTarski/Ampersand#1432]
Our [documentation](https://ampersandtarski.github.io/the-tools-we-use#contributions-to-the-documentation) says:

> If you have anything to fix or details to add, just post a comment next to the paragraph. We really appreciate if you do so, because our readers know best what it is they are looking for in the docs.

> You can do that by clicking the icon that appears when you hover above the paragraph. Don't be shy! Try it out! (you need to be logged in however, but it is totally free to create an account).

However, in Docusaurus, this no longer works.

**Describe the solution you'd like**
I'd like this to work in our Docusaurus-based documentation.

**Describe alternatives you've considered**

Even though this feature wasn't used much, it was used. Its rare use has to do with the quality of our documentation and whether our site actively solicits feedback.  I think it is necessary to lower the threshold for "strangers" and let this feature be part of an inviting and inclusive experience as much as we can.

**Comment by stefjoosten** [comment]
This issue is covered by https://github.com/AmpersandTarski/AmpersandTarski.github.io/issues/9.

**Comment by hanjoosten** [comment]
Test
