### ISSUE TITLE
Weird Docusaurus behaviour on broken links

### ISSUE THREAD

**Issue by stefjoosten** [AmpersandTarski/Ampersand#1433]
# What happened
I compiled the documentation and got the following broken links.
```
#0 1.740 [INFO] [en] Creating an optimized production build...
#0 2.368 ℹ Compiling Client
#0 2.387 ℹ Compiling Server
#0 30.81 ✔ Client: Compiled successfully in 28.45s
#0 34.25 ✔ Server: Compiled successfully in 31.86s
#0 42.22 [ERROR] Unable to build a website for locale en.
#0 42.22 [ERROR] Error: Docusaurus found broken links!
#0 42.22 
#0 42.22 Please check the pages of your site in the list below, and make sure you don't reference any path that does not exist.
#0 42.22 Note: it's possible to ignore broken links with the 'onBrokenLinks' Docusaurus configuration, and let the build pass.
#0 42.22 
#0 42.22 Exhaustive list of all broken links found:
#0 42.22 
#0 42.22 - On source page path = /ampersand/reference-material/the-language-ampersand:
#0 42.22    -> linking to ../syntax-of-ampersand#the-concept-statement (resolved as: /ampersand/syntax-of-ampersand)
#0 42.22    -> linking to ../syntax-of-ampersand#RELATION-statement (resolved as: /ampersand/syntax-of-ampersand)
#0 42.22    -> linking to ../syntax-of-ampersand#RULE-statement (resolved as: /ampersand/syntax-of-ampersand)
#0 42.22    -> linking to ../syntax-of-ampersand#PATTERN-statement (resolved as: /ampersand/syntax-of-ampersand)
#0 42.22    -> linking to ../syntax-of-ampersand#POPULATION-statement (resolved as: /ampersand/syntax-of-ampersand)
#0 42.22    -> linking to ../syntax-of-ampersand#CLASSIFY-statement (resolved as: /ampersand/syntax-of-ampersand)
#0 42.22 
```
No matter how hard I try, I cannot get this fixed, so I need some help. I got this message with the following settings in `docusaurus.config.js` on `ampersandtarski.github.io`:
```JavaScript
  onBrokenLinks: 'throw',
  onBrokenMarkdownLinks: 'warn',
  onDuplicateRoutes: 'warn',
```
# What I expected
I expected no errors because when I force-compile the documentation, the links work just fine.

# Version of Ampersand that was used
I used AmpersandTarski/AmpersandTarski.github.io@e899e83e56fc08f17061ff2aa9a082557ce8278b, changing the `onBrokenLinks` setting to `throw` to get the messages.
I used AmpersandTarski/Ampersand@8f5e1983b03bf9907735ade2e5bb34b1b900443c for the Ampersand documentation, AmpersandTarski/TheToolsWeUse@d6e513cf3ea461fd9d5f054a9c4eb7547a9e0362 for TheToolsWeUse, and AmpersandTarski/Prototype@8bc4a1afa22c1fdee0ccdccb6039dd8e00c7d658 for the documentation of the prototype framework.

# Steps to reproduce

1. Make the Docusaurus container build locally
2. checkout the documentation in the versions mentioned above
3. build and watch the messages.

**Comment by hanjoosten** [comment]
There were two suspects: 
* Casing. the links are case sensetive
* There exists a directory `the-language-ampersand` and a file named `the-language-ampersand.md` at the same level. I think that also caused problems, but I am not sure about that. Currently, there are not broken links :)
