### ISSUE TITLE
Cannot use Ormolu

### ISSUE THREAD

**Issue by stefjoosten** [AmpersandTarski/Ampersand#1454]
# What is the page that your suggestion is about?
`https://ampersandtarski.github.io/ampersand/the-tools-we-use/group-1/development-using-vs-code#code-formatting`

# What Is your comment?
I failed at using Ormolu. I am trying to make a pull request to satisfy the Ormolu requirement that we built into the GitHub workflow. I'm running in the devcontainer, but Ormolu does not run automatically. To find out what to do, I consulted the manual.  It makes me build Ormolu, which takes an awful lot of time (which I used to type this issue). All of that is way too much hassle for the added value Ormolu gives us.
![afbeelding](https://github.com/AmpersandTarski/Ampersand/assets/275768/cdc855cd-e210-47bb-8e47-fed8b1004618)

# Feature request
## Alternative 1
Skip Ormulu, if the user must do too much. The cognitive load of developing Ampersand is already too high, and adding Ormolu to that isn't worth the benefits.
## Alternative 2
Make it fully automatic in the devcontainer, so that it works in 100% of cases to make sure the Haskell developer does not have the cognitive load of Ormolu.
## Alternative 3
Make good instruction on ampersandtarski.github.io, that makes Ormolu work with an acceptable cognitive load.

**Comment by stefjoosten** [comment]
At the moment, I'm running Ormulu "by hand" from the command line every time I commit a branch...

**Comment by hanjoosten** [comment]
Alternative 1: This is a no-go. The purpose of using system wide code formatting is exactly to reduce cognitive load. 
Alternative 2: This has been implemented already. However, It assumes that you have format-on-save enabled in your vscode settings. 
Alternative 3: I did some clarification in the documentation.
