### ISSUE TITLE
Rewrite "fatal" to give the location of the error

### ISSUE THREAD

**Issue by sjcjoosten** [AmpersandTarski/ampersand#146]
In GHC 7.10.2, there is this great new feature, as described here: https://downloads.haskell.org/~ghc/7.10.2/docs/html/users_guide/other-type-extensions.html#special-implicit-params

We could use it to clean up our `fatal` everywhere.

I propose we wait with this until the haskell platform ships with 7.10.2 or newer.

**Comment by sjcjoosten** [comment]
Closed by 5828bdd..8a11a6c

**Comment by sjcjoosten** [comment]
The change provides in a nice new way of debugging: suppose we get a fatal in function "f", but that  does not really tell us something, we want to know where "f" was called instead. Then we can do the following:

- add ``{-# LANGUAGE ImplicitParams #-}`` at the top of the file (if not already there)
- add ``import GHC.Stack`` to the list of imports (if not already there)
- change the type of ``f`` from ``f :: a`` to ``f :: (?loc :: CallStack) => a``.

That's all! The error message will now include the call-site of f.

**Comment by hanjoosten** [comment]
Fat!  :-))
