### ISSUE TITLE
Error in the operator #

### ISSUE THREAD

**Issue by stefjoosten** [AmpersandTarski/Ampersand#1460]
# What happened
I noticed that
```Ampersand
RELATION r[A*B]
ENFORCE r := I[A]#"foo"
```
has a different semantics than
```Ampersand
RELATION r[A*B]
ENFORCE r := V[A*B]#"foo"
```
If I test this with the following population:
```Ampersand
POPULATION A CONTAINS [ "1", "2", "3" ]
POPULATION B CONTAINS [ "foo", "bar", "gnu" ]
```
I see that the expression ` I[A]#"foo"` yields `[("1","foo"),("1","bar"),("1","gnu"),("2","foo"),("2","bar"),("2","gnu"),("3","foo"),("3","bar"),("3","gnu")]`.
Yet, the expression ` V[A*B]#"foo"` yields `[("1","foo"),("2","foo"),("3","foo")]`.

# What I expected
I expected the result to be the same, i.e. `[("1","foo"),("2","foo"),("3","foo")]`, in both cases to comply with the definition of `#`.

# Version of ampersand that was used
I used a dockerfile FROM ampersandtarski/prototype-framework:v1.14

# Steps to reproduce

1. Run the script below as a prototype (e.g. in `https://rap.cs.ou.nl`) and observe the results for the term `V[A*B]#"foo"`.
2. Move the comment, rerun, and observe the results for the term `I[A]#"foo"`.

# Screenshot / Video

# Context / Source of ampersand script
```Ampersand
CONTEXT Issue1460

RELATION r[A*B]
-- ENFORCE r := I[A]#"foo"
ENFORCE r := V[A*B]#"foo"

POPULATION A CONTAINS [ "1", "2", "3" ]
POPULATION B CONTAINS [ "foo", "bar", "gnu" ]

INTERFACE ShowAll : "_SESSION";I[SESSION] BOX
 [ As : V[SESSION*A] BOX
       [ A : I
       , "B (r)" : r
       ]
 , Bs : V[SESSION*B] BOX
       [ B : I
       , "A (r~)" : r~
       ]
 ]

ENDCONTEXT
```

**Comment by hanjoosten** [comment]
@stefjoosten , This is weird indeed. In the [documentation](https://ampersandtarski.github.io/ampersand/reference-material/terms#notation-on-the-keyboard) it says that `#` (The operator for cartesian product) is deprecated. It doesn't say _why_ it is deprecated. If it is, we should get rid of it. If it isn't deprecated, could you please point me to the semantics of the cartesian product of two expressions?

**Comment by hanjoosten** [comment]
Stef explained to me that the `#`-operator is syntactical sugar for `;V;`.

IMHO: this is something else than the cartesian product as defined in set theory. Hence, we should come up with a better name for this operator:

The Cartesian product of two relations \( R \) and \( S \) is defined as the set of all ordered pairs where the first element is a pair from \( R \) and the second element is a pair from \( S \). Mathematically:

$$
R \times S = \{ ((a, b), (c, d)) \mid (a, b) \in R \text{ and } (c, d) \in S \}.
$$

### Explanation:
1. **Relation $ R $:** A subset of the Cartesian product of two sets \( A \) and \( B \), i.e., \( R \subseteq A \times B \).
2. **Relation $ S $:** A subset of the Cartesian product of two sets \( C \) and \( D \), i.e., \( S \subseteq C \times D \).

The Cartesian product $ R \times S $ forms a new relation in which each element is a pair of pairs: one pair from $ R $ and another pair from $ S $.

### Example:
Let $ R = \{(1, 2), (3, 4)\} $ and $ S = \{(5, 6), (7, 8)\} $. Then:

$$
R \times S = \{((1, 2), (5, 6)), ((1, 2), (7, 8)), ((3, 4), (5, 6)), ((3, 4), (7, 8))\}.
$$

This concept extends the Cartesian product of sets to relations by treating each relation as a collection of ordered pairs.

**Comment by stefjoosten** [comment]
I have fixed the "deprecated" remark in the documentation.

**Comment by hanjoosten** [comment]
I cannot reproduce this in ampersand 5.2.5. I modified your script in such a way that both ENFORCE rules are executed in the same model:

~~~.ampersand
CONTEXT Issue1460

RELATION r[A*B]
ENFORCE r := I[A]#"foo"

RELATION s[A*B]
ENFORCE s := V[A*B]#"foo"

POPULATION A CONTAINS [ "1", "2", "3" ]
POPULATION B CONTAINS [ "foo", "bar", "gnu" ]

INTERFACE ShowAll : "_SESSION";I[SESSION] BOX
 [ As : V[SESSION*A] BOX
       [ A : I
       , "B (r)" : r
       , "B (s)" : s
       ]
 , Bs : V[SESSION*B] BOX
       [ B : I
       , "A (r~)" : r~
       , "A (s~)" : s~
       ]
 ]

ENDCONTEXT
~~~

I see the same results for the population of both `r`and `s`:

![image](https://github.com/user-attachments/assets/104011dd-4cf0-4ad2-a3cf-fc5833e7590c)

**Comment by stefjoosten** [comment]
Convincing! let's close :-)
