### ISSUE TITLE
Error occurred for Markup when implementing the latest version of Formal Ampersand in RAP. 

### ISSUE THREAD

**Issue by SimonvRoozendaalOrdina** [AmpersandTarski/Ampersand#1484]
Error occurred when implementing the latest version of Formal Ampersand in RAP.  
# What happened
When trying out the latest version of Ampersand in RAP, an error occured:
"Every Markup must have a MarkupText in the relation text".

When compiling a script, this error occured due to the inclusion of the MEANING for 'isEnrolledFor' "Students Enroll for each module in the course separartely"
![afbeelding](https://github.com/AmpersandTarski/Ampersand/assets/156786695/ffdfccad-800e-4e1e-a3a7-e976c3bfb777)

Upon further inspection in the 'script_generated_pop.json' file generated by the compilation of the script, the relation 'text[Markup*MarkupText]' seems to be filled as normal. 

![afbeelding](https://github.com/AmpersandTarski/Ampersand/assets/156786695/7a5aa15b-acaa-4671-a5f2-4a83663061df)

# Version of ampersand that was used
Latest version of branch formalampersand-meatgrinder-update-example

# Context / Source of ampersand script

CONTEXT Enrollment IN ENGLISH
PATTERN Courses

CONCEPT Student "Someone who wants to study at this institute"
CONCEPT Module "An educational entity with a single exam"
RELATION isEnrolledFor [Student*Module]
MEANING "Students enroll for each module in the course separately"

ENDPATTERN
ENDCONTEXT

**Comment by hanjoosten** [comment]
This issue is caused by an alias mechanism that @stefjoosten and I used in formalampersand. However, the alias mechanism isn't properly implemented.

**Comment by hanjoosten** [comment]
The issue about aliasses is https://github.com/AmpersandTarski/Ampersand/issues/1309
