### ISSUE TITLE
Strange error with Transitive closure

### ISSUE THREAD

**Issue by stefjoosten** [AmpersandTarski/Ampersand#1497]
I'm experimenting with the transitive closure algorithm in a GitHub codespace of project-template@3fb85c6 from April 5th, 2024. My code is below.

# What happened
I got an error from the PHP-level: 
<img width="1078" alt="image" src="https://github.com/user-attachments/assets/7d3550b7-5e59-405b-9c86-2d07d6e367cf">

# What I expected
I expected the Transitive closure algorithm to do something. Or nothing at all if it cannot be found. But this one puzzles me.

# Steps to reproduce

1. Open a new codespace and wait till it says "All good".
2. Paste the code below in the file project/example.adl.
3. Compile everything by giving the command `docker compose up -d --build` in in a terminal and wait until the popup-window allows you to open the prototype.
4. Click the button to open the prototype.

# Context / Source of ampersand script
```Ampersand
CONTEXT KleenePrototype

RELATION r[A*A] = [ ("1","2"), ("2","3"), ("3","4") ]
RELATION s[A*A]

-- The following Exec engine rule is the translation of ENFORCE s >: r+
    RELATION rCopy[A*A] -- necessary only for calling the Transitive closure function.
    ROLE ExecEngine MAINTAINS TransClos
    RULE TransClos : r = rCopy
    VIOLATION (TXT "{EX} TransitiveClosure;r[A*A];A;rCopy[A*A];s")

INTERFACE Overview : "_SESSION"[SESSION] cRud BOX <TABLE>
   [ r : V[SESSION*A] cRud BOX <TABLE>
         [ left : I
         , right : r
         ]
   , s : V[SESSION*A] cRud BOX <TABLE>
         [ left : I
         , right : r
         ]
   ]

ENDCONTEXT
```

**Comment by hanjoosten** [comment]
My first thought is that there will be something wrong with the syntax at PHP interpreter level:`{EX} TransitiveClosure;r[A*A];A;rCopy[A*A];s`. I assume that you have crafted a PHP function somewhere? The error message indicates that there is something wrong with the call to that function.

**Comment by hanjoosten** [comment]
A better way to fix this is the use of `+` and `*`. We only need to spend some time to see how exactly these should be translated to SQL. https://github.com/AmpersandTarski/Ampersand/issues/137 explains how this should be done.
