### ISSUE TITLE
Link to documentation in README doesn't work

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/Ampersand#1504]
# What is the page that your suggestion is about?
https://github.com/AmpersandTarski/Ampersand?tab=readme-ov-file

# What Is your comment?
<!-- You can provide sceenshots, or whatever you think is helpful to us to do better --!>
The text says:

Our **[documentation](https://ampersandtarski.github.io/docs/Ampersand/)** features full-text search and it contains all documentation of several repositories in a single place. We are still https://github.com/AmpersandTarski/Ampersand/issues/1315 on structuring it.

The (bolded) link points to a non-existent page. This prevents me from learning, e.g., what to do with a release I just downloaded, and how I can get it running.

**Comment by hanjoosten** [comment]
Thanks for reporting! It has been fixed.
