### ISSUE TITLE
Priority of the '-'operator

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/ampersand#151]
Currently, there are two flavors of the `-` (minus) operator: a unary and binary one.
The unary minus-operator has highest precedence (that is: over `;`, `!`, `/\`, etc.)
The binary minus-operator however has the same precedence as `;`, `!`, `/\`, etc.
Somehow, this seems unbalanced.
 
I suggest to make the precedence of the binary minus-operator just as high as that of the unary operator. Opinions, anyone?

**Comment by stefjoosten** [comment]
Yes! (comment in the making)
