### ISSUE TITLE
`uml` command gives fatal error

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/Ampersand#1512]
# What happened

![image](https://github.com/user-attachments/assets/6f72aeaf-8c37-4495-b01f-ac3eb548b8cb)

The file `main.adl` compiles a very simple application - which works 

# What I expected
I expected some UML graphics or something to be generated

**Comment by hanjoosten** [comment]
Thanks for reporting this issue. Long time ago we did some experiments to generate a file that could be used with [Enterprise Architect](https://sparxsystems.com/products/ea/). However, the use of it had limited benefits, and it was abandoned. It has obviously bitrotted. The uml command will be removed in a future release.
