### ISSUE TITLE
Using `ENFORCE` to populate `I_Am` doesn't work due to an incorrect expectation of relations starting with lower case

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/Ampersand#1519]
I am using v4.7.7, and have the following script:

~~~
CONCEPT I_Am "Representation of the Actor that the system itself is"

CLASSIFY I_Am ISA Actor

RULE "There can only be one I_Am": V[I_Am] = I[I_Am]
POPULATION I_Am CONTAINS [ "I_Am" ] -- This is what I_Am

ENFORCE I[I_Am] := "I_Am"[I_Am]
~~~

`I_Am` is to be similar to `ONE`, i.e., there can only be one `I_Am`, but there also must be at least one `I_Am`, which is the atom `I_Am`.

To cater for that, I want to use the `ENFORCE` statement - see the above script.
This produces the error

~~~
C:\Git\Ampersand\Demos\siam-demo\project\SIAM_Who_I_Am.adl:11:9 error:
  unexpected keyword "I"
  expecting lower case identifier
~~~

I would have expected that `I` (and `V` for that matter)` would be acceptable for `ENFORCE`.

**Comment by hanjoosten** [comment]
There are two issues here

- unfortunately ENFORCE currently is only implemented for the case where the expression on the left hand side is a binded relation. I agree that it would make sense to also allow l[Some Concept] 
- your rule wouldn't work like you intend. If the population of I_am is empty, what tuple would denote the violation?

**Comment by hanjoosten** [comment]
Implementing `ENFORCE I |- <expr>` (Or one of the other two operators) has to do with the discussion in https://github.com/AmpersandTarski/Ampersand/issues/851

**Comment by RieksJ** [comment]
it is not `ENFORCE ... |-... ` but `ENFORCE ... :=... ` which goes both ways

**Comment by hanjoosten** [comment]
These are indeed the other two operators. But that is beside the point.

**Comment by hanjoosten** [comment]
There are 3 operators: `:=`, `:<` and `>:`. We aren't talking about these operators, but on what is allowed at the left hand side of it. Currently, that may only be a user defined relation. The idea of the ENFORCE statement is that the population of whatever is at the left hand side is being manipulated automatically, based on the expression on the right hand side and the operator that is used. 
It makes sense to also allow `I[SomeConcept]`. It does not make sense to allow `V[SomeConcept*SomeOtherConcept]`. Implementing `I` is what the first bullet above is about.

The second bullet still remains, with or without the implementation of the first bullet.

**Comment by RieksJ** [comment]
My earlier comment was about the second bullet, where you asked "If the population of I_am is empty, what tuple would denote the violation?". I understand `ENFORCE I[I_Am] := "I_Am"[I_Am]` to:
1. check `I[I_Am] -| "I_Am"[I_Am]`, so that it can depopulate `I[I_Am]` if the right hand side population does not have stuff that `I[I_Am]` has (which are the violations), and
2. `I[I_Am] |- "I_Am"[I_Am]`, so that it can populate `I[I_Am]` if the right hand side population has stuff that is not in `I[I_Am]` (which are the violations).

The violation you are asking for would then be `("I_Am","I_Am")`, which is a violation of `I[I_Am] -| "I_Am"[I_Am]`

**Comment by hanjoosten** [comment]
An atom used in a rule doesn't automatically translate to an atom in the database. See the ['Sinterklaas' issue](https://github.com/AmpersandTarski/Ampersand/issues/1519) for the discussion why. Besides that, even if atom would be element of the initial population of the concept, nothing would prevent anyone to delete it later on. That would be valid, because there is no rule that says it cannot be deleted.

**Comment by hanjoosten** [comment]
I created #1520 for allowing `I` . The rest of your issue was explained in the opening and closing again of #166 .
I guess that resolves this issue. @RieksJ , if you disagree, feel free to reopen.
