### ISSUE TITLE
Discussion: Limit CRUD annotations to fields only?

### ISSUE THREAD

**Issue by stefjoosten** [AmpersandTarski/Ampersand#1527]
**Is your feature request related to a problem? Please describe.**

CRUD annotations in interfaces that reflect on the interface term are typically `cRud`.
The same goes for CRUD annotations for the sub-interface term or the INTERFACE redirection.
Here is an example with fields, views, subinterfaces, and redirects:
```Ampersand
   INTERFACE label : term cRud BOX
       [ field        : term CRUD
      , view         : otherterm VIEW<something> cRUd
       , subInterface : term cRud BOX 
                            [ "label" : term cRUD   , etc       ]
      , redirect     : term cRud INTERFACE andereInterface 
      ]
```
At the moment, if I deviate from cRud for interface-terms, sub-interface terms and redirect-terms, I get warnings or error messages. 
It makes me wonder whether these three situations should be made mandatory. 

Is this a good idea or is there a reason why we want to use other crud-annotations than cRud for interface-terms, sub-interface terms and redirect-terms?

**Describe the solution you'd like**
If cRud is fine as a default for interface-terms, sub-interface terms and redirect-terms, we can save ourselves the syntax checking and error messages for this purpose.
But I'm not sure which use cases we can think of for other situations.

**Comment by hanjoosten** [comment]
This issue seems closely related with issues https://github.com/AmpersandTarski/Ampersand/issues/1375, https://github.com/AmpersandTarski/Ampersand/issues/1376.

**Comment by Michiel-s** [comment]
Specifying crud rights for box sub interfaces and interface references absolutely are needed.

As explained e.g. here https://ampersandtarski.github.io/ampersand/reference-material/interfaces#create a crud-C on a expression before `BOX` allows you to be able to add new pairs in the relation by creating a new target. There is no real difference between crud statements for fields (interface leaves), boxes (intermediate) or root expressions. The semantics are defined for the expression, not the interface construct.

A practical example: `INTERFACE "People" : V[SESSION*Person] CRud BOX <TABLE> [ ... ]`. Here the crud-C allows us to create a new Person.

**Comment by Michiel-s** [comment]
I propose to close this issue.
