### ISSUE TITLE
Breadcrumb should be reset after choosing item in top level menu.

### ISSUE THREAD

**Issue by hanjoosten** [AmpersandTarski/ampersand#153]
Currently, the breadcrumb is extended with an item from the menu when it is clicked:

![image](https://cloud.githubusercontent.com/assets/1159672/9353231/1e9b6a88-4667-11e5-80c5-0d11f5e39cab.png)
I would expect that a <path> of atoms is created with the interface that shows that atom (object). That could be reflected in the breadcrumb, leaving out double interfaces.
The path of atoms is cleared each time a menu-item is clicked. (the path then starts with the session atom again)

Please fix or explain the current behaviour, because now it is confusing.

**Comment by Michiel-s** [comment]
Werking is vrij simpel:
- Alle stappen die je doet worden toegevoegd aan de breadcrump. 
       - Voor toplevel interfaces laat hij het interface label zien
       - Voor interfaces met een atom object, laat hij het atom label zien
- Er staan max 5 items in de breadcrumb. Bij de zesde, komt er '...' vooraan te staan
- Indien je teruggaat naar een element dat in de breadcrumb staat (al dan niet via de breadcrumb) dan worden alle items die erachter staan verwijderd.

Suggestie die je doet, om bij klikken op een toplevel interfaces de breadcrumb weer te resetten, lijkt me een goede. Die ga ik oppakken.
