### ISSUE TITLE
Request for attribute interfaceLabel in RouteProvider.js template

### ISSUE THREAD

**Issue by Michiel-s** [AmpersandTarski/ampersand#154]
Hi Han, 

Can you add the attribute `interfaceLabel` in the generation of the RouteProvider.js file. This is done by GenFrontend.hs lines 287 to 297.

Currently already the interfaceNames are provided. Here the special characters are replaced by its ANSI or UNI code (e.g. spaces become _32_). However, in the presentation of interfaceNames to the user I want the original name, without escaping.

The RouteProvider template loops over the interfaceName**s**, this should be changed to looping over the interfaces and for each interface have the attibute interfaceName and interfaceLabel available.

Kind regards,
Michiel

**Comment by hanjoosten** [comment]
This is a very good moment to also implement a very old wish to allow the same name for different interfaces, as long as there is no overlap in roles.

**Comment by Michiel-s** [comment]
Please create a separate ticket for that, because in my opinion it has nothing to do with my request above.
