### ISSUE TITLE
Initialization of a prototype does not complete

### ISSUE THREAD

**Issue by hanjoosten** [AmpersandTarski/ampersand#157]
Currently, the very first time a newly generated prototype is opened, the database gets initialized. There are two problems:

  1.  If the generated initialization script fails, the error is displayed only in a split second. Of course, the generated script must not fail, but alas, sometimes, when changes are made in the generator, this can happen. Such an error should be displayed loud and clear.
  2.  Even when the generated script is fine, the menu bar stays empty (see picture). I would expect that menu interfaces would show, and somthing that makes it show that initialization was succesfull. (succes message?)  . 

![image](https://cloud.githubusercontent.com/assets/1159672/9407429/6688f4ca-4809-11e5-967f-d3e1d42d0167.png)

I would like that the 'out of the box' behaviour is easy to understand for any &-modeller. So either explain or correct.

**Comment by Michiel-s** [comment]
You're correct. I noticed this also a week ago. Fix will follow

**Comment by hanjoosten** [comment]
This causes quite some frustration and unpredicteble behaviour. So I raised the prio

**Comment by Michiel-s** [comment]
@hanjoosten please let me know if you are satisfied with the fix #157
