### ISSUE TITLE
Please allow for reference cycles with LINKTO INTERFACE

### ISSUE THREAD

**Issue by Michiel-s** [AmpersandTarski/ampersand#158]
Consider the following script:
```
CONTEXT Test IN DUTCH

CONCEPT A ""
r :: A * A

INTERFACE Droste : I[A]
    BOX [ "r" : r LINKTO INTERFACE Droste
        ]

ENDCONTEXT
```
This gives the error:
```
Reading file Test2.adl
Error(s) found:
Interfaces form a reference cycle:
- "Droste" at position line 6:1, file Test2.adl

  Error at symbol () in file Test2.adl at line 6 : 1
```

Since the interface boxes AND html templates are not expanded when using a LINKTO INTERFACE, could we allow for this Droste feature?

**Comment by hanjoosten** [comment]
The motivation for not allowing cycles in interfaces is to avoid pages that take infinite time to expand. However, since LINKTO interfaces do not expand, they must not be taken into account when checking for cycles.

**Comment by Michiel-s** [comment]
Thanks for the quick fix

**Comment by Michiel-s** [comment]
Fix for data in fw still needed.
