### ISSUE TITLE
Deleting doesn't seem to work any longer.

### ISSUE THREAD

**Issue by hanjoosten** [AmpersandTarski/ampersand#161]
A couple of days ago, it was possible to delete an object from the interface. There was a trashcan icon. Recently, the trashcan has been replaces by another icon, as can be seen in this screenshot:

![hjo 20150825 11 26 33](https://cloud.githubusercontent.com/assets/1159672/9463316/3ebe7652-4b1c-11e5-9810-e085e044a5fb.jpg)

What happend? What should I do to remove an object from the population in the frontend?

**Comment by Michiel-s** [comment]
Feature to delete atoms is disabled on purpose. Waiting for proper CRUD syntax in INTERFACES

**Comment by Michiel-s** [comment]
Will be fixed when #141 is solved/implemented
