### ISSUE TITLE
Rollen, Sessies en Menu's

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/ampersand#170]
Wat moet er precies gebeuren met rollen in een SESSION? Ik stel het volgende voor:

Er is een drop-downlist van rollen. Als er met LOGIN wordt gewerkt worden die voor elke sessie vvanuit het sessie-account (login-account) gepopuleerd. Anders bestaat de lijst uit alle rollen die in de ADL scripts bekend zijn. De tekst 'no role' wordt vervangen door 'all roles' (wat een betere beschrijving is van het achterliggende idee).

In de lijst met rollen kan achter elke rol een vinkje staan. We zeggen dan dat zo'n rol 'actief is in de sessie'. Als er een vinkje staat achter 'all roles', dan zijn alle rollen die in de drop-down list staan actief (ook als er geen vinkje achter een van die rollen staat).

De gebruiker kan de vinkjes achter de rollen (en achter 'all roles') aan c.q. uitzetten, en zo de rollen (de)activeren.

Het hoofdmenu bestaat uit elke INTERFACE waarvoor geldt dat (1) die vanuit de (current) SESSION gaat, en (2) er voor de INTERFACE geen rol is gespecificeerd dan wel dat er een rol is gespecificeerd die actief is in die sessie.

Voor elk gehyperlinkt atoom is een lijst van INTERFACEs waar naartoe gesprongen kan worden. Bij gebruik van 'LINKTO' bestaat deze lijst uit maximaal 1 element, te weten de INTERFACE waarnaar ge'LINKTO'd wordt. Voor elke INTERFACE in deze lijst geldt dat hij ofwel niet voor een (of meer) rol(len) is gedefinieerd, ofwel dat tenminste een van die rollen actief is in de sessie.

**Comment by Michiel-s** [comment]
Todo:
- [ ] all roles vinkje

**Comment by hanjoosten** [comment]
I have an ampersand script with no roles defined at all. I get an error when I follow a link in a prototype. I get an error 
  
    You do not have access for this call   (api.php, line 285)

Also, I don't understand what is going on any longer.

**Comment by hanjoosten** [comment]
When I add a role to the script. I get different behaviour. This feels buggy?

**Comment by Michiel-s** [comment]
Problem solved.

**Comment by Michiel-s** [comment]
@hanjoosten 

The editableConcepts are not complete yet. Consider:

```
CLASSIFY Lime ISA Citrus
INTERFACE Person (ownsCitrus) : I[Person]
BOX [ "Person atom" : I
        , "ownsCitrus;I[Lime]" : ownsCitrus;I[Lime]
        ]
```
Lime is not added to the list with editableConcepts, while it should be.

**Comment by Michiel-s** [comment]
Everything (except for all roles checkbox) is implemented.
