### ISSUE TITLE
DateTime en tijdzones

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/ampersand#171]
Voorstel om in de database tijdstippen altijd volgens dezelfde tijdzone op te slaan (bijv. GMT), en bij het displayen te converteren naar een 'displaytijdzone', die gelijk is aan
a) als de gebruiker een voorkeur heeft opgegeven (nader te bepalen hoe/wat), dan gebruik je die;
b) als de gebruiker geen voorkeur heeft opgegeven, dan gebruik je de systeem-tijdzone van de client computer.
c) als dat ook niet gaat, dan gebruik je de voorkeurs tijdzone zoals ingesteld in 'localsettings.php' (hoe/wat: tbd)
d) als dat ook niet gaat, dan display je wat er in de database staat (GMT).

Het zou mooi zijn als je met een popover zou kunnen zien in welke tijdzone het gedisplayde tijdstip is.

**Comment by hanjoosten** [comment]
Gebruik hiertoe de REPRESENTatie DATE en/of DATETIME. 

Het effect hiervan is dat er in de database de standaard DATE of DATETIME formaten worden gebruikt.  Die zijn onafhankelijk van de toevallige tijdzone waarin je je toevallig bevindt. 
Afhankelijk van de instelling van je database wordt er bij het bekijken een timezone gebruikt. Die zetten we default op amsterdam (GMT +1 )

In de door Haskell aangeleverde populaties wordt [iso8601](http://www.w3.org/TR/NOTE-datetime) gebruikt. Dat is een notatie die onafhankelijk is van de tijdzone. Die notatie is prima om datum/datumtijd waarden door te geven, zonder je te hoeven bekommeren om de tijdzone. 

Op z'n best zou er nog wat kunnen worden gedaan aan het tonen van datum/tijden in de frontend, maar dat lijkt me niet nodig.

**Comment by RieksJ** [comment]
Dat is ook precies de bedoeling van dit ticket: een aanpassing in het tonen in de frontend van de datum. Dat is bijvoorbeeld nuttig voor NRM wanneer het gebruikt gaat worden door partijen die locaties over de hele wereld hebben.

**Comment by Michiel-s** [comment]
@hanjoosten, @RieksJ 

Het is me gelukt om de **DATETIME** met timezone goed te krijgen. In de database wordt dit opgeslagen in UTC, want daar kunnen we namelijk geen tijdzone inzetten. Om rekenwerk met datetimes in de database mogelijk te houden, moeten we dit ook zo laten en niet een string representatie gebruiken.

Bij de **DATE** loop ik tegen het probleem van tijdzones aan:
* Stel ik heb een datum 31-3-2015 in Amsterdam, dit wordt door de frontend doorgegeven als 2015-03-31T00:00:00+01:00. 
* In UTC is dit 2015-02-28T23:00:00Z. 
* Vervolgens slaan we 2015-02-28 op in de database. 
* Halen we dit er weer uit, dan staat er 2015-02-28T00:00:00Z
* Dit wordt in lokale tijd 2015-02-28T01:00:00+01:00. 
* Door afsnijden van tijd krijgen we na de transformatie de verkeerde datum terug.

Wat mij betreft zijn er twee opties:
1) We maken een datum onafhankelijk van de tijdzone. Dus 31-3-2015 ingevoerd in bv Australië is ook 31-3-2015 wanneer weergegeven in NL.
2) We hanteren wel tijdzones bij datums, maar dan moet de representatie van DATE dezelfde als DATETIME worden.

Welke kant willen we op?

**Comment by RieksJ** [comment]
Tja, wat te doen… Eerst maar de felicitatie dat je de DATETIME met timezone goed hebt. Proficiat!

M.b.t. de DATE: Het rekenen met twee datums die in verschillende tijdzone’s zitten is ambigu, zoals je hebt laten zien. Dat zouden we niet moeten willen. Als je met tijdzones wilt werken, dan moet je met DATETIME gaan werken, zodat het rekenwerk eenduidig wordt. Als je dan toch met alleen een DATE wilt werken (dat is in veel gevallen best legitiem), dan nemen we gewoon aan dat je dat in dezelfde tijdzone doet. Ik ga dus voor optie 1.

Rieks
This message may contain information that is not intended for you. If you are not the addressee or if this message was sent to you by mistake, you are requested to inform the sender and delete the message. TNO accepts no liability for the content of this e-mail, for the manner in which you use it and for damage of any kind resulting from the risks inherent to the electronic transmission of messages.
