### ISSUE TITLE
Getting DelAtom to work properly in the ExecEngine

### ISSUE THREAD

**Issue by stefjoosten** [AmpersandTarski/ampersand#173]
After a fruitful discussion, we ran into multiple issues.

1. A little thing for @Michiel-s to pick up in the front end (I am not sure what exactly, but this will serve as a reminder for Michiel.).
2. The concept table in Generics.php must be filled with the correct conjuncts. This is for @stefjoosten to pick up.

And let's take it from there.

**Comment by stefjoosten** [comment]
I discovered a mistake in the Haskell code for determining conjuncts for concepts. I could fix it, using the observation that a conjunct is "populated" by atoms that are in the source and target concepts of relations used in that conjunct. So the concepts are all concepts in the source and targets of relations used, plus all concepts within (i.e. more specific than) them.

**Comment by Michiel-s** [comment]
Sounds good. Glad you found the mistake. I still have to do a minor bugfix.

**Comment by RieksJ** [comment]
It looks like some other stuff is broken now: the GRC application now gets all sorts of (invariant, e.g. multiplicity) violations that did not occur with earlier versions of Ampersand (and should not occur as far as I'm concerned). I'm not sure though whether or not that is related to this issue, but at least that's what I think.

**Comment by hanjoosten** [comment]
@RieksJ , This might have had todo with some work on the normalizator, which didn't work out very nice. That should be all solved as of commit 27e09da705e5f2efa24bca0485a4419e0565fade . Can you tell if you are still having 'some other stuff is broken'? 
If so, it could well be that now violations are detected that didn't in previous versions. (because of this fixed bug in the normalizer)

**Comment by stefjoosten** [comment]
@Michiel-s: could you fix your end of this bug? Right now this issue is blocking the Braga-presentation, so it is holding up things. Could you please give me a ring when it is fixed? Thx
