### ISSUE TITLE
!fatal 428 (module Core.AbstractSyntaxTree) with Ampersand v3.1.0[master:0f2cc35]

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/ampersand#174]
Try to compile the following script:

     CONTEXT Issue174 IN ENGLISH
     
     bfRLIType :: BusinessFunction * RLIType [UNI]
     impactTypeOf :: Impact * RLIType
     likelihoodTypeOf :: Likelihood * RLIType
     riskTypeOf :: Risk * RLIType
     
     RULE "RLIType integrity": -- invariant
     bfRLIType |- bfRLIType;(impactTypeOf~;impactTypeOf /\ likelihoodTypeOf~;likelihoodTypeOf /\ riskTypeOf~;riskTypeOf)
     MEANING "A BusinessFunction may only use a predefined RLIType"
     VIOLATION (SRC I, TXT " attempts to use the non predefined RLIType '", TGT I, TXT "'")
     
     ENDCONTEXT

Using Ampersand v3.1.0[master:0f2cc35], the result is the following error message:

     ampersand.exe: !fatal 428 (module Core.AbstractSyntaxTree) Ampersand v3.1.0[master:0f2cc35]
     
       Cannot intersect (with operator "/\") expression l of type [BusinessFunction*RLIType]
        EDcD bfRLIType[BusinessFunction*RLIType]
        with expression r of type [RLIType*RLIType]
        EIsc (ECps (EFlp (EDcD likelihoodTypeOf[Likelihood*RLIType]),EDcD likelihoodTypeOf[Likelihood*RLIType]),ECps (EFlp (EDcD riskTypeOf[Risk*RLIType]),EDcD riskTypeOf[Risk*RLIType])).

**Comment by hanjoosten** [comment]
Is bekend. Even vorige versie gebruiken. Of even wachten....

**Comment by stefjoosten** [comment]
Sorry Rieks, iiets te enthousiast een commit gepusht....
