### ISSUE TITLE
Property checkbox misalignment

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/ampersand#179]
Property checkboxes are not nicely aligned with other items in a row. They should also be vertically aligned. I tried, but did not succeed in modifying the template succesfully.

**Comment by Michiel-s** [comment]
Hi Rieks, could you give me a screenshot of your specific situation

**Comment by RieksJ** [comment]
<img width="800" alt="screenshot" src="https://cloud.githubusercontent.com/assets/8522589/9726538/857739c0-55f4-11e5-9482-92513e1e0d90.png">

**Comment by RieksJ** [comment]
Close the ticket - it seems that this is due to the earlier/my own HTML-property-template. The built in one seems to work
