### ISSUE TITLE
Persistent checkbox to clear the database upon Excel-import

### ISSUE THREAD

**Issue by stefjoosten** [AmpersandTarski/ampersand#182]
@Michiel-s,

For the Braga demo we want to reload Excel-imports, refreshing the database with each reload. However, currently the import will be done on top of the current population in the database. This could be resolved by offering a choice in the Excel-import screen. A checkbox called "clear database upon import" would be a good solution. This checkbox should persist, so we can repeat the procedure without having to check it each time.

**Comment by Michiel-s** [comment]
@stefjoosten, I understand your request, however the ExcelImport and reset/clear database  are independent functionalities. Therefore I suggest to not change this is the core of the frontend library.

We do however have the possibility to make project specific changes and include those using the /include folder. I'll make a custom ExcelImporter for your Braga demo and email this to you.
