### ISSUE TITLE
Please comment: Semantics of View Selection

### ISSUE THREAD

**Issue by stefjoosten** [AmpersandTarski/ampersand#184]
The semantics of Ampersand prescribe which View (if any) is to be selected for a particular atom in any given situation. As a consequence, two different front-ends for Ampersand must be guaranteed to produce the same result in every situation.

Currently, the Zwolle front-end does its own selection. In function getView (in file fw\Concept.php) the selection of relevant views for a concept is done from the PHP-table $allViews (in file Generics.php). Another front-end might do a different selection based on the same $allViews.

This part of the semantics of Ampersand should not be delegated to the front-end, but supplied by means of a table.

I propose a table `$viewBy`, that maps every "viewable" concept to the concept of which the view should be used. So Ampersand will guarantee that the viewConcept has a view. In the following example, there are five concepts, four of which have a view (in $allViews). Only `Lime` has no view of its own, so for that concept, the view of `Citrus` must be used.

~~~~
$viewBy=
  array
    (   array ( 'concept' => 'Citrus',  'viewConcept' => 'Citrus' )
    ,   array ( 'concept' => 'Fruit',   'viewConcept' => 'Fruit'  )
    ,   array ( 'concept' => 'Lime',    'viewConcept' => 'Citrus' )
    ,   array ( 'concept' => 'Orange',  'viewConcept' => 'Orange' )
    ,   array ( 'concept' => 'LimOr',   'viewConcept' => 'LimOr'  )
    );
~~~~
Ampersand will guarantee that there is at most one view for every concept, so the behaviour of the front-end will be deterministic.

The proposed semantics are defined in Views.adl, which exists starting from commit 2fa348f. You can experiment with its behaviour by running ViewExperiment.adl and Views.xlsx.

I sollicit feedback on this proposal, especially from @Michiel-s .

**Comment by Michiel-s** [comment]
Hi @stefjoosten 

Please add the required default view to the existing allConcepts array:
```
$allConcepts = array
  ( 'A' => array
      ( 'affectedInvConjunctIds' => array ('conj_0', 'conj_1')
      , 'affectedSigConjunctIds' => array ('conj_2')
      , 'conceptTables' => array
         ( array ( 'table' => 'A', 'cols' => array ('A') )
         )
      , 'type' => 'OBJECT'
      , 'specializations' => array ('B', 'C')
      , 'defaultViewId' => '<here the viewId>'
      )
  , 'Iets' => array()
  )
```
Let me know when you're ready.

**Comment by RieksJ** [comment]
I object to the idea that there is at most one view for every concept. In order to be deterministic, it suffices that

1. there can be at most one DEFAULT view for every concept, and 
2. there must be a DEFAULT view for every concept for which there is an INTERFACE that must show atoms that are in that concept, and for the point at which such atoms are shown there is no explicit view deined.

AFAIK, this is the case today.

**Comment by Michiel-s** [comment]
@RieksJ, this ticket is only about stating the DEFAULT view for a concept. I propose to add this information to the $allConcepts array. This has no impact on scripts, views, etc.

**Comment by hanjoosten** [comment]
I Just had a look at this ticket. In the case that a default view definition exists for a concept (or one of its greater parents), there will be an entry `defaultViewId` for that concept, in $allConcepts, as requested by @Michiel-s . However, it is possible that still no view exists.

**Comment by Michiel-s** [comment]
The backend framework part is not yet done.
