### ISSUE TITLE
Error! 404 Not Found

### ISSUE THREAD

**Issue by sjcjoosten** [AmpersandTarski/Ampersand#186]
I have no user-include files, and just installed a prototype (newFrontend is the new default now, many thanks for that!). Problem is: it doesn't work. I get "Error! 404 Not Found". All menus are empty, except for the Refresh/Reset/Reinstall and the Notification menu. There are no queries in the query log.
Behind the "Error! 404 Not Found" is a number, which keeps increasing every time I reinstall the database.

In the console, there are two "Failed to load resource" messages:
http://localhost/Terms.proto/api/v1/installer?roleId=...
http://localhost/Terms.proto/api/v1/navbar?roleId=...

In the directory Terms.proto/api/v1/, there are only the files Api.php and index.php
I have PHP 5.6 installed.

My guess is that the routing which should be done by index.php is not catching on.. there should be a better error message for this, or, ideally, the issue should be fixed.

For some reason, the url http://localhost/Terms.proto/#/ does work (despite the file # not existing). It seems to be going to index.php in Terms.proto

Let me know if you would like to receive the generated .proto directory.

**Comment by Michiel-s** [comment]
You're probably using a Mac, right? My first guess, based on you're
description of the issue is that the .htaccess file in /api/v1 folder is
not doing its work. I've tested this implementation on windows and Linux
(centos), but not on mac.

Do you know if OS X handles .htaccess files differently?


Op di 8 sep. 2015 om 17:46 schreef Sebastiaan Joosten <
notifications@github.com>

**Comment by sjcjoosten** [comment]
So no, OS X does not handle .htaccess differently, but I had a "AllowOverride None" in my etc/apache2/httpd.conf (which was the default). Can you generate a more helpful error message instead of the 404 not found? (Or alternatively, the v1 api could be built to not rely on the rewriting.)

**Comment by Michiel-s** [comment]
@sjcjoosten does it work after you changed the AllowOverride mode? I think its good to document this in the gitbook under 1.5 'installing and running a prototype'. Could you document your steps there?

The 404 is created by apache. I cannot change this. In the frontend application we cannot distinguish between this error and a regular 404 resource not found. Rewriting the api sound a bit to much hassle for this problem. Don't you think?

**Comment by sjcjoosten** [comment]
Yes, it worked after changing AllowOverride to True. Maybe we should add the message ``This error may be caused if `AllowOverride' is set to False. Please check your Apache configuration.`` in case the navbar has a 404 not found error. Maybe through a call to http://localhost/Terms.proto/api/v1/index.php, which then shows the error. I will see what I can do in the gitbook.
