### ISSUE TITLE
Adding as a smaller atom doesn't work correctly

### ISSUE THREAD

**Issue by hanjoosten** [AmpersandTarski/ampersand#191]
![hjo 20150913 15 16 41](https://cloud.githubusercontent.com/assets/1159672/9836873/77bbcf96-5a2a-11e5-87b6-6f304cc1c60e.jpg)

**Comment by hanjoosten** [comment]
@Michiel-s , is the code that you call from within the framework to add the atom, is that code generated in Generics, or is it built using the information from Generics? In other words, who shoud do this change?

**Comment by hanjoosten** [comment]
This bug is compromizing a smooth Braga-demo.

**Comment by Michiel-s** [comment]
I have to do this, but won't be able to look at this within 2 weeks. You
know the work around.
Op zo 13 sep. 2015 om 15:20 schreef Han Joosten <notifications@github.com>

**Comment by stefjoosten** [comment]
# Diagnosis
The problem occurs because the atom t5 is inserted twice: once as a Term and once as a Composition. Both occurrences must land in the same record, because Composition ISA Term. So the second insert should be an UPDATE rather than an INSERT.

**Comment by stefjoosten** [comment]
This diagnosis contradicts the first solution I suggested: to substitute INSERT by INSERT IGNORE. In fact, this solution removes the symptom and leaves the problem, because it merely omits the second insert. My mistake. Sorry.

**Comment by stefjoosten** [comment]
This diagnosis also contradicts Michiel's workaround, which suggests that a different order of worksheets should work. In that case, however, the message reads:

~~~~~~
Error! Duplicate entry `t5`for key "Primary" in query: INSERT INTO `Composition` (.. etc.
~~~~~~

I have tried Michiel's workaround, with the result as presented here.

**Comment by Michiel-s** [comment]
Issue #201

Consider:
```
CLASSIFY B ISA A
CLASSIFY C ISA A
```
When inserting atom[B], and after that inserting atom[C], a duplicate entry error is shown.

Example:
```Error Duplicate entry 'Invoice' for key 'PRIMARY' in query:INSERT INTO `Name` (`PropertyName`, `Name`) VALUES ('Invoice', 'Invoice')```

**Comment by Michiel-s** [comment]
Fixed
