### ISSUE TITLE
Wrong behaviour with Excell population

### ISSUE THREAD

**Issue by hanjoosten** [AmpersandTarski/Ampersand#194]
The ADL script:

```
CONTEXT Issue194 IN DUTCH
INCLUDE "Issue194.xlsx"
   CLASSIFY Auto ISA Voertuig
   RELATION eigenaar [Voertuig * Persoon] [UNI,TOT]
   RELATION aantalWielen [ Auto * Getal]  [UNI,TOT]
   REPRESENT Getal TYPE INTEGER

   RULE ThisShouldHoldForTheGivenExcelSheet 
     : eigenaar;'Piet';eigenaar~ |- aantalWielen;'4';aantalWielen~
ENDCONTEXT    
```

And given the following Excel population:
![hjo 20150916 13 42 39](https://cloud.githubusercontent.com/assets/1159672/9903711/d3a662bc-5c78-11e5-96af-62a9c82ca5af.jpg)

This leads to the following error:

```
Violations of rule "ThisShouldHoldForTheGivenExcelSheet":
- [("wagen1","wagen1")]

Signals for initial population:
Rule(s): ["ThisShouldHoldForTheGivenExcelSheet"]
  Conjunct   : -(eigenaar;'Piet'[Persoon];eigenaar~) \/ I{-Eps-}[Auto];aantalWielen;'4'[Getal];aantalWielen~;I{-Eps-}[Auto]
  Violations : [("wagen1","wagen1")]

ERROR: No prototype generated because of rule violations.
```

**Comment by RieksJ** [comment]
It may be that the error message could be more helpful, but it is an error, caused by the contents of cell B1, which does not contain a relation name as its contents starts with a CAPITAL A.

**Comment by hanjoosten** [comment]
I am still confused. Yes, it was wrong in specifying the I[Auto] relation in the previous way. So now I am looking for a way to express the intended population. New attempt:

![hjo 20151129 08 55 22](https://cloud.githubusercontent.com/assets/1159672/11455981/0d9a76ec-9677-11e5-9b23-0359828de8ef.jpg)

However, this still does not word,.

So now I am look ing for the correct way to specify this with Excel. ( @RieksJ , could you please help out here?). The next thing is to look if that allready works, or else fix the Excel importer.

**Comment by RieksJ** [comment]
How about specifying the name of the appropriate Concept in cell B7? Does that help?
This message may contain information that is not intended for you. If you are not the addressee or if this message was sent to you by mistake, you are requested to inform the sender and delete the message. TNO accepts no liability for the content of this e-mail, for the manner in which you use it and for damage of any kind resulting from the risks inherent to the electronic transmission of messages.
