### ISSUE TITLE
Difficulties upgrading to Haskell 7.10

### ISSUE THREAD

**Issue by hanjoosten** [AmpersandTarski/ampersand#195]
I have created a branch to enable the upgrade to Haskell 7.10. As far as I can see now, this will not be a backwards compatible upgrade. This means, that all Ampersand developers have to upgrade simultaniously. 
Further, I am unsure what to do with the following error message:

```
src\Database\Design\Ampersand\ADL1\P2A_Converters.hs:766:68:
    No instance for (Foldable t3) arising from a use of `elem'
    The type variable `t3' is ambiguous
    Relevant bindings include
      lst :: [t3 String]
        (bound at src\Database\Design\Ampersand\ADL1\P2A_Converters.hs:766:27)
    Note: there are several potential instances:
      instance Foldable (Const m) -- Defined in `Control.Applicative'
      instance Foldable (Either a) -- Defined in `Data.Foldable'
      instance Foldable Data.Functor.Identity.Identity
        -- Defined in `Data.Functor.Identity'
      ...plus 44 others
    In the first argument of `map', namely `(name (source e) `elem`)'
    In the first argument of `and', namely
      `(map (name (source e) `elem`) lst)'
    In the second argument of `(||)', namely
      `and (map (name (source e) `elem`) lst)'
cabal: Error: some packages failed to install:
ampersand-3.1.0 failed during the building phase. The exception was:
ExitFailure 1
```

I assume (hope?) that @sjcjoosten will know how to handle this. 

So far,things that need(ed) to be done for the upgrade:
  * [x] upgraded all packages in the .cabal file, so that should be OK. 
  * [x] fixed some Pandoc things (Pandoc now gives error handling support for readers of several formats). This will likely not work in ghc <7.10.
  * [ ] Prelude now exports (<$). I do not know if that function is the one we need.
  * [ ] Control.Applicative seems to get redundant at places. I commented some out, but I do not know if that is the right thing to do. 
  * [ ] Before we merge the pull request for this branch into master, we have to agree as a team.

**Comment by sjcjoosten** [comment]
Yup, change the binding lst :: [t3 String] to lst :: [[String]]

**Comment by sjcjoosten** [comment]
So to explain what is going on:

in ghc 7.10, some functions became more general. In particular functions that acted on lists, now act on more general classes. So in most cases, adding a type signature to indicate that you want to act on a list, should suffice. We could of course also add the Foldable requirement.

**Comment by sjcjoosten** [comment]
This is fixed now, I changed the result to always yield Set.Set (instead of any `setlike' thing), with an explicit toList at some places in the P2A_Converters code.
