### ISSUE TITLE
Make Generics(.php) platform independent

### ISSUE THREAD

**Issue by Michiel-s** [AmpersandTarski/ampersand#197]
This issue describes a proposal to change the way by which the generated info from ampersand is provided to the backend framework. Currently all information is generated to Generics.php, a php file containing several php arrays. I propose to change this to *multiple JSON files*. *JSON* because it makes the generated information platform independent. *Multiple files* because that is more convenient to manually browse through, to e.g. bug fix.

The files are:
 - [x] mysql-installer.json
 - [x] concepts.json
 - [x] relations.json
 - [x] rules.json
 - [x] interfaces.json
 - [x] settings.json
 - [x] conjuncts.json
 - [x] ~~tables.json~~ can be removed. not used.
 - ~~services.json~~ do not implement. old experiment, not used anymore
 - [x] views.json
 - [x] roles.json

Implement in backend (Michiel):
 - [x] mysql-installer.json
 - [x] concepts.json
 - [x] relations.json
 - [x] rules.json
 - [x] interfaces.json
 - [x] settings.json
 - [x] conjuncts.json
 - ~~tables.json~~
 - ~~services.json~~
 - [x] views.json
 - [x] roles.json

All files should satisfy the JSON specification (see http://www.json.org for an introduction)
php arrays can be easily converted into json arrays and objects.

**mysql-installer.json**
```
{ "allDBstructQueries" : 
  [ "<query1>"
  , "<query2>"
  , "<etc>"
  ]
, "allDefPopQueries" :
  [ "<query1>"
  , "<query2>"
  , "<etc>
  ]
}
```

**concepts.json**
* interfaces should contain the IDs of the toplevel interfaces that have the concept (or its generalizations) specified as SrcConcept.
* defaultViewId should specify the default view using the following reasoning:
1: If there is a view defined for this concept that is marked DEFAULT => use that one
2: If there is a view defined for a generalization concept that is marked DEFAULT => use the smallest one (if there are more than 1 smallest, just pick one!)
3: If there is no DEFAULT view defined => `null` (do not use a view here that is not marked default)
 
```
[ { name : "ConceptA"
  , type : "OBJECT"
  , generalizations : [ "ConceptX", ConceptY, "etc" ]
  , specializations : [ "ConceptB", ConceptC, "etc" ]
  , affectedConjuncts : [ "conj1", "conj2", "etc" ]
  , interfaces : [ "ifcA", "ifcB", "etc" ]
  , defaultViewId : "<name of default view>"
  , conceptTable : { name : "<table name>"
                            , cols : [ "<col1>", "<col2>", etc ]
                            }
}
, { another concept }
]
```

**relations.json**
`tableOf` specifies if relation is administrated in table of srcConcept, tgtConcept or its own (n-n table)
```
[ { name : "rel"
  , signature : "rel[SrcConcept*TgtConcept]"
  , srcConcept : "SrcConcept"
  , tgtConcept : "TgtConcept"
  , uni : true|false
  , tot: true|false
  , inj : true|false
  , sur : true|false
  , affectedConjuncts : ["conj1", "conj2", "etc"]
  , mysqlTable : { name : "<table name>"
                         , tableOf : "src"|"tgt"|null
                         , srcCol : {name : "<col name>", null : true|false, unique : true|false}
                         , tgtCol : {name : "<col name>", null : true|false, unique : true|false}
                         }
  }
, { second relation }
, { etc }
]
```

**roles.json**
maintains = rule names/ids of rules that are maintained by this role
interfaces = interface ids of interfaces that are available to this role (including the interfaces for every role)
```
[ { id : <increasing nr>
  , name : "<role name>"
  , maintains : ["<rule1>", "<rule2>", "<etc>"]
  , interfaces : ["<interface1>", "<interface2>", "<etc>"]
  }
, { second role }
, { etc }
]
```
**rules.json**

**interfaces.json**

**settings.json**
generateConstants from Generate.hs (*isDev* and *autoRefreshInterval* are obsolete)
mysql settings from ObjBinGen.hs
```
{ "versionInfo" : "<versionInfo>"
, "contextName" : "<contextName>"
, "mysql-settings" : 
  { "dbHost" : "<dbHost>"
  , "dbName" : "<dbName>"
  , "dbUser" : "<dbUser>"
  , "dbPass" : "<dbPass>"
  , "signalTableName" : "<signalTableName>"
  }
}

**Comment by hanjoosten** [comment]
I think this is a good idea. The way to go would be to create these files beside the current .php files. Only when we all are happy with the contents in the .json files, and the frontend fully uses the .json files, the .php files will become obsolete.

**Comment by hanjoosten** [comment]
The approach to this (from a Haskell pov, would be to create a haskell data structure for each of these files, populate them using fspec. Then, by using the [Aeson package](http://hackage.haskell.org/package/aeson-0.10.0.0/docs/Data-Aeson.html) to convert each of them to a json file.
This should be pretty straitforward.

**Comment by hanjoosten** [comment]
Hi Michiel, 
I have built relations.json in a slightly different way. I have put all conjuncts of that relation in one array. That is closer to the Ampersand structure. 
A conjunct itself isn't signal or invariant. However, the rule where the conjunct is from has that property. It is possible to denormalize the property of the rule to a property of a conjunct, but that might have nasty consequences later on. I think that in the end you'd have nicer code when we keep it this way. 

However, if you have a good reason to split at this level, then it can be done.

**Comment by hanjoosten** [comment]
I also added prettyprinting of the .json files

**Comment by hanjoosten** [comment]
Without any specification of Michiel, I made a rules.json. @Michiel-s , Let me know what you think about this!

**Comment by Michiel-s** [comment]
@hanjoosten 

Take a look at the output of mysql-installer.json:
```
{
    "allDBstructQueries": [
        "$allDBstructQueries =",
        "  array ( 'CREATE TABLE \"__SessionTimeout__\"",
        "            ( \"SESSION\" VARCHAR(255) UNIQUE NOT NULL",
        "            , \"lastAccess\" BIGINT NOT NULL",
        "            ) ENGINE=InnoDB DEFAULT CHARACTER SET UTF8 COLLATE UTF8_BIN'",
        "        , 'CREATE TABLE \"__History__\"",
...
```
A couple of things need fixing:
* The `$allDBstructQueries =` is part of the php definition. This should not be here
* This also applies to the `array (`
* The `'CREATE TABLE .... COLLATE UTF8_BIN'` is one query and should be 1 item in the json array.
* The single quotes around a query are not needed anymore. This was due to the php string. In JSON this is replaced by the single quotes.
* Double quotes need to be escaped.

**Comment by Michiel-s** [comment]
@hanjoosten 

The rules.json look good, except for the 'expSQL' field of a pairView item. It contains '\n' and space characters. These should be removed.

Furthermore, I saw that you've added a 'segmentNr'. Can you guarantee that these are put in the right order in the pairView array?

**Comment by Michiel-s** [comment]
@hanjoosten 

The **relations.json** is ok, except for the 'signature' field of a relations. It now contains `[Src*Tgt]`. However, the full signature should also contain the relation name: `rel[Src*Tgt]`

**Comment by Michiel-s** [comment]
I've updated the initial post and added specification for **concepts.json**

**Comment by hanjoosten** [comment]
On your comments about **mysql-installer.json:**
Hmm. You are right. I went too fast. I could have noticed most of your issues myself. Sorry. 
About order in Json: There isn't any! So I added a seqNr to the queries. It looks however that the array is kept in order anyway. Not sure if that is by accident or if you may trust that ordering.

**Comment by hanjoosten** [comment]
Also fixed the other issues unto this comment.

**Comment by hanjoosten** [comment]
Michiel, I am not sure the segments of the viewdefinitions in concepts.json are generated correctly. Do you have a nice test-model somewhere?

**Comment by Michiel-s** [comment]
Hi @hanjoosten ,

I've updated the specification for the concepts.json file.

Could you please add the `mysqlConceptTables` information?

Michiel
The new spec:
```
[ { name : "ConceptA"
  , type : "OBJECT"
  , generalizations : [ "ConceptX", ConceptY, "etc" ]
  , specializations : [ "ConceptB", ConceptC, "etc" ]
  , affectedConjuncts : [ "conj1", "conj2", "etc" ]
  , interfaces : [ "ifcA", "ifcB", "etc" ]
  , views : [ { label : "Name of view"
                  , isDefault : true/false
                  , segments : []
                  }
                , { another view for this concept, including generalization views }
                ]
  , mysqlConceptTables : [ { tableName : "<table name>"
                                          , conceptCols : [ { colName : "<col1>" }, { colName : "<col2>"}, etc ]
                                          }
                                          , { another table (does this occur in practice??) }
                                        ]
  }
, { another concept }
]
```

**Comment by Michiel-s** [comment]
Hi @hanjoosten,

Could you change the specs for the **relations.json** to the following:

Instead of srcMin, srcMax, tgtMin and tgtMax, let us just specify the uni,tot,inj and sur properties.
```
[ { name : "rel"
  , signature : "rel[SrcConcept*TgtConcept]"
  , srcConcept : "SrcConcept"
  , tgtConcept : "TgtConcept"
  , uni : true/false
  , tot: true/false
  , inj : true/false
  , sur : true/false
  , affectedConjuncts : ["conj1", "conj2", "etc"]
  }
, { second relation }
, { etc }
]

**Comment by hanjoosten** [comment]
mysqlConceptTables has become mysqlConceptTable, for there will be exactly one table in each case.

**Comment by hanjoosten** [comment]
@Michiel-s  more wishes for the .json files? let me know!

**Comment by Michiel-s** [comment]
@hanjoosten, you've implemented the structure of concept.json slightly different than specified above. Fine by me, the backend already takes your implementation.

Things you've implemented differently:
* key `mysqlConceptTables` -> `conceptTable`
* key `tableName` -> `name`
* key `conceptCols` -> `cols`
* array in `cols` is not an array of object, but array of colnames
* key `colName` thus not implemented

Should we update the specs above?

**Comment by Michiel-s** [comment]
@hanjoosten 

For some reason I don't see roles.json yet. 

Specification:
**roles.json**
maintains = rule names/ids of rules that are maintained by this role
interfaces = interface ids of interfaces that are available to this role (including the interfaces for every role)
```
[ { id : <increasing nr>
  , name : "<role name>"
  , maintains : ["<rule1>", "<rule2>", "<etc>"]
  , interfaces : ["<interface1>", "<interface2>", "<etc>"]
  }
, { second role }
, { etc }
]
```

**Comment by Michiel-s** [comment]
Implemented views.json in 0c4fad46353a4732753c0dacb66f37c534c49cd1

**Comment by Michiel-s** [comment]
@hanjoosten 

I've updated the specs for the `relations.json`. Could you add the mysql table information exactly as specified below. The `tables.json` file can be removed.

**relations.json**
`tableOf` specifies if relation is administrated in table of srcConcept (i.e. `"src"`), tgtConcept (i.e. `"tgt"`) or its own n-n table (i.e. `null`).
```
[ { name : "rel"
  , signature : "rel[SrcConcept*TgtConcept]"
  , srcConcept : "SrcConcept"
  , tgtConcept : "TgtConcept"
  , uni : true|false
  , tot: true|false
  , inj : true|false
  , sur : true|false
  , affectedConjuncts : ["conj1", "conj2", "etc"]
  , mysqlTable : { name : "<table name>"
                         , tableOf : "src"|"tgt"|null
                         , srcCol : {name : "<col name>", null : true|false, unique : true|false}
                         , tgtCol : {name : "<col name>", null : true|false, unique : true|false}
                         }
  }
, { second relation }
, { etc }
]
```

**Comment by Michiel-s** [comment]
Hi @hanjoosten 

I've updated the concept.json specs. Please add the `defaultViewId` attribute. The old array with all view definitions (`views` attribute) can be removed here.

**concepts.json**
* interfaces should contain the IDs of the toplevel interfaces that have the concept (or its generalizations) specified as SrcConcept.

* defaultViewId should specify the default view using the following reasoning:
1: If there is a view defined for this concept that is marked DEFAULT => use that one
2: If there is a view defined for a generalization concept that is marked DEFAULT => use the smallest one (if there are more than 1 smallest, just pick one!)
3: If there is no DEFAULT view defined => `null` (do not use a view here that is not marked default)
 
```
[ { name : "ConceptA"
  , type : "OBJECT"
  , generalizations : [ "ConceptX", ConceptY, "etc" ]
  , specializations : [ "ConceptB", ConceptC, "etc" ]
  , affectedConjuncts : [ "conj1", "conj2", "etc" ]
  , interfaces : [ "ifcA", "ifcB", "etc" ]
  , defaultViewId : "<name of default view>"
  , conceptTable : { name : "<table name>"
                            , cols : [ "<col1>", "<col2>", etc ]
                            }
}
, { another concept }
]
```

**Comment by Michiel-s** [comment]
Implemented `roles.json` in 72458e7b5634446c3cac15c2374e25a20a8c296b

**Comment by Michiel-s** [comment]
All json files are implemented in the backend.

**Comment by hanjoosten** [comment]
I cleaned up conform issue #198. I also modified the Cruds a little in the interface.json file, as we have spoken of before. The cruds are now in one object together, at all places. It might be that some of the connections with the backend is broken by that action. @Michiel-s, please check this, then you can close this issue again.

**Comment by Michiel-s** [comment]
All ok.
