### ISSUE TITLE
Rename static folders

### ISSUE THREAD

**Issue by Michiel-s** [AmpersandTarski/ampersand#200]
After we made the newFrontend the default switch for generating prototypes and we call this the Zwolle interface, I propose to rename those static folders:

newFrontend -> zwolle
oldFrontend -> "what's the name again?"

I also propose to rename the static folder to 'interfaces' or 'prototypes' to specify what it is about.

**Comment by hanjoosten** [comment]
I will clean up the oldFrontend folder all together. If for some reason we still need it, we can recover it with git. There is no use in leaving it in the current branch.

**Comment by sjcjoosten** [comment]
yay for this! Maybe we will finally be categorised as a Haskell project :-)

**Comment by hanjoosten** [comment]
@sjcjoosten  HaHa, might be. Let's see about that. Otherwise, you might want to try some tricks mentioned [here](https://help.github.com/articles/my-repository-is-marked-as-the-wrong-language/). This IS a Haskell project. Right?
