### ISSUE TITLE
Creating pairs in Atoms.ifc

### ISSUE THREAD

**Issue by stefjoosten** [AmpersandTarski/ampersand#202]
Try to compile and run [Atoms.ifc](https://github.com/AmpersandTarski/ampersand/blob/master/AmpersandData/FormalAmpersand/Atoms.ifc).  I can create atoms, and then use them when creating pairs. Everything works fine.
Now I want to do that without creating atoms, by letting the Exec-engine create atoms for me. Somehow, I cannot get it done. Does @RieksJ or @Michiel-s have an idea how this can be done?

**Comment by RieksJ** [comment]
I assume that your question is this: How can I create a Pair, which includes (new) Atoms? In other words: How do I create  a new atom in the concept 'Pair', and populate the relations 'l', 'r', and 'in[Pair*Relation]' using that newly created atom. I assume that an atom in Atom has only the relation repr to be populated.

I have checked in a new Atoms.ifc that shows the ideas of how to do this. I have not compiled it, so you may encounter some typos...

**Comment by stefjoosten** [comment]
thx @rjoosten. Your interpretation of the problem is consistent with mine. I'll look into your solution and try to run it at first opportunity. Did you notice any mistake on my part that caused my problem?

Verzonden vanaf Samsung Mobile


-------- Oorspronkelijk bericht --------
Van: Rieks
Datum:24-09-2015 20:30 (GMT+01:00)
Aan: "Joosten, Stef"
Onderwerp: Re: [ampersand] Creating pairs in Atoms.ifc (#202)

I assume that your question is this: How can I create a Pair, which includes (new) Atoms? In other words: How do I create a new atom in the concept 'Pair', and populate the relations 'l', 'r', and 'in[Pair*Relation]' using that newly created atom. I assume that an atom in Atom has only the relation repr to be populated.

I have checked in a new Atoms.ifc that shows the ideas of how to do this. I have not compiled it, so you may encounter some typos...

—
Reply to this email directly or view it on GitHub<https://github.com/AmpersandTarski/ampersand/issues/202#issuecomment-143012796>.

________________________________
Deze e-mail is uitsluitend bestemd voor de geadresseerde(n). Verstrekking aan en gebruik door anderen is niet toegestaan. Open Universiteit sluit iedere aansprakelijkheid uit die voortvloeit uit elektronische verzending. Aan de inhoud van deze e-mail en/of eventueel toegevoegde bijlagen kunnen geen rechten worden ontleend.

This e-mail is intended exclusively for the addressee(s), and may not be passed on to, or made available for use by any person other than the addressee(s). Open Universiteit rules out any and every liability resulting from any electronic transmission. No rights may be derived from the contents of this message.

Disclaimer
Dit bericht met eventuele bijlagen is vertrouwelijk en uitsluitend bestemd voor de geadresseerde. Indien u niet de bedoelde ontvanger bent, wordt u verzocht de afzender te waarschuwen en dit bericht met eventuele bijlagen direct te verwijderen en/of te vernietigen. Het is niet toegestaan dit bericht en eventuele bijlagen te vermenigvuldigen, door te sturen, openbaar te maken, op te slaan of op andere wijze te gebruiken. Ordina N.V. en/of haar groepsmaatschappijen accepteren geen verantwoordelijkheid of aansprakelijkheid voor schade die voortvloeit uit de inhoud en/of de verzending van dit bericht.

This e-mail and any attachments are confidential and are solely intended for the addressee. If you are not the intended recipient, please notify the sender and delete and/or destroy this message and any attachments immediately. It is prohibited to copy, to distribute, to disclose or to use this e-mail and any attachments in any other way. Ordina N.V. and/or its group companies do not accept any responsibility nor liability for any damage resulting from the content of and/or the transmission of this message.

**Comment by stefjoosten** [comment]
New insights from Braga. I have redone Atoms.adl and it has become a lot simpler. 2 relation-algebra specialists have cursed our use of repr. Indeed, the Atoms.adl looks better and works well (which it didn't before). The only thing that is lacking is Ampersand allowing me to use every atom (both with and without a technical type) in the same way. Lesson I learned here: If I have a reason to want to use a typed atom (i.e. scalar) as an ugly identifier, relation algebra gives no reason why that must be forbidden.

**Comment by stefjoosten** [comment]
@Michiel-s ,
I hope there is a way to implement a solution to
Error! 501 Not Implemented: TgtConcept of interface: 'atoms' is scalar and can not have subinterfaces

**Comment by RieksJ** [comment]
@stefjoosten: Did the relation algebra experts not like the purpose you specified for 'repr'?

**Comment by RieksJ** [comment]
If I remember correctly, 'atoms' are ideas (information), and in order to refer to them you need to have an (arbitrary) representation (data). Changing the representation (within the limits imposed by rules) is allowed, as it does not change the atom (idea). For example, I am now thinking about an atom I could represent by '1' or 'I' or 'one'  or 'the smallest integer that is greater than zero'. If there are no atoms that have a representation, I may think about them, but I cannot talk/write about them, or store them. That may be very well in mathematics, but it is useless in the real world. Any further ideas (in some kind of representation)?

**Comment by RieksJ** [comment]
Pondering about the scalar discussion, I noticed that there is a difference between a non-scalar atom and a scalar atom: a scalar atom is actually defined by its dirty identifier (repr), meaning that if you change this dirty identifier, you replace the atom with another one. With non-scalar atoms, however, the dirty identifier merely serves as a name/identifier/representation, and its value is allowed to change ad libitum (provided it does not take a value that already exists in the atom's concept classification).

**Comment by RieksJ** [comment]
Stef sayd "If I have a reason to want to use a typed atom (i.e. scalar) as an ugly identifier, relation algebra gives no reason why that must be forbidden." I have no problem with this statement, since:
* within RA, you do not care about representations (data), since RA is about ideas (information).
* the fact that RA does not object does not imply that objections could not be raised from other directions. 
(Welterusten...)

**Comment by stefjoosten** [comment]
@RieksJ said: Did the relation algebra experts not like the purpose you specified for 'repr'?

There is no problem with having repr. It just doesn't belong in the atoms pattern, because it is less fundamental than I thought earlier. It can (and will be) used for good purposes, of course.

**Comment by stefjoosten** [comment]
After discussions with @RieksJ and @Michiel-s (thx guys for helping me out here!) , my perspective on this issue has changed (i.e. become sharper). The problem has started to look a whole lot simpler (for me)

In the past, all atoms were implemented as strings. Today, atoms can have different technical representations, each of which will (in the future) impose different algebras/functionality. For instance: numbers can be added, and strings can be concatenated.

This particular issue discusses the functionality of atoms without an explicit technical type. Currently, such atoms can for example be used as an object-key in the front-end, aka ugly identifiers. Ampersand allows such atoms to be used as a root atom for interfaces at run-time. The current problem can be solved simply by allowing these atoms to be edited.

So much for now...
