### ISSUE TITLE
Feature request: Skins

### ISSUE THREAD

**Issue by hanjoosten** [AmpersandTarski/ampersand#204]
The default look-n-feel of the prototype currently has the TNO logo. It would be nice to have two or three different skins, that could be automatically generated based on a command-line switch. For example, the skin used in Braga could be fit for one of them. 
@Michiel-s, I assume that we should have some 'skins' folder? What exacly should be in it, and what should be generated from within Haskell to get this all to work?

**Comment by Michiel-s** [comment]
I'm already working on this feature. I don't think we should implement this on the Haskell part. It's all static, nothing has to be generated. I suggest to have a default Ampersand header and style. App or organization specific styles can be put into the include folder, which is copied during the prototype generation.
