### ISSUE TITLE
Add insert and update timestamps to database tables

### ISSUE THREAD

**Issue by Michiel-s** [AmpersandTarski/ampersand#205]
I would like to have two additional columns in every table:
1) ts_insert, to specify the timestamp when the row is inserted
2) ts_update to specify the timestamp when the row is updated last.

This provides an easy way to track database activity. E.g. when is an atom added or updated.
To enable this, the following SQL column statements have to be added to the database installer, especially the one that generates $allDBstructQueries and $allDefPopQueries in Generics.php (Generate.hs)

`"ts_insert" TIMESTAMP DEFAULT CURRENT_TIMESTAMP`
`"ts_update" TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NULL`

**Comment by Michiel-s** [comment]
Hi Han, 

I added the mentioned columns and it works. Could you check if same changes are required in other places?

**Comment by hanjoosten** [comment]
Splendid! You did a great job writing Haskell!
I guess we don't require  this behaviour in the sessiontimeout , History and allSignals tables?. Otherwise, these same statements could be copied at the appropriate places in the area of lines 114-134.
Then this issue could be closed.
