### ISSUE TITLE
Request to add 'verbose' variable to templates

### ISSUE THREAD

**Issue by Michiel-s** [AmpersandTarski/ampersand#206]
For debugging purposes, the html and controller templates for the zwolle frontend contain a lot of comments related to the generator. I would like to have a conditional clause around those comments, to be able to switch them on/off.

I suggest to add the `verbose` variable so we can use `$if(verbose)$......$endif$` and connect it to the --verbose switch which is already present in ampersand.

**Comment by hanjoosten** [comment]
I am not sure if this is what you mean, but I added a boolean attribute _verbose_ to the contents of templates. Please close this issue if this does the job. If not, let me know what you mean.
