### ISSUE TITLE
Request for editable concepts per Role

### ISSUE THREAD

**Issue by Michiel-s** [AmpersandTarski/ampersand#211]
For API access management I require a list of editable concepts per role.

This list should contain the names of all concepts that are used as target of expressions that are editable in interfaces for that specific role. Keep in mind that the expression can be flipped (~) and that I require the target of the expression, not the target of the relation.

Could this be added as array in $allRoles in Generics.php as specified below.

```
allRoles =
  array
    ( array ( 'id' => 1
            , 'name' => 'ExecEngine'
            , 'ruleNames'  => array ()
            , 'interfaces' => array ()
            , 'editableConcepts' => array('<conceptA>', '<conceptB>', etc)
            )
```

**Comment by hanjoosten** [comment]
I realized that the fix I made isn't correct. There will be too much concepts marked as editableConcepts. However @Michiel-s , You could just use the list in the FE. I will fix this issue at the end of this week.
