### ISSUE TITLE
Rethink the way we release ampersand

### ISSUE THREAD

**Issue by hanjoosten** [AmpersandTarski/Ampersand#213]
Uses on different platforms, and different versions of ghc are struggling to install Ampersand in a smooth way. 

Wolfram Kahl writes:
> Perhaps you should have a single separate package that supports your Setup.hs,
> similar to the way this is handled by gtk2hs, where they have
> http://hackage.haskell.org/package/gtk2hs-buildtools for also that purpose.
> Then that separate package could have dependencies on the right (old-)time
> versions, and easily also on other useful material like filemanip and
> http://hackage.haskell.org/package/tar .

An additional issue is that we put the allstaticfiles into the binary. This doesn't work for the distribution of Ampersand via Hackage. That means that a simple installation of haskell, and then use cabal to get ampersand from Hackage does not work. The static files are not present, because we do not want to maintain all those files into ampersand.cabal as data-files.

**Comment by sjcjoosten** [comment]
How about maintaining all static files within another git-repo, and having 1 zip for all the static files?

**Comment by Michiel-s** [comment]
I'm looking into a solution to include all static files in another way. Currently dependencies to other libraries we need in the backend framework are added to the static folder. We basically copy those libraries into our own. This is not a nice way do so. 

The backend framework for the ampersand prototype is now implemented in PHP. Tools like Composer (https://getcomposer.org/) provide functionality to define dependencies to other libraries. I'm thinking of defining the Ampersand backend framework (all static files) as a library itself and let generated prototypes have a dependency to this backend. 

To deploy prototypes you would require Composer on your machine and have to run 'composer install' after you generated the prototype with ampersand. @sjcjoosten the Ampersand repo will become a Haskell project again I think.

You guys any thoughts on this matter? @hanjoosten @stefjoosten

**Comment by hanjoosten** [comment]
Sounds good. I had a quick look at Composer, but not long enough to find the answer to the following questions:

  1. Would an ampersand modeller need to have Composer installed to generate a prototype?
  2. Would it be required to have composer installed to be able to deploy a prototype?

**Comment by Michiel-s** [comment]
1) no, the generated files would be still provided by the ampersand executable. You can't however run the prototype because you need the backend fw files.
2) yes, or download all dependencies, incl. backend fw, manually (from github).

**Comment by hanjoosten** [comment]
So this would mean that a user of Ampersand would need to install not only a Xampp-like stack, but also composer? (Which [seems](http://www.techflirt.com/install-composer-xampp) quite simple)

**Comment by hanjoosten** [comment]
You probably need a repo to experiment with this? If so, what name should it have?

**Comment by stefjoosten** [comment]
I disagree with @sjcjoosten that we want to separate our static files into a separate git-repo. Synchronisation between different repos requires human effort. That gives us more mistakes. I think we would rather wish to integrate git-repos than to split them up. That lets Git do the work for us and saves on mistakes on our part.

**Comment by stefjoosten** [comment]
I would appreciate @Oblosys ' perspective on this matter. Any opinions, Martijn?

**Comment by hanjoosten** [comment]
We seem to loose focus on what the problem is we are suggesting solutions for. I see the following problems:

  1) The ampersand executable is (was!) not portable, in a sense that distributing a single binary wasn't enough. 
  2) We include a lot of resources from libraries into ampersand.exe This makes the executable large. But is this a problem?
  
What other problems do we have, that we are trying to find a solution for? 

My point: Define the problem, before we discuss solutions.

**Comment by Michiel-s** [comment]
You stated the problem yourself in the first post:
> An additional issue is that we put the allstaticfiles into the binary. This doesn't work for the distribution of Ampersand via Hackage. That means that a simple installation of haskell, and then use cabal to get ampersand from Hackage does not work. The static files are not present, because we do not want to maintain all those files into ampersand.cabal as data-files.

**Comment by hanjoosten** [comment]
True. The core problem is that cabal demands that every file is mentioned explicitly in the .cabal file. This is a maintanance burden that is too big to handle manually.

**Comment by sjcjoosten** [comment]
Shall we put 1 .zip in the cabal file instead? It should be relatively easy to change Setup.hs to read a .zip (or the like), as Setup.hs already imports some .zip functions

**Comment by WolframKahl** [comment]
On Wed, Dec 16, 2015 at 04:30:03AM -0800, Han Joosten wrote:
> We seem to loose focus on what the problem is we are suggesting solutions for. I see the following problems:
> 
>   1) The ampersand executable is (was!) not portable, in a sense that distributing a single binary wasn't enough. 
>   2) We include a lot of resources from libraries into ampersand.exe This makes the executable large. But is this a problem?
>   
> What other problems do we have, that we are trying to find a solution for? 

Even though the ampersand executable contains a lot of PHP material,
the generated prototype still depends on other PHP libraries, and
web server modules and settings. I found some of this out when I tried to
run prototypes on PC-BSD (essentially FreeBSD), where apache and PHP
come with slimmer core distributions than on my gentoo linux.
I haven't fully succeeded yet, and would appreciate precise listings
of PHP dependencies and required apache settings.

You may also want to check whether the ampersand executable is legally distributable,
and not violating any of the licences of software it contains.


> What other problems do we have,

The mere presence of PHP...  ;-)


Wolfram

**Comment by WolframKahl** [comment]
On Wed, Dec 16, 2015 at 04:43:53AM -0800, Han Joosten wrote:
> True. The core problem is that cabal demands that every file is mentioned explicitly in the .cabal file. This is a maintanance burden that is too big to handle manually.  

Well, you could generate the .cabal file automatically, just moving the static
directory traversal from ./Setup runtime to .cabal generation time.
Can git/github automate this for you, so it is re-done at every commit?

(Something like hastache might be one option for coding the real
 .cabal.source .)

**Comment by Oblosys** [comment]
In my opinion it would be a very bad idea to put the Ampersand-specific statics in a separate repo, as they are part of the Ampersand code base. Decoupling them will create headaches when switching branches or going back in history. Moreover, because the static files are not Haskell, you probably won't notice any mismatches until run time.

The libraries and frameworks in the statics could be handled by some external package manager like composer, but this will add some extra complexity to the installation process. I think my choice would be to include these zipped. This way it is also easy to be sure that the versions at the user's installation are exactly the ones we use during development.

Including static files in cabal is tricky because 'data-files' still doesn't allow recursive paths and it looks like that's not going to change anytime soon. Keeping the dependencies in seperate zips, makes maintenance a bit easier, but it may still be to error prone. Maybe we can add a script to the Travis test that checks whether all static files are indeed included by cabal and lists the paths that are missing? This shouldn't be too hard, and will also make it easy to update the cabal file after changing the static directory structure. It will also work for the dependencies, but they may clutter the cabal file a bit if they contain a lot of subdirectories, so zipping them may still be a good idea.

**Comment by Oblosys** [comment]
Generating the cabal file, as Wolfram suggests is also an option. I considered that last year but dismissed it due to the added complexity. If something goes wrong with generated build scripts things can get very confusing. Since we now have Travis in place, we could go for a semi-automated solution, in which you update the cabal file manually when Travis reports a missing path.

**Comment by hanjoosten** [comment]
We now use travis-ci to do automatic building. For deploying binaries, we might want to use [appveyor](http://www.appveyor.com/docs). That would even more encourage the use of scripts to automate whatever solution we want.

**Comment by hanjoosten** [comment]
Appveyor now builds a windows executable. Every time a new version number is bumped in ampersand.cabal, and merged into master, there is a new release created automatically.  Isn't that neat?

**Comment by sjcjoosten** [comment]
Excellent and many thanks for this nice feature! It is neat indeed! Can Appveyor also build Mac executables? That would be very neat.
