### ISSUE TITLE
Add auto rerun functionality in ExecEngine

### ISSUE THREAD

**Issue by Michiel-s** [AmpersandTarski/ampersand#220]
For the execEngine the order in which the rules are defined in your ampersand script matters. This means that if violations of a rule are fixed by the execEngine, it depends on the position of this rule if violations that are caused by this fix are also fixed in the same run. A 'rerun' function call is already available, but the behavior is not always easy to explain. Therefore, this ticket requests an autoRerun option (default: true).

The following script explains the behavior. With autoRerun set to true (=default), relations *s*, *t* and *u* are populated after insert of tuple in *r* in the same transaction. With autoRerun set to false, the order in which the rules *Step1*, *Step2* and *Step3* are defined causes the execEngine to only populate *s* in the same transaction. Two manual reruns are required to fix *Step2* and *Step3*

```
CONTEXT Test IN ENGLISH
r :: A * B
s :: A * B
t :: A * B
u :: A * B
  
POPULATION A CONTAINS ["a1"]
POPULATION B CONTAINS ["b1"]

INTERFACE "A" (r) : I[A]
  BOX [ "I"     : I
      , "r"     : r
      , "s"     : s
      , "t"     : t
      , "u"     : u
      ]

ROLE ExecEngine MAINTAINS "Step3"
RULE "Step3" : t |- u
VIOLATION (TXT "{EX}Inspair;u;A;", SRC I, TXT ";B;", TGT I)

ROLE ExecEngine MAINTAINS "Step2"
RULE "Step2" : s |- t
VIOLATION (TXT "{EX}Inspair;t;A;", SRC I, TXT ";B;", TGT I)

ROLE ExecEngine MAINTAINS "Step1"
RULE "Step1" : r |- s
VIOLATION (TXT "{EX}Inspair;s;A;", SRC I, TXT ";B;", TGT I)

ENDCONTEXT
```

**Comment by hanjoosten** [comment]
It doesn't feel right to depend on the order in which rules are specified. This is in violation to [rule 4.3 of the Business Rules Manifesto](http://www.businessrulesgroup.org/brmanifesto.htm)

**Comment by Michiel-s** [comment]
Unless we evaluate all rules simultaneously, it's unavoidable that there is an order in which the rules are **evaluated**. That's why I implemented this feature. In the runtime environment, evaluating rules requires that you start somewhere and that the script terminates. We know where to start: those rules that are build of conjuncts that are affected. But the fix of rule A can fire rule B. This issue is about if we evaluate rule B, and others, in the same transaction.

This is something else than the meaning of BRM 4.3, which specifies that the rules themselves may not require implicit sequencing.

**Comment by stefjoosten** [comment]
Han, you are right that this doesn't feel right. Michiel, you are right that it is unavoidable. The rerun feature is an implementation of a fixpoint on the function 'eval', which evaluates the entire model one step further. Since termination of this fixpoint is not guaranteed, we need mechanisms to interrupt this. In this (nice and simple) example of Michiel, we have a terminating fixpoint. So it works with 'rerun' switched on.

This topic is also relevant for Wolfram.

**Comment by Michiel-s** [comment]
Stef, Han, please explain to me how you would do this differently. Keep in mind that it is about evaluating rules in the runtime. E.g. if I update relation r, and the affected rules are rule1, rule2 and rule3. I need to evaluate these rules. Tell me with which conjunct I need to start?! You do not no the best strategy beforehand and it also doesn't matter. I just evaluate them in the order as stated in Generics, which is the order in which the rules are specified in the &-script. So, rule1, rule2, etc. If a violation of rule2, fixed by the execEngine, causes a new violation of rule1, we require a so called rerun. This is implemented by this issue. Thereby, the order in which you specify rules is not important anymore.

Honestly, I don't understand why you don't understand this. If it is still unclear after my explanation or you still think that I don't see it right, let's have a call.

By the way, as we cannot guarantee that the execEngine functionality will terminate, there is a config to set the max (re)runs, which defaults to 10. So after 10 runs, if there are still violations for the execEngine, we terminate the script and throw an error. In practice, this number of 10 proves quite reasonable. Usually if the execEngine hasn't terminated by then, you have created an infinite loop in your rule statements.

**Comment by hanjoosten** [comment]
Michiel, Don't understand this wrong, What you do is undoubly the best there currently is. Practically, this will suffice in most cases. However, theoretically there is probably more about it. Maybe, @WolframKahl might have some thoughts about this.
