### ISSUE TITLE
Warshall for non-strict endo relations

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/ampersand#222]

**Comment by RieksJ** [comment]
Warshall is not only needed for endo relations (i.e. `r :: A * A`), but also for relations such as `r :: B * A` in a context where `CLASSIFY B ISA A` or `A ISA B`

**Comment by hanjoosten** [comment]
We allready have Warshall. Please be more specific in what you WANT.

**Comment by RieksJ** [comment]
I'm sorry. I haven't been thinking straight. Forget it...
