### ISSUE TITLE
Sentinel: add a way to switch between haskell/ghc versions

### ISSUE THREAD

**Issue by sjcjoosten** [AmpersandTarski/Ampersand#225]
I just updated ghc on the sentinel, and it now compiles ``ampersand[upgrade_to_haskell_7.10:57ab699], ampersand-models[master:79f5349], sentinel[master:e425774]``. Note that ghc 7.8 is still on there, it's just not used anymore.

Trouble is: other branches no longer work, including master and typegraphs. I hope that we can discuss how to fix that in this issue. Here are some options:

0. We go with GHC 7.10.2: master and typegraphs will have to be updated to work with 7.10 as well. This option has my preference, I just forgot why we didn't do this already (maybe we can create an issue for that reason, too).
0. We create a separate make-file for each branch. Instead of running "cabal install", we run that make-file, so it can say ``cabal install --use-ghc=ghc-7.8.3``. This raises some security concerns, as someone who can create branches on git, will also be able to run arbitrary make-files on the sentinel. Of course, we all know that someone who can create branches can run arbitrary Haskell code, since we execute ampersand on the sentinel. The change to the sentinel is minor, and the changes to all branches are minor as well (requires a ``install.sh`` file to be added)
0. We make the sentinel smarter: have it look at the .cabal file for which ghc version it should use, so we do not have to change the current branches. This change is more involved of course.

**Comment by hanjoosten** [comment]
Option 1 would be the preferred one, However, Ampersand cannot be build with ghc 7.10.* (not even with the latest Haskell Platform, unfortunately) So this is not an option, because most developers of Ampersand use windows.

Option 2 might work, I do not know exactly what would be in the makefile. I do know that currently the master does not compile under 7.10.*, and the upgrade_to_haskell_7.10 branch does not compile with any ghc < 7.10.* 

Option 3 soudns pretty complex. 

This is why the sentinel still used the old ghc. However, now that you have installed the new ghc on the sentinel, I htink the best bet is option 2.

**Comment by sjcjoosten** [comment]
I suppose you mean that the upgrade_to_haskell_7.10 branch cannot be built with ghc 7.10 under windows?

I changed the default version back to ghc 6.8.3. There is some strange behavior with the 7.10 branch, you can search ``Sentinel_2015-11-13_11.10.58__13_of_567__amp=upgrade_to_haskell_7.10:57ab699_mdl=master:79f5349_sen=master:e425774.html`` for ``Exit code -11``. The problem seems to arise non-deterministically. Any ideas on what happens here?

If a complete lack of sentinel starts to become problematic for me, I will start working on Option 2. Hopefully ghc 8.0 will have no problems for windows, and I can avoid having to do this.

**Comment by hanjoosten** [comment]
I had a brief look at the problem with Exit code -11, but I have no clue at this moment what is going on.

**Comment by hanjoosten** [comment]
Another option to consider might be to see if we can do the tests that Sentinel does, by using Travis-ci.

**Comment by sjcjoosten** [comment]
I like that option even better!

**Comment by hanjoosten** [comment]
Since stack takes care of the correct version of GHC, we do not need to do anything about this any longer. Therefor, I close this ticket. If you disagree, just reopen it and motivate.
