### ISSUE TITLE
GitBook: Automated Rules

### ISSUE THREAD

**Issue by stefjoosten** [AmpersandTarski/ampersand#229]
@RieksJ @Michiel-s ,
I have discussed Exec-engine rules with the Canadian students. They could not grasp the idea based on the available documentation. For this reason, I have elaborated the Exec-Engine story in GitBook in a separate branch. I have included more detailed examples and paid some attention to the "why" questions of the students.

Would you please review this text on https://www.gitbook.com/book/ampersandtarski/documentation/edit#/edit/AutomatedRules/prototypes/extensions/execengine.md

When we're done, I will merge this branch in the master.
There are some TBD's at the end of the chapter, but right now I'm out of inspiration.

**Comment by RieksJ** [comment]
I suppose this can be closed now...
