### ISSUE TITLE
Sentinel is broken

### ISSUE THREAD

**Issue by hanjoosten** [AmpersandTarski/ampersand#230]
At this moment, the Sentinel reports the following error:

    cabal: Version mismatch between ghc and ghc-pkg: /usr/local/bin/ghc is version 
    7.8.3 /usr/local/bin/ghc-pkg is version 7.10.2 

I think this was caused accidently by an attemtp by @sjcjoosten to upgrade sentinel to ghc 7.10, but I am unaware what has been done exactly.

**Comment by sjcjoosten** [comment]
true

**Comment by sjcjoosten** [comment]
please try again, reopen if problem persists

**Comment by sjcjoosten** [comment]
ps, I did this:

sudo mv /usr/local/bin/ghc-pkg-7.8.3 /usr/local/bin/ghc-pkg
