### ISSUE TITLE
Cycle in LINKTO usage causes nontermination of functional document generator

### ISSUE THREAD

**Issue by hanjoosten** [AmpersandTarski/Ampersand#231]
If there is a cycle in the reference structure of interfaces, a prototype can be generated, but when I try to generate an fspec document from it, ampersand doesn't terminate.

**Comment by stefjoosten** [comment]
Hm, this means that either the prototype generator or the specification generator is doing more than rendering only...

**Comment by hanjoosten** [comment]
No, @stefjoosten . In this case, the document uses Crud calculations that are not used in the prototype generator, maybe because of the new CRUD stuff in the interface.

**Comment by stefjoosten** [comment]
Good to know that this has been fixed.
