### ISSUE TITLE
Support for the Diamond-operator

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/Ampersand#233]
We may want to have the diamond-operator, e.g. to support better `IDENT` statements.

**Comment by sjcjoosten** [comment]
Did you verify that the diamond-operator `<>` does not work? Can you refer to a try....adl ?

**Comment by RieksJ** [comment]
I have created file `Issue233.adl` in `ShouldSucceed`. It doesn't work (as expected - which means it works as expected as it does not work, you see...). @sjcjoosten can you validate what I did?

**Comment by WolframKahl** [comment]
What is the “diamond-operator”?

If a direct reading of the operators in
```
./src/Database/Design/Ampersand/FSpec/Switchboard.hs:  f (EDia (l,r)) = f (flp l .\. r ./\. l ./. flp r)
```
is correct, it is a variant of the symmetric quotient?

**Comment by sjcjoosten** [comment]
Yes, it is supposed to be the symmetric quotient. Rieks put the following rule in his test script, and I believe the rule should hold:

``
RULE "Test equivalence": arg <> arg~ = (-arg ! arg~) /\ (arg ! -arg~)
``

Since the script type-checks, I tried to find out what Rieks means by `does not work'. I used the following command (from ampersand-models):

``
ampersand Tests/ShouldSucceed/Issue233.adl  --diagnosis --fspec Latex
``

The diagnosis chapter showed 4 violations on "Test equivalences". If we agree on the semantics of `<>`, then there should not be violations, and the implementation of `<>` is currently wrong.

**Comment by WolframKahl** [comment]
On Sun, Nov 29, 2015 at 09:36:58AM -0800, Sebastiaan Joosten wrote:
> Yes, it is supposed to be the symmetric quotient. Rieks put the following rule in his test script, and I believe the rule should hold:
> 
> ``
> RULE "Test equivalence": arg <> arg~ = (-arg ! arg~) /\ (arg ! -arg~)
> ``

From the remarks elsewhere, I gather that you want the same typing for <> as for ; .

Then I would expect the following rules to hold:

```
RULE "<> definition1": R <> S = - (R ; - S) /\ - (-R ; S)
RULE "<> definition2": R <> S = (-R ! S) /\ (R ! -S)  # assuming ! is ``dagger''
RULE "<> definition3": R <> S = (R~ \ S) /\ (R / S~)
```

> The diagnosis chapter showed 4 violations on "Test equivalences". If we agree on the semantics of `<>`, then there should not be violations,
> and the implementation of `<>` is currently wrong.

Where is this implementation?


Wolfram

**Comment by sjcjoosten** [comment]
@stefjoosten do you know where the implementation of `<>` is?

**Comment by stefjoosten** [comment]
I have no idea. As far as I recall, the symmetric quotient has never been 
implemented properly. However, it looks like we did actually build it Ampersand. On all places where there is mention of ELrs or ERrs (i.e. left- and right residuals), you can see that EDia is in place. I guess we have put it in some time ago and my memory is failing me. I cannot remember having verified that it does what one (esp. Wolfram) would expect it to do. The reason I am not using it, is that I have always thought it to be absent.

Apparently, the current implementation is wrong (as Bas argues). Given the fact that it is omnipresent it should not be hard to fix.

**Comment by stefjoosten** [comment]
The interpretation function in Haskell is `contents :: Expression -> Map AAtomValue [AAtomValue]` (in module Populated.hs)
The code for the residuals and the diamond is:
```
         -- The left residual l/r is defined by: for all x,y:  x(l/r)y  <=>  for all z in X, y r z implies x l z.
         ELrs (l,r) -> fromListWith (++)
                       [(x,[y]) | x<-aVals (source l), y<-aVals (source r)
                                , null (lkp y (contents r) >- lkp x (contents l))
                                ]
         -- The right residual l\r defined by: for all x,y:   x(l\r)y  <=>  for all z in X, z l x implies z r y.
         ERrs (l,r) -> fromListWith uni
                       [(x,[y]) | x<-aVals (target l), y<-aVals (target r)
                                , null (lkp x (contents (EFlp l)) >- lkp y (contents (EFlp r)))
                                ]
         EDia (l,r) -> fromListWith (++)
                       [(x,[y]) | x<-aVals (source l), y<-aVals (source r)
                                , null (lkp y (contents r) >- lkp x (contents l))
                                , null (lkp y (contents l) >- lkp x (contents r))
                                ]
```
It will take me some effort and a whiteboard to review the correctness by code inspection. Should be doable though. I guess Bas will need less effort than I for that purpose...  :-)

**Comment by sjcjoosten** [comment]
Implementation might still be buggy, but I checked the normaliser and the rule-checker. To answer @WolframKahl the code containing the semantics for EDia was found in src/Ampersand/FSpec/ToFSpec/Populated.hs (and was incorrect there, something like `(R~ \ S~) /\ (R / S)` was implemented, which doesn't even type check but that's not tested there)
