### ISSUE TITLE
Atoms.adl has stopped working

### ISSUE THREAD

**Issue by stefjoosten** [AmpersandTarski/ampersand#234]
I have always cherished Atoms.ifc as a little demo for showing off how Ampersand treats atoms.
However, it works no more (sob :-( ). This is what I got right after resetting the database:
![image](https://cloud.githubusercontent.com/assets/275768/11480736/76ee5aaa-9799-11e5-9ed8-12e23c67df9f.png)
Details: I have compiled Atoms.ifc (commit SHA 86f460c93dccad9b4632a76eb2241dc52b1767cc)  with Ampersand v3.2.0[master:c90f1f9]. However, it still works with the compiler of Nov 28th, being Ampersand v3.2.0[HEAD:5574196], so I have only myself to blame (sigh  >-(  )

I have excluded all explanations outside my own .adl source. So I have reverted the update in the master that causes this to happen. Atoms works again.

**Comment by RieksJ** [comment]
While this may not be needed (or even wanted) for Atoms.ifc, the ExecEngine has been provided with the capability of doing automated reruns, which is (now) its default behaviour. I have added a section in the ExecEngine documentation that explains all this. 

The quick fix for you is to add the following line in your `localSettings.php` file in your `include` directory:

    Config::set('autoRerun', 'execEngine', false);

Having said that, I'm surprised that Atoms.ifc actually hits the rerun-limit.

**Comment by stefjoosten** [comment]
Thx Rieks for thinking along. But this was just me goofing up. It happens... :-(  I fixed the stuff by putting it back.
