### ISSUE TITLE
INCLUDE "Mindmaps.xlsx" does not work properly

### ISSUE THREAD

**Issue by stefjoosten** [AmpersandTarski/Ampersand#240]
Including an excel-sheet from the Ampersand-script gives erroneous results.
# Reproducing the mistake

I have pushed some files for the MirrorMe project in AmpersandTarski/ampersand-models@5724cf1ec440287113a0f87915c2f6ae10b7f287. One of these files is `MirrorMe/Mindmaps.xlsx`, which contains population for a demo given by `MirrorMe/Mindmaps.adl`.
## Correct Behaviour

To get the correct behaviour perform the following: 
1. Check out the MirrorMe project from ampersand-models.
2. Compile `Mindmaps.adl` into a prototype. This should work.
3. Run the program and install the database. This should work.
4. Log in, using the Login menu entry. Use `Stef Joosten`  and `welkom` to log in.
5. ImportD-file `MirrorMe/Mindmaps.xlsx`. For now, don't worry about the message `Concept @1449705600 )`. It does not interfere with this issue.
6. Now look at the Overview screen. This is what you should see:
![image](https://cloud.githubusercontent.com/assets/275768/11726989/80296304-9f81-11e5-8588-0e0730757e97.png)
Notice that column "grond" contains URL's. Verify that this is consistent with the content of `Mindmaps.xlsx`.
## Incorrect Behaviour

In order to reproduce the mistake, proceed with the following steps:
7. Edit the file `Mindmaps.adl` and activate the line saying `INCLUDE "Mindmaps.xlsx"`
8. Compile `Mindmaps.adl` into a prototype. This should work.
9. Run the program and install the database. This should work. 
10. Log in, using the Login menu entry. Use `Stef Joosten`  and `welkom` to log in. This should work. You no longer need to import the Excel-file `Mindmaps.xlsx`, because it is now included by the compiler.
11. Now look at the Overview screen. This is what you should see:
![image](https://cloud.githubusercontent.com/assets/275768/11727122/537f790a-9f82-11e5-99da-4de24624e376.png)
Notice that column "grond" no longer contains any URL, but instead it contains content which is inconsistent with the structure of `Mindmaps.xlsx`.
# Analysis

I have not (yet) looked into this, but this smells like a mistaken xlsx-parser. For this reason I have assigned @hanjoosten to this issue. Can you make sense out of this?
I have compiled with Ampersand v3.2.0[master:62e159f*], build time: 10-Dec-15 15:16:00 West-Europa (standaardtijd)

**Comment by hanjoosten** [comment]
I added an extra file (Issue240.adl). If you generate both that file and Mindmaps.adl, you get two databases with the same structure. Now import MirrorMe/Mindmaps.xlsx into the mindmaps database, as you did in your first scenario. 

I have tried to spot any differences between the two databases, but I cannot find them. (except for the modification timestamps that are set in the database). 

This is very strange behaviour!

**Comment by Michiel-s** [comment]
I'll have a look at thuis issue to.

**Comment by hanjoosten** [comment]
This too is very likely related with the [bug](https://github.com/qrilka/xlsx/issues/45) fixed with xlsx 0.2.1.1. It will be available in stack LTS expected next week.

**Comment by hanjoosten** [comment]
This bug should be fixed now. @stefjoosten , can you test/confirm this, and then close this ticket?

**Comment by hanjoosten** [comment]
I assume this bug is fixed. We use the fixed version of xlsx now.
