### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by ejsmits** [AmpersandTarski/ampersand#242]
I don't get Ampersand installed, see below (even if I run the command 'cabal install' several items). I am using ghc 7.10.3 and dowloaded the branch 'ampersand_upgrade_to_haskell_7.10'. Haskell is all setup. I am working on a Macbook, El Capitain. Any ideas how to get things running?

Best,

Erik-Jan

---

Van-Anreijk:Ampersand vananreijk$ cabal install
Resolving dependencies...
Configuring ampersand-3.2.0...
Building ampersand-3.2.0...
Failed to install ampersand-3.2.0
Build log ( /Users/vananreijk/.cabal/logs/ampersand-3.2.0.log ):
Configuring ampersand-3.2.0...
"fatal: Not a git repository (or any of the parent directories): .git\n"
"fatal: Not a git repository (or any of the parent directories): .git\n"

WARNING: Execution of 'git' command failed.
BuildInfo_Generated.hs will not contain revision information, and therefore
neither will fatal error messages.
Please check your installation

Warning: Cannot read previously generated src/Database/Design/Ampersand/Prototype/StaticFiles_Generated.hs:
src/Database/Design/Ampersand/Prototype/StaticFiles_Generated.hs: openFile: does not exist (No such file or directory)
This warning should disappear the next time you build Ampersand. If the error persists, please report this as a bug.

setup: static/zwolle/./extensions/ExcelImport/lib/Classes/PHPExcel/locale/no:
resource exhausted
cabal: Error: some packages failed to install:
ampersand-3.2.0 failed during the building phase. The exception was:
ExitFailure 1

**Comment by sjcjoosten** [comment]
I'm hoping @hanjoosten can solve this? Maybe this issue is related: http://stackoverflow.com/questions/22893168/preventing-getcurrentdirectory-resource-exhausted-too-many-open-files-error

**Comment by sjcjoosten** [comment]
Erik-Jan, as ghc-7.10.3 is not available yet, can you maybe also paste the output of:

ghc --version

**Comment by sjcjoosten** [comment]
If you just want the ampersand binary for OS X, a fairly recent one is available from http://sentinel.tarski.nl/sentinel/executables/

**Comment by ejsmits** [comment]
Hi, ghc --version results in the following output:

Van-Anreijk:Ampersand vananreijk$ ghc --version
The Glorious Glasgow Haskell Compilation System, version 7.10.3
Van-Anreijk:Ampersand vananreijk$ cabal --version
cabal-install version 1.22.6.0
using version 1.22.5.0 of the Cabal library 
Van-Anreijk:Ampersand vananreijk$

**Comment by hanjoosten** [comment]
This still is very tricky. currently ghc 7.10.* is not supported. This is due to a bug in ghc. 
The haskell ecosystem has changed the last couple of months. I am currently investigating if it possible to switch onto [stack](https://github.com/commercialhaskell/stack). Stack is a package manager. It reads my-project.cabal and stack.yaml to link in third party code. It will install GHC for you too. So if this will succeed, building ampersand from scratch will become a piece of cake. Untill then, it is pretty hard.

**Comment by hanjoosten** [comment]
@sjcjoosten , It would be a good idea to publish the binary for OS X via the documentation. I have [described how I do that for windows ](https://ampersandtarski.gitbooks.io/the-tools-we-use-for-ampersand/content/publish_executable_online.html). Maybe you can do something similar for OS X?
Then we store the binaries at github, not at sentinel any longer. (see the [repo for binaries](https://github.com/AmpersandTarski/webFiles/tree/master/executables))

**Comment by sjcjoosten** [comment]
I'll look in to both fixing the compilation issue on OS X, and into creating a binary (and a binary-deploy-script) when I have more time (which may be by the end of this year, but definitely in January)

**Comment by stefjoosten** [comment]
Hi Erik-Jan,
If you must compile from the Haskell source, use ghc version 7.8.4. That is our current production version.
Given the way you use it, you just want:
1. an executable file, which lets you issue the command: `Ampersand <foo>.adl` from the command line.
2. LaTeX and Graphviz, which lets you generate .pdf-files by way of functional specifications. This is done with the command : `Ampersand -fl --verbose <foo>.adl`
3. a MAMP-stack, which lets you generate working prototypes. This is done with the command : `Ampersand -p/D/var/www/probeersel --verbose <foo>.adl` (unsure about the Mac-path, which must point to the destination folder for your http-server).

Notice that this does not require you to compile with Haskell, but you do need to install stuff.

**Comment by ejsmits** [comment]
And I'm up and running! Thanks for pointing me to the binary file.
