### ISSUE TITLE
Documentation does not build (does that belong here?)

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/ampersand#244]
@hanjoosten your latest modifications on the documentation make it unbuildable:
![picture1](https://cloud.githubusercontent.com/assets/8522589/11765945/f5d79e3c-a16f-11e5-9b1a-d3b6ad1f5566.png)
Can you fix that?

**Comment by hanjoosten** [comment]
Something with a copied page. I removed it, and now it builds again.
