### ISSUE TITLE
Too many open files during install

### ISSUE THREAD

**Issue by sjcjoosten** [AmpersandTarski/Ampersand#248]
I'm making this ticket to remind myself of ticket #242 
The problem of ej is solved, but an issue remains: too many open files causing a `resource exhausted' during installation.

**Comment by hanjoosten** [comment]
And also to get the OS X binary in github

**Comment by hanjoosten** [comment]
@sjcjoosten In branch #228, I fixed this by using the conduit library. I suppose that this solve the resource exhaused bug on IOS. Can you confirm that? (I don't have the hardware)

**Comment by sjcjoosten** [comment]
Not really, I never got the resource exhausted bug earlier, and I'm not getting it now. In that sense, the problem is solved. Closing as a cannot reproduce.
