### ISSUE TITLE
Exec-engine timestamps

### ISSUE THREAD

**Issue by sjcjoosten** [AmpersandTarski/ampersand#249]
@stefjoosten posted the following:

``
Rieks, ik meen me te herinneren dat er iets bestaat om de Exec-Engine een tijdstempel te laten zetten. Heb je daar een voorbeeld van? (In het GitBook is het niet gedocumenteerd, dus voor hetzelfde geld bestaat het niet...)
``

Should the feature be present, consider this a task to put it into GitBook. Should it not be, we can decide on whether to consider this as a feature request.

**Comment by RieksJ** [comment]
The example project "ProjectAdministration.adl" contains the following rule:

     ROLE "ExecEngine" MAINTAINS "Create Assignment"
     RULE "Create Assignment" : pl |- project~;assignee
     VIOLATION (TXT "NewStruct;Assignment"
                  , TXT ";project;Assignment;_NEW;Project;", SRC I
                  , TXT ";assignee;Assignment;_NEW;Person;", TGT I
                  , TXT ";assignmentStartDate;Assignment;_NEW;Date;{php}date(DATE_ISO8601)" -- Current date in ISO 8601 date format 
               )

Note the the last line includes an argument `{php}date(DATE_ISO8601)`. This is a (dirty) way to call simple php functions. See the [php manual](http://www.php.net/manual/en/) for details about such functions. You can also search `php date` in Google, which will point you directly to the documentation page of such functions.

If this is satisfactory, please close the ticket.

**Comment by RieksJ** [comment]
The `{php}` tag is currently not supported officially, because there are some details you need to know when it suddenly doesn't appear to work... I expect it to go away when violations, views and interfaces are integrated. But then, if it is handy, ....

**Comment by sjcjoosten** [comment]
I trust this has reached @stefjoosten , thank you for the explanation!

**Comment by hanjoosten** [comment]
Not sure if this is what you are looking for: In the database, all tables have two extra columns, containing the timestamp of creation and the timestamp of last modification of a row.

**Comment by stefjoosten** [comment]
Thanks @RieksJ, this is exactly what I was looking for. I'll give it a try.
Thx @sjcjoosten for forwarding this.

**Comment by stefjoosten** [comment]
It doesn't work, but it is not urgent. @hanjoosten I see that tables are timestamped automatically in the database. How do I use that from my Ampersand-script?

**Comment by hanjoosten** [comment]
This is a feature in the implementation of mysql only. It is not accessable from your script, as far as I know.

**Comment by RieksJ** [comment]
That's correct. If you need to do timestamping, you can do this with an ExecEngine rule that contains a violation such as

    VIOLATION (TXT "{EX} InsPair;timestamprelation;SomeConcept;", SRC I, TXT ";DateTimeConcept;{php}gmdate('d-m-Y H:i T')" -- Set the DateTime for the atom of SomeConcept

Google the PHP-function `gmdate` to find more ways for formatting the timestamp
