### ISSUE TITLE
Front-end does not seem to work anymore.

### ISSUE THREAD

**Issue by stefjoosten** [AmpersandTarski/ampersand#250]
I wrote a simple script:
~~~~~~
CONTEXT Arguments IN ENGLISH

PATTERN Arguments
    RELATION phrasing[Argument*Text] [UNI]
    REPRESENT Text TYPE ALPHANUMERIC
ENDPATTERN

INTERFACE "New Argument" (phrasing) : I[Argument]
COLS [ formulering : phrasing
     ]

ENDCONTEXT
~~~~~~

I would expect that I can create a new `Argument` (using menu `+` ) and create a new tuple in the relation `phrasing`. This thing works up to the point where the tuple needs to be saved to the database. I get a front-end message saying `! 405 Method Not Allowed: Resource already exists. POST method is not allowed`. @Michiel-s : This behaviour was obtained with Ampersand v3.2.0[master:62e159f*], build time: 07-Dec-15 13:00:20 West-Europa (standaardtijd), which is well before the transition to Haskell 7.10.3. Any ideas? here's the output screen.

![image](https://cloud.githubusercontent.com/assets/275768/11819056/366e2da4-a35e-11e5-8b9e-92637595567b.png)

Removing the REPRESENT-statement doesn't help, by the way.

**Comment by Michiel-s** [comment]
This should be fixed in branch 228 (soon to be merged in master), I'm closing this issue. Please reopen if it still occurs.
