### ISSUE TITLE
Ampersand MySql dbase access rights

### ISSUE THREAD

**Issue by tvwengen** [AmpersandTarski/ampersand#251]
met OSX mac. vanuit Ampersand op MAMP dbase created. Ampersand user met voldoende rechten toegevoegd. vervolgens toch foutmelding :

![foutmelding phpmyadmin](https://cloud.githubusercontent.com/assets/16361588/11912986/6c98fe28-a655-11e5-819c-7b52ed85a7cc.jpg)

**Comment by stefjoosten** [comment]
@hanjoosten of @sjcjoosten , enig idee wat hier aan de hand zou kunnen zijn? De database is zichtbaar, ampersand is ingelogd, maar bij het opbouwen van de timestamp-relatie gaat er wat fout. Het betreft hier de Apple-ampersand, die Bas heeft gebouwd.

**Comment by Michiel-s** [comment]
This is an error due to a older version of MySQL. I don't know the required version number right now, but I will look this up for you. The latest version of XAMPP does include the required version. I'll also improve the error message.

**Comment by stefjoosten** [comment]
This happens in MAMP. Not in XAMPP.... does thatake a difference?

**Comment by Michiel-s** [comment]
http://stackoverflow.com/questions/267658/having-both-a-created-and-last-updated-timestamp-columns-in-mysql-4-0

The function we've implemented with two time stamp columns if available since MySQL v5.6.5

I suggest to remove the 'ts_insert' (defaults to current time stamp) column and add the default option to the 'ts_update' column.

**Comment by Michiel-s** [comment]
FYI: MAMP bundles MySQL 5.5.

**Comment by stefjoosten** [comment]
Tjeerd van Wengen is stuck at the moment. @Michiel-s or @hanjoosten, does one of you know which version of the master does NOT use the 'ts_insert', which causes this problem? Would that version help Tjeerd?

**Comment by hanjoosten** [comment]
Yes. This has been done on with commit be32b36c0b8989472cfc683b26e452fe200b9b8d.

For Windows we have a [binary of a few days before](https://github.com/AmpersandTarski/webFiles/blob/972a28b2e21c38c4e0c4e56534b49859c24a8600/executables/windows/ampersand.zip?raw=true). 
Does that help?
