### ISSUE TITLE
ExecEngine ROLE 'ExecEngine' not found

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/ampersand#254]
If you have a script that contains no ExecEngine rules, there is no need to show this (twice) in the front-end as a (blue) bar. In fact, it is irrelevant (and hence somwhat disturbing) to have it there (it is ok to have this in the log). Could the notification (in the blue bar) be removed?

**Comment by Michiel-s** [comment]
I've changed the info message, but I suggest to leave it as an info message. If you don't use the ExecEngine, don't enable the extension in your script. It would be better to not include this extension by default, but for reasons of convenience we decided otherwise.
