### ISSUE TITLE
INTERFACE OVERVIEW does not display results

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/ampersand#255]
Consider the following script:

     CONTEXT Bug_255 IN ENGLISH
     
     REPRESENT LargeText TYPE BIGALPHANUMERIC
     r :: A * LargeText [UNI]
     POPULATION r CONTAINS [ ("a001", "1") ]
     
     INTERFACE OVERVIEW : V[SESSION*A]
     BOX[ "id" : I
        , "r's": r
        ]
     
     ROLE ExecEngine MAINTAINS arghh RULE arghh: I[A]=I[A] -- In order to not be distracted by issue #254:
     ENDCONTEXT

When I create a prototype of this script, and click on 'OVERVIEW',  nothing can be seen.

I have seen this issue with
* Ampersand v3.2.0[master:6c4d0ef]  (before transfer to Haskell 10.x)
* Ampersand v3.3.0[master:1e93f51]  (after transfer to Haskell 10.x)
In both cases I use the default configuration.

**Comment by hanjoosten** [comment]
I cannot reproduce this error. In Ampersand v3.2.0[master:62e159f*] this seems to work fine

**Comment by hanjoosten** [comment]
No bug, however, also no row in "OVERVIEW"

**Comment by RieksJ** [comment]
I have seen this issue with 
- Ampersand v3.2.0[master:6c4d0ef]
- Ampersand v3.3.0[master:1e93f51]

which suggests it has something to do with the frontend (perhaps config stuff). You can see a red error message when you turn on the configuration switch `Show error messages` in the logitem menu.

**Comment by hanjoosten** [comment]
I have looked into this issue. The database is generated exactly as expected. (The BIGALPHANUMERIC is represented as TEXT in MySQL, which is correct. The population statement causes a row in table "A", which is correct too.

However, when I monitor the database, there is no database activity at all when the OVERVIEW menu is clicked. That seems curious, because I would expect a query on the contents of table "A".

**Comment by hanjoosten** [comment]
This might have been related with issue #260, which has been fixed. @RieksJ , could you please retest this issue?

**Comment by Michiel-s** [comment]
@hanjoosten thinks this issue is fixed. @RieksJ please reopen if that is not the case.
