### ISSUE TITLE
Why is `delValue` not considered violated?

### ISSUE THREAD

**Issue by stefjoosten** [AmpersandTarski/Ampersand#256]
SJ: This issue also appears in issue #345, and showed up in branch_#228 on Mar 22nd 2016.

The script Sequence.adl [ AmpersandTarski/ampersand-models@3a3fc5879776e01f068ff9eccd656b12463e4ced ] contains a rule, `delValue`, that deletes atoms of concept `Value` whenever the relation `value` violates surjectivity.

    RULE delValue : I[Value] |- value~;value
    VIOLATION ( TXT "{EX} DelAtom;Value;", SRC I[Value] )
    ROLE ExecEngine MAINTAINS delValue

I have compiled and run this with Ampersand v3.1.0 [ AmpersandTarski/ampersand@ac300ab3d7b4076b8739ffb0cb2b3eb52628c5cf ]. This leads to the following code in `Generics.php`:

    , 'conj_18' =>
        array ( 'signalRuleNames' => array ('delValue')
              , 'invariantRuleNames' => array ('SUR value::Item*Value')
              // Normalization steps:
              //     -V[Value*Value]
              // 
              , 'violationsSQL' => '/* this will quaranteed return 0 rows: */
                                    select
                                    distinct
                                           a as src, a as tgt
                                    from (/* Select nothing... */
                                          select 1 as a)
                                         as nothing
                                    where a <> 1'
              )

# Analysis
This clearly is a mistake, because the generator thinks that conjunct 18 (the surjectivity of rule delValue) can never be violated.

The question is: where did the semantics go? Normalization should start with `I |- value~;value`. But here it starts with ` -V[Value*Value]`! 

I have shortened this script whilst retaining the mistake:

    CONTEXT Sequence IN ENGLISH MARKDOWN

    PATTERN "Sequences"
    RELATION value[Item*Value] [UNI,INJ,SUR]

        RULE delValue : I[Value] |- value~;value
        VIOLATION ( TXT "{EX} DelAtom;Value;", SRC I[Value] )
        ROLE ExecEngine MAINTAINS delValue

    ENDPATTERN

    ENDCONTEXT

However, when I remove `SUR` from the declaration of value, the mistake disappears and the correct code is generated.

    RELATION value[Item*Value] [UNI,INJ]

So here is the reason why Ampersand generated 'incorrect' code: The programmer had already declared relation `value` to be surjective. For this reason, Ampersand must have concluded that there is little to test if this condition is already satisfied. In fact, it wasn't satisfied, so we may still argue that Ampersand contains a mistake. 

# Workaround
The problem for the programmer is easily solved by removing the `SUR` annotation.

**Comment by tvwengen** [comment]
Bas, 
De nieuwe build van Ampersand (of de re-build) werkt perfect!!

DANK!!

met vriendelijke groet 
Tjeerd van Wengen

**Comment by RieksJ** [comment]
I notice that you are using quite an old version of Ampersand.exe. We know there are a lot of things there that have been fixed in the meantime. Does your issue also appear when you use a recent version of the tool?

**Comment by stefjoosten** [comment]
@RieksJ , that thought crossed my mind, but it now looks like we have pinpointed the cause in code that has been around for a while. Han and I have just been able to reproduce this behaviour in other versions too. to be continued...

**Comment by hanjoosten** [comment]
I ran into a similar bug. Because of the UNI in the relation, value will be stored in the same table where Item is stored, Hence, the structure of the table enforces UNI. However, that does not hold for TOT and SUR, because the concepts could generally have greater concepts. Hence, a proper query must be generated at all times for TOT and SUR.

**Comment by hanjoosten** [comment]
When I write SUR as a rule, it gets generated perfectly. This once more tells that there is nothing wrong with the SQL generator. The SQL generator only needs the correct expression...


So the workaround is:
Instead of writing 

```
RELATION myRel[A*B][SUR]
```
explicitly write the rule:
```
RELATION myRel[A*B]
RULE "myRel is surjective" : I[B] |- myRel~;myRel
MEANING "Every B has an A in the relation myRel"
```

**Comment by hanjoosten** [comment]
The same is true for INJ relations. An example is uploaded in commit https://github.com/AmpersandTarski/ampersand-models.git . See the workaround rules at the bottom of file KlantRollen.ifc (That is also the correct file to generate the prototype from)

**Comment by stefjoosten** [comment]
This issue is now ready for testing.

**Comment by Michiel-s** [comment]
I've checked the fix and everything looks good now.
