### ISSUE TITLE
Cannot enter values of type ALPHANUMERIC in relation `sessionMsgText`

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/ampersand#257]
Consider the script

     CONTEXT Bug_25x IN ENGLISH
     
     INTERFACE "Send Message" (sessionMsgText, sessionMsgPerson): '_SESSION'[SESSION]
     BOX[ "Send Message" : I COLS
          [ "To (person)": sessionMsgPerson
          , "Message text" : sessionMsgText
          ]
        , "Message send requests" : V[SESSION*MsgSendRequest] COLS
          [ "To" : msgsrPerson
          , "Message text" : msgsrText
          ]
        ]
     
     sessionMsgPerson :: SESSION * Person [UNI] -- Person to send the message to
     sessionMsgText :: SESSION * MsgText [UNI] -- Text to be sent
     
     --[Message Send Requests]--
     msgsrPerson :: MsgSendRequest * Person [UNI,TOT]
     msgsrText :: MsgSendRequest * MsgText [UNI,TOT]    REPRESENT MsgText TYPE ALPHANUMERIC
     
     ROLE ExecEngine MAINTAINS "Create message send request"
     RULE "Create message send request": sessionMsgPerson~;'_SESSION';sessionMsgText |- msgsrPerson~;msgsrText
     VIOLATION (TXT "{EX}_;NewStruct_;MsgSendRequest"
                   ,TXT "_;msgsrPerson_;MsgSendRequest_;_NEW_;Person_;", SRC I
                   ,TXT "_;msgsrText_;MsgSendRequest_;_NEW_;MsgText_;", TGT I
               ,TXT "{EX} DelPair;sessionMsgPerson;SESSION;", SRC V;'_SESSION'[SESSION], TXT ";Person;", SRC I
               ,TXT "{EX} DelPair;sessionMsgText;SESSION;", SRC V;'_SESSION'[SESSION], TXT ";MsgText;", TGT I
               )
     
     ENDCONTEXT

The idea is that if you enter a person and a text, a message send request should be generated. However, this does not happen. Data is not entered in the database.

I am using  Ampersand v3.3.0[master:1e93f51]

This bug may be related to #255

**Comment by stefjoosten** [comment]
Hi Rieks, it helps to add `REPRESENT Person TYPE ALPHANUMERIC` to your script.
It made your script work instantly.
I don't know whether it solves your problem, because it seems to contradict the title of this issue.
Could you formulate your problem more precisely?

**Comment by RieksJ** [comment]
My problem is that the prototype that I have generated with the provided (valid) script does not allow me to enter a text in the field `Message Text` of the `Send Message` interface. When I press 'Enter', nothing happens. Also, whenever it somehow does occur that rules are evaluated, the rule that I specified does not fire, implying, that at least one of the session-variables is considered empty (which it should not be).

**Comment by stefjoosten** [comment]
Has this problem been solved (by  adding `REPRESENT Person TYPE ALPHANUMERIC` to your script)?

**Comment by RieksJ** [comment]
No, that would not fix my problem. The presented script is an excerpt from a larger script, in which `Person` has other relations (attributes). Using your suggestion would not solve that (larger) problem.

**Comment by stefjoosten** [comment]
@RieksJ , if you think issue #260 might solve this issue too, I suggest you close this issue.

**Comment by hanjoosten** [comment]
I would suggest to leave this issue open as long as #260 has not been fixed. Then, @RieksJ would surely be able to decide that this issue is solved as well, or that this is a different issue.

**Comment by hanjoosten** [comment]
@RieksJ, Issue #260 has been fixed and merged into master. Could you please retest this issue?

**Comment by Michiel-s** [comment]
Closed because no response from @RieksJ
