### ISSUE TITLE
Representation mismatch in recent versions of Ampersand

### ISSUE THREAD

**Issue by hanjoosten** [AmpersandTarski/ampersand#260]
Whenever there is a REPRESENT statement, it seems that this is disregarded. For me this is the reason I cannot use a recent version of Ampersand. I know Stef is having trouble with this too (issue #262). 

Given the following script:

```
CONTEXT Issue260 IN DUTCH

RELATION r[A*B]
REPRESENT B TYPE INTEGER

POPULATION r CONTAINS
   [( "Aap" , 2)]

ENDCONTEXT
```

This tiny script is perfectly allright. It could be succesfully compiled with Ampersand v3.2.0[master:62e159f*] 
However, it fails when using Ampersand v3.3.0[master:91e0569]
It throws the following error:

```
Error(s) found:
Representation mismatch
    Found: `2`,
    as representation of an atom in concept `B`.
    However, the representation-type of that concept is (implicitly) 
    defined as ALPHANUMERIC. The found value does not match that type.
  Error at symbol () in file Issue260.adl at line 7 : 15
```

**Comment by hanjoosten** [comment]
This has been introduced in the master branch with the pull request https://github.com/AmpersandTarski/ampersand/pull/243 (upgrade to ghc 7.10)

**Comment by RieksJ** [comment]
To me, this sounds the same as issue #257.

**Comment by hanjoosten** [comment]
Yes, that is very likely. However, this one is more specific, for it does not have anything to do with interfaces / frontend. Hence, assigning @Michiel-s is pointless.

**Comment by sjcjoosten** [comment]
Sorry for the delay in fixing this

**Comment by hanjoosten** [comment]
Thanks for the fix! could you add a pull request, so Stef can merge it into
the master, or is there still something that has to be done?

2016-01-22 11:59 GMT+01:00 Sebastiaan Joosten <notifications@github.com>:
