### ISSUE TITLE
Feature request: LocalSettings must import all PHP files from \Settings dir

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/Ampersand#264]
With reference to the discussion #261, I request that `localSettings.php` would import all .php files from a directory `\Settings`, which is needed for the creation of modules, and is otherwise nice to have as well.

**Comment by Michiel-s** [comment]
As discussed with Rieks, this does not only applies for (local)settings files, but also for the whole `include` folder containing views, extensions, etc

**Comment by Michiel-s** [comment]
Issue should be reformulated (if still relevant) now that we have the config.yaml functionality and Composer for dependency management.
