### ISSUE TITLE
Arguments.xlsx is read improperly from an INCLUDE statement

### ISSUE THREAD

**Issue by stefjoosten** [AmpersandTarski/Ampersand#266]
When running Tiles.adl (commit AmpersandTarski/ampersand-models@c3aebc60268b58313c8ca655bf1c42fee3b63c48), the file Arguments.xlsx is not read properly. I have compiled it with Ampersand v3.1.0[master:ac300ab], build time: 05-Oct-15.

After I initialize the database, the contents of the database does not correspond with the contents of Arguments.xlsx ..

**Comment by hanjoosten** [comment]
@stefjoosten Please eleborate on what you expect and what actually happens.

**Comment by hanjoosten** [comment]
@stefjoosten , please confirm that this has been solved in branch 228, for I guess this had to do with the fix in issues #305 and #355. If it is something else. don't hesitate to reopen this issue, but then please elaborate.
