### ISSUE TITLE
Possible optimisation in SQL-code

### ISSUE THREAD

**Issue by stefjoosten** [AmpersandTarski/Ampersand#268]
# Observation

Currently, the code generator generates SQL-code for Epsilon-expressions, as in:

```
select
distinct
       t1.src as src, t1.tgt as tgt
from (/* case: (ECps es), with two or more elements in es.I{-Eps-}[Statement];template;I{-Eps-}[Template];head */
      select
      distinct
             fence0.src as src, fence3.tgt as tgt
      from (/* epsilon Statement [Sequence*Statement] */
            select
            distinct
                   "Statement" as src, "Statement" as tgt
            from "Sequence"
            where "Statement" IS NOT NULL)
           as fence0,
           (select
            distinct
                   "Statement" as src, "tgt_template" as tgt
            from "Sequence"
            where "Statement" IS NOT NULL AND "tgt_template" IS NOT NULL)
           as fence1,
           (/* epsilon Template [Template*Sequence] */
            select
            distinct
                   "Template" as src, "Template" as tgt
            from "Sequence"
            where "Template" IS NOT NULL)
           as fence2,
           (select
            distinct
                   "Sequence" as src, "tgt_head" as tgt
            from "Sequence"
            where "Sequence" IS NOT NULL AND "tgt_head" IS NOT NULL)
           as fence3
      where fence0.tgt = fence1.src AND fence1.tgt = fence2.src AND fence2.tgt = fence3.src)
     as t1
     left
     join (/* case: (ECps es), with two or more elements in es.head;I{-Eps-}[Prefix];bind;I{-Eps-}[Variable] */
           select
           distinct
                  fence0.src as src, fence3.tgt as tgt
           from (select
                 distinct
                        "Sequence" as src, "tgt_head" as tgt
                 from "Sequence"
                 where "Sequence" IS NOT NULL AND "tgt_head" IS NOT NULL)
                as fence0,
                (/* epsilon Prefix [Item*Prefix] */
                 select
                 distinct
                        "Prefix" as src, "Prefix" as tgt
                 from "Item"
                 where "Prefix" IS NOT NULL)
                as fence1,
                (select
                 distinct
                        "Prefix" as src, "tgt_bind" as tgt
                 from "Item"
                 where "Prefix" IS NOT NULL AND "tgt_bind" IS NOT NULL)
                as fence2,
                (/* epsilon Variable [Variable*Item] */
                 select
                 distinct
                        "Variable" as src, "Variable" as tgt
                 from "Item"
                 where "Variable" IS NOT NULL)
                as fence3
           where fence0.tgt = fence1.src AND fence1.tgt = fence2.src AND fence2.tgt = fence3.src)
          as t2
     on t1.src = t2.src AND t1.tgt = t2.tgt
where t2.src IS NULL OR t2.tgt IS NULL
```

The code for epsilons can be avoided, which leads to almost half the size of this query:

```
select
distinct
       t1.src as src, t1.tgt as tgt
from (/* case: (ECps es), with two or more elements in es.I{-Eps-}[Statement];template;I{-Eps-}[Template];head */
      select
      distinct
             fence1.src as src, fence3.tgt as tgt
      from (select
            distinct
                   Statement as src, tgt_template as tgt
            from Sequence
            where Statement IS NOT NULL AND tgt_template IS NOT NULL)
           as fence1,
           (select
            distinct
                   Sequence as src, tgt_head as tgt
            from Sequence
            where Sequence IS NOT NULL AND tgt_head IS NOT NULL)
           as fence3
      where fence1.tgt = fence3.src)
     as t1
     left
     join (/* case: (ECps es), with two or more elements in es.head;I{-Eps-}[Prefix];bind;I{-Eps-}[Variable] */
           select
           distinct
                  fence0.src as src, fence2.tgt as tgt
           from (select
                 distinct
                        Sequence as src, tgt_head as tgt
                 from Sequence
                 where Sequence IS NOT NULL AND tgt_head IS NOT NULL)
                as fence0,
                (select
                 distinct
                        Prefix as src, tgt_bind as tgt
                 from Item
                 where Prefix IS NOT NULL AND tgt_bind IS NOT NULL)
                as fence2
           where fence0.tgt = fence2.src)
          as t2
     on t1.src = t2.src AND t1.tgt = t2.tgt
where t2.src IS NULL OR t2.tgt IS NULL
```
# Analysis

Epsilon expressions are introduced for type checking. They satisfy:

```
epsilon X [Y*Z] = I[X]
```

The typechecker introduces `epsilon X [Y*Z]` only if `X ISA Y` and `X ISA Z`.
The typechecker ensures that every expression in the F-structure is type correct, expecially that `r[A*B];s[C*D]` implies `B=C`. Removing epsilons means that this guarantee can no longer be given. However, without epsilons, the type checker still guarantees that expressions in the F-structure satisfy `r[A*B];s[C*D]` implies there is an `X` such that `X ISA B` and `X ISA C`. This is obvious if you consider that every `r[A*B];s[C*D]` comes (at worst) from `r[A*B];epsilon X [B*C];s[C*D]`.

A consequence of this is that the SQL-generator can ignore epsilons, because semantically they are equivalent to `I[X]` and `I[X];r = r`.

**Comment by hanjoosten** [comment]
The SQL generator is ment to transform normilized expressions only. No semantics of normalization should be put into the SQL genarator. This is clearly a normalization issue.

**Comment by WolframKahl** [comment]
Unfortunately I am still not fully confident with parsing
your use of relation algebra withing English sentences ---
could you please help me by clarifying the following:

On Sun, Jan 10, 2016 at 01:18:41AM -0800, Stef Joosten wrote:
 > The typechecker ensures that every expression in the F-structure is
 > type correct, expecially that `r[A*B];s[C*D]` implies `B*C`.

What does `B*C` mean here?
And what does ``implies'' mean here?
Since, so far, when I have seen relation expressions `R` used as ``formulae''
in English sentences, I gather that the intended meaning is `R == V`...
Therefore I actually also have to ask what `r[A*B];s[C*D]` means here.
(Reading `R` as `R != empty` would make some sense,
 but even then I still don't even know what kind of expression `B*C` is.)
``implies`` cannot mean |- , since that would be a type error
(without unlikely assumptions)...


Wolfram

**Comment by stefjoosten** [comment]
Sorry Wolfram, I wrote `B*C` where I meant `B=C`. My mistake. I have corrected my comment in situ.

Does this answer your question?
(By the way, my comment was informal and intended for Han and myself. As a reminder to fix this some day.)

**Comment by WolframKahl** [comment]
Yes, thanks!

(So
 >  `r[A*B];s[C*D]` implies `B=C`

means “the presence of an expression `r[A*B];s[C*D]` implies `B=C` ”; now clear.)

If I consider ```I[B*B];epsilon X [B*C];I[C*C]```,
with ```B = {2,3,4}``` and ```C = {3,4,5}``` and ```X = {3}```,
then ```I[B*B];epsilon X [B*C];I[C*C] = {(3,3)}```,
while ```I[B*B];I[C*C] = {(3,3), (4,4)}```,
or am I misunderstanding something?

**Comment by hanjoosten** [comment]
Well, in your example, x would be a relation from B to C, where B and C are sets. so with B = {2,3,4} and C = {3,4,5}, x cannot be {3}, since x contains tuples. So x could be something like { (2,3), (5,3), (5,4)}.

The epsilon is some internal thing ment for cope with ISA relations between the concepts. i.e. If B would be the set of People, and C would be the set of Males, then obviously, you would be in both sets, but People /= Males, so the concepts are different. However, the if relations r[M*People] and s[Males*N] would be defined, an expression r;s would make sense perfectly. The typechecker will know this. Internally, an epsilon is inserted in the expression.

**Comment by stefjoosten** [comment]
Yes, there is an extra detail you might want to know.

Without any `CLASSIFY` statements, `I[B*B];I[C*C]` is type incorrect.

If the Ampersand-script contains `CLASSIFY` statements such that there is one `X` with `X ISA B` and `X ISA C`, the type checker will accept `I[B*B];I[C*C]` and interpret it as `I[B*B];epsilon X [B*C];I[C*C]`. In that case, `I[B*B];I[C*C] = {(3,3)}`, because `X = {3}`.

However, if (besides `X`) there is also a concept `Y`, with `Y = {3,4}`, Ampersand has a choice. It will choose the largest of `X` and `Y`, picking `Y` as the in-between-concept. Ampersand will now interpret `I[B*B];I[C*C]` as `I[B*B];epsilon Y [B*C];I[C*C]`. The result is `{(3,3), (4,4)}`.

Does that clarify?

**Comment by stefjoosten** [comment]
@WolframKahl Wolfram, do you mind if I clean up the part of our discussion about `B*C` versus `B=C`? In that way, this ticket becomes more understandable for future readers, who might find this interesting.

**Comment by stefjoosten** [comment]
Han, I deleted your comment (see below), to keep the issue understandable for future readers.

________________________________________
Van: Han Joosten <notifications@github.com>
Verzonden: maandag 11 januari 2016 06:49
Aan: Joosten, Stef
Onderwerp: Re: [ampersand] Possible optimisation in SQL-code (#268)

Well, in your example, x would be a relation from B to C, where B and C are sets. so with B = {2,3,4} and C = {3,4,5}, x cannot be {3}, since x contains tuples. So x could be something like { (2,3), (5,3), (5,4)}.

The epsilon is some internal thing ment for cope with ISA relations between the concepts. i.e. If B would be the set of People, and C would be the set of Males, then obviously, you would be in both sets, but People /= Males, so the concepts are different. However, the if relations r[MPeople] and s[MalesN] would be defined, an expression r;s would make sense perfectly. The typechecker will know this. Internally, an epsilon is inserted in the expression.

�
Reply to this email directly or view it on GitHub<https://github.com/AmpersandTarski/ampersand/issues/268#issuecomment-170438967>.

________________________________
Deze e-mail is uitsluitend bestemd voor de geadresseerde(n). Verstrekking aan en gebruik door anderen is niet toegestaan. Open Universiteit sluit iedere aansprakelijkheid uit die voortvloeit uit elektronische verzending. Aan de inhoud van deze e-mail en/of eventueel toegevoegde bijlagen kunnen geen rechten worden ontleend.

This e-mail is intended exclusively for the addressee(s), and may not be passed on to, or made available for use by any person other than the addressee(s). Open Universiteit rules out any and every liability resulting from any electronic transmission. No rights may be derived from the contents of this message.

Disclaimer
Dit bericht met eventuele bijlagen is vertrouwelijk en uitsluitend bestemd voor de geadresseerde. Indien u niet de bedoelde ontvanger bent, wordt u verzocht de afzender te waarschuwen en dit bericht met eventuele bijlagen direct te verwijderen en/of te vernietigen. Het is niet toegestaan dit bericht en eventuele bijlagen te vermenigvuldigen, door te sturen, openbaar te maken, op te slaan of op andere wijze te gebruiken. Ordina N.V. en/of haar groepsmaatschappijen accepteren geen verantwoordelijkheid of aansprakelijkheid voor schade die voortvloeit uit de inhoud en/of de verzending van dit bericht.

This e-mail and any attachments are confidential and are solely intended for the addressee. If you are not the intended recipient, please notify the sender and delete and/or destroy this message and any attachments immediately. It is prohibited to copy, to distribute, to disclose or to use this e-mail and any attachments in any other way. Ordina N.V. and/or its group companies do not accept any responsibility nor liability for any damage resulting from the content of and/or the transmission of this message.

**Comment by WolframKahl** [comment]
> If the Ampersand-script contains `CLASSIFY` statements such that there is one `X` with `X ISA B` and `X ISA C`, the type checker will accept `I[B*B];I[C*C]` and interpret it as `I[B*B];epsilon X [B*C];I[C*C]`.

Does this “one” mean “exactly one”? Apparently not, see below.

 > In that case, `I[B*B];I[C*C] = {(3,3)}`, because `X = {3}`.

(So `X` is still a concept, not a relation like Han seemed to suggest?
 And `epsilon X [Y*Z]` denotes the relation `I[X]` considered as of type `Y*Z`,
 and is well-formed (if and?) only if `X ISA Y` and `X ISA Z`?)

 > However, if (besides `X`) there is also a concept `Y`, with `Y = {3,4}`, Ampersand has a choice. It will choose the largest of `X` and `Y`, picking `Y` as the in-between-concept.

What if there are two maximal such concepts, but no largest one?

 > Ampersand will now interpret `I[B*B];I[C*C]` as `I[B*B];epsilon Y [B*C];I[C*C]`. The result is `{(3,3), (4,4)}`.

But if there is no declaration for `Y`, then the typechecker
would still emit `I[B*B];epsilon X [B*C];I[C*C]`, which evaluates to `{(3,3)}`
which cannot be simplified to `I[B*B];I[C*C]` (both considered as relations on the common implementation type of `B` and `C`), which evaluates to `{(3,3), (4,4)}`?

**Comment by WolframKahl** [comment]
> Wolfram, do you mind if I clean up the part of our discussion about `B*C` versus `B=C`?

Please do, no problem!

**Comment by stefjoosten** [comment]
Han was mistaken. `X` is a concept. For that reason, his comment was removed.

Your observation is correct that `epsilon X [Y*Z]` denotes the relation `I[X]` considered as of type `Y*Z`, and is well-formed if `X ISA Y` and `X ISA Z`.

If there are two maximal such concepts, but no largest one, the type checker will complain and refuse the Ampersand-script.

Your last remark requires Ampersand to have knowledge of populations of concepts. These populations vary dynamically, which would require dynamic type checking. However, we have implemented static type checking. For that reason, the type system makes no use of any knowledge of the populations (which is consistent with the Braga-paper). The only way the type system knows about the order of concepts is by means of the `CLASSIFY`-statements in the Ampersand-script. The actual population of concepts is not taken into consideration by the type system. You might want to try these things in trial programs of your own.

**Comment by WolframKahl** [comment]
I don't think my reasoning is population-dependent: The point I am trying to make (without having tried to understand the SQL above) is that a type-checker-inserted `epsilon X [B*C]` cannot be removed unless you have proof that `X = B \intersection C`.

Or, alternatively, if `X < B \intersection C`, then you could argue that the insertion of `epsilon X [B*C]` is unsound. Actually I think I tend more in this direction, because if `R[A*B]` and `S[C*D]` are two relations declared with these types, where `B` and `C` have a common supertype (e.g., a REPRESENTATION type) `E`, the author of `R;S` may not be aware of the current ontology of subtypes (concepts) of `E`, and might be quite surprised to see  the semantics of `R;S` change due to the introduction of a new subtype (concept) there.

**Comment by stefjoosten** [comment]
7. If `X = B \intersection C`, we know straight away that `X` is the largest concept, because intersection represents the least upper bound in the partial order of concepts. (In other words, if `X = B \intersection C`, there is no `Y` larger than `X` other than `X` itself.)

8. Indeed, if the partial order of concepts (i.e. the set of ISA-statements in a context) changes, the author may be in for surprises. The only solution I can think of is to educate authors.

@sjcjoosten, happy birthday today!  Do you have anything to add to this discussion? ( @WolframKahl, Sebastiaan is much better in this stuff than I am... :-) )

**Comment by WolframKahl** [comment]
Another solution could be intersection types, that is, there would always be the type `B \intersection C`.
(One could restict this to cases where `B` and `C` have a common supertype ─ which are the cases that give rise to possibly problematic `epsilon` insertions, if my understanding is correct.)

Happy Birthday Sebastiaan!

**Comment by stefjoosten** [comment]
This is a design choice. Ampersand insists on a concept name for every allowed type. Consider the following example:

    CLASSIFY Employee ISA Person
    CLASSIFY Student ISA Person

In this case, Ampersand requires that `Employee` and `Student` be disjoint.
In order to allow atoms that are both `Employee` and `Student`, the Ampersand-user must add:

    CLASSIFY StudentEmployee IS Employee /\ Student

The semantics of this statement is that the concept `StudentEmployee` is the actual intersection `Employee /\ Student`. So keyword `IS` tells Ampersand that there is no larger concept than `StudentEmployee` that is `Employee /\ Student`. As opposed to keyword `ISA`, that says nothing about intersection types.

So in the design of Ampersand we have given this choice to the modeler, who can now decide whether two concepts must be kept disjoint or whether an intersection type is allowed. Being a modeler myself, I have learned to appreciate this feature.

**Comment by WolframKahl** [comment]
In my eyes, the presence of
```
CLASSIFY StudentEmployee IS Employee /\ Student
```
is the only kind of proof you are currently considering for facts of shape ```X = B \intersection C```,
so, going back to the head of this issue, only those ```epsilon X [B*C]``` for which
```
CLASSIFY X IS B /\ C
```
is in scope can safely be eliminated.

If you don't know ```X = B \intersection C```, then even if ```X`` is the largest concept with
```
CLASSIFY X ISA B
CLASSIFY X ISA C
```
, you still cannot eliminate ```epsilon X [B*C]``` safely, since there might be an atom ```q``` in the intersection of ```B``` and ```C``` outside ```X```.

Or, simpler, ```I[X];r = r``` does not hold when ```r : [B*C]``` and ```X < B```.

I can rationalise the design decision to insert the ```epsilon``` for the largest common subconcept by assuming that you want to allow situations where ```q```, when interpreted as a ```B```, has a different semantics than when interpreted as  a ```C```. Does this make sense?

**Comment by sjcjoosten** [comment]
Assigning Stef since Han believes this to be a normalisation issue
