### ISSUE TITLE
Implement Monolog as logging framework for php backend

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/Ampersand#269]
It would be very helpful for debugging purposes to have the log window display all the log entries that have been added to the logging cache. @Michiel-s: Would that be possible?

**Comment by Michiel-s** [comment]
In branch 228 the logging functionality is significantly improved. After merging in master i'll work on implementing a third party logging framework called Monolog. This will enable us to e.g. enable logging to logfiles, email, Pushover.

https://github.com/Seldaek/monolog

**Comment by Michiel-s** [comment]
Implemented monolog log framework in branch 228
