### ISSUE TITLE
Interface functionality (bug)

### ISSUE THREAD

**Issue by stefjoosten** [AmpersandTarski/Ampersand#272]
This issue is probably superfluous, as we are waiting for Michiel's CRUD feature. Nevertheless, I want to document this issue as a reminder to myself. In the meantime, I would appreciate @Michiel-s 's view on a possible workaround, because I cannot think of one and I need it badly.
# Situation and Observations

This issue is about the source code in Statements.adl  (AmpersandTarski/ampersand-models@379a8f965cfd2950b1bff22d0735c556ec21e4ab), which I have compiled with Ampersand v3.2.0[master:62e159f], build time: 07-Dec-15.
However, it still doesn't work with Ampersand v3.3.0[master:e9539fc], build time: 25-Jan-16, which is after the fix of issue #260 (representation mismatch)

The script contains the following interface definition:

```
INTERFACE Template (name[Sequence*Name], seq, seqHead, preText, type, identifier) : I[Template]
ROWS[ "naam van dit template" : name[Sequence*Name]
    ,  "Name your items here:" : seqHead
    , items : seq~;I[Variable]
      COLS[ identifier : identifier
          , seq        : seq
          , preText    : preText
          , type       : type
          ]
    ]
```

Right after initializing the database, use "+" to create a new template. You can give this template a name and you can create new variables. However, these variables are not shown in the interface. The table of items (which should contain variables) stays empty. Yet, in the database and in the interface "overzicht" they are visible. Removing `I[Variable]` from the box-expression `seq~;I[Variable]` helps to remove the symptom.

After removing `I[Variable]`, I get to see the variables, but am unable to fill the field `preText`.
![image](https://cloud.githubusercontent.com/assets/275768/12318983/0458c93e-ba9f-11e5-8002-40de86c5e612.png)
# Analysis

My hunch is that the interface functionality does not treat generalization well.

**Comment by Michiel-s** [comment]
@stefjoosten could you check if this issue still occurs when making a prototype with branch 228?

**Comment by stefjoosten** [comment]
OK. Will do

Stef Joosten

M +31 (0)6 51348895
skype: stef.joosten




-----Oorspronkelijk bericht-----
Van: Michiel Stornebrink [mailto:notifications@github.com]
Verzonden: maandag 21 maart 2016 15:46
Aan: Joosten, Stef
Onderwerp: Re: [ampersand] Interface functionality (bug) (#272)

@stefjoosten<https://github.com/stefjoosten> could you check if this issue still occurs when making a prototype with branch 228?

—
You are receiving this because you were mentioned.
Reply to this email directly or view it on GitHub<https://github.com/AmpersandTarski/ampersand/issues/272#issuecomment-199321913>

________________________________
Deze e-mail is uitsluitend bestemd voor de geadresseerde(n). Verstrekking aan en gebruik door anderen is niet toegestaan. Open Universiteit sluit iedere aansprakelijkheid uit die voortvloeit uit elektronische verzending. Aan de inhoud van deze e-mail en/of eventueel toegevoegde bijlagen kunnen geen rechten worden ontleend.

This e-mail is intended exclusively for the addressee(s), and may not be passed on to, or made available for use by any person other than the addressee(s). Open Universiteit rules out any and every liability resulting from any electronic transmission. No rights may be derived from the contents of this message.

Disclaimer
Dit bericht met eventuele bijlagen is vertrouwelijk en uitsluitend bestemd voor de geadresseerde. Indien u niet de bedoelde ontvanger bent, wordt u verzocht de afzender te waarschuwen en dit bericht met eventuele bijlagen direct te verwijderen en/of te vernietigen. Het is niet toegestaan dit bericht en eventuele bijlagen te vermenigvuldigen, door te sturen, openbaar te maken, op te slaan of op andere wijze te gebruiken. Ordina N.V. en/of haar groepsmaatschappijen accepteren geen verantwoordelijkheid of aansprakelijkheid voor schade die voortvloeit uit de inhoud en/of de verzending van dit bericht.

This e-mail and any attachments are confidential and are solely intended for the addressee. If you are not the intended recipient, please notify the sender and delete and/or destroy this message and any attachments immediately. It is prohibited to copy, to distribute, to disclose or to use this e-mail and any attachments in any other way. Ordina N.V. and/or its group companies do not accept any responsibility nor liability for any damage resulting from the content of and/or the transmission of this message.

**Comment by stefjoosten** [comment]
@Michiel-s. I have tried to run ampersand\AmpersandData\FormalAmpersand\Atoms.ifc on commit branch_#228@3a3cdb40aabfc0c9c084918e4304d0f667e81a59 . This script is demonstrable on the master, but not on branch_#228. So maybe we should skype about this.

**Comment by Michiel-s** [comment]
I found out the following bug:

In your interface definition you specify explicitly that for the name relation the srcConcept must be Sequence (the generalization of Template) `"naam van dit template" : name[Sequence*Name]`

However, in the generated interfaces.json file (which the backend uses as input), the concept Template is specified as source (see below). This is not correct. @hanjoosten I think this is something for you. Please reassign me, if this is fixed. I'll then debug this issue further.

```
interfaces.json
{
	"NormalizationSteps": [
		"    I{-Eps-}[Template];name"
	],
	"expr": {
		"isProp": false,
		"tgtConcept": "Name",
		"isUni": true,
		"isIdent": false,
		"srcConcept": "Template",   <--- This is not Sequence as explicitly specified in Interface
		"query": "<query is cut out>",
		"isTot": false
	},
	"viewId": null,
	"crud": {
		"read": true,
		"create": true,
		"delete": true,
		"update": true
	},
	"relation": "rel_name_Sequence_Name",
	"subinterfaces": null,
	"id": "naam_32_van_32_dit_32_template",
	"relationIsFlipped": false,
	"label": "naam van dit template"
}
```

**Comment by hanjoosten** [comment]
I think that there are two separate issues here:
1) The expression `items : seq~;I[Variable]` is not a simple expression. Therefore, modifying it's population should not be allowed. A user defined error shoud be generated on this script. I am however not confident on the exact conditions of this restriction.
2) If the expression would be a simple expression (i.e. `items : seq~`), the json file should contain the source of the declaration.

**Comment by hanjoosten** [comment]
I had a better look at the script. What your intention seems to be is to populate a relation and at the same time enforcing the inserted atoms to be more specific than could be derived from the sign of the declaration. 

In this case, we have 
```
CLASSIFY Template ISA Sequence 
CLASSIFY Variable ISA Item
RELATION seq[Item*Sequence]
```
You intend to populate seq with some tuple (i,s), where i is an element of Variable and s is an element of Template. 

@stefjoosten : Do you agree with this analysis? If so, is this intention formalized? Do we need specific syntax for this?

**Comment by hanjoosten** [comment]
@sjcjoosten: Could the typechecker give this kind of information in some way?
