### ISSUE TITLE
Undefined control sequence. \tightlist

### ISSUE THREAD

**Issue by hanjoosten** [AmpersandTarski/ampersand#273]
When using Markdown as pandoc format, I ran into \tightlist not defined. This is caused by pandoc. We probably still use an old pandoc template for LaTeX. 

(See http://tex.stackexchange.com/questions/257418/error-tightlist-converting-md-file-into-pdf-using-pandoc ).

**Comment by hanjoosten** [comment]
This isn't only for markdown, but it seems to be for all LaTeX output of the functional documentation.

**Comment by hanjoosten** [comment]
(since the use of pandoc 1.15)

**Comment by WolframKahl** [comment]
See https://github.com/osener/markup.rocks/issues/4
