### ISSUE TITLE
Cannot enter the text '0' (zero) in an ALPHANUMERIC type 

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/ampersand#278]
When I have a script containing stuff such as

   itemName :: Item * ItemName [UNI]     REPRESENT ItemName Type ALPHANUMERIC

and I have an `INTERFACE` within which I can edit `itemName`
and I try to enter the (text) '0' (zero),
then it discards the edit.

This may be a consequence of PHP's smart use of '0', 'NULL', "" (empty string) and stuff. 
But it is not the behaviour that I would like to see...

**Comment by Michiel-s** [comment]
This is fixed in branch 228 (soon to be merged in master).
