### ISSUE TITLE
Some ideas about views

### ISSUE THREAD

**Issue by Oblosys** [AmpersandTarski/ampersand#28]
At first I thought that a class system would render views obsolete, but since we will want to access more than just the raw atom id when presenting it, views will still be useful. In fact, they may provide an elegant way to specify the concept-specific html and js code we need for sophisticated presentations of atoms.

Consider this example:

```javascript
SPEC Color ISA String

gName :: Ghost -> String = [("ghost1_","Inky");("ghost_2", "Pinky");("ghost_3", "Clyde")]
gColor :: Ghost -> Color = [("ghost1_","cyan");("ghost_2", "pink"); ("ghost_3", "orange")]

VIEW ColoredGhost: Ghost {ghostName : gName, ghostColor : gColor }
HTML
... <span style="{color: $ghostColor$}">$ghostName$</span> ...
ENDVIEW

INTERFACE GhostlyInterface : I[Ghost]
BOX [ "Ghost": I<ColoredGhost>
    ]
```

The `<ColoredGhost>` annotation in the interface specifies the view that should be used to show the ghost. The `VIEW` specifies how to obtain the name and color from the Ampersand model, and how this information is used to create a colored html presentation.

We can use the same mechanism to present a boolean as an html checkbox:

```javascript
VIEW BoolSwitch: Bool {boolVal : I}
HTML
.. some html presentation of a switch, referring to $boolVal$ ..
JS
.. some JavaScript code needed for switches ..
ENDVIEW
```

At the same time, we can also have a textual presentation for booleans:

```javascript
VIEW BoolYesNo: Bool {boolVal : I}
HTML
<span .. showBoolYesNo($boolVal$).. > ..</span>
JS
.. function showBoolYesNo(bool) { return bool=="True" ? "Yes" : "No"; }
ENDVIEW
```

The annotation to specify the view:

```javascript
INTERFACE ...
BOX [ "Has finished": hasFinished <BoolSwitch>
    ]
```

can be seen as a shorthand for

```javascript
INTERFACE ...
BOX [ "Has finished": hasFinished ATOMIC<BoolSwitch>
    ]
```
    
This is analogous to the way we specify classes for boxes (`"label": rel BOX<Class> [..]`). (We might even want to declare VIEWs for boxes as well, but I haven't really thought about that yet.)

To prevent a multitude of view annotations, we need some way to specify a default view for a concept:

```javascript
VIEW BoolStr : Bool {boolVal : I} DEFAULT
```

For each primitive type we can define a default string-based view, and for any other concept we use a default view that shows the raw atom id string (aka the dirty identifier).

If we have all this, the old VIEW syntax can be treated as syntactic sugar.

Old:
```javascript
VIEW Client: Client(clientName, TXT " from ", clientCity)
```

New:
```javascript
VIEW Client: Client {seg1: clientName, seg2: V;' in ', seg3: clientCity} DEFAULT
HTML
$allAttrs:{attr|$attr.val$}
ENDVIEW
```

In the html template code `allAttrs` is a list of all attributes, and the string-template construct `$allAttrs:{attr|$attr.val$}$` iterates over the attibutes and concatenates the attribute value strings.

In general, a view declaration will look something like this:

```javascript
VIEW <view_id> : <concept> { (<label> : <relation> )* } DEFAULT?
HTML
... $<label>$ ... or some expression referring to $allAttrs$ ..
JS
.. not sure what attributes we would like have here ..
ENDVIEW 
```

A lot of things are still unclear, especially concerning non-univalent relations, editing of values, and how to knit everything together. I am also not sure how compositional the Angular code in the current view tree is, but we may be able to generate some extra code in between to fix that. We will also need to figure out what kind of JavaScript fragments we will allow, and how we will access these.

A nice aspect of the new views is that the impact on the Ampersand language will be rather low, and that we will be able to do a lot of experimenting even on a partial implementation.

I'm interested to know what everybody thinks about this.

**Comment by Michiel-s** [comment]
Hi Martijn,

I really like your suggested solution. Escpecially the JSON-like definition of the attributes of a view:  
`{ (<label> : <relation> )* }`

Furthermore, I would like to add a way to make it possible to refer to external html template files. I personally don't think we should mix html markup with ampersand models in a single script. How about:
```
VIEW <view_id> : <concept> { (<label> : <relation> )* } DEFAULT?
TEMPLATE "filename.html"
ENDVIEW 
```
where the attributes can be used in the template files in the same way as you described with $<label>$

For now, I don't think we need dedicated angularjs controllers for the views. The controllers for the interfaces stay the same. They will handle the data requests to and from the framework. If we do want special javascripting on the views, you always have the possibility to add this in a html file using <script></script> section.

Let me know.

**Comment by Oblosys** [comment]
Good idea about the TEMPLATE link. I do still suspect we will want html fragments in the source directly, but this also depends on how complex these fragments will be. If they are just 1 or 2 lines, it is much easier to read them when they are in the same file. We can use the syntax `HTML TEMPLATE "filename.html"` to denote a template ref, and if absent, expect inline html. The latter requires more parser modifications though, so we can first implement the template-based version only.

I am not familiar with sections. Can you use these to specify JavaScript utility functions such as `showBoolYesNo(bool)` above?

**Comment by Michiel-s** [comment]
Ok.

Yes you can insert js functions as described above in <script/> sections.

**Comment by Oblosys** [comment]
Perfect, then we can leave out the `JS` section.

**Comment by Michiel-s** [comment]
Hi Martijn,

I had the opportunity to play around with the introduced VIEW feature in interfaces and templates. Works great. In order for the backend framework to determine which view variables to send to the frontend, I require a specification of which VIEW to use in the $allInterfaceObjects in Generics.php.

e.g.
```
INTERFACE ...
BOX [ "Has finished": hasFinished <BoolSwitch>
    ]
```
should result in the following attribute specification in Generics.php
```
$allInterfaceObjects =
  array
    ( // Top-level interface 
      '...' => 
        array ( 'name'  => '...'
              ....
              , 'view' => '<label of the view that is used>'
```

Can you add this to Generics.php?

**Comment by Oblosys** [comment]
Done. I missed that one because my example views used the same variables, but we definitely need it.
