### ISSUE TITLE
INCLUDE statements should be relative to the file in which they are found

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/Ampersand#282]
Currently the statement `INCLUDE "file"` interprets `"file"` as a reference to a file where the reference is relative to the directory/path from which Ampersand has taken the script to compile (see e.g. issue #75). Consequently, when you put a group of related files in a directory, you cannot have such files `INCLUDE` one another unless you make assumptions about the path from which the Ampersand script is being compiled. This makes life hard for engineers like me, that try to create module-like applications such as SIAM or Messaging.

I would like to see the behaviour of the `INCLUDE` statement changed so that it interprets file-references relative from the directory/path from which the file is being INCLUDEd.

**Comment by stefjoosten** [comment]
How does this differ from issue #75?

**Comment by sjcjoosten** [comment]
Issue #75 is about allowing INCLUDE statements to have paths. This issue is about how those paths are interpreted.

**Comment by RieksJ** [comment]
An alternative might be to have a syntax like `INCLUDE  "repoid" "fileid"` where `repoid` would either be
* a path such as `C:\Ampersand\Git\ampersand-modules` where the file can be found, or
* a symbolic name for a local repository with some way to resolve that symbolic name into a path where the file can be found.

The symbolic name option may have the nice property that different people can place the repositories at locations as they please, which I consider a benefit over the first option. The first option however is still better than having nothing at all.

**Comment by hanjoosten** [comment]
Currently, all include statements are allowed to have paths. These paths are interpreted as relative w.r.t the main script (the one mentioned as a parameter to ampersand.)
