### ISSUE TITLE
Omission in error messages of INCLUDE statements

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/Ampersand#283]
When you have big projects with very many `INCLUDE`s all over the place, and if you then get a message such as `could not find <somefile>`, it would help a lot if the message would also state the filename and the line number at which this INCLUDE statement generated the error.

**Comment by hanjoosten** [comment]
Very true. Maybe someday.... As a workaround, I advice you to use [Agent Ransack](https://www.mythicsoft.com/agentransack).
