### ISSUE TITLE
Non-existent interface ref loop detected

### ISSUE THREAD

**Issue by Oblosys** [AmpersandTarski/ampersand#29]
The context [ampersand-models/Bugs/No Sentinel/Bug29_InterfaceRefLoop.adl](https://github.com/AmpersandTarski/ampersand-models/blob/master/Bugs/No%20Sentinel/Bug29_InterfaceRefLoop.adl) yields incorrect errors about cyclic interface refs:

    Error! 500 Internal Server Error: Infinite loop in interface 'Ref' by referencing 'Ref' 

The server seems to check the labels on every level in the interface tree, rather than just the roots.

**Comment by Michiel-s** [comment]
I'm aware of this issue and will bugfix this in the first week of March.

**Comment by Oblosys** [comment]
Nice. You can assign yourself with the **Assignee** item on the right (or someone else can do it for you,) and when you fix the issue, you can mention "Closes #29", or "Fixes #29" in the commit message to automatically close it (and create a useful reference to the issue from the commit.)
