### ISSUE TITLE
Transactions in practice

### ISSUE THREAD

**Issue by stefjoosten** [AmpersandTarski/Ampersand#290]
This issue is about the practicalities of transactions in the prototype. It is meant to consolidat a discussion between Michiel, Wolfram, myself, and Yuriy. Here is the problem (at Others: please rephrase if you can do better...)
# Problem

In order to incorporate automated rules in the generated software, the backend (written by the generator) provides API-calls to ECA-rules. These will be called by the front-end just before the end of a transaction. The issue is how to specify the communication between front-end and back-end for this purpose.

@Michiel-s, maybe you start with a proposal, because I expect you will have concrete ideas already.
@WolframKahl , maybe you reformulate the problem if this is not what you intended. Or maybe formulate it sharper...

**Comment by WolframKahl** [comment]
The probably most important aspect of this communication is that ECA-rules need (currently one) ```ecaDelta``` as input. Currently, ``` ecaDelta ::  Declaration```, so the SQL translation would most naturally expect to be able to use the ```decnm``` of that declaration as relation name referring to the relevant actual delta. This actual delta is what is being inserted to or deleted from one of the editable relations of an interface.

Where is this actual delta being communicated via the API right now?
For ECA-rules that are triggered automatically, this is possibly all we need to know.

We were considering to make triggering of ECA-rules (potentially/partially) interactive, e.g., button-triggered. Probably it would be safest to keep the delta (some recent deltas?) as part of the state of the API back-end, and provide the front-end the means to refer to unfinished deltas?

**Comment by stefjoosten** [comment]
On Jan 26th, 2016, @Michiel-s wrote: 

Hi all,

Attached you find an overview of the frontend and backend architecture of our Ampersand prototypes. 

For now, I don't know where and how you want to connect to the framework. A couple of options that we can explore:

1. Build in core framework (php code). This can be done in the MySQL adapter block (Database.php) where all actions on atoms and tuples are communicated with the database.
2. Build as an extension (using Hooks.php). Hooks are registered to be executed at certain Hookpoints. Hookpoints are defined at several places in the core framework, mostly pre- and post function calls.  Currently we only support hooks that are programmed in php, but this can be extended if really necessary. The current ExecEngine is implemented as extension that runs at hookpoint 'preDatabaseCloseTransaction'.
3. Using the API. The API is currently used to communicate data with the frontend. Note that the API is implemented stateless (design rules for HTTP). Because of this characteristic and based on what I think you want to achieve with ECA rule, I don't think the API is a suitable option.
4. Implement ECA rules using the MySQL stored procedures. You can specify procedures (in SQL) to run pre- or post INSERT, UPDATE, DELETE statements. These procedures could be generated by the Ampersand executable (programmed in Haskell) and installed in the DBMS by the backed framework, just like the database structure and initial population. 

Questions that I still have:
* How do the ECA rules look like. Can you give me an example
* In what language will this part be programmed
* What exactly do you need to know in order to evaluate/execute ECA rules
* What will be the output/result of your code
* What do you expect from the backend framework to do with this output/result
* In more general terms, can you draw how the process would look like

Please let me know if you have any questions.

Michiel Stornebrink

Attachment: 
[Architectuur Ampersand FW.pdf](https://github.com/AmpersandTarski/ampersand/files/112939/Architectuur.Ampersand.FW.pdf)
