### ISSUE TITLE
Error in UNI-test (in the presence of intersection types?)

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/Ampersand#292]
The following script (very much like the one used in #291), has a (slightly modified) population (using `seqName` rather than the intended `seqTreeName`). The population is valid. I use Ampersand v3.2.0[HEAD:9f8f087]. When initializing the database, it erroneously produces the following error:
<img width="551" alt="picture1" src="https://cloud.githubusercontent.com/assets/8522589/12574637/22c8104e-c406-11e5-9fe9-4a06e084bee8.png">

```
CONTEXT Bug292 IN ENGLISH

RELATION seqName[Sequence*SeqName] [UNI]   REPRESENT SeqName TYPE ALPHANUMERIC
RELATION itemName[Item*ItemName] [UNI]         REPRESENT ItemName TYPE ALPHANUMERIC
RELATION itemInSeq[Item*Sequence] [UNI]    -- An Item can be part of one sequence
RELATION nextItem[Item*Item] [UNI,INJ,IRF] -- A SRC Item can have the TGT Item as its successor

CLASSIFY SeqTree IS Sequence /\ Item -- This enables trees of sequenced items.
seqTreeName :: SeqTree * SeqTreeName [UNI,TOT]
CLASSIFY SeqName ISA SeqTreeName
CLASSIFY ItemName ISA SeqTreeName

PURPOSE RULE "Congruence of SeqTree names"
{+Since Sequences and Items both have names, SeqTrees, which are both Sequences and Items, might have two (different) names. In order to ensure non-ambiguity of SeqTree naming, this rule ensures that the `itemName` of a SeqTree has the same value as the `seqName` of that SeqTree. The choice is based on the fact that `seqName`s always exist - it is a function, whereas `itemName`s do not (it is [UNI]).-}
ROLE ExecEngine MAINTAINS "Congruence of SeqTree names"
RULE "Congruence of SeqTree names": seqTreeName |- seqTreeName -- itemName;I[SeqTreeName] /\ seqName;I[SeqTreeName]
VIOLATION (TXT "{EX} InsPair;seqName;Sequence;", SRC I[Sequence], TXT ";SeqName;", TGT I[SeqName]
          ,TXT "{EX} InsPair;itemName;Item;", SRC I[Item], TXT ";ItemName;", TGT I[ItemName]
          )

POPULATION seqName CONTAINS [ ("DocAtom", "Document") ]
  POPULATION seqName CONTAINS [ ("Doc_1Atom", "Introduction") ]
  POPULATION seqName CONTAINS [ ("Doc_2Atom", "Definitions") ]

  POPULATION itemInSeq CONTAINS [ ("Doc_1Atom", "DocAtom") ]
  POPULATION itemInSeq CONTAINS [ ("Doc_2Atom", "DocAtom") ]

  POPULATION nextItem CONTAINS [ ("Doc_1Atom", "Doc_2Atom") ]

VIEW SeqTree: SeqTree { SeqTrees : seqTreeName } ENDVIEW
VIEW Item: Item { Item : seqTreeName } ENDVIEW

INTERFACE "Overview": V[SESSION*SeqTree];(I-(itemInSeq;itemInSeq~)) COLS
  [ "Name" : I[SeqTree] <SeqTree>
  , "Items" : itemInSeq~ COLS
     [ "Prev" : nextItem~ <Item>
     , "Item" : I <Item>
     , "Next" : nextItem <Item>
  ]  ]

ENDCONTEXT
```

**Comment by stefjoosten** [comment]
@RieksJ , in order to make this bug reproducible on a later date, could you add text such as (example): 
This issue is visible by compiling this script with Ampersand v3.3.0[master:c3382b6*], build time: 29-Dec-15. (use Ampersand --version to get this line of text).

**Comment by stefjoosten** [comment]
Is it possible that you forgot to add the line: 

    REPRESENT SeqTreeName TYPE ALPHANUMERIC

**Comment by stefjoosten** [comment]
Here are some symptoms, which might help in getting a good diagnosis:

1. Removing property `UNI` from relation `itemInSeq` yields an installation without violations.
2. Atom `DocAtom`, which is a `Sequence`, does not occur in the concept table of sequences (which is located in SQL-table `Item`). This is clearly a mistake, so we have a bug.
3. On first sight, none of the Exec-Engine rules were called. Besides, there are only `InsPair` rules in this script. So we cannot blame any Exec-Engine rule for this.

**Comment by RieksJ** [comment]
Regarding the possible omission of `REPRESENT`: my understanding of the represent-types is that there is one represent-type for a family of ISA's, which is maintained by Ampersand, unless I explicitly make an error in specifying this. From that, it follows that I need not have specified a REPRESENT statement.
Having said that: a choise of REPRESENT-types should not have any effect on the problem I point out.

**Comment by stefjoosten** [comment]
Sounds good...

**Comment by stefjoosten** [comment]
# Hypothesis
I think these problems can be explained from one observation: the user states that `CLASSIFY SeqTree IS Sequence /\ Item`, but there is no concept `X` such that `Sequence ISA X` and `Item ISA X`.

In the RAMiCS article of 2011, Jaap vd Woude already showed that Ampersand rests on an assumption that there must be a greatest lower bound (glb) for two concepts in order to be compared at  all.

In Rieks' script this implies adding two lines, to get the desired effect:

    CLASSIFY Sequence ISA SeqOrItem
    CLASSIFY Item     ISA SeqOrItem
    CLASSIFY SeqTree  IS  Sequence /\ Item  -- This enables trees of sequenced items.

The effect of this addition on Rieks' script is that the problem disappears, as theory predicts. It therefore stands to reason to require a glb for any two concepts that are compared.

# Suggested solution
In this line of reasoning we can do two things, as pointed out by @hanjoosten:
1. forbid the situation and produce a message that suggests the addition of the desired glb.
2. invent a new concept to serve as glb.
I would prefer the first solution from a software engineering perspective.

@sjcjoosten, I would appreciate your review on this issue and your opinion on this matter.

**Comment by stefjoosten** [comment]
After adding

    CLASSIFY Sequence ISA SeqOrItem
    CLASSIFY Item     ISA SeqOrItem
 
to Rieks' script, a new bug shows up in the database: 
![image](https://cloud.githubusercontent.com/assets/275768/12711394/cc427be2-c8bf-11e5-96fa-f1a449ecf7f8.png)
The mistake is that the items `Doc_1Atom` and `Doc_2Atom` should both be in the concept table of `SeqTree`.

**Comment by RieksJ** [comment]
@stefjoosten: Can you be more precise about the reason for preferring "the first solution from a software engineering perspective"? From an information-engineering perspective I would prefer the second solution as I (currently) do not see why I would need to be bothered by creating such a glb. After all, isn't the whole purpose of doing Ampersand that information-engineers are 'unburdenened' (ontzorgd)?

**Comment by hanjoosten** [comment]
In alternative 2, Ampersand has to come up with a name of the largest concept. This name is likely to come up in error messages, logs, etc. Also, situations like this are very rare. It is therefore likely that that the intention of the modeller is different. Therfor, it sounds very reasonable to let the user explicitly define the additional CLASSIFY statements. 

Even if this would not be reasonable, taken into account that this is only a very rare situation, and that getting this right in the software will mean quite some effort, end is errorprone, it just is not worth the effort. (engineering perspective)

**Comment by RieksJ** [comment]
Seems to me that a concept such as `Sequence_Or_Item` could nicely be generated automatically and should not lead to any confusion. I would be very grateful for a concrete example where this would be likely to have a different intention than that of themodeller, as my fantasy is insufficient to do that…
This message may contain information that is not intended for you. If you are not the addressee or if this message was sent to you by mistake, you are requested to inform the sender and delete the message. TNO accepts no liability for the content of this e-mail, for the manner in which you use it and for damage of any kind resulting from the risks inherent to the electronic transmission of messages.

**Comment by WolframKahl** [comment]
For now, just a quick remark: Note that ```SeqOrItem``` is an _upper_ bound of ```Sequence``` and ```Item```, and I do not see why it might need to be the least upper bound (lub) of the two.
The declaration
```
CLASSIFY SeqTree  IS  Sequence /\ Item
```
specifies that ```SeqTree``` is the greatest lower bound (glb) of ```Sequence``` and ```Item```.

The discussion is whether this declaration should only be legal if  ```Sequence``` and ```Item``` are known to have some upper bound?

**Comment by stefjoosten** [comment]
Thanks Wolfram, I always get upper bounds and lower bounds confused. Glad someone is paying attention. I'll fix this by editing the comments above by swapping lub and glb. Somewhat later, I'll remove this comment.

**Comment by hanjoosten** [comment]
I will implement alternative 1. In the error message, a suggestion is done to add proper CLASSIFY statements. As suggested root name, the suggestion of @RieksJ is used.
