### ISSUE TITLE
Wrong table name in Technical data model drawing

### ISSUE THREAD

**Issue by hanjoosten** [AmpersandTarski/ampersand#293]
The file KlantRollen.adl as in commit https://github.com/AmpersandTarski/ampersand-models/commit/bde8e89a87499636b444b39f6987c3e38865edc4 produces the following logical and technical data models:

[LogicalDataModel.pdf](https://github.com/AmpersandTarski/ampersand/files/108221/LogicalDataModel.pdf)

[TechnicalDataModel.pdf](https://github.com/AmpersandTarski/ampersand/files/108226/TechnicalDataModel.pdf)

This issue is about the statement

```
CLASSIFY Identiteit IS Klant /\ KlantRol /\ Beheerder
```

Is can be seen, the logical data model looks fine. In the technical data model, the table for identities is called *Beheerder*. I would have expected that the name of that table would be *Identiteit.*

**Comment by stefjoosten** [comment]
I expect this issue to be linked to issue #292 (Error in UNI-test in the presence of intersection types)

**Comment by stefjoosten** [comment]
The logical data model does not look fine. Concept `Beheerder` has no concept-table.

**Comment by stefjoosten** [comment]
# Analysis
This script yields 4 entities: Beheerder, Klant, Klantrol, and Identiteit.
All four are in the same typology.
However, there is no unique largest element. I.e. the classification tree has no unique root concept.

The generated database model looks like this: 
![image](https://cloud.githubusercontent.com/assets/275768/12701380/aaf98bcc-c808-11e5-832b-6f26d448ea49.png)
What is wrong here, is that `Beheerder` is treated as the primary key attribute in the database. There should be an implicit key,

**Comment by hanjoosten** [comment]
Duplicate of #292
