### ISSUE TITLE
Handling ExecEngine re-run 'overflows'

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/ampersand#296]
Currently, if the ExecEngine (auto)rerun has run for the specified maximum number of times, a fatal error is thrown, which prevents logging etc. to take place.

Please replace line 49 of `ExecEngine.php` that currently contains:
~~~
if(self::$runCount > $maxRunCount) throw new Exception('Maximum reruns exceeded for ExecEngine (rules with violations:' . implode(', ', $rulesThatHaveViolations). ')', 500);
~~~

with

~~~
if(self::$runCount > $maxRunCount){
  Notifications::addError('Maximum reruns exceeded for ExecEngine (rules with violations:' . implode(', ', $rulesThatHaveViolations). ')');
  break;
}
~~~

**Comment by stefjoosten** [comment]
I second that. I would love to have some log-output when the "maximum reruns" exception occurs.

**Comment by RieksJ** [comment]
@stefjoosten I use the following as a workaround: 

1. generate a(n aribitrary) prototype, and find the file `{YourPrototype}\extensions\ExecEngine\ExecEngine.php` (where `{YourPrototype}` is the path to your prototype files).
2. make the changes that are suggested in the ticket (i.e.: replace line 49 as described)
3. save the resulting file as `{YourSourceDir}\include\extensions\ExecEngine\ExecEngine.php`, where `{YourSourceDir}` is the directory that contains the .adl file(s) you generate prototypes out of. This step will ensure that the change you make will be copied to the prototype every time you generate such a prototype.
