### ISSUE TITLE
Interface ref problem in new front-end

### ISSUE THREAD

**Issue by Oblosys** [AmpersandTarski/ampersand#30]
Interface refs are not handled entirely correctly by the new front-end. In 
[ampersand-models/Bugs/No Sentinel/Bug30_InterfaceRefBug.adl](https://github.com/AmpersandTarski/ampersand-models/blob/master/Bugs/No%20Sentinel/Bug30_InterfaceRefBug), no atoms are shown for "buggyRef", even though all three subinterfaces "inline", "ref", and "buggyRef" are equivalent.

**Comment by Michiel-s** [comment]
I'm aware of the issue and will bugfix this in the beginning of March.

**Comment by Michiel-s** [comment]
Fixed
