### ISSUE TITLE
PHP 7

### ISSUE THREAD

**Issue by Michiel-s** [AmpersandTarski/Ampersand#306]
As of dec 2015, PHP 7 is released. At some point in time we have to switch from php 5.6 to php 7. See http://php.net/supported-versions.php for timelines of support and security updates.

PHP 7 is already available in a new version of the XAMPP stack.

**Comment by hanjoosten** [comment]
This would also be a good moment to switch to MariaDB. That is available in the current version of XAMPP too. I don't think that the software needs any changes. However, the documentation will.

**Comment by WolframKahl** [comment]
On Mon, Feb 08, 2016 at 12:07:36AM -0800, Michiel-s wrote:
> As of dec 2015, PHP 7 is released. At some point in time we have to switch from php 5.6 to php 7.

How about switching to some Haskell web server instead?

Wolfram

**Comment by hanjoosten** [comment]
Interesting idea. However, the requirement here is that we want the average &-modeller to be able to deploy his/her prototypes with as little as possible technical skills. 
Another requirement is that this should be possible with as little as possible support of the &-team, for time is a precious asset. 
Xampp meets both requirements nicely, for it is well documented and does the job. If there would exist something like that in Haskell, that would be very nice! Maybe that would free us from php. 
However, I do not know of anything that would meet above criteria, but I could have missed it.

**Comment by Michiel-s** [comment]
PHP7 is supported. I've looked at the release notes and assessed the impact on our back end implementation. I'm running an Ampersand prototype on php 7 for several weeks already. Everything works ok.

Currently Ampersand prototypes require php >= 5.6, which is checked in src/bootstrap.php

**Comment by Michiel-s** [comment]
It’s time to move to php 7 to make use of added functionality

**Comment by hanjoosten** [comment]
My guess is that hardly anything is required for this. The latest Xammp stack and the latest Bitnami all use php 7. Also our docker builds are based on php 7. Travis also supports php 7, so as far as I can see there is no reason any more to not use the php 7 functionality. The only thing that should be done is to update the [requirements in the documentation](https://ampersandtarski.gitbooks.io/documentation/installation/installing_ampersand.html)

**Comment by Michiel-s** [comment]
I agree. There is also a check in the backend code for the rigth version that must be increased.

**Comment by Michiel-s** [comment]
@hanjoosten would you be so kind to update the documentation already and close the issue?

**Comment by hanjoosten** [comment]
done
