### ISSUE TITLE
Special characters cannot be used as atom id

### ISSUE THREAD

**Issue by Michiel-s** [AmpersandTarski/Ampersand#316]
Currently, because of the web based approach for the backend-frontend interface (api), characters that have special meaning in an url cannot be used as atom id. This only holds atoms of concepts that have a non-scalar representation (= object).

Possible solutions I see:
* url encoded these atom strings. I've done a small experiment, but this solution introduces other problems as well (e.g. routing of interfaces in angular frontend app). Double encoding is probably needed.
* don't allow these special characters. Since the atom ids of non-scalar concepts are 'dirty' identifiers which are not intended for the eyes of the end-user, we could forbid these from having special characters in their name.
* add special identifier (assigned by backend fw), which can not be manipulated by any user. Also not when importing via excel.

**Comment by stefjoosten** [comment]
Indeed a low priority. Nevertheless it is a bug. The neat solution is to (double-) encode these atoms. To forbid special characters will work in the short term, but will backfire at a later time (maybe years from now) and incur a much higher cost. So that is unwise. The third solution looks like a specialization of the first solution. If it works, it is fine with me.

**Comment by Michiel-s** [comment]
Ok. For now I will introduce a constraint that allows only alphanumeric characters an an underscore for atoms with an object representation (i.e. non-scalar). Otherwise the current backend-frontend interaction won't work (due to api url mechanism) and we are not able to use the new frontend in short term.

I don't see why this would backfire at a later time? @stefjoosten could you elaborate? If we represent an atom as an integer or date, we also introduce constraints on its representation. Why is this different? Keep in mind that there is already an other constraint for atom representations (type object): Atom representations should fit within 255 characters, which is enforced by the database by the varchar(255) column type.

**Comment by Michiel-s** [comment]
Maybe we can loosen the constraint a bit, but we have to check which of the URL reserved characters don't cause a problem in our implementation.

 https://en.wikipedia.org/wiki/Percent-encoding#Types_of_URI_characters

**Comment by RieksJ** [comment]
When importing the current UETP in a prototype that was built using Ampersand v3.5.0[branch_#228:bf3d940], it says: 

`While evaluating rule ‘DTCriterion tekst parsing – delete parsed CritText’: Only alphanumeric characters and an underscore are allowed for object representations. Atom ‘[DTCriterion]’ (ttype: OBJECT) does not comply to this constraint` 

This seems awkward, since `DTCriterion` is the name of a concept and never appears as an atom identifier as far as I can tell. Also, it means that I have no clue where to fix this (thus justifying the change in priority).

**Comment by Michiel-s** [comment]
The atom id is missing. So it is probably an empty text string. This is an invalid identifier for an atom without scalar representation. Does this help finding the issue?

I'll update the error message to reflect this situation.

**Comment by RieksJ** [comment]
(I modified my earlier comment to reflect that it did not have anything to do with ExcelImport, but with the initialization of the prototype). I removed the default population too, but that did not help. I still have no clue.

**Comment by Michiel-s** [comment]
We found out that the issue of @RieksJ was caused by a database tabla `CritText` not being created when installing the database. This was because a `PRIMARY KEY` statement was added to the column definition while the column representation is a `TEXT (BLOB)`. In MYSQL this is not possible.

This (primary) key issue was already identified in issue #341. A work around fix is implemented.

The mysql error was not thrown/shown. This is solved by commit 7b8ba5787ba1b89d54533f958a83d120df4c7ba3

**Comment by hanjoosten** [comment]
I have added a test at the generator side for the constraint that @Michiel-s added recently. Now, when the value of an atom of a concept with TTYPE == OBJECT contains invalid characters, an error is given to the modeller, not the user of the application. Still I think this constraint is a workaround.

**Comment by hanjoosten** [comment]
@Michiel-s , There was something about replacing the primary key of each concept table with an additional autoincrement primary key. There were some other things too, but I don't remember well. Could you please elaborate on this, so I can add this stuff (in a separate branch).

**Comment by hanjoosten** [comment]
Todo for @Michiel-s : 

- [ ] enable the use of the technicalID values in the urls of the application
- [ ] remove the restriction on values of atoms

**Comment by hanjoosten** [comment]
I changed the prio, because I could use this functionality in several models.

**Comment by hanjoosten** [comment]
@Michiel-s : for what it is worth: http://meyerweb.com/eric/tools/dencoder/

**Comment by Michiel-s** [comment]
I think it is fixed now by means of url encoding of atoms without a representation type. Please report broken functionality if and when it occurs in this issue.

**Comment by RieksJ** [comment]
@Michiel-s: I have seen the following in our SWOT demo:
creating a new atom in a link
- works in commit [branch_#228-f5c0e88]
- provides an error in commit [branch_#228-a1cef3b]
I must go now, so let's see this through on monday
