### ISSUE TITLE
Slim not found

### ISSUE THREAD

**Issue by stefjoosten** [AmpersandTarski/ampersand#324]
When installing branch_#228@890de97967676df5db0dbe97cce0c231e8d9dacf and running my first CRUD-infested script :-) I ran into this error
![image](https://cloud.githubusercontent.com/assets/275768/13721311/8912110c-e822-11e5-82fe-75328a49515a.png)
@Michiel-s can you help diagnose this?

**Comment by RieksJ** [comment]
Starting with branch 228, the creation of prototypes uses 'Composer', which is a dependency manager for the frontend (similar to what cabal does for the compiler). You must install composer and run it every time after creating a prototype. 

So first, you need to download and install 'Composer'. Details can be found at https://getcomposer.org/download/

After you have created a prototype, you should run the following from the command prompt:
`     composer install --working-dir="C:\XAMPP\HTDOCS\MYAPP\" `
and you should make sure that `C:\XAMPP\HTDOCS\MYAPP\` is replaced by the path to the directory where you execute the prototype from.

**Comment by Michiel-s** [comment]
I already discussed this with @hanjoosten and he will check if this step can be included in the ampersand executable. Of course you still have to install Composer first

**Comment by Michiel-s** [comment]
Close this issue and discuss further in #330
