### ISSUE TITLE
Testing on validity of interface label characters is required

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/ampersand#325]
If you have the following texts in an interface:

     BOX[ "eval'd by" : relation 

this will produce an error in the frontend, because it cannot handle the quote character '. 
I suggest that @Michiel-s and @hanjoosten precisely specify the character sets that can be used for labels (and that would be nice for names of relations, concepts, etc., too), and that the use of such chars is tested for by ampersand. When the character sets are defined, I will update the syntax coloring file for EditPad, so that you can see if the appropriate characters are used as you are typing.

**Comment by WolframKahl** [comment]
On Fri, Mar 11, 2016 at 11:54:22PM -0800, Rieks wrote:
> If you have the following texts in an interface:
> 
>      BOX[ "eval'd by" : relation 
> 
> this will produce an error in the frontend, because it cannot handle the quote character '. 

Can this possibly be solved by escaping certain special characters appropriately for the frontend?


Wolfram

**Comment by RieksJ** [comment]
Any (escaped) character set is fine with me, as long as it is properly specified and checked at compile time rather than that it produces runtime errors.

**Comment by hanjoosten** [comment]
@Michiel-s, as far as I'm concerned, the string is transferred correctly in the .json file. Iff there is a good reason that these strings cannot be handled correctly at the front-end, a restriction should be implemented. However, that should only be done if a good reason exists.

**Comment by Michiel-s** [comment]
I'll have a look at it. Think this is a bug that I should fix
