### ISSUE TITLE
How to Create an atom in an empty relation (in branch_#228)

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/ampersand#327]
Consider the following chunck from an INTERFACE:

      sessionCurrentTransaction :: SESSION * Transaction [UNI] -- current transaction in a session
      concernTransaction :: Concern * Transaction [UNI,TOT] -- Every concern belongs to 1 transaction
      concernText :: Concern * Description [UNI] -- A concern can have a description
      concernSHRole :: Concern * SHRole [UNI,TOT] -- Every concern has one stakeholder role that bears the concern.

      , "Concerns": sessionCurrentTransaction cRud BOX <ROWSNL>
         [ "Concerns": concernTransaction~ CRuD BOX <SHCOLS>
            [ "Concerns of current transaction": concernText cRUd
            , "Accountable stakeholderrole": concernSHRole cRUd
         ]  ]

Assume pair `(s, t)` is part of the population of `sessionCurrentTransaction`.

If there is a `c[i]` such that `(c[i], t)` is in `concernTransaction`, then columns appear that show details of every such `c[i]`, with a header and a footer both of which contain the symbol `+` that, when clicked upon, creates a new concern `c_k` as well as a pair `(c_k, t)` in `concernTransaction`.

However, if `concernTransaction` has no population, then the header and footer are not shown, depriving the user of the possibility to clik on the symbol `+` to create a first pair in that relation.

I suggest that, if a relation such as `concernTransaction` in the above example is empty, and the crud-specification has a `C`, then only the header (or footer, but not both) are shown, optionally with a text saying that the relation is empty.

**Comment by Michiel-s** [comment]
You should use `<SCOLS>` instead of `<SHCOLS>`
