### ISSUE TITLE
Session-timout geeft een '500 Internal Server Error'

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/ampersand#328]
Als je een tijdje bij je werkplek weg bent geweest en je sessie is getermineerd door een timeout, dan krijg je een rode foutmelding '500 Internal Server Error'. De fout blijkt dan te zijn: 'Interface is not accessible for active roles or accessible roles (login)'. Kan dat niet meteen een rode foutmelding worden in de trant van 'Session has timed out'?

**Comment by RieksJ** [comment]
A session timeout causes inconsistencies in the sense that undetected rule violations exist. The reason for this is that the session atom is tacitly deleted outside of a transaction. As the user-interface does not change, edits that are doen after the timeout occurred give rise to problems. The solution would be to start a transaction when deleting the timed-out session atom.

**Comment by Michiel-s** [comment]
> Rieks:
A session timeout causes inconsistencies in the sense that undetected rule violations exist. The reason for this is that the session atom is tacitly deleted outside of a transaction

That is actually not the case. Session atoms are deleted by the same function as other atoms are. Therefore the affected conjuncts are checked. Also the execEngine kicks off. (How) can we reproduce the issue you mentioned?
