### ISSUE TITLE
offline use of 'composer'

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/Ampersand#330]
In branch_#228, the 'composer' application is introduced for creating prototypes. However, it requires an active internet connection, thus impeding the development of stuff if internet is not available. I would like to see that  prototypes could also be created in an offline manner.

**Comment by Michiel-s** [comment]
Copied Rieks comment:
Starting with branch 228, the creation of prototypes uses 'Composer', which is a dependency manager for the frontend (similar to what cabal does for the compiler). You must install composer and run it every time after creating a prototype.

So first, you need to download and install 'Composer'. Details can be found at https://getcomposer.org/download/

After you have created a prototype, you should run the following from the command prompt:
composer install --working-dir="C:\XAMPP\HTDOCS\MYAPP\"
and you should make sure that C:\XAMPP\HTDOCS\MYAPP\ is replaced by the path to the directory where you execute the prototype from.

**Comment by Michiel-s** [comment]
> Rieks
In branch_#228, the 'composer' application is introduced for creating prototypes. However, it requires an active internet connection, thus impeding the development of stuff if internet is not available. I would like to see that prototypes could also be created in an offline manner.

No this is not possible. What you can do is store the `lib` folder that is added by composer somewhere on your pc. When you make a prototype without internet connection, just copy that folder to your application folder, instead of running `composer install`.

**Comment by Michiel-s** [comment]
@hanjoosten 

We've discussed the possibility to let the ampersand executable call the `composer install` command after generating a prototype. Can you take into account that it requires an internet connection. How should we deal with this? e.g.:
* Throw error when no internet connection available
* Generate prototype, but skip the composer install command (note! prototype will not work)
* Provide command line option to let the user decide to include composer action or not
* ....

**Comment by WolframKahl** [comment]
On Mon, Mar 14, 2016 at 07:19:24AM -0700, Michiel Stornebrink wrote:
> > Rieks
> In branch_#228, the 'composer' application is introduced for creating prototypes. However, it requires an active internet connection, thus impeding the development of stuff if internet is not available. I would like to see that prototypes could also be created in an offline manner.
> 
> No this is not possible. What you can do is store the `lib` folder that is added by composer somewhere on your pc. When you make a prototype without internet connection, just copy that folder to your application folder, instead of running `composer install`.

This sounds dangerous: So error messages now not only need to mention the commit tag
of the git repository the ampersand exectuble was buitlt from, but also precise version information of everything composer may have pulled?

Wolfram

**Comment by Michiel-s** [comment]
> Wolfram:
This sounds dangerous: So error messages now not only need to mention the commit tag
of the git repository the ampersand exectuble was buitlt from, but also precise version information of everything composer may have pulled?

No that is not necessary. The precise version information of php libraries that are used are mentioned in the composer configuration file, which is part of the ampersand repository. It is only a dependency mechanism, like cabal. With errors, just provide the commit hash and we know enough.

**Comment by WolframKahl** [comment]
On Mon, Mar 14, 2016 at 09:57:20AM -0700, Michiel Stornebrink wrote:
 > No that is not necessary. The precise version information of php
 > libraries that are used are mentioned in the composer configuration
 > file, which is part of the ampersand repository. It is only a
 > dependency mechanism, like cabal. With errors, just provide the commit
 > hash and we know enough.

If the precise versions are specified locally, it should be possible to verify that they are present locally without an internet connection, and install them from the local cache.

Even Cabal can do that...

**Comment by hanjoosten** [comment]
Fixed the easy way: If Composer is not in the path or if there is no internet connection, an apropriate message is printed, which will be helpfull, I assume. 
The option @WolframKahl suggests, is possible, but then we have to get all library info into Ampersand. That is too cumbersomb, and errorprone. (and we can spend our time in more importent things...)

**Comment by RieksJ** [comment]
That's ok with me, as long as I can detect such a condition automatically (cmd-script, batchfile). Does ampersand.exe work with errorlevels/return codes? Can you tell me which code is returned when Composer is not in the path or there is no internet connection?

**Comment by hanjoosten** [comment]
We do not work with errorlevels. You could check if there is a folder named 'lib' in the prototype directory. Or you could (re-)run `composer install --working-dir="C:\XAMPP\HTDOCS\MYAPP\"`afterwards in your script.

**Comment by Michiel-s** [comment]
@hanjoosten I've updated the cmd for composer install when generating a prototype.
`--prefer-dist` provides a means to use caching of packages in local profile of user
`--profile` provides more details about composer install action.

Could you also output the stdout of composer install on ExitSuccess in verbose mode?

**Comment by hanjoosten** [comment]
- [ ] Could you also output the stdout of composer install on ExitSuccess in verbose mode?
