### ISSUE TITLE
hiding an entire BOX in interfaces

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/ampersand#331]
The templates `<ROWSNL>` and `<COLSNL>` provide a way for hiding the row/column headers (labels), which has turned out to be quite useful. Another useful feature would be to automatically hide a complete box (regardless of the template used) if it has nothing to show for. 

Note that this might imply that you cannot use it in combination with C(reate), as the box simply wouldn't be there for showing fields that you would need to create an atom. What the desired behaviour would be for C(reate) cases remains to be discussed.

**Comment by Michiel-s** [comment]
For now you have the possibility to Hide entire box is no target in expression (HROWS and HCOLS) and hide the labels in rows/columns with ROWSNL, COLSNL. In order to hide both label and content for specific subinterfaces in a box, we require the resolution of #133
