### ISSUE TITLE
Issue298.adl untraceable?

### ISSUE THREAD

**Issue by stefjoosten** [AmpersandTarski/ampersand#338]
I cannot find the issue that corresponds to the sentinel test "Issue298.adl". Who can help me out? Is this something @RieksJ recalls? My own memory is blank wrt this test file.

As far as I'm concerned, this test file should not be in ShouldFail,  because
`I[Natural] - I[Even] = {"thisShouldFail" , "one"}` and `I[Natural] - I[Odd] = {"thisShouldFail" , "two"}`, so the union of the two equals `I[Natural]`.

If nobody claims this test case or the issue doesn't turn up, I propose to move "Issue298.adl" to Travis, in should succeed.

**Comment by RieksJ** [comment]
I don’t recall this. However, there is an issue at https://github.com/AmpersandTarski/ampersand/issues/298 that mentions things like ‘even’ and ‘odd’ and ‘natural’s. @stefjoosten even asked @hanjoosten to provide a script. Could it be that the script you refer to is an answer to that question?
This message may contain information that is not intended for you. If you are not the addressee or if this message was sent to you by mistake, you are requested to inform the sender and delete the message. TNO accepts no liability for the content of this e-mail, for the manner in which you use it and for damage of any kind resulting from the risks inherent to the electronic transmission of messages.

**Comment by hanjoosten** [comment]
I wonder why you raise this issue??? An adl script with the name `Issue298.adl` is about issue #298 of course. And when you read the comments in that issue, (the one of 2 feb), it becomes more than clear that the script and the issue are connected.

**Comment by stefjoosten** [comment]
@RieksJ  and @hanjoosten , you are quite right. I misread issue #298. Of course file `Issue298.adl` is about issue #298. Sorry for that. I'm closing this issue.
