### ISSUE TITLE
Relation table info in relations.json does not match database structure

### ISSUE THREAD

**Issue by Michiel-s** [AmpersandTarski/ampersand#343]
Consider the following script:
```
CONTEXT Issue343 IN ENGLISH
  rUniTot :: A * B [UNI,TOT]
ENDCONTEXT
```
After generating a prototype, this results in:
relations.json:
```
[{
"signature": "rUniTot[A*B]",
"mysqlTable": {
    "tableOf": "src",
    "srcCol": {
        "null": false,
        "unique": true,
        "name": "A"
    },
    "tgtCol": {
        "null": false, <----- Specifies that column may not be null
        "unique": false,
        "name": "rUniTot"
    },
    "name": "A"
},
...
}]
```
The `null` attribute of the tgtCol specifies that the column may not be set to null. This corresponds to the TOT constraint on the relation. However, the database structure does not implement this restriction as such, since we use ampersand rules for this.

![image](https://cloud.githubusercontent.com/assets/7961582/13979916/d298cd7c-f0db-11e5-896b-6ee38a82fc06.png)

@hanjoosten could you let the mysql table info in relations.json reflect the generated database structure. That would mean in this case that the `null` attribute is set to true. Please do **not** add the `NOT NULL` constraint in the database structure, because we do want to allow violations within a transaction.

**Comment by hanjoosten** [comment]
Except for primary key fields, this field is allways null. If you need that information, you now can read it from the field dbNull, that I added to the json file.

**Comment by Michiel-s** [comment]
@hanjoosten I was thinking about this issue again. Why did you introduce a new field `dbNull`. I mean, this column defintion is all about the database. The TOT or SUR aspects of the relations are already somewhere else in the relation definiton in relations.json. The `null` attribute which is now still there has no function at all. It's rather confusing. I suggest to delete the dbNull attribute and let the null attribute take its information. Unless there is a good reason for not doing so, but I haven't heard it yet.

**Comment by Michiel-s** [comment]
As discussed with Han by phone: replaced dbNull by null
