### ISSUE TITLE
Relation table column names are switched in default population for r[A*B] [SUR]

### ISSUE THREAD

**Issue by Michiel-s** [AmpersandTarski/ampersand#344]
Consider script:
```
CONTEXT Issue344 IN ENGLISH
  rSur :: A * B [SUR]
  POPULATION rSur CONTAINS [("a1","b1"),("a2","b2")]
ENDCONTEXT
```
The column names for inserting the default population in table rSur are switched!

![image](https://cloud.githubusercontent.com/assets/7961582/13983511/7a7e0a52-f0f0-11e5-8869-fe508c803afb.png)

**Comment by hanjoosten** [comment]
This should be no problem. The relation is stored as a binary table, because it is UNI nor INJ. Please explain what you mean by 'switched'? As far as I know, the corresponding JSON tells you what the source and target is of r. Is this information not sufficient?

**Comment by hanjoosten** [comment]
If there is a problem with the order of the two columns in a binary table, what order do you prefer?

**Comment by Michiel-s** [comment]
Take a close look! atoms `a1` and `a2` are inserted in the wrong column (B)!!, atoms `b1` and `b2` are in colum A.

**Comment by hanjoosten** [comment]
ahh! I see. I missed that. Good point. I'll fix it.
