### ISSUE TITLE
Concept not defined with REPRESENT statement

### ISSUE THREAD

**Issue by Michiel-s** [AmpersandTarski/ampersand#348]
Consider the following script, which defines concept A and represents this concept as alphanumeric. This script defines the concept A in the json output files for the prototype and creates a database table for it.
```
CONTEXT Issue348 IN ENGLISH
  
  CONCEPT A ""
  REPRESENT A TYPE ALPHANUMERIC
  
ENDCONTEXT
```
If we only specify the REPRESENT statement, concept A is not defined and no database table is created:
```
CONTEXT Issue348 IN ENGLISH
  
  --CONCEPT A ""
  REPRESENT A TYPE ALPHANUMERIC
  
ENDCONTEXT
```

Shouldn't concept A be defined implicitly by the `REPRESENT` statement, the same as we do with relation and classify statements. E.g. if I specify `r :: A * B`, both concepts A and B are defined implicitly. Same for `CLASSIFY A ISA B`

**Comment by hanjoosten** [comment]
Hmm. Interesting. The current A-Structure has no explicit knowledge of REPRESENT statements. The Representation is only used in the P-structure. The A-structure has a function (A_Concept -> TType). This guarantees that the A-structure has knowledge of the TType of ALL concepts known in the A-structure. It also knows of the TType of the concept in your example, but it will never be used for that. 

We could do two things:
1) leave it the way it is & close this issue: No harm can ever occur from not having the concept. (As soon as it would be used in any way, extra statements in the model will make the concept 'appear' in the A-structure.
2) write some obviously dead code, to get this concept to a place where it will not be used.

I opt for the first option. Hence, I close this issue. Feel free to reopen, but if you do, please add a motivation for doing so.
