### ISSUE TITLE
!fatal 428 (module Core.AbstractSyntaxTree) - has to do with IDENT

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/ampersand#35]
Consider the following script:

    CONTEXT Ticket35GitHub IN ENGLISH
    
    normtextNH :: NormText * NormHierarchy
    normID :: Norm * NormID

    IDENT Norms: Norm(normtextNH,normID)

    CLASSIFY Norm ISA NormText
    isSubsidiaryToNorm :: NormText * Norm

    ENDCONTEXT

This produces the following error:

    ampersand.exe: !fatal 428 (module Core.AbstractSyntaxTree) Ampersand v3.0.3[fancy-views:2b5ad66]
    Cannot intersect (with operator "/\") expression l of type [NormText*NormText]
    ECps (EDcD normtextNH[NormText*NormHierarchy],EFlp (EDcD normtextNH[NormText*NormHierarchy]))
    with expression r of type [Norm*Norm]
    ECps (EDcD normID[Norm*NormID],EFlp (EDcD normID[Norm*NormID])).

When the `IDENT` statement is removed, the error disappears.

**Comment by stefjoosten** [comment]
Rieks, is deze nog actueel?

**Comment by RieksJ** [comment]
Ja.
