### ISSUE TITLE
ExcelImport (uploader) now fails

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/ampersand#350]
@Michiel-s has refactored the ExcelImport, but it is not backward compatible. For example, if a cell in one of the two header lines of a block is empty, the column in that block should be ignored. However, it now produces errors. I've seen other issues (in UETP) that I cannot properly diagnose and for which I do not know how to work around. Therefore, I have created a new branch ExcelImportINTERFACE that contains this new stuff. Also, I have taken the 'old' ExcelImporter and restored that in branch_#228. 

I still cannot import files, but this time, it seems to be a file uploader issue in js:
<img width="482" alt="picture1" src="https://cloud.githubusercontent.com/assets/8522589/14058089/8ce507b4-f315-11e5-9e27-bfd879701b16.png">

**Comment by Michiel-s** [comment]
@RieksJ could you verify if excel import functionality is ok now in branch ExcelImportINTERFACE?

**Comment by RieksJ** [comment]
No. It is not. I checked by compiling UETP and then importing _Profile_TGN_Autos verkopen.xlsx. It now ignores block columns of which the 2nd header row has an empty cell, as it should. However, it still does not treat columns of which the 1st header row has an empty cell as a comment. I'm not sure about any further stuff.

**Comment by RieksJ** [comment]
Seems to work
