### ISSUE TITLE
!fatal in P2A_Converters.hs:310:45

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/Ampersand#351]
When you compile the following script:

     CONTEXT GRC IN ENGLISH LATEX
     
     CLASSIFY Organization ISA Party
     CLASSIFY OrgUnit ISA BusinessFunction
     CLASSIFY Organization ISA OrgUnit
     
     ENDCONTEXT

It produces the following error:

     ampersand.exe: !fatal, called at src\Database\Design\Ampersand\ADL1\P2A_Converters.hs:310:45
     in main:Database.Design.Ampersand.ADL1.P2A_Converters
                  Ampersand v3.5.0[branch_#228:0b376a9*]
                  error nr: 299
       multiple roots for [BusinessFunction,OrgUnit,Organization,Party]: [BusinessFunction,Party].

While the error is correct, and the message provides sufficient feedback to resolve the error, it should not have been a !fatal.

**Comment by hanjoosten** [comment]
Yes, I have seen this bug. ([Travis told me](https://travis-ci.org/AmpersandTarski/ampersand/jobs/118564591)). It is related with the fix of #349 .
