### ISSUE TITLE
Missing population from Xlsx-include

### ISSUE THREAD

**Issue by stefjoosten** [AmpersandTarski/Ampersand#355]
In ampersand-models@4ff06cc026f37c3e198d71fb9c3cabc86242325f I have submitted a script Arch.adl, which includes 
[processen.xlsx](https://github.com/AmpersandTarski/ampersand/files/193740/processen.xlsx). This compiles correctly with Ampersand v3.4.0[master:f2e1a0d]. It should fail, however, due to violations of the population. It turns out that the population of "processen.xlsx" is not being included by the compiler into the initial database population.

The same behaviour is seen in branch_#228. I have compiled Arch.adl from ampersand-models@cef40a34319f2f8879048f2e1506e374d3357476 in Ampersand v3.5.0[branch_#228:b3a0916]. I have run --haskell, to see where the population comes from. In the resulting Haskell-file, you can see that concept `Handeling` is not populated, whereas other concepts are. Strange! Here is the screenshot:
![image](https://cloud.githubusercontent.com/assets/275768/14134282/4722d9d8-f656-11e5-9662-5632282f166c.png)

It is likely that something is wrong with the xlsx-importer. Another symptom showed up that points in the same direction. The file [processen.bak.xlsx](https://github.com/AmpersandTarski/ampersand/files/193741/processen.bak.xlsx) has exactly the same content as processen.xlsx, but it does not compile. The following screen shot shows the error message. I suspect the error in Xlsx.hs, line 202, because the error message points at the `(!)` operator in `Vector`. This is speculative, however, because I haven't made a diagnosis yet.
![image](https://cloud.githubusercontent.com/assets/275768/14113744/903a7432-f5d4-11e5-9e52-9d95e0a0f62e.png)

**Comment by stefjoosten** [comment]
@hanjoosten, I have some extra symptoms for this issue:

1. In the second tab (worksheet `grondslagen van Handelingen`) of Processen.xlsx, the first column consists of formulas. Might that explain things? When I substituted the formulas for their values, the problem dissappeared.

2. In the first tab (worksheet `Handelingen`) of Processen.xlsx, the cell B1 should contain `omschrijving`. If it doesn't, (for example `aap` instead of `omschrijving`), I get the error message `ampersand.exe: .\Data\Vector\Generic.hs:235 ((!)): index out of bounds (775,775)` instead of `undeclared relation "aap"`.

**Comment by hanjoosten** [comment]
probably the same cause as #305
