### ISSUE TITLE
Changes/bitrot in the parser???

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/ampersand#361]
Using Ampersand v3.5.0 branch_#228:[01dc18b] I find that a few INTERFACEs now produce the error `Parsing stumbled upon symbol '('
at that point expecting keyword "CLASS", symbol '{', keyword "FOR" or operator ':'`
while the used syntax has been supported for a long time now and is (still) not obsolete. An example of such an interface is:

     INTERFACE "My Focus" 
         ( scopeBF, scopeNH
         , bfWantsToBeCompliantWithNorm
         , ctrlIsImpldByOblOfBF, ctrlCoversCtrl, ctrlSpecification, ctrlNAReason
         , ctrlIsAccepted, ctrlIsImplemented, ctrlIsEffective
         ) : '_SESSION'[SESSION] cRud
     ROWS[ "Scoping<br>constraints" : I cRud

Where the complete error message is

     Error(s) found:
     In file "GRC-GeneralInterfaces.ifc" (line 51, column 22):
     Parsing stumbled upon symbol '('
     at that point expecting keyword "CLASS", symbol '{', keyword "FOR" or operator ':'

which points to the opening brace `(` of the second line in the example.
I note that only a few INTERFACEs seem to have this issue.

**Comment by Michiel-s** [comment]
This is an easy one. We're preparing for merging branch 228 in the master. The crud functionality replaces the editable relation syntax between () in an interface. Han committed a change yesterday which removed this syntax for the parser.

**Comment by RieksJ** [comment]
If it is correct what @Michiel-s says, then  @hanjoosten should revert this change immediately. We should only remove the () syntax after we are all satisfied with the new functionality, not a minute before that. The reason is that we may need to revert to an older version of & that uses the ()'s, and we should not be put in a position to have to re-edit all these interfaces again. 

Having said that, if it is correct what @Michiel-s says, @hanjoosten has done a sloppy job, because only a tiny fraction of the INTEFACEs suffers from this. 

Either way, I would like to stress that the ()-syntax should remain available even if it is no longer used, for the reasons mentioned above.

**Comment by Michiel-s** [comment]
Are you reflecting all the changes you make in crud specifications for expression in the editable relations syntax?

I do understand your point though, but on the other hand, allowing syntax that has no effect in your prototype is confusing. Maybe not for you as experienced developer, but others may have difficulties with this. Don't you agree?

Same holds the other way around. Crud syntax is allowed since Nov 2015. Your scripts won't parse against a version before that.

**Comment by hanjoosten** [comment]
Michiel is correct. And my job is not sloppy at all. There is not a single script that can be parsed with the obsolete brackets. However, our parser only tells one error at a time, because that's the way it works for ages.

**Comment by hanjoosten** [comment]
Parse error has been fixed temporarily

**Comment by RieksJ** [comment]
Thanks
