### ISSUE TITLE
!500 internal server error for importing illegal string format from Excel

### ISSUE THREAD

**Issue by stefjoosten** [AmpersandTarski/ampersand#363]
I have compiled Arch.adl from ampersand-models@b28d23057e9bd2aa647ac85e8ee4c8c7dd920e1d using Ampersand v3.5.0[branch_#228:b3a0916].  After installing the base I want to get an overview of "Handelingen". However, this produces a !500 internal server error. 
Fortunately, if I click on it, I get some useful feedback. It turns out to be a Slim application error:
![image](https://cloud.githubusercontent.com/assets/275768/14199515/62efe44a-f7e5-11e5-8408-ebb8073b5c0f.png)

**Comment by hanjoosten** [comment]
At a first sight, I think that this is not an issue with the .xlsx generator. If the population like that would be inserted in the initial population with POPULATION statements in you .adl file, the same error will occur. My guess is, that this has to do with the restriction introduced as part of issue #316. @Michiel-s , can you confirm this?

**Comment by stefjoosten** [comment]
# Diagnosis
This occurs because fields without a declared technical type are (by default) Object, and the atoms of object fields are restricted. That is what happens here. The atom `1994-` is not allowed as an Object atom.

A consequence is that I cannot obtain a prototype without specifiying many concepts explicitly as `ALHANUMERIC`. From a user perspective this feels like excess work, which we didn't have before...

**Comment by Michiel-s** [comment]
I agree with diagnosis above. Let's discuss this further in issue #316
