### ISSUE TITLE
Dirty identifiers should not (ever) be shown on the screen

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/ampersand#369]
One of the ideas with dirty identifiers is that they should not (ever) appear on the screen. Currently, there are some cases where they do appear, one of which is in the 'history bar' (or whatever it is called) on the top of the screen. Here, it could perhaps be replaced with the corresponding default view.

(Others exist, but we need to think a bit about how to deal with that. An example is when atoms are created and you need a complex interface for dealing with many invariants that all need to be satisfied)

**Comment by hanjoosten** [comment]
Please state the problem. This sounds like an idea for a solution, but to what problem? I can fantasize, that the problem behind this solution is the one discussed in #316

**Comment by RieksJ** [comment]
Dirty identifiers (e.g. 'Concern_1243563_12341235')  should not appear on the screen, as they are references that are entirely internal to the 'database'/internals of the prototype. The problem is that they do appear. The issue is not related to #316, since dirty identifiers do not contain the special chars refered to there.

**Comment by Michiel-s** [comment]
I opened an issue to fix the breadcrumb (history bar) #373 

Furthermore the identifier are used when no view is specified. In that case we don't have anything else to show to the user. Please provide an example of where this is not functioning correct.
