### ISSUE TITLE
Rules with 'SESSION' get evaluated while SESSION does not exist

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/ampersand#370]
When you close the browser in a running session with e.g. roles activated, and you restart the prototype, this results in error messages that (obviously?) should not bother the user, such as the following:

<img width="800" alt="picture1" src="https://cloud.githubusercontent.com/assets/8522589/14238143/9f621a16-fa2d-11e5-84cd-2973da70ce05.png">

**Comment by Michiel-s** [comment]
I can't reproduce this. Please let me know when it happens again

**Comment by Michiel-s** [comment]
I found the bug. Fix on its way
