### ISSUE TITLE
Internal Server error when importing Excel sheet

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/ampersand#372]
As in issue [previous], I get an Internal server error, but this time when importing an Excel sheet.
To reproduce the error, compile UETP from tno-models commit [c52b85f]:
1) compile, reset database
2) Import the excel file '_Profile_TGN_Autos verkopen.xlsx'
The debugging stuff produces the following:

<img width="800" alt="picture2" src="https://cloud.githubusercontent.com/assets/8522589/14239524/f62f6060-fa3c-11e5-9c42-caad9a94cfb1.png">

**Comment by Michiel-s** [comment]
Zoals de foutmelding aangeeft: `Concept `TrxTemplate` is not defined, bestaat het door jou gebruikte concept `TrxTemplate` in excelsheet `DT Transactions:F2` niet. Dit komt omdat het concept `TrxTemplate` wordt gedefinieerd in `UETP-PRFL-Ontology.adl` welke je niet importeert in `UETP.adl`
