### ISSUE TITLE
reserved for future use...

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/ampersand#375]
UETP in tno-models [b0a36cb] provides the error 'cannot patch replace for object reference'. 
Reproduce:
- install database, click on '+' in menubar, click 'New Transaction'
- fill in the Transaction ID
- create a new concern (click '+' on the lowest line)
- fill in text under 'Concern', 'Criterion' and 'Stakeholder'
- click on the checkbox under 'Prm'
Then I see the following:

<img width="575" alt="picture4" src="https://cloud.githubusercontent.com/assets/8522589/14307724/8b8a1a34-fbd1-11e5-9d85-fc3115cbd4e5.png">

The checkbox has a view, as mentioned in the fix for Issue #367.

**Comment by Michiel-s** [comment]
I identified the bug and created a ticket for it: #376
