### ISSUE TITLE
Uniform relation signature in generated json files

### ISSUE THREAD

**Issue by Michiel-s** [AmpersandTarski/ampersand#377]
Currently there are two different relation signatures formats in use for generating the json files:

Relations.json: `"signature" : "r[A*B]"`

Interfaces.json: `"relation": "rel_r_A_B"`

Let's uniform and use `r[A*B]` as signature

Note! As this change affects the API we have between haskell and php backend, this change has to be implemented on both sides. Please (re)assign me when ready.

**Comment by hanjoosten** [comment]
@Michiel-s : Your turn.

**Comment by hanjoosten** [comment]
A side-effect of this change is that generated names of propertyrules are now uniform too: the name of some rule based on property TOT of the relation r[A*B] now is "TOT r[A*B]"

**Comment by hanjoosten** [comment]
@RieksJ  @stefjoosten : Whenever you bump into errors about non-existent rule names that are generated, read my latest comments on this issue for the fix.
