### ISSUE TITLE
Views are not used anymore in interfaces

### ISSUE THREAD

**Issue by Michiel-s** [AmpersandTarski/ampersand#379]
@hanjoosten I suspects that in commit f924a76df9200cd486dafcd5eecf6c2f71f5a2d8 something went wrong:  deleted lines 138-140, added 129

In interfaces.json the right viewId is not displayed anymore.

Consider the following script:
```
CONTEXT Test IN ENGLISH

r :: A * B
s :: A * C
t :: A * D

CLASSIFY D ISA C

VIEW "ViewB"          : B ENDVIEW
VIEW "ViewCdefault"   : C DEFAULT ENDVIEW
VIEW "ViewC2"         : C ENDVIEW

INTERFACE A : I[A] BOX
  [ r1 : r -- no view: null
  , r2 : r <ViewB>
  , s1 : s -- expect "ViewCdefault" here
  , s2 : s <ViewC2>
  , t1 : t -- expect "ViewCdefault" here, because D ISA C
  , t2 : t <ViewC2> -- should be allowed, because D ISA C
  ]

ENDCONTEXT
```
The places where a view is explicitly stated (r2, s2 and t2), the wrong view is provided in interfaces.json.

As we've discussed and agreed on, the view priority should be:
1) Explicitly specified `<viewId>` in an interface
2) Concepts own **default** view
3) **Default** view of smallest generalization concept (diamond? just pick one)
4) Else `null`

**Comment by Michiel-s** [comment]
Now something else is broken.

View definitions from the new view syntax (i.e. `VIEW .... ENDVIEW`) are not defined in `views.json` anymore.

**Comment by Michiel-s** [comment]
I think my commit to fix the issue is correct. @hanjoosten could you verify?

**Comment by hanjoosten** [comment]
yes, it is spot-on ! :100:
