### ISSUE TITLE
Request for adding installer queries to Generics.php

### ISSUE THREAD

**Issue by Michiel-s** [AmpersandTarski/ampersand#38]
Currently, when the new framework performs new database install, it runs 2 scripts:
- InstallerDBstruct.php
- InstallerDefPop.php

These files contain the needed queries for that, but also run those queries using a database link that is created in the scripts itself.

In order to return any error and/or success messages, I would like to let the new framework perform those queries. My proposed solution for this feature request is to add the queries that are stated in the installer scripts, to the Generics.php file. The scripts can stay as is, to maintain functionality for the current framework and ampersand application.

The 2 arrays in Generics:
```
$allDBstructQueries = array ( 'DROP DATABASE $DB_name',
                                               'CREATE DATABASE $DB_name DEFAULT CHARACTER SET UTF8',
                                               'DROP TABLE `__SessionTimeout__',
                                               'CREATE TABLE `__SessionTimeout__`
                                                   ( `SESSION` VARCHAR(255) UNIQUE NOT NULL
                                                   , `lastAccess` BIGINT NOT NULL
                                                   ) ENGINE=InnoDB DEFAULT CHARACTER SET UTF8',
                                               etc..
                                              );

$allDefPopQueries = array ( 'INSERT IGNORE INTO `Project` (`Project`,`tgt_projectName`,`tgt_projectStatus`,`tgt_projectDescription`,`tgt_projectStartDate`,`tgt_projectStarted`)
                                                VALUES (\'2013.01\', \'Alfa board\', \'Afgerond\', \'Het maken van een alfa bordje voor de klant.\', \'2013-12-30T23:00:00.0Z\', \'TRUE\')
                                                   , (\'2014.02\', \'Beta board\', \'Loopt\', \'Het verder ontwikkelen tot een beta bordje.\', \'2014-02-14T23:00:00.0Z\', \'TRUE\')
                                                   , (\'2014.03\', \'Release board\', NULL, \'Het gereed maken voor vekoop van het bordje.\', \'2014-07-14T23:00:00.0Z\', \'FALSE\')
                                                   , (\'2014.04\', \'Odysseus\', NULL, \'Onderzoek naar het kunnen verslaan van Troje.\', NULL, \'FALSE\')
                                                   , (\'2014.05\', \'Argos\', NULL, \'Het ophalen van het gulden vlies.\', NULL, \'TRUE\')
                                                    , (\'1970.13\', \'Apollo 13\', \'Gelukt (gelukkig)\', \'Zorgen dat we weer met beide benen op de grond komen te staan.\', \'1970-04-11T13:13:13.1313Z\', \'TRUE\')
                                          ',
                                          'next insert query'
                                          etc
                                          );
```

**Comment by hanjoosten** [comment]
Michiel, 
Currently, the history table is filled with the current data and time. The SQL query expects some PHP variables to be set. ($date, $seconds). How would you like that this is handled?

**Comment by Michiel-s** [comment]
Han,

The $data variable returns the current datatime including microseconds. We can use the MYSQL function `NOW(6)`. The parameter of NOW() specifies that we want 6 digit fraction of a sec (i.e. microseconds).

The $seconds variable returns a UNIX timestamp including microseconds. Here we can use the MYSQL function  `UNIX_TIMESTAMP(NOW(6))` for this.

These functions can be inserted directly into the query:
`INSERT INTO `__History__` (`Seconds`,`Date`) VALUES (UNIX_TIMESTAMP(NOW(6)), NOW(6))`

The result looks slightly different than the format that is created by our own php script, but I can adapt this in the new framework accordingly.

For $seconds: `1425391387761968` -> `1427708759.515664` (with a dot!).
For $date: `3-Mar-2015, 14:03:07.761968` -> `2015-03-30 11:45:59.515664` (standard format)

**Comment by hanjoosten** [comment]
@Michiel-s if you are happy with this fix, please close the issue

**Comment by Michiel-s** [comment]
Almost:) Thanks for the effort so far.

There are still some comments generated in the array $allDBstructQueries

e.g:
```
------------------------------------------------
           -- Plug SESSION
           -- 
           -- fields:
           -- I[SESSION]  [UNI,TOT,INJ,SUR,SYM,ASY,TRN,RFX]
           ------------------------------------------------
```

I already have the changes ready in the frontend framework to test it. Let me know when you're ready.

**Comment by hanjoosten** [comment]
Ah, the comment was on purpose. However, I accidently user Haskell comment syntax. Tomorrow I will chang it to SQL comment.

**Comment by Michiel-s** [comment]
Thanks! 

You can use `From a /* sequence to the following */ sequence, as in the C programming language. This syntax enables a comment to extend over multiple lines because the beginning and closing sequences need not be on the same line.` see https://dev.mysql.com/doc/refman/5.0/en/comments.html

**Comment by hanjoosten** [comment]
It was even more silly: Line comment in SQL can perfectly be '-- '. Behold! The third character is a space....

**Comment by Michiel-s** [comment]
Another issue I found. For some reason the quotes that are used in the queries in $allDBstructQueries and $allDefPopQueries are different from the quotes in InstallerDBstruct.php and InstallerDefPop.php. Why is that?

e.g.:
$allDefPopQueries: 
```
INSERT IGNORE INTO "__all_signals__"
("conjId", "src", "tgt")
VALUES ("conj_0", "p10001", "Hardware"), ("conj_0", "p10002", "Hardware")
```
while in InstallerDefPop.php:
```
INSERT IGNORE INTO `__all_signals__` (`conjId`, `src`, `tgt`)
VALUES (\'conj_0\', \'p10001\', \'Hardware\'), (\'conj_0\', \'p10002\', \'Hardware\')
```

The latter is correct. Mysql uses the grave accent (&#96;) for database objects (table names, column names, etc) and single quotes (&#39;) for values to insert. Can you adjust this?

Furthermore, could you leave out the first 3 queries of $allDBstructQuries: 
`DROP DATABASE $DB_name`
`CREATE DATABASE $DB_name DEFAULT CHARACTER SET UTF8`
`SET SESSION sql_mode = \'ANSI,TRADITIONAL\'`
These can be handled by the framework (Database class), which makes the function for resetting the database less complicated.

**Comment by Michiel-s** [comment]
Looks good, I'll close this ticket
