### ISSUE TITLE
'Delete not allowed' error 

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/Ampersand#381]
I've just committed the CritTexts application in the ampersand-models repo. This demonstrates the use of criteria and variables. However, if you try to delete a criterion, it has a 500 internal error of which firebug says the following:

<img width="805" alt="picture1" src="https://cloud.githubusercontent.com/assets/8522589/14363409/63cea9fe-fd04-11e5-8dac-bc32d0bb4e83.png">

I have no clue as to what is wrong here. Did I make a mistake with specifying the interface or is something else happening here?

**Comment by Michiel-s** [comment]
Typo in haskell output caused this issue.
