### ISSUE TITLE
PHP error: Call to a member function get() on null

### ISSUE THREAD

**Issue by sjcjoosten** [AmpersandTarski/Ampersand#385]
I got a PHP error running the installer (probably a more generic problem, but the installer is all I can run currently).

The request is of `GET /ProjectAdministration.proto/api/v1/admin/installer HTTP/1.1`

The respons reads:
`Fatal error: Call to a member function get() on null in /Library/WebServer/Documents/ProjectAdministration.proto/api/v1/admin.php on line 15`

I have PHP Version 5.6.19 installed through php-osx.liip.ch by Liip (originally developed by www.local.ch)

**Comment by Michiel-s** [comment]
@sjcjoosten I'm not sure what the purpose of line `-RewriteCond %{REQUEST_FILENAME} !-f` was. Probably some copy-pasting from example code on the web. Anyway, the api is still working. Thx for the fix
