### ISSUE TITLE
Old documentation should point to new documentation

### ISSUE THREAD

**Issue by sjcjoosten** [AmpersandTarski/Ampersand#386]
It seems that our sourceforge page https://sourceforge.net/projects/ampersand/ is not being maintained. What's worse, is that it links to the (even less well maintained) wiki, rather than to github.

I have no access to the sourceforge page, but han and oblosys both do. Can one of you change the sourceforge page, or even take it offline?

The wiki I also cannot edit, even though I can login. I keep getting "the connection was reset" as an error.

The link https://www.gitbook.com/book/ampersandtarski/documentation/details is a good place to refer people to, or even https://github.com/AmpersandTarski/

**Comment by hanjoosten** [comment]
Thanks for the hint. It has been somewhat more difficult than I thought it would be, but I guess the current situation at sourceforge can do now.
