### ISSUE TITLE
Error in generalization handling by (Runtime) Excel Import function

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/Ampersand#396]
I have the following scriptlet:

```
varAgr      :: Variable * Agreement [UNI,TOT] -- Scope of the Variable
CLASSIFY Term ISA Variable
```

Consider the following stuff that I want to import into a prototype:

![picture1](https://cloud.githubusercontent.com/assets/8522589/14843018/166c6554-0c4d-11e6-81f1-1d259dfc85af.png)

Column A contains Term-atoms that are also Variable-atoms since Terms are Variables.
Column B contains Agreement-atoms that are to be stored in the `varAgr` relation for the Term/Variable-atoms.
However, the following screenshot shows that the `varAgr` relation is not populated with the pairs that have been specified above:

![picture1](https://cloud.githubusercontent.com/assets/8522589/14843147/ec2f4594-0c4d-11e6-99cb-071a3471e626.png)

**Comment by WolframKahl** [comment]
The first picture does not show enough “following stuff” to explain the second picture ─ better supply verbatim text represntations of both.

By the way, reading
```
CLASSIFY Term ISA Variable
```
almost physically hurts...

Conventionally, terms are either variable symbols (or constant symbols) or applications of function symbols to terms. In a subtyping view of this, you therefore have:
```
CLASSIFY Variable ISA Term
```
(Using the word “variable” to stand for “variable symbol” is normal usage.)

**Comment by RieksJ** [comment]
@WolframKahl: I'm sorry to have (almost) physically hurt you. I'm still looking for better words in the context that I'm using this stuff in. A fast explanation (which I hope offers a bit of comfort rather than hurting you more) is as follows:
A party needs to address some Concerns, which is an assertion of which that party must decide whether or not it is addressed. Evaluation of the assertion by the party should lead to 'true' or 'false'. Thus, an assertion could be a simple or compound statement (of terms) that should be satisfied. A simple statement might contain 'simple' variables/values rather than other terms that provide values only after having been evaluated. There is recursion here: statements produce values and can hence be considered as variables that are being processed by statements in which they are used. Does this provide some clarity?

**Comment by hanjoosten** [comment]
Just curious: What result do you get when you import the script define time, using an INCLUDE statement? (Then the Haskell implementation of the excel importer is used)

**Comment by RieksJ** [comment]
@hanjoosten: Can't tell just yet, because the INCLUDE-importer does not seem to handle multiple atoms in a single cell correctly - when there are multiple atoms in a cell, any white space should be trimmed (I just fixed that in the PHP-importer too).

**Comment by hanjoosten** [comment]
ah. Didn't know about that error. Did you file an issue already?

**Comment by Michiel-s** [comment]
This issue doesn't provide enough information to diagnose the issue. @RieksJ let's discuss this in person and report our findings here

**Comment by Michiel-s** [comment]
This one is fixed long ago.
