### ISSUE TITLE
Generated prototypes broken by new sql generator

### ISSUE THREAD

**Issue by Oblosys** [AmpersandTarski/ampersand#40]
The new sql generator on master causes some problems in the generated prototypes. The prototypes below are currently broken:

http://sentinel.tarski.nl/ampersand/Limorange/index.php?interface=Overview&atom=1
http://sentinel.tarski.nl/ampersand/Delivery/index.php?interface=Overview&atom=1
http://sentinel.tarski.nl/ampersand/Hello/index.php?interface=Overview&atom=1

(These are the only ones I tested, so there's probably more)

**Comment by Oblosys** [comment]
The problem seems to be that the mysql server is not set to ansi mode. If you set this once, with

     SET GLOBAL sql_mode = 'ANSI';

the setting will be remembered until the mysql server is restarted, and you won't notice the problem anymore. It's also possible to specify ansi on mysql.server startup.

Is it okay to force a global ansi for each ampersand installation? This means that also other database applications using the same mysql server will have the setting.

**Comment by Michiel-s** [comment]
I've just pushed a commit to fix this issue. This does not set the sql_mode GLOBALy, but for each database SESSION. The one place where a `SET SESSION sql_mode = 'ANSI'` still needed to be added was in the static files (DatabaseUtils.php).

Han checked it, and it seems to work now.

**Comment by Oblosys** [comment]
Nice. I was already hoping there was a less global way to set the mode. The examples run fine on my machine now. I'll test whether the new front-end and its fancy views work as well and will close the issue if so.
