### ISSUE TITLE
Create an effective landing page for Ampersand

### ISSUE THREAD

**Issue by hanjoosten** [AmpersandTarski/Ampersand#403]
In order to effectively guide potential users of Ampersand to whatever they are looking for, a simple landing page is required. I see the following requirements for this landing page:
- It must be the one place that anyone could start at. It only contains pointers to the most important locations.
- It must be easy to maintain.
- Git. What else?
- It should be inviting.
- ...

Github already offers a comunity page. It can be [set up with like this](https://pages.github.com/). I have been playing around with this. The repo to use is [AmpersandTarski.github.io](https://github.com/AmpersandTarski/AmpersandTarski.github.io)

The page should contain links to:
- [Docs](ampersandtarski.gitbooks.io/documentation/)
- [Latest release](https://github.com/AmpersandTarski/Ampersand/releases/latest)
- old wiki?
- ...

**Comment by WolframKahl** [comment]
Which URL should I currently use to point possibly-interested people to for learning more about what Ampersand is?

**Comment by Michiel-s** [comment]
Currently our GitHub page is the best place to start. The readme provides pointers to the documentation and developers guide.

**Comment by hanjoosten** [comment]
I have been fiddling a bit with [ AmpersandTarski.github.io]( AmpersandTarski.github.io). Comments please!
