### ISSUE TITLE
database reinstall creates 404 not found

### ISSUE THREAD

**Issue by EstherHageraats** [AmpersandTarski/Ampersand#404]
I am trying to get the ampersand environment up and running. Creating prototypes is succesful. But then creating a database is not. Clicking at "reinstall database" results in 404 error. 
As far as I can make out from the inspect-window in chrome the error comes from agular.js:9866 initiating a get for http://locahost/testen.proto/api/v1/installer. There is no such file, but maybe this is not referring to a file.

I am using 
- Chrome (same result with Explorer though)
- Windows 10 home edition
- IIS as webserver
- MySQL 
- php 5.6
- Ampersand v.3.2.0 (dec 2015)

Esther Hageraats

**Comment by hanjoosten** [comment]
@Michiel-s : I have tried to help Esther this week, but I am too unfamiliar with inspecting what goes on in a browser. Do you know what is going on?
@Esther, Have a look at issue #186 It seems similar to what is going on at your Windows 10 machine. There exists a configuration file named `http.conf` somewhere in your webserver stuff. (At least, this is what it is called in Apache).  Does it help if you set `AllowOverride' = true ?

**Comment by EstherHageraats** [comment]
I don't have Apache, but IIS. On a forum I found a reference to windows/system32/inetsrv/config/applicationHost.config
Here really dozens of override-parameters and most of them set on "deny".
I found one on access and set it to "allow" but no change.

When I have the inspect-window open from the start I see that also navbar is not found.

**Comment by Michiel-s** [comment]
@EstherHageraats, The file `../api/v1/installer` doesn't exists, which is ok. The .htaccess file in that folder should rewrite all api calls to index.php. There are already some other issues about this, most of them solved in Ampersand v3.5.x. So I suggest to upgrade to the latest release first. You can download the executable (for Windows) from: [Latest release](https://github.com/AmpersandTarski/Ampersand/releases/latest)

Please also take a look at these related issues: #186 #384 #385

Could you let us know if this solves your problem?

**Comment by EstherHageraats** [comment]
No luck, I'm afraid.
Installed Ampersand 3.5.0
Then dowloaded composer after generating the prototype gave an error about that.
Then proto behaves the same as in the earlier version.
Issue #186 seems the same as my issue, but I cannot find the IIS10 equivalent of Apaches AllowOverride.

Next step: try to disable IIS and MySQL and switch to a XAMPP configuration to that we are talking the same language.

**Comment by EstherHageraats** [comment]
OK, now it all seems to work.
I have uninstalled mySQL as I had it and disabeled IIS.
thenn installed XAMPP. Configured user ampersand, path to prototype etc.
Now it all works.

Full speed ahead to the next hurdle...:)
