### ISSUE TITLE
Database not created when running Ampersand under Linux using 'Reinstall database' button.

### ISSUE THREAD

**Issue by teezeequeue** [AmpersandTarski/Ampersand#409]
@WolframKahl : okay. Compiled the 3.5 version. It has a new dependency named 'composer'. I installed 'composer' as well. All seems fine after that. Deployment of the model to the /var/www/html/ampersand directory worked using the commandline './ampersand --proto=/var/www/html/ampersand ./myModel.adl'. I also tried this with the Roles.adl file.
The red button 'Reinstall Database' still isn't doing what it's supposed to do. And that counts for both options 'Reinstall Database' and 'Reinstall Database (without default population)'. 
But hey, there's a log file in the log directory with a log file 'debug-2016-05-03.log' in it and here are it's contents:
=========== START LOG ===========
[2016-05-03 21:31:59] HOOKS.DEBUG: Hook '\Ampersand\Extension\ExecEngine\ExecEngine::run()' added to 'preDatabaseCloseTransaction' [] []
[2016-05-03 21:31:59] HOOKS.DEBUG: Hook '\Ampersand\Extension\ExecEngine\ExecEngine::run(1)' added to 'postDatabaseReinstallDB' [] []
[2016-05-03 21:31:59] USERLOG.ERROR: Please <a href="#/admin/installer" class="alert-link">install database</a> [] []
[2016-05-03 21:31:59] USERLOG.ERROR: Session not initialized: 1049: Unknown database 'ampersand_mymodel' [] []
[2016-05-03 21:31:59] FW.DEBUG: ## BUILD ANGULAR APP ################################################## [] []
[2016-05-03 21:35:35] HOOKS.DEBUG: Hook '\Ampersand\Extension\ExecEngine\ExecEngine::run()' added to 'preDatabaseCloseTransaction' [] []
[2016-05-03 21:35:35] HOOKS.DEBUG: Hook '\Ampersand\Extension\ExecEngine\ExecEngine::run(1)' added to 'postDatabaseReinstallDB' [] []
[2016-05-03 21:35:35] USERLOG.ERROR: Please <a href="#/admin/installer" class="alert-link">install database</a> [] []
[2016-05-03 21:35:35] USERLOG.ERROR: Session not initialized: 1049: Unknown database 'ampersand_roles' [] []
[2016-05-03 21:35:35] FW.DEBUG: ## BUILD ANGULAR APP ################################################## [] []
=========== END LOG ==========

I intercepted the server response to the command triggered by the red button. As it turns out the response is similar to the response I got with the 2.4 version.
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL /ampersand/api/v1/admin/installer was not found on this server.</p>
<hr>
<address>Apache/2.4.18 (Ubuntu) Server at localhost Port 80</address>
</body></html>

===============================

Hi,
I compiled Ampersand from source from the master branch source files using Stack. All went well without errors or warnings. Next I ran some tests. Unfortunately I ran into some trouble. Can you help me out? First some configuration details, next three tests I performed using the Ampersand binary from the command prompt.
Han suggested a fourth test using the web based UI (test 4). Unfortunately that didn't work either, but it dit give a better clue on what might be going wrong.  

    uname -a: Linux compy 4.4.0-21-generic #37-Ubuntu SMP Mon Apr 18 18:33:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
    ampersand --version: Ampersand v3.4.0[no git info], build time: 23-Apr-16 13:26:29 CEST
    php -v: PHP 7.0.4-7ubuntu2 (cli) ( NTS )
    Copyright (c) 1997-2016 The PHP Group
    Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
        with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies
    en
    extension=mysql.so is working (tested).

    apache2 -v:
    Server version: Apache/2.4.18 (Ubuntu)
    Server built:   2016-04-15T18:00:57

    mysqld --verbose --version:
    ...
    mysqld  Ver 5.7.11-0ubuntu6 for Linux on x86_64 ((Ubuntu))
    ...
    mysqld runs on localhost; username and passwordt both: ampersand
       mysql> SHOW GRANTS;
    +--------------------------------------------------------------------------+
    | Grants for ampersand@localhost                                           |
    +--------------------------------------------------------------------------+
    | GRANT ALL PRIVILEGES ON *.* TO 'ampersand'@'localhost' WITH GRANT OPTION |
    +--------------------------------------------------------------------------+
    1 row in set (0.00 sec)

    mysql --version:
    mysql  Ver 14.14 Distrib 5.7.11, for Linux (x86_64) using  EditLine wrapper

    echo $PATH:
    /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/me/.local/bin

    stack --version:
    Version 1.0.4.3, Git revision db1afb275ebd64016e8ef0db122f0f03da9e5906 (3242 commits) x86_64

    GraphViz : installed
    MikTeX not installed
    dot and neato not installed

    Tests @Commandline: ~/.local/bin$

    [TEST 1]
    ./ampersand --proto=/var/www/html/ampersand ./myModel.adl
    --> No errors

    At the database:
    mysql> show tables;
    +-------------------------------------------+
    | Tables_in_ampersand_temporaryvalidationdb |
    +-------------------------------------------+
    | __History__                               |
    | __SessionTimeout__                        |
    | __all_signals__                           |
    +-------------------------------------------+
    3 rows in set (0.00 sec)

    Webserver:
    <<files were added to the directory>>
    URL: localhost/ampersand

    [TEST 2]
    ./ampersand --proto=/var/www/html/ampersand --interfaces --validate ./myModel.adl
    Error message:
    me@compy:~/.local/bin$ export PATH=$PATH:/home/me/.local/bin
    me@compy:~/.local/bin$ echo $PATH
    /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/me/.local/bin
    me@compy:~/.local/bin$ ./ampersand --proto=/var/www/html/ampersand --interfaces  --validate ./myModel.adl
    Initializing temporary database
    Number of expressions to be validated: 11

    ******Problematic query:
    /* case: EMp1 val c */
                              select
                              distinct
                                     "SESSION" as src, "SESSION" as tgt
                              from "SESSION"
                              where "SESSION" = '_SESSION'
    ******
    ampersand: !fatal, called at src/Database/Design/Ampersand/Prototype/PHP.hs:204:15 in main:Database.Design.Ampersand.Prototype.PHP
                 Ampersand v3.4.0[no git info]
                 error nr: 141
      PHP/SQL problem: Error 1146: Table 'ampersand_temporaryvalidationdb.SESSION' doesn't exist(Sql: $sql)

    --> I tried some other models like for example 'Kernmodel.adl' and that resulted in similar errors. Each time the relations are added as tables while the concept-tables have not been created.

    At the database server
    mysql> show tables;
    +-------------------------------------------+
    | Tables_in_ampersand_temporaryvalidationdb |
    +-------------------------------------------+
    | __History__                               |
    | __SessionTimeout__                        |
    | __all_signals__                           |
    +-------------------------------------------+
    3 rows in set (0.00 sec)

    Webserver
    <<no files added: empty folder>>

    [TEST 3: without validation option]
    ./ampersand --proto=/var/www/html/ampersand --interfaces ./myModel.adl
    Generating new frontend..

    Webserver
    <<files were added>>
    URL: localhost/ampersand

    An http 404 message was displayed on the first web page.
    Apache Error.log:
    <<no new errors messages were logged during tests 1,2,3>>

[Test 4: Han's suggestion to use the red 'Reinstall database' button in the web based UI ]
The button it didn't turn green nor was a database created. Next comes the debugger (FireBug) information.
    the htto GET request on 'http://localhost/ampersand/api/v1/installer':

    GET Request header:

        Host: localhost
        User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0
        Accept: application/json, text/plain, */*
        Accept-Language: en-US,en;q=0.5
        Accept-Encoding: gzip, deflate
        Referer: http://localhost/ampersand/
        Cookie: PHPSESSID=kmvp91n4lfgb19blqphvqpksi7
        Connection: keep-alive

    Server response (from GET request):

        <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
        <html><head>
        <title>404 Not Found</title>
        </head><body>
        <h1>Not Found</h1>
        <p>The requested URL /ampersand/api/v1/installer was not found on this server.</p>
        <hr>
        <address>Apache/2.4.18 (Ubuntu) Server at localhost Port 80</address>
        </body></html>

    And that condition checks out because '/var/www/html/ampersand/api/v1' has only these file in it:
    .htaccess
    Api.php
    index.php

    --> the file named 'installer' is missing. However when I take a peek in the Api.php file the code below shows up: 
(does this perhaps mean that this is a function call error?)

    /****************************** INSTALLER & SESSION RESET ******************************/
        /**
         * @url GET installer
         * @param array $roleIds
         */
        public function installer($roleIds = null){
            try{
                if(Config::get('productionEnv')) throw new Exception ("Database reinstall not allowed in production environment", 403);
               
                Database::createDB();
               
                $db = Database::singleton();
                $db->reinstallDB();
               
                $session = Session::singleton();
                $session->activateRoles($roleIds);
               
                return Notifications::getAll(); // Return all notifications
           
            }catch(Exception $e){
                throw new RestException($e->getCode(), $e->getMessage());
            }
        }

**Comment by WolframKahl** [comment]
Is anybody running the Ampersand frontend successfully with Apache-2.4?

Last time I ran it with some success, I still had Apache-2.2, and I have seen some information that many access control and authentication directives work quite differently in Apache-2.4.


Wolfram

**Comment by hanjoosten** [comment]
Yes, I have no problems. I have a Xampp stack, and my version is 
`Apache/2.4.17 (Win32) OpenSSL/1.0.2d PHP/5.6.19 Server at localhost Port 8056`
However, I run Windows7.

@Michiel-s pointed me to the .htaccess file in the directory api/v1. There have been some issues with this, which may be related to the issues of @teezeequeue : 
Have a look at issues #384 and #385 . Let us know if this makes any difference for you

**Comment by Michiel-s** [comment]
@teezeequeue I see you're using Ampersand v3.4.0. Please note that we've made some major changes to the backend-api-frontend, including a new API framework. It might help to upgrade to v3.5 (current release).

**Comment by teezeequeue** [comment]
Hallo Han,

De .htaccess lead op Linux leverde niets op. Daarom maar even 
overgestapt op Windows 7 SP1 icm XAMPP om het aantal variabelen in dit 
experiment te beperken.

Nogmaals Hello, worldb (zie attachment: myadl.adl; de is de Hello.adl 
testcase).
Ik heb ampersand versie 3.5 *) nu onder dezelfde specs draaiende als jij 
onderstaand aangeeft. Waarschijnlijk op de ampersand.exe versie na, die 
ik gewoon gedownload heb.
     *) output van ampersand.exc --version: Ampersand 
v3.5.0[master:bf6e4b7], build time: 28-Apr-16 10:06:21 West-Europa 
(zomertijd)
Eerst heb ik het adl bestand door ampersand heen gehaald: 
C:\Users\test\Desktop\ampersand\ampersand.exe -V 
C:\Users\test\Desktop\ampersand\myadl.adl 
--proto=C:\myApps\xampp\htdocs\ampersand

Vervolgens heb ik de database geinstalleerd via de UI optie 'reinstall 
database'. Dat levert een positief resultaat op en eveneens een nieuw 
schema in de ampersand database met 'atomen' in de 'identifier', 
'identifies' en 'things' conceptentabellen.

==> Toch krijg ik ook nu een http 500 (Internal Server Error), ook na 
het schonen van het browser profiel: http://localhost/ampersand/#/Overview
En wederom vanuit de .\api\v1\index.php (zie melding verderop)

[commandline uitvoer]
C:\Users\test\Desktop\ampersand>C:\Users\test\Desktop\ampersand\ampersand.exe 
-V C:\Users\test\Desktop\ampersand\myadl.adl 
--proto=C:\myApps\xampp\htdocs\ampersand
Reading file C:\Users\tester\Desktop\ampersand\myadl.adl
Checking on rule violations...
No violations found.
No signals for the initial population.
Generating prototype...
   Generating settings.json
   Generating mysql-installer.json
   Generating relations.json
   Generating rules.json
   Generating concepts.json
   Generating conjuncts.json
   Generating interfaces.json
   Generating views.json
   Generating roles.json
Generating frontend..No user includes (there is no directory 
C:\Users\tester\Desktop\ampersand\include)
   Generating views\Overview.html
   Generating views\Id.html
   Generating views\Th.html
   Generating controllers\Overview.js
   Generating controllers\Id.js
   Generating controllers\Th.js
   Generating RouteProvider.js
..done.

Prototype files have been written to C:\myApps\xampp\htdocs\ampersand
   Trying to download and install Composer libraries... Succeeded. 
(stdout is empty)


--> Heb jij nog tips voor mij?

Met vriendelijke groet,
    Tzadiq


[Error]
Slim Application Error

The application could not run because of the following error:
Details
Type: Exception
Code: 404
Message: Resource 'ONE_1463316311_252890[ONE]' not found
File: 
C:\myApps\xampp\htdocs\ampersand\src\Ampersand\Interfacing\InterfaceObject.php
Line: 331
Trace

#0 
C:\myApps\xampp\htdocs\ampersand\src\Ampersand\Interfacing\InterfaceObject.php(463): 
Ampersand\Interfacing\InterfaceObject->atom('ONE_1463316311_...')
#1 C:\myApps\xampp\htdocs\ampersand\api\v1\resources.php(144): 
Ampersand\Interfacing\InterfaceObject->create('{}', Array)
#2 [internal function]: {closure}('ONE', '_NEW_', Array)
#3 C:\myApps\xampp\htdocs\ampersand\lib\slim\slim\Slim\Route.php(468): 
call_user_func_array(Object(Closure), Array)
#4 C:\myApps\xampp\htdocs\ampersand\lib\slim\slim\Slim\Slim.php(1357): 
Slim\Route->dispatch()
#5 
C:\myApps\xampp\htdocs\ampersand\lib\slim\slim\Slim\Middleware\Flash.php(85): 
Slim\Slim->call()
#6 
C:\myApps\xampp\htdocs\ampersand\lib\slim\slim\Slim\Middleware\MethodOverride.php(92): 
Slim\Middleware\Flash->call()
#7 
C:\myApps\xampp\htdocs\ampersand\lib\slim\slim\Slim\Middleware\ContentTypes.php(81): 
Slim\Middleware\MethodOverride->call()
#8 
C:\myApps\xampp\htdocs\ampersand\lib\slim\slim\Slim\Middleware\PrettyExceptions.php(67): 
Slim\Middleware\ContentTypes->call()
#9 C:\myApps\xampp\htdocs\ampersand\lib\slim\slim\Slim\Slim.php(1302): 
Slim\Middleware\PrettyExceptions->call()
#10 C:\myApps\xampp\htdocs\ampersand\api\v1\index.php(50): Slim\Slim->run()
#11 {main}


On 05/03/2016 07:34 AM, Han Joosten wrote:
>
> Yes, I have no problems. I have a Xampp stack, and my version is
> |Apache/2.4.17 (Win32) OpenSSL/1.0.2d PHP/5.6.19 Server at localhost 
> Port 8056|
> However, I run Windows7.
>
> @Michiel-s <https://github.com/Michiel-s> pointed me to the .htaccess 
> file in the directory api/v1. There have been some issues with this, 
> which may be related to the issues of @teezeequeue 
> <https://github.com/teezeequeue> :
> Have a look at issues #384 
> <https://github.com/AmpersandTarski/Ampersand/issues/384> and #385 
> <https://github.com/AmpersandTarski/Ampersand/issues/385> . Let us 
> know if this makes any difference for you
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub 
> <https://github.com/AmpersandTarski/Ampersand/issues/409#issuecomment-216442693>
>


CONTEXT Hello IN ENGLISH

PURPOSE PATTERN Hello
{+
This pattern is a very small, but demonstrative Ampersand script.
It contains one relation, one rule and three interfaces.
-}

PATTERN Hello

  identifies :: Identifier * Thing       PRAGMA "" " and " " are paired in relation identifies".

  RULE "identification": I |- identifies;identifies~ -- totality of identifies
    MEANING IN ENGLISH "Every identifier identifies at least one Thing"

ENDPATTERN

INTERFACE Overview  : I[ONE]
  BOX [ identifiers : V[ONE*Identifier]
      , things      : V[ONE*Thing]
      ]

INTERFACE Id : I[Identifier]
  BOX [ id         : I[Identifier]
      , identifies : identifies
      , back       : V[Identifier*ONE]
      ]

INTERFACE Th : I[Thing]
  BOX [ id                 : I[Thing]
      , "is identified by" : identifies~
      , back               : V[Thing*ONE]
      ]

POPULATION identifies[Identifier*Thing] CONTAINS
    [ ("1", "Guggenheim Museum")
    ; ("2", "France")
    ; ("3", "Rutte")
    ; ("4", "Rutte")
    ]

ENDCONTEXT

**Comment by hanjoosten** [comment]
Nice to see that you have come some further again. You currently get error messages where they should not be in place. I think it works already without you knowing it. See issue #423

**Comment by stefjoosten** [comment]
@teezeequeue, has your problem been solved? If yes, you may close this issue. If no, can you tell what you still need?

**Comment by teezeequeue** [comment]
@stefjoosten, 
I haven't checked. I switched to using the command line interface recently and quitted using the web based UI. The command line interface has proven to be more efficient for me.
In short: to me this case is closed. However, for all those users using Linux it may be worthwhile to have a verified installation and verification procedure at hand.
