### ISSUE TITLE
Bug (related to the type checker or the code generator)

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/Ampersand#410]
Consider the following script:
~~~
isACopyOf :: X * X [UNI,IRF,ASY]

CLASSIFY C ISA X

-- When X's are copied, and an X is also a C, then the copy should also be a C
ROLE ExecEngine MAINTAINS "Copy classification property"
RULE "Copy classification property": isACopyOf;I[C] |- I[C];isACopyOf 
VIOLATION (TXT "{EX} SetConcept;X;C;", SRC I)
~~~
At runtime, the `VIOLATION` statement is wrong, as `SRC I` is not replaced with the source atom of the violation, but it is empty (NULL). I consider this to be a bug.

I have noted that this bug goes away when `SRC I` is changed into `SRC I[X]` in the violation statement, which causes me to believe that this is an error in the type checker.

**Comment by hanjoosten** [comment]
I see nothing wrong with the typeing of the expression. At both `;` places in the expression an epsilon is inserted, which is perfectly valid. Your intention seems to be that isACopyOf is a purely endorelation. (i.e. of type [X*X] or [C*C]). However, in Ampersand, the type of any relation might differ based on the context (the expression) where it is used. There is nothing wrong with that, and very usefull in all other cases.

**Comment by RieksJ** [comment]
If there is nothing wrong with the typeing of the expression, then I would expect that the `SRC I` in the violation statement would be replaced with the source atom of the detected violation. That is not the case. Instead, there is no atom (i.e., it is NULL), which causes a malfunction of `SetConcept`. In that case it is a bug in the code generator.

**Comment by hanjoosten** [comment]
# Diagnosis
I can confirm that the type of the rule is [X*X], which is right. However, this seems not to be taken into account for the type of the VIOLATION part of the RULE statement..  

The SRC part in this case is denoted in the A structure as `PairViewExp Src (EDcI cpt_C)`. However, that should be `PairViewExp Src ((PlainConcept "C") (Sign cpt_X cpt_C))`

# Solution
A fix should be made in P2A_Converters.hs, probably somewhere near line 913. The source and target of an expression in the violation segments should match with the sign of the rule. 

@sjcjoosten: Could you please fix this?
