### ISSUE TITLE
Deleting a row from a COLS interface does not refresh

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/Ampersand#412]
When I delete a row in an INTERFACE that shows COLS, by clicking on the dustbin-icon, the screen does not change, even though the appropriate atom is discarded from the database. In such cases (perhaps also in other kinds of interfaces such as ROWS etc.), the screen needs to be refreshed.

If this is done generally after deleting atoms, this would also solve the issue that we have with logouts not refreshing the screen.

**Comment by hanjoosten** [comment]
currently, SHCOLS does not have this problem.

**Comment by hanjoosten** [comment]
@RieksJ : I think that this is the same problem as described in issue #430. Can you confirm this?

**Comment by RieksJ** [comment]
I'm not sure. I use FireFox. Since I do not have these popups asking me what to do with dialog boxes, it seems to me that (while) the issues (may be related, they) are different.
