### ISSUE TITLE
Duplicate key field upon importing the same key field twice.

### ISSUE THREAD

**Issue by stefjoosten** [AmpersandTarski/Ampersand#413]
This bug appears by compiling and running the file https://github.com/AmpersandTarski/ampersand-models/blob/master/Casus%20Gemeente%20Selectielijst/selectielijst.ifc from commit AmpersandTarski/ampersand-models@113b4a1f46f3c7b6edbfabcf0e93cae9adfaee2e with Ampersand v3.5.0 [HEAD:f9db878], which I built on 04-May-16 15:26:14 West-Europa (zomertijd).

The following screen is obtained when installing the application on the database for the first time:
![image](https://cloud.githubusercontent.com/assets/275768/15071897/4b183b4a-138f-11e6-8c5a-3ec189ef385b.png)

Below you'll find a detailed view, which shows the symptom:
![image](https://cloud.githubusercontent.com/assets/275768/15071922/891c9b0c-138f-11e6-8b0c-8481a2e2dc79.png)

In file `mysql-installer.json` we find the string `        "INSERT INTO \"Termijn\" (\"Termijn\") VALUES ('5 of 10 jaar') , ('25 jaar') , ('30 jaar') , ('3 jaar') , ('E') , ('10 jaar') , ('5 jaar') , ('1 jaar') , ('15 jaar') , ('7 jaar') , ('20 jaar') , ('16 jaar') , ('11 jaar') , ('110 jaar') , ('11 Jaar') , ('50 jaar') , ('19 jaar') , ('21 jaar') , ('7 jaar') , ('4 jaar') , ('4 weken') , ('1 / 10 jaar') , ('1 / 5 jaar') , ('40 jaar') , ('1,5 jaar of 110 jaar') , ('Adviesverzoeken, zienswijze van de organisatie') , ('7 jaar en 3 maanden')"`, which is the culprit, so we must look for the cause of this phenomenon in the generator of the `mysql-installer.json`-file.

The urgency of this bug lies in the fact that students will be using this after the summer of 2016. This type of bug can be quite killing for them.

**Comment by stefjoosten** [comment]
I tried to insert a `nub` into line 147-148 of file https://github.com/AmpersandTarski/Ampersand/tree/master/src/Database/Design/Ampersand/Prototype/Generate.hs, yielding:

    "VALUES " ++ intercalate "\n     , " (nub [ "(" ++valuechain md++ ")" | md<-tblRecords] )

That didn't work, however

**Comment by stefjoosten** [comment]
I tried to do the same in `ADL2Fspec.hs`, on line 528. Again with no effect.
![image](https://cloud.githubusercontent.com/assets/275768/15075860/e56648ba-13a6-11e6-9c98-163478d541a6.png)

**Comment by hanjoosten** [comment]
# Diagnosis
When you run with --haskell, the haskell output shows the content of each Concept. There are quite a few atoms that are questionable. 

In the concept `Termijn` there are two atoms, which are probably intended to be the same:
  * `7<space>jaar`
  * `7<space><space>jaar`

Because of a faulty implementation of a request to get rid of \n characters (issue #378) , all whitespace was reduced to a single space in the query. This resulted in both above atoms to appear twice in the INSERT query. This is obviously wrong. 

# Solution: Remove the reduction of whitespace in the query.

**Comment by stefjoosten** [comment]
Fair enough. I think that we need to do the "getRidOfSpaces" switch as follows:
1. normalize every sequence of spaces (i.e. spaces, newlines and tabs) to one space.
2. remove leading and trailing spaces entirely.

**Comment by hanjoosten** [comment]
not so fast: That is another issue. With or without that swich, this error in the INSERT statement must not occur.

**Comment by stefjoosten** [comment]
Agree. If the difference between `7<space>jaar` and `7<space><space>jaar`is relevant, we should not give the user a Slim Application Error, but let him suffer the consequences in Ampersand.
That suggests that we should tell MySQL that  `7<space>jaar` and `7<space><space>jaar` are distinct. For that would resolve the Slim Application Error, and give the programmer the consequences in the Ampersand-world. That leaves us with a situation that we can explain in the classroom.

**Comment by hanjoosten** [comment]
This issue has now been fixed in the development branch.
