### ISSUE TITLE
New switch: --no-double-whitespace

### ISSUE THREAD

**Issue by hanjoosten** [AmpersandTarski/Ampersand#414]
There are usecases, that we want to *protect* the user of mistakes due to misleading whitespace in atoms. By introducing this switch, we can enable this functionality. What it does is the following:

In *all* atom values (=population):
-  [ ] remove all leading and trailing whitespace
-  [ ] remduce any sequence of whitespace to either a single newline or a single space. The choice between these two depends on the presence of newline in the sequence being reduced.

**Comment by RieksJ** [comment]
The 2nd requirement - reducing 'inline' whitespace - needs to be carefully specified. For example, what if there is a space/tab before/after a newline? Do you keep the space/tab or the newline? What if you have CR+LF? 
Before, c.q. in order to decide on this, it might help to elaborate on the use cases whose existence you postulate.

**Comment by hanjoosten** [comment]
@stefjoosten : Rieks is very right. Please specify what your student's need is. Then I will make it so.

**Comment by RieksJ** [comment]
This seems related to issue #413. While I agree that the exposure of students (as well as the likes of myself) to SLIM errors (and similar errors) should be minimized, I do not mind them (as well as myself) to be disciplined somewhat, e.g. when it comes to handling spaces. `somename` is indeed different from `some name` or ` somename` or `somename `, and they should be aware of that. 

Note that this discussion is quite different from another one I had with @stefjoosten, which was about reading many/large excel-files whose contents was larded with spaces. I do not mind these different discussions having different outcomes.

**Comment by hanjoosten** [comment]
There are currently three sources of population (except form directly entering in a browser):

1. As population in a script
2. Reading a .xlsx file using an INCLUDE statement
3. Reading a .xlsx file using the runtime excel importer. 

Being strict in the first case (populations inside an .adl script) is fine with me. I don't think that this is used for large (i.e. 'real world') populations. 

Being strict in the .xlsx has as consequence that a lot of real world spreadsheets have to be cleaned before they can be effectively used by Ampersand. 

I think that fiddling around with whitespace within a value can be quite harmfull: Why replace a double space by a single space in between words, but leaving spaces directly after a newline, as they are intended as layout? This is a useless path to walk along. 

However, it might be usefull to strip leading- and trailing spaces from values, specifically when dealing with multi-value cells. (using some separator to enable multiple atoms in a single cell. 

What do you guys think?

**Comment by RieksJ** [comment]
Nicely described! Good suggestion...

**Comment by hanjoosten** [comment]
I fixed this by leaving inbetween whitespace intact. Only leading and trailing spaces (not tabs, newlines etc) are now ignored by default.
