### ISSUE TITLE
What should --diagnosis do? no pdf created

### ISSUE THREAD

**Issue by EstherHageraats** [AmpersandTarski/Ampersand#417]
Ampersand -fl works and creates a bunch of files in my Output-directory.
Ampersand --diagnosis --verbose give a messagen "reading file testen.adl", but it finishes without doing anything (at least that's how it seems). No files are generated.

**Comment by hanjoosten** [comment]
Excellent question! You probably looked at the [documentation](https://ampersandtarski.gitbooks.io/documentation/content/command-line-interface/switches.html) if you could find an answer. I saw that it didn't tell, so I added the info that also --fspec should be used. 

In cases like this, the documentation has a very convenient way to report these kind of questions/comments: Hover over the paragraph will show a tiny '+' - symbol to the right of the paragraph. You can ask these kinds of questions right at the documentation. Just give it a try whenever you feel like it. :smile:
