### ISSUE TITLE
IN DUTCH results in error creating functional spec

### ISSUE THREAD

**Issue by EstherHageraats** [AmpersandTarski/Ampersand#419]
Trying to figure out how Ampersand deals with language in the functional spec:

CONTEXT IN ENGLISH results in the following:
all text that have no added language are being printed in func spec.
So adding ”IN ENGLISH” after MEANING etc does not seem to add anything.

CONTEXT IN DUTCH results in an error:
Package babel Error: Unknown language ’english’. 
But there is no text ’english’ in my adl-file. 

Suggestion: make documentations consistent with currect application.
related issue #127

**Comment by hanjoosten** [comment]
This is not an Ampersand issue. It is LaTeX related. It happens if a previous .aux file was generated with that different language. For more info, see [this answer](http://tex.stackexchange.com/questions/82669/will-cruft-from-a-previous-compile-ever-change-the-final-look-of-my-document)
