### ISSUE TITLE
Default TODO in functional spec

### ISSUE THREAD

**Issue by EstherHageraats** [AmpersandTarski/Ampersand#420]
When no TODO is defined, the functional spec prints the following:

TODO: Inleiding bij de rol-regel tabel

**Comment by hanjoosten** [comment]
The chapter this is in, is still in development 8-((

**Comment by hanjoosten** [comment]
Did some enhancements to the functional document generator. All these TODO statements have been fixed. However, there still is a lot of ongoing work to get a smooth functional specification document.
