### ISSUE TITLE
Logical data model of FormalAmpersand contains too many boxes 

### ISSUE THREAD

**Issue by hanjoosten** [AmpersandTarski/Ampersand#422]
Have a look at the current LDM of FormalAmpersand. As one can see, there is some strange thing going on in handling ID values. Some things are `named`. 
1. In the box fro Concept (somewhere in the middel of the diagram) we see the relation `name` to be an Identifier. There is no explicit box for the concept `Identifier` in the drawing.
2. For Rule, we have a the relation `name[Rule*RuleID]` drawn between two distinct boxes. 
3. For Conjunct, we have Conjunct and ConjunctID as separate boxes. They seem unrelated!

![logicaldatamodel](https://cloud.githubusercontent.com/assets/1159672/15274195/04ca5324-1aad-11e6-90ad-1c7b72809953.png)

**Comment by hanjoosten** [comment]
It is getting a bit better now:

![logicaldatamodel](https://cloud.githubusercontent.com/assets/1159672/15450951/088d8d32-1fad-11e6-92c2-9337ee523652.png)

**Comment by stefjoosten** [comment]
Han, what is the underlying problem that we are trying to solve here?

**Comment by hanjoosten** [comment]
The idea was to sanitize the logical data model from whatever stuff that should not be in it. Exploring the LDM proves to be one of the ways to find minor issues with the current AST.adl. 
Currently, the model looks like this:

![logicaldatamodel](https://cloud.githubusercontent.com/assets/1159672/15798798/1879e1ac-2a46-11e6-9b93-b5021097d235.png)

**Comment by stefjoosten** [comment]
In doing this sanitation, I would like to understand why we do whatever we do to improve the LDM. That is because this type of Action has a High risk of symptom-chasing.

**Comment by hanjoosten** [comment]
Very true, but being aware of that, it still helps in reducing double relations/concepts from the model.

**Comment by hanjoosten** [comment]
![logicaldatamodel](https://user-images.githubusercontent.com/1159672/35174245-f4f0c0f4-fd6e-11e7-98f9-7e493d198632.png)
