### ISSUE TITLE
Implement check on Releasenotes.md

### ISSUE THREAD

**Issue by hanjoosten** [AmpersandTarski/Ampersand#425]
It would be nice to have an automatic check that the releasenotes.md has been modified, every time a branch is pulled into development. 

I asked for help at the guys of Github:

**Comment by hanjoosten** [comment]
Hi Han,

Yeah, I think you should be able to do that by following this approach:

1. Protect the development branch and add a required status check for it. That required status check will ensure that commits can be pushed to that branch only if some condition is satisfied. The condition that you want to test for in your case is "the releasenotes.md files was updated" (which is what you'll need to implement on your end, see the next steps). You can read more about protected branches and required status checks here:

https://help.github.com/articles/about-protected-branches

2. If you're using pull requests, then you can use this API to check the list of files modified by a pull request: https://developer.github.com/v3/pulls/#list-pull-requests-files. If you're not using pull requests, then you can use this API to get the list of files changed by a feature branch since it was started: https://developer.github.com/v3/repos/commits/#compare-two-commits. If you see the releasenotes.md file listed, then that file was modified.

3. If you're using pull requests, create a webhook which listens on pull_request events and notifies you any time pull requests are updated: http://developer.github.com/webhooks/. If you're not using pull requests, then you'll need to subscribe to the push event.

4. When you receive a webhook and you determine that you need to re-check a pull request or a branch -- you'd use the API to determine if the pull request/branch satisfy the condition (step 2), and then create a status for the latest commit in that pull request/branch: https://developer.github.com/v3/repos/statuses/#create-a-status. If the condition is satisfied, you'd create a "success" status for the required status check you defined (step 1) and that would allow the feature branch to be merged into development. If the condition is not satisfied, you'd create an "error" status.

Does that help?

Cheers,
Ivan

> As an admin of AmpersandTarski, I have been looking for info to solve the following problem:
>
> As workflow, we recently introduced [gitflow workflow](https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow). Now any development is required to be done using a feature branch, which can be pulled into the development branch.
> The author(s) of the feature branch should update a specific file: ReleaseNotes.md, to comment on the feature. I would like to have an automatic check to see if the ReleaseNotes.md file has changes since the beginning of the feature branch. This will prevent anybody to merge a feature branch without updating the release notes.
>
> Is there any guidence where I can read how to set this up?
>
> The repo this is intended for is https://github.com/AmpersandTarski/Ampersand/tree/development , which is also the default branch of https://github.com/AmpersandTarski/Ampersand
>
> Thanks a lot!
>
> Han Joosten

**Comment by hanjoosten** [comment]
@Michiel-s Does this help? I am not very familiar with api programming

**Comment by Michiel-s** [comment]
Now with Github actions this is easy. Take a look at: 
https://dangoslen.me/blog/enforcing-a-changelog-with-github-actions/ and the change log enforcer they created: https://github.com/dangoslen/changelog-enforcer/
