### ISSUE TITLE
SQL query performance improvement

### ISSUE THREAD

**Issue by Michiel-s** [AmpersandTarski/Ampersand#426]
I've identified a quick win for increasing performance.

Consider the following interface definition
```
INTERFACE Test : I[A]
```
This results in the following query: 
```select distinct "A" as src, "A" as tgt from "A" where "A" IS NOT NULL```

The backend framework creates a query around the query above to get a certain A:
```
SELECT DISTINCT * FROM (
    select distinct "A" as src, "A" as tgt from "A" where "A" IS NOT NULL
) AS results WHERE src = '<id of a certain A>' AND tgt IS NOT NULL
```
On my development machine, with a population of around 10.000 As, this query takes about 0,015 seconds. Not that much, but given our generic architecture, when we request an overview of all As using:
```
INTERFACE All : V[SESSION*A] BOX
  [ "A" : I ]
```
this takes up to 150 seconds. :-1: 

Among others, sub queries are bad for performance. Therefore I propose to get rid of the sub query that is introduced by the backend to get the right atom. What we need is that the prototype generator provides a placeholder for the source atom id in the query. At runtime the backend will replace this placeholder by the actual identifier. In order to enable this:

**The query must look like**:
```
select distinct "A" as src, "A" as tgt from "A" where "A" = '{SRC_PLACEHOLDER}' AND "A" IS NOT NULL
```
example with 10.000 Atoms, query time: 0,0010 sec (improvement by factor 10)

**instead of**
```
select distinct "A" as src, "A" as tgt from "A" where "A" IS NOT NULL
```
example with 10.000 Atoms, query time: 0,015 sec

For complex expressions, the generator nests a lot of queries. The solution described above is only needed for the outer-most query.

**Comment by hanjoosten** [comment]
Yes, we should enable less queries. See also issue #217. That issue could be addressed now, because the json stuff is in place. We could have a real good performance boost when that idea is implemented.

The benefit for this issue (issue #426) could be collected without modification of the haskell code: Currently, every query has the form : select <something> as src, <something> as tgt from <whatever>. So, the result is a table with two columns, called src and tgt. So to get what you want, you could say:

select * from <the entire query you currently get from the backend goes here> where src = {SRC_PLACEHOLDER}.

Nothing fancy. The DBMS will sort this out in an eyeblink. This will work, until we implement issue #217

**Comment by Michiel-s** [comment]
@hanjoosten what you describe as *solution* is actually how it is implemented currently as I described in my issue post.

You state that 
> the DBMS will sort this out in an eyeblink

but in fact this is a subquery that takes quite some time with large(r) population (factor 10, with pop of 10k). As I explained in my post.

The solution is to move this `src = src_placeholder` to the query generated by haskell and fill in the `src` part for the actually source columnname. We can't do this in the backend (without having to parse the query again). What we can do is at runtime fill in the src atom as the src_placeholder.

Please review my request again.

**Comment by hanjoosten** [comment]
I'll have a better look at it, although it is not a quick fix. Generating a query from a binary expression is done all over the place with a single function 8-)) Here, we only want to adapt it for interfaces. If a solution for #217 seems to be the same amount of work, then I think that would be a far better approach. I'll let you know.

**Comment by Michiel-s** [comment]
Ok. But keep in mind that issue #217 addresses another point. That issue proposes a solution to improve performance by having to execute less queries, because for certain sub**interfaces** the information can be retrieved from the parent ifc query. 
This issue (#426) however proposes a solution to improve performance by having less subqueries within a certain query.
Both are relevant and exists next to eachother.

**Comment by Michiel-s** [comment]
Nice first steps here @hanjoosten.

A couple of points for improvement I've identifiied:
- [ ] queries with singleton atoms look odd: `select distinct \"SESSION\" as src, \"SESSION\" as tgt from \"SESSION\" where \"SESSION\" = {SRC_PLACEHOLDER} AND \"SESSION\" = '_SESSION'` _SESSION is already replaced by the session atom. In this case it is ok. Because the session id will also be placed at the src placeholder
- [ ] queries covering 2 or more tables don't have this src placeholder yet, while they can have. e.g. `select distinct fst.\"SESSION\" as src, snd.\"FileObject\" as tgt from \"SESSION\" as fst, \"FileObject\" as snd where fst.\"SESSION\" IS NOT NULL AND snd.\"FileObject\" IS NOT NULL`
- [ ] now that we've moved this src atom thing to the generated query, the src IS NOT NULL part is not needed anymore, e.g. in: `select distinct \"Project\" as src, \"Project\" as tgt from \"Project\" where \"Project\" = {SRC_PLACEHOLDER} AND \"Project\" IS NOT NULL"`

**Comment by Michiel-s** [comment]
I've created a branch to work on this issue more.

Branch: less_queries

**Comment by hanjoosten** [comment]
In my opinion, the sole fact that some of the queries look odd, isn't enough motivation to interfere in the qeneric way the queries are generated. Only when there is a performance penalty, it is worthwile to interfere. That is why I do not like to do anything about the first and third bullit above. (So I stripped it in the text)

**Comment by Michiel-s** [comment]
> That is why I do not like to do anything about the first and third bullit above. (So I stripped it in the text)

ok

**Comment by hanjoosten** [comment]
Michiel, I fixed the queries covering 2 or more tables. Iff you are happy with this, we can merge to development and close this ticket.
