### ISSUE TITLE
MEANING and VIOLATION cannot be combined for same rule

### ISSUE THREAD

**Issue by EstherHageraats** [AmpersandTarski/Ampersand#428]
Ampersand v3.5.0 (28 april 2016) gives a parser error when MEANING and VIOLATION are both defined for a RULE. Problem is visible when trying to generate a proto of sets.adl (ampersand-models/sets, created Mar 8)

**Comment by hanjoosten** [comment]
Well is does work. However, the [syntax](https://ampersandtarski.gitbooks.io/documentation/content/syntax/rule.html) is picky. you have to comply to the order these keywords are in. 
Don't hesitate to reopen this issue if you don't agree.

**Comment by EstherHageraats** [comment]
Aha, I see, no argument from me:)

Esther
================
Esther Hageraats
Walkottelanden 87
7542 MT Enschede
053-4 768 554
06-136 289 34
