### ISSUE TITLE
Babel versioning problem

### ISSUE THREAD

**Issue by stefjoosten** [AmpersandTarski/Ampersand#429]
# Symptoms
When running an Ampersand script towards PDF-documentation, I get the following error message by LaTeX:

    ! Package babel Error: Language definition file shorthands=off.ldf not found

# Analysis
A little research on the internet points towards our use (in `outputTemplates/default.beamer`  and `outputTemplates/default.latex`) of:

    \usepackage[shorthands=off

On January 02, 2015 Halldor Bjornsson wrote that the `shorthands=off` option is new in babel 3.9.(Check it out on https://support.rstudio.com/hc/en-us/community/posts/202191778-Knit-PDF-failed-after-upgrade-due-to-latex-babel-3-9). My `.log0`-file shows that I'm using `Babel <v3.8m>`. I assume that when I upgrade to a newer Babel, my problem will be gone. (I haven't tried it yet)

# Problem
Apparently, our version management does not extend all the way to Babel. So I can solve my problem by upgrading Babel, but is there a generic way to do such things for all our users?

**Comment by hanjoosten** [comment]
No. We do not interfere at all with the TeX application of our users, let alone the versioning of packages of that applications. The only thing we can do is point them to the appropriate site.
