### ISSUE TITLE
Configure switches in yaml file

### ISSUE THREAD

**Issue by Michiel-s** [AmpersandTarski/Ampersand#438]
Currently for generating a prototype the content of the `include` folder is used.

This issue requests for a CLI switch to specify the include folder location. It should overwrite the default.

My suggestion: `--include="custom-include"

**Comment by Michiel-s** [comment]
The use case for this is that I want project specific include folders with e.g. different localsettings and css files. I thereby can reuse the ampersand scripts for multiple instances of the same application.

**Comment by Michiel-s** [comment]
Even better would be if I could specify the include folder in my scrip. But I think I'm asking too much then. This is somewhat related to #261 and #264 

The CLI swith would already be great

**Comment by hanjoosten** [comment]
A swich is pretty simple to implement. However, your usecase seems to call for something else: You suggest that there can be multiple 'instances' of an application. Then it seems fair to specify all things that makes it specific, in a single file (Think Yaml for key-value pair stuff). If we have an array of instance names, where each name points to all stuff required in the Yaml file, then a specific instance can be generated using a switch like: --instance="myInstance" 
The yaml file could contain not only the location of your include file, but also stuff for localsetting.php and so on.

**Comment by Michiel-s** [comment]
Even better!

Stuff I would like to be able to configure in that yaml file:
* verbose
* crud-defaults
* prototype output folder
* ... basically all current CLI switches

and new functionality:
* include folder path

We then can run `ampersand script.adl --config="projectx.yaml"`
the yaml file could look like:
```yaml
# configuration file
verbose : true
proto : C:\xampp\htdocs\app
crud-defaults : cRud
include : project-include
```

**Comment by Michiel-s** [comment]
Also:
- [ ] Remove environment variables

**Comment by hanjoosten** [comment]
I fixed this issue by 

- [x] Add switch `--config=myConfig.yaml`  (read a config file)
- [x] Add switch `--sampleConfigFile`       (creates a sample config file)
- [x] Add switch `--include=myIncludeDir` (uses myIncludeDir instead of the default "include" for the prototype
- [x] I did NOT remove the environment variables, because that could still be usefull, and it didn't cause extra complexity during the implementation of the above

**Comment by Michiel-s** [comment]
I'm having an issue using the config file. I can't get it working at all.
my config.yaml:
```yaml
config:
 - verbose
```

`ampersand file.adl --config=config.yaml` produces the following error:
```
Ampersand-v3.5.2 [development:b43e9c7], build time: 19-Jun-16 21:17:38 W. Europe Daylight Time
config file:config.yaml
.\config.yaml could not be parsed.
Aeson exception:
Error in $: expected [a], encountered Object
ampersand.exe: Please fix this first.
```
