### ISSUE TITLE
Change in ChapterNatLangReqs.hs

### ISSUE THREAD

**Issue by stefjoosten** [AmpersandTarski/ampersand#44]
In chapter 2 of the functional specification, Shared Language, I would like to omit the captions of agreements in case of relations with a purpose but without meaning (explanation).

At the same time, in chapter 3 of the functional specification (Diagnosis) I would like to signal relations without meaning.

**Comment by hanjoosten** [comment]
Omitting these, will result in broken links in chapter 4. I think this needs a good rethink.

**Comment by stefjoosten** [comment]
Indeed. The LaTeX symbolic labels and references  must be avoided along with them...

**Comment by hanjoosten** [comment]
Stef, I have restructured chapter 2 in a separate branch. Could you please confirm that chapter 2 looks fine to you? (other chapters will follow later)
