### ISSUE TITLE
Violations don't show until some editing on data has been done

### ISSUE THREAD

**Issue by EstherHageraats** [AmpersandTarski/Ampersand#440]
When the initial dataset has a violation of a process rule, the violation message does not show after reinstalling database. After adding or deleting data, the message shows. It seems evaluation or calculation of the message is not done directly at startup.

**Comment by Michiel-s** [comment]
Thx for reporting this issue. I'll look into it.

**Comment by hanjoosten** [comment]
This could be related with #423

**Comment by stefjoosten** [comment]
Yes, sounds like it. Have you verified that closing this issue actually solved your problem? If so, it must be a different issue or your issue has returned...

**Comment by EstherHageraats** [comment]
This one is solved in V3.6.0, violation messages appear right after reinstall database.
