### ISSUE TITLE
Old interface remains although code is changed and recompiled

### ISSUE THREAD

**Issue by EstherHageraats** [AmpersandTarski/Ampersand#442]
I have a internal server error when activating the interface.
To debug I deleted parts of the interface to see what part creates this error. 
I ran Ampersand -p filename, but the interface did not change.
I checked whether I had saved the changed code, yes I had.

I renamed the .adl file and then ran Ampersand -p newfilename and the prototype that is generated has the new (smaller) interface.

**Comment by EstherHageraats** [comment]
And somewhere in this process I also deleted all existing proto-folders to force a complete rebuild of the prototype. Still the old interface remains. 
I did not now how to delete a database from the sql-server, but I did reinstall the database every time.

**Comment by EstherHageraats** [comment]
Sorry...cash problem

**Comment by hanjoosten** [comment]
My rule of thumb when I regenerate a model: 
Always hit the F5 button to refresh the screen. 
Whenever the structure/contents of the relations/rules have changed, also reinstall the database. (there is no need to reinstall the database if only interfaces have changed.)

**Comment by EstherHageraats** [comment]
You're right.
In this case F5 didn't do the trick, but deleting history (clear browsing data) was needed. 
Windows10 or Chrome-thing I don't know. But now I know what to do it if mysterious things happen;)
