### ISSUE TITLE
Angular mapping error in Internet Explorer

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/Ampersand#445]
When I run my (UETP) prototype locally, it works fine with FireFox and Chrome.
However, when I try to use Internet Explorer, nothing is shown on the screen.
The debugger says this:

`Could not locate http://ampersand/UETP/app/lib/angular/angular.js specified in source map http://ampersand/UETP/app/lib/angular/angular.min.js.map.`

**Comment by Michiel-s** [comment]
I'll remove the .map files for now.

We're planning to change the way the frontend application is built/distributed in the near future.
