### ISSUE TITLE
SQL queries: replace , (comma) syntax for joining tables by explicit INNER JOIN

### ISSUE THREAD

**Issue by Michiel-s** [AmpersandTarski/Ampersand#450]
Currently the comma syntax is used in sql queries to join two tables. E.g.
```sql
SELECT DISTINCT fence0.src AS src, fence1.tgt AS tgt 
    FROM (
        	SELECT DISTINCT "A" AS src, "B" AS tgt 
        	FROM "r" WHERE ("A" IS NOT NULL) AND ("B" IS NOT NULL)
    	) AS fence0
    	, <-- here it is
    		SELECT DISTINCT "C" AS src, "D" AS tgt 
    		FROM "s" WHERE ("C" IS NOT NULL) AND ("D" IS NOT NULL)
    	) AS fence1 
	WHERE (fence0.tgt = fence1.src)
    ) AS t1 
```

>From http://dev.mysql.com/doc/refman/5.7/en/join.html
INNER JOIN and , (comma) are semantically equivalent in the absence of a join condition: both produce a Cartesian product between the specified tables (that is, each and every row in the first table is joined to each and every row in the second table).

This issue request to replace this comma notation by explicitly specifying the INNER JOIN and use corresponding ON clause (instead of WHERE)

**Comment by hanjoosten** [comment]
I do not see the need to do so. This code copes not only with the case of two tables, but generally with N tables, with N >= 2. I think that using JOINs will not improve the performance, but it will be a disadvantage in the maintainability of the SQL generator. 
Hence, I close the ticket. Please reopen if you have other insights.
