### ISSUE TITLE
Interface-bar makes part of the screen invisible

### ISSUE THREAD

**Issue by stefjoosten** [AmpersandTarski/Ampersand#451]
When I have more interfaces in the interface-bar than will fit on one line (see figure), then part of the remaining screen will be covered with the surplus.

This will hurt novices, who may not understand why part of their screen is missing.
![image](https://cloud.githubusercontent.com/assets/275768/15811793/6b5caf7c-2bad-11e6-972f-458c775823d0.png)

**Comment by hanjoosten** [comment]
This is the same issue as #103
