### ISSUE TITLE
Uniform uppercase use of SQL keywords

### ISSUE THREAD

**Issue by Michiel-s** [AmpersandTarski/Ampersand#453]
SQL queries generated by Ampersand are inconsistent in using upper casing for keywords.

Some keywords (like AND, OR, ON, IS NOT NULL) are written in uppercase letters. Other not (like select, distinct, from, as, where).

This ticket request to uniform this and use uppercase letters for keywords.

**Comment by hanjoosten** [comment]
Because of the library we use, most keywords are printed in lowercase. This could only be modified by using another library or changing the library itself. Therfor, uppercase is not realistic. 
Lowercase could be done for the keywords that are written as such.

**Comment by Michiel-s** [comment]
Ah. Didn't know we used a lib for that. Never mind then.

**Comment by hanjoosten** [comment]
We use a lib for most 'difficult' things 8-))
