### ISSUE TITLE
I think this is a bug.

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/Ampersand#455]
Consider the following script:
~~~
CONTEXT Bug455 IN ENGLISH

REPRESENT ModuleVsnMajor TYPE INTEGER
moduleVsnMajor :: Module * ModuleVsnMajor [UNI,TOT] -- The major version indicator of the module
POPULATION moduleVsnMajor CONTAINS [ ("SIAM", 2) ]   

RULE "This file expects to load SIAM version 9.x": 'SIAM';V[Module*ModuleVsnMajor];'9' |- moduleVsnMajor
RULE "This file is expected to load SIAM version 9.x": 'SIAM';moduleVsnMajor |- moduleVsnMajor;'9'

ENDCONTEXT
~~~
In my perception, both rules should agree on what is, and what is not a violation, which they do not (and that is why I consider this a bug). Personally, I agree with the second rule.

**Comment by hanjoosten** [comment]
Both rules cannot be violated at the same time:

If 9 is an atom of ModuleVsnMajor, 
then the second rule cannot be violated.
else the first rule cannot be violated

**Comment by hanjoosten** [comment]
no bug.
