### ISSUE TITLE
Nonexistent CONTEXT error while it is declared

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/ampersand#46]
Consider the following script:

    CONTEXT "One" IN ENGLISH
    INCLUDE "Two.adl"
    ENDCONTEXT

Assume the file `Two.adl` contains the following script:

    CONTEXT "Two" IN ENGLISH
    PURPOSE CONTEXT "Two" {+This context exists to show a bug-}
    ENDCONTEXT

Compiling the first script results in the message:

    Error(s) found:
    Purpose refers to non-existent CONTEXT "Two"

This error is wrong, since `CONTEXT "Two"` is actually declared. If the parser is capable of ignoring a `CONTEXT` statement, it should also be capable of ignoring any other statements related to that context.

**Comment by hanjoosten** [comment]
The parser will currently only look at the contextname of the 'upper' file. The rest of the context names are ignored. Currently, we still have no sound theory on how to cope with multiple contexts. 
This means that the parser will only give a single context to the typechecker. The purpose statement pointing to a contextname that 'fizzled', now points to an non-existing context. 

There are multiple 'solutions':
1) wait until we have a mature understanding of how to cope with multiple contexts. 
2) disable the check for the existence of the context mentioned in a PURPOSE statement

**Comment by stefjoosten** [comment]
I suggest we wait until we pick up on working with multiple contexts.

**Comment by RieksJ** [comment]
Let’s do the latter so as to not inhibit ongoing work.

**Comment by RieksJ** [comment]
If you wait for working with multiple context, I suggest to be congruent and not require the context statement at the top of the files.

**Comment by hanjoosten** [comment]
Hey guys, 

Please do not respond by email, unless you discard all text from previous mails. Otherwise, the discussion at Github will get very combersome to read.
