### ISSUE TITLE
wiki.tarski.nl status query, and bad links in User hub

### ISSUE THREAD

**Issue by WolframKahl** [AmpersandTarski/Ampersand#462]
I ventured on http://wiki.tarski.nl/index.php/User_hub , and there, the road map link goes to a sourceforge download page, and the issues link also goes to sourceforge.

Since the documentation repository appears to have no issues functionality I filed this here.

Is http://wiki.tarski.nl/ still the right place to point people to for introducing them to Ampersand?

**Comment by hanjoosten** [comment]
Thanks for pointing this out. We defenitly are in need of a landing page. We have issue #403 allready for that, but it hasn't have mutch attention lately.

**Comment by Michiel-s** [comment]
Old wiki is offline. We have [landing page](http://ampersandtarski.github.io/) now.

**Comment by WolframKahl** [comment]
http://ampersandtarski.github.io/ still contains a link to the old wiki at the bottom.

(And I would consider some explanation of what Ampersand is as more important on that page than “Recent activity”.)

**Comment by WolframKahl** [comment]
I just came across http://hackage.haskell.org/package/ampersand : There are a few more outdated links there...
