### ISSUE TITLE
<stdin>: hGetBufSome: resource exhausted (Not enough space)

### ISSUE THREAD

**Issue by stefjoosten** [AmpersandTarski/Ampersand#463]
In branch `Archimate_extension`, the Ampersand compiler of commit 30328007986b36691ac029ef3550f5d18a975a90 translates `ampersand-models/Arch.adl` from commit 133c15caa7660a93bc99c150ecf741bbc810dc9d into a failing program. On my Windows 7 laptop it crashes immediately with the following error message:
```
D:\git\ampersand-models\Blik>Ampersand -pD:\htdocs\klad Arch.adl
Ampersand: <stdin>: hGetBufSome: resource exhausted (Not enough space)
```
The compiler from the commit just before that, 8776d8279460b8c60f0ecd62c43c3cc578f9e2a8, compiles the same script smoothly. That puts the blame unmistakably on commit 30328007986b36691ac029ef3550f5d18a975a90 . Even better, this commit has only three hunks, two of which are comments. The remaining hunk should therefore be to blame. However, I remain clueless as to what might cause this error.

Some internet research shows that this error message is around since 2012. It does not occur frequently. @jgm reported [this issue](https://github.com/jgm/pandoc/issues/874) in the Pandoc Github on 5 Jun 2013. A [ticket](https://ghc.haskell.org/trac/ghc/ticket/11009) for Haskell has been made on the ghc-trac system already. @dulguun0225 and @ncreep address [the same issue](https://github.com/haskell/bytestring/issues/35) on the ByteString-Github.

There seems to be consensus that this error is associated with Windows. Some relate it to Lazy ByteStrings, but all we have as evidence are examples of programs that fail. That includes this report of mine. I did not find anything that even comes close to a plausible diagnosis. Without such an analysis, we might all be looking in the wrong direction. I hope this issue may contribute....

**Comment by hanjoosten** [comment]
@Stefjoosten, the links you have added, are broken links.

**Comment by stefjoosten** [comment]
I am closing this issue because:
 - it does not seem to contribute to diagnosing the phenomenon of this bug;
 - I have made an import of the Archi-repository by means of `INCLUDE` in the file `parsing.hs`. This effectively circumvents the problem.
