### ISSUE TITLE
Default configuration file 

### ISSUE THREAD

**Issue by hanjoosten** [AmpersandTarski/Ampersand#468]
When we call ampersand.exe, with a file `foo.adl`, it would be nice if the switches that are being used come from a default yaml file. When the file `foo.yaml` exists, (name of the file is equal to the name of the .adl file), and no explicit config file is specified using the `--config=` switch, then `foo.yaml` is taken as the configuration file.

**Comment by Michiel-s** [comment]
Nice one!
