### ISSUE TITLE
switch --meta-table

### ISSUE THREAD

**Issue by Michiel-s** [AmpersandTarski/Ampersand#472]
In the `--help --verbose` usage info the switch --meta-table**s** is mentioned. This however is implemented without the **s** `--meta-table`

**Comment by hanjoosten** [comment]
Ha! Funny. The package we use for handling the switches, seems to have new(?) functionality: For switches you can skip the last characters, as long as it is not ambiguous. If you omit more characters, you get an error message:

```
ampersand: option `--m' is ambiguous; could be one of:
    --meta-tables  When set, generate the meta-tables of AST into the prototype
    --meta-file    Generate the meta-population in AST format and output it to an .adl file
```
I think that this is quite neat. No bug.
