### ISSUE TITLE
Disambiguation required because of meta-ampersand

### ISSUE THREAD

**Issue by hanjoosten** [AmpersandTarski/Ampersand#474]
When we introduce meta-information of the model, the user can be confronted with the need to explicitly specify the signature of a relation she uses. This happens frequently in existing models:

For instance, in our testfile try12.adl, we now get the following error:

```
Error at symbol () in file try12.adl at line 5 : 6
        Cannot disambiguate the relation: r
        Please add a signature (e.g. [A*B]) to the relation.
        Relations you may have intended:
        r[A*B]
        r[Pair*Atom]
```

This is due to the fact, that a relation with the name `r` exists in FormalAmpersand.adl (or below, due to INCLUDEs)
## Considerations
- The meta information is ment to enable the user to reason about his/her own rules/ relations, etc, This has as a consequence, that the relations must be available from within the user's model. Hence, if a relation exists in the meta-model of Ampersand, then it will exist in the user's model too. Therefore, disambiguation has to be done explicitly.
- Disambiguation of relations that the _normal_ user is unaware of, isn't very user friendly.
- ...

**Comment by Michiel-s** [comment]
Yet another reason to introduce namespaces #850. When formal ampersand models and other added models like the prototype context are in their own namespace, they won't interfere with userland models.

**Comment by Michiel-s** [comment]
Let's pick this one up at #850
