### ISSUE TITLE
Screen updating falls short after inserting a new atom.

### ISSUE THREAD

**Issue by stefjoosten** [AmpersandTarski/Ampersand#476]
# Symptoms

Suppose I have an interface that shows all atoms of concept `G`. If I insert a new `G` by creating a new pair in a relation, I would expect the screen to display that new atom too. However, I need to do a refresh (F5) to get it done.

Here is the example:

```
CONTEXT SpecializeTest IN ENGLISH

CLASSIFY A ISA G
CLASSIFY B ISA G

RELATION r[G*G]
RELATION s[A*B]
RELATION name[G*Text] [UNI]

RULE PeterRule : r;(I/\name;'Peter';name~) |- s
VIOLATION (TXT "{EX} InsPair;s;A;", SRC I[G], TXT ";B;", TGT I[G])
ROLE ExecEngine MAINTAINS PeterRule

RULE verify : s |- r;(I/\name;'Peter';name~)

POPULATION name CONTAINS
  [ ("0", "Jack")
  ; ("1", "Peter")
  ]

POPULATION r CONTAINS
  [ ("0", "0")
  ; ("1", "1")
  ]

INTERFACE Gs : V[SESSION*G]
BOX [ name : name
    , r : r
    , s : s
    ]

ENDCONTEXT
```

Here is the experiment:
1. compile and run the script. Then inspect and verify the population through interface `Gs`.
2. Now try to insert the pair `(1,3)` into `r` by typing 3 into the `r`-field of atom 1.
![image](https://cloud.githubusercontent.com/assets/275768/16538855/d6577ba8-4030-11e6-93d4-6a5a462b1908.png)
1. Click on the insert icon (the green `+`) and observe that it works.
   ![image](https://cloud.githubusercontent.com/assets/275768/16538890/a155fdac-4031-11e6-9614-72e1877b48ef.png)
2. On closer inspection, you can see that the box that contains atom 3 is missing. Never mind. F5 helps out.
# Problem

After inserting atom `3` and observing the system responds in green-yes-it-works-cheerio, I would expect that the screen would also show a box containing `3`. The current result will be confusing for novices, who do not (yet) have the reflex to press F5 in such situations.
# Reproduce the experiment:

I have compiled with `Ampersand-v3.5.2 [Archimate_extension:9d3e117*], build time: 29-Jun-16 14:21:52`

**Comment by stefjoosten** [comment]
I have noticed that this occurs frequently. Another example: If i login using SIAM, roles will be allocated automatically to my session. For this reason, I get a different menu-bar content. However, I need to press F5 after logging in to see that.

**Comment by RieksJ** [comment]
Refreshment issues keep popping up. Currently, the implementation has some optimizations that cause only parts of the screen to be updated. We may want to think about what we want and compare that with the (implementation-dependent) possibilities, which @Michiel-s could explain...

**Comment by stefjoosten** [comment]
@Michiel-s This is the F5-issue. I have just checked that it has not been resolved yet.

**Comment by stefjoosten** [comment]
I have tested this issue on Ampersand-v3.7.1 [Archimate_extension bb669707a3c9b9059a65ddb775fa62334dc2b818], after a preliminary fix of @Michiel-s of the F5-bug. This particular instance of the F5-bug has not disappeared yet, so this issue remains open.
