### ISSUE TITLE
Feature request: Linking to specified INTERFACEs

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/ampersand#48]
Currently, when a (line in) an INTERFACE refers to an atom for the concept of which multiple INTERFACEs have been defined, some kind of selection must take place. Currently, this selection is made runtime, with (or without) user intervention. 
I would like to have a means of selecting an INTERFACE define time, in a similar fashion as <views> are selected define time, and for similar purposes. 
I suggest the following syntax:

    INTERFACE ifcid ...
    ...
    label : expression LINKTO INTERFACE interfacename
   ...

The `LINKTO` keyword would prohibit the runtime expansion of the INTERFACE, but instead call this INTERFACE whenever a user clicks on a (target) atom of `expression`.

**Comment by hanjoosten** [comment]
@Michiel-s , this should do the job at Haskell side. Introduced the keyword "LINKTO"
