### ISSUE TITLE
Front-end work for RAP3

### ISSUE THREAD

**Issue by stefjoosten** [AmpersandTarski/Ampersand#481]
As a student, I want to use RAP3 intuitively, without getting stuck in little things that I might not understand immediately. This task is more of an epic than a single backlog-item.

This issue is about removing UX-obstacles that affect the introduction of RAP3 in the OBR-course at the Open University. This issue deals with one aspect from issue #449. Items in this list are checked if the item is resolved in the RAP3 branch of the ampersand-models repository.
- [ ] When logging in, the student must click twice in the password field before typing the password. This might correspond to issue #476.
- [ ] The refresh-button (F5) needs to be pushed quite frequently. This should not have to be necessary at all, because a novice won't understand this. This corresponds to issue #476.
- [ ] The account management must be made usable for the role `AccountMgr`.
- [x] Disable the login-help functionality in the production version.
- [x] The Ampersand-role must not be allocated to a student.
- [ ] It must be made obligatory to fill in the "opdracht" field when making a new script
- [x] Error reporting must be made readable
- [x] transaction functionality must be made to work (reference to other issue(s))
- [x] If a diagnosis/func-spec/prototype exists, don't recompile
- [ ] fix the text of the functional specification. (Check all, fix the data structure)
- [ ] Error: A Slim-error occurs if I try to compile an empty script.
- [ ] Upon pressing the `SAVE` button, I would like the CompileToNewVersion function to be called automatically, without clicking on the compileren-checkbox.
- [ ] Error: After logging out and then logging in under a different user, the name of the previous user hangs around as though it were my name.

**Comment by hanjoosten** [comment]
@Michiel-s Have a look at [Ace](https://ace.c9.io/#nav=about). Would it be possible to incorporate this into a template for editing a user script?

**Comment by Michiel-s** [comment]
No problem. What we need is an Angular wrapper for Ace or create one of our own.

**Comment by Michiel-s** [comment]
E.g.: https://github.com/angular-ui/ui-ace

**Comment by Michiel-s** [comment]
@hanjoosten and @stefjoosten is this issue still up-to-date? Or can it be closed or moved to RAP repository?

**Comment by hanjoosten** [comment]
@stefjoosten , This issue is pretty outdated. I suggest that when needed, create a new version of it in the RAP repo.
