### ISSUE TITLE
Ampersand exit codes (errorlevels)

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/Ampersand#483]
#In order to run Ampersand in batchfiles (command scripts), as well as for use in RAP3, it is nice to be able to have Ampersand produce exit codes (errorlevels). The specification of such exit codes is as follows (an entry is ticked when the exit code is implemented/supported according to spec):

- [x] 0: Ampersand terminated succesfully.
- [x] 1: Ampersand terminated unsuccesfully - the cause is another one as that mentioned for higher exit codes.
- [x] higher exit codes. These can now be looked up in the file [Exit.hs](https://github.com/AmpersandTarski/Ampersand/blob/development/src/Ampersand/Basics/Exit.hs)

The above list is intended to be extended by those that are in need of specific other exit codes.

**Comment by hanjoosten** [comment]
I have introduced the file [Exit.hs](https://github.com/AmpersandTarski/Ampersand/blob/development/src/Ampersand/Basics/String.hs), that can be used to look up information about exit codes.
