### ISSUE TITLE
Ampersand does stuff

### ISSUE THREAD

**Issue by sjcjoosten** [AmpersandTarski/Ampersand#484]
in the Archimate_extension branch, when I run `ampersand tryArch.adl`, ampersand writes the file `ArchiMetaModel.adl`. This was kind of unexpected, as I did not provide any switches. The expected behavior is that ampersand will run some checks (at least the type-checker checks) and then exit (possibly with errors). Can we put this file output behind a switch again?

**Comment by stefjoosten** [comment]
will do, once this thing gets some status. For now, I have just put it in to check. It may even be removed entirely before I merge this branche into something else.

**Comment by Michiel-s** [comment]
Stale issue
