### ISSUE TITLE
Improve performance by using  `Text` instead of `String`

### ISSUE THREAD

**Issue by stefjoosten** [AmpersandTarski/Ampersand#485]
We are having performance problems, as our populations get bigger by the day. See for example issue #479.

The next performance improvement can be obtained by using `Text` instead of `String`.
`fillSignalTable` in `Prototype/Generate.hs` is a good place to start.

**Comment by hanjoosten** [comment]
Using Text instead of String is allready done at a lot of places. There is no evidence that replacing String by Text will improve the performance much more.
