### ISSUE TITLE
DB performance: indexing

### ISSUE THREAD

**Issue by Michiel-s** [AmpersandTarski/Ampersand#488]
In order to increase the database performance, commit e715f52ca4e3527c5b2e92d8e43255cd15fb8bac introduced indexes on table columns where possible. 

We argued that the performance improvements of indexes for Ampersand generally outweigh the costs for updating the index on inserts, updates and deletes. Therefore this feature is enabled by default. You can manually remove indexes when necessary.

TODO:
- [x] For n-n tables, the index is still missing on the first column.
- [x] For single column concept tables there is no primary key defined. Adding the PK will guarantee that there are no duplicates in the table.
- [x] For n-n tables we can also defined a primary key statement on the combination of both columns. This will guarantee that there are no duplicates in the table.

**Comment by Michiel-s** [comment]
Minor fix: a1d7f67f76021b418b3266607859534f9c84f733

**Comment by Michiel-s** [comment]
I've updated the initial post and added two todo's

**Comment by hanjoosten** [comment]
@stefjoosten found a bug as a result of putting a primary key on the n-n table: In case that one of the columns has a technical type that is not suitable as primary key, there must not be a primary key defined on that table.
