### ISSUE TITLE
Bug in normalizer causes a loop

### ISSUE THREAD

**Issue by hanjoosten** [AmpersandTarski/Ampersand#50]
The reason that DEMO_VOG.adl is taking too long is very likely that there is a loop somewere. I have seen that makeFSpec uses recursion in the definition of the fSpec. I see no reason why that is required, and it is a suspect of the loop(s).

**Comment by Oblosys** [comment]
Removing the cycles from makeFSpec is a good idea, but it is not what's causing the VOG problem. That one is caused  by a normalizer bug:

https://sourceforge.net/p/ampersand/tickets/451/

**Comment by hanjoosten** [comment]
I'll remove the cycles from makeFSpec, Stef might have a look at the normalizer bug

**Comment by hanjoosten** [comment]
Changed the title of the issue to a better one for this problem. Btw, @stefjoosten , the text file that Martijn mentions ( https://sourceforge.net/p/ampersand/tickets/451/attachment/conj_1%20violationExpr.txt )  in this ticket, wiil probably help you see what is going on pretty fast.

**Comment by Michiel-s** [comment]
@stefjoosten any updates on this ticket?

**Comment by stefjoosten** [comment]
No updates yet. I'm not getting any time to look into it. Just leave it open until I do

**Comment by hanjoosten** [comment]
The loop has gone since quite a while. No reason to leave this ticket open.
