### ISSUE TITLE
Toolbar dissapears when screen is not broad enough

### ISSUE THREAD

**Issue by hanjoosten** [AmpersandTarski/Ampersand#510]
On the upper richt of a prototype screen, we normally have the toolbar:

![image](https://cloud.githubusercontent.com/assets/1159672/17888441/394e9b10-692b-11e6-9afe-4d9a22e3d7be.png)

However, if we make the screen less broad, the toolbar disappers, without anything else to replace it:

![image](https://cloud.githubusercontent.com/assets/1159672/17888506/93256f88-692b-11e6-8e45-8ab1117cda5f.png)

I would like the functionality of the toolbar available on small screens too.

**Comment by Michiel-s** [comment]
This is intended behavior. Tipping point is 768px (Bootstrap: extra small devices/Phones).

The idea is that when you access a prototype on a small device, you have a different task than on a large screen. Now there is more space for the toplevel interface items.

The only option that stays visible if the Role selector (if applicable).
Things that are **not** visible:
- Notification settings
- Refresh options
- Extension menu (contains e.g. excel importer)
- Create new (+) menu

Please provide a small screen use case before reopening this issue
