### ISSUE TITLE
Subtypes do not show in Interface

### ISSUE THREAD

**Issue by hanjoosten** [AmpersandTarski/Ampersand#511]
Consider the following script:

```
CONTEXT Persons IN ENGLISH
  CLASSIFY Woman ISA Person
  CLASSIFY Man   ISA Person
  RELATION name[Person*Name] [UNI,TOT] 
    = [("p1","Pascal") , ("p2","Maxima") , ("p3","Willem")]
  RELATION husband[Woman*Man][UNI,INJ] = [("p2","p3")]
  REPRESENT Name TYPE ALPHANUMERIC
  VIEW Person : Person(name)
INTERFACE Persons : '_SESSION';V[SESSION*Person]
  BOX <SHCOLS> [ "Person" : I[Person] ,
                 "Name" : name
               ,  "husband's name:" : husband ;name
               , "Woman" : I[Woman]
               ]
ENDCONTEXT
```

When we run this script, a prototype shows, containing errors:

![image](https://cloud.githubusercontent.com/assets/1159672/17922419/2bd3819e-69df-11e6-816b-5e9127fb677f.png)

The error messages should not be shown, and the right values should be present.

**Comment by hanjoosten** [comment]
#Diagnosis 

The database contains the right values:

![image](https://cloud.githubusercontent.com/assets/1159672/17922492/9b22d216-69df-11e6-895e-ca63811b7c30.png)

For some reason, the subtypes aren't shown correctly.

**Comment by Michiel-s** [comment]
Rebuild your script with Ampersand-v3.8.8 and no errors occur anymore. Not sure what caused the issue and/or in which commit this is fixed. But anyway, issue can be closed I think
