### ISSUE TITLE
Specify a (set of) INTERFACE(s) for resolving violations by users

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/Ampersand#514]
When you have a script such as

```
ROLE User MAINTAINS "some rule"
RULE "some rule": rule-expression
VIOLATION (violation-text)
```

and at runtime a violation of `some rule` occurs, every violation can be displayed. Clicking on a specific violation shows the set of all interfaces that are available for doing something with the SRC of the violation. In the presence of many INTERFACEs, this is not user-friendly.

I propose that the syntax of the `ROLE` statement be enhanced, such that we can specify the INTERFACE(s) that the specified role(s) are supposed to use as they attempt to fix the specific violation, e.g. as follows:
`ROLE <rolenames> MAINTAINS "some rule" USING INTERFACE "interfacename"`

**Comment by stefjoosten** [comment]
We kunnen dit doen als een inperking.

**Comment by hanjoosten** [comment]
Let's see how this would look in formalampersand first. Then building it would be easier.
