### ISSUE TITLE
REPRESENT ALPHANUMERIC renders strings with (too?) many decimal digits as E-numbers

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/Ampersand#516]
In the first row of the figure below, the `ActCode` field, which is defined as a REPRESENT ALPHANUMERIC, is supposed to contain the string `1234567890`, which is what I specified in the xlsx file that was used to populate this stuff. In the excel file, the cell format was explicitly set to 'text'. However, the atom is rendered as if it were a floating point integer `1.23456789e9`, which is not what I would expect. 

<img width="800" alt="picture1" src="https://cloud.githubusercontent.com/assets/8522589/18170150/8830db56-705d-11e6-9526-a2516914e9d5.png">

**Comment by hanjoosten** [comment]
First of all, I assume this is about the runtime excel importer (excel -> frontend), not the designtime excell importer (with INCLUDE statement). These two importers are totally different. (the INCLUDE importer doesn't have this 'feature'. That works just fine. (also see issue #317 )

In your excell, the contents of the cell is probably numeric, regardless of the cell format you specify. The cell format in excell only tells how the value has to be presented in excell itself. 
If you want the value itself to be text, not numeric, then in excell you have to start it with a '-symbol.  In any case don't get confused by looking at the cell-format of excell. It is misleading for this purpose!

**Comment by RieksJ** [comment]
Thanks. That solved it.
