### ISSUE TITLE
Weird code (Bug?) in gen_concs

### ISSUE THREAD

**Issue by stefjoosten** [AmpersandTarski/Ampersand#520]
Something strang in [ParseTree.hs](https://github.com/AmpersandTarski/Ampersand/blob/development/src/Ampersand/Core/ParseTree.hs) in the definition of `gen_concs`. The code on commit 73cae8bf38ed8c8bf1ae1d0448cb5edbbab76844 shows:
~~~~
gen_concs :: P_Gen -> [P_Concept]
gen_concs (P_Cy {gen_rhs=x}) = x
gen_concs (PGen {gen_gen=x,gen_spc=y}) = [x,y]
~~~~
I would expect the second line to be:
~~~~
gen_concs (P_Cy {gen_rhs=x,gen_spc=y}) = y:x
~~~~
However, this change produces [mistakes](https://travis-ci.org/AmpersandTarski/Ampersand/builds/157461676) that weren't there before. What is going on here?

**Comment by stefjoosten** [comment]
@hanjoosten has just explained why. `gen_concs` is being used in one place only, Its name is ill chosen, which has caused confusion. Han is fixing this as we speak, so we will close this case.

**Comment by hanjoosten** [comment]
This is a double of issue #519
