### ISSUE TITLE
nieuwe switch nodig voor Rap3

### ISSUE THREAD

**Issue by stefjoosten** [AmpersandTarski/Ampersand#521]
Voor de RAP 3 applicatie hebben we een switch nodig waarmee niet het volledige prototype, maar enkel het **prototype/generics/mysql-installer.php** bestandje wordt gegenereerd.

Dit raakt aan de functionaliteit van de oude(re) --no-static-files switch. Deze werkt echter niet meer na de introductie van de nieuwe frontend generator, welke afhankelijk is van de static files.

**Comment by Michiel-s** [comment]
Zie ook #522
