### ISSUE TITLE
Change of mysql-installer.json

### ISSUE THREAD

**Issue by Michiel-s** [AmpersandTarski/Ampersand#522]
Request to adapt the  mysql-installer.json output:

Currently, we get 2 arrays:
- allDBstructQueries (for queries that define both application tables and meta tables)
- allDefPopQueries (for population of application tables and meta tables)

This must be split into:
- appTableStructure
- appTablePopulation
- metaTableStructure
- metaTablePopulation

This allows us to load metamodel populations separately, which is necessary for loading student scripts into RAP3.

**Comment by hanjoosten** [comment]
In RAP3, for the time being, we want to start with students being able to load and view their population. Maybe edit stuff.
The idea is that the initially, the database is constructed like normal. AST.adl is the model where the prototype is being generated from. 
Initially, there is only the initial population that comes from AST.adl. 

Now in the running prototype, a student uploads a script, and compiles it. In the initial version of RAP3, we will not add any table in the database. We only add some population to the exsisting database. This influences the naming of the files above. 
My suggestion is to leave the current files as is. When the new switch (see #521) is used, only a single JSON file is created, containing new population, which can be injected into the existing prototype. It is comparible with uploading an Excell file during runtime.

**Comment by hanjoosten** [comment]
I implemented the Haskell part. When the switch `--gen-as-rap-model` is enabeld, a file named `extraPopulation.json` is written into the prototype environment. To know about the place where it should be generated, also the --proto must be enabled.

**Comment by hanjoosten** [comment]
@Michiel-s , could you do the pipefitting work in the frontend? Dont't hesitate to contact me when you have questions!

**Comment by Michiel-s** [comment]
I'm not yet really happy with the solution as only part of my initial request is now implemented for RAP3. It works for now, but I would prefer a more generic and reusable solution for other applications as wel. Let's discuss this during our sprint meeting?
