### ISSUE TITLE
Alternative for conjuncts

### ISSUE THREAD

**Issue by sjcjoosten** [AmpersandTarski/Ampersand#525]
Checking all the conjuncts for each transaction is currently a major performance bottleneck. I suggest we use a more fine-grained approach, which uses the changes as part of the rule-check.

For each interface, there should be a separate "how to insert" function. I'll start with an example (adapted from `ShouldSucceed/Ticket440.adl`):

```
heeftVoldaanAan   :: Afdeling * Norm
isDeelnormVan :: Norm * Norm [ASY,IRF]
RULE "Voldoen aan normen [2]": -(-heeftVoldaanAan;isDeelnormVan)  |- heeftVoldaanAan

INTERFACE "TEST" (isDeelnormVan) : I[Norm]
BOX[ "Norm" : I
      , "Is deelnorm van" : isDeelnormVan
      , "Heeft deelnormen" : isDeelnormVan~
      ]
```

Note that there are three rules here, I'll call them ASY_isDeelnormVan, IRF_isDeelnormVan and VOLDOEN, respectively. Given a list of changes, we only need to check that:
- none of the added pairs into "isDeelnormVan" (pairs labeled add or replace) violates IRF_isDeelnormVan. This can be computed without a call to SQL.
- None of the added pairs into "isDeelnormVan" is in "isDeelnormVan~". This can be a very efficient SQL query `SELECT * FROM isDeelnormVan WHERE NormSource IN (....) AND NormTarget = '".$sourceID."'`. This checks half of the rule ASY_isDeelnormVan.
- None of the added pairs into "isDeelnormVan~" is in "isDeelnormVan". This can be checked along the same lines, completing the check of ASY_isDeelnormVan.
- Any deletion (through a delete, remove or replace) of a pair. in "isDeelnormVan" should not violate VOLDOEN. This is somewhat more complicated, and in the worst case we will need to fall back on the old behavior: doing the update and checking the conjunct. We could decide to use that "isDeelnormVan" is ASY and IRF, since that is already checked.

This ticket is to fix an intermediate data-structure to be put in a file that will replace `conjuncts.json`, which can encode all of the above tasks. After execution, the result may be a set of violations, in which case a ROLLBACK is performed. If not, all the new data should be present in the database and a COMMIT is performed. I will refer to the file as `transactions.json`, and it should contain one item per interface. Based on the above the data-structure should be able to:
- Sequence tasks, when the first task generates an error, the second task is not run.
- Run tasks in parallel; they may of course be run after one another, but the idea is to collect all errors, rather than quitting when one is found.
- Perform SQL calls linked to some RULE, which should return no values (if they do, it is an error).
- Perform simple checks without SQL calls. This is especially important to prevent things like `INSERT (0,'hello') (0,'world') INTO someUnivalentRelation`, which is an error (relation not UNI) but cannot be caught through SQL.
- Update, Insert and Delete tuples into the database. The generated .json should make sure this is done in such a way that the database's cardinality constraints are never violated.

Needless to say, the data-structures of the SQL call and of the non-SQL tests should be able to refer to the changes sent to the server, so some form of variable mechanism should be in place.

To make this work, I suggest first making the old conjunct-test behavior work from both the PHP and the json-generation side. As a next step, we can optimise the generated json.

**Comment by hanjoosten** [comment]
If you look at the logs, I don't see too much of a bottleneck in maintaining the conjuncts. Are we sure we are adressing a real problem? (of course, it is always good to think about alternatives)

**Comment by Michiel-s** [comment]
I agree with @hanjoosten , that's why I would like to discuss this issue during our sprint meeting. Maybe I don't oversee the whole picture.

Currently, conjuncts are only evaluated when they may be affected. This already reduced the amount of conjuncts to check significantly.

Furthermore, keep in mind that the exec engine performs actions outside the boundaries of the interface. Before we can even further reduce the amount of checks, we also need to  merge the INTERFACE and VIOLATION (used by exec engine) stuff.

**Comment by Michiel-s** [comment]
Stale issue
