### ISSUE TITLE
Add state chart to template library

### ISSUE THREAD

**Issue by Michiel-s** [AmpersandTarski/Ampersand#532]
Something nice for RAP3?

http://gojs.net/latest/samples/stateChart.html

**Comment by hanjoosten** [comment]
Nice idea. However, take note that this is not free open software, Or did I overlook something in the pricing?

Also we need to think for what purpose we aim to use a tool like this. Input? output only? Both have consequences. But in general, I love the idea!

**Comment by Michiel-s** [comment]
>However, take note that this is not free open software,

That I didn't saw the first time. Thx!
