### ISSUE TITLE
Reinstalling RAP3

### ISSUE THREAD

**Issue by stefjoosten** [AmpersandTarski/Ampersand#534]
When RAP3 is reinstalled, we want past work of students to be loaded into RAP3, so they do not experience loss of work. This involves:
- restoring the account administration in RAP3
- restoring the administration of scripts in RAP3

The problem with accounts is that the passwords of students will be lost. So students will have to sign up again. In order not to lose work, the files on the file system must be tracable by means of the student number, because every student will use that number consistently and obligatory.

**Comment by RieksJ** [comment]
Currently, we can use INTERFACEs for importing from Excel files. I can imagine the converse: using something INTERFACE-like to write Excel files. That way, we could backup whatever it is we needed to (in terms of database populations of course, not complete file systems), then reinstall RAP3, and re-import the saved Excel files (or maybe you can even compile them as default population).

**Comment by Michiel-s** [comment]
Not relevant anymore I guess. Otherwise can be picked up/reopened in RAP repo.
