### ISSUE TITLE
Enable syntax highlighting of Ampersand in ACE editor

### ISSUE THREAD

**Issue by hanjoosten** [AmpersandTarski/Ampersand#537]
Having ACE in place in multiple Ampersand prototypes (#533), we need an Ampersand syntax file for [ACE](mp1Pops contextInfo rules), which then can be used in the editor.

**Comment by hanjoosten** [comment]
I have been looking at what has to be done. It is more than just putting a file somewhere. There is some javascript that has to be written, to define a `'mode'`. A clear [How To](https://ace.c9.io/#nav=higlighter) is available. 

For the highlighter stuff, examples are available [here](https://ace.c9.io/tool/mode_creator.html). I hope @Michiel-s is available to do the ultimate integration.

**Comment by Michiel-s** [comment]
Close and reopen issue in RAP repo
