### ISSUE TITLE
Ampersand installation on (my) Windows 7 machine

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/Ampersand#539]
This ticket is here to reassure users that get lots of errors when trying to install `stack` or compile ampersand.exe` should continue to call stack until they get the result they want. @Michiel-s has informed me that he, too, has experienced the likes of what is described here. 

This morning I was no longer able to generate ampersand.exe, due to changes in the 'lower parts' of haskell. I lost the exact errors that I got, but they somehow had to do something with haddock.

I took this opportunity to reinstall `stack` from scratch, using the installation instructions in the gitbook. 
Before doing so, I uninstalled and removed everything I could find that was related to stack, haskell, ghc, and cabal. 

I got all sorts of errors when executing `stack setup`, ranging from 
~~~
mkdir: cannot change permissions of '/dev/shm': Permission denied
mkdir: cannot change permissions of '/dev/mqueue': Permission denied
~~~
and
~~~
gpg: DBG: armor-keys-failed (KEY 0x9761A75C7C353A1892DE0CDBE1CE2D5D9183CA0B BEGIN
) ->0
gpg: DBG: armor-keys-failed (KEY 0x9761A75C7C353A1892DE0CDBE1CE2D5D9183CA0B FAILED 6
) ->6
~~~
and
~~~
gpg: keyserver refresh failed: bad public key
==> ERROR: A specified local key could not be updated from a keyserver.
~~~

Then, when running `stack install`, a similar amount of errors occurred, and I have seen several `ExitFailure 1` texts. However, running `stack install` multiple (3) times ultimately resulted in a new Ampersand.exe.

**Comment by RieksJ** [comment]
I have updated the installation documentation to reflect this.

**Comment by hanjoosten** [comment]
This bug has been reported to the developer team of stack, in [this issue](https://github.com/commercialhaskell/stack/issues/2617).
