### ISSUE TITLE
webserver deployment

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/Ampersand#540]
It has come to my attention that besides Apache, there is another webserver stack that is commonly used: Nginx.  Together, they are responsible for serving over 50% of traffic on the internet. Both solutions are capable of handling diverse workloads and working with other software to provide a complete web stack. However, they also have some notable differences, that may influence the choice on which to deploy prototypes, in particular as we are slowly (but steadily) moving towards situations where we actually deploy webservices that are basically (CSS-tweaked) prototypes. 

https://www.digitalocean.com/community/tutorials/apache-vs-nginx-practical-considerations has a comparison that shows the (dis)advantages of one over the other.

We may want to ponder about whether or not we should generate our prototypes in such a way that they could be deployed on either of these webserver stacks.

**Comment by hanjoosten** [comment]
As far as I know there is nothing specifc we do for any webserver. Basically, we generate a directory that contains the prototype. It should run in any well-set-up webserver. As far as I know we all use Apache, so we can guarantee that it works on that webserver. If anyone has knowledge of another webserver (like Nginx or whatever), it should be possible to run any ampersand prototype. However, we are not the ones providing that knowledge. I would like to know if there is anything we generate that is specific for Apache, not working on other webservers.

**Comment by RieksJ** [comment]
Here's an example: we use the .htaccess files to convert calls to webpages into API calls. This is a feature that Nginx does not handle, and therefore a prototype that is deployed on an Nginx server doesn't work. There may be other examples.

**Comment by Michiel-s** [comment]
Personally I think this is a non-issue. The complete stack is platform independent: frontend (js,html,css) runs in every up-to-date browser. backend (php, mysql) should run on every webserver.

You're right that you may experience difficulties with the URL rewriting for the API. URL rewriting functionality is webserver functionality. Htaccess is Apache specific, but also supported by IIS (windows webserver). We could add the Nginx equivalent, but for me this has very low prio. Maybe it's easy though. Not sure.

**Comment by hanjoosten** [comment]
I suggest closing this issue to prevent it to gloggerup the issue list. If there is a real need, it can be reopened.

**Comment by WolframKahl** [comment]
On Thu, Sep 29, 2016 at 06:19:36AM -0700, Han Joosten wrote:
> As far as I know there is nothing specifc we do for any webserver.

Except that the front-end required a ton of modules activated/installed,
and configuration options set in the right way, when I tried last time
on FreeBSD...

**Comment by Michiel-s** [comment]
Of course. If you want to have all the nice features, templates, etc you require something more than just "turn it on".

Same applies to the ampersand generator. You must learn the modeling language, the syntax, know how to work with the command line interface and more.

"if you can't stand the heat, get out of the kitchen"

**Comment by Michiel-s** [comment]
By the way. We're trying to keep it as simple as possible. At least that is what I'm striving for.
