### ISSUE TITLE
Adding a scope to the type checker

### ISSUE THREAD

**Issue by sjcjoosten** [AmpersandTarski/Ampersand#543]
As mentioned in #133 we need a type checker that gets a scope, determining which relations are defined and which are not. This is important if Violations are treated in the same way as interfaces: a violation should be able to make reference to the original tuple, so there are relations `_src` and `_tgt`, which are only in scope in Violations, but not in other parts of the code.

Currently, there is one part in Ampersand that needs this: `_SESSION`. This is because a session is only defined within interfaces. Therefore, in the branch `feature/unifiedInterfaces`, I will make it such that this relation (standing for a singleton atom) is only allowed within interfaces.

**Comment by sjcjoosten** [comment]
This was complicated by the suggested solution to https://github.com/AmpersandTarski/RAP/issues/8

The solution proposed there shows that it should be possible for rules that are linked to roles to contain the ``_SESSION`` atom. Since it is not straightforward to decide which rules are linked to roles and which are not, I need to allow this for all rules. This raises the question where ``_SESSION`` should be disallowed.

**Comment by RieksJ** [comment]
`_SESSION` is not only needed in interfaces, but also in other contexts. Here are some examples from RAP3: 
~~~
ROLE User MAINTAINS "Wilt u uw wachtwoord veranderen?"
RULE "Wilt u uw wachtwoord veranderen?": '_SESSION';sessionAccount;accPassword;'welkom' |- -V
MESSAGE "Het wachtwoord 'welkom' dient te worden aangepast."
VIOLATION (TXT "U dient uw wachtwoord te wijzigen in de interface 'My Account' in de menubalk.")

accNewPassword :: Account * Password [UNI]
ROLE ExecEngine MAINTAINS "(Re)set the password of an account"
RULE "(Re)set the password of an account": 
   accNewPassword /\ (sessionAccount~ \/ V;'AccountMgr';sessionActiveRoles~);'_SESSION';V |- -V
MEANING "(Re)setting the password for an account can only be done by an AccountMgr or the account user."
VIOLATION (TXT "{EX} InsPair;accPassword;Account;", SRC I, TXT ";Password;", TGT I
          ,TXT "{EX} DelPair;accNewPassword;Account;", SRC I, TXT ";Password;", TGT I
          )
RULE "(Re)setting the password for an account can only be done by an AccountMgr or the account user":
   accNewPassword |- (sessionAccount~ \/ V;'AccountMgr';sessionActiveRoles~);'_SESSION';V
~~~

I'm curious as to where this goes. I hope this work will also enable us to refer to specific atoms in interfaces, e.g. the root atom of (a BOX in) an INTERFACE.
