### ISSUE TITLE
Atoms containing a `;`-character cannot be deleted by means of the ExecEngine

### ISSUE THREAD

**Issue by hanjoosten** [AmpersandTarski/Ampersand#547]
The title says it all. This is due to the fact that in the call to delAtom (in PHP), the `;` character is interpreted as a separator for arguments.

**Comment by Michiel-s** [comment]
You can use _; as seperator in your exec engine rule specification.

Fix for this issue awaits #133

**Comment by hanjoosten** [comment]
I probably do something wrong, for it doesnt work:

```
VIOLATION ( TXT "{EX} DelAtom _;ShowADL _;", SRC I )
```

**Comment by Michiel-s** [comment]
After {EX} specify the _; seperator, see example below.

```VIOLATION ( TXT "{EX}_;DelAtom _;ShowADL _;", SRC I )```

**Comment by hanjoosten** [comment]
Great! So far for the documentation update of this nice feature :smile:

**Comment by Michiel-s** [comment]
I consider this a hidden feature and actually like it that way. It's important to have a proper implementation for the exec engine any time soon.
