### ISSUE TITLE
Message of violation doesn't show

### ISSUE THREAD

**Issue by hanjoosten** [AmpersandTarski/Ampersand#548]
Ina prototype that is generated with --meta-tables (e.g.  RAP3), I have several cases where the message of a violation doesn't make it into the message bar:

![image](https://cloud.githubusercontent.com/assets/1159672/19115482/72068c2a-8b12-11e6-9462-c2870ccd118e.png)

I am 100% sure that there is a MESSAGE part in the RULE.:

```
ROLE User MAINTAINS "Wilt u uw wachtwoord veranderen?"
RULE "Wilt u uw wachtwoord veranderen?": '_SESSION';sessionAccount;accPassword;'welkom' |- -V
MESSAGE "Het wachtwoord 'welkom' dient te worden aangepast."
VIOLATION (TXT "U dient uw wachtwoord te wijzigen in de interface 'My Account' in de menubalk.")

```

**Comment by hanjoosten** [comment]
I have raised this issue, because without the message, it is very hard to tell what is going on, when errors occur. Diagnosis is very hard now.

**Comment by Michiel-s** [comment]
Probably something small. I'll look into this asap

**Comment by hanjoosten** [comment]
@Michiel-s : The fix didn't solve the issue

**Comment by Michiel-s** [comment]
Han and I found the issue. The ace editor library and the markdown library somehow don't work together. Up to me to solve this.
