### ISSUE TITLE
Error message wante in  ROLE statement that mentions an undefined RULE.

### ISSUE THREAD

**Issue by stefjoosten** [AmpersandTarski/ampersand#55]
In a ROLE statement (e.g. ROLE ExecEngine MAINTAINS UpdateAssignment) I would like to see an error message if the rule name (to the right of MAINTAINS)  does not refer to an existing rule.

**Comment by hanjoosten** [comment]
I'll take this issue to a broader level: Currently, a MAINTAIN statement must be in the same process as the rule mentioned. There is no reason for this limitation.
