### ISSUE TITLE
Improve indentation of html templates

### ISSUE THREAD

**Issue by Michiel-s** [AmpersandTarski/Ampersand#551]
Currently the indent action in the GenFrontend.hs file for html templates is not context sensitive. Therefore the output html files look very messy and less readable. This issue requests to fix this.

**Comment by hanjoosten** [comment]
The solution is not perfect, because there is no context available when replacing variables in the template. However, I think this is well enough.

**Comment by Michiel-s** [comment]
I don't agree. Output is really shitty HTML layout. Please keep it open. I can think of a way to solve it.
