### ISSUE TITLE
ClearConcept functionality

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/Ampersand#556]
Consider the scriptlet:
~~~
CLASSIFY Expectation   ISA Objective
CLASSIFY Obligation    ISA Objective
CLASSIFY SelfObjective ISA Expectation /\ Obligation

e :: Expectation * E
o :: Obligation * O

POPULATION SelfObjective CONTAINS [ "s" ]
POPULATION e CONTAINS [ ("s", "eeeee") ]
POPULATION o CONTAINS [ ("s", "ooooo") ]
~~~

Suppose that the ExecEngine calls function `ClearConcept(SelfObjective,s)`.
Then we still have atom `s` that is both an Obligation and an Expectation, which violates the assumption that Obligations and Expectations are disjunct. This is a bug.

Suppose that the ExecEngine calls consecutively calls `ClearConcept(SelfObjective,s)` and `ClearConcept(Obligation ,s)`. Then the Obligations and Expectations are still disjunct.
However, a pair `(s, ooooo)` still exists, even though `s` is no longer an Obligation. This is also a bug.

I would think that the following is needed:

- [ ] ~~After a transaction, disjunctness should be guaranteed (and an error message must be generated if a rollback is required to guarantee this). This requires some Haskell work.~~
- [x] `ClearConcept(Concept, Atom)` must remove all pairs `(Atom, x)` and `(y, Atom)` for relations where `Atom` is explicitly used as an instance of `Concept`. This is frontend stuff.

**Comment by hanjoosten** [comment]
I don't know exactly what this clearConcept functionality does, but it must be implemented in a way that atoms are either deleted or untouched.  CLASSIFY statements are not to be used for properties that can vary in time.:

If we say 
Expectation ISA Objective, and we have an atom E1 in Expectation, it will allways be in Objective as well. On the other hand, removing E1 from Objective must result in removal from Expectation too. It is all atomic:.

I see no clues as to what should be done at the Haskell side.

**Comment by Michiel-s** [comment]
@hanjoosten, I discussed this issue earlier this morning with @RieksJ. In order for me to solve this issue, I need some more information in generics/concepts.json. That's what Rieks is talking about. I'll come back to this later.
