### ISSUE TITLE
Performance issues due to unneccessary cartesian products.

### ISSUE THREAD

**Issue by stefjoosten** [AmpersandTarski/Ampersand#562]
Expressions such as `-I;rel` and `V;rel` are translated to SQL with too many cartesian products in them.
This can be verified by running experiments while using the Ampersand-switch --sqldump. I have run some (arbitrary) experiments, just to conclude that we have some systematic work still to be done:
~~~~~~
RELATION rel[A*B]

RULE -rel
RULE rel
RULE -(rel;-I;rel~)
RULE rel;-I;rel~
RULE rel;rel~
RULE -(rel;rel~)
RULE rel;-I
RULE -I;rel~
RULE rel;V[B*A]
RULE V[A*B];rel~
RULE rel;-I
RULE -I;rel~
RULE rel;(V[B*B] - I[B]);(V[B*B] - I[B])
RULE (V[A*A] - I[A]);(V[A*A] - I[A]);rel
RULE (V[A*A] - I[A]);(V[A*A] - I[A])
~~~~~~
The sub-expression `rel;-I[B];rel~` is being compiled efficiently (in branch InjUniDefinition, SHA 16ce3363effe0295e10f5f2f5aa4b4892c48a7e7), as can be seen by code inspection:
~~~~~~
  - "rule@line 7:6, file uniInjTest.adl": RULE ""rule@line 7:6, file uniInjTest.adl"" : -(rel;-I[B];rel~)
select
  distinct
         fence0.src as src, fence2.tgt as tgt
  from (select "A" as src, "B" as tgt
        from "rel"
        where ("A" is not null)
              and ("B" is not null))
       as fence0,
       (/* Flipped: EDcD rel[A*B] */
        select "B" as src, "A" as tgt
        from "rel"
        where ("A" is not null)
              and ("B" is not null))
       as fence2
  where (fence0.tgt <> fence2.src)
~~~~~~
However, the sub-expression `rel;-I` is translated into inefficient SQL, because it contains an unneccessary cartesian product:
~~~~~~
/* case: (ECps es), with two or more elements in es.rel;-I[B] */
select fence0.src as src, fence1.tgt as tgt
from (select "A" as src, "B" as tgt
      from "rel"
      where ("A" is not null)
            and ("B" is not null))
     as fence0,
     (/* case: ECpl (EDcI B) */
      select "concept0"."B" as src, "concept1"."B" as tgt
      from "B" as "concept0",
           "B" as "concept1"
      where "concept0"."B" <> "concept1"."B")
     as fence1
where (fence0.tgt = fence1.src)
~~~~~~

**Comment by sjcjoosten** [comment]
Does MySQL not optimise this? Can you give a query (and a data-set) that gives a noticeable performance-difference?

**Comment by Michiel-s** [comment]
@stefjoosten as @sjcjoosten already suggest, MySQL optimizes this perfectly (at least in the version I'm using: MariaDB v10.1). Run query with the `EXPLAIN` keyword in front and you see something like this:

![image](https://user-images.githubusercontent.com/7961582/36062698-054a04ba-0e72-11e8-9bf3-0517c7d97b25.png)

Let's close this issue?

**Comment by stefjoosten** [comment]
Reopening: the closing argument ("the DBMS optimizes this") is refuted by a measured production case on MariaDB 10.6 — full analysis and a concrete, testable fix proposal follow in the next comment.

**Comment by stefjoosten** [comment]
# Reopening: "the DBMS optimizes this" turns out not to hold — and cannot hold

This issue was closed in 2018 on the argument that the DBMS optimizer eliminates the unnecessary Cartesian products (an `EXPLAIN` on MariaDB 10.1 looked fine). I now have a measured production counter-example on MariaDB 10.6 showing that it does not — and a structural argument why it *cannot*. I also want to sharpen the problem statement, because the 2018 formulation mixed two classes that need different treatment. With the sharper statement the problem becomes fully solvable in the compiler, with a checkable definition of done.

All identifiers below are anonymized; populations and timings are real.

## The counter-example

```adl
RELATION x[S*E]            -- ENFORCE target: 188 pairs
RELATION a[S*E]            -- 188 pairs
RELATION f[S*T] [UNI]
RELATION st[E*T] [UNI]
ENFORCE x := (a /\ f;st~) \/ (I[S] - f;f~);a
```

with |S| = 11–20 (grows while the application is in use) and |E| = 4790. The `⊆`-direction of the ENFORCE yields the violation term

```
x ∧ ¬((a ∧ f;st~) ∨ (I−f;f~);a)   =   x ∧ (¬a ∨ ¬(f;st~)) ∧ ¬((I−f;f~);a)
```

The generated SQL (Ampersand v5.9.3) contains `select fst."S" as src, snd."E" as tgt from "S" as fst, "E" as snd` — the full Cartesian product `V[S*E]` — **twice**, once per union arm, each row probed by a correlated `NOT EXISTS`. The small anchor `x` (188 rows) is joined only at the outermost level, *after* the products have been computed.

Measured (MariaDB 10.6, slow-query log):

| | generated query | hand-anchored equivalent |
|---|---|---|
| per evaluation | 2.1 s (16 S-atoms) … 6.5 s (seeded sandbox) | < 0.01 s (0.06 s wall incl. client) |
| result | 50 violation rows | identical 50 rows (sorted diff) |

One transactional save re-evaluates the affected conjuncts ~130 times → **20–35 s for a single user action**, growing ~2 s with every additional `S`-atom. The equivalence benchmark: copies of the four tables in a sandbox database, seeded with synthetic violations, both queries diffed row-for-row.

## Why the DBMS cannot rescue this query

`EXPLAIN` on MariaDB 10.6 (names anonymized):

```
id  select_type         table   type    ...
1   PRIMARY             <derived5>  ALL          <- materialized union, no index
1   PRIMARY             x           eq_ref       <- anchor joined AFTER the fact
5   DERIVED             fst × snd   index        <- Cartesian product S×E  (arm 1)
9   UNION               fst × snd   index        <- Cartesian product S×E  (arm 2)
11  DEPENDENT SUBQUERY  ...         eq_ref       <- correlated NOT EXISTS per product row
```

The indexes are all there and all used — and it is still slow, because the *shape* of the query demands the product:

1. **The SQL semantically asks for V per union arm.** `FROM "S", "E" WHERE NOT EXISTS (…)` must enumerate |S|·|E| candidate pairs. Nothing in the query tells the optimizer that the result will later be intersected with the 188-row `x` — that intersection lives in an outer derived table.
2. **A UNION inside a derived table is a materialization barrier.** MariaDB's condition pushdown into derived tables/unions handles constant predicates; it cannot push a *join condition* (`x.src = arm.src AND x.tgt = arm.tgt`) into the union arms. Each arm is therefore materialized in full before the anchor is consulted.
3. **The identity that fixes it, `g ∧ ¬e = g − e`, is relation algebra, not SQL.** The knowledge that an intersection partner `g` exists is discarded by the code generator when it compiles intersection members in isolation. No DBMS recovers algebraic structure across derived-table boundaries. The generator is the only component that has this information — so the generator is where the fix belongs.

So the 2018 closing argument evaluated the wrong case: the original examples here were mostly *bare* complements (`RULE -rel` etc.), where the product is semantically unavoidable and a toy-population EXPLAIN looks harmless. The problem class that hurts in production is different:

> **A complement that has a positive sibling ("anchor") available in the same intersection.** There the product is avoidable — but only by the compiler.

## What has been fixed since 2018, and why it is not enough

`FSpec/SQL.hs` today contains exactly the right micro-optimization: `maybeSpecialCase` compiles `EIsc(expr1, ECpl expr2)` as an anchored anti-join (`t1 LEFT JOIN t2 … IS NULL`), and `EDif(l,r)` is rewritten to `EIsc(l, ECpl r)` so differences benefit too. But it fires **only when the complement is a direct binary operand of the intersection**. It does not reach a complement that sits:

* **(a) in a member of an n-ary intersection** — the general `EIsc{}` case (`makeIntersectSelectExpr`) compiles each member in isolation and joins them afterwards (`subIntersect0`, `subIntersect1` in the output). Members are sibling-blind: a cheap positive member cannot bound an expensive complement inside another member.
* **(b) inside a union arm** — the `EUni` case compiles arms standalone; a `ECpl` arm falls through to the generic `ECpl e` branch, which introduces `EDcV (sign e)` (its own trace comment warns "CARTESIAN PRODUCT!").

Exact case chain for the counter-example, confirmed by the annotation comments in the generated SQL:

```
EIsc( x , EDif( EUni(ECpl a, ECpl b) , c ) )
  └─ general EIsc{}: x and the EDif-member compiled in isolation      (a)
       └─ EDif → EIsc(EUni(¬a,¬b), ECpl c) → maybeSpecialCase:
            anti-join for c ✓ — but its t1 = EUni(¬a,¬b) is compiled standalone
              └─ EUni: each ¬-arm → generic ECpl branch → EDcV → V[S*E]   (b) ×2
```

Issue #1624 proposes the binary rewrite `r ∧ ¬e → r − e` for the ENFORCE deletion check — correct, but it only reaches pattern-position complements and would not have fixed this case (nested one level deeper). Issue #1646 documents shape (b) on import. Issue #1409 is likely a relative.

## Proposal: an anchored rewrite in the optimizer — and what "100% solved" means

A pure `Expression → Expression` pass on violation terms, before SQL generation (at the point where conjunct violation expressions are formed, or as a pre-pass at the top of `selectExpr`). Flatten the intersection (`exprIsc2list`), pick any complement-free member `g` as anchor (heuristic: a stored relation / the smallest), then rewrite the remaining members with three rules:

* **R1 (absorb):** `g ∧ ¬e → g − e`
* **R2 (distribute, guarded):** `g ∧ (p ∨ q) → (g ∧ p) ∨ (g ∧ q)` — only when `p` or `q` contains a complement (the guard prevents pointless tree growth)
* **R3 (push through difference):** `g ∧ (p − q) → (g ∧ p) − q`

until no `ECpl` is reachable. Every complement then ends up as the right-hand side of an anchored `EDif` — exactly the shape the **existing** `EDif`/`maybeSpecialCase` machinery already compiles into an efficient anti-join. **No new SQL-generation code is needed; the generic `ECpl` branch simply stops being reached.**

Worked example:

```
x ∧ ((¬a ∨ ¬b) − c)
  = x ∧ (¬a ∨ ¬b) ∧ ¬c        -- def. −
  → ((x ∧ ¬a) ∨ (x ∧ ¬b)) ∧ ¬c  -- R2
  → ((x − a) ∨ (x − b)) − c      -- R1 ×3
```

Every subquery now starts `FROM "x"` (188 rows) instead of `FROM "S", "E"` (52 690 rows and growing). This is the hand-anchored query from the measurement table: identical results, ~100× faster, and the multiplicative growth with |S| is gone.

**Correctness.** R1 follows from `¬e = V − e` and `g ∧ V = g` (every well-typed term of signature `[A*B]` is contained in `V[A*B]`; on the database side this is the standing invariant that relation contents lie within the concept tables). R2 is distributivity, R3 associativity with `p − q = p ∧ ¬q`. **Termination:** each R1 removes an `ECpl`; R2/R3 strictly move a complement closer to an anchor in a finite tree.

**Definition of done** (this is what makes the issue closable this time):

1. After the pass, the generic `ECpl` branch (the one introducing `EDcV`) is reachable **only** for terms with no complement-free member at all (e.g. `RULE -r |- s`) — the only case where the product is semantically necessary. Emit a compiler **warning** there, so the modeler knows the rule is inherently O(|A|·|B|).
2. Acceptance test: compile the reproducer below and assert the generated SQL for the ENFORCE rules contains no `cartesian product of` marker.
3. The existing regression suite passes unchanged (the rewrite is expression-level; the SQL layer is untouched).

## Minimal reproducer

```adl
CONTEXT AnchorTest
RELATION x[S*E]
RELATION a[S*E]
RELATION f[S*T] [UNI]
RELATION st[E*T] [UNI]
ENFORCE x := (a /\ f;st~) \/ (I[S] - f;f~);a
ENDCONTEXT
```

Compile and search the generated SQL for `cartesian product of S and E`: it appears twice today, despite `x` being available as an anchor in the same violation term.
