### ISSUE TITLE
Generation of dirty identifiers should not use scientific notations

### ISSUE THREAD

**Issue by hanjoosten** [AmpersandTarski/Ampersand#565]
![image](https://cloud.githubusercontent.com/assets/1159672/20344023/4cc5915e-abf1-11e6-95f0-4f6cd46c490c.png)

**Comment by hanjoosten** [comment]
[This](http://stackoverflow.com/questions/1471674/why-is-php-printing-my-number-in-scientific-notation-when-i-specified-it-as-00) might help

**Comment by Michiel-s** [comment]
With the above information I'm not able to diagnose where the bug is. This might be a bug in the RAP3 exec engine specific functions or a generic issue. @hanjoosten let's dive into this together on a friday afternoon!?

**Comment by hanjoosten** [comment]
friday aftenoon sessions are temporarily not possible any more, because of my current work. However, this issue can be seen very clear in phpmyadmin. Looking at the generated identifiers, examples are there enough. For instance in the concept table:

![image](https://cloud.githubusercontent.com/assets/1159672/20860499/baa41d36-b979-11e6-80ed-8eec1c32ff4d.png)

As you can see, some of them end with E+15.

**Comment by hanjoosten** [comment]
@Michiel-s , Could you please review the fix I made? My PHP is like your Haskell ;-)
