### ISSUE TITLE
API call not found in generated prototype

### ISSUE THREAD

**Issue by Sranang-J** [AmpersandTarski/Ampersand#568]
![bug](https://cloud.githubusercontent.com/assets/20729551/20629078/eaf22434-b329-11e6-8aae-31b0472bbc9a.PNG)

Translated with Ampersand v3.5.1[master:4496c8f]

[Prototype2.txt](https://github.com/AmpersandTarski/Ampersand/files/613494/Prototype2.txt)

I edited the extension to ".txt" instead of ".adl" because of the upload restrictions. I translated the "Prototype2.adl" file with an command line.

I used the following command line: 
~~~~~~
D:\>Ampersand --proto=c:\xampp\htdocs\Protonewjdr d:\proto\prototype2.adl
Generating frontend....done.
~~~~~~

**Comment by hanjoosten** [comment]
Hi. Sorry to see you have trouble installing your prototype. There should be log files at the location where the prototype was generated. In your case at `C:\xampp\htdocs\Protonewjdr\log` . There is a good chance that the clue can be found in those logs. If it isn't obvious to you, please attach those log files. 
Please let us know if this helped for you.

**Comment by Michiel-s** [comment]
I think your webserver is not processing the .htaccess file in the folder /api/v1 correctly. There is a RewriteEngine rule that should redirect calls to /api/v1 to the index file in that folder:

```
RewriteEngine On
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^ index.php [QSA,L]
```

A couple of suggestions:
* Make sure the rewrite module of your apache server is enabled.
* See issues #320, #186, #404 for other users running into this issue.
* Google on how to enable and check your rewrite engine is working

Would you report here if and how you solved the issue?
