### ISSUE TITLE
Target-machine dependent configurations

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/Ampersand#570]
Currently, we have some basic facilities to support configurations for applications as they are deployed on (sometimes different) target machines. This support is provided in the file `localSettings.php`. Examples include the configuration of:

- database accounts
- external API's (e.g. for social logins, postcode-api's, ...) 
- runtime behaviour (e.g. preventing the resetting of the database or importing excel files)
- and recently: the location of ampersand.exe (in the RAP3 application)

In the near future, I foresee that the need to manage such configurations will increase, e.g. as the new version of SIAM (v3) will be made available, and as we start using prototypes in different projects.

We need to discuss what is needed and how to do this in such a way that 

- the basic `localSettings.php`, containing the default configurations for deployment of applications on a local machine (localhost), can remain part of the default deployment
- deployments on other machines, including virtual machines, can be configured independently of the dfault deployment and other possible deployments (for example, if an application is to be deployed on a development server (localhost), a test server, and a production server, then the 'client-secret' that would be needed for social logins can be configured independently for all servers, without any interference between the different deployment-configurations and the default configuration).

**Comment by hanjoosten** [comment]
This raises the question of scope. 

In general, a prototype built with Ampersand consist of several components:
1) The stuff that is generated by ampersand.exe, based on the user's script.
2) stuff that is not generated by ampersand.exe, but which is part of the frontend (e.g. execengine)
3) Stuff that is model-specific, (e.g. cli.php in RAP3)

The stuff in 1) and 2) are all under version management in the ampersand repository. There should be nothing specificly for a single user in there. 
The stuff in 3) can be under version management in ampersand-models, but could also be under a different version management regime. (Like TNO does in their own version management repo). 

The default LocalSettings.php is (and should be) in the ampersand repo. A modified copy of it could be in the repo for any application.

**Comment by RieksJ** [comment]
I think we should properly distinguish between version management and configuration management. In order to understand @hanjoosten's comment: where does the possibility of using social logins belong? Is that 2 (which means we can make it available to all applications that need it)or 3 (which means that everyone has to organize if for himself)?

**Comment by Michiel-s** [comment]
Ho! Stop!

You both are right. I think the request of Rieks is misunderstood. I recognize the issue myself.

I totally agree that a generic settings file should be in the repo and by means of the include folder you have the possibility to overwrite for application specific purposes.

However, during development you have other settings than when you want to deploy an app on e.g. a hosted server. There comes the "settings or configuration management" Rieks is talking about. Different configurations for different deployment situations.

We already have the config yaml file solution. Let's see if this already provides a solution for Rieks.

**Comment by Michiel-s** [comment]
As said, use the deployment configuration settings via the --config switch. In the yaml file you can specify the include folder, where deployment specific localSettings.php and other files can be put.
