### ISSUE TITLE
Filename missing in API.ERROR: 2002: No such file or directory [] []

### ISSUE THREAD

**Issue by WolframKahl** [AmpersandTarski/Ampersand#576]
After giving write permission (I did not find this documented ...) in the prototype subdirectory `/var/www/localhost/htdocs/A/EURent/log`, the `error-2016-12-02.log` contains:
````
[2016-12-02 02:40:44] API.ERROR: 2002: No such file or directory [] []
[2016-12-02 02:45:30] API.ERROR: 2002: No such file or directory [] []
[2016-12-02 02:47:48] API.ERROR: 2002: No such file or directory [] []
[2016-12-02 02:48:20] API.ERROR: 2002: No such file or directory [] []
[2016-12-02 03:32:56] API.ERROR: 2002: No such file or directory [] []
````
It would be much preferred if this contained the offending file name...

The apache log shows that this is a problem with sessions:
````
192.168.1.121 - - [01/Dec/2016:20:45:29 -0500] "GET /A/EURent/api/v1/sessions/s89b860apb02vbm1kvak7hjk94/navbar HTTP/1.1" 500 152
192.168.1.121 - - [01/Dec/2016:20:45:30 -0500] "GET /A/EURent/app/images/logos/logo-ou.png HTTP/1.1" 304 -
192.168.1.121 - - [01/Dec/2016:20:45:30 -0500] "GET /A/EURent/app/images/logos/logo-tno.png HTTP/1.1" 304 -
192.168.1.121 - - [01/Dec/2016:20:45:30 -0500] "GET /A/EURent/app/images/logos/logo-ordina.png HTTP/1.1" 304 -
192.168.1.121 - - [01/Dec/2016:20:45:30 -0500] "GET /A/EURent/app/images/ampersand.png HTTP/1.1" 304 -
::1 - - [01/Dec/2016:20:45:45 -0500] "OPTIONS * HTTP/1.0" 200 -
192.168.1.121 - - [01/Dec/2016:20:47:11 -0500] "GET /A/EURent/index.php HTTP/1.1" 200 5901
192.168.1.121 - - [01/Dec/2016:20:47:15 -0500] "GET /A/EURent/api/v1/sessions/s89b860apb02vbm1kvak7hjk94/navbar HTTP/1.1" 403 383
192.168.1.121 - - [01/Dec/2016:20:47:44 -0500] "GET /A/EURent/index.php HTTP/1.1" 200 5901
192.168.1.121 - - [01/Dec/2016:20:47:48 -0500] "GET /A/EURent/api/v1/sessions/s89b860apb02vbm1kvak7hjk94/navbar HTTP/1.1" 500 152
192.168.1.121 - - [01/Dec/2016:20:48:20 -0500] "DELETE /A/EURent/api/v1/sessions/s89b860apb02vbm1kvak7hjk94 HTTP/1.1" 500 152
````
Even after I create that `A/EURent/api/v1/sessions` directory with write permissions.

Probably some functionality is missing from my apache-2.4.23 setup --- what might that be?

(The prototype does nothing useful, probably due to that.)

Ampersand-v3.7.3

**Comment by WolframKahl** [comment]
Possibly my problem was one of the following PHP extensions missing:
````
mysql libmysqlclient xmlreader xmlrpc xmlwriter xslt  
````
The prototype now seems to be somewhat working.

However, if that `API.ERROR: 2002: No such file or directory [] []` is thrown, it still should contain the file name...

**Comment by hanjoosten** [comment]
@Michiel-s : Do you know if this missing file error is thrown by something generic? Could the file name be logged as well? Or is it in eurent specific code? In that case, @RieksJ might be able to fix it?

**Comment by Michiel-s** [comment]
Hi @WolframKahl, your issue was indeed causes by a missing mysql extension. The error is thrown by an internal function trying to connect to the database socket. Since the error is not catched, the generic error (returned by the internal function) is thrown.

If you enable the debug mode in your localSettings.php: `Config::set('debugMode', 'global', true);` the call stack if shown, which points directly to the error location.

**Comment by WolframKahl** [comment]
Thank you!

Wolfram
