### ISSUE TITLE
Clean up way of escaping

### ISSUE THREAD

**Issue by hanjoosten** [AmpersandTarski/Ampersand#580]
There is an [excellent article about having text in text](http://kunststube.net/escapism/). This will help us unravel the escaping stuff we have at the Haskell part of ampersand. 

TODO: Write some escape functions in a single module. Use these all over the place where escaping is used. Get rid of the current functions (like escapeNonAlphaNum and escapeIdentifier in Ampersand.Basics.String)

**Comment by Michiel-s** [comment]
@hanjoosten this one is fixed now right? With the new quotes for singletons?
