### ISSUE TITLE
Make specification of language optional.

### ISSUE THREAD

**Issue by hanjoosten** [AmpersandTarski/Ampersand#587]
Currently, in any script, it is mandatory to specify the language you use. Why not make it optional?

`CONTEXT Foo IN ENGLISH` 

we can just type `CONTEXT Foo`

### Consequences
Although this reduces specification, it could look odd when you are not aware of multiple languages. Therefor, if no language is specified, the language used will match the language specified in the switches, if there is one. Otherwise, ENGLISH will be the default.

**Comment by Michiel-s** [comment]
Nice!
