### ISSUE TITLE
PURPOSE / MEANING / MESSAGE syntax should be alike

### ISSUE THREAD

**Issue by hanjoosten** [AmpersandTarski/Ampersand#589]
## Current situation

We use markup for PURPOSE, MEANING and MESSAGE:

![image](https://cloud.githubusercontent.com/assets/1159672/21079344/0524f15c-bf90-11e6-8b74-98a17cece7fd.png)

![image](https://cloud.githubusercontent.com/assets/1159672/21079323/3c8b5fb0-bf8f-11e6-84b0-096e98aa376d.png)

![image](https://cloud.githubusercontent.com/assets/1159672/21079391/4163caf2-bf91-11e6-98d5-c162194985de.png)

All these constructs enable the user to supply some text that has some metadata: the language of the supplied text and the format it is in, for layout. 

## Observation
Allthough there are a lot of similarities, the minor differences have impact on the maintainability of the source code of Ampersand. This has grown in time, and now it is messy. 

## Proposed change
We could introduce this common NonTerminal in the synax: 

![image](https://cloud.githubusercontent.com/assets/1159672/21079502/8a7367d2-bf93-11e6-8cab-174cd500949f.png)

and use this in PURPOSE, MEANING and MESSAGE alike.

**Comment by RieksJ** [comment]
Would `Ref2Obj`s, as used in `PURPOSE`s, still be supported?

- if so, I don't mind the change as proposed.
- if not, I propose `Markup ::= Ref2Obj? LanguageRef? TextMarkup? ('REF' StringListSemi)? (String | Expl)`

**Comment by hanjoosten** [comment]
Yes. That will remain specific for PURPOSE ofcours. Ref2Obj has nothing to do with markup.
