### ISSUE TITLE
Algebra problems with dagger and dagger-like constructs

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/ampersand#59]
Consider the following scriptlet:

    factuurRegel :: Factuur * Regel
    regelText :: Regel * TEXT [UNI]
    factuurOK :: Factuur * Factuur [PROP]

    RULE "Factuur check": factuurOK = I[Factuur] /\ -(factuurRegel;-regelText);V
    MEANING "A Factuur is ok IFF the Factuur is empty or every of its factuurRegels contains text."

    POPULATION factuurRegel CONTAINS [ ("Factuur1", "Regel1") ]
    POPULATION regelText    CONTAINS [ ("Regel1", "Eentje") ]
    POPULATION factuurRegel CONTAINS [ ("Factuur1", "Regel2") ]
    POPULATION regelText    CONTAINS [ ("Regel2", "Tweede") ]
    POPULATION factuurOK    CONTAINS [ ("Factuur1", "Factuur1") ]

It seems to me that this is a valid population for the model, but the script does not compile due to population errors. This is also the case when the rule is replaced with its equivalent:

        RULE "Factuur controle": factuurOK = I[Factuur] /\ (-factuurRegel ! regelText);V

I have put an elaborate set of testpopulations in the Sentinel, testing both proper and improper populations for `factuurOK`. The files containing the abovementioned population are `FactuurConcat4.adl` and `FactuurDagger4.adl` in the `ShouldSucceed` directory.

**Comment by stefjoosten** [comment]
Hoi Rieks,
Ik probeer even na te rekenen wat jouw regel doet. Eerst de gegevens, dan het rekenwerk, dan de resultaten en conclusies...

Gegeven:

    factuurRegel :: Factuur * Regel
     = [ ("Factuur1", "Regel1") , ("Factuur1", "Regel2") ]
    regelText :: Regel * TEXT [UNI]
     = [ ("Regel1", "Eentje") , ("Regel2", "Tweede") ]
    factuurOK :: Factuur * Factuur [PROP]
     = [ ("Factuur1", "Factuur1") ]
    
    RULE "Factuur check": factuurOK = I[Factuur] /\ -(factuurRegel;-regelText);V
    MEANING "A Factuur is ok IFF the Factuur is empty or every of its factuurRegels contains text."


Gevraagd:
Controleer of jouw bewering klopt, dat RULE "Factuur check" waar is.

Aanpak:
Deductie vanuit de gegevens.

Rekenwerk

    1.     I[Factuur] = [ ("Factuur1", "Factuur1") ]
    
    2.     V[Regel*TEXT] = [ ("Regel1", "Eentje") , ("Regel1", "Tweede") , ("Regel2", "Eentje") , ("Regel2", "Tweede") ]
    
    3.     -regelText
        =
           V[Regel*TEXT]-regelText
        =  { 2. en regelText }
           [ ("Regel1", "Eentje") , ("Regel1", "Tweede") , ("Regel2", "Eentje") , ("Regel2", "Tweede") ] - [ ("Regel1", "Eentje") , ("Regel2", "Tweede") ]
        =
           [ ("Regel1", "Tweede") , ("Regel2", "Eentje") ]
    
    4.     factuurRegel;-regelText
        =  { factuurRegel en 3. }
           [ ("Factuur1", "Regel1") , ("Factuur1", "Regel2") ];[ ("Regel1", "Tweede") , ("Regel2", "Eentje") ]
        =
           [ ("Factuur1", "Eentje") , ("Factuur1", "Tweede") ]
    
    5.     V[Factuur*TEXT] = [ ("Factuur1", "Eentje") , ("Factuur1", "Tweede") ]
    
    6.     -(factuurRegel;-regelText)
        =
           V[Factuur*TEXT]-(factuurRegel;-regelText)
        =  { 5. en 4. }
           [ ("Factuur1", "Eentje") , ("Factuur1", "Tweede") ]-[ ("Factuur1", "Eentje") , ("Factuur1", "Tweede") ]
        =
           []
    
    7.     V[TEXT*Factuur] = [ ("Eentje", "Factuur1") , ("Tweede", "Factuur1") ]
    
    8.     -(factuurRegel;-regelText);V
        =  
           -(factuurRegel;-regelText);V[TEXT*Factuur]
        =  { 6. en 7. }
           [] ; [ ("Eentje", "Factuur1") , ("Tweede", "Factuur1") ]
        =
           []
    
    9.     I[Factuur] /\ -(factuurRegel;-regelText);V
        =  { 8. }
           I[Factuur] /\ []
        =
           []
    
    10.    factuurOK = I[Factuur] /\ -(factuurRegel;-regelText);V
        =  { factuurOK en 9. }
           [ ("Factuur1", "Factuur1") ] = []
       Deze bewering is dus niet waar.

Conclusie
Omdat 10. niet waar is en 10. logisch volgt uit de aannames, moet ik concluderen dat aan RULE "Factuur check" niet voldaan is.

Ik zit me dus even af te vragen of je de tickets wel terecht inschiet… Maar nu ga ik slapen…

**Comment by stefjoosten** [comment]
Ik probeer even na te gaan wat de bedoeling was.

Gedachte 1. De oorspronkelijke `MEANING`:
`A Factuur is ok IFF the Factuur is empty or every of its factuurRegels contains text.`

Het lijkt me dat de `is empty` erin overbodig is, omdat de lege verzameling van regels ook de eigenschap heeft dat alle regels tekst bevatten. Dus:
`A Factuur f is ok IFF every Regel of the factuurRegels of f contains text.`

Gedachte 2. Een formulering in Ampersand
Deze regel laat zich als volgt opschrijven:

    RULE "fact" : factuurRegel~ |- (regelText;regelText~/\I[Regel]);V

in woorden: als een regel r in een factuur zit, dan bevat die regel tekst

Gedachte 3. De formulering van de eigenschap `factuurOK`

        V[Factuur*Regel];(-factuurRegel~\/(regelText;regelText~/\I[Regel]);V[Regel*Factuur])
    <=> { distributie }
        -(V[Factuur*Regel];-factuurRegel~ \/ V[Factuur*Regel];(regelText;regelText~ /\ I[Regel]);V[Regel*Factuur])
    <=> { De Morgan }
        -(V[Factuur*Regel];-factuurRegel~) /\ -(V[Factuur*Regel];(regelText;regelText~ /\ I[Regel]);V[Regel*Factuur])

Tussenconclusie:
Deze uitdrukking bestaat dus in feite uit twee regels: `-(V[Factuur*Regel];-factuurRegel~)` en `(regelText;regelText~ /\ I[Regel])`. De tweede is niets anders dan het totaal zijn van `regelText`.

Gedachte 4. Spelen met `-(V[Factuur*Regel];-factuurRegel~)`

        -(V[Factuur*Regel];-factuurRegel~)
    <=> { De Morgan op ; }
        -V[Factuur*Regel] ! factuurRegel~
    <=> { naar residu }
        V[Regel*Factuur] \ factuurRegel~
    <=> 
        factuurRegel

Tussenconclusie:
Dit is een rare gedachte. Kennelijk moet `factuurRegel` een volledige relatie (`V`) zijn.
Hier gaat iets fout...

**Comment by RieksJ** [comment]
Dit ticket geeft een algebra-regel en een `MEANING` die geacht worden hetzelfde uit te drukken. De populatie in het ticket geeft een voorbeeld van wat er wordt bedoeld en nog andere voorbeelden hiervan zitten in de Sentinel. Ik stel vast dat Ampersand vindt dat er discrepanties optreden. Het doel dat ik met dit ticket nastreef is dat er een algebra-regel komt die de geformuleerde `MEANING` in RA uitdrukt en die *dus* geen violations geeft in de test-populaties in de Sentinel, die immers de operationele uitdrukking zijn van wat we willen.

Ik postuleer dat dit de volgende regel is:

    factuurOK = I  /\  -factuurRegel ! ( (I /\ regelText;regelText~); factuurRegel~ )

waarbij `factuurRegel~` vervangen zou mogen worden door `V`. De precieze verwoording van deze regel is als volgt:

    Een factuur is OK dan en slechts dan als:
    ( voor elke Regel die er maar bestaat het volgende geldt:
      ( deze Regel is GEEN factuurRegel op die factuur
      of:
        ( deze Regel is WEL een factuurRegel op die factuur, 
        en 
          heeft bovendien de eigenschap dat hij is voorzien van een TEXT inhoud.
    ) ) )

En deze blijkt ook te doen wat de bedoeling is.

**Comment by Oblosys** [comment]
Het viel me op dat een aantal van de regels hierboven een `I[Factuur]` conjunct hebben, met als gevolg dat de regel altijd faalt zodra er meer dan 1 `Factuur` atoom is. (wil de regel slagen dan moeten alle conjuncten gelijk zijn aan `V[Factuur]`, en `I[C] == V[C]` geldt alleen als `C `maximaal 1 element heeft) Gebruik van `I` lijkt me logischer bij implicaties en disjuncties (`|-` & `\/`). Het heeft niet meteen met de situatie hierboven te maken, aangezien het voorbeeld alleen `Factuur1` bevat, maar kan wellicht verwarring veroorzaken zodra er meer `Factuur` atomen zijn.

Zelf vind ik relatiealgebra altijd vrij ingewikkeld en ik gebruik daarom vaak de `testRule` functionaliteit van Ampersand. Door `php/Database.php?testRule=regelNaam` aan de url van een prototype toe te voegen kun je regel `regelNaam` evalueren en krijg je zowel de paren in de regelexpressie als de violations te zien. Bv:

```
http://padNaarAmpersandPrototypes/Delivery/php/Database.php?testRule=allAccepted
```

Hiermee kun je gemakkelijk het effect van aanpassingen op regels en populaties zien (bij populatieverandering even de database opnieuw initialiseren). Je moet het prototype wel met --dev gebouwd hebben, maar als dat niet zo is word je eraan herinnerd.

**Comment by stefjoosten** [comment]
Hoi Rieks,

Ik ga nog even door, omdat deze exercitie bedoeld was als leerstuk in het formuleren van regels.

Ik vind jouw definitie van factuurOK uitstekend:

factuurOK = I  /\  -factuurRegel ! ( (I /\ regelText;regelText~); factuurRegel~ )

De betekenis ervan is goed te volgen.

Je signaleert terecht dat de dagger er een plaats in heeft, met een complement aan één kant.
Dat betekent dat het een residu moet zijn, op basis van  -r~!s = r\s.
Ik kom, al handenzwaaiend, tot de volgende formulering:

factuurOK’ = I /\ (factuurRegel~\regelText);V

Het verhaal daarbij:

Een factuur f is OK dan en slechts dan als:
( er bestaat een TEXT
  ( voor elke Regel die op factuur f staat
 ) )

De vraag die ik heb: hoe bewijs je dat factuurOK’ = factuurOK?
Of eigenlijk mag die zwakker zijn. Ik ben ook tevreden met het bewijs dat factuurOK’ |- factuurOK  of  factuurOK |- factuurOK’.
(Natuurlijk is ook een bewijs dat factuurOK’ /= factuurOK interessant, want dat toont aan dat mijn handengezwaai niet deugt.)

Ik heb niet getest of deze formulering werkt op de database.

Stef Joosten

M +31 (0)6 51348895
skype: stef.joosten




-----Oorspronkelijk bericht-----
Van: Rieks [mailto:notifications@github.com]
Verzonden: donderdag 9 april 2015 13:51
Aan: Joosten, Stef
Onderwerp: Re: [ampersand] Algebra problems with dagger and dagger-like constructs (#59)

Dit ticket geeft een algebra-regel en een MEANING die geacht worden hetzelfde uit te drukken. De populatie in het ticket geeft een voorbeeld van wat er wordt bedoeld en nog andere voorbeelden hiervan zitten in de Sentinel. Ik stel vast dat Ampersand vindt dat er discrepanties optreden. Het doel dat ik met dit ticket nastreef is dat er een algebra-regel komt die de geformuleerde MEANING in RA uitdrukt en die dus geen violations geeft in de test-populaties in de Sentinel, die immers de operationele uitdrukking zijn van wat we willen.

Ik postuleer dat dit de volgende regel is:

factuurOK = I  /\  -factuurRegel ! ( (I /\ regelText;regelText~); factuurRegel~ )


waarbij factuurRegel~ vervangen zou mogen worden door V. De precieze verwoording van deze regel is als volgt:

Een factuur is OK dan en slechts dan als:
( voor elke Regel die er maar bestaat het volgende geldt:
  ( deze Regel is GEEN factuurRegel op die factuur
  of:
    ( deze Regel is WEL een factuurRegel op die factuur,
    en
      heeft bovendien de eigenschap dat hij is voorzien van een TEXT inhoud.
) ) )


En deze blijkt ook te doen wat de bedoeling is.

—
Reply to this email directly or view it on GitHub<https://github.com/AmpersandTarski/ampersand/issues/59#issuecomment-91206515>.

________________________________
Deze e-mail is uitsluitend bestemd voor de geadresseerde(n). Verstrekking aan en gebruik door anderen is niet toegestaan. Open Universiteit sluit iedere aansprakelijkheid uit die voortvloeit uit elektronische verzending. Aan de inhoud van deze e-mail en/of eventueel toegevoegde bijlagen kunnen geen rechten worden ontleend.

This e-mail is intended exclusively for the addressee(s), and may not be passed on to, or made available for use by any person other than the addressee(s). Open Universiteit rules out any and every liability resulting from any electronic transmission. No rights may be derived from the contents of this message.


Disclaimer
Dit bericht met eventuele bijlagen is vertrouwelijk en uitsluitend bestemd voor de geadresseerde. Indien u niet de bedoelde ontvanger bent, wordt u verzocht de afzender te waarschuwen en dit bericht met eventuele bijlagen direct te verwijderen en/of te vernietigen. Het is niet toegestaan dit bericht en eventuele bijlagen te vermenigvuldigen, door te sturen, openbaar te maken, op te slaan of op andere wijze te gebruiken. Ordina N.V. en/of haar groepsmaatschappijen accepteren geen verantwoordelijkheid of aansprakelijkheid voor schade die voortvloeit uit de inhoud en/of de verzending van dit bericht.

This e-mail and any attachments are confidential and are solely intended for the addressee. If you are not the intended recipient, please notify the sender and delete and/or destroy this message and any attachments immediately. It is prohibited to copy, to distribute, to disclose or to use this e-mail and any attachments in any other way. Ordina N.V. and/or its group companies do not accept any responsibility nor liability for any damage resulting from the content of and/or the transmission of this message.

**Comment by Oblosys** [comment]
Ah, ik zie nu dat ik
```
factuurOK = I  /\  -factuurRegel ! ( (I /\ regelText;regelText~); factuurRegel~ )
```
las als de definitie van regel factuurOK, met een `I` conjunct, maar het is natuurlijk een gewoon equivalentie expressie voor relatie factuurOK, die helemaal niet tot top-level `I` conjuncten leidt. Negeer mijn bovenstaande stukje over de `I`'s dus maar (stukje over testRule is nog wel interessant).

**Comment by RieksJ** [comment]
Stef, 

Jouw verhaal bij factuurOK' kan ik niet goed volgen omdat ik (nog) geen concrete (en vooral ook: eenvoudige) zinnen heb bij residuen zoals ik die wel heb bij `r[A*B];s[B*C]` (_voor elke (a,c) is er een b waarvoor geldt r(a,b) en s(b,c)_), en dus ook niet kan nagaan of wat je al handenzwaaiend zegt enige basis heeft (al vertrouw ik je natuurlijk op je woord).

Ik heb jouw formulering getest op de database, als volgt:

1. Ik ga uit van het bestand in `Git\ampersand-models\NewFrontend\DaggerExample.adl`. Dit bestand gaat weliswaar over Orders ipv Facturen, maar het idee is hetzelfde. Er zit ook een INTERFACEje in zodat je er wat mee kunt spelen.
2. Ik heb het bestand gecompileerd om zeker te weten dat er geen overtredingen in zitten.
3. Ik heb de volgende text toe (binnen het PROCESS) toegevoegd, die het equivalent is van de door jou genoemde regels (vertrouw daar maar op):

        RULE: orderOK = I[Order] /\ (lineInOrder\lineText);lineInOrder~

3. Als ik dit bestand compileer zie ik een overtreding, wat voor mij laat zien dat jouw regel niet equivalent is met de mijne.

Helaas...

P.S.: Tegen de tijd er een mogelijkheid is om vanuit prototypes jullie code aan te roepen die van een RA-expressie SQL maakt, dan zou `DaggerExample` makkelijk kunnen worden uitgebreid met een interface waarin je met verschillende expressies en populaties kunt experimenteren.
