### ISSUE TITLE
EURent does not compile with Ampersand-v3.7.3 [development:c2fabc7]

### ISSUE THREAD

**Issue by stefjoosten** [AmpersandTarski/Ampersand#592]
I have tried installing ampersand-models\ZwolleFrontEnd\EURent in commit @285edb675e04a41edffdcb638163aee03e628bfd with Ampersand-v3.7.3 [development:c2fabc7]. That is the version with PURPOSE++. However, EURent no longer compiles.

![image](https://cloud.githubusercontent.com/assets/275768/21292238/e59b1712-c4fd-11e6-8da7-cd7f1fb152df.png)

@hanjoosten: Would it be an idea to let compilation of EURent be part of the Travis test in the development branch?

**Comment by hanjoosten** [comment]
@stefjoosten : If you create links to a specific branch (as you did above), please make sure it works!

**Comment by RieksJ** [comment]
fixed in commit 92615f1

**Comment by WolframKahl** [comment]
> Would it be an idea to let compilation of EURent be part of the Travis test in the development branch?

I think this is a very good idea.

A related setup to possibly keep in mind with this is the AFP (Archive of Formal Proofs) of the Isabelle theorem prover: Once a development has been accepted into the AFP (which tries to be something of a journal at the same time as a repository of working theory developments), the duty to keep them working with changes in Isabelle is on those who make those changes.

**Comment by stefjoosten** [comment]
EUrent produces a violation message of rule "At least one account must exist that is active" (file: SIAM_Login.adl, line 45). After disabling that rule, I get a deep error, saying:
"API call not found: GET http://localhost/AmpersandPrototypes/EURent/api/v1/AmpersandPrototypes/EUrent/api/v1/sessions/5i5i0qjge4bqgb7amvl20aj2p2/navbar"
![image](https://cloud.githubusercontent.com/assets/275768/25118862/3e33744a-2418-11e7-8cff-4be79f9d75ee.png)

I think we need to become serious about taking EUrent to Travis. What is required to get that done?
