### ISSUE TITLE
Issue on installing RAP3

### ISSUE THREAD

**Issue by MvanRooijen** [AmpersandTarski/Ampersand#593]
In the manual the following command is given to install RAP3:
`ampersand.exe --meta-tables --add-semantic-metamodel --verbose  -p"D:\xampp\htdocs\RAP3\" RAP3.adl` 

I've changed this so the path to xampp matches the one on my system. 
However, I get the error;
ampersand.exe: unrecognized option `--add-semantic-metamodel'

I am guessing I've done something wrong but what can I do to fix this?
My current version of Ampersand is:
Ampersand-v3.7.2 [HEAD:d836f4c], build time: 28-Oct-16 08:46:34 Coordinated Universal Time

**Comment by MvanRooijen** [comment]
with the new (al beit developement version of Ampersand 3.7.3) I get the following errors:

`C:\xamp\htdocs\RAP3>ampersand.exe --meta-tables --add-semantic-metamodel --verbose RAP3.adl
Ampersand-v3.7.3 [development:c2fabc7], build time: 18-Dec-16 08:59:45 W. Europe Standard Time
Reading file AST.adl (from within ampersand.exe)
Reading file Concepts.adl (from within ampersand.exe)
Reading file Contexts.adl (from within ampersand.exe)
Reading file Relations.adl (from within ampersand.exe)
Reading file Documentation.adl (from within ampersand.exe)
Reading file Rules.adl (from within ampersand.exe)
Reading file Expressions.adl (from within ampersand.exe)
Reading file Views.adl (from within ampersand.exe)
Reading file RAP3.adl
Reading file SIAM_importer.adl
Reading file ..\Sequences\SeqOntology.adl
Reading file Scripts.adl
Reading file Scripts.docadl
Reading file Scripts.ifc
Reading file Analyse.ifc
Error at symbol () in file RAP3.adl at line 4 : 4
  While looking for file '..\Sequences\SeqOntology.adl':
    File does not exist.
==============================
Lexer error at line 86:11, file Scripts.adl
  Unterminated markup section. (any text between `{+` and `+}` ).
==============================
Lexer error at line 36:11, file Scripts.docadl
  Unterminated markup section. (any text between `{+` and `+}` ).
==============================
Error at symbol () in file RAP3.adl at line 4 : 4
  While looking for file '..\Sequences\SeqOntology.adl':
    File does not exist.
==============================
Lexer error at line 86:11, file Scripts.adl
  Unterminated markup section. (any text between `{+` and `+}` ).
==============================
Lexer error at line 36:11, file Scripts.docadl
  Unterminated markup section. (any text between `{+` and `+}` ).
==============================
Error at symbol () in file RAP3.adl at line 4 : 4
  While looking for file '..\Sequences\SeqOntology.adl':
    File does not exist.
==============================
Lexer error at line 86:11, file Scripts.adl
  Unterminated markup section. (any text between `{+` and `+}` ).
==============================
Lexer error at line 36:11, file Scripts.docadl
  Unterminated markup section. (any text between `{+` and `+}` ).`

Hope this helps

**Comment by hanjoosten** [comment]
just get the new stuff I released this morning.

**Comment by MvanRooijen** [comment]
Getting a lot further on installing the RAP 3, still some issues though.

I've attached the error in a text file for better readability
[error rap3 install.txt](https://github.com/AmpersandTarski/Ampersand/files/662967/error.rap3.install.txt)

**Comment by MvanRooijen** [comment]
Newest release fixes all! Thanks, will close the issue

**Comment by hanjoosten** [comment]
You are still using ampersand v 3.7.x . Please use v 3.8.0, that was released today.

**Comment by MvanRooijen** [comment]
newest version solved the issue. thanks!
