### ISSUE TITLE
DUPLICATE KEY UPDATE may cause `InsPair: Oops.. something went wrong`-error

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/Ampersand#599]
This ticket may be related to #486 and/or #508.

To reproduce this error, 

- checkout the XPath application from ampersand-models, commit [3fb9616] (22 dec 2016);
- compile `XPaths.adl`;
- uncomment the debugging configuration flag in `localSettings.php`
- install the database with the default population
- search in the debug logfile for `DUPLICATE KEY UPDATE` (or `Oops`).

**Comment by hanjoosten** [comment]
Issue #486 has been resolved. We now get another error message. The database can be created when the rule "Create XPaths for non-root Properties" is disabled. Also the interfaces then work (not the rule, of course).

**Comment by Michiel-s** [comment]
Problem has nothing to do with the distinct statement.

The problem lies in the generated relation definition for xpIPO[XPath*XPath] in relations.json. The combination of attributes `tableOf`, `srcCol` and `tgtCol` does not make sense.

This issue is for @hanjoosten and me to make stricter arrangements according to the database table column assignments.

```json
"signature": "xpIPO[XPath*XPath]",
        "sur": false,
        "mysqlTable": {
            "tableOf": "src",
            "srcCol": {
                "null": true,
                "unique": false,
                "name": "xpIPO"
            },
            "tgtCol": {
                "null": false,
                "unique": true,
                "name": "XPath"
            },
            "name": "XPath"
        },...
```

debug info: query that is being executed is: 
```sql
UPDATE `XPath` SET `XPath` = 'XPath_1483720101_00705406' WHERE `xpIPO` = 'XPath_1483720101_00649400'
```
this must be:
```sql
UPDATE `XPath` SET `xpIPO` = 'XPath_1483720101_00705406' WHERE `XPath` = 'XPath_1483720101_00649400'
```

**Comment by hanjoosten** [comment]
The relation xpIPO is INJ, hence it is stored flipped. Therefor, if (XPath_1,XPath_2) is inserted into the relation xpIPO, the sql query should be:

```sql
UPDATE `XPath` SET `xpIPO` = 'XPath_1' WHERE `XPath` = 'XPath_2'
```
In the information in the Haskell structure, where the relation is stored, it says that the relation is stored flipped:

```.haskell
          sqlAtt_xpIPO
           = Att { attName    = "xpIPO"
                 , attExpr    = EFlp (EDcD rel_xpIPO_XPath_XPath)
                 , attType    = OBJECT
                 , attUse     = ForeignKey cpt_XPath
                 , attNull    = True
                 , attDBNull  = True
                 , attUniq    = False
                 , attFlipped = True
                 }
```

This is currently not taken into account in the json file. 
@Michiel-s , What would you like to be generated in the json file in this case? Is an extra attribute required? (e.g. a boolean storedFlipped? )

**Comment by Michiel-s** [comment]
I'll come with a proposal.

**Comment by Michiel-s** [comment]
Probably caused by the same error as #864 and #862
