### ISSUE TITLE
Discrepancies in Limorange edit behavior between old and new front-ends

### ISSUE THREAD

**Issue by Oblosys** [AmpersandTarski/ampersand#60]
The ampersand-models/ISAtest/Limorange.adl example shows a number of differences between the old and the new frontends. (Some of these may be intentional because of the slightly different edit model.) All issues mentioned below are in the `Person` interface for atom `martijn`.

- [x] `ownsLimes` is not editable in new front-end, whereas the old front-end allows editing on two levels: add/remove on limes and add/remove/modify on `limeProperties` for each lime.
edit: will be addressed, see ticket #141 

- [x] Remove/add in `ownsCitrus;I[Orange]` does not have any effect in the new front-end. In the old front-end this is editable, even though for --dev deletions don't display correctly until the page is saved (probably due to a styling problem for crossing out underlined atoms).

- [x] In the old front-end new atoms can be created by typing them in the edit field, which causes insertion in the concept tables of the field's target concept and its superconcepts. In the new front-end only existing atoms may be entered. This may be intended behavior though.
edit: will be addressed, see ticket #141 

- [x] ~~The `+` menu button only supports 'New Person' and 'New Lime', but does not allow creation of atoms for the other concepts (Nectarine, Citrus, Orange, Limorange, and Lemon)~~
edit: that's because there are no interfaces specified for those other fruits

- [x] Sometimes on clicking on atoms or in fields the browser log shows `"selected id is undefined" Person.js:84:6`

**Comment by stefjoosten** [comment]
Hoi Michiel,
Ik denk dat je bovenstaande wel wilt weten. Het gaat hier om editfunctionaliteit i.v.m. specialisatie (de limes&orange casus zit vol met CLASSIFY statements.)

**Comment by Michiel-s** [comment]
I've edited the original comment of Martijn. A couple of things are already fixed. Aspects regarding edit functionality are addressed by ticket #141
