### ISSUE TITLE
Autoload config yaml file with same filename as entry script

### ISSUE THREAD

**Issue by Michiel-s** [AmpersandTarski/Ampersand#600]
This issue request to autoload a config yaml file (if exists in same folder) with the same filename as the entry script.

If the yaml file exists, the following 2 commands should have the same effect:
`ampersand.exe script.adl`
`ampersand.exe script.adl --config=script.yaml`

The check if the script.yaml file exists should only result in an error when it is explicitly mentioned on the command line.

**Comment by hanjoosten** [comment]
This has been fixed. The implementation is now that there can only be a single configuration file. Iff a configuration file is requested by use of the --config switch, that file is taken. An error will follow if that file doesn't exist, or if it is not a proper yaml configuration file. If no --config swich is given, and there exists a .yaml file with the same name as the .adl file that is being compiled, that file is taken as the configuration file.

**Comment by Michiel-s** [comment]
Many many thanks. This really saves me a lot of work and having different batch files for different processes.
