### ISSUE TITLE
Clear out one normalizer

### ISSUE THREAD

**Issue by stefjoosten** [AmpersandTarski/Ampersand#603]
Currently we have two normalizers. The old normalizer has a fixed set of rewrite rules, which are traversed in one direction only. The new normalizer has a variable set of rewrite rules and a cost function to decide how to use the rewrite rules. Both normalizers terminate.

The problem is that these normalizers pollute the code. Only one normalizer should suffice. Currently we are doing an experiment to get some more useful info.

**Comment by hanjoosten** [comment]
When I tried to get rid of the new normalizer, it turned out that it is still used. It is used to produce proofs.
