### ISSUE TITLE
Renaming relations and concepts feature request

### ISSUE THREAD

**Issue by stefjoosten** [AmpersandTarski/Ampersand#606]
# Problem description
When re-using things from other modules (See #605), renaming can be necessary. Reasons for this may be that the module in which re-used things are being used uses different conventions for naming, or that the name of a thing is already used. Also, in order to enable others to re-use the module, it is desirable to leave the imported module unchanged.

**Comment by stefjoosten** [comment]
# Way of Working
First we will make the naming mechanism visible in Ampersand. This is meant for inclusion in FormalAmpersand. Once that is satisfactory, we can do the same in Haskell in the code of the Ampersand compiler.

**Comment by Michiel-s** [comment]
I propose to take this issue together with #850. There we talk about introducing file scoped namespaces. The `import .. as ..` is perfectly suited to rename/alias concepts, relations and other objects within the scope of a file and leaves the imported module unchanged.
