### ISSUE TITLE
Make SQL-generator universal

### ISSUE THREAD

**Issue by stefjoosten** [AmpersandTarski/Ampersand#607]
# Problem description
In Travis, https://travis-ci.org/AmpersandTarski/Ampersand/jobs/187301035, you can see generation of SQL-code with the new normalizer switched on. From the bunch of errors produced, it is obvious that the Ampersand needs the (old) normalizer to produce correct code.

The SQL-generator apparently makes assumptions, which are fulfilled by the old normalizer. In order to make Ampersand independent of any normalizer, we want the SQL-generator to produce correct code for any conceivable `Expression`.
# Analysis

**Comment by sjcjoosten** [comment]
After turning the normalizer off all-together, there seems to be no problem anymore. This suggests that the problem is not in the SQL generator. Feel free to reopen if there is a better diagnosis.
