### ISSUE TITLE
Jumpy and overlapping layout for Limorange in new front-end

### ISSUE THREAD

**Issue by Oblosys** [AmpersandTarski/ampersand#61]
In the `Person` interface of ampersand-models/ISAtest/Limorange.adl  (on my machine `http://localhost/AmpersandInSites/Limorange/#/Person/martijn`), interface labels overlap with the atom values:

![screen shot 2015-04-09 at 17 28 09](https://cloud.githubusercontent.com/assets/1735040/7072342/c64c1fb8-deeb-11e4-9d0d-9e5c8be47f04.png)

This interface also shows how having the layout change on mouse-over events may cause problems. If you you scroll down and try to edit in the `ownsLimes;I[Orange]` fields, the page changes considerably, and you will have to scroll down again to see the field again.

**Comment by RieksJ** [comment]
When there is a fix for an issue, it should be closed.

**Comment by Michiel-s** [comment]
The jumpy part is not fixed yet
