### ISSUE TITLE
Problems with generalizations anticipated in the backend.

### ISSUE THREAD

**Issue by stefjoosten** [AmpersandTarski/Ampersand#613]
I have been trying to find out how the relation `pop[Atom*Class]` from FormalAmpersand is represented in the backend.

The object model of the backend defines class `Atom` in module Atom.php. The only attribute that relates to `Concept` is  `$concept`. The comment of this attribute says "Specifies the concept of which this atom is an instance". That statement is not valid, because there is no such thing as "THE concept of which an atom is an instance". There are multiple of such concepts.

So is this a problem, other than that the backend deviates from FormalAmpersand? For the theory behind this, please study the RAMiCS paper [Type Checking by Domain Analysis in Ampersand.pdf](https://github.com/AmpersandTarski/Ampersand/files/706054/2015.RAMiCS.Type.Checking.by.Domain.Analysis.in.Ampersand.pdf). In practice we have little experience with generalizations in the user interface. That might explain why this problem has not shown up in any diagnosis yet. I would expect that to show up, because this issue appeared nontrivial on the database side as well. Since I have no instance of this yet, I can only say that I anticipate similar problems once we make applications that make extensive use of generalization.

Maybe, however, I am reading in the wrong place and `pop[Atom*Class]` is represented in another way in the backend....

**Comment by hanjoosten** [comment]
I don't think there is a problem with the current implementation. Any atom is stored in what we call the concepttable. However, all concepts that are related by means of generalisation/specification relations, are stored in a single concepttable. So an atom is implemented as a single row in that table. 
Of course, it could well be that I don't get your point. lets talk about this by phone somewhere this week.

**Comment by stefjoosten** [comment]
How is the relation pop[Atom*Class] from FormalAmpersand represented in the backend?

**Comment by stefjoosten** [comment]
I think this might be it: let `$a` be an `Atom`, then all concepts in `pop[Atom*Class]` are computed by:
~~~~~~~~~
$a->concept->getGeneralizations()
~~~~~~~~~

**Comment by Michiel-s** [comment]
> I think this might be it: let $a be an Atom, then all concepts in pop[Atom*Class] are computed by:
$a->concept->getGeneralizations()

That's the function indeed to get a lists of all concepts the atom is an instance. For practical purposes, the atom in instantiated in the backend by its smallest concept. Then you have all the information you need.

Issue can indeed be closed. I don't see any problem.
