### ISSUE TITLE
Duplicate, identical definitions in FSPEC

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/Ampersand#617]
When generating an fspec for the TText stuff (which is in the Ampersand Models repo), I find that the following text gets generated:

![image](https://cloud.githubusercontent.com/assets/8522589/22010912/6c6935a8-dc8c-11e6-9d7b-bf96209cae2b.png)

I consider this a bug, as I expect the fspec-generator to distinguish between two definitions of a single term that have the same description and those that do not. One use case for having multiple occurances of the same definition of a term in (different) source code (files) is to assist readers of the that source code.

**Comment by hanjoosten** [comment]
This is a feature: When something (in this case a Concept) is defined n times, all those n definitions are shown, regardless of the properties of that definition, like the text.

**Comment by hanjoosten** [comment]
I fixed this. When the text of both definitions of the same concept is equal (string compare, not intent compare ;) ), AND the references are (exactly) the same, when they exist, then the definitions are regarded as a single one. If the comparison isn't exact, they both will show in the document.
