### ISSUE TITLE
!fatal without a call site: Option --fpa-excel is broken

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/Ampersand#621]
Compiling various applications (e.g. SIAM, HelloWorld as exist in the Ampersand repo),
using Ampersand-v3.8.0 [development:3886c61], which ( built on January 9th) 
with the `--fpa-excel` option gives a fatal. 

Here is what I copied from my DOS box:
~~~
ampersand.exe SIAM.adl  -p"C:\xampp\htdocs\GENDIR"  --fpa-excel

!fatal without a call site (check Version.hs to add a call site)
             Ampersand-v3.8.0 [development:3886c61]
             error nr: 78
  TODO: fix to see if the interface contains editalbe fields
~~~
I have tried this with other stuff, which result in the same error (meaning that it does not depend on SIAM).

**Comment by hanjoosten** [comment]
Because of ongoing work wrt Interfaces, the FPA analisys has bitrotted quite some time ago. FPA analisys should be built up from the ground. Until that happens, --fpa-excel will be discontinued.

**Comment by hanjoosten** [comment]
The fatal doesn't happen any more, because of the disabling of the switch.
