### ISSUE TITLE
Robustness of Rules

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/Ampersand#623]
The theory of declarative rules says that the order in which rules are being evaluated should not matter.
In practice, it does.

One of the rule-evaluation ordering mechanisms is the transaction. Another might be called 'Services' (meaning that when rules that are part of a service get evaluated (randomly), rules that are not part of that service do not).

How about implementing an option in the backend for randomly changing the order in which rule violations are being computed? Perhaps also an integer that specifies that this has to be done multiple times, to see if that provides the same violations? 

I think this feature will be very instructive for users that want to write better rules.

**Comment by hanjoosten** [comment]
What is this about? Could you give an example of what you mean? To me, this sounds rather vague.

**Comment by Michiel-s** [comment]
No update for 2 years. And i’m not implemeting such a feature. It had negative impact on maintainability of code and no clear use case.
I’ll close this issue
