### ISSUE TITLE
Merge Atoms

### ISSUE THREAD

**Issue by stefjoosten** [AmpersandTarski/Ampersand#624]
I have included functionality for merging atoms in InsDelPairAtom.php. You can find the results in commit ampersand@37401f2a9fe660646b7b799b6307ed511b6254db and ampersand-models@8de1a8b254dc4812ac8356f8ce73f522827045e9. The intended semantics is that violation of a rule that checks the identity of two atoms can be fixed by the ExecEngine. It will put the union of all pairs of both atoms into one atom (thereby unifying all properties in the eyes of the user).

If you run the test program "TestMergeAtoms" (see below), this is what you may get.
![image](https://cloud.githubusercontent.com/assets/275768/22336711/6eb43cdc-e3e3-11e6-8326-6ba64c535e1e.png)

# Semantics
The intention of PHP-function `MrgAtoms` is to turn two atoms into one.
The purpose is to resolve a violation of two atoms being the same (e.g. violation of univalence).
It takes 4 arguments: source type, source atom, target type and target atom.
After the call, the source atom has obtained all properties of the target atom in addition to what it already had. The target atom has vanished. The following program shows its use.
~~~~~~
CONTEXT TestMergeAtoms

RELATION ssn[Person*SocialSecurityNumber] [UNI]

ROLE ExecEngine MAINTAINS Person
RULE Person : ssn;ssn~ |- I
VIOLATION (TXT "{EX} MrgAtoms;Person;", SRC I, TXT ";Person;", TGT I )

INTERFACE Persons : I[SESSION] cRud
BOX [ persons : V[SESSION*Person] CRuD
      COLS[ id : I[Person] cRud
          , ssn : ssn
          ]
    ]

ENDCONTEXT
~~~~~~

**Comment by Michiel-s** [comment]
Looks like the functionality works as expected and described. I don't experience any bugs. Feel free to reopen the issue if necesarry
