### ISSUE TITLE
INCLUDE path comparison does not work

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/Ampersand#625]
The current way in which modules can be created, is by allowing files to INCLUDE other files (on which they depend). An example is:
~~~
INCLUDE ../SIAM/SIAM_PersonReg.adl
~~~
If files in modules depend on other files in said module, this mechanism can be used as well.
However, including stuff from different locations leads to errors such as:
~~~
==============================
Error at symbol () in file C:\Ampersand\git\tno-models\SIAMv3\..\SIAMv3\..\SIAMv3\SIAM_PersonReg.adl at line 51 : 1
  Names / labels must be unique. "Auto maintain 'personRef' relation", however, is used at:
    line 51:1, file C:\Ampersand\git\tno-models\SIAMv3\..\SIAMv3\..\SIAMv3\SIAM_PersonReg.adl
    line 51:1, file C:\Ampersand\git\tno-models\SIAMv3\..\SIAMv3\SIAM_PersonReg.adl.
==============================
~~~
Obviously, whatever it is that is defined in these 'different' files is not different, but exactly the same. In this case, the complaint is about a double-defined label of a rule, but there may be other kinds of 'differences' that are actually the same.

One way to resolve this particular issue is to determine whether 'different' files are in fact actually different, by transforming the path to its canonical form before using it in a comparison (or even loading it).

Another way is to check for 'real differences'...

**Comment by RieksJ** [comment]
SIAMv3 awaits the fixing of this bug

**Comment by hanjoosten** [comment]
This request does not take symbolic links into account. In general, the files in the above example do not have to be the same files at all. See [this blog post](http://neilmitchell.blogspot.nl/2015/10/filepaths-are-subtle-symlinks-are-hard.html) for details. 
However, if we assume that symlinks aren't used currently, the request seems valid, so I fixed it. From now on, Ampersand does not support INCLUDE with files that have symbolic links in their paths.  (it might work, but it is not guaranteed)

**Comment by RieksJ** [comment]
Sorry @hanjoosten, but the bug has not gone. I used `Ampersand-v3.8.1 [development:7f81b93], build time: 01-Feb-17 16:58:19` to compile this stuff again, and get the same error messages.

**Comment by RieksJ** [comment]
Seems to work. Thanx
