### ISSUE TITLE
DB property query performance

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/Ampersand#628]
### PROBLEM
In the MPTrx project, I have encountered a situation that caused the database to take indefinitely (that is: the execution needed to be terminated by hand). @Michiel-s and I think this is a time-bomb that will go off as the use of properties in our models increases. 

Here is one example (from MPTrx) that would cause the problem. As you can see there are many property relations, both explicit (`ttAccept`, `mptrxIsAcceptable`, `concernIsAddressed`) and hidden ones that are used to make sure we have the right class (`I[MPTrx]`, `I[Concern]`):
```adl
ttScope :: TText * Scope [UNI,TOT]
ttAccept :: TText * TText [PROP] -- TText has been given a valid value

CLASSIFY MPTrx ISA Scope
CLASSIFY Concern ISA TText
mptrxIsAcceptable :: MPTrx * MPTrx [PROP]
concernIsAddressed :: Concern * Concern [PROP]

ROLE ExecEngine MAINTAINS "Detect MPTrx is acceptable"
RULE "Detect MPTrx is acceptable": 
   I[MPTrx] /\ -(ttScope~;(I[Concern] /\ (ttAccept-concernIsAddressed));ttScope)
                 /\ ttScope~;(I[Concern] /\ ttAccept);ttScope
   |- mptrxIsAcceptable
MEANING "All criteria in the MPTrx are satisfied"
```
### ANALYSIS
The resulting query is way too large (a good reason for not showing it in this ticket). @Michiel-s's analysis showed that it could be dramatically reduced if the characteristics of property-relations can be taken into account when generating queries. The example provided further down gives you an idea of what this is about.

### WHY OPTIMIZING FOR USING PROPERTIES IS IMPORTANT 
We will be see an increasing use of property-like relations, for reasons such as:
- an increase in the use of `CLASSIFY`-statements will increase the need to use `I[Specialization]` constructs in expressions (as is the case in the example provided above). The foreseen support for `MODULE`s will further increase this need.
- as we become better at specifying interfaces, we will be needing state-machines for navigation through screens (example: newer versions of SIAM login). 
- when we will be using `SERVICE`s, we will be needing service-requests (e.g. to reset objects, currently already used in SIAM and TTexts), that are conveniently modeled as properties.

As properties will be defined more often, and will appear in rules more often, and as rules (in particular those with classification-dependencies) become more complex, the corresponding MySQL code will become much more complex, and is more likely to 'explode' as it did in the MPTrx case.

### SIMPLE EXAMPLE OF OPTIMIZATION
Consider the following script
```adl
CONTEXT Bug628
  r :: A * A [PROP]
  s :: A * A [PROP]
 RULE r /\ I[A] |- s
ENDCONTEXT
```
The MySQL code that is generated for the conjuct query is as follows:
```sql
select
  distinct
         someDummyNameBecauseMySQLNeedsOne.src as src,
         someDummyNameBecauseMySQLNeedsOne.tgt as tgt
  from (
        select subIntersect0.src as src, subIntersect0.tgt as tgt
        from (select "A" as src, "r" as tgt
              from "A"
              where ("A" is not null)
                    and ("r" is not null)
             ) as subIntersect0,
             (
              select t1.src as src, t1.tgt as tgt
              from (
                    select "A" as src, "A" as tgt from "A" where "A" is not null)
                   as t1
                   left join "A" as t2
                   on (t1.src = t2."A")
                      and (t1.tgt = t2."s")
              where (t2."A" is null)
                    or (t2."s" is null)
            ) as subIntersect1
        where (subIntersect1.src = subIntersect0.src)
              and (subIntersect1.tgt = subIntersect0.tgt))
       as someDummyNameBecauseMySQLNeedsOne
```

Optimization step 1: 
subIntersect1 concerns two properties (i.e. I[A] and s). Therefore the left join in subIntersect1 can be rewritten to a single where clause as follows:
```sql
select
  distinct
         someDummyNameBecauseMySQLNeedsOne.src as src,
         someDummyNameBecauseMySQLNeedsOne.tgt as tgt
  from (
        select subIntersect0.src as src, subIntersect0.tgt as tgt
        from (select "A" as src, "r" as tgt
              from "A"
              where ("A" is not null)
                    and ("r" is not null)
              ) as subIntersect0,
             (
              select "A" as src, "A" as tgt
              from "A"
              where ("A" is null)
              and ("s" is null)
            ) as subIntersect1
        where (subIntersect1.src = subIntersect0.src)
              and (subIntersect1.tgt = subIntersect0.tgt))
       as someDummyNameBecauseMySQLNeedsOne
```

Optimization step 2: 
someDummyNameBecauseMySQLNeedsOne table concerns two properties (i.e. r and (I[A]-s) ). Therefore the join can be rewritten to a single where clause as follows:
```sql
select
  distinct
         someDummyNameBecauseMySQLNeedsOne.src as src,
         someDummyNameBecauseMySQLNeedsOne.tgt as tgt
  from (
        select "A" as src, "r" as tgt
        from "A"
        where ("A" is not null)
        and ("r" is not null)
        and ("s" is null)
    ) as someDummyNameBecauseMySQLNeedsOne
```

Finally, because there is no intersect anymore, the `someDummyNameBecauseMySQLNeedsOne` table is also not needed anymore. Resulting in:
```sql
select distinct "A" as src, "r" as tgt
from "A"
where ("A" is not null)
and ("r" is not null)
and ("s" is null)
```

**Comment by hanjoosten** [comment]
This seems like a good idea, however, there is a class of expressions that is involved. In fact, a property relation `r[A*A]` denotes a subset of the set `A`. This goes for all property relations. 
If a rule is built of only property relations on some concept C, we are in the domain of set theory, I guess. 
Violations would always be pairs where the src and tgt are equal. In such a case it is easy to see that 

If R is a subset of A, and S is a subset of A, your rule could be written as:
forall a: If a is an element of R, then it must be an element of S. 
violations would obviously be all elements in R that are not in S. 
That would lead to the sql:
```sql
select distinct "A" as src, "A" as tgt
from "A"
where  ("r" is not null)
and ("s" is null)
```
This is not something we should quickfix in the sql generator. We should cave out this class of expressions in a nomalizer sort of way, I think. Any ideas on this, @sjcjoosten ?

**Comment by RieksJ** [comment]
I have added the labels 'bug' and 'priority' to make clear that this issue is becoming an increasing bother to me.

**Comment by stefjoosten** [comment]
@hanjoosten Could it be that this occurs since we have switched off the normalizer? We did that because the distributive property caused a combinatorial explosion. But of course, we could reinstate the normalizer without the distributive property. Does that sound like a solution?

**Comment by hanjoosten** [comment]
IT is a good idea iff it is guaranteed that there are no loops in the normalizer rules

**Comment by RieksJ** [comment]
We are increasingly often running into this problem, and it is reaching the point of becoming unacceptable in some projects. That's why I have increased the priority. @stefjoosten and @sjcjoosten: could you have a look at this soon?

**Comment by stefjoosten** [comment]
I ran an experiment on the expression Rieks showed in `CONTEXT Bugxxx`.

The rule on line 4:7 has 
Expression: `r[A*A] /\ I[A] |- s[A*A]`
conjNF: `-r[A*A] \/ -I[A] \/ s[A*A]`
conj: `-r[A*A] \/ -I[A] \/ s[A*A]`

So whether we switch the normalizer on or off will have no effect on this one.

**Comment by stefjoosten** [comment]
The requested optimization is about properties. We can recognize this by the presence of `/\I[A]` in the expression. I am not aware (currently) which theory helps us with this. Maybe Jaap van der Woude has some ideas how we might handle this. He is quite proficient in manipulating in the homogeneous world. Let me ask him.

**Comment by sjcjoosten** [comment]
Here's my bit of manipulation of the `violations` expression:

``viol = -(r /\ I[A] |- s)``

First, let's use that r is prop, so ``r |- I[A]``

``viol = -(r |- s)``

Next, we move the unary ``-`` inwards, and rewrite the unary complement into a binary one:

``viol = r /\ -s = r - s``

If we translate this into mysql naively, we should directly get the optimal expression. This shows that we can do these optimisations on the RA side (yay!). However, there are a couple of difficulties:
- The above analysis shows we can manually do the optimisations, not that how to do them.
- The rule ``-V = r /\ ((-s) - I[A])`` is also equivalent to ``r /\ I[A] |- s``, but now it's even harder to see how we would optimise it (automatically).
- In general, these optimisations might not be achievable automatically (RA is undecidable). We also need to think about allowing the user to write optimised queries. Maybe the diagnosis chapter (or something similar) should contain lists of propositions that an Ampersand user needs to prove do in order to know that the optimised code is equivalent to non-optimised but more straightforward one.

**Comment by RieksJ** [comment]
While the example uses properties all over the place, I have experienced poor performance in the more general case that has the form `I[A] /\ r1;r1~ /\ r2;r2~ /\ r3;r3~ ... /\ rn;rn~`; if `A` has some 4+ atoms, and many relations with source concept `A`, performance can become dramatic. The current workaround is to limit `n` to 3 (or 4). This is obviously unacceptable, as the semantics of these expressions differs.

**Comment by stefjoosten** [comment]
This particular expression can be simplified. The violations are computed as the complement of the expression that corresponds to `r /\ I[A] |- s`, which is `-(-(r/\I[A]) \/ s)`. This yields:
```
   -(-(r/\I[A]) \/ s)
=
   -(-(r/\I[A])) /\ -s
=
   (r/\I[A]) /\ -s
=
   r /\ -s
=
   r-s
```
This should yield:
```sql
select distinct * from r
except
select distinct * from s
```

**Comment by WolframKahl** [comment]
> This should yield:
> ```sql
> select distinct * from r
> except
> select distinct * from s
> ```

I would naively expect that without the second `distinct` it would be faster.

**Comment by hanjoosten** [comment]
Unfortunatly mysql and mariadb do not support the INTERSECT and EXCEPT operator. I need to see what we can do. [This](http://www.mysqltutorial.org/mysql-intersect/) might help.

**Comment by hanjoosten** [comment]
I made a change in the SQL generator for the case that we have an expression of the form:
```
e0 /\ e1 /\.../\eN, where N >=2
``` 
When generating SQL, the subexpressions `e0` ... `eN` are separated in three disjunct sets:

1.  A set containing all subexpressions of the form `I`. This set must not be empty in order to do the optimization. If it is empty, the `old` sql is used. 
2. A set of all subexpressions of one of the forms:  `r`,  `r~`,  `r;r~`,  `r~;r`, where r is implemented in the same plug as the `I` espression(s) in the first set.
3. A set of all subexpressions not in the first or second set.

A query is constructed for the elements of the first and second set. It is a select statement that selects all elements of the plug where the `I`(s) are in, where all fields that implement one of the `I`(s) or one of the `r`(s) are required to be not null. 
In case that the third set is empty, the above is the right implementation. In case that the third set has elements, sql is generated for the intersection of these subexpressions. This yealds a second sql query. the intersection of both queries is constructed as the result query.

**Comment by hanjoosten** [comment]
@RieksJ , could you please have a look at the performance of above change?

**Comment by Michiel-s** [comment]
This looks promising. Looking forward to check it out. I’ll do this when back from holiday.

**Comment by Michiel-s** [comment]
Finally (sorry!), I've looked into the implementation of @hanjoosten and it really looks like an optimization we're going to enjoy. I haven't checked if the generated queries are correct so I completely trust on the Ampersand generator. But the effect it has on the database performance is of the kind we want. Below my analysis for that:

Given a rule from a script of Rieks:
```adl
RULE "InsPair vaformIsClean":
   I[VerblijfAangifteForm]
   /\ vaform_persoon_Geslachtsnaam;vaform_persoon_Geslachtsnaam~
   /\ vaform_persoon_Voornamen;vaform_persoon_Voornamen~
   /\ vaform_persoon_Geboorteplaats;vaform_persoon_Geboorteplaats~
   /\ vaform_persoon_Geboorteland;vaform_persoon_Geboorteland~ -- deze regel uitcommentarieren zolang issue #628 niet is opgelost
   /\ vaform_persoon_Geslacht;vaform_persoon_Geslacht~ -- deze regel uitcommentarieren zolang issue #628 niet is opgelost
|- vaformIsClean
```
In the non-optimized implementation this would output a query with many joins
```sql
explain select
  distinct
         someDummyNameBecauseMySQLNeedsOne.src as src,
         someDummyNameBecauseMySQLNeedsOne.tgt as tgt
  from (/* `intersect` does not work in MySQL, so this statement is generated: */
        select subIntersect0.src as src, subIntersect0.tgt as tgt
        from (
              select "VerblijfAangifteForm" as src, "VerblijfAangifteForm" as tgt
              from "Form"
              where "VerblijfAangifteForm" is not null)
             as subIntersect0,
             (
              select fence0.src as src, fence1.tgt as tgt
              from (
                    select "VerblijfAangifteForm" as src,
                           "vaform_persoon_Geslachtsnaam" as tgt
                    from "Form"
                    where ("VerblijfAangifteForm" is not null)
                          and ("vaform_persoon_Geslachtsnaam" is not null))
                   as fence0,
                   (
                    select "vaform_persoon_Geslachtsnaam" as src,
                           "VerblijfAangifteForm" as tgt
                    from "Form"
                    where ("VerblijfAangifteForm" is not null)
                          and ("vaform_persoon_Geslachtsnaam" is not null))
                   as fence1
              where (fence0.tgt = fence1.src))
             as subIntersect1,
             (
              select fence0.src as src, fence1.tgt as tgt
              from (
                    select "VerblijfAangifteForm" as src,
                           "vaform_persoon_Voornamen" as tgt
                    from "Form"
                    where ("VerblijfAangifteForm" is not null)
                          and ("vaform_persoon_Voornamen" is not null))
                   as fence0,
                   (
                    select "vaform_persoon_Voornamen" as src,
                           "VerblijfAangifteForm" as tgt
                    from "Form"
                    where ("VerblijfAangifteForm" is not null)
                          and ("vaform_persoon_Voornamen" is not null))
                   as fence1
              where (fence0.tgt = fence1.src))
             as subIntersect2,
             (
              select fence0.src as src, fence1.tgt as tgt
              from (
                    select "VerblijfAangifteForm" as src,
                           "vaform_persoon_Geboorteplaats" as tgt
                    from "Form"
                    where ("VerblijfAangifteForm" is not null)
                          and ("vaform_persoon_Geboorteplaats" is not null))
                   as fence0,
                   (
                    select "vaform_persoon_Geboorteplaats" as src,
                           "VerblijfAangifteForm" as tgt
                    from "Form"
                    where ("VerblijfAangifteForm" is not null)
                          and ("vaform_persoon_Geboorteplaats" is not null))
                   as fence1
              where (fence0.tgt = fence1.src))
             as subIntersect3,
             (
              select fence0.src as src, fence1.tgt as tgt
              from (
                    select "VerblijfAangifteForm" as src,
                           "vaform_persoon_Geboorteland" as tgt
                    from "Form"
                    where ("VerblijfAangifteForm" is not null)
                          and ("vaform_persoon_Geboorteland" is not null))
                   as fence0,
                   (
                    select "vaform_persoon_Geboorteland" as src,
                           "VerblijfAangifteForm" as tgt
                    from "Form"
                    where ("VerblijfAangifteForm" is not null)
                          and ("vaform_persoon_Geboorteland" is not null))
                   as fence1
              where (fence0.tgt = fence1.src))
             as subIntersect4,
             (
              select t1.src as src, t1.tgt as tgt
              from (
                    select fence0.src as src, fence1.tgt as tgt
                    from (
                          select "VerblijfAangifteForm" as src,
                                 "vaform_persoon_Geslacht" as tgt
                          from "Form"
                          where ("VerblijfAangifteForm" is not null)
                                and ("vaform_persoon_Geslacht" is not null))
                         as fence0,
                         (
                          select "vaform_persoon_Geslacht" as src,
                                 "VerblijfAangifteForm" as tgt
                          from "Form"
                          where ("VerblijfAangifteForm" is not null)
                                and ("vaform_persoon_Geslacht" is not null))
                         as fence1
                    where (fence0.tgt = fence1.src))
                   as t1
                   left join "Form" as t2
                   on (t1.src = t2."VerblijfAangifteForm")
                      and (t1.tgt = t2."vaformIsClean")
              where (t2."VerblijfAangifteForm" is null)
                    or (t2."vaformIsClean" is null))
             as subIntersect5
        where (subIntersect1.src = subIntersect0.src)
              and (subIntersect1.tgt = subIntersect0.tgt)
              and (subIntersect2.src = subIntersect0.src)
              and (subIntersect2.tgt = subIntersect0.tgt)
              and (subIntersect3.src = subIntersect0.src)
              and (subIntersect3.tgt = subIntersect0.tgt)
              and (subIntersect4.src = subIntersect0.src)
              and (subIntersect4.tgt = subIntersect0.tgt)
              and (subIntersect5.src = subIntersect0.src)
              and (subIntersect5.tgt = subIntersect0.tgt))
       as someDummyNameBecauseMySQLNeedsOne;
```

The optimized implementation results in:
```sql
explain select
  distinct
         someDummyNameBecauseMySQLNeedsOne.src as src,
         someDummyNameBecauseMySQLNeedsOne.tgt as tgt
  from (/* Combination of optimized and non-optimized intersections */
        /*    Expression: I[VerblijfAangifteForm]/\vaform_persoon_Geslachtsnaam [VerblijfAangifteForm*Geslachtsnaam];vaform_persoon_Geslachtsnaam [VerblijfAangifteForm*Geslachtsnaam]~/\vaform_persoon_Voornamen [VerblijfAangifteForm*Voornamen];vaform_persoon_Voornamen [VerblijfAangifteForm*Voornamen]~/\vaform_persoon_Geboorteplaats [VerblijfAangifteForm*Plaats];vaform_persoon_Geboorteplaats [VerblijfAangifteForm*Plaats]~/\vaform_persoon_Geboorteland [VerblijfAangifteForm*LandOfGebied];vaform_persoon_Geboorteland [VerblijfAangifteForm*LandOfGebied]~/\vaform_persoon_Geslacht [VerblijfAangifteForm*Geslachtsaanduiding];vaform_persoon_Geslacht [VerblijfAangifteForm*Geslachtsaanduiding]~-vaformIsClean [VerblijfAangifteForm] */
        /*    Signature : [VerblijfAangifteForm*VerblijfAangifteForm] */
        select src as src, tgt as tgt
        from (
              select t1.src as src, t1.tgt as tgt
              from (
                    select fence0.src as src, fence1.tgt as tgt
                    from (
                          select "VerblijfAangifteForm" as src,
                                 "vaform_persoon_Geslacht" as tgt
                          from "Form"
                          where ("VerblijfAangifteForm" is not null)
                                and ("vaform_persoon_Geslacht" is not null))
                         as fence0,
                         (
                          select "vaform_persoon_Geslacht" as src,
                                 "VerblijfAangifteForm" as tgt
                          from "Form"
                          where ("VerblijfAangifteForm" is not null)
                                and ("vaform_persoon_Geslacht" is not null))
                         as fence1
                    where (fence0.tgt = fence1.src))
                   as t1
                   left join "Form" as t2
                   on (t1.src = t2."VerblijfAangifteForm")
                      and (t1.tgt = t2."vaformIsClean")
              where (t2."VerblijfAangifteForm" is null)
                    or (t2."vaformIsClean" is null))
             as part2
        where (src = tgt)
              and (src in (select src
                           from (/* Optimized intersection: */
                                 select "VerblijfAangifteForm" as src, "VerblijfAangifteForm" as tgt
                                 from "Form"
                                 where ("VerblijfAangifteForm" is not null)
                                       and ("vaform_persoon_Geslachtsnaam" is not null)
                                       and ("vaform_persoon_Voornamen" is not null)
                                       and ("vaform_persoon_Geboorteplaats" is not null)
                                       and ("vaform_persoon_Geboorteland" is not null))
                                as part1)))
       as someDummyNameBecauseMySQLNeedsOne;
```

**Comment by Michiel-s** [comment]
The above output looks oke!

Unfortunately the last part of the left hand side of the expression `vaform_persoon_Geslacht;vaform_persoon_Geslacht~` is combined with the right hand side `|- vaformIsClean` when creating the conjunct. This part of the conjunct results in `/\vaform_persoon_Geslacht;vaform_persoon_Geslacht~-vaformIsClean`, which causes this part not being optimized (see upper part of the optimized query containing an inner join: fence0 and fence1).

If we add another aspect to the end of the left hand side of the RULE expression (e.g. `/\ vaform_persoon_Geboortedatum;vaform_persoon_Geboortedatum~`), like this: 
```adl
RULE "InsPair vaformIsClean":
   I[VerblijfAangifteForm]
   /\ vaform_persoon_Geslachtsnaam;vaform_persoon_Geslachtsnaam~
   /\ vaform_persoon_Voornamen;vaform_persoon_Voornamen~
   /\ vaform_persoon_Geboorteplaats;vaform_persoon_Geboorteplaats~
   /\ vaform_persoon_Geboorteland;vaform_persoon_Geboorteland~ -- deze regel uitcommentarieren zolang issue #628 niet is opgelost
   /\ vaform_persoon_Geslacht;vaform_persoon_Geslacht~ -- deze regel uitcommentarieren zolang issue #628 niet is opgelost
   /\ vaform_persoon_Geboortedatum;vaform_persoon_Geboortedatum~
|- vaformIsClean
```
We see that the `vaform_persoon_Geslacht` is now also optimized and for the `vaform_persoon_Geboortedatum` an **unnecessary** join is inserted
@hanjoosten do you see a solution for this phenomenon 

```sql
explain select
  distinct
         someDummyNameBecauseMySQLNeedsOne.src as src,
         someDummyNameBecauseMySQLNeedsOne.tgt as tgt
  from (/* Combination of optimized and non-optimized intersections */
        /*    Expression: I[VerblijfAangifteForm]/\vaform_persoon_Geslachtsnaam [VerblijfAangifteForm*Geslachtsnaam];vaform_persoon_Geslachtsnaam [VerblijfAangifteForm*Geslachtsnaam]~/\vaform_persoon_Voornamen [VerblijfAangifteForm*Voornamen];vaform_persoon_Voornamen [VerblijfAangifteForm*Voornamen]~/\vaform_persoon_Geboorteplaats [VerblijfAangifteForm*Plaats];vaform_persoon_Geboorteplaats [VerblijfAangifteForm*Plaats]~/\vaform_persoon_Geboorteland [VerblijfAangifteForm*LandOfGebied];vaform_persoon_Geboorteland [VerblijfAangifteForm*LandOfGebied]~/\vaform_persoon_Geslacht [VerblijfAangifteForm*Geslachtsaanduiding];vaform_persoon_Geslacht [VerblijfAangifteForm*Geslachtsaanduiding]~/\vaform_persoon_Geboortedatum [VerblijfAangifteForm*Datum];vaform_persoon_Geboortedatum [VerblijfAangifteForm*Datum]~-vaformIsClean [VerblijfAangifteForm] */
        /*    Signature : [VerblijfAangifteForm*VerblijfAangifteForm] */
        select src as src, tgt as tgt
        from (
              select t1.src as src, t1.tgt as tgt
              from (
                    select fence0.src as src, fence1.tgt as tgt
                    from (
                          select "VerblijfAangifteForm" as src,
                                 "vaform_persoon_Geboortedatum" as tgt
                          from "Form"
                          where ("VerblijfAangifteForm" is not null)
                                and ("vaform_persoon_Geboortedatum" is not null))
                         as fence0,
                         (
                          select "vaform_persoon_Geboortedatum" as src,
                                 "VerblijfAangifteForm" as tgt
                          from "Form"
                          where ("VerblijfAangifteForm" is not null)
                                and ("vaform_persoon_Geboortedatum" is not null))
                         as fence1
                    where (fence0.tgt = fence1.src))
                   as t1
                   left join "Form" as t2
                   on (t1.src = t2."VerblijfAangifteForm")
                      and (t1.tgt = t2."vaformIsClean")
              where (t2."VerblijfAangifteForm" is null)
                    or (t2."vaformIsClean" is null))
             as part2
        where (src = tgt)
              and (src in (select src
                           from (/* Optimized intersection: */
                                 select "VerblijfAangifteForm" as src, "VerblijfAangifteForm" as tgt
                                 from "Form"
                                 where ("VerblijfAangifteForm" is not null)
                                       and ("vaform_persoon_Geslachtsnaam" is not null)
                                       and ("vaform_persoon_Voornamen" is not null)
                                       and ("vaform_persoon_Geboorteplaats" is not null)
                                       and ("vaform_persoon_Geboorteland" is not null)
                                       and ("vaform_persoon_Geslacht" is not null))
                                as part1)))
       as someDummyNameBecauseMySQLNeedsOne;
```

**Comment by Michiel-s** [comment]
Furthermore, i've noticed that if you put the `I[something]` part of the expression to the end of the right hand side, the optimization isn't applied. 
E.g. when changing only the order of the parts of the RULE expression from above we don't benefit from the optimization:
- [ ] @hanjoosten is this a bug?
```adl
RULE "InsPair vaformIsClean":
   vaform_persoon_Geslachtsnaam;vaform_persoon_Geslachtsnaam~
   /\ vaform_persoon_Voornamen;vaform_persoon_Voornamen~
   /\ vaform_persoon_Geboorteplaats;vaform_persoon_Geboorteplaats~
   /\ vaform_persoon_Geboorteland;vaform_persoon_Geboorteland~ -- deze regel uitcommentarieren zolang issue #628 niet is opgelost
   /\ vaform_persoon_Geslacht;vaform_persoon_Geslacht~ -- deze regel uitcommentarieren zolang issue #628 niet is opgelost
   /\ I[VerblijfAangifteForm]
|- vaformIsClean

-- won't optimize because I[VerblijfAangifteForm] is not at the beginning
```

**Comment by Michiel-s** [comment]
PR #817 is merged, but the two actions stated above still need to be done. We'll keep this issue open until this is fixed.
