### ISSUE TITLE
Populeren van concepten (vervolg van sf ticket 417)

### ISSUE THREAD

**Issue by hanjoosten** [AmpersandTarski/ampersand#63]
Dit is een vervolg op [ticket417 in sourceforge.]( https://sourceforge.net/p/ampersand/tickets/417/ ). Laten we vooral daar geen nieuwe updates meer doen, want dat is erg verwarrend.Indien nodig, dan graag hier op github een nieuw ticket aanmaken, en er dan naar verwijzen.

**Comment by hanjoosten** [comment]
De oplossing van Stef is bijna goed. Maar hiermee ben ik nog niet tevreden. In plaats van één concept bij naam te noemen, moet het ook mogelijk zijn om een lijst van concepten te noemen. Die moeten dan wél voldoen aan de volgende regels:

* De lijst is niet leeg
* De genoemde concepten behoren tot één en dezelfde classificatie.

Hierdoor kan je bij ingewikkelde classificaties toch heel precies de juiste concepten kiezen.

**Comment by RieksJ** [comment]
Doe eens een voorbeeld van wat je bedoelt, zodat ik het ook ga snappen.

**Comment by hanjoosten** [comment]
Given:

B ISA A
C ISA A

How could I populate a single instance of A, that is both B and C? (without needing tot extend the classification)

In this case, I need something like:

POPULATION B, C CONTAINS ["this atom is an instance of both B and C, end thus also of A"]

**Comment by RieksJ** [comment]
Really? Consider the following scriptlet:

    r :: A * B
    POPULATION r CONTAINS [ ("a", "b1") ]
    POPULATION r CONTAINS [ ("a", "b2") ]
    POPULATION r CONTAINS [ ("a", "b1") ]

Note that the second `POPULATION`-statement does not create a second atom `a` in `A`.
Also note that the third `POPULATION`-statement does not do anything, since the link `(a, b1)` is already populated (and it is good that it does not produce an error, either).
Now, consider the following:

    CLASSIFY B ISA A
    CLASSIFY C ISA A
    POPULATION B CONTAINS [ "a" ] -- as per Stef's solution

I would expect that there is an atom `a` that is both an `A` and a `B`. Now, if this is followed by

    POPULATION C CONTAINS [ "a" ] -- as per Stef's solution

I would expect that this only creates  an atom `a` in `C`, and not in `A` since it already exists there.
And a subsequent statement `POPULATION A CONTAINS [ "a" ]` would not have any effect.
So what's the problem?

**Comment by hanjoosten** [comment]
Interestng. I have spoken to Stef. As I understand now, with the above classifications, B and C are disjunct. This means, that iff there is an atom a in B (and thus in A), it cannot be in C.
This means that my suggestion about extending the population statement to contain a list of concepts, is void.
We need validations to check all this. Maybe they are in place already. Some testscripts would be nice...

**Comment by stefjoosten** [comment]
a  number of test cases is operational on the Sentinel.


Verzonden vanaf Samsung Mobile


-------- Oorspronkelijk bericht --------
Van: Han Joosten
Datum:11-04-2015 14:49 (GMT+01:00)
Aan: "Joosten, Stef"
Onderwerp: Re: [ampersand] Populeren van concepten (vervolg van sf ticket 417) (#63)

Interestng. I have spoken to Stef. As I understand now, with the above classifications, B and C are disjunct. This means, that iff there is an atom a in B (and thus in A), it cannot be in C.
This means that my suggestion about extending the population statement to contain a list of concepts, is void.
We need validations to check all this. Maybe they are in place already. Some testscripts would be nice...

—
Reply to this email directly or view it on GitHub<https://github.com/AmpersandTarski/ampersand/issues/63#issuecomment-91837396>.

________________________________
Deze e-mail is uitsluitend bestemd voor de geadresseerde(n). Verstrekking aan en gebruik door anderen is niet toegestaan. Open Universiteit sluit iedere aansprakelijkheid uit die voortvloeit uit elektronische verzending. Aan de inhoud van deze e-mail en/of eventueel toegevoegde bijlagen kunnen geen rechten worden ontleend.

This e-mail is intended exclusively for the addressee(s), and may not be passed on to, or made available for use by any person other than the addressee(s). Open Universiteit rules out any and every liability resulting from any electronic transmission. No rights may be derived from the contents of this message.

Disclaimer
Dit bericht met eventuele bijlagen is vertrouwelijk en uitsluitend bestemd voor de geadresseerde. Indien u niet de bedoelde ontvanger bent, wordt u verzocht de afzender te waarschuwen en dit bericht met eventuele bijlagen direct te verwijderen en/of te vernietigen. Het is niet toegestaan dit bericht en eventuele bijlagen te vermenigvuldigen, door te sturen, openbaar te maken, op te slaan of op andere wijze te gebruiken. Ordina N.V. en/of haar groepsmaatschappijen accepteren geen verantwoordelijkheid of aansprakelijkheid voor schade die voortvloeit uit de inhoud en/of de verzending van dit bericht.

This e-mail and any attachments are confidential and are solely intended for the addressee. If you are not the intended recipient, please notify the sender and delete and/or destroy this message and any attachments immediately. It is prohibited to copy, to distribute, to disclose or to use this e-mail and any attachments in any other way. Ordina N.V. and/or its group companies do not accept any responsibility nor liability for any damage resulting from the content of and/or the transmission of this message.

**Comment by Oblosys** [comment]
Note that mutual exclusion is not currently enforced, and that the sentinel tests will not fail on this (we need edit validation checks for that). I've created a new issue (#68) so we'll be reminded of it.
