### ISSUE TITLE
Enhancement request for ExecEngine violations logging

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/Ampersand#634]
When debugging complex scripts, the ExecEngine log can have lines such as

![image](https://cloud.githubusercontent.com/assets/8522589/23341203/47321102-fc43-11e6-8460-400b31475592.png)

I would like to draw attention to the 'dirty identifiers' within the red line.
With some effort, you can see that they are all different, but you cannot see anything else.
For lowlevel debugging, these identifiers are great.
For higherlevel debugging, it would be nice if we could *also* have the default view/representation of these dirty identifiers as we are used to in the user interface. If the default view of such an identifier is the name of the object, then the name of the object would show, which makes (higher-level) debugging easier.

Would it be possible to show the violation both in terms of dirty identifiers and in terms of default views on the same line?

**Comment by Michiel-s** [comment]
Of course your request is possible, but I think it does impact performance. Views are now only calculated when needed in the user interface. This request wil result in many additional database interactions. @RieksJ  I think there are other options to provide you with even more debugging information, I'll show you when we see each other next time.

For now, I'll close this issue.
