### ISSUE TITLE
Checking populations compromises performance

### ISSUE THREAD

**Issue by hanjoosten** [AmpersandTarski/ampersand#64]
One of the checks that is currently being done, is the check that SESSION is populated with nothing else than `_SESSION`. Since this check is added to the Haskell code, Sentinel needs over 40 minutes to finish. This used to be about 13 minutes. 
This is partly due to the fact that Haskell is lazy: 

* With the check, the populations will be calculated. 
* Without check, there is no need to calculate the populations in a lot of testcases, thus saving time.

**Comment by Oblosys** [comment]
We could choose to only check when --proto is provided. For a prototype the populations are already being computed, and having the check there will also allow it to be overridden with --dev (which may be useful if you want to do some testing with sessions.)

**Comment by hanjoosten** [comment]
Not an issue any longer
