### ISSUE TITLE
ArchiMate access relation imported under wrong name

### ISSUE THREAD

**Issue by filetp** [AmpersandTarski/Ampersand#642]
When an ArchiMate access relation is provided with a name in Archi, Ampersand creates a relation under the given name, instead of recognizing it as an access relation.

Archi:
![image](https://cloud.githubusercontent.com/assets/22689893/24321328/3c718ba0-114a-11e7-8133-06feda1e9a92.png)

In XML:
![image](https://cloud.githubusercontent.com/assets/22689893/24321335/649ce6b0-114a-11e7-9460-c48422c9d1c4.png)

Import into Ampersand results in metamodel.adl:
![image](https://cloud.githubusercontent.com/assets/22689893/24321341/8a8b87be-114a-11e7-8a10-bdfc969447ba.png)

[Archisurance.zip](https://github.com/AmpersandTarski/Ampersand/files/869912/Archisurance.zip)

**Comment by filetp** [comment]
The same issue goes for the Flow relationship. Presumably this goes for all relations that are provided with a name attribute in Archi.

**Comment by stefjoosten** [comment]
Voor zover ik kan zien verschijnt het Archi-element met id "693" in het concept `AccessRelationship`, en daardoor ook in het concept `Relationship` (omdat `AccessRelationship` ISA `Relationship`). Hij is daarmee herkenbaar als `AccessRelationship`. Ik heb dat gecheckt in de broncode van de Archi-importer en ook in de gegenereerde database voor Archisurance.

Als dit het probleem is, is er geen probleem...
@filetp wil je dat checken? Als dat zo is mag je dit issue sluiten.

**Comment by filetp** [comment]
De relatie wordt inderdaad zoals het hoort in Relationship opgenomen. Daarmee is hij herkenbaar en dus bruikbaar. Issue is een non-issue.

Ampersand voegt wel ook (ten overvloede) een nieuwe relatie toe onder de naam die in het label is vermeld. Dat is wat deed vermoeden dat de relatie niet goed werd opgenomen.
