### ISSUE TITLE
The Archimate access relation's type is ignored

### ISSUE THREAD

**Issue by filetp** [AmpersandTarski/Ampersand#643]
When the ArchiMate access relation attribute 'Access Type' is provided with a value in Archi, Ampersand ignores this value. The attribute however, provides distinction between read and/or weite access.

The access relation can have the following attribute values:

Value		Meaning					XML appearance
======		================	============
Read		[src] Reads [tgt]			accessType="1"
Access		[src] Accesses [tgt]			accessType="2"
Read/Write	[src] Reads/writes [tgt]		accessType="3"
Write		[src]Writes [tgt]			accessType is absent

Archi:
![image](https://cloud.githubusercontent.com/assets/22689893/24321418/84f33034-114c-11e7-85be-be09d2e43065.png)

XML:
![image](https://cloud.githubusercontent.com/assets/22689893/24321421/8e97aaf2-114c-11e7-843d-eb9de5553e63.png)

[Archisurance.zip](https://github.com/AmpersandTarski/Ampersand/files/869916/Archisurance.zip)

**Comment by stefjoosten** [comment]
I have introduced the accessType in the metamodel (in commit @9fb9525f991315db6f49046465bf1a7ea67c996d)
