### ISSUE TITLE
Archi properties with separate XML tagging are not imported into Ampersand

### ISSUE THREAD

**Issue by filetp** [AmpersandTarski/Ampersand#644]
In Archi, object properties that are provided with values:

![image](https://cloud.githubusercontent.com/assets/22689893/24321553/4817dcb6-114f-11e7-98a7-5337e851e319.png)

![image](https://cloud.githubusercontent.com/assets/22689893/24321556/5a2770ce-114f-11e7-90cd-39726f559f21.png)

...are XML coded by Archi as follows:
![image](https://cloud.githubusercontent.com/assets/22689893/24321559/82c02f62-114f-11e7-8586-46a4b51face0.png)

These properties are not imported into Ampersand.

[Archisurance properties.zip](https://github.com/AmpersandTarski/Ampersand/files/869927/Archisurance.properties.zip)

**Comment by stefjoosten** [comment]
I have included these documentations too. In the metamodel, they appear in the relation `docu`. That is the same relation as the documentation tag that is an XML-attribute of the element itself. I fixed this in branch Archi-extension, commit @f73805909dbb38402a3e74058d40abb9d8fcc949
