### ISSUE TITLE
Archi XML tagging not recognized by default

### ISSUE THREAD

**Issue by filetp** [AmpersandTarski/Ampersand#645]
XML tagging as provided by Archi differs from what Ampersand recognizes:
	Archi provides -->	Ampersand expects
	--------------------------------------------------
	[archimate:model] --> [archimate:ArchimateModel]
	[element] --> [elements]
	[folder] --> [folders]

Preferably Ampersand recognizes Archi's tagging, so manual corrections become unnecessary.

**Comment by stefjoosten** [comment]
I fixed this in branch Archi-extension, commit @f73805909dbb38402a3e74058d40abb9d8fcc949

**Comment by stefjoosten** [comment]
Reverted this change in commit @acb02a52baf8d8d1e11c85f17e4d40c1e14c5515 on request of @filetp.

Peter, could you test whether this is resolved? Please close or extend this issue depending on your findings.

**Comment by filetp** [comment]
The fix attempt for #645 Archi XML tagging works fine. Ampersand now reads Archi files without the need for manual corrections.


The fix attempt for #656 (Key-value pairs from ArchiMate are ignored) seems incomplete.
Property keys and values are all imported from the .xml file into the relations `key` and `value`.
However, strangely enough not all properties are related to their ArchiObject. The enclosed .zip file contains an example.

The generated metamodel states:

![image](https://cloud.githubusercontent.com/assets/22689893/25249910/ef3799ae-2613-11e7-974a-6da2afd66532.png)

Only property `pr-5` is related to is ArchiObject `TestBA01` in relation `PropOf`

[MiniMinDef.zip](https://github.com/AmpersandTarski/Ampersand/files/945303/MiniMinDef.zip)
