### ISSUE TITLE
Wish: Delivery of rule metrics in outputfile

### ISSUE THREAD

**Issue by filetp** [AmpersandTarski/Ampersand#646]
During compile time, the outputfile archicount.txt is created which contains (among more) the number of processed elements, relations, etc. This file would be a fine place to store the rule metrics.

To enable calculation of alignment metrics, I need metrics that concern Ampersand rules.
For each rule I need:
   - the rule ID;
   - the number of pairs in the antecedent;
   - the number of violations (pairs in antecedent minus consequent).

The generated prototype is able to show only the number of violations:
![image](https://cloud.githubusercontent.com/assets/22689893/24330104/059353d8-1218-11e7-865e-ddbf203ce830.png)

**Comment by Michiel-s** [comment]
Because work on the archimate extension is discontinued (if I'm correct) I'm closing this issue.
