### ISSUE TITLE
Disambiguating IDENT statement

### ISSUE THREAD

**Issue by hanjoosten** [AmpersandTarski/ampersand#65]
Currently, there is no relations between the Concept in an IDENT statement and the source of the expression. There should be one, because the expression might be overloaded, giving unhelpful error messages. For this reason, I added ShouldSucceed/try47.adl: 

```
CONTEXT Try47 IN ENGLISH
   IDENT Context: Context(name)  
   RELATION name[Context*ContextName] [UNI,TOT,INJ]
   IDENT Pattern: Pattern(name)  
   RELATION name[Pattern*PatternName] [UNI,TOT,INJ]
ENDCONTEXT
```

This now gives the following message:

```
Error(s) found:
Cannot disambiguate the relation: name
  Please add a signature (e.g. [A*B]) to the relation.
  Relations you may have intended:
  name[Context*ContextName]
  name[Pattern*PatternName]
  Error at symbol name in file try47.adl at line 3 : 24
```

**Comment by hanjoosten** [comment]
Bas, could you please look into this? It will also help me with identifying where to solve this. That might enable me to fix the issue with try48.adl
Thanks!

**Comment by hanjoosten** [comment]
fixed

**Comment by stefjoosten** [comment]
This leaves me curious as to how this has beem fixed....

**Comment by sjcjoosten** [comment]
Thanks for asking! To fix this bug, I had to make P_IdentDef disambiguatable. Note that try48 had nothing to do with it. Let me copy some of the comments I wrote to this place.

    -- To make something Disambiguatable, do the following:
    -- (1) Make sure the type of the Disambiguatable thing has a type variable.
    --     Suppose "Thing" should become disambiguatable, then "Thing" has "TermPrim" inside somewhere.
    --     Change "data Thing =" into "data ThingPolymorphic a =", and change occurences of "TermPrim" into "a".
    --     We changed "Thing" into "ThingPolymorphic" so we can create a type instance for "Thing":
    --     type Thing = ThingPolymorphic TermPrim
    --     This makes sure that "Thing" is the exact same type before and after this change.
    -- (2) Make ThingPolymorphic an instance of Traversable. The default "deriving Traversable" should be fine.
    -- (3) Make ThingPolymorphic an instance of Disambiguatable. It is your responsibility to prevent loops here. The instance looks like this:
    --     disambInfo (Thing1 x y z) td = (Thing1 x' y' z', (bottomUpSourceTypes,bottomUpTargetTypes))
    --      where (x',resultingTypesForX) = disambInfo x' topDownTypesForX
    --            (y',resultingTypesForY) = disambInfo y' topDownTypesForY
    --            (z',resultingTypesForZ) = disambInfo z' topDownTypesForZ
    --     The variables topDownTypesFor... may depend on td,
    --     the variables bottomUpSourceTypes and bottomUpTargetTypes may depend on resultingTypesFor...
    --     Closing the loop (at the top of the structure) is done in the function "disambiguationStep".
    --     Note that disambInfo actually performs two separate functions in one go: one to go top down, the other to go bottom up.
    --     The top-down function may use parts of the bottom-up function, but not the other way around.
    --     A nice example to look at is PCps:
    --         disambInfo (PCps o a b) (ia1,ib1) = ( PCps o a' b', (ia, ib) )
    --          where (a', (ia,ic1)) = disambInfo a (ia1,ic2) -- here ic2 is top-down, so that is ok
    --                (b', (ic2,ib)) = disambInfo b (ic1,ib1)

In the case of P_IdentDef, the new data type is called P_IdentDf a, and P_IdentDef is a type synonym for P_IdentDef TermPrim. It contains a P_IdentSegmnt for which I did the same (used to be P_IdentSegment, which now is a type synonym for P_IdentSegmnt TermPrim)
