### ISSUE TITLE
RAP3-Azure: permission required for mkdir

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/Ampersand#650]
When I start RAP3 in Azure, and try to enter a studentnumber (in this case: xxx), it says this:
![image](https://cloud.githubusercontent.com/assets/8522589/24793392/27514606-1b82-11e7-9cfd-2edba5b24f03.png)

**Comment by hanjoosten** [comment]
This should have been solved by now, by taking into account the user/group authorisations.
