### ISSUE TITLE
RAP3-Azure: Diagnosis/FSPEc pdfs cannot be found

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/Ampersand#651]
I have a simple script that i compiled, and created a Diagnosis of, as follows:

![image](https://cloud.githubusercontent.com/assets/8522589/24828396/79165a46-1c5c-11e7-89df-128c31a880e4.png)

Clicking on the `Diagnosis` link results in 

![image](https://cloud.githubusercontent.com/assets/8522589/24828398/8ac7c0cc-1c5c-11e7-94d1-2b12f3b2501e.png)

**Comment by RieksJ** [comment]
The same thing happens when I create a functional specification:

![image](https://cloud.githubusercontent.com/assets/8522589/24828408/d26357a2-1c5c-11e7-8a10-23fc2d6d8fe4.png)

**Comment by hanjoosten** [comment]
We still have to install LaTeX correctly.
