### ISSUE TITLE
RAP3-Azure: Import of trash files may result in SQL errors

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/Ampersand#652]
Importing a 'trash file' - I did it with a powerpoint presentation may result in:

![image](https://cloud.githubusercontent.com/assets/8522589/24828437/80ef0c08-1c5d-11e7-9a01-e67acf76d48d.png)

**Comment by RieksJ** [comment]
Het zou kunnen zijn dat ik hiermee de database stuk heb gemaakt. Hij werkt in ieder geval niet meer (herinstalleren ervan duurt ook eindeloos)...

**Comment by hanjoosten** [comment]
Niet meer doen ;)
We zijn nog niet toe aan monkey tests. 
Het bleek dat mysql twee keer draaide. Hoe dat komt? Geen idee. Wie het weet, mag het zeggen.
