### ISSUE TITLE
MySQL error 1406 'Data too long for column' when importing fields 'documentatie' and 'Tekst'

### ISSUE THREAD

**Issue by filetp** [AmpersandTarski/Ampersand#653]
The generated prototype contains fields named 'documentatie' in several concepts and a field 'Tekst' in table 'Tekst' which are created as VARCHAR(255).
The content however is generally longer than 255 characters, even up to 4700+ characters.
This leads to fatal error 1406 when MySQL tries to INSERT the content.

![image](https://cloud.githubusercontent.com/assets/22689893/24836706/4b06ba7a-1d23-11e7-8bf0-97cabb1e9a52.png)

To reconstruct the error, copy the content of this .zip file to the folder XAMPP\htdocs\prototype 
[CaseBelastingdienst.zip](https://github.com/AmpersandTarski/Ampersand/files/908137/CaseBelastingdienst.zip)

**Comment by hanjoosten** [comment]
I like the error. In former days, this error was ignored, but only 255 characters were stored. That's even worse!
It should be easy to fix this error. There are several representation types for string-like stuff. You should choose a larger one than ALPHANUMERIC. Try BIGALPHANUMERIC or even HUGEALPHANUMERIC. They obviously require more space in your database, but that's exacly what you need. 
In your ampersand script (I didn't even look into it) there will be something like 

    REPRESENT Tekst TYPE ALPHANUMERIC

just change that.
