### ISSUE TITLE
Key-value pairs from Archimate are dangling

### ISSUE THREAD

**Issue by filetp** [AmpersandTarski/Ampersand#656]
The two attributes 'Soort product' and 'Domein' are not imported into the metamodel. I coded this in two ways of which neither was succesfull :-(

`<elements xsi:type="archimate:ApplicationComponent" id="TestAC01" name="Test AC">`
`<property key="Soort product" value="test soort"/>`
` <property key="Domein" value="test domein"/> ` 
`</elements>`

`<elements xsi:type="archimate:ApplicationComponent" id="TestAC01" name="Test AC" SoortProductAttrib="testSoortAlsAttrib" DomeinAttrib="testDomeinAlsAttrib"/>`

The fix attempt for #656 (Key-value pairs from ArchiMate are ignored) seems incomplete.
Property keys and values are all imported from the .xml file into the relations `key` and `value`.
However, strangely enough not all properties are related to their ArchiObject. The enclosed .zip file contains an example.

The generated metamodel states:

![image](https://cloud.githubusercontent.com/assets/22689893/25249910/ef3799ae-2613-11e7-974a-6da2afd66532.png)

Only property `pr-5` is related to is ArchiObject `TestBA01` in relation `PropOf`

[MiniMinDef.zip](https://github.com/AmpersandTarski/Ampersand/files/945303/MiniMinDef.zip)

**Comment by stefjoosten** [comment]
I am treating XML-tags "property"  and "properties" as the same. This should resolve the issue.

**Comment by stefjoosten** [comment]
The second part of this issue needs attention. It looks like each property is not linked to the object to which it belongs.

**Comment by Michiel-s** [comment]
I propose to close this stale issue

**Comment by stefjoosten** [comment]
ok. Can it get a special label to mark that it has not been resolved?
