### ISSUE TITLE
Specialisation relation for Archimate element 'ApplicationComponent' is not imported

### ISSUE THREAD

**Issue by filetp** [AmpersandTarski/Ampersand#660]
Many ApplicationComponents are related to ApplicationComponent `id-11274` by means of a specialisation relation. 
When importing in Ampersand however, the occurrences of this specialisation relation do not occur as specialisation. 
Apparently, they are described in the ArchiMetaModel.adl in a relation with the name `flow` instead of `specialisation`

E.g. AC `id-20718` has a specialisation relation to AC `id-11274`, but this relation is shown in ArchiMetaModel.adl as tuple in the relation `flow`

[ACspecialisation.zip](https://github.com/AmpersandTarski/Ampersand/files/945475/ACspecialisation.zip)

**Comment by stefjoosten** [comment]
Solved in commit 1ee45ace514f7d6b081908333bb31572d7b3038d by removing the special treatment of flow relationships.
