### ISSUE TITLE
all_signals table seems to cause deadlock

### ISSUE THREAD

**Issue by hanjoosten** [AmpersandTarski/Ampersand#662]
When multiple sessions are open, we encountered the following error message:
![image](https://cloud.githubusercontent.com/assets/1159672/25307021/3f23710e-279a-11e7-9bc0-ff0c1e032804.png)

I suspect that while calculating conjuncts, the locking mechanism on all_sessions is not handled properly.

**Comment by Michiel-s** [comment]
Duplicate issue #635
