### ISSUE TITLE
array_key_exists Bug

### ISSUE THREAD

**Issue by stefjoosten** [AmpersandTarski/Ampersand#663]
# Symptoms
I wanted to make a new script in RAP3. Auto commit changes and Auto save changes were switched off. When pushing the "new script" button, the Save/Cancel buttons appeared immediately. Before doing anything else, I pushed Save. Then this bug appeared:

![afbeelding](https://cloud.githubusercontent.com/assets/275768/25313516/390c19a6-2830-11e7-87bd-60cfbfa7eeef.png)

The only possible location in the code was traced to cli.php on line 341:
![afbeelding](https://cloud.githubusercontent.com/assets/275768/25313556/e7074a12-2830-11e7-87a2-7f591174f0b5.png)

**Comment by Michiel-s** [comment]
Moved issue to RAP repository. Specific issue for that application. Not Ampersand generic
