### ISSUE TITLE
Excel-import in prototype no longer handles duplicate atom entries

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/Ampersand#664]
De map `[Git]\ampersand-models\ZwolleFrontEnd\RWS` bevat een kleine applicatie die een voorbeeld is van hoe je gegevens kunt opschonen, en dus een kleine (maar fijne) demo is. Deze demo (maar ook anderen) importeren excel-bestanden waarbij het voorkomt dat er een regel is die InsPairs wil doen op een reeds bestaand atoom. Dat kan bijvoorbeeld:

  * omdat het atoom in een eerdere regel werd genoemd. Dat is bij RWS het geval, en de noodzaak komt hieruit dat de excel-sheets zijn geconstrueerd uit bestaande sheets van de RWS organisatie.
  * omdat het atoom al bestond in de database. Dat komt voor als je het importeren van een excel sheet gebruikt om aan een bestaand atoom nieuwe attributen toe te voegen (handig bij testen bijvoorbeeld).

Vroeger was het mogelijk om in een excel-file een regel op te nemen voor een atoom dat al bestond voordat de regel werd geinterpreteerd. Dat zou weer mogelijk moeten worden.

**Comment by Michiel-s** [comment]
Same issue as #672 which is fixed by 86d0329c9ad55904913131ce82f93b7ec6d43fe0
