### ISSUE TITLE
Some vague halting with Sequences

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/Ampersand#665]
As I am trying some (older) stuff, I keep running into bitrot. As I think it helps the robustness of our tooling, I try to fix that stuff. Here is something I need some help with.

The `ampersand-models/Sequences` stuff compiles nicely, but the initialization of the database does not seem to properly terminate. Here is the rules-log:

![image](https://cloud.githubusercontent.com/assets/8522589/25382107/8ef25ec0-29b6-11e7-9e65-af620cd0f600.png)

And here is the tail of the debug log:

![image](https://cloud.githubusercontent.com/assets/8522589/25382190/d68caaec-29b6-11e7-99e4-445f0f6f2a26.png)

So it seems that the ExecEngine somehow does not start.

**Comment by Michiel-s** [comment]
Rieks, weet niet precies wat hier aan de hand is, maar de interne werking van de ExecEngine gaat op de schop. Laten we daarna kijken of deze opgelost is.
