### ISSUE TITLE
The demonstration devil ...

### ISSUE THREAD

**Issue by stefjoosten** [AmpersandTarski/Ampersand#666]
# Symptoms
Giving demos for an audience has occasionally failed. Here is the situation: I have carefully made a nice little script and prepared my demo with it. For example:
![afbeelding](https://cloud.githubusercontent.com/assets/275768/25653082/a364256a-2feb-11e7-94a2-69cc0a790c9f.png)
The next day, it is showtime. I have made sure I didn't touch anything that could jeopardize the presentation. Then, in the face of my audience, all of a sudden nothing works anymore:
![afbeelding](https://cloud.githubusercontent.com/assets/275768/25653066/8e2b8774-2feb-11e7-99f6-310a63df3ae1.png)
The complete error-message reads: `API call not found: GET http://localhost/AmpersandPrototypes/TestMergeAtoms/api/v1/AmpersandPrototypes/testMergeAtoms/api/v1/sessions/5d4rpdqeglhibkkg5na21l5f52/navbar`

This thing has caused my demo to fail completely on several occasions in the past. Quite embarrassing, I must say. In the pressure of presenting, I have not always been able to recognize this problem on the spot, let alone diagnose and fix it in front of an audience. When I checked afterwards, the directory `...\htdocs\AmpersandPrototypes\TestMergeAtoms` was in perfect order. Checking with phpMyAdmin showed that the database `ampersand_testmergeatoms` was present. I wasted quite some time looking for the problem and trying to fix it...  :-(
# Analysis
Here is the answer: If, for some reason, I type the URL with a lowercase letter instead of the uppercase letter by which it was generated, I am the Sjaak. A stupid mistake indeed!  But it took me (on two occasions at least) a desperate phone call to @Michiel-s to diagnose the situation. That is why I think this silliness justifies an issue.
# Solution
Can we help the poor demo-presenter, (me, and maybe others as well) by enforcing a case sensitive URL in the front-end? That would allow for a more informative error message, which is much needed, pointing towards the case sensitivity of his URL.

**Comment by hanjoosten** [comment]
This is the wrong solution to a local problem. In the world we live in, URL's are case sensitive. You simply have to deal with that. 

For your demo purposes, there are (at least) two sure and simple ways not to bump into typing the wrong URL: 

1.   Create a shortcut on your desktop with the correct URL. You can test that shortcut, so at showtime you simply click it and have your awsome demo.
2. Make sure the directory where your prototypes are being generated can be read. In that case you can browse to (extracted from the above example) http::localhost/AmpersandPrototypes/ where you will find all your generated prototypes in the right case spelling. Click on the one that holds the prototype for your demo, and voila. Works at all times.

**Comment by hanjoosten** [comment]
After talking to @stefjoosten about this issue, I still feel strong about the above points. However, I do agree that it would be nice if the actual error message would suggest an error regarding case sensitivity.

**Comment by hanjoosten** [comment]
![image](https://cloud.githubusercontent.com/assets/1159672/25870875/f92dd1d4-3505-11e7-86c1-f8e2fb978330.png)
