### ISSUE TITLE
Import for Excel not being handled properly

### ISSUE THREAD

**Issue by stefjoosten** [AmpersandTarski/Ampersand#669]
In my work on the MirrorMe application, I ran into a problem with importing the Excel file [MirrorMe - Stef Example.xlsx](https://github.com/AmpersandTarski/Ampersand/files/997722/MirrorMe.-.Stef.Example.xlsx). I was executing the system generated from file ...git\ampersand-models\MirrorMe\MirrorMe.adl. You will find it in repository ampersand-models on commit 8190b5a980bbbabac812945a3c7811416578f335 of May 12th 2017. It compiles properly, even when it includes the Excel file in the source code (which means that the Excel file is checked by the compiler).
However, at runtime it produces an error.
![image](https://cloud.githubusercontent.com/assets/275768/26013748/12522128-375a-11e7-9550-0f85ab5b2e75.png)

**Comment by hanjoosten** [comment]
Please specify if this is at compiletime (using INCLUDE) or at runtime.

**Comment by stefjoosten** [comment]
# Analysis
The error message mentions `Interface path: 'Case/Bindings/ground'`. This implies expression `legalGround[Binding*LegalGround]` on line 188 of file `MirrorMe.adl`. The spreadsheet contains this relation too. In this situation, the Slim Error message reads `Message: Atom 't01[TText]' does not match source concept 'Binding' or any of its specializations.` That makes sense. Apparently something translates `t01` to a `TText` inadvertedly.

**Comment by Michiel-s** [comment]
This seems no issue anymore. I've tested the application given the commit mentioned in the post of @stefjoosten and uploaded the excel file.

I think that commit c782f79baa21f1fa9ec156c85966fbb66610b132 of July 14th already fixed this issue.
