### ISSUE TITLE
Redundant conjuncts generated in simple model

### ISSUE THREAD

**Issue by hidde-jan** [AmpersandTarski/Ampersand#670]
We are toying around with a simple model and we noticed that some redundant conjuncts were generated in the prototype. The conj_5 and conj_8 queries are equivalent. Both even say they check SYM projIsActive.

The conjuncts.json, adl and xslx files that are used are attached to this issue. 

[conjuncts.txt](https://github.com/AmpersandTarski/Ampersand/files/1095292/conjuncts.txt)
[archive.zip](https://github.com/AmpersandTarski/Ampersand/files/1095288/archive.zip)

**Comment by hanjoosten** [comment]
Indeed, this is incorrect. When a relation is symmetrical, this happens. @stefjoosten  might want to look at this:
For the propertyrule on the relation r[A*B][SYM], two conjuncts are being generated. (violations will occur double for this reason).

**Comment by hidde-jan** [comment]
I've got another question. In the example attached to this issue, I noticed that the `projIsActive` property is implemented in SQL as a field in the Project table. This field is a VARCHAR, which can be filled with anything. From what I can see, when the violation rules are run, it is checked whether `projIsActive` is INJ, UNI, ASY, SYM (and SYM again). All these properties of the property would automatically hold if `projIsActive` were to be implemented as a boolean field. This is something that we would like to achieve for the solidity com/transpiler we're looking at. If such a thing would be (back)ported into mysql, a couple of complex self-joins occuring in certain queries could be replaced by a simple `where projIsActive = 1`.

Is such a think feasible? Or would it require rather rigorous changes in Ampersand?

**Comment by hanjoosten** [comment]
This would be another discussion. Please open a new thread for that if you like. I'll call you this afternoon to discuss these options

**Comment by stefjoosten** [comment]
The code that is generated for interfaces is not (yet) going through an optimization algorithm. There are ideas to do that with SMT-solvers such as Z3. That requires someone to dive into this. I trust this will happen when the time is right.

We will not revert to quick-fixes to solve this problem. That draws away attention from the issue, places a technical debt on the future and diminishes the overall maintainability of Ampersand.
