### ISSUE TITLE
Implement [PROP] as boolean field in the prototype

### ISSUE THREAD

**Issue by hidde-jan** [AmpersandTarski/Ampersand#671]
In the example attached to issue #670 , I noticed that the projIsActive property is implemented in SQL as a field in the Project table. This field is a VARCHAR, which can be filled with anything. From what I can see, when the violation rules are run, it is checked whether projIsActive is INJ, UNI, ASY, SYM (and SYM again). All these properties of the property would automatically hold if projIsActive were to be implemented as a boolean field. This is something that we would like to achieve for the solidity com/transpiler we're looking at. If such a thing would be (back)ported into mysql, a couple of complex self-joins occuring in certain queries could be replaced by a simple where projIsActive = 1.

Is such a thing feasible? Or would it require rather rigorous changes in Ampersand?

**Comment by stefjoosten** [comment]
Hidde-Jan, Thanks for bringing this up.  We'll look into it. As an Ampersand user you will at best notice a speed-up, because the semantics won't change because of this. It might take a while, however, before we get to this.

Stef

**Comment by hanjoosten** [comment]
Nah. For SQL we will not change the implementation. This has been discussed earlier in issue #150
