### ISSUE TITLE
Population of propOf relation is omitted

### ISSUE THREAD

**Issue by filetp** [AmpersandTarski/Ampersand#673]
The relation `propOf` is not populated with tuples.
Therefore the properties belonging to ArchiObjects are not accessible.

![image](https://user-images.githubusercontent.com/22689893/27773130-1b8685d6-5f73-11e7-9fea-58c2165b9c63.png)

The attached .zip file contains the & .adl script and the ArchiMate .xml file.

[PropOf issue.zip](https://github.com/AmpersandTarski/Ampersand/files/1118061/PropOf.issue.zip)

**Comment by filetp** [comment]
With the following code change, the `propOf` relation in ArchiMetamodel.adl contains the references from the Property key to the ArchiObject key.

![image](https://user-images.githubusercontent.com/22689893/28502721-d8ac25ae-6ff8-11e7-99f3-cacc6f2b005e.png)

as shown in the following screenshot:
![image](https://user-images.githubusercontent.com/22689893/28502728-f2615528-6ff8-11e7-8709-28b75a74bcce.png)

Next step is to make sure that the `propOf` relation content lands in the SQL database.
As a newbie in Haskell, I have not yet been able to locate the Haskell code for this.

**Comment by stefjoosten** [comment]
Peter, you are making me proud! :-)
