### ISSUE TITLE
PHP escaping of Excel content.

### ISSUE THREAD

**Issue by stefjoosten** [AmpersandTarski/Ampersand#676]
# Symptom
I get a Slim Application Error that says I'm giving too many parameters to `DelAtom`:
![afbeelding](https://user-images.githubusercontent.com/275768/27833687-26342468-60d4-11e7-9939-3da45500b1a1.png)

The Ampersand source code of this rule is:
~~~~~~
ROLE ExecEngine MAINTAINS SURttPhrase
RULE SURttPhrase : I[TTPhrase] |- ttTemplate~;ttTemplate \/ ttInstance~;ttInstance
MEANING "If a TTPhrase is no longer used in a TText, it is registered no longer."
VIOLATION (TXT "{EX} DelAtom;TTPhrase;\"", SRC I, TXT "\"")
~~~~~~
The Ampersand source code clearly gives two arguments, so what explains this behavior?
Well, here is the source input, which resides in an Excel spreadsheet:
![afbeelding](https://user-images.githubusercontent.com/275768/27833585-caef60ae-60d3-11e7-9071-b02f1d8adac4.png)
# Reproducing this bug
I have used repo AmpersandTarski/ampersand-models@ad657b096a86a44c769e1031f0c8778096c4c1e7, in which I compiled and ran `...\git\ampersand-models\Contract Freeze\Main.adl`. I compiled with Ampersand-v3.8.5 [development:b17124abf]. The error occurs after importing `Contracten.xlsx` with the interactive importer, and subsequently deleting case 634 from the cases menu.

**Comment by stefjoosten** [comment]
# Further investigation
I have removed the newlines from the excel-sheet:
![image](https://user-images.githubusercontent.com/275768/27834780-8fc41b82-60d8-11e7-913c-62a7270bae44.png)
Although there are no newlines, I get the same behaviour:
![image](https://user-images.githubusercontent.com/275768/27834824-beb98a94-60d8-11e7-8f2a-f539d815255f.png)
It is clear that the change has been seen by the .xlsx importer, but the arguments are being split in exactly the same way.

Clearly the newlines are not to blame...

**Comment by RieksJ** [comment]
It is the semi-colons in the text. The ExecEngine parser sees them as an argument-delimiter. The 2 semi-colons you use in your text, and the other two in the violation itself, account for the four arguments.

The solution is to specifiy another delimiter in the violation text. The 'default' other delimiter we use here is `_;`. You can specify it immediately behind the `{EX}`, and then - of course - you should use it in the rest of the violation. 

What you should do is replace your violation:
~~~
VIOLATION (TXT "{EX} DelAtom;TTPhrase;\"", SRC I, TXT "\"")
~~~
with the following text that uses the alternative delimiters:
~~~
VIOLATION (TXT "{EX}_;DelAtom_;TTPhrase_;\"", SRC I, TXT "\"")
~~~
Please verify the correctness of this solution and close if you're satisfied.
