### ISSUE TITLE
Make Haskell code more readabble

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/Ampersand#681]
Currently, the Haskell code stands stiff with abbr's, which makes it unnecessarily difficult for people to understand what's going on. In order to help people, in particular those that are not very fluent in the language, to contribute to the further development of the Ampersand tool, it would help to use more elaborate and descriptive names (and comments). Consider this ticket as a request for that.

**Comment by hanjoosten** [comment]
There are several points in this. Yes, there are parts of the haskell code that are more readable than others. This is subjective, and it is a constantly ongoing work of refactoring.
