### ISSUE TITLE
Generate output for Solidity (Ethereum) from ADL

### ISSUE THREAD

**Issue by hanjoosten** [AmpersandTarski/Ampersand#682]
Specifying smart contracts by using Ampersand seems feasable. This issue is to document the ongoing work on this topic. 

The first work that will be done is to build a generator by means of examples.

**Comment by hanjoosten** [comment]
The initial stuff has been made available some time ago. The rest is up to @jcnauta

**Comment by hanjoosten** [comment]
@jcnauta , I saw that you have been working on this again. The branch had become stale, so I spent some time to merge development into it, so it is current again. How is this solidity stuff going?

**Comment by jcnauta** [comment]
@hanjoosten Great, thanks! I noticed and discussed with Rieks how Ampersand had evolved quite a bit. I'm almost done writing a few pages for Maarten on how the translation to Solidity worked out, I'm afraid it's far too inefficient and limited to be of any practical use though, the model that we used to demonstrate it gives out-of-gas exceptions even for the most generous test settings.

**Comment by hanjoosten** [comment]
In that case, if you agree, we could freeze the solidium branch (make a tag and then remove the branch). Would be nice to have a link to those pages from here, that is if they are public.

**Comment by hanjoosten** [comment]
Closing this issue, for it has become obsolete. Feel free to reopen it, if you would like to see this in Ampersand.
