### ISSUE TITLE
Roundtrip error in MetaPopulationFile

### ISSUE THREAD

**Issue by stefjoosten** [AmpersandTarski/Ampersand#684]
# Symptom
The file with metapopulation (`MetaPopulationFile.adl`) is written and directly parsed again in `CreateFspec.hs`. However, this yields a parse error as shown here:
![afbeelding](https://user-images.githubusercontent.com/275768/28321958-fdaf4a20-6bd4-11e7-9a7c-c3341646d9fd.png)

# Reproducing the error
The ampersand compiler (including FormalAmpersand files) used to get this error has SHA 3a1c5a5be4542ac4e447a6404865d06247a5047c in the ampersand repository.
The file RAP3.adl that I have been compiling is found in AmpersandTarski/ampersand-models@e7d9e72d37ff3d473b7d792e3d0dbe5e2a74d3d6.
I have compiled this file by:
~~~
ampersand.exe --meta-tables --add-semantic-metamodel --verbose -p"D:\htdocs\AmpersandPrototypes\RAP3
~~~

**Comment by stefjoosten** [comment]
Strange that the function 'content' generates text. One would expect a P-structure (of even an A-structure) instead. A roundtrip over a file is less maintainable than communication via the P-structure or A-structure.

**Comment by hanjoosten** [comment]
I had a look at this 'bug'. It was caused by an error that you made yourself, only in your own branch. Please have a closer look at what it was that I fixed.
