### ISSUE TITLE
Interface with ONE gives a Slim Application Error

### ISSUE THREAD

**Issue by stefjoosten** [AmpersandTarski/Ampersand#687]
# Symptom

Consider the following interface definition:
~~~
INTERFACE RelationsPerContext : I[ONE] cRud BOX <SHCOLS>
    [ Contexts : V[ONE*Context] COLS
       [ Relations : V[Context*Relation] COLS
          [ name : name[Relation*RelationName]
          , source : source[Relation*Concept]
          , target : target[Relation*Concept]
          ]
       ]
    ]
~~~
I want this interface to work on RAP3, irrespective of which sessions are running. For this reason, I use ONE instead of SESSION. However, this is what I get:
![afbeelding](https://user-images.githubusercontent.com/275768/28608527-f2e9eeda-71e0-11e7-940b-e7bc704d8bed.png)
The atom that is mentioned in the error message is `sgq89840ilkiiu6kari9tdbpb5`, being the current session atom. However, the concept ONE has only one atom, which is `1`.

**Comment by RieksJ** [comment]
Try '_SESSION'[SESSION] instead of 'ONE', as follows:
~~~
INTERFACE RelationsPerContext : '_SESSION'[SESSION] cRud BOX <SHCOLS>
    [ Contexts : V[SESSION*Context] COLS
       [ Relations : V[Context*Relation] COLS
          [ name : name[Relation*RelationName]
          , source : source[Relation*Concept]
          , target : target[Relation*Concept]
          ]
       ]
    ]
~~~

**Comment by Michiel-s** [comment]
As discussed with Stef, the session is considered the ONE atom in interfaces. Therefore, as Rieks points out above, ONE should be replaced by SESSION to make ik work.
