### ISSUE TITLE
How about an Excel Exporter?

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/Ampersand#689]
In order to flesh out the (functional) specifications of a tool that aims to provide support in complex situations, it is nice to be able to have several variations of the tool, so we can experiment what works best. 

A case that I have at hand is NRM, where I need a very simple tool for beginners, and as awareness of users about the complexity (and the causes thereof) increases, I would like to provide them with increasing functionality in the tool.

The situation I would like to have some more support for is that where users are playing with the tool in a workshop-like setting, create a hefty population in that workshop, and in the evaluation it becomes clear that functionality of the tool should be adapted. I would then like to be able to save their work in an Excel file, so that when the tool is changed, it is easy for me to change the Excel file and load it into the updated tool. Then, in the next workshop, we can proceed from the point where we left off with the modified functionalities.

Here is what I would like to have:

- an extension of the ExcelInterface, where it is possible to upload the database contents;
- when clicking the 'save database' button, the entire database is saved into an excel file, in such a way that when I subsequently reset the database (without installing the initial population) and then load the excelfile, this will restore the tool in the situation that it was in when the database was saved (with the exception of sessions, each of which would of course have been discareded).

**Comment by hanjoosten** [comment]
I can imagine that there is a need to be able to export / import a database, so we can have database versioning. It would be nice to have this in some handy way for a user. However, I am not convinced of this specific solution, to use Excel. We need to do better than that some day.

**Comment by Michiel-s** [comment]
My thoughts: I think we have a couple of use cases here, each with their own appropriate solution.

Use case 1: backup and restore of database. Here you can use functionality of standard database software (e.g. phpMyAdmin or MySQL workbench). You can export and import a complete database structure and population in various formats (sql contained file, csv, spreadsheet)

Use case 2: migrate population (atoms and links) to a newly created database. For example, when you update your Ampersand model, reinstall the database to create the tables again, you would like to be able te import the old population (given that this is possible). 
I think the best solution here is to upgrade the export and import functionality in the prototype (php) backend. We already have something in place, but it is not user-friendly and kinda hidden. 
Try: http://pathtoyourapp/api/v1/admin/export/all. A export file is created in the /log directory.
To import again: http://pathtoyourapp/api/v1/admin/import?file=[filename].

Use case 3: export certain data given a src atom and an interface (like the excel importer). For example, if you have an application and an interface with a list of things, you might want to give the user the possibility to download the data. Reasonable serializations here are xml, json and spreadsheets. This feature request is already on the wish list of a certain Ampersand application of mine and I will implement this genericly so it will be available to other prototypes as well.

@RieksJ could you specify which of the above you need the most.

**Comment by RieksJ** [comment]
A user-friendly version of use-case 2.

Verzonden met mijn Windows Phone
________________________________
