### ISSUE TITLE
Invalid expressions generated by conjNF

### ISSUE THREAD

**Issue by hanjoosten** [AmpersandTarski/Ampersand#692]
While working on the formal ampersand branch, I found that conjNF gives an unexpected result. 
Reproduction can be done by using the FormalAmpersand branch, [commit 31412c6db5d08a50c24bf7690badc77c3019039d](https://github.com/AmpersandTarski/Ampersand/commit/31412c6db5d08a50c24bf7690badc77c3019039d)
I was playing around with the script in [try45.adl](https://github.com/AmpersandTarski/Ampersand/blob/FormalAmpersand/testing/Travis/testcases/prototype/shouldSucceed/try45.adl). The command issued was

````
ampersand --meta-file try45.adl
````

Given some expression `expr`, I deduced that:
````
show expr = EEqu (EDcD x[A*D],ECps (EDcI A,ECps (EEps A [A*B],ECps (ECps (EDcI B,EEps C [B*C]),ECps (EDcI C,ECps (EEps C [C*D],EDcI D))))))
show (conjNF expr) = EIsc (EUni (ECpl (EDcD x[A*D]),ECps (EEps A [A*B],EEps C [B*D])),EUni (ECpl (ECps (EEps A [A*B],EEps C [B*D])),EDcD x[A*D]))
````

In the last expression, we have a subexpression
````
ECps (EEps A [A*B],EEps C [B*D]))
````
This is not how the design of Epsilon was ment to be. 

This expression triggers a fatal. This can be seen at line 989 of [this log](https://travis-ci.org/AmpersandTarski/Ampersand/jobs/262774154).

## Diagnose
Currently, in Haskell we have the data structure Expression. One of the constructors is EEps. EEps could be seen as an expression, but it has restrictions: It must be used inside of an ECps constructor as left or right expression. It is not allowed to have an ECps constructor with both subexpressions are an EEps. 
Because of these limitations, it is tricky to guarantee that EEps is not used incorrectly. 

## ~Solution~
~I propose to dissmiss the EEps constructor from the Haskell code. It should be replaced by another constructor, that can hold a *real* subexpression as well as two optional EEps-like things. Something like:~

````
data Expression
    ....
    | EEpsv2_0 { leftEpsilon :: Maybe (A_Concept, Signature) 
               , subExpr     :: Expression
               , rightEpsilon:: Maybe (A_Concept, Signature) 
               }
    ....
````
~The semantics will be similar to the semantics of the current epsilon. However, there will be no more implicit relation with the ECps constructor. I expect that the error in conjNF will become obvious while implementing this change.~

**Comment by hanjoosten** [comment]
@stefjoosten and I had a conversation on the phone to discuss this issue. This resulted in the following insight:

In formalAmpersand.adl, Epsilon is not modeled as a separate concept. It should, because in the implementation, EEps is considered to be a first-class constructor of an Expression. This difference is what causes this problem. 

## Solution
The solution is to model Epsilon as a concept in formalAmpersand. Just like we model "V" and "I".

**Comment by stefjoosten** [comment]
The diagnosis above is not  correct.
## Situation ##
The `EEps`-expression is an expression like any other. The only difference is that the user cannot write it down explicitly, because the parser has no syntax for `EEps`-expressions. Like any other expression, it has semantics. The semantics of `EEps C [A,B]` is the same set of pairs as the expression `I[C]`. The system invariant for `EEps C [A,B]` is that `C` is the intersection of `A` and `B`. This invariant is guaranteed by the type system.
## Consequences for the diagnosis above ##
The expression `ECps (EEps A [A*B],EEps C [B*D]))` has a well defined semantics. It is allowed to have an `ECps`-expression with both of its subexpressions being an `EEps`.

**Comment by hanjoosten** [comment]
Since 3.8.8, Epsilon is part of formalAmpersand
