### ISSUE TITLE
User interface vertoont onverwacht gedrag

### ISSUE THREAD

**Issue by ellekebaecke** [AmpersandTarski/Ampersand#694]
![image](https://user-images.githubusercontent.com/30124368/29606164-b7bdc52a-87ed-11e7-862d-f87c29755f38.png)

# Reproducing the bug
I have compiled MirrorMe.adl on AmpersandTarski/ampersand-models@aedbfd67b15c05f025bf9663fe9cb29f87bbbf71 using Ampersand-v3.8.6 [HEAD:49946cb70], build time: 08-Jul-17 09:11:28 with command:
~~~
ampersand --verbose mirrorme.adl -pC:/xampp/htdocs/mirrorme
~~~

I am unable to create a new claim(/datum/warrant), only add an existing one.

**Comment by hanjoosten** [comment]
I guess that this is one of the known bugs that should get solved with the `refactor_ifc` feature. This is under development however. @Michiel-s might confirm this?

**Comment by ellekebaecke** [comment]
It seems like the problem has been solved! I was just able to create a new claim in the field.
Thanks!

**Comment by hanjoosten** [comment]
@ellekebaecke sent me a mail that for some reason didn't make it to github:

~~~
It seems like the problem has been solved! I was just able to create a new claim in the field.
Thanks!
~~~
