### ISSUE TITLE
Performance issue on compiler Ampersand-v3.8.8 [master:1312237]

### ISSUE THREAD

**Issue by stefjoosten** [AmpersandTarski/Ampersand#697]
I used Ampersand-v3.8.8 [master:1312237], build time: 03-Sep-17 08:34:13 to compile  RAP3.adl from AmpersandTarski/ampersand-models@cf326b2f72c7292083bd6c38b180c0f28cc69462. It took a serious amount of time (5-10 minutes. I didn't measure it).
I then used Ampersand-v3.8.6 [FormalAmpersand:562571467] and compiled the same RAP3.adl. It passed quickly without significant delay.

**Comment by hanjoosten** [comment]
This is not a bug. It is due to the fact that we now have MUCH more atoms contained in it because of the formalAmpersand improvement.

**Comment by stefjoosten** [comment]
@hanjoosten 
Can it be that the transitive closure, needed to check for cycles in generalizations, is to blame?

**Comment by stefjoosten** [comment]
Aha, that explains...
