### ISSUE TITLE
Database server has gone away when starting RAP3.adl

### ISSUE THREAD

**Issue by stefjoosten** [AmpersandTarski/Ampersand#698]
I used Ampersand-v3.8.8 [master:1312237] to compile and run RAP3.adl from AmpersandTarski/ampersand-models@cf326b2f72c7292083bd6c38b180c0f28cc69462. This is what I got when initializing RAP3.
![afbeelding](https://user-images.githubusercontent.com/275768/30003003-9be004d0-90b7-11e7-9635-363ae9a9b435.png)
Here is the bottom part of the error message: 
![afbeelding](https://user-images.githubusercontent.com/275768/30003687-af923426-90c1-11e7-86fc-888418553e16.png)

**Comment by hanjoosten** [comment]
I can reproduce this error. It seems that the population of Expression (in particular the singletons) are causing this problem. I will look into this further shortly.

**Comment by stefjoosten** [comment]
I got the same error when compiling MiniMirrorMe.adl in the branch EllekesProbeersels of ampersand-models. This example is much smaller and very straightforward.

**Comment by Michiel-s** [comment]
@hanjoosten this issue is fixed right? With the new quotes for singletons?

**Comment by hanjoosten** [comment]
check.
