### ISSUE TITLE
Concept ONE in the population of the metamodel.

### ISSUE THREAD

**Issue by stefjoosten** [AmpersandTarski/ampersand#70]
When compiling with --ast-tables, I get a populated metamodel.
Inspecting that in the database (on phpMySQL), my eye is caught by the table conceptone.
It is empty, but I would expect it to contain one element in all situations.

**Comment by hanjoosten** [comment]
For some reason this table is created. However, there is a table `concept`, which is populated with both plainconcepts and ONE. (apart from the issue of #74 )

**Comment by stefjoosten** [comment]
Han, did you see (in commit dae3eb3) that Michiel is making error messages in the front end to hide this mistake? That is in conflict with Simon Marlow's principle: "If a program is going to crash, it should crash as soon, as noisily and as often as possible.".

**Comment by hanjoosten** [comment]
Yes, I saw that. Did you see my comment? Now we have the following issue:
If ONE is a concept in the context, and each concept has a type, what is the type of ONE? This is a special type, i guess. No other concept can have the type of concept ONE. This is a similar issue as the name of the concept ONE..
