### ISSUE TITLE
reference to rule is uncomprehensible for students

### ISSUE THREAD

**Issue by EstherHageraats** [AmpersandTarski/Ampersand#701]
The rules in the student's code are referred to in the diagnoses, func. spec and the violation messages. The reference is very ugly. (see picture) Can something be done about it?
![schermafdruk 2017-09-22 13 46 55](https://user-images.githubusercontent.com/18698059/30744378-1e844420-9fa2-11e7-9200-ce6ee9db6f3c.png)

**Comment by hanjoosten** [comment]
Very ugly indeed. This is because Ampersand has been forced to name the rule itself. The easiest way to avoid this is by giving a name to the rule, by supplying a label. (see the [syntax of RULE](https://github.com/AmpersandTarski/documentation/blob/master/syntax/rule.md) ).
