### ISSUE TITLE
in RAP3 "IN ENGLISH" creates incorrect documentation

### ISSUE THREAD

**Issue by EstherHageraats** [AmpersandTarski/Ampersand#702]
I have generated diagnoses doc and func.spec for the HAWAII case.
When the context is IN ENGLISH the purpose and meanings are reported as being absent. Also "losse eindjes" is emtpy.
When the context is changed into IN DUTCH the elements that are there are correctly printed in the documents. "losse eindjes" is filled.

We could tell students to use IN DUTCH, but it might depend on things I don't know about.
[FS Hawaii IN  DUTCH.pdf](https://github.com/AmpersandTarski/Ampersand/files/1324526/FS.Hawaii.IN.DUTCH.pdf)
[FS Hawaii IN  ENGLISH.pdf](https://github.com/AmpersandTarski/Ampersand/files/1324527/FS.Hawaii.IN.ENGLISH.pdf)

**Comment by hanjoosten** [comment]
This is actually the way it works. Keep in mind that if you specify IN ENGLISH in your script, you actually say that all textst you write there are the English ones, which could be OK. (Ampersand cannot tell the language of some string. We leave that to Google Translate...). 
At the command line, Ampersand.exe has a switch that you can use to ask to create documentation for a given language. RAP3 uses Dutch for all output. It will simply ignore all texts that are not Dutch. 
I hope this helps you understand this behaviour. 
The easiest way is not to tell the students anything about the IN ENGLISH or IN DUTCH. There is no need for them to know, and it could be confusing. Also see issue #587 , in which we made it optional.

**Comment by stefjoosten** [comment]
See https://ampersandtarski.gitbooks.io/documentation/content/syntax/languages.html for the complete picture.
