### ISSUE TITLE
Atlas button not active in RAP3

### ISSUE THREAD

**Issue by EstherHageraats** [AmpersandTarski/Ampersand#703]
I am not sure if this is a bug, but there is a button named "Atlas", but I cannot do anything with it.

**Comment by stefjoosten** [comment]
This is a bug allright. It will work in the next release of RAP3. I fixed this a while ago, but the release is still waiting on a major bugfix Han is working on.

**Comment by EstherHageraats** [comment]
In RAP3 version of 22 nov 2017 the button is gone.

**Comment by Michiel-s** [comment]
Could we agree not to open RAP specific issues/topics/discussions in the Ampersand repo? Maybe good to (re)open this issue in the [RAP repository](https://github.com/AmpersandTarski/RAP).
