### ISSUE TITLE
Funny session number substitutes text '_SESSION' in the script being edited

### ISSUE THREAD

**Issue by EstherHageraats** [AmpersandTarski/Ampersand#707]
I have been making a model, trying it out, recreating the protoype several times with minor changes in the interface definition.
At one point I deleted a column from a tab-definition.
Recompile.
Launch prototype.
To my surprise the heading of the column is still there,  but the fields are gone.
Because the heading of the column is no longer present in the ampersand script, I assumed it must be a cache-problem. So I deleted all history from the browser and tried to launched the prototype again. 
The RAP3 window was still active when I did this. I had to login again. 
I recompiled and launched the proto.
Now the prototype doesn't have any data and reinstalling database doesn't solve this problem. It can't seem to find the stuff.

Now I think I have compromised the account. And this is the second one. My previous account is compromised because I have a script it cannot find and cannot delete either. 
So I have now two broken accounts: 123456789 and 13628934. If you need the password to try them out, let me know.
To be complete, I also add the script itself.
[Enrollment.txt](https://github.com/AmpersandTarski/Ampersand/files/1362774/Enrollment.txt)

**Comment by EstherHageraats** [comment]
OK, I know a little bit more now.
The first line in the interface definition is:
INTERFACE Overview : 'd094c3a52113a0a44afcb47e2ba48d52'                  cRud
I had never added that 'number'. I have replaced it with _SESSION and recompiled the script.
It works again as it should. the _SESSION is again replaced with a 'number'.

**Comment by stefjoosten** [comment]
I have run into the same thing and I have learned to work around it the same way you do. Of course, it is weird that RAP3 substitutes the word "_SESSION" for the actual session identifier (which is the long number you saw) in your editor. It is a computer that edits things for you!

This is clearly a bug of the category beginner-friendly

**Comment by stefjoosten** [comment]
@Michiel-s and @hidde-jan,
I have assigned this issue to you, hoping you have some time to solve this, or at least diagnose it properly. Today, @EstherHageraats ran into this issue for a second time.

**Comment by hidde-jan** [comment]
I don't really have enough knowledge about the prototype code to fix this issue. Hopefully @Michiel-s knows more.

**Comment by Michiel-s** [comment]
I've fixed this bug. See pull request #721

**Comment by Michiel-s** [comment]
Is the solution tested? Can we close the issue?
