### ISSUE TITLE
CamelCase or underscores?

### ISSUE THREAD

**Issue by EstherHageraats** [AmpersandTarski/Ampersand#709]
The diagnoses and functional specification don't handle underscores very well. 
If this is  a staying feature, I suggest to advice to use CamelCase a coding convention.

**Comment by stefjoosten** [comment]
It it wise to advise students to use alphanumeric characters only. Hence, camelcasing is the obvious way to go.
At the moment we even have a bug: if you use diacritics in the name of a relation, the compiler will compile but running the prototype crashes with an incomprehensible error. For this reason too: stick to alphanumerics for now.

**Comment by Michiel-s** [comment]
Could we agree not to open RAP specific issues/topics/discussions in the Ampersand repo? Maybe good to (re)open this issue in the [RAP repository](https://github.com/AmpersandTarski/RAP)
