### ISSUE TITLE
More visual information in buttons

### ISSUE THREAD

**Issue by EstherHageraats** [AmpersandTarski/Ampersand#710]
The four buttons Diagnoses, Func.Spec, Atlas and Protoype are not real buttons.
They are more like checkboxes. Clicking them twice will uncheck the command and at save nothing happens.
Is it possible to get some visual comfirmation of the action? E.g. make them real checkboxes or change the appearance when checked.

**Comment by stefjoosten** [comment]
@hidde-jan , @Michiel-s ,
I noticed when using Ampersand, the behaviour with or without the SAVE button (i.e. auto commit changes and auto save changes) can vary a lot. This issue shows an example where the user has used the four buttons in a situation with both switches off. (Is that correct @EstherHageraats ?)
Clearly, these buttons were designed for use with both switches on.
Opinions?

**Comment by RieksJ** [comment]
Clicking a button toggles the value of an ampersand [PROP] relation. So, naturally, clicking a button twice restores the setting of that relation as it was before clicking it twice.

The `<PropertyButton>` template has been made in the full awareness that it does not function like you would like it to. 'Real' buttons will have to wait until the interface-stuff is being redesigned, as was discussed in the &-meeting some time (years?) ago, when we discussed unifying the interfaces for views, interfaces and violations. It works 'as is'.

Here is an example of how you can use buttons to show different views in an interface. It assumes that both switches are 'on' :
~~~
sessionShowIntObjReq :: SESSION * SESSION [PROP] -- Show internal objectives

INTERFACE "Objectives": '_SESSION'[SESSION] cRud BOX <ROWSNL>
   [ "Select Buttons" cRud BOX <COLSNL>
      [ "Hide Internals":   sessionShowIntObjReq cRud BOX <PropertyButton> [ hide: sessionShowAllObjReq cRud, property: sessionShowIntObjReq cRUd ]
      , "Show Internals": I-sessionShowIntObjReq cRud BOX <PropertyButton> [ hide: sessionShowAllObjReq cRud, property: sessionShowIntObjReq cRUd ]
      ]
   , "Row:Internals" : sessionShowIntObjReq INTERFACE "ShowInternalObjectives"
   ]
~~~
If this poses any questions, please ask.

**Comment by Michiel-s** [comment]
Could we agree not to open RAP specific issues/topics/discussions in the Ampersand repo? Maybe good to (re)open this issue in the RAP repository.

Buttons are process oriented. Ampersand models are information/data/state oriented. Rieks improvised a button template using relations with the property characteristic (PROP). If we want native support for buttons, we should first discuss if and how this should be reflected in the Ampersand language before we can work on the UI/interaction design.
