### ISSUE TITLE
!fatal - Cannot use diamond operator "<>" - called from AbstractSyntaxTree.hs

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/Ampersand#712]
I compiled the following script using Ampersand-v3.8.8 [development:dba3a29]:
~~~
CONTEXT Bug

CONCEPT Entity "something that is known to exist"
CONCEPT Identifier "combination of a Namespace and a Symbol that identifies an entity"
CONCEPT Namespace "a set of entities, each of which can be identified within that set by a Symbol" 
CONCEPT Symbol "name/label/... by which an entity can be identified within a Namespace" 
REPRESENT Symbol TYPE ALPHANUMERIC

--[Identifiers]
IDENT Identifiers: Identifier(idfrNS,idfrID)
idfrNS     :: Identifier * Namespace [UNI] -- Namespace within which the Symbol can be dereferenced
idfrID     :: Identifier * Symbol [UNI] -- Symbol (bitstring) that identifies an Entity within (the set of Entities within) the Namespace
idfrEntity :: Identifier * Entity [UNI] -- Identifiers that allow references to the Entity to be dereferenced

--[Statements]
CONCEPT Statement "something stated about an Entity, which is represented by the combination of (SubjID,Predicate,LDGraph)"
CONCEPT LDGraph "representation of everything that is stated about the Subject in a Statement"
REPRESENT LDGraph TYPE ALPHANUMERIC

stmSubject     :: Statement * Entity [UNI,TOT] -- the Entity that is the subject of the statement
stmSubjNS      :: Statement * Namespace [UNI] -- the Namespace within which the SubjID can be dereferenced (to an Entity)
stmSubjID      :: Statement * Symbol [UNI,TOT] -- the Symbol to be dereferenced into the Subject
stmLDGraph     :: Statement * LDGraph [UNI] -- the stuff that is stated about the statement's subject 

RULE "Subject identifiers in a Statement must be dereferenceable as Entitys":
  stmSubject = (stmSubjNS<>idfrNS~ /\ stmSubjID;idfrID~);idfrEntity

ENDCONTEXT
~~~
Doing so produces the error:
~~~
!             Ampersand-v3.8.8 [development:dba3a29]
Cannot use diamond operator "<>") expression l of type [Statement*Namespace]
   EDcD stmSubjNS[Statement*Namespace]
   with expression r of type [Namespace*Identifier]
   EFlp (EDcD idfrNS[Identifier*Namespace]).
CallStack (from HasCallStack):
  fatal, called at src\Ampersand\Core\AbstractSyntaxTree.hs:612:39 in ampersand-3.8.8-3mTqaTKPAI36OTa824xsLN:Ampersand.Core.AbstractSyntaxTree
~~~

**Comment by sjcjoosten** [comment]
Can you try again with the new version?
It would be nice to add this as an isolated test script too, it seems <> is not tested much.

**Comment by RieksJ** [comment]
This seems to work. Thanks.

**Comment by RieksJ** [comment]
@hanjoosten can you add the script to wherever it is that it needs to be put?

**Comment by hanjoosten** [comment]
It sure is a good idea to add this script to the tests. In this case, the script works, so it can be added to the Travis test cases. These testcases are stored in an appropriate subdirectory of `testing\Travis`.

There is a README.md file in that directory, explaining how the different kind of tests are executed. Basicly, every testcase in Travis has three properties:

1. A script. This must be in a file with the extention `.adl`.
2. A command. This is the command the script should be run against.
3. An expected outcome. Currentyl this can be succes or fail.

.adl files that have both the command and the expected outcome in common, can be grouped together in the same subdirectory. The command and outcome are specified in a file called `testinfo.yaml` in that directory. Travis will run the specified command with each file in the directory that has the .adl extention. 

That's all. Go ahead and try it out with your script.

**Comment by stefjoosten** [comment]
Good work, @sjcjoosten . I think your intervention was right on the spot!

At the same time, the wrap-up of this issue is not something we can be proud of.
@sjcjoosten says it would be nice to add this as an isolated test script.
@RieksJ asks Han to add the script to wherever it is that it needs to be put.
@hanjoosten explains how to do it and reassigns Rieks, who then closes the issue....

\<here is some space to add your own emoticons\>

I have just now added this script, Issue712, to travis, after checking that it exhibits the bug in old versions and it succeeds in the current one.

**Comment by RieksJ** [comment]
@stefjoosten: So what is it that you are not proud of?

**Comment by stefjoosten** [comment]
Sorry guys! I missed the fact that @RieksJ actually added this test case (...\testing\Travis\testcases\Bugs\Fixed\Other\Bug_DiamondOperator.adl) to Travis. I didn't read that from the discussion above and I didn't check it in the repo. Shame on me...
