### ISSUE TITLE
Blobs as Atom

### ISSUE THREAD

**Issue by stefjoosten** [AmpersandTarski/Ampersand#717]
On October 21st, 2017, @EstherHageraats got a PHP-error in RAP3, when editing her script "Enrollment" (issue AmpersandTarski/RAP#30). She said:

> I change some code, click on "beware to save..." and the counter on the error message "DelAtom() expects 2 arguments, but you provided 10" increases and no changes have been saved.

**Comment by stefjoosten** [comment]
@EstherHageraats could you please supply the Ampersand script "Enrollment" for us to test with?

**Comment by stefjoosten** [comment]
# Analysis
In the Ampersand database, the full text of a script (or any other blob, for that matter) is inserted in a concept table. Ampersand assumes that equality is defined on any atom, even on blobs. In theory that is fine; in practice, it causes trouble.

I would not like to restrict the use of blobs, but a fact is that the assumption of defined equality is not realistic for all atoms. And it is not necessary too, because blobs (e.g. movies, sound recordings) can better be stored as attribute than as key in a database. @sjcjoosten is experimenting with atoms of different algebras. That would include atoms on which equality is not defined. Should we go as far as that to get an acceptable solution to this problem in Ampersand?

Opinions please... (Sebastiaan?...)

**Comment by Michiel-s** [comment]
The solution to this particular problem is probably easier. I think there is a typo in the ExecEngine rule. The arguments for the exec engine rule are separates by a semicolon. The error message explains that to many arguments are passed to the DelAtom function. Another issue might be that the Ampersand script being saved is itself provided as argument in the function. In that case any semicolon character in the script will mashup the execengine function as well. There is a solution for this using a rule specific delimiter. After the {EX}, before the function name, you specify the delimiter. E.g. `VIOLATION(TXT “{EX}$;DelAtom$;argument 1$;etc”)`

Let me know of you need any further help with this issue.

**Comment by RieksJ** [comment]
Not being an expert in formalisms, I still do think that an Ampersand context should only contain references to entities that are known to exist with a CONTEXT. Dirty identifiers qualify as such, and so do numbers (integers and other kinds). Files (in general) do not. They ARE entities, within a CONTEXT, we should only have references to them. I guess this is the (old) discussion of whether an atom is a reference to an entity that is known to exist within a context, or such an entity itself.

**Comment by stefjoosten** [comment]
Sebastiaan and I have developed some theory to tackle this issue more fundamentally. This is documented in issue #722. I'm closing this issue here, because considerations of practice seem to obscure what is going on. In issue #722 "Concepts without equality", we discuss a relaxation of Ampersand's built-in assumption that should tackle this issue in an upward compatible way, based solely on good theory.
