### ISSUE TITLE
Bug in normalizer causes wrong SQL code of conjunct of SYM rule

### ISSUE THREAD

**Issue by Michiel-s** [AmpersandTarski/Ampersand#72]
If I make statement `elmMapping :: Element * Element [SYM]`

In Generics.php I get: 
``` 
$allRules =
  array
    ( 'SYM elmMapping::Element*Element' =>
        array ( 'name'          => 'SYM elmMapping::Element*Element'
              , 'ruleAdl'       => 'elmMapping = elmMapping~'
              , 'origin'        => 'line 40:25, file "C:\\\\Users\\\\stornebrinkmhm\\\\AppData\\\\Local\\\\My Local Documents\\\\Ampersand\\\\T4SMM\\\\SMM-Ontology.adl"'
              , 'meaning'       => 'elmMapping[Element] is symmetric'
              , 'message'       => 'elmMapping[Element] is not symmetric'
              , 'srcConcept'    => 'Element'
              , 'tgtConcept'    => 'Element'
              , 'conjunctIds'   => array ('conj_23')
              , 'pairView'      =>
                  array
                    ()
              )
``` 
so far so good. But if I look at conj_23 i see:
```
$allConjuncts =
  array
    ( 'conj_23' =>
        array ( 'signalRuleNames' => array ('Symmetry of mappings, add mapping')
              , 'invariantRuleNames' => array ('SYM elmMapping::Element*Element')
              , 'violationsSQL' => '/* this will quaranteed return 0 rows: */
                                    select
                                    distinct
                                           a as src, a as tgt
                                    from (/* Select nothing... */
                                          select 1 as a)
                                         as nothing
                                    where a <> 1'
              )
```
There is some 'dummy' sql code here, which will never result in an violation. The SYM rule is thus not checked.

**Comment by hanjoosten** [comment]
The generated SELECT statements assume that the database is created and maintained by Ampersand itself. This enables optimalisation of SELECT statements. If for any reason a SELECT statement is trying to read the violations of an invariant, then under these assumptions we KNOW that no violations can exist. As you discoverd, the optimizer does a good job at this....

**Comment by Michiel-s** [comment]
Hi Han,
I think we don't understand each other. Maybe I'm missing something about how symmetric relations work.

If `elmMap :: Element * Element [SYM]`

Say I insert tuple elmMapping(Elm1, Elm2) and close the transaction, I would expect a rule violation that says 'elmMapping[Element] is not symmetric', because elmMap(Elm2, Elm1) is not there. But this rule cannot be evaluated if there is no sql query provided.

**Comment by hanjoosten** [comment]
Michiel, I think you are right. There is something in the entire chain that doesn't make sense. I have taken a look at what goes on in Database.php. (My php isn't that good, but I think I get a feeling about what goes on there). It seems to me that a couple of conjunctViolations is tested for the invariants. This only makes sense, if the assumptions by which the SQL is generated, that I mentioned before, are not taken for granted. In that case, other SQL must be generated. Of course, there could be a flaw in this reasoning. Let's ask @stefjoosten and/or @Oblosys to comment on this.

**Comment by hanjoosten** [comment]
I had a brief chat with Stef. He remembered that this is an [old bug, as you can see on our previous ticket system](http://sourceforge.net/p/ampersand/tickets/396/ ). It is a bug in the normalizer. So it still is Stef who could best look into it.

**Comment by Michiel-s** [comment]
@stefjoosten any updates on this ticket?

**Comment by Michiel-s** [comment]
Again, I run into this bug. I'm giving this issue a higher prio. Maybe for next sprint?

**Comment by stefjoosten** [comment]
I have a hunch. As you know, a univalent relation `r`  is represented as a column in a wide table. In that column there is room for no more than one value per key atom. Thus, univalence is guaranteed at all times, even without guarding it. Suppose however, that you designate this univalence to a role `R`. This tells Ampersand that violations should be signalled to role `R`. That will never happen, given the fact that relation `r`  is represented as a column.

It is clear that relation `r` should be represented in a separate (binary) table instead. So I'll try to fix that. @Michiel-s, is my analysis consistent with the symptoms you have observed?

**Comment by Michiel-s** [comment]
I don't think that will do the trick. It's about the SYM rule conjuct. Not UNI. I think there should be an sql rule which checks this invariant but querying all violations (i.e. tuples in r that are not in r~ and the other way around). Or am I missing something?

**Comment by stefjoosten** [comment]
Han was right. It turns out to be a bug in the normalizer. As far as I can tell, I have fixed the bug correctly. As a consequence, generated code in interfaces may turn out to be less efficient. I have not yet looked into that.

**Comment by stefjoosten** [comment]
@Michiel-s , maybe you want to take a look at this before closing this issue.

**Comment by RieksJ** [comment]
I would like to draw you attention to the following rule
~~~
addrIsAtSameLocationAsAddr :: DutchAddr * DutchAddr [RFX,SYM,TRN]
ROLE ExecEngine MAINTAINS "RFX[addrIsAtSameLocationAsAddr]"
RULE "RFX[addrIsAtSameLocationAsAddr]": I[DutchAddr] |- addrIsAtSameLocationAsAddr
VIOLATION (TXT "{EX} InsPair;addrIsAtSameLocationAsAddr;DutchAddr;", SRC I, TXT ";DutchAddr;", TGT I)
~~~
If this rule were to be violated, I would expect one of two things to happen:

1. if the violation were actually fixed, I would expect the violation not to reappear in subsequent runts.
2. if the violation were not fixed, I would expect the violation to be detected immediately, which would then lead to an error after 10 runs.

However, neither of these things do actually happen, as is shown by the following exec-engine log that was produced when exercising the QBox application:
<img width="960" alt="picture1" src="https://cloud.githubusercontent.com/assets/8522589/17846198/8206784e-6847-11e6-8495-4d1b7c570c94.png">

**Comment by Michiel-s** [comment]
The following script 
```adl
CONTEXT Issue72 IN ENGLISH

  r :: A * A [SYM]

ENDCONTEXT
```

produces the following conjunct output:
```json
[
    {
        "signalRuleNames": [],
        "violationsSQL": "select t1.src as src, t1.tgt as tgt from (select \"SrcA\" as src, \"TgtA\" as tgt from \"r\" where (\"SrcA\" is not null) and (\"TgtA\" is not null)) as t1 left join (select \"TgtA\" as src, \"SrcA\" as tgt from \"r\" where (\"SrcA\" is not null) and (\"TgtA\" is not null)) as t2 on (t1.src = t2.src) and (t1.tgt = t2.tgt) where (t2.src is null) or (t2.tgt is null) union distinct select t1.src as src, t1.tgt as tgt from (select \"TgtA\" as src, \"SrcA\" as tgt from \"r\" where (\"SrcA\" is not null) and (\"TgtA\" is not null)) as t1 left join \"r\" as t2 on (t1.src = t2.\"SrcA\") and (t1.tgt = t2.\"TgtA\") where (t2.\"SrcA\" is null) or (t2.\"TgtA\" is null)",
        "invariantRuleNames": [
            "SYM r[A]"
        ],
        "id": "conj_0"
    }
]
```

taking a closer look at the generated sql query:
```sql
select t1.src as src, t1.tgt as tgt 
from (
    select "SrcA" as src, "TgtA" as tgt 
    from "r" 
    ) as t1 
left join (
    select "TgtA" as src, "SrcA" as tgt 
    from "r" 
    ) as t2 
on (t1.src = t2.src) and (t1.tgt = t2.tgt) 
where (t2.src is null) or (t2.tgt is null) 

union distinct 

select t1.src as src, t1.tgt as tgt 
from (
    select "TgtA" as src, "SrcA" as tgt 
    from "r" 
    ) as t1 
left join "r" as t2 
on (t1.src = t2."SrcA") and (t1.tgt = t2."TgtA") 
where (t2."SrcA" is null) or (t2."TgtA" is null)
```

all looks good! the first left join selects those pairs that are in r but not r~, the second join checks this the other way around. the union combines the result.

I think one of the joins can be omitted, because the SYM property can only be set for endorelations. But this is an optimization issue.

**Comment by Michiel-s** [comment]
Together with @RieksJ I will look at his issue with a specific rule mentioned above. 

I consider this issue fixed. Thx @stefjoosten
