### ISSUE TITLE
Bug introduced by new Atom-syntax

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/Ampersand#724]
The following script worked earlier on. However, with the introduction of `Ampersand-v3.9.0 [development:58fd4a8]`, i.e. an Ampersand version that has fixed #713 and #716, a bug was introduced:
~~~
CONTEXT Bug724

POPULATION Account CONTAINS [ "MyAccount" ]

sessionAccount :: SESSION * Account [UNI]

ROLE ExecEngine MAINTAINS "Always login using 'MyAccount'"
RULE "Always login using 'MyAccount'":
   "MyAccount"[Account] /\ V;("_SESSION"-sessionAccount;sessionAccount~);V |- -V
VIOLATION (TXT "{EX} InsPair;sessionAccount;SESSION;", SRC V;"_SESSION"[SESSION], TXT ";Account;", TGT I)

ENDCONTEXT
~~~
The intention of this script is to automatically assign `MyAccount` as the sessionAccount of any session. The rule does fire, but `sessionAccount` does not get populated, because the expression `V;"SESSION"[SESSION]` evaluates to `NULL`. Thus, the violation is not resolved and the execengine terminates after 10 runs. All this can be seen by inspecting the execengine log:

![image](https://user-images.githubusercontent.com/8522589/33547524-a182022e-d8e4-11e7-82b5-b53409073734.png)

**Comment by hanjoosten** [comment]
My impression is that this is somewhere in the execengine code. Maybe we could look at this together, @Michiel-s ?

**Comment by Michiel-s** [comment]
I think this has to do with #721 . I'll take a look.

**Comment by RieksJ** [comment]
The bug has not gone away (using Ampersand-v3.9.0 [development:58fd4a8]).
