### ISSUE TITLE
Fatal: after checking everything an unhandled singleton value found!

### ISSUE THREAD

**Issue by stefjoosten** [AmpersandTarski/Ampersand#725]
# Symptom
@ellekebaecke showed me a bug, which I can reproduce. This bug is urgent, because this bug is in a distributed version of the compiler. So it also exposes a flaw in our automated testing procedure.

I compiled `D:\git\ampersand-models\MirrorMe\MiniMirrorMe.adl` using Ampersand-v3.9.0 [master:fb042c8], build time: 28-Nov-17 09:05:15

I expected the compiler to work as intended. However, I got a compiler error:
![afbeelding](https://user-images.githubusercontent.com/275768/33765604-ec10dc06-dc19-11e7-93dd-1f81ecbea114.png)

**Comment by stefjoosten** [comment]
# Analysis
The compiler fails when compiling the (internally stored) FormalAmpersand files. This points towards a meatgrinder issue.

**Comment by hanjoosten** [comment]
I have done some experiments and concluded that this error is due to the xlsx parser. In this particular case, there is an integer in the xlsx file (excel) that is parsed as being a string. This is wrong of course. It will be fixed in the next release.

**Comment by hanjoosten** [comment]
The previous observations pointed me in the wrong direction. This seems to be deeper. It might be even in the typechecker!

**Comment by hanjoosten** [comment]
The fatal shouldn't appear. I have created issue #726 for that. However, that is only part of the problem.

**Comment by hanjoosten** [comment]
I have done some more diagnosis. If @sjcjoosten will resolve issue #726, this issue will be gone too. Therefor, this issue can be closed. 

@ellekebaecke , I have fixed the faulty script in your branch of ampersand-models. If you use that, you will not run into this bug any more.
