### ISSUE TITLE
Fatal caused by lack of typechecking of singleton values

### ISSUE THREAD

**Issue by hanjoosten** [AmpersandTarski/Ampersand#726]
#### Version of ampersand that was used 
Ampersand-v3.9.0 [feature/issue725:e1f65fcf1] 
this version gives a more elaborate fatal message, but the bug is present since the implementation of technicaltypes.

#### What I expected
A fatal message must not appear at runtime. When there is a type error, I like the typechecker to catch it.

#### What happened instead
I got the following fatal message:

~~~~
This should be impossible: after checking everything an unhandled singleton value found!
  Concept: B
  TType: INTEGER
  Origin: line 7:8, file C:\Users\hjo20125\Ampersand\Issue726.adl
  PAtomValue: ScriptString ("Aap")
CallStack (from HasCallStack):
  fatal, called at src\Ampersand\Core\AbstractSyntaxTree.hs:792:16 in ampersand-3.9.0-1IA3yQkHeEpBWAjW4jnYiv:Ampersand.Core.AbstractSyntaxTree
~~~~

#### Steps to reproduce
Try to create a prototype with the following script

#### Context / Source of ampersand script

~~~~
CONTEXT Test
   RELATION r [A*B]
   REPRESENT B TYPE INTEGER
   RULE r;"Aap"
ENDCONTEXT
~~~~

**Comment by hanjoosten** [comment]
@sjcjoosten , this issue is reported quite often now. Do you have time to fix it?

**Comment by sjcjoosten** [comment]
I fixed this, but got a conflict in the developer branch. My changes were quite a major rewrite, so please don't let this get stale!

**Comment by sjcjoosten** [comment]
Ahh sorry for fixing this in the wrong repository... I feel quite annoyed with myself cause it was a major rewrite. I'll try again later

**Comment by hanjoosten** [comment]
@sjcjoosten , maybe we can save your work by having a skype session in which we merge your work?
