### ISSUE TITLE
Bugs in generated database structure and population queries

### ISSUE THREAD

**Issue by Michiel-s** [AmpersandTarski/Ampersand#729]
**Missing single quotes**
Somewhere between Ampersand v3.8.7 and the current development branche a change is made to the way atoms are represented in the default population queries (output in mysql-installer.json). An atom of a concept with DATE representation was put between single quotes, as is required by mysql because we use a `-` between year, month and day (see [mysql documentation](https://dev.mysql.com/doc/refman/5.7/en/date-and-time-literals.html)). However, these single quotes are not their anymore, causing the initial population to produce an error. Please check if this is an issue for other representations as well.

**Issue with newline character**
Furthermore, I've noticed newline characters `\n` in both the allDBstructQueries as allDefPopQueries (in mysql-installer.json). These shouldn't be there.

**Comment by hanjoosten** [comment]
The quoting syntax has been modified for good reason. See issue #713. However, it introduced this bug with DATA fields. This is fixed with commit 0eb7e6ba2ec25ff66c65e89ddb7a6e6dd3844f4b . Other representations should be fine.

**Comment by Michiel-s** [comment]
@hanjoosten, thx. Is it also possible to remove the new line characters?

**Comment by hanjoosten** [comment]
Working on that. expect it fixed tomorrow

**Comment by Michiel-s** [comment]
Ah, maybe you could wait with that, because it is not blocking the installer and I have another related request #730 (now writing)

**Comment by hanjoosten** [comment]
Fixed with commit a1883d863172e6f1084c2bb6c91a7fa5ee8238b6

**Comment by Michiel-s** [comment]
Thx!

**Comment by Michiel-s** [comment]
I believe you've introduced another bug.

The output of the default population in mysql-installer.json queries is incomplete. The values part is missing.

E.g.
```json
"allDefPopQueries": [
        "INSERT INTO \"Date\" (\"Date\") VALUES ",
        "INSERT INTO \"Description\" (\"Description\") VALUES ",

```

**Comment by hanjoosten** [comment]
Oops, I tested the prettyprinted version only :( Sorry!. The fix is directly in development, because I had merged the feature branch already in there.
