### ISSUE TITLE
Discussion about Atoms.adl

### ISSUE THREAD

**Issue by hanjoosten** [AmpersandTarski/ampersand#73]
In the recent version of Atoms.adl, there are some things that need attention. @stefjoosten, please elaborate on each of the following remarks:

1. The derived relation `type` is TOT. This cannot be derived, because l and r are not SUR
1. How can a Pair exist without knowing in what relation it is? Could you give an example of the usefullness of it? Does this have anything to do with storing of deriving pairs?
1. Since Pair is in the *core* part of the pattern, it seems to suggest that all instances of pair must be persistent. That seems obvious for pairs in declared relations. However, pairs in non-primitive expressions, will likely be calculated.

**Comment by stefjoosten** [comment]
I would like to prove that {{type}} is univalent, just because it is derived.

Also, I would like to study the conditions under which {{ttype}} is total.

I just haven't had the time to do it yet. It is likely that little changes in Atom.adl emerge from such exercises, which is baaed on past experience.

**Comment by stefjoosten** [comment]
A pair exists inside a relation. In my mind it makes no sense to talk about a pair outside a relation.

**Comment by stefjoosten** [comment]
I am not sure how to treat pairs that are intermediate results in AST.adl. In all cases, the type of an intermediate atom is known, whether persistent or not. So I don't see any reason yet to make intermediate results persistent.

**Comment by hanjoosten** [comment]
With the current definition, I disagree that the type is known in all cases. For that to be true, the relations **l[Pair * Atom]** and **r[Pair * Atom]** should be ***TOT***, which is not the case in your Atoms.adl
Also, I think that **in[Pair * Relation]** should be ***TOT*** by definition.

**Comment by hanjoosten** [comment]
Currently, if you create a prototype with the --ast-tables flag, the things in your script will also be generated in the database. There is an interface showing the atoms, pairs etc. This could be helpfull in understanding the relations. Also some violations are given. Use Stef as role... ;-))
It is possible to modify the interface. To do so, use these steps:

*  Just edit the interface in AmpersandData/FormalAmpersand/ASTInterface.ifc. 
* Make sure that it is valid. (that can be tested by compiling AST.adl in that same directory)
* cabal install (when ampersand is installed, the files in FormalAmpersand will be copied to their proper places)

**Comment by stefjoosten** [comment]
Han, please do a review on Atoms.adl

Rieks, feel free to experiment with Atoms.adl, because I have included some exec-engine stuff in it.

**Comment by hanjoosten** [comment]
I reviewd Atoms.adl and added my comment directly in it. @stefjoosten have a look!
