### ISSUE TITLE
Request to change the output of generated database installer files

### ISSUE THREAD

**Issue by Michiel-s** [AmpersandTarski/Ampersand#730]
Currently the mysql database structure and default population is generated and put in generics/mysql-installer.json.

This issue request to change this output as commit in the refactor_ifc branch.

What I would like is to have a `database.sql` file containing the database structure only. This file must be formatted as sql and can have comments, new lines, etc. @hanjoosten I believe that you already have functionality for this in the Haskell code like with the --sql-dump switch. An example:
```sql
--
-- Table structure for table `project`
--
CREATE TABLE "Project"
    ( "Project" VARCHAR(255) UNIQUE NOT NULL /* OBJECT */
    , "projectName" VARCHAR(255) DEFAULT NULL /* ALPHANUMERIC */
    , "projectStatus" VARCHAR(255) DEFAULT NULL /* ALPHANUMERIC */
    , "projectDescription" TEXT DEFAULT NULL /* BIGALPHANUMERIC */
    , "projectStartDate" DATE DEFAULT NULL /* DATE */
    , "projectActive" VARCHAR(255) DEFAULT NULL /* OBJECT */
    , "pl" VARCHAR(255) DEFAULT NULL /* OBJECT */
    , PRIMARY KEY ("Project")
    , "ts_insertupdate" TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP
    ) ENGINE = InnoDB DEFAULT CHARACTER SET UTF8 COLLATE UTF8_BIN, ROW_FORMAT = DYNAMIC;
```

For the default population I would like to have a `population.json` file containing the atoms and links for all concepts and relations. **Not** formulated as sql queries. The reason behind this is that I'm reintroducing a plug mechanism. When the default population is inserted via this way, all other plugs and components of the backend can also be notified. A suggestion for the population.json file:
This is exactly the same as the `metaPopulation.json` file when generated with --gen-as-rap-model
```json
{
    "atoms": [
        {
            "atoms": [
                "project1",
                "project2"
            ],
            "concept": "Project"
        },
        {  }
    ],
    "links": [
        {
            "relation": "name[Project*Name]",
            "links": [{
                    "tgt": "A project",
                    "src": "project1"
                },{}]
        },
       { }
    ]
}
```

@hanjoosten, if you also think this is a good idea would you do the haskell part, then I will do the php stuff.

**Comment by hanjoosten** [comment]
This shouldn't be too hard to do. I'll have a look

**Comment by hanjoosten** [comment]
@Michiel-s Any other requirements? Not totally satisfied with this fix? Let me know by reopening this issue.
