### ISSUE TITLE
Database initialization wrt ``localSettings.php``

### ISSUE THREAD

**Issue by stefjoosten** [AmpersandTarski/Ampersand#731]
When installing a production version of an application (e.g. RAP3), I want to block the possibility for reinstalling the database in the ``localSettings.php``. That works. However, if that database does not exist yet, it still works. Which results in a failure to install. Of course, I do not want to enable the reinstall database switch in ``localSettings.php``, because this is a production version. This behaviour is especially nasty when installing with docker, because everything has to be scripted. And I don't want an (error-prone) edit-action in a ``localSettings.php`` file somewhere in my docker scripts to fix this flaw.

**Comment by Michiel-s** [comment]
We’ve identified a solution, building a separate second prototype container with dev/admin privileges. Let’s not make this more complex.
