### ISSUE TITLE
Length of names of Concepts, Relations, ... should be tested before creating a prototype

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/Ampersand#737]
#### Version of ampersand that was used 
Ampersand-v3.9.0 [development:1f4819b]

#### What I expected
Here is part of a script that I used:
![image](https://user-images.githubusercontent.com/8522589/34726791-5132f890-f555-11e7-988d-6a60cd945bdb.png)

I would have expected either one of the following:

1. The compiler produces an error and/or warning message saying that the length of the name of the target concept of the relation `irContent` is too long to process.
2. A prototype that is generated from a script that defines this concept and that has no errors, will actually be able to create internal administration (database tables) for this concept and this relation.

#### What happened instead
![image](https://user-images.githubusercontent.com/8522589/34726966-c9c2b2d2-f555-11e7-83a9-8e8fa0a8442b.png)

**Comment by Michiel-s** [comment]
I plead again for solution as described in #708. A strict set of constraints implementeren in the Ampersand compiler for identifiers of all artefacts, including concepts, relations, views, rules, roles, etc

**Comment by stefjoosten** [comment]
I agree with Michiel. Restrictions of this type should be in Ampersand proper. They must not depend on implementation choices, to keep the semantics of Ampersand consistent across all kinds of implementations (including future ones)

**Comment by Michiel-s** [comment]
We’ll fix this in #708
