### ISSUE TITLE
Put InsAtom to good use

### ISSUE THREAD

**Issue by stefjoosten** [AmpersandTarski/Ampersand#738]
I have built a demo for distributed transactions. For this purpose, I needed a backend function ``InsAtom``. This function was present, using the following (existing) code: 

```
// Use: VIOLATION (TXT "InsAtom;<concept>") -- this may not be of any use in Ampersand, though.
function InsAtom($conceptName){
	Logger::getLogger('EXECENGINE')->info("InsAtom($conceptName)");
    if(func_num_args() != 1) throw new Exception("InsAtom() expects 1 argument, but you have provided ".func_num_args(), 500);
	try{
		$database = Database::singleton();
		
		$concept = Concept::getConceptByLabel($conceptName);
        $atom = $concept->createNewAtom();
		$atom->addAtom(); // insert new atom in database
		
		 Make newly created atom available within scope of violation for use of other functions
		ExecEngine::$_NEW = $atom;
		
		Logger::getLogger('EXECENGINE')->debug("Atom '{$atom->__toString()}' created and added to database");
		
	}catch(Exception $e){
		Logger::getUserLogger()->error('InsAtom: ' . $e->getMessage());
	}
	
}
```
I checked whether it is being used in Ampersand-models, only to find that it is used nowhere. So I changed the code of ``InsAtom`` to make ``Transactions.adl`` work as desired (see AmpersandTarski/ampersand-models@cbba890da73defc05e71deb58eb6193e0449b3cf).

The new code for ``InsAtom`` is:

```
// Use: VIOLATION (TXT "InsAtom;<concept>;<value>") -- this is used in ampersand-models/Transactions/Transactions.adl
function InsAtom($concept, $atomId){
	Logger::getLogger('EXECENGINE')->info("InsAtom($concept,$atomId)");
    if(func_num_args() != 2) throw new Exception("InsAtom() expects 2 arguments, but you have provided ".func_num_args(), 500);
	try{$database = Database::singleton();
		// if atom id is specified as _NEW, the latest atom created by NewStruct or InsAtom (in this VIOLATION) is used
	    if($atomId == "_NEW") $atom = ExecEngine::$_NEW;
	    else $atom = new Atom($atomId, Concept::getConceptByLabel($concept));
	    $atom->addAtom(); // insert new atom in database
                Logger::getLogger('EXECENGINE')->debug("Atom '{$atom->__toString()}' added to database");
	
	}catch(Exception $e){
		Logger::getUserLogger()->error('InsAtom: ' . $e->getMessage());
	}
	
}
```

@Michiel-s, would you please check this code (commit 7b073100358af91d45674060d4d749a71b155aad) for me? It works in my example, but I would appreciate you approval.

**Comment by RieksJ** [comment]
`InsAtom` exists (at least in Ampersand-v3.9.0 [development:1f4819b]), and it should.

It also has a practical use - it may/will result in the deprecation of the `NewStruct` function.

**Comment by Michiel-s** [comment]
I've adapted the InsAtom function for your use-case so it stays backwards compatible with the current situation. Furhermore I fixed some bugs, e.g. regarding setting the ExecEngine::$_NEW variable. This is needed because of what @RieksJ already mentioned, the replacement of NewStruct function.

I think this should work now. @stefjoosten can you confirm and close this issue?

**Comment by stefjoosten** [comment]
Yes, I've tested this on Transactions.adl compiled with Ampersand-v3.9.2 [development:ea192ec]. I can confirm closure of this item.
