### ISSUE TITLE
POPULATION statement and DATETIME

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/Ampersand#739]
#### Version of ampersand that was used 
I used `Ampersand-v3.9.0 [development:1f4819b]` to compile the following script:

~~~
CONTEXT Issue739
  ibtTime :: Issue * DateTime [UNI]     
  REPRESENT DateTime TYPE DATETIME
  POPULATION ibtTime CONTAINS [ ("Issue_739", "20181015") ]
ENDCONTEXT
~~~

#### What I expected
I expected it to compile correctly.

#### What happened instead
I got the following error:
~~~
Error at symbol () in file C:\Ampersand\Git\tno-models\ISTAR\Issue739.adl at line 4 : 47
  Representation mismatch
    Found: `"20181015"`,
    as representation of an atom in concept `DateTime`.
    However, the representation-type of that concept is
    defined as DATETIME. The found value does not match that type.
~~~
I have tried to replace the datetime atom with all sorts of other representations, with and without double quotes, but I keep getting this error message

#### Request
I would like that

- [ ] this bug gets fixed
- [ ] an error message that complains about incorrect type syntax to tell me what the correct syntax actually is.

**Comment by hanjoosten** [comment]
The error message says it all: The value that you supply is a ALPHANUMERIC, not DATETIME. What you probably intended is something like 

````
CONTEXT IssueX
  ibtTime :: Issue * DateTime [UNI]     
  REPRESENT DateTime TYPE DATETIME
  POPULATION ibtTime CONTAINS [ ("Issue_1", 2018-01-14T16:35:21+00:00) ]
ENDCONTEXT
````

**Comment by RieksJ** [comment]
For user-friendliness of beginners such as I, I would not only like that

- [x] this bug gets fixed (check)

but also that

- [ ]  the error message that complains about incorrect type syntax tells me what the correct syntax actually is (in this case, the example of 2018-01-14T16:35:21+00:00).

**Comment by hanjoosten** [comment]
Please provide a proposal for the error message. Take into account that we know the expected type (like ALPHANUMERIC, INTEGER, DATE, DATETIME etc. ). Alternatively (maybe better?) we could refer to a page in the documentation, [this one?](https://ampersandtarski.gitbooks.io/documentation/content/syntax/population.html) which should contain sufficient examples.

**Comment by RieksJ** [comment]
Both suggestions are nice to follow up on.

Where the error message says `However, the representation-type of that concept is defined as` and then the type, e.g. `DATETIME` or `ALPHANUMERIC`, the following text can be added for the various types. @hanjoosten: if this list is incomplete, please let me know which need to be added.

- [ ] `ALPHANUMERIC types are texts (max 255 chars) surrounded with double quotes ("-characters)`
- [ ] `BIGALPHANUMERIC types are texts (max 64k chars) surrounded with double quotes ("-characters)`
- [ ] `HUGEALPHANUMERIC types are texts (max 16M chars) surrounded with double quotes ("-characters)`
- [ ] `DATE types are defined by ISO8601, e.g. 2013-07-04`
- [ ] `DATETIME types follow ISO 8601 format, e.g. 2013-07-04T11:11:11+00:00 or 2015-06-03T13:21:58Z (without surrounding quotes).`
- [ ] `BOOLEAN types can have the value TRUE or FALSE (without surrounding quotes).`
- [ ] `PASSWORD types are texts (max 255 chars) surrounded with double quotes ("-characters)`
- [ ] `FLOAT types ???` <-- please see what Haskell does here, since I have no clue.
- [ ] `INTEGER types are decimal numbers (max 20 positions), e.g. 4711 or -4711 (without surrounding quotes)`

I hope that this is in fact what is happening (cannot say because while I took this info from the backend docs I have, this may differ from what Haskell does). Note that

**Comment by hanjoosten** [comment]
@RieksJ thanks for the list. Your wish is granted ;)
