### ISSUE TITLE
Reflexive ISA does not compile properly

### ISSUE THREAD

**Issue by stefjoosten** [AmpersandTarski/Ampersand#742]
I have used Ampersand-v3.9.0 [development:1f4819b*] to compile the following script:
```
CONTEXT Try55
CLASSIFY A ISA A
ENDCONTEXT
```

I expected this script to compile successfully, but the compiler terminates without generating any error message and without generating any code:
```
Ampersand-v3.9.0 [development:1f4819b*], build time: 09-Jan-18 23:23:34 West-Europa (standaardtijd)
Reading file D:\git\ampersand\testing\Travis\testcases\prototype\shouldSucceed\Try55.adl
Reading file SystemContext.adl (from within ampersand.exe)
```

I have saved this script in ``testing/Travis/testcases/prototype/shouldSucceed/Try55.adl``.
I have released it in branch ``sentinel/pending_bug``. Once the bug is fixed, this branch can be merged into branch ``development``.

**Comment by Michiel-s** [comment]
After issue #751, urgent request to quick fix a proper error message.

**Comment by hanjoosten** [comment]
I have a quickfix in place, and I created issue #752 for a structural fix. 

This issue now only is about fixing the typechecker, so that `CLASSIFY A ISA A` is allowed.
