### ISSUE TITLE
Add static checks on use of CRUD

### ISSUE THREAD

**Issue by hanjoosten** [AmpersandTarski/Ampersand#745]
Currently, it is possible to specify CRUD behaviour at several places in the INTERFACE statement. The semantics have been defined (see [the comment of @Michiel-s in issue #704](https://github.com/AmpersandTarski/Ampersand/issues/704#issuecomment-350472116)).

From the semantics some restrictions can be derived. e.g, it should not be possible to specify `D` for an expression `I` in an interface. There will be other _imposible_ cases. 
Also, there will be cases where a it is mandatory to have the upper case defined. e.g,It should not be allowed to specify cruD, in cases where D is allowed. The `r` should be uppercase in that case.

The derivation of this information should be done during compiletime. It should be made available in the .json file, so it can be used at the frontend too. The latter could be usefull when certain box-types are used, or maybe during the use of html templates. 

I am currently thinking of supplying this information together with each CRUD information. For every CRUD character I guess a value should be provided that indicates that is one of **_mandatory_**,  **_forbiden_** or **_optional_**
In cases that restrictions are violated, there will be a compile-time error. However, I still think this info could be benneficial for the front-end, because of the usage of html templates.

@Michiel-s what do you think? Do you agree that this info should go in the json file? Do you see good use for it? Any other thoughts?

**Comment by RieksJ** [comment]
If the compiler is going to check on such situations, PLEASE provide error messages that have the property that they help novice users to not only fix the error, but also in understanding why it is an error, e.g. by explaining it on the spot, or explicitly referring to the documentation using a hyperlink.

**Comment by Michiel-s** [comment]
@hanjoosten, I like the idea to raise compile time error for invalid crud specifications. Not sure yet whether there are really *mandatory* situations, but let's find out when defining the rules for this.

For the front-end generation we only need the outcome (i.e. the crud specification itself), not the indicators for mandatory, forbidden or optional. The same applies to the data model for the backend (.json files), only the outcome is relevant. Nothing needs to be done here. So I think it is parser/fspec only.

There are other interface restrictions the front-end implies that should raise an error, e.g.:
#### 1. It is not possible to have a non-object target concept for a root interface expression, e.g.
```adl
CONCEPT DateTime ""
REPRESENT DateTime TYPE DATETIME
-- The following interface is not supported (yet) in the front-end, due to the REST based web app approach
INTERFACE "Not allowed" : V[SESSION*DateTime] BOX []
```

**Comment by stefjoosten** [comment]
#### 3. From within a box, the root atom is read-only.

```
INTERFACE "Silly CRUD" : I[Person] CRUd
BOX [ name : name
    , "date of birth" : birthdate
    , SSN : socialSecurityNumber
    ]
```
I would expect the CRUd annotation to be cRud in this case, and nothing else. But I am not entirely sure why....

**Comment by RieksJ** [comment]
@stefjoosten: the `INTERFACE "Silly CRUD"` that you specified might be useful, e.g. for importing data from an excel file, in which case the upper case `C` would be mandatory, and the relations in the `BOX` should specify `cRUd`. This use of INTERFACEs is in contradiction with your expectations...

**Comment by hanjoosten** [comment]
Today I added an error message for non-OBJECT target concepts of interface expressions. Such an error message could be observed today in a travis-ci log:

```
Error at symbol () in file /home/travis/build/AmpersandTarski/Ampersand/testing/Travis/testcases/prototype/shouldSucceed/Issue163.adl at line 12 : 1
  The TYPE of the concept for wich an INTERFACE is defined should be OBJECT.
  The TYPE of the concept `A`, for interface `Issue163`, however is INTEGER.
```
