### ISSUE TITLE
The relations `changes[Act*Relation]` should be replaced

### ISSUE THREAD

**Issue by hanjoosten** [AmpersandTarski/Ampersand#748]
An action could als be to insert/delete a single atom. This is by modifying the population of `I`. In this case we have an Act, but it has no Relation that goes with it. 

Probably we need a relation `changes[Act*Expression]`, and only a subset of Expression.

**Comment by Michiel-s** [comment]
Since we had so many changes in formal ampersand model the past few years I think this issue is not relevant anymore.

Is it?

**Comment by hanjoosten** [comment]
This relation still appears in the current version of FormalAmpersand. It is wrong. @stefjoosten , did you have a look at it already?

**Comment by stefjoosten** [comment]
No I didn't. So let's keep it open and let me find out what the issue was... I'll revive or close.
