### ISSUE TITLE
Ampersand terminates erroneously but without any error message

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/Ampersand#751]
I have been compiling an extensive script ([ssif.zip](https://github.com/AmpersandTarski/Ampersand/files/1684621/ssif.zip)) using `Ampersand-v3.9.1 [development:b051de7]`.
I would expect it to either compile, or produce an error message that helps me to correct any mistakes.

When you type:
~~~
ampersand.exe KvK.adl  -p"C:\xampp\htdocs\KvK" & echo. & echo Errorlevel = %errorlevel%
~~~
the output is as follows:
~~~
Reading config file: ..\KvK.yaml
Ampersand-v3.9.1 [development:b051de7], build time: 16-Jan-18 15:24:12 W. Europe Standard Time
Reading file C:\Ampersand\Git\ssif\KvK.adl
Reading file C:\Ampersand\Git\ssif\KvK\KvK_SIAMv3_Module.adl
Reading file C:\Ampersand\Git\ssif\SIAMv3\SIAM_Module-versioning.adl
Reading file C:\Ampersand\Git\ssif\SIAMv3\SIAM_FrontendIntegration.adl
Reading file C:\Ampersand\Git\ssif\SIAMv3\SIAM_AccountSessionRoles.adl
Reading file C:\Ampersand\Git\ssif\SIAMv3\SIAM_PersonRefs.adl
Reading file C:\Ampersand\Git\ssif\SIAMv3\SIAM_PersonReg.adl
Reading file C:\Ampersand\Git\ssif\SIAMv3\SIAM_OrgRefs.adl
Reading file C:\Ampersand\Git\ssif\SIAMv3\SIAM_OrgReg.adl
Reading file C:\Ampersand\Git\ssif\SIAMv3\SIAM_PersonOrgs.adl
Reading file C:\Ampersand\Git\ssif\SIAMv3\SIAM_LoginWithUPW.adl
Reading file C:\Ampersand\Git\ssif\SIAMv3\SIAM_RegisterWithUPW.adl
Reading file C:\Ampersand\Git\ssif\SIAMv3\SIAM_LoginWithUID.adl
Reading file C:\Ampersand\Git\ssif\SIAMv3\SIAM_RegisterWithUID.adl
Reading file C:\Ampersand\Git\ssif\SIAMv3\SIAM_LoginLogging.adl
Reading file C:\Ampersand\Git\ssif\SIAMv3\SIAM_ISO_LoA.adl
Reading file C:\Ampersand\Git\ssif\SIAMv3\SIAM_SessionSuspension.adl
Reading file C:\Ampersand\Git\ssif\SIAMv3\SIAM_AutoLoginAccount.adl
Reading file C:\Ampersand\Git\ssif\SIAMv3\SIAM_GodAccounts.adl
Reading file C:\Ampersand\Git\ssif\SIAMv3\SIAM_LoginWithUPW.ifc
Reading file C:\Ampersand\Git\ssif\KvK\SBICodes.adl
Reading file C:\Ampersand\Git\ssif\KvK\SBI 2008 versie 2018 excerpt.xlsx
Reading file C:\Ampersand\Git\ssif\SSIFv1\SSIFv1_InfoShops.adl
Reading file C:\Ampersand\Git\ssif\T4SMM-Core\T4SMM-Core.adl
Reading file C:\Ampersand\Git\ssif\T4SMM-Core\T4SMM-Core-StdAndVersions.adl
Reading file C:\Ampersand\Git\ssif\T4SMM-Core\T4SMM-Core-Class.adl
Reading file C:\Ampersand\Git\ssif\T4SMM-Core\T4SMM-Core-Property.adl
Reading file C:\Ampersand\Git\ssif\T4SMM-Core\T4SMM-Core-Codelist.adl
Reading file C:\Ampersand\Git\ssif\T4SMM-Core\T4SMM-Core-BusinessRule.adl
Reading file C:\Ampersand\Git\ssif\T4SMM-Core\T4SMM-Core-XMLSchema.xlsx
Reading file C:\Ampersand\Git\ssif\SSIFv1\SSIFv1_InfoShops.ifc
Reading file C:\Ampersand\Git\ssif\T4SMM-Core\T4SMM-Core.ifc
Reading file C:\Ampersand\Git\ssif\KvK\KvK_Handelsregister.adl
Reading file C:\Ampersand\Git\ssif\KvK\KvK_Handelsregister.xlsx
Reading file C:\Ampersand\Git\ssif\KvK\KvK_Handelsregister.ifc
Reading file C:\Ampersand\Git\ssif\KvK\KvK_ZZPRegistrationForm.adl
Reading file C:\Ampersand\Git\ssif\SSIFv1\SSIFv1_FormTemplates.adl
Reading file C:\Ampersand\Git\ssif\SSIFv1\SSIFv1_Debug.ifc
Reading file C:\Ampersand\Git\ssif\KvK\KvK_ZZPRegistration.xlsx
Reading file C:\Ampersand\Git\ssif\KvK\KvK_InfoShop.adl
Reading file SystemContext.adl (from within ampersand.exe)

Errorlevel = 10
~~~
Thus: Ampersand terminates with error code `10`, which is an error.
However, Ampersand has not generated any such message.

What can I do to find out what the error is all about?

**Comment by hanjoosten** [comment]
Hmm. strange. I cannot reproduce now. My first suggestion however would be to see what happens if you try the command 

`ampersand.exe KvK.adl  -p"C:\xampp\htdocs\KvK" --verbose`

(without echo stuff whatsoever)

**Comment by RieksJ** [comment]
The `--verbose` is already in the yaml-file. The echo stuff is only there to show that ampersand terminates with an error - it is the only way to show that this is actually the case (apart from the fact that it generates nothing). Any other suggestions?

**Comment by hanjoosten** [comment]
I have done some investigation. An error is thrown, because the script is invalid. However, the string that should explain what is wrong, is empty. Of course, this is a bug, because such an empty string is not helpful at all. 
I will investigate further, which will result in a fix so that a helpful message is written. In the meantime, you might try to find out what is wrong by eliminating stuff from this script and see if it compiles. That might bring you a result earlier.

**Comment by RieksJ** [comment]
Discussing with @hanjoosten provided me with some inspiration, that led me to find the following text on `line 18` of file `SSIFv1_FormTemplates.adl`:
~~~
CLASSIFY Organization ISA Organization
~~~
This line has come into existince with a rename.  
Restoring this line to the original version (`CLASSIFY Party ISA Organization`) made the script compile again.

Apart from the fact that `CLASSIFY X ISA X` should not lead to an error in the first place, it should also not have led to an error without error message. So the issue remains open till the latter is solved.

Here is the (smallest?) script that will reproduce the error:
~~~
CONTEXT Issue751    CLASSIFY X ISA X     ENDCONTEXT
~~~

**Comment by Michiel-s** [comment]
There is already an issue for this one #742
