### ISSUE TITLE
No more empty error messages

### ISSUE THREAD

**Issue by hanjoosten** [AmpersandTarski/Ampersand#752]
Issue #751 was raised because somewhere in the Haskell code an error is thrown with an empty message. 
Root cause is that the constructor `Errors` of data type `Guarded` takes a list. This should be a non-empty list. In Haskell, [another datatype can be used for that](https://wiki.haskell.org/Non-empty_list). If we use such a datatype, it will become impossible to have issues like this in the future. Strong typing to the rescue!

**Comment by hanjoosten** [comment]
Fixed with commit ea192ec0fb1958c3ef3ee1760f1fa62f1e41af63

**Comment by Michiel-s** [comment]
Hi @hanjoosten, i think you’ve copied the wrong commit hash above.

**Comment by hanjoosten** [comment]
No, i don't think so.
