### ISSUE TITLE
Specify the folders/files that must be in static files when building Ampersand

### ISSUE THREAD

**Issue by Michiel-s** [AmpersandTarski/Ampersand#753]
This issue requests to not include the `static/zwolle/lib` folder in Setup.hs when building the static files. This folder contains external libraries that are added automatically by Composer after generating the prototype. These files are not in git, but locally I do have them for development purposes. When building on my local machine, this folder should be skipped.

**Comment by Michiel-s** [comment]
No wait, let's turn it around and make a list of folders/files that DO need to be included. There's a lot that can be skipped.

**Comment by hanjoosten** [comment]
Sounds like something to configure in a .yaml file?

**Comment by Michiel-s** [comment]
Let’s discuss this first, it relates to the wish to put the front end stuff in a separate repository. This means that to build Ampersand compiler, the static/zwolle folder won’t exist anymore or consist far less files (only those needed to actually generate the prototype)

**Comment by Michiel-s** [comment]
We'll go for a solution for #756
