### ISSUE TITLE
Contents of FLIPPED endo-relations (that are UNI/INJ) are not correctly read from the database

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/Ampersand#760]
I compiled the following script using Ampersand-v3.9.3 [development:609c03d]:
~~~
CONTEXT "Bug760" IN ENGLISH

RELATION myFatherIs[Person*Person] [UNI,INJ] -- (Src) Person has (Tgt) Person as its predecessor

POPULATION myFatherIs CONTAINS [ ( "Stein", "Rieks" ) ] 
POPULATION myFatherIs CONTAINS [ ( "Rieks", "Pierre" ) ] 
POPULATION myFatherIs CONTAINS [ ( "Pierre", "Harry" ) ] 
POPULATION myFatherIs CONTAINS [ ( "Harry", "Peter" ) ] 

INTERFACE "[Persons]": "_SESSION";V[SESSION*Person] cRud BOX <SHCOLS>
   [ "Me"        : I cRud
   , "My father" : myFatherIs cRud
   , "My son"    : myFatherIs~ cRud
   ]

ENDCONTEXT
~~~

I expected that each row in the interface would list the son of a person in the last column.
Instead, the interface looked like this:
![image](https://user-images.githubusercontent.com/8522589/37327032-fb62de50-2694-11e8-86da-b6c846d94b86.png)

@Michiel-s diagnosed this bug as incorrect sql code being used. It has to do with the fact that interfaces use an optimization for getting the population of UNI/INJ relations. In the early days, 4 queries were needed in this example: one for the toplevel expression, and another one for each of the columns. For quite some time now, it was observed that it would be more optimal to obtain the contents of the columns in the same query as the top-level expression, which is possible if a column has a relation that is UNI/INJ w.r.t. toplevel (TGT) atom. For normal applications, this already constitutes quite a performance improvement. 
The bug is in the code that obtains the contents for such a column. The bug appears when the relation that is used there is ENDO and flipped.

**Comment by hanjoosten** [comment]
I agree with the diagnosis. When I use the --sqldump switch on this script, it is clear that the generated sql is wrong. I'll look into this later this week.

**Comment by hanjoosten** [comment]
I assume this is what you'd expect:
![image](https://user-images.githubusercontent.com/1159672/37554430-93018d56-29d8-11e8-9656-e386c30fa502.png)
