### ISSUE TITLE
install fails on Pandoc branch

### ISSUE THREAD

**Issue by stefjoosten** [AmpersandTarski/Ampersand#765]
I'm working with Ampersand-v3.9.3 [development:4939a95]. I'm trying to compile to the most recent Pandoc version on commit 243334e3440388676b41d3ca7bc81b7ff3c7e272. For this purpose I opened a CLI (bash) and tried to run stack install.

I expected stack to generate a new ampersand.exe for me. However, I got an AesonException. This is what happened:
![afbeelding](https://user-images.githubusercontent.com/275768/37679632-c15cbdb4-2c81-11e8-9f28-a9850abba872.png)

**Comment by hanjoosten** [comment]
Nothing to do with Ampersand. It might be specific to the bash window. Try to build from a cmd window or from a PS window.

**Comment by hanjoosten** [comment]
Otherwise google the error message.

**Comment by hanjoosten** [comment]
upgrade your stack. See https://github.com/commercialhaskell/stack/issues/3686

**Comment by stefjoosten** [comment]
That was good advice. Thanks. After that, I got another error. Somehow the intermediate directories were read-only, which caused the unzipping of ghc to fail. When I made everything writeable, I got my stack install down to the very end. (It took a while to compile....)

**Comment by hanjoosten** [comment]
Lessons learned: Google your error messages. :stuck_out_tongue_winking_eye:
