### ISSUE TITLE
Why do I get an error message here?

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/Ampersand#766]
I have compiled the following script with Ampersand-v3.9.3 [development:ff47f46]
~~~
CONTEXT "Issue#766" IN ENGLISH

  CLASSIFY Datatype ISA Class
  
  subClassOf        :: Class * Class [IRF,ASY]
  baseDatatype      :: Datatype * Datatype [UNI]
  
  RULE subClassOf;baseDatatype |- baseDatatype
  VIOLATION (TXT "some text ", SRC I[Datatype], TXT " other text ", SRC subClassOf)
  
ENDCONTEXT
~~~
A type error is raised, as follows:
~~~
Error at symbol () in file C:\Ampersand\Git\ssif\KvK\Issue.adl at line 8 : 3
  Type error, cannot match:
  the concept Datatype (Src of I[Datatype], line 9 : 36)
  and concept Class (Src of subClassOf[Class*Class];baseDatatype[Datatype*Datatype] |- baseDatatype[Datatype*Datatype])
~~~
This script is an excerpt of code by @Michiel-s that I have been using for quite some time now. Only today I found out that it currently generates this error, suggesting that one of the latest commits is the cause. It may be related to #759. 

This is a bug that needs to be fixed.

**Comment by sjcjoosten** [comment]
I agree with Rieks, looking into it.

**Comment by RieksJ** [comment]
Would be nice to get the fix for #757 fixed. It's troublesome in a project here.

**Comment by sjcjoosten** [comment]
still looking into it

**Comment by sjcjoosten** [comment]
Awaiting travis for this pull request: https://github.com/AmpersandTarski/Ampersand/compare/development...sjcjoosten:development

**Comment by stefjoosten** [comment]
I disagree. Concept `Datatype` isa `Class`, so `Datatype` is narrower. There can be atoms that are `Class` but not `Datatype`. Writing this violation:
```Ampersand
VIOLATION (TXT "some text ", SRC I[Datatype], TXT " other text ", SRC subClassOf)
```
means that a violation tuple `(a,b)` doesn't get printed if `a` is a `Class` but not `Datatype`. That is why the compiler wants terms inside violation messages that at least wide enough to accept every conceivable violation tuple. The source of the violation segment `SRC I[Datatype]` should be `Class` or wider.

If you really want your violation statement to miss out on `Class` atoms that are not `Datatype`, you must explicitly state: 
```Ampersand
VIOLATION (TXT "some text ", SRC I[Class];I[Datatype], TXT " other text ", SRC subClassOf)
```
