### ISSUE TITLE
Auto login page

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/Ampersand#770]
In the refactor-branch, an auto redirect to `/#/ext/Login` is done when an interface is being requested for which the user has no rights. This leads the browser to show something like this:

![image](https://user-images.githubusercontent.com/8522589/38414776-c48cf9c0-398f-11e8-87ac-e5f750eb310e.png)

In SIAMv3, relations `sessionAnonIfc[SESSION*NavToIfc]` and `sessionUserIfc[SESSION*NavToIfc]` have been defined as a way for the &-modeler to specify the default interfaces for anonymous sessions and user sessions respectively. Currently, SIAMv3 uses `sessionAnonIfc` to specify the `Login` interface, and `sessionUserIfc` to specify the `Logout` interface.

This has to be integrated (and perhaps reflected on some more).

**Comment by Michiel-s** [comment]
See commit f7c00a3a9ff12a5651835e8a097b29a7d8c18586

**Comment by Michiel-s** [comment]
The login page was statically set to 'ext/Login' (used by OAuthLogin extension). When a request to the API responded with a 401 'Unauthorized', the frontend app directed automatically to this login page. By default this login page didn't exist.

Now a config option in localSettings.php can be set to specify the login page. Default is that there is no login page, and the user stays on the page and gets an info message 'Please login to access this page'.

You can specify the loginPage by adding the following line to your localSettings.php
`Config::set('loginPage', 'login', '<escaped interface id here>');`
The line is already there (commented out) in the default localSettings file.

For know I propose we leave it with this. When working on issue #578 we can look at integrating these configurations with an Ampersand model (like SIAMv3).
