### ISSUE TITLE
Installation of the Ampersand Compiler on OSX

### ISSUE THREAD

**Issue by stefjoosten** [AmpersandTarski/Ampersand#771]
I am trying to install an Ampersand compiler on a MacBook running OS X. I have opened a terminal (/bin/bash) and installed stack. I have also cloned the Ampersand git repository in ~/git/Ampersand. This is where Ampersand.cabal is found.
![screen shot 2018-04-10 at 20 35 17](https://user-images.githubusercontent.com/275768/38576560-bec39a22-3cfe-11e8-82a8-c7574f3245c2.png)
As you can see, `stack install` starts as expected.
After some time, the process comes to a halt because of a configuration error. The system says that the C compiler cannot create executables.
![screen shot 2018-04-10 at 20 22 24](https://user-images.githubusercontent.com/275768/38576369-3818477a-3cfe-11e8-8ed5-1d88ad271799.png)
Anyone got an idea what's wrong? Or should we ask @Oblosys ?

**Comment by hanjoosten** [comment]
I am not familiar with mac os, but this error states that the C compiler doesn't work. It doesn't recognize your CPP program. I guess you have to make sure you have a working C++ compiler. Maybe [this link](https://stackoverflow.com/questions/6438792/are-there-any-free-c-compilers-for-macosx) could help you on your way.
