### ISSUE TITLE
Some extra work to be done in refactor_ifc branch before merging into master

### ISSUE THREAD

**Issue by stefjoosten** [AmpersandTarski/Ampersand#774]
I compiled `ampersand-models\Hawaii\Hawaii.adl` with Ampersand-v3.9.4 [feature/refactor_ifc:0255495].

I expected to compile and run Hawaii smoothly in the refactored version of Ampersand on my Windows 7 laptop. Instead, I got a fatal error. To reproduce this error, I ran it with a YAML-file to get all options reproducible. Reproduce this from AmpersandTarski/ampersand-models@3ebc55a63db3b4b97ece461ebd0f1d14b2d8d159.
1. change directory to `...\git\ampersand-models\Hawaii\
2. run `ampersand Hawaii.adl`

This is what I saw
![afbeelding](https://user-images.githubusercontent.com/275768/39416369-bb759cd2-4c4c-11e8-94de-af1525c55d94.png)

**Comment by hanjoosten** [comment]
This fatal is by design. FormalAmpersand must be correct. However, in the refactor branch, this is not yet the case. The error message says it all.

**Comment by Michiel-s** [comment]
I don’t know anything about the relation sign[Rule*Signature]. What is needed? Merging development into the branch?
