### ISSUE TITLE
Issue na merge 7317bff

### ISSUE THREAD

**Issue by Michiel-s** [AmpersandTarski/ampersand#78]
Na commit 7317bff resulteert onderstaande INTERFACE specificatie niet meer in generatie van TABS structuur.

Mijn vermoeden is dat de BOX classificatie stuk is die ervoor zorg dat het juiste template wordt gebruikt voor generatie van html views. In dit geval had dat moeten zijn: Box-TABS.html, maar hij valt terug op de default Box.html template.
 
```
CONTEXT Test IN DUTCH

PATTERN Test
	CONCEPT SESSION ""
	r1 :: A * TEXT
	r2 :: A * TEXT
ENDPATTERN
		
INTERFACE "Overzicht" (r1,r2) FOR "Test" : V[SESSION*A]
	TABS [ "Tab1"	: r1
		, "Tab2"	: r2
		]

ENDCONTEXT
```

**Comment by sjcjoosten** [comment]
True, the Nothing on line 415 in P2A_Converters will have to be replaced by the second-to-last field of x. I'm assigning Han to do this.

**Comment by hanjoosten** [comment]
Indeed, I must have been sleeping.. ;) Anyway, this should solve the issue.
