### ISSUE TITLE
Menu bar contents

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/ampersand#781]
In earlier days, we used the concept `ONE` in interfaces that would appear in the menu bar. 
Now that we can (and should) use `"_SESSION"[SESSION]` for that, we should no longer populate the menu bar with interfaces whose concept is `ONE`, so that we can use such interfaces for other purposes (e.g. as subinterfaces for debugging.  

@Michiel-s : can you change the population of menu-interfaces to exclude interfaces with the `ONE` concept?

**Comment by hanjoosten** [comment]
@Michiel-s , was this related to issue #509? If so, can that one be closed as well?
