### ISSUE TITLE
Ampersand fails to build

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/Ampersand#794]
After I pulled the latest version of Ampersand this morning, I expected that it could be built in the same way as the previous versions (the fact that I use a script is irrelevant because I haven't changed it for quite some time). However, building it produced the following error:
~~~
You are already using composer version 1.6.5 (stable channel).
Downloaded lts-11.13 build plan.
AesonException "Error in $.packages.cassava.constraints.flags: failed to parse field packages: failed to parse field constraints: failed to parse field flags: Invalid flag name: \"byte
string--lt-0_10_4\""
~~~ 
Any suggestions as to how this can be resolved?

**Comment by hanjoosten** [comment]
It is very likely that you are using an old version of `stack`. You need the latest version (currently 1.7.1). Just run `stack upgrade` and you should be fine. Please let me know of this solved your build issue.

**Comment by RieksJ** [comment]
That seems to have done the trick.

However, when I make the stuff, --version now says `Ampersand-v3.10.1 [no git info], build time: 11-Jun-18 07:24:29` -- note the **[no git info]**

**Comment by hanjoosten** [comment]
This must be something to your own git settings. This can be checked by using the latest build by appveyor. I just downloaded that [artifact](https://ci.appveyor.com/project/hanjoosten/ampersand/build/build.1524-development/artifacts), and it shows the correct version info:

~~~
Ampersand-v3.10.1 [HEAD:3fede1973], build time: 11-Jun-18 03:42:12 Coordinated Universal Time
~~~

**Comment by hanjoosten** [comment]
git info is only given when you have a (working!) git installation at the time of compilation of Ampersand.
