### ISSUE TITLE
Relation signatures that differ just by epsilon should result in an error

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/Ampersand#796]
Suppose we have an ADL script that contains:
~~~
CLASSIFY SpecializedForm ISA Form
objForm :: Object * Form [UNI]
objForm :: Object * SpecializedForm [UNI]

sfInputIsClean :: SpecializedForm * SpecializedForm [PROP]
sfProcessReq   :: SpecializedForm * SpecializedForm [PROP]

ROLE ExecEngine MAINTAINS "Create Object Based on provided input"
RULE "Create Object Based on provided input": sfProcessReq /\ sfInputIsClean |- V;objForm
VIOLATION (TXT "{EX} InsAtom;Object"
          ,TXT "{EX} InsPair;objForm;Object;_NEW;Form;", TGT I
-- Here we fill in fields in the Object based on input in the form
          )
~~~
In a prototype this would produce a `maximum number of reruns exceeded` error.
This is caused by the fact that `InsPair;objForm;Object;_NEW;Form;", TGT I[Form]` populates objForm[Object*Form], while the rule uses objForm[Object*SpecializedForm]. Once you have found this cause, the error seems obvious. However, if you have not found it, you have no clue where this may come from: after all `objForm` in the rule could just as well have been `objForm[Object*Form]`.

To prevent other developers from having to spend lots of time in finding similar bugs, I suggest to forbid relations whose ONLY differences consist of 1+ specializations, with an error message such as "you are not allowed to define two relations whose ONLY difference consists of 1+ specializations (epsilons)".

**Comment by hanjoosten** [comment]
A much better solution would be that we would add syntax for the `{EX}`- hack. Then a proper typechecking could be done of the stuff in the TXT part.
