### ISSUE TITLE
"no git info" in --version text

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/Ampersand#799]
For some time now, I have found that the `--version` switch returns texts such as 
~~~
Ampersand-v3.10.1 [no git info], build time: 18-Jun-18 15:14:25 W. Europe Daylight Time
~~~
which means that I cannot specify the Ampersand version in tickets with better info than that.
Can you replace the `no git info`  text with the text of the git version again?

**Comment by hanjoosten** [comment]
You have to make sure git is installed properly, then compile ampersand again. Then you will see that this works. See also my earlier comment in issue #794
