### ISSUE TITLE
Iets raars in LaTeX

### ISSUE THREAD

**Issue by stefjoosten** [AmpersandTarski/ampersand#80]
Han, I see somthing funny in LaTeX. Below, please find the last part of the (verbose) output of Ampersand.
I am getting this when compiling `NVWA DTV/Tijdverantwoording.adl`, but also other  `.adl` files in `NVWA DTV`. Since you are working on LaTeX things anyway, would you look into this for me?
```
.\RulesInPatternAutoMaintainHistory.png written.
Generating Png using Dot.
.\Classification.png written.
Generating Png using Dot.
.\LogicalDataModel.png written.
Generating Png using Dot.
.\TechnicalDataModel.png written.
----------- LaTeX error-----------
Overfull \hbox (1291.9695pt too wide) in alignment at lines 18759--18785
 [] [] [] []
 []


Package longtable Warning: Column widths have changed
(longtable)                in table 44.1 on input line 18785.

[260

] ("D:\git\ampersand-models\NVWA DTV\Tijdverantwoording.gls" [261]
! Undefined control sequence.
<argument> \letcs {\glo@name
                             }{glo@\glsdetoklabel {Assignment}@name}\expanda...
l.5 ...tentrycounter[]{page}\glsnumberformat{20}}}

----------------------------------

ERROR: Latex execution failed.
For more information, run pdflatex on: Tijdverantwoording.tex
Or consult the log file:
.\Tijdverantwoording.log0
PdfLatex was called once.
Done.
Done.

D:\git\ampersand-models\NVWA DTV>
```

**Comment by hanjoosten** [comment]
I see more then one strange things:
* The error message normally has to do with non-existent or multiple defined references. I am dealing with that.
* The overful hbox normally has to do with long math statements (adl-expressions shown in LaTeX). I currently see no proper solution for that one. 
* the undefined control sequence. This is one of a long list of things that could go wrong with glossary. Glossary is very LaTeX specific, and a pain really. It hasn't been used for years, and it is at best a nice-to-have feature. It is an expensive feature in terms of code clutter, so I am getting rid of it all together.
