### ISSUE TITLE
Haskell Excel importer

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/Ampersand#801]
@Michiel-s and @jcnauta noticed (after a long time debugging) that the Haskell excelfile importer does not/no longer do what it used to do, which is: disregard (the contents of) any cell that is empty (or contains an empty string) i.e. treat is as if it didn't exist. 

@Michiel-s, @jcnauta: Please describe the evidence of this, so that @hanjoosten can fix this.

**Comment by Michiel-s** [comment]
The issue occurs when a cell formula evaluates to an empty cell. The excel importer should skip the cell, instead of inserting a tuple with tgt atom that has no/empty identifier.

If needed I can provide an simple example

**Comment by hanjoosten** [comment]
@Michiel-s, I didn't have an example at hand, but I am confident that this is fixed, for the Haskell code is pretty clear. Feel free to reopen if required.
