### ISSUE TITLE
Trying to store blobs (texts) containing quotes leads to SQL Errors

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/ampersand#81]
Als je in een Excel bestand een tekst opneemt met quotes (als in: "HeadHunters Inc. doesn't see it as their task ..."), dan komt er bij het importeren een "**Error!** You have an error in your SQL syntax" vanwege die quote. 
Datzelfde geldt als je een veld aan het editen bent en deze tekst er in probeert te stoppen.

**Comment by Michiel-s** [comment]
Fixed with f50a683aefd5f878619ecf6eab97d3017d289c8d
