### ISSUE TITLE
Resource type not found

### ISSUE THREAD

**Issue by stefjoosten** [AmpersandTarski/Ampersand#812]
#### Version of ampersand that was used 
I wrote a tiny Ampersand program, `Issue628.adl`, to assist in resolving issue #628 and put it in the AmpersandTarski/ampersand-models@3c57e36fe068da029fb374a7ba575cefafb3fd46 repository. This program was compiled with Ampersand-v3.11.0 [HEAD:d1ce3dd*], build time: 06-Jul-18 06:42:49 UTC, which was published on the master branch and has been pushed to Docker Hub.

I expected to see a working program. Instead I got a red message "Resource type not found". In spite of that, the program seems to work fine.

#### Steps to reproduce
1. clone `ampersand-models`
2. go to `Experiment 628`
3. give the command `docker-compose up -d` in a CLI
4. In the browser, go to `localhost` and navigate to the `Atoms` interface. There you will see the error message.
(this application needs ports 80 and 8080, so you may need to shut down your local Apache server)

#### Screenshot / Video
![image](https://user-images.githubusercontent.com/275768/42869344-0f6f5f6a-8a75-11e8-9542-5e56e75a8e78.png)

The trace of the error might be informative:
![image](https://user-images.githubusercontent.com/275768/42869452-5b743282-8a75-11e8-9994-ead439b49b4d.png)

#### Context / Source of ampersand script
(to be found in `AmpersandTarski/ampersand-models/Experiment\ 628`)
```
CONTEXT Bugxxx IN ENGLISH
  r :: A * A [PROP]
  s :: A * A [PROP]
RULE R : -(r-s)
ROLE User MAINTAINS R

POPULATION r CONTAINS
 [ ("aap","aap")
 , ("noot","noot")
 , ("mies","mies")
 ]

POPULATION s CONTAINS
 [ ("aap","aap")
 , ("pim","pim")
 ]

INTERFACE Atoms : "_SESSION"
BOX [ "this session" : V[SESSION*A] 
      BOX [ "" : I
          , "r" : r
          , "s" : s
          ]
    ]
ENDCONTEXT
```
# Noteworthy
1. I experimented with the `REPRESENT  A TYPE ALPHANUMERIC`-statement, but doesn't work.
2. When I closed the message, it did not reappear. Apparently it occurs at start-up of the application. It is reproducible by reinstalling the database.

**Comment by stefjoosten** [comment]
I have resolved this by adding crud annotations in the interface. See AmpersandTarski/ampersand-models@bdc0081446a329eac50a9c9526c2ad87aafa7863.
Don't know why, but it worked. So if anyone has a proper explanation, I'd be very happy....

**Comment by RieksJ** [comment]
I have no explanation to offer; I suspect however that @Michiel-s does.

I also experience these kinds of errors, which are a (minor) annoyance, yet have to be resolved IMHO in order for prototypes to become really robust. AFAIK, the not-so-robust stuff has to do with

- [ ] (re)installing the database;
- [ ] synchronisation between &-SESSION atoms and web server sessionids;
- [ ] showing the contents of (red) error boxes when you click on it (more often than not I find there is no content, which forces me to inspect log files)

Some proper (re)thinking of all this, documenting it perhaps, and revising it may be called for.
