### ISSUE TITLE
INTERFACE names that start with `_` are incorrectly registered in `interfaces.json`

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/Ampersand#816]
We need a SIMPLE way to predict the `id` of an `INTERFACE` that is being generated in the file `interfaces.json`. The reason for this is that we need such `id`s as arguments for the `NavToOnCommit` execengine function. If we cannot predict what the `id` of an `INTERFACE` is, the user will be faced with a 404 error at runtime.

It was decided earlier that this is not a 1-1 correspondence: 'special' characters, such as `#`, `_`, brackets etc. are represented as `_nn_`, where `nn` is the character code. The following example shows this; it has been generated from a script that defines `INTERFACE "[DEBUG]"`:
~~~
            },
            "id": "_91_DEBUG_93_",
            "txt": null,
            "type": "ObjExpression",
            "relationIsFlipped": null,
            "label": "[DEBUG]"
        }
~~~

The problem is that when we define an `INTERFACE` whose name starts with an underscore, the `id` does not start with `_32_` as one would expect, but with `__` (two underscores)`. This makes the predictability of 'INTERFACE` `id`s needlessly cumbersome.

Can you change the generator such that a leading underscore is converted to `_32_`?

And while you're at it: it would be nice if the JSON interface definition would start with the keys `label` and `id`, so that they are more easy to find when one inspects the JSON file.

**Comment by hanjoosten** [comment]
The id is generated in a very deterministic way. I see no reason to change this separat from issue #708

**Comment by Michiel-s** [comment]
Rieks, i see your problem, but this is a escaping library we use in Haskell. The _ is denotating that a special character is defined, instead the regular number. E.g. if the encoded string would be _32_, how could you tell if this means an underscore or just the string _32_. The library enables encoding and decoding, but we don’t use the decoding part. The special char needs to be escaped, that why you see the double underscore.

Having the id and label noted first in the json output is something I would like also, to make debugging less annoying. I’ll see if this is possible by moving the attributes up.
