### ISSUE TITLE
Invariant violations after running the installer

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/Ampersand#819]
It sometimes happens that after the installer is run, invariant violations exist. This condition is noted as an error (a red box appears in the user interface saying so). 

The normal (and expected) behaviour of such boxes is that if you click on them, they show the actual violations. However, in the case where the installer exits with violations (and a database rollback), clickin on the box does not show the violations. Also, the rules that have been violated are not shown. This can make debugging such situations a pain.

Please make sure that also after a reinstallation, the notifications are shown as expected.

**Comment by RieksJ** [comment]
While we're at it: empty notifications occur at other places as well, as shown in:
![afbeelding](https://user-images.githubusercontent.com/8522589/43684077-bcdaaae2-9899-11e8-9bd4-94fd093774c1.png)

Can they be populated, too?

**Comment by Michiel-s** [comment]
I understand your frustration. It is a complex initialization process right now, with too many dependencies on a happy flow. I’ll look into this and make it more explainable and consistent with what you would expect.
