### ISSUE TITLE
Feature request wrt NEW atoms

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/ampersand#82]
Creating new objects (atoms with several relations) is distinct from updating them. For starters, new objects should often relate to other, already existing ones. For example, a new order line should relate to precisely one order. We do not want to bother the user with specifying such links. In the old prototype generator, the editor took care of this and I assume that the new one will do this too, some day.

However, some fields may need to be filled in automatically where their contents depend on session variables (i.e. relations where the source (or target) atom is in SESSION). For example, a session user may be set as the author of a Note (or Comment). In order to prevent false populations in a multi-user environment, the rule for automatically populating fields using session variables requires that the object itself be created in the same SESSION. So, creating new atoms should be done in an interface that starts with the '_SESSION' atom.

Request: replace the list of INTERFACEs that you get when clicking on the '+' icon (i.e. the rightmost icon) in the menu bar with INTERFACEs whose source atom start with the '_SESSION' atom (and/or INTERFACEs whose name starts with the text 'New', in which case &-writers can control which INTERFACEs are there - in this case, such INTERFACEs should NOT be included in the list of selections that you get when clicking on a single atom (link)).

**Comment by Michiel-s** [comment]
Rieks,

This is not that easy as you describe. The current FE implementation has the following functionality regarding intefaces. Say I have:
```
r :: A * B
INTERFACE "Test" : I[A];r
   BOX [ ....]
```
In the above example, you can give an A (a1) to the interface and receive all Bs in the relation r. You can request the content of an atom in A. So the Read/GET right relates to the src of the interface. 

If you edit relations in the first BOX, it relates to Bs (can be b1, b2, ...). So the Update rights relate to the tgt atoms of the interface. Currently this also holds for the Delete functionality. Although you can also delete the src atom.

But now the Create functionality. What type of atom do we create in the Test interface? A new A, or new B (and link in the relation r). Currently I've chosen for the first option (a new A). Therefore if you have an interface that has the SESSION atom as src, you would create a new session. That cannot be the required behavior.

But then, if we would decide that the Create functionality relates to the tgt concept of an interface, you cannot create new atoms (in this case Bs) and access them with the same interface (in this case As). This is also not what we want.

Let discuss this face-2-face in more detail.

**Comment by Michiel-s** [comment]
Will be solved when #141 is fixed/implemented
