### ISSUE TITLE
deployment with docker broken?

### ISSUE THREAD

**Issue by stefjoosten** [AmpersandTarski/Ampersand#827]
#### Version of ampersand that was used 
Ampersand-v3.11.1 [HEAD:e7be402*]

#### What I expected
I expected to run Hawaii.adl easily

#### What happened instead
I got run time errors 

#### Steps to reproduce
1. cd to `ampersand-models/Hawaii`
2. docker-compose up -d
3. open your browser
4. reinstall database

#### Screenshot / Video
![image](https://user-images.githubusercontent.com/275768/44974446-f9a69d00-af5f-11e8-9ce8-35a1cf51b989.png)

#### Context / Source of ampersand script
This issue reveils shortcomings in our deployment discipline. How can we get more reliable releases? Can we invent better tests in the release-gateway?

**Comment by hanjoosten** [comment]
As far as I know, we have no automatic deployment of docker images jet. Therefor, it cannot be broken. 

In this case, I guess that some things are rememberd by the container, which should be renewed. 

Questions I have regarding to this: 

1. What images should be built?
2. In what cases do we want to trigger such a build?
3. What is the exact recipe to build such image?
4. How can we know that the build is succesful?

If I know the answers to these questions, we could start automating this lot.

**Comment by hanjoosten** [comment]
Double of issue #686

**Comment by stefjoosten** [comment]
The purpose of having automated deployment is that every user of Ampersand can rely on the existence of the right docker images, so they only have to use them (as opposed to baking images for them).

Answers to your 4 questions:

1. images to be built: For every named release on https://github.com/AmpersandTarski/Ampersand/releases (e.g. 3.10.0) we need docker images on https://hub.docker.com/u/ampersandtarski/dashboard/. Which docker images we need is defined on  https://github.com/AmpersandTarski/docker-ampersand/build.sh. Currently we need:
   1. ampersandtarski/ampersand-prototype-db:3.10.0
   2. ampersandtarski/ampersand-prototype:3.10.0
   3. ampersandtarski/ampersand-prototype:texlive-3.10.0

2. we want to trigger these builds from the moment a new level-3 release tag is made, to ensure that for every release of Ampersand there are corresponding docker images.

3. The exact recipe is found on on  https://github.com/AmpersandTarski/docker-ampersand/build.sh and in the Dockerfile instances in the (sub-)directories of https://github.com/AmpersandTarski/docker-ampersand/

4. The build is successful if the desired docker-images exist. If there are more conditions, they should preferrably be included in the automatic testing sequence of Ampersand.
