### ISSUE TITLE
Initial population fails to load

### ISSUE THREAD

**Issue by stefjoosten** [AmpersandTarski/Ampersand#829]
#### Version of ampersand that was used 
I am using Ampersand vs.3.11.0, I am trying to make Analyse.adl from commit AmpersandTarski/ampersand-models@03eca631c6d6c0794e9e27a9c7a52f1e8102778b work. 

#### What I expected
I am creating an ADL file, because I want a quick prototype.
I compiled the file (including the `INCLUDE` statement with the spreadsheet.) successfully.
I expected the data in the spreadsheet to be loaded upon install.

#### What happened instead
When I ran the prototype, I got an empty database instead of a populated database.

#### Steps to reproduce
1.  I removed the existing containers, thus releasing port 80 and 8080 on localhost, so this application can use them.
2.  I ran `docker-compose -f ampersand-models/Wjsg/ProbleemAnalyse/docker-compose.yml up -d --build`, verifying that the spreadsheet contains no errors
3.  I navigated to `http://localhost`
4.  I reinstalled the database, only to stare at an empty population.

#### Screenshot / Video
<img width="905" alt="afbeelding" src="https://user-images.githubusercontent.com/275768/45031219-86c81f80-b04e-11e8-9055-f7da8dd138da.png">

**Comment by RieksJ** [comment]
I have seen similar things. It is one of the items mentioned in #802. @Michiel-s has promised to refactor the whole setup of databases stuff to fix this. 

In the meantime, you can press the `Install` button a second time. That should provide you with the default population.
