### ISSUE TITLE
Empty interface expressions lead to "Resource not found" error rather than an empty screen.

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/ampersand#83]
Consider the scriptlet:

     INTERFACE Test : <expression>
     <remainder of the interface>

Whenever `Test` is invoked by the user for some (src)atom, the <remainder of the interface> paints all sorts of stuff on the screen, given the (tgt)atom(s) of <expression>. However, when there are no such (tgt)atoms, an error is given rather than an empty screen, which suggests that there is something wrong in the database, or in the code, or ... Rather than presenting this error, it would be preferable to NOT show this error, but catch it and provide some regular text on the screen that does not have this association, e.g. saying: "There is nothing to show, or you are not permitted to see it."

**Comment by hanjoosten** [comment]
What is the exact error message?

**Comment by RieksJ** [comment]
The exact error message is `Error! 404 Not Found: Resource not found` (red background)

**Comment by RieksJ** [comment]
Het gebeurt overigens niet als je een INTERFACE met TABS als bovenste laag hebt. Wel als je er een hebt met ROWS of met COLS begint.

**Comment by Michiel-s** [comment]
Fixed by af1c2e5e489e510a7640a34251ccdc4844c6a205
