### ISSUE TITLE
Cannot populate relations that contain ONE

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/Ampersand#834]
I expect the following script to compile properly using Ampersand-v3.11.2 [development:1592e235a]:
~~~
CONTEXT Issue 

  iCallMyself :: ONE * Name [UNI]
  POPULATION iCallMyself CONTAINS [ ("ONE", "Rieks") ]

ENDCONTEXT
~~~
Instead, it produces the message
~~~
In file "C:\Ampersand\Git\ssif\Issue.adl" (line 3, column 17):
Parsing stumbled upon keyword "ONE"
at that point expecting upper case identifier or string
~~~

**Comment by hanjoosten** [comment]
There are two problems here. 

1. ONE is a keyword of Ampersand. See issue #835 
2. We cannot refer to the ONE concept. This is an interesting point. @sjcjoosten  and @stefjoosten , should we be able to refer to the concept ONE? To populate relations with ONE in it's source and/or target? If so, how do we refer to the single atom in ONE? Do we have syntax for that?

**Comment by RieksJ** [comment]
The fact that `ONE` is a keyword should not preclude us from using a concept, and even an atom named `ONE` - see #835. 

There is a link with multiple contexts here. If `ONE` represents the god-concept and god-atom, then I would also like `I` to represent the concept and atom that refers to the `current context`, and I would like to be able to populate relations with such a context.

**Comment by stefjoosten** [comment]
Bas is right, we don't have syntax for the atom that populates  concept `ONE`. I propose to call it ONE (without brackets). I'll make a new issue for that enhancement.
