### ISSUE TITLE
Concept `I` cannot be created

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/Ampersand#835]
I expect to be able to use concept(name)s as I see fit, which implies that I expect the following script to compile properly using Ampersand-v3.11.2 [development:1592e235a]:
~~~
CONTEXT Issue 

  CONCEPT I "identifier that designates the system itself"

ENDCONTEXT
~~~
Instead, it produces the message
~~~
In file "C:\Ampersand\Git\ssif\Issue.adl" (line 3, column 10):
Parsing stumbled upon keyword "I"
at that point expecting upper case identifier or string
~~~
This issue may be related to #833 and/or #834.

**Comment by hanjoosten** [comment]
`I` is a reserved word in Ampersand. There are more reserved words, like `TRUE`, `CONCEPT` etc, At this moment, there is a sneaky way to circomvent this. You could create the concept anyway, by enquote it with double quotes. Then the parser will see it as a String.
Be aware that this sure will be prohibited sometime in future, when we fix issue #708 . Remember your [comment on that issue](https://github.com/AmpersandTarski/Ampersand/issues/708#issuecomment-348883103)?
If you use this 'feature', be aware that you are on your own. I guess that wierd things WILL happen. 

> Problems with 'weird' characters keep popping up...
> I suggest that names of relations and concepts should be forced to use characters from a limited character set, that exclude any character that might be 'special' in some case. The argument is that names of relations and concepts are there for the Ampersand engineer, and hence can well do without such characters.

**Comment by hanjoosten** [comment]
This issue contradicts with issue #708

**Comment by RieksJ** [comment]
This issue does not contradict with issue #708 - they are different things.
Issue #708 is about mapping names of interfaces (and perhaps by extension: names of concepts, relations and rules) onto database tables. The problem of #708 is about characters that are not in the set that is commonly used for identifiers, i.e. { [a-z], [A-Z], [0-9] }. The problem here is that we cannot use arbitrary identifiers whose characters are all in this set. 

Arguing that `I` is a reserved word is unacceptable, as it basically says that the current implementation of the parser prevails over proper design (i.e. what it should be able to do), and arguments like these have consequently be rejected by us as a group. And rightly so. I should be able to define concepts such as `CONCEPT`, `RELATION` and `RULE` in a similar way that I can define the concept `SESSION`. 

Having said that, I can see that this would require some major refactoring, and there can be reasons to postpone that, even for a long time. But then, it is also appropriate to leave this issue open so as not to forget that we have a bug here.

**Comment by Michiel-s** [comment]
@RieksJ You can define a concept with name `I` by putting it between quotes:
```adl
CONCEPT “I” “blabla”
```
I don’t think there is a bug here, so I suggest to close this issue. Nothing is going to change right now. If reserved words are disallowed in the furture, even placed betwee quotes, let’s deal with it then.
