### ISSUE TITLE
Table generation for specialization concepts does not scale

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/Ampersand#838]
As I expanded my BRP project with additional functionality, MySQL was no longer able to create the database due to its row limitation of 64k bytes. It turned out that the table was for a concept that had many specialization concepts, each of which had quite a few relations that have ALPHANUMERIC target atoms. Since ALPHANUMERICs (in UTF8) map onto 2 bytes per character, 128 relations suffice to reach the 64k row limit of MySQL.

A workaround that @Michiel-s is using, is to omit the use of CLASSIFY altoghther, create a bijective relation what the generic and specific concepts would have been, and then (tediously) ensure that this relation is used appropriately wherever this is necessary.

But that's not a nice solution.

Moreover, such a solution only works for relatively practical databases - it does not work for a user that for one reason or another would like to define `Entity` as something that is known within a context, and for every concept `C` include a `CLASSIFY C ISA Entity` statement. Of course this is currently more a theoretical case than a practical one, but then we also sometimes see theory actually being used...

Would it be possible to either have generalization/specialized concepts in separate tables, or (as preferred by @Michiel-s) an option in `CLASSIFY` statement where it can be specified whether or not to have such concepts in the same or in separate tables?

**Comment by hanjoosten** [comment]
What error messages do you get? What is this exactly about? What limitation in mysql? What version are you using? Is this in mariadb as well?

**Comment by Michiel-s** [comment]
Mysql error 1118 Row size too large
See: https://dev.mysql.com/doc/refman/5.6/en/column-count-limit.html

So for a concept classification tree with 64 columns (with varchar 255) = row size 16kb this error occurs. Database table cannot be created.

For us the MySQL/Mariadb restriction is not really the problem. Having tables with that amount of columns isn’t what you want anyway. 
In my opinion, a solution were we can benefit from the concept specialization feature, without putting it all together in a single db table, is the right way forward. 
@hanjoosten, how complex would this be for the compiler, it has large impact on the query generator I guess.

**Comment by hanjoosten** [comment]
Indeed. I expect major impact. Currently, the idea is that every atom is stored as a row in exactly one table. It is the table of the most generic concept in the ISA structure. For most usecases of Ampersand, this suffices. I do not think that we will address this issue in the forseeable future. Maybe it will be solved when we realize an implementation of Ampersand with another type of database (triple stores?).
