### ISSUE TITLE
How to merge a feature branch into the development branch

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/Ampersand#840]
As I tried to merge feature/Preprocessor into the development branch, I ran into trouble. 

1. I could not get it to merge (the way that I AM able to merge the deveopment branch into the feature branch).
2. I also could not create a pull request.

In both instances, I get this message:
![afbeelding](https://user-images.githubusercontent.com/8522589/46647794-50704980-cb92-11e8-9b87-470e61eeca82.png)

How do I merge the feature branch into the development branch?

**Comment by RieksJ** [comment]
Seems to be a sourcetree issue as doing a pull request on the repo works fine.

**Comment by stefjoosten** [comment]
Do we already know what has caused this problem?

**Comment by RieksJ** [comment]
I guess if I had read the actual message, I would have seen that merging required a review that had not happened at that time. This issue was raised around the time that guys like me were no longer allowed to fool around in the development branch unchecked...

**Comment by hanjoosten** [comment]
The cause of this problem was stated in the error message: `At least 1 approving review is required by reviewers with write access.`
