### ISSUE TITLE
Natural Language Generation

### ISSUE THREAD

**Issue by stefjoosten** [AmpersandTarski/Ampersand#842]
#### Version of ampersand that was used 
Ampersand-v3.11.3

#### What happens

The fourth chapter of the generated documentation, "Conceptual Analysis", documents each rule in two forms: a natural language meaning and the relation algebraic representation. Both are provided by the Ampersand engineer and have not been manipulated. Here is a fragment of that documentation:

<img width="739" alt="afbeelding" src="https://user-images.githubusercontent.com/275768/46850132-e99d9b00-cdf2-11e8-821d-6f1010adfad3.png">

#### What is needed
We need two more forms in which every rule is documented:
1. the predicate logic representation of the rule, to serve readers who are more familiar with predicate logic.
2. a generated natural language representation (as intended in issue #129), to serve readers who want to validate the meaning (provided by the Ampersand engineer) from a pidgin English representation of the rule.

#### Steps to reproduce
1. work from the command line
2. navigate in your git repo to AmpersandTarski/ampersand-models/Hawaii
3. call "ampersand -fDocx Hawaii.adl
4. open file Hawaii.docx and accept external links.

#### Context / Source of ampersand script
This issue is related to issue #129.

**Comment by hanjoosten** [comment]
This has a relation with issue #144, for an extra meaning can be generated automatically. So we have to cope with that.
