### ISSUE TITLE
Zwolle interface has problems with multiple users

### ISSUE THREAD

**Issue by stefjoosten** [AmpersandTarski/Ampersand#845]
At RAMiCS 2018 in Groningen, I tried to let 30 users work with RAP at the same time in an Ampersand tutorial. The assignment was to compile and run "[Hawaii.adl](ampersand-models/Hawaii/Hawaii.adl)" from `ampersand.tarski.nl/RAP3`. I tried the assignment before the tutorial took place. Nevertheless, during the tutorial we got all sorts of error messages, varying from SQL messages to front-end system messages. This made me go back to RAP3 of the last year (running from `rap.cs.ou.nl/RAP3`).

I had no opportunity to consolidate any errors, so no screenshots this time. The errors seemed to point towards multi-user behaviour, but I cannot be sure. The [log files](https://surfdrive.surf.nl/files/index.php/s/hAXF3q3EiKdxzay) have been consolidated and contain the debug, exec-engine, and error logs.

So, Houston, we have a problem! Let us think of a way to redo this multi-user experiment to expose the flaws. In the meantime, @Michiel-s , do you already have possible diagnoses based on your knowledge of the prototype code base?

**Comment by RieksJ** [comment]
I also regularly experience problems that have to do with sessions/session timeouts, setting up sessions after (re)installing databases etc. @Michiel-s has been trying to solve some issues there, but it is far from being really stable. We not only need a solid diagnosis, but above all a good theoretical model for doing this stuff. Requirements/user stories to entertain in sessions that we intend to hold on this topic are welcome.

**Comment by stefjoosten** [comment]
Maybe we could make a virtual testbox with 30 virtual users to validate some multi-user applications?

**Comment by Michiel-s** [comment]
With your permission I’m closing this issue. I haven’t heard of any complaints about multi user applications and from my own experience also don’t see issues here. Please reopen with new/more information is available.
