### ISSUE TITLE
Feature request: generation of Dockerfile

### ISSUE THREAD

**Issue by stefjoosten** [AmpersandTarski/Ampersand#847]
# Purpose
To support software automation and to make a small step in integrating development and deployment of Ampersand applications, I want Ampersand to bake docker images. This means that Ampersand must write docker files and call `docker build`.

# Which problem does this solve?
In production situations we want to decrease the time-to-release by automating the build-deploy-run process further.  This is currently a problem for RAP, because we have too few collaborators to do this by hand. For every deployment, it is as though I have to reinvent deployment, so I want this knowledge to be consolidated in a robust automated process.

# Analysis and scope
At this point in time we have enough experience with docker to consolidate this into the code repository, so the timing for this is right. 

Generation of docker files can be done for every script that is parsed correctly (even when it still contains type errors).

The generation of deployments (docker-compose or Kubernetes) is out of scope for this issue. Let's start with baking docker files.

As a first step, we can use the `Dockerfile` for RAP3 as a template and generalize it:
```Ampersand
# This script is meant to build from the root directory of your RAP-repo.
FROM ampersandtarski/ampersand-prototype:texlive

ENV AMPERSAND_DB_HOST=db

# link to the current directory to get application sources
RUN mkdir /src
ADD . /src
RUN mkdir /SIAM
ADD ./SIAM /SIAM
RUN mkdir /Sequences
ADD ./Sequences /Sequences

# stuff needed for gulp
RUN apt update \
 && apt install -y gnupg \
 && curl -sL https://deb.nodesource.com/setup_8.x | bash - \
 && apt-get install -y nodejs \
 && rm -rf /var/lib/apt/lists/* \
 && npm i -g gulp-cli

# build RAP3 application from folder
RUN ampersand /src/RAP3/RAP3dev.adl --config=/src/RAP3/RAP3dev.yaml -p/var/www/html/RAP3 \
 && mkdir -p /var/www/html/RAP3/log \
 && chown -R www-data:www-data /var/www/html/RAP3 \
 && cd /var/www/html/RAP3 \
# && npm i gulp \
 && npm install \
 && gulp build-ampersand \
 && gulp build-project

VOLUME /var/www/html/RAP3
```
# Process
I suggest @hanjoosten and I pick this one up and @Michiel-s and @hidde-jan will monitor and challenge as we go. Is that a workable scheme?

**Comment by hanjoosten** [comment]
I am making a start with the implementation. For starter, we now have a new switch: `--docker`. It will output a file named Dockerfile. Question is in which directory to put it. I suggest to put it in the prototype directory. @stefjoosten suggests that this file should also be written if the script can be parsed, but is not even type correct. That yealds complexity. For now, I merely only generate the file if typechecker is happy.

**Comment by hanjoosten** [comment]
This could well be. If no info from the FSpec is required, this is the way to go indeed.

**Comment by hanjoosten** [comment]
@stefjoosten , I did a first, probably very wrong Dockerfile. Could you please comment / try it out / whatever to see what has to be changed in it? Currently, the only thing used is the filename if it is available. If it isn't it defaults to `MyApp`

**Comment by hidde-jan** [comment]
@hanjoosten where is this docker file?

**Comment by hanjoosten** [comment]
@hidde-jan If you run ampersand with the new --docker switch, it will write a file to DockerFile in your output directory. (which can be specified in [several different ways](https://ampersandtarski.gitbook.io/documentation/the-command-line-tool)).

**Comment by hanjoosten** [comment]
Be aware that this currently is available only in the feature branch that I recently made.

**Comment by hidde-jan** [comment]
From a quick view:

- The docker file seems to assume some things about naming and structuring (and there is something about "dev.adl")
- It's adding directories which probably aren't available in every project
- The prototype image should be able to build and run prototypes, so if nodejs or gulp is a requirement, we should make sure it's available there
- There's no docker-compose file to run all needed services

**Comment by hanjoosten** [comment]
@stefjoosten , is this issue still relevant? If not, please close it.

**Comment by Michiel-s** [comment]
Let’s not add/generate a dockerfile into the Ampersand compiler. It really depends on your project, how your project folder is organized and for wat purpose you want a Dockerfile.

Instead, I’ve created a [project-template repo](https://github.com/AmpersandTarski/project-template), that can be used to quickly initialize a Ampersand project (folder). This repo includes a docker-compose and Dockerfile to build/deploy a prototype, but other Dockerfiles can be added for different purposes, e.g. generating functional specification.

Since this is a stale issue, I’ll close it. Please reopen if anyone disagrees.
