### ISSUE TITLE
feature: UTF-16

### ISSUE THREAD

**Issue by stefjoosten** [AmpersandTarski/Ampersand#852]
Currently we prescribe the use of UTF-8 as character set.
@sjcjoosten said in issue #850:
> Note that exFAT (newer windows versions), Os X and NTFS all use Unicode (in particular: UTF-16) for filenames, and I would prefer it if Chinese characters and sentences were valid names. However, I can understand if some characters were forbidden (in particular those forbidden by exFAT: 0x00-0x1F 0x7F " * / : < > ? \ |).

The question is whether we want to change our UTF-8 convention to UTF-16.
I personally would like to postpone this (if doing it at all) for the sake of continuity. Relevant facts (as mentioned above by Bas) and any opinions about this can be gathered in this issue.

**Comment by hanjoosten** [comment]
I agree: There is no issue in this.
