### ISSUE TITLE
Feature request regarding `CLASSIFY` statements

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/Ampersand#855]
Currently, the syntax for `CLASSIFY` statements is as follows:
~~~
CLASSIFY <Concept1> ISA <CONCEPT2>
CLASSIFY <Concept1> IS <... the appropriate syntax ...>
~~~
In order to make syntax more uniform, it would be nice to allow `<Concept1>` to be a comma-separated list, similar to the syntax of the `REPRESENT` statement, of which the syntax is:
~~~
REPRESENT <Concept1> [, <Concept>]* TYPE <type>
~~~
When done, I'll update the documentation.

**Comment by hanjoosten** [comment]
If I understand this correctly, you intend to be able to write something like:

~~~
CLASSIFY A, B, C IS P /\ Q /\ R
~~~

Isn't this an odd notation? I wonder what @sjcjoosten thinks about this.

**Comment by sjcjoosten** [comment]
Yes, it's very odd, although it makes sense to have such a notation in the future when we start massively using ``EQUALS``, say for:

```
import Person_GBA as GBA
import User_Registration as User
import Person_Family as Family

CLASSIFY GBA.Person, User.Person, Family.Person IS Person
```

Something like that... We don't yet have the ``import`` this way, but we have ``CLASSIFY`` and it would make sense to move into this direction.

For ``CLASSIFY .. ISA ..``, having syntax would already be useful in the current Ampersand.

The only situation in which I would not know a good example on how it could be useful, is for the example @hanjoosten just gave, but it's consistent and the semantics are clear, so there's no problem in implementing it like this.

**Comment by RieksJ** [comment]
This has not been fixed. I used Ampersand-v3.11.5 [development:9f30deec8] to compile the following script:
~~~
CONTEXT Issue855

CONCEPT CList "(named) list of codes with associated descriptions"
clName :: CList * Name [UNI,TOT] -- Name by which the CList is known

cleCList :: CListEntry * CList [UNI,TOT] -- CList to which the CListEntry belongs
cleCode  :: CListEntry * Code  [UNI]     -- Code that is described by the CListEntry
cleDescr :: CListEntry * Descr [UNI]     -- Description of the Code in the CListEntry

CLASSIFY SBICode, Rechtsvorm  ISA Code
-- CLASSIFY SBICode ISA Code
-- CLASSIFY Rechtsvorm ISA Code

rfSBICode :: RegForm * SBICode
RULE "SBICode must be valid": rfSBICode |- V;(I/\cleCList;(I/\clName;"SBICodes";clName~);cleCList~);cleCode

ENDCONTEXT
~~~
This produces the error
~~~
Error at symbol () in file C:\Ampersand\Git\ssif\KvK\bug.adl at line 15 : 41
  Type error, cannot match:
  the concept Code (Tgt of V [RegForm*CListEntry];(I[CListEntry]/\cleCList [CListEntry*CList];(I[CList]/\clName [CList*Name];"SBICodes"[Name];clName [CList*Name]~);cleCList [CListEntry*CList]~);cleCode [CListEntry*Code])
  and concept SBICode (Tgt of rfSBICode [RegForm*SBICode])
~~~

However, when I comment the line with `CLASSIFY SBICode, Rechtsvorm  ISA Code` and uncomment the two lines below that, it compiles just fine.
