### ISSUE TITLE
Error in SQL code for r;r~ where r is [INJ] and/or [UNI,INJ]

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/Ampersand#860]
Issues such as #318 and #340 have shown that relations that the database constructs that are used for relations that have the `INJ` property (in conjunction with having the `UNI`) property, have been cumbersome for some time now.

The current implementation is not robust: since #628 solved a performance problem, I've been seeing invalid evaluations of expressions of the kind `I /\ r;r~ /\ s;s~ ...`, and/or `I /\ r~;r /\ s;s~ ...`. That is: when I exercise a rather complex prototype, and I expect this relation to evaluate to `I` (true), I find that it evaluates to `-V` (false). When I look in the database, I see that all relations `r`, `s`, etc. are populated, thus supporting my expectation that it should have evaluated to `I`.

According to @Michiel-s, who has seen this behavior, this has to do with the way that a relation `r[A*B] [INJ,UNI]` is assigned its database column. While in theory, that column could be either in the table for `A` or in the table for `B`, practice (i.e. the above series of issues) shows that in  order to achieve robust code, the location of the column needs to be easily predictable. Currently, this decision seems to depend on which of the concepts `A` or `B` is defined first which someone that writes code can easily forget, thereby producing code that arbitrarily functions either all right, or not.

So in this issue requests to implement  relations that are of the form `r[A*B] [INJ,UNI]` such that their population ends up in a column that is located in the table of their source concept (`A`). In other words, every relation `r[A*B]` ends up having a column in the table for concept `A`, except if it is ONLY `INJ`, in which case it ends up having a column in the table for concept `B`.

@hanjoosten: is it possible to address this issue even while @Michiel-s has not provided a simple example of code yet (which he promised he would do)?

**Comment by RieksJ** [comment]
Here is a script that you can use to see the issue:
~~~
CONTEXT Issue860

sessionForm :: SESSION * Form [INJ,UNI]
ROLE ExecEngine MAINTAINS "Ensure there is always a Form in a session"
RULE "Ensure there is always a Form in a session": I |- sessionForm;sessionForm~
VIOLATION (TXT "{EX} InsAtom;Form"
          ,TXT "{EX} InsPair;sessionForm;SESSION;", SRC I, TXT ";Form;_NEW"
          ,TXT "{EX} InsPair;formName;Form;_NEW;Name;Master Form"
          )

formIsClean  :: Form * Form [PROP]
formName     :: Form * Name     [UNI]   REPRESENT Name     TYPE ALPHANUMERIC
formContents :: Form * Contents [UNI]   REPRESENT Contents TYPE ALPHANUMERIC

ROLE ExecEngine MAINTAINS "InsPair `formIsClean`"
RULE "InsPair `formIsClean`": I /\ sessionForm~;sessionForm /\ formName;formName~ /\ formContents;formContents~ |- formIsClean
VIOLATION (TXT "{EX} InsPair;formIsClean;Form;", SRC I, TXT ";Form;", TGT I)
ROLE ExecEngine MAINTAINS "DelPair `formIsClean`"
RULE "DelPair `formIsClean`": formIsClean |- I /\ sessionForm~;sessionForm /\ formName;formName~ /\ formContents;formContents~
VIOLATION (TXT "{EX} DelPair;formIsClean;Form;", SRC I, TXT ";Form;", TGT I)

formIsSubformOf :: Form * Form [INJ,UNI]
ROLE ExecEngine MAINTAINS "Create subform when form is clean"
RULE "Create subform when form is clean": formIsClean |- formIsSubformOf~;formIsSubformOf
VIOLATION (TXT "{EX} InsAtom;Form"
          ,TXT "{EX} InsPair;formIsSubformOf;Form;_NEW;Form;", SRC I
          ,TXT "{EX} InsPair;formName;Form;_NEW;Name;Subform of ", SRC formName
          )
ROLE ExecEngine MAINTAINS "Delete subform"
RULE "Delete subform": I |- sessionForm~;sessionForm \/ formIsSubformOf;formIsSubformOf~
VIOLATION (TXT "{EX} DelAtom;Form;", SRC I)

VIEW Forms: Form(formName)
INTERFACE "Home": "_SESSION" cRud BOX <DIV>
   [  "Sessionform": sessionForm INTERFACE Form
   ]

INTERFACE "Form": I[Form] CRuD BOX <SHCOLS>
      [ "Name": formName cRUd
      , "Contents": formContents cRUd
      , "Clean?": formIsClean cRud
      , "Subform": formIsSubformOf~ LINKTO INTERFACE Form
      ]

ENDCONTEXT
~~~
Here is how to reproduce the issue:

1. Compile the script
2. Install/Reinstall the database
3. Click `Home` in the menu bar
4. Enter a contents of the form (and hit `Enter` to have it transferred to the database)
5. The form is now clean, which results in a subform being created.
6. Click on the name of the subform (so that you can edit it)
7. Enter a contents of the form (and hit `Enter` to have it transferred to the database)

Now, we would expect this subform to be clean as well, but that is not the case.

**Comment by hanjoosten** [comment]
I am not sure the diagnosis of this problem is correct. I'd rather think that this relates to issue #746. This cannot be solved using the current theory in Ampersand. (See [this comment](https://github.com/AmpersandTarski/Ampersand/issues/746#issuecomment-359033572) of @stefjoosten where he shows the details).

**Comment by hanjoosten** [comment]
For @RieksJ to play with, I will create a branch with his request implemented. However, I don't see how this could solve this case.

**Comment by hanjoosten** [comment]
I have looked into the code. The suggestion as done by @Michiel-s is false. Since two years, a relation that has both INJ and UNI properties defined, *allways* is stored in the table of the source concept. This can be observed by looking at the code of [ADL2Plug.hs](https://github.com/AmpersandTarski/Ampersand/blob/6d14920cf8d10737be509bb12924b753c25fe8f6/src/Ampersand/FSpec/ToFSpec/ADL2Plug.hs#L219) . Hence, there is nothing to do for now. This issue seems to be a double of issue #746.

**Comment by RieksJ** [comment]
in retrospect, the example provided in the issue shows the behaviour as specified. That does not mean there is no bug (we've seen it in a rather complex case), but only that we did not succeed in making the example smaller while preserving the bug.
