### ISSUE TITLE
Incorrect evaluation of rule I /\ r;r~ /\ s;s~

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/Ampersand#861]
[Edited in response to @hanjoosten's request to make the model smaller]: I compiled a prototype from the following script using Ampersand-v3.11.5 [development:4ae863323], (re)installed the database, and clicked `Home` in the menu bar. Then, I entered a contents in the 'Content' field of `Form2`, expecting the rule `InsPair formIsClean` to fire and populate `formIsClean`. However, it did not. I consider this to be a bug.

This script was part of #860, which suggested a cause and solution. However, @hanjoosten has rebutted that, stating that it may have to do  with issue #746, which is currently unsolvable (also according to @stefjoosten). 

I don't think it has anything to do with issue #746. Rather, I think that the generated code is incorrect. I base my assumption on the fact that earlier (say: before optimizing expressions of the kind `I /\ r;r~ /\ s;s~ /\ ...` - see issue #628), these expressions did produce correct code, which means that it is possible.

~~~
CONTEXT Issue861

regForm :: Registration * Form [INJ,UNI]
formName :: Form * Name [UNI]
formContents :: Form * Contents [UNI]

REPRESENT Name, Contents TYPE ALPHANUMERIC

formIsClean :: Form * Form [PROP]
ROLE ExecEngine MAINTAINS "InsPair formIsClean"
RULE "InsPair formIsClean": I /\ regForm~;regForm /\ formName;formName~ /\ formContents;formContents~ |- formIsClean
VIOLATION (TXT "{EX} InsPair;formIsClean;Form;", SRC I, TXT ";Form;", TGT I)

POPULATION regForm CONTAINS [ ("Reg1", "Form1") ]
POPULATION formName CONTAINS [ ("Form1", "Form1 name") ]
POPULATION formName CONTAINS [ ("Form2", "Form2 name") ]
POPULATION formContents CONTAINS [ ("Form1", "Form1 contents") ]
-- POPULATION formContents CONTAINS [ ("Form2", "Form2 contents") ]

INTERFACE "Home": V[SESSION*Form] cRud BOX <SHCOLS>
   [ "Form": I cRud
   , "Name": formName cRUd
   , "Contents": formContents cRUd
   , "Clean?": formIsClean cRUd
   ]

ENDCONTEXT
~~~

First post of this was by @RieksJ in https://github.com/AmpersandTarski/Ampersand/issues/860#issuecomment-447567120_

**Comment by hanjoosten** [comment]
We need to drill down on this example. Make it even smaller. Providing an intermediate state as initial state could help doing so.

**Comment by RieksJ** [comment]
I edited my first post to provide the smallest example that I can think of now.

**Comment by RieksJ** [comment]
I noticed that the smaller example does not result in a showing of the bug. I will close this issue until I have one.
