### ISSUE TITLE
Creation of database fails in case of specific populations

### ISSUE THREAD

**Issue by hanjoosten** [AmpersandTarski/Ampersand#864]
#### Version of ampersand that was used 
Ampersand-v3.12.0 [master:9dfc6db0c], build time: 21-Dec-18 10:22:17 West-Europa (standaardtijd)

#### What I expected
I expected the population to load

#### What happened instead
I got an error message:

#### Steps to reproduce
1.  Compile the script with `--prototype` switch
2. Open the browser at the place where the prototype should be
3. Reinitialise the database with population

#### Screenshot / Video
![image](https://user-images.githubusercontent.com/1159672/50341760-639f7e00-0520-11e9-9f91-e044246a35d4.png)

#### Context / Source of ampersand script

~~~.ampersand
CONTEXT "Issue864" IN ENGLISH

RELATION father [Person * Male] [UNI]
RELATION mothersChilds [Female * Person] [INJ] --this relation is the flipped 'mother' relation
RELATION isMale [Person * Person] [PROP] 

CLASSIFY Female ISA Person
CLASSIFY Male ISA Person

POPULATION father CONTAINS
    [ ("Marian", "Pierre")
    , ("Suzanne", "Timo")
    ]
POPULATION mothersChilds CONTAINS 
    [ ("Marian","Suzanne")
    ]
POPULATION isMale CONTAINS 
    [ ("Pierre","Pierre")
    , ("Timo", "Timo")
    ]

ENDCONTEXT
~~~

This script was engineered while trying solve issue #862.

This is the error log:

[error-2018-12-21.log](https://github.com/AmpersandTarski/Ampersand/files/2702698/error-2018-12-21.log)

**Comment by Michiel-s** [comment]
@hanjoosten and I diagnosed the bug and some refactoring is required in Ampersand compiler. To be continued.
