### ISSUE TITLE
Code for [IRF] does not work

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/Ampersand#865]
When using Ampersand-v3.12.0 [development:5f8cbc876], I attempted to create a prototype from the following script:
~~~
CONTEXT Issue865

isSuccessorOf :: Assignment * Assignment [UNI,INJ,IRF,ASY]

POPULATION isSuccessorOf CONTAINS  [ ("Ass2", "Ass1") ]
POPULATION isSuccessorOf CONTAINS  [ ("Ass3", "Ass2") ]

ENDCONTEXT
~~~
I expected the prototype to install without errors. However, it generated an error:
![afbeelding](https://user-images.githubusercontent.com/8522589/50400292-e117f800-0785-11e9-8dc2-5a3e0ccad285.png)
which pertains to the `IRF` property of relation `isSuccessorOf`, and is a bug that needs to be fixed.

**Comment by hanjoosten** [comment]
@RieksJ : This is NOT a beginner-friendly bug.

**Comment by RieksJ** [comment]
I assume the comment of @hanjoosten pertains to the label `beginner-friendly` rather than the label `bug`. 

I consider `beginner-friendly` to be anything that beginners should not be confronted with. As such I would say that, since `IRF`, `UNI` etc. are very basic properties of relations, beginners should not be confronted with associated code being buggy. But perhaps you have a different understanding of what `beginner-friendly` is?
