### ISSUE TITLE
Roles have vanished from screen

### ISSUE THREAD

**Issue by stefjoosten** [AmpersandTarski/ampersand#87]
Reproduce this as:
1. compile "ampersand-models\NVWA DTV\Login.adl" with --newFrontend
2. run it
3. try to use it for logging in as role FAB. This is what I get:
![image](https://cloud.githubusercontent.com/assets/275768/7553315/a3888ab6-f6f1-11e4-9772-bab6789d4631.png)

It works in the old front end, until the point where the exec-engine has to kick in, which proves that the Login.adl is OK:
![image](https://cloud.githubusercontent.com/assets/275768/7553309/39f7fece-f6f1-11e4-92db-b7b765624762.png)

**Comment by hanjoosten** [comment]
I am not sure if this has anything to do with the front-end. In Generics.php, I see the following code:

```php
$allRoles =
  array
    ( array ( 'name' => 'Medewerker'
            , 'ruleNames' => array ('unknownUsername')
            )
    , array ( 'name' => 'Leidinggevende'
            , 'ruleNames' => array ('unknownUsername')
            )
    , array ( 'name' => 'FAB'
            , 'ruleNames' => array ('unknownUsername')
            )
    , array ( 'name' => 'KODE'
            , 'ruleNames' => array ()
            )
    , array ( 'name' => 'P&O'
            , 'ruleNames' => array ()
            )
    , array ( 'name' => 'beheerder'
            , 'ruleNames' => array ()
            )
    );
```

This means, that the frontend simply doesn't know about rules.
A quick look at your script reveals NO rules to be maintained by rule 'KODE'. 
Also, the appropriate interfaces show up in the menu.

**Comment by hanjoosten** [comment]
However, when "Login" is clicked, the following error message shows:

```
Error! 500 Internal Server Error: No database table defined for concept ONE in $allConcepts (Generics.php)
```

The message is True. there is no table created for ONE. Is that correct? 
If no table is created for ONE, some 'special' behaviour is to be coded in the front end, which must be well defined. 
if a table shoud exist for ONE, still some 'special' behaviour might be requred in the front-end. 
In the latter case, the absense of the table ONE could be a good trigger for the special behaviour, since the table would always contain exactly one atom at all times.

**Comment by Michiel-s** [comment]
@stefjoosten: ik kan je fout niet reproduceren, heb je bugfix 9436ef9ee6d28068975f9f1667482ae74017b368 al meegenomen?

@hanjoosten: jij gebruikt vermoedelijk niet de laatste versie van Login.adl. De foutmelding die je krijgt heeft te maken met ticket #70. Als het goed is wordt nu standaard ook een tabel gemaakt en gepopuleerd voor ONE. Tenminste, daar ging ik vanuit toen je het ticket afsloot.

**Comment by hanjoosten** [comment]
Inderdaad, ik kan de fout ook niet reproduceren. En @Michiel-s : ik gebruikte inderdaad een oude versie van login.adl. Het ligt nog wat subtieler met ticket #70 . Er wordt géén tabel aangemaakt in de database voor ONE, maar alle SQL queries hebben die ook niet nodig 8-)) De tabel komt echter wél voor in $allConcepts 
Lang verhaal kort: Er is niets aan de hand. @stefjoosten: als je het hier mee eens bent, graag ticket sluiten.

**Comment by stefjoosten** [comment]
Heel vreemd. Ik heb Login.adl vertaald met commit 991af63, dus daar zit 9436ef9 zeker wel in. Ik heb het met Internet explorer en met Chrome gedraaid, en krijg hetzelfde gedrag. Ik heb databases en directories gewist en geschoond dat het een lieve lust is, maar niets hoor! Het blijft fout gaan. Behalve bij Han, daar blijft het maar goed gaan. Ik snap het niet...

**Comment by Michiel-s** [comment]
Probleem zat in error reporting van php die sinds paar commits geleden in localsettings.php staat. Stef had een verouderde localsettings.php versie in zijn include map staan die eroverheen werd geschreven. Na verwijderen daarvan was het euvel verholpen.
