### ISSUE TITLE
Bug in Atoms.adl

### ISSUE THREAD

**Issue by stefjoosten** [AmpersandTarski/ampersand#89]
Check out Atoms.adl (from commit Ampersand master:1f1adc8).
I have compiled this script once for the new front end, and once with the old front end.
In the new front end, I cannot create a new atom.
In the old front end, I can make a new atom.
My intended behaviour is to make a new atom in the new front end (so I can use exec-engine rules).

Just for the record: I also tried removing localsettings.php from "\localhost\klad", but that didn't do anything (as expected).

**Comment by Michiel-s** [comment]
Rieks and I analyzed the issue and concluded that there is a bug with INJ constraints in the new frontend. I'll dive into it and try to fix the bug. For now, if you remove the INJ constraint it works.
