### ISSUE TITLE
Start prototype from root directory again

### ISSUE THREAD

**Issue by hanjoosten** [AmpersandTarski/Ampersand#892]
#### Version of ampersand that was used 
3.13.0

#### What I expected
When a prototype is generated, I am used that it can be started from the root directory of the generated prototype. 

#### What happened instead
It doesn't start from there. I have to go to the `public` directory to start the prototype. 

#### Steps to reproduce
1. Generate a prototype from any script.
2. Try to launch the prototype in the (formerly) usual manner, by going to the root of the generated prototype application
3. see that the prototype does not launch.

**Comment by RieksJ** [comment]
@Michiel-s communicated to me that this choice was made for security reasons. Starting from the root requires the root directory to be publicly accessible. Starting from another directory (that can be publicly accessible) prevents users to access the root dir and its contents.

**Comment by Michiel-s** [comment]
I'll add a redirect

**Comment by Michiel-s** [comment]
hmm.. it's more complicated than I thought.

I was planning to use an .htaccess file that rewrites calls to `/...` to `/public/...`. But here's the problem:
- htaccess of all in between folders are applied. So a call to `/public/...` would be redirected to `/public/public/...`, which is wrong.

**Comment by Michiel-s** [comment]
We only have this issue because of the XAMPP setup with a htdocs folder that serves multiple sites.
It depends on the webserver configuration on your machine. A generic solution does seem possible.
When using Docker containers this isn’t an issue anymore. The webserver starts from the `public` folder.
Therefore, I’ll close this issue.
