### ISSUE TITLE
On Travis CI: Temp database creation failed!

### ISSUE THREAD

**Issue by hanjoosten** [AmpersandTarski/Ampersand#917]
## What happens?
Lately we get a failure when testing on Travis CI, with this error: [Here is an example of such a build](https://travis-ci.org/AmpersandTarski/Ampersand/jobs/511197166).

Because of this, we get false negatives as a build result. 

## Diagnosis
I have seen several locations where different tests go wrong. It seems to occur with random test cases.

**Comment by Michiel-s** [comment]
I think this has to do with my commit cb7382c17c357d70ec295080108095df7af5ab28 on 578 navbar branch. This is WIP. Or do you see it also in other branches?

**Comment by hanjoosten** [comment]
Well, that commit should be reverted. But I've seen other errors too, stating that a connection with the database cannot be made. There is something funny going on with the name of a temporary file, that contains the sql query.

**Comment by stefjoosten** [comment]
Gents, do we already know what the problem is?

**Comment by hanjoosten** [comment]
No. However, it seems to only occur in the navbar feature branch.

**Comment by hanjoosten** [comment]
Issue has dissapeared.
