### ISSUE TITLE
First error in --daemon does not return to prompt

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/Ampersand#918]
When I running AMPvsnr=Ampersand-v3.15.0 [development:97c2e6c95] in a VSCode terminal with the `--daemon` switch, it starts up nicely. After the first mistake (e.g. replacing `UNI` with `UNIX`), I get the corresponding error message. However, when I correct the output in the terminal does not change, suggesting that the daemon has died.

**Comment by hanjoosten** [comment]
This seems to be in cases where the error occurs in one of the INCLUDEed files, which resides in a different directory as the root directory of the workspace.

**Comment by hanjoosten** [comment]
@RieksJ , I found the bug and solved it. If you think it isn't solved, feel free to update this issue and reopen it.

**Comment by stefjoosten** [comment]
@hanjoosten What was the problem in this issue? Has it been fixed structurally or temporarily?
