### ISSUE TITLE
relation complements

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/ampersand#92]
Since we have `CLASSIFY`, the complement of a relations may be preceeded with `V`, so that you can get constructs such as `(V - r)`. I was wondering whether or not `V` may be replaced with any other relation that satisfies type checking constraints, e.g. `(s - r)`and if so, does that mean that this expression represents the set of pairs  { (a,b) | (a,b) \elem s and (a,b) \notelem r }? 

Such constructs would be useful e.g. when testing whether or not an atom has a set of properties (each of which represented with a relation that is [PROP]), or selecting sets of atoms that have such sets of properties, as in 

    INTERFACE test: '_SESSION';sessionOrders;(orderIsAccepted - orderIsShipped)

which would then work on all orders that have been accepted but not yet shipped.

**Comment by hanjoosten** [comment]
Currently the - operator is an operator with a single argument. 
We could make it an operator with two arguments, whereas the first one is optional. If that optional argument is ommitted, V will be used as default. 
This would cause a change in the parser, the type-checker and maybe some further addaptions of the generator as well, but I think this would be a nicer, more generic use of the - operator.
@stefjoosten and @sjcjoosten please your opinions too!

**Comment by stefjoosten** [comment]
This proposal is already reality.

-r   means  V-r, and is implemented in this way.
It is up to the type checker to assign a type, which means that if the type checker cannot find a unique type [A*B] (yielding V[A*B]-r[A*B]), it produces an error.

Stef Joosten

M +31 (0)6 51348895
skype: stef.joosten




-----Oorspronkelijk bericht-----
Van: Han Joosten [mailto:notifications@github.com]
Verzonden: woensdag 3 juni 2015 10:25
Aan: Joosten, Stef
Onderwerp: Re: [ampersand] relation complements (#92)

Currently the - operator is an operator with a single argument.
We could make it an operator with two arguments, whereas the first one is optional. If that optional argument is ommitted, V will be used as default.
This would cause a change in the parser, the type-checker and maybe some further adaptions of the generator as well, but I think this would be a nicer, more generic use of the - operator.
@stefjoosten<https://github.com/stefjoosten> and @sjcjoosten<https://github.com/sjcjoosten> please your opinions too!

—
Reply to this email directly or view it on GitHub<https://github.com/AmpersandTarski/ampersand/issues/92#issuecomment-108244916>.

________________________________
Deze e-mail is uitsluitend bestemd voor de geadresseerde(n). Verstrekking aan en gebruik door anderen is niet toegestaan. Open Universiteit sluit iedere aansprakelijkheid uit die voortvloeit uit elektronische verzending. Aan de inhoud van deze e-mail en/of eventueel toegevoegde bijlagen kunnen geen rechten worden ontleend.

This e-mail is intended exclusively for the addressee(s), and may not be passed on to, or made available for use by any person other than the addressee(s). Open Universiteit rules out any and every liability resulting from any electronic transmission. No rights may be derived from the contents of this message.

Disclaimer
Dit bericht met eventuele bijlagen is vertrouwelijk en uitsluitend bestemd voor de geadresseerde. Indien u niet de bedoelde ontvanger bent, wordt u verzocht de afzender te waarschuwen en dit bericht met eventuele bijlagen direct te verwijderen en/of te vernietigen. Het is niet toegestaan dit bericht en eventuele bijlagen te vermenigvuldigen, door te sturen, openbaar te maken, op te slaan of op andere wijze te gebruiken. Ordina N.V. en/of haar groepsmaatschappijen accepteren geen verantwoordelijkheid of aansprakelijkheid voor schade die voortvloeit uit de inhoud en/of de verzending van dit bericht.

This e-mail and any attachments are confidential and are solely intended for the addressee. If you are not the intended recipient, please notify the sender and delete and/or destroy this message and any attachments immediately. It is prohibited to copy, to distribute, to disclose or to use this e-mail and any attachments in any other way. Ordina N.V. and/or its group companies do not accept any responsibility nor liability for any damage resulting from the content of and/or the transmission of this message.

**Comment by hanjoosten** [comment]
The point is, we also want to be able to write 

```
r:[A*B]
s::[A*B]
t::[A*B]
RULE r = s - t
```

**Comment by sjcjoosten** [comment]
I agree, but maybe we're missing your point. Is there a data structure in the Haskell source you would like to see changed?

**Comment by hanjoosten** [comment]
Yes, there is. In the A-structure of Expression, we would replace the constructor ECpl Expression with another one with two Expression-s , the relative substraction. (In the P-structure similar adaptation will probably be required)

**Comment by hanjoosten** [comment]
Oops. Sorry. I see that this is already in place ...
