### ISSUE TITLE
Enhance overall quality by using Rio

### ISSUE THREAD

**Issue by hanjoosten** [AmpersandTarski/Ampersand#921]
Inspired by [this webcast](https://www.fpcomplete.com/blog/rio-standard-library-for-haskell), I see benefits of replacing prelude and other common used packages by [rio](https://github.com/commercialhaskell/rio#readme). This will enable better overall quality of the software, and could enable easier build of future functionality.

**Comment by stefjoosten** [comment]
Sounds nice! But, which one of our problems does rio solve?

**Comment by hanjoosten** [comment]
The purpose is well-described in the [Readme of the Rio package](https://github.com/commercialhaskell/rio#readme). tl;dr : Overall quality boost of haskell software.

**Comment by Michiel-s** [comment]
@hanjoosten This issue can be closed right? We use RIO.
