### ISSUE TITLE
How to produce warnings for deprecated front-end features (e.g. obsolete templates)

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/Ampersand#925]
I use Ampersand-v3.15.0 [development:a84500c99] (but a student of mine reports to have seen this also with the currently released master branch) to compile a project into a new (clean, empty) directory:
~~~
"C:\Ampersand\AMPprogs\ampersand.exe" "BRP" --ignore-invariant-violations -p"C:\xampp\htdocs\BRP"
~~~
This produces the following terminal output:
~~~
Processing your model...
There are invariant violations that are ignored. Use --verbose to output the violations
There are signals for the initial population. Use --verbose to output the violations
Generating prototype...
ampersand.exe: Cannot read template file Box-ROWSNH.html
C:\xampp\htdocs\BRP\templates\Box-ROWSNH.html: openBinaryFile: does not exist (No such file or directory)
CallStack (from HasCallStack):
  error, called at src/Ampersand\Prototype\GenFrontend.hs:438:30 in ampersand-3.15.0-GFLPUz1wCkiJBeTe44Ti5m:Ampersand.Prototype.GenFrontend
~~~
After talking with @Michiel-s, it turns out that this template has been rendered obsolete, as the 'NoHeader' property that the template was used for, has been made default behavior of the `ROWS` template. Accordingly, in order for arbitrary users to solve this problem, they should be made aware of this fact, and that they should replace any `BOX <ROWSNH>` that they use in their scripts with `ROWS`.

@Han/@Michiel: can either of you generate a warning message (in this case, perhaps even an error message) that helps users in these cases?

**Comment by RieksJ** [comment]
I have recovered the template and restored it in the development branch of the prototype. @Michiel-s: if you think that is not the way to go (e.g. the template should no longer be one of the default templates) then please ensure that appropriate warning messages are generated.

**Comment by hanjoosten** [comment]
There is a decoupling between the frontend stuff and the ampersand stuff. The user who generates the prototype can explicitly specify what version of frontend should be used. When the error occurs, we do not know if the default value is used, or a specific other version of the frontend. The ampersand generator has no knowledge of the frontend stuff. So it doesn't know what templates should be there or not. It only knows that templates that are used in the script must be available. We cannot guess the intent of the user.

@RieksJ , what error/warning message do you propose?

**Comment by RieksJ** [comment]
Suggestion for message: `Please replace any occurrance of 'BOX <ROWSNH>' with 'ROWS'`.

**Comment by hanjoosten** [comment]
I will leave the error message as is. It is correct. However, I will add a warning that is fired while editing (the daemon), in the specific case that there is a usage of a `BOX` with the class `<ROWSNH`>. This should give a proper user experience.
