### ISSUE TITLE
specify multiple loader files in the .ampersand config-file

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/Ampersand#929]
The `.ampersand` file currently requires that one so-called 'loader file' is specified, i.e. a file that contains, or includes files that contain, the code of a single project.

When developing code (even modules) that are used in multiple projects, it is nice to have the ability that multiple projects are checked at the same time. That is currently not possible, yet it is also what this issue calls for to enable.

One might consider creating a single file that 'loads' all project files that are to be checked simultaneously. This, however, does not work, because different projects may use the same names for INTERFACEs or RULES, yet with different content. This would (rightfully) result in errors, which would not occur if projects were really compiled independently of one another.

@hanjoosten: could you allow for multiple files to be specified in the `.ampersand` file, e.g. one per line, and then run ampersand over each of them independent from all the others?

**Comment by hanjoosten** [comment]
This is part of the --daemon switch of ampersand.
