### ISSUE TITLE
Warning while compiling Ampersand: non-portable path to file

### ISSUE THREAD

**Issue by stefjoosten** [AmpersandTarski/Ampersand#937]
#### Version of ampersand that was used
I used Ampersand-v3.16.0 [HEAD:1da9943a0*], build time: 27-Apr-19 08:30:37 CEST in order to compile Ampersand using the command:
```
stack install
```
#### What I expected
Since my script contained no compile time errors, I expected to get a smooth run resulting in a working Ampersand compiler.

#### What happened instead
Instead, I got a nasty warning which gave me an uncomfortable feeling:
<img width="629" alt="Screenshot 2019-04-27 at 20 19 21" src="https://user-images.githubusercontent.com/275768/56853546-de8f0000-6929-11e9-9c1c-2f9e589c7073.png">
Still, I got my Ampersand compiler. Apparently, nothing is wrong with it, so why bother? Well, it seems it has something to do with cabal. So I expect it will not go away by changing Haskell files. 

#### Analysis
I think this is the same issue as [nonportable-include-path warning on case-insensitive systems](https://github.com/commercialhaskell/stack/issues/3918) by @gelisam ([Samuel Gélineau](https://github.com/gelisam)) from Montreal. I am working on a Macbook, which is case sensitive, while Han, Rieks, and Michiel are working on case insensitive Windows machines. That might explain why this occurs only on my machine. I have not yet experimented to verify this hunch.

**Comment by hanjoosten** [comment]
There is an issue for this: https://github.com/haskell/cabal/issues/4739 . Currently, there is only a workaround, which I will implement.
