### ISSUE TITLE
Modifying concept membership by the ExecEngine

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/ampersand#94]
Consider an application that has concepts Animal, Cat and Dog where Cats are Animals and Dogs are Animals. Suppose that an Animal gets registered, but after some time, it becomes apparent that this animal is a Cat. This situation can already be handled by humans - the file 'SpecEdit.adl' (in the directory ShouldSucceed of the Sentinel) contains an analogous example that deals with citrus fruits.

This situation however cannot yet be handled by the ExecEngine. This issue aims to specify the additional function(s) we need to call through the ExecEngine for achieving similar behaviour. Such functions would be similar to (but behave differently from) 'InsPair', 'DelPair', 'InsAtom', 'DelAtom' and 'NewStruct'.

How about the following functions:

1. **SetConcept (Concept, Atom, NewConcept)**, where 
  * Concept and NewConcept are in the same classifcation tree ('island'),
  * Atom is a member of Concept, and
  * the behaviour is that the Atom will henceforth also be a member of NewConcept

2. **ClrConcept (Concept,Atom)** where
  * Atom is a member of Concept, and
  * the behaviour is that if (Atom is a member of a concept other than Concept), then atom is removed as element of Concept

For relatively easy cases that should suffice. I sollicit use-cases that may go sour on these definitions, but better yet: contributions to improve on these specifications. I particularly invite @stefjoosten and @sjcjoosten to do so.

**Comment by hanjoosten** [comment]
As I was reviewing the Atoms.adl file, that contains a pattern to describe the equivalence of atoms, I had a thought that could prove very usefull in this discussion as well. 

apparently, there is something like grouping of Concepts. concepts with a specialisation relation between them, are in the same group. (I took the term 'Typology' for this.) 

```
RELATION in[Atom*Typology] [UNI,TOT]
MEANING "Every atom is in exactly one typology"

RELATION partOf[Concept*Typology] [UNI,TOT]
MEANING "Every concept is part of exactly one typology"

RULE "typologies" : sub;partOf |- partOf
MEANING "A specialisation of a concept and the concept itself are both part of the same typology."
```

In the above example of cats and dogs, whenever any animal gets registerd (representation e.g. 123), the animal with representation 123 must be the same as the cat with representation 123 or the dog with representation 123. However, the relation pop[Atom*Concept] will hold information about the animal being a cat and/or a dog and/or an animal....

When the realization is in a relational database, all concepts that are part of the same typology will be in the same table. Each row in that table holds the representation of the atom. For each concept that is part of that typology, a field is available holding the information of pop[Atom*Concept].

That information could be modified within the limits of the rules we set.
