### ISSUE TITLE
Remove company logo's from footer

### ISSUE THREAD

**Issue by Michiel-s** [AmpersandTarski/Ampersand#940]
I think we should remove the company logo's from the default footer of a generated prototype.

This is a open source project. Main contributors of this repository are working for these companies, but other than that there is no special connection.

@stefjoosten OU
@hanjoosten Ordina
@Michiel-s TNO
Please agree/disagree.

**Comment by Michiel-s** [comment]
Agree

**Comment by stefjoosten** [comment]
Agree, and let's do it now!

**Comment by hanjoosten** [comment]
Agree
