### ISSUE TITLE
Cannot make proper issues

### ISSUE THREAD

**Issue by SterredenBreeijen** [AmpersandTarski/Ampersand#945]
Hoi, ik kan geen fatsoenlijke issues maken omdat ik geen rechten heb om labels, assignees en dat soort dingen toe te voegen. Mag ik dat ook? 
Dankjewel!

**Comment by Michiel-s** [comment]
Hoi Sterre,

Dat hoeft ook niet hoor. Schiet gewoon een ticket in, het core developers team van Ampersand zorgt voor de juiste labels en assingments.
