### ISSUE TITLE
Something went wrong when returning an error message

### ISSUE THREAD

**Issue by SterredenBreeijen** [AmpersandTarski/Ampersand#946]
#### Version of ampersand that was used 
3.16.0 master ee22d20

#### What I expected
Build an interface

#### What happened instead
![afbeelding](https://user-images.githubusercontent.com/49937913/57126532-8b83d580-6d8d-11e9-801b-32be23daa0d0.png)

I think something is wrong with 
~~~

ROLE ExecEngine MAINTAINS "nonceGen"
RULE "nonceGen": I |- didPairHasNonce;didPairHasNonce~
VIOLATION (TXT "InsPair;didPairHasNonce;DidPair;", SRC I, TXT ";Nonce;{php}random_bytes(10)")

ROLE ExecEngine MAINTAINS "keyGen"
RULE "keyGen": I |- didPairHasKey;didPairHasKey~
VIOLATION (TXT "InsPair;didPairHasKey;DidPair;", SRC I, TXT ";Key;{php}random_int(100,500)")
~~~

**Comment by RieksJ** [comment]
The information provided in this ticket does not allow me to analyze the error. Since the error message mentions that the information is in the server log files, could you attach the `debug-2019-05-03.log` file to this ticket? You can find it in the directory `log`, which is a subdirectory of the directory in which you created your prototype.

**Comment by SterredenBreeijen** [comment]
I tried again this morning using the bat document but I still get the same error. 

[debug-2019-05-03.log](https://github.com/AmpersandTarski/Ampersand/files/3147412/debug-2019-05-03.log)
[debug-2019-05-06.log](https://github.com/AmpersandTarski/Ampersand/files/3147415/debug-2019-05-06.log)

**Comment by hanjoosten** [comment]
The logfile contains the following line:

```
[2019-05-06 08:54:50] API.CRITICAL: Malformed UTF-8 characters, possibly incorrectly encoded [] []
```
This suggests that there is a problem reading the file. All encoding in ampersand is based on UTF8.

**Comment by hanjoosten** [comment]
I suppose this is caused by the `{php}random_bytes(10)` function. Can you guarantee that such random bytes can be converted to UTF-8 characters? If not, that is very likely your problem.

**Comment by SterredenBreeijen** [comment]
Yes, that is indeed the problem!
