### ISSUE TITLE
After role (de)activation in the menu, the screen should be refreshed

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/Ampersand#951]
When I change the roles that are active in a session from the menubar, I expect this to have an immediate effect on the user-interface (and before that, to have done an ExecEngine run). However, the effect only shows after a manual refresh of the screen. Can we have an automatic refresh in such cases?

**Comment by RieksJ** [comment]
Please describe the reason for closing the issue, particularly when there's no reference to a commit or so.

**Comment by Michiel-s** [comment]
See above: `Michiel-s closed this in AmpersandTarski/prototype@0a85b94 4 days ago`
If you look at this commit you see that it's fixed.
