### ISSUE TITLE
--daemon should automatically include the SystemContext.adl file

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/Ampersand#959]
In an ampersand script, you do not need to define relations and other stuff that is defined in the SystemContext.adl script. However, the --daemon switch does not take that into account. This issue asks for having that fixed.

**Comment by hanjoosten** [comment]
Not sure what you mean exactly. Could you provide a tiny script that now gives an error but (in your opinion) should just work?

**Comment by RieksJ** [comment]
~~~
CONTEXT "Issue959"

-- RELATION isVisible[PF_NavMenuItem*PF_NavMenuItem] [PROP] is defined in SystemContext

POPULATION isVisible CONTAINS [ ("MyMenuItem", "MyMenuItem") ]

ENDCONTEXT
~~~

**Comment by Michiel-s** [comment]
@RieksJ, not only the daemon has issues with this situation, where you reference to relations defined in the PrototypeFramework context, but also the `ampersand proto` command doesn't work.

This has to do with the current implementation and refactored way grinding.. read about it in #971. Especially the diagram by @stefjoosten in his [comment](https://github.com/AmpersandTarski/Ampersand/issues/971#issuecomment-497920185) explains it very good. What you can see here is that the user scripts needs to be able to be parsed and transformed into a FSpec on its own, before it is grinded and/or merged with other scripts (like the PrototypeFramework context).

We completely refactored the meatgrinder and this is working good now with readable code. So I propose not to make exceptions now or change that code again. The solution is to explicitly define the relations you need from the PrototypeFramework context in your user script. Probably this will change when we implement #850 (you'll then need to import them).
