### ISSUE TITLE
Feature request with --daemon option

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/Ampersand#965]
Currently, the `--daemon` option takes a file that contains a (list of) file(s) that ampersand checks as it runs in daemon mode. This is a very nice feature and a great asset when developing code in projects. 

However, I regulary find myself in a situation where I need to isolate a bug as I prepare for a new issue. This is another way of working, where I only temporarily want to use the `--daemon` option on the single file that I am constructing as an example for the issue. So, without loosing the ability that currently exists, I would like to have the possibility to start the daemon by explicitly specifying the file that I want it to check.

There are several ways in which this can be achieved:

1. the --daemon option could look into the file and figure out whether or not the file contains an &-script or a list of files. This might be decided using the criterion that &-scripts currently start with `CONTEXT` at the top of the file and/or that the first line is a valid, existing fileid.
2. there could be an addtional option, e.g. `--daemon2` that would be used to directly interpret the &-script.

There may be more options.

**Comment by hanjoosten** [comment]
There are possibilities in this direction, however, be awere that this can only work in a command terminal outside vscode. The vscode command will always use the internal vscode way to call the checker. I assume that this isn't a problem though.

**Comment by RieksJ** [comment]
No problem.

**Comment by stefjoosten** [comment]
I don't understand this issue. I need some more details. What problem are you trying to solve? Example maybe?

**Comment by hanjoosten** [comment]
By default, `--daemon` looks at the `.ampersand` file to know what files should be monitored for changes. It will also monitor all INCLUDEd files.

While this is nice, @RieksJ asks for a possibility to specify some other file instead of the `.ampersand` file. Of course, this can only be done if the --daemon is run from a terminal, for that is the only way that switches can be given.

**Comment by hanjoosten** [comment]
This is a duplicate of issue #932 , which is already solved. @RieksJ , if you disagree, then I didn't understand your need. In that case, feel free to reopen this issue and make clear what it is you want.

**Comment by RieksJ** [comment]
This is not a duplicate of issue #932, which calls for the ability to specify `--daemon=filename` where `filename` contains a list of files that the daemon has to check. 

This issue calls for the ability to specify `--daemon=filename`, where `filename` is a regular ampersand script that the daemon has to check.

We would need the ability to distinguish between the situation where `filename` is a list of files to be checked and the sittuation where `filename` is an ampersand script to be checked. There are various ways to do this. I can suggest one or two if you like.

**Comment by hanjoosten** [comment]
Ok. Fair enough. I still don't get you. Let's have some skype session where you show me what you mean. Either I can let you see how to do what you intend, or you convince me that with the current features it cannot be done. In either case we add the results to a comment to this issue. This will either make clear what has to be done, if any.

**Comment by RieksJ** [comment]
Closing this issue and replacing it with #976
