### ISSUE TITLE
FormalAmpersand should be included when option `add-semantic-metamodel` is used

### ISSUE THREAD

**Issue by stefjoosten** [AmpersandTarski/Ampersand#967]
#### Version of ampersand that was used 
Ampersand-v3.17.0 [development:d30e6eb96]

#### What I expected
I wanted to see the Ampersand metamodel, so I made a tiny file, `Issue967.adl`, with just one relation it. I then ran:
```
Ampersand --meta-tables --add-semantic-metamodel --verbose -fDocx Issue967.adl
```
I expected to see the Ampersand metamodel together with this one relation in the resulting documentation.

#### What happened instead
Instead, I got the metamodel of my single relation only:
![LogicalDataModel](https://user-images.githubusercontent.com/275768/58011280-33b9ce00-7af2-11e9-8627-82baa5b5e75d.png)

**Comment by stefjoosten** [comment]
I added priority high, because this issue is blocking the RAP3 development.

**Comment by hanjoosten** [comment]
This issue has become irrelevant, because of the introduction of commands, and the idea of recipes.
