### ISSUE TITLE
Compilation fails to reproduce on Travis

### ISSUE THREAD

**Issue by stefjoosten** [AmpersandTarski/Ampersand#968]
#### Version of ampersand that was used
Ampersand-v3.17.0 [tryPullReq:e40e14a97*], build time: 25-May-19 06:18:49 CEST

#### What I expected
I expected that Travis will compile without errors any Ampersand that is compiled without errors on my laptop.

#### What happened instead
Travis failed to compile Ampersand, whereas this Ampersand compiles without errors on my laptop.

#### Steps to reproduce
1. check out branch ["tryPullReq" from GitHub](https://github.com/AmpersandTarski/Ampersand/tree/tryPullReq)
2. verify on your laptop that Ampersand can be compiled.
3. inspect the [result on Travis](https://travis-ci.org/AmpersandTarski/Ampersand/jobs/537066631) to see that Travis failed.

#### Screenshot / Video
<img width="1192" alt="Screenshot 2019-05-25 at 06 26 34" src="https://user-images.githubusercontent.com/275768/58364556-a215dc00-7eb6-11e9-86a4-75f54b87c3db.png">

**Comment by hanjoosten** [comment]
This error was thrown after downloading the lts of haskell packages from stack failed. As with all services, the availability isn't 100%. It is less. Not much, but less. That means that it is possible that the service is temporarily down, which is unfortunate, but inevitable. 
In these rare cases, It is possible to restart the travis build, which I just did. At the time of writing, the build has succesfully downloaded the lts (but is't finished yet).
