### ISSUE TITLE
Transaction functionality incomplete

### ISSUE THREAD

**Issue by stefjoosten** [AmpersandTarski/ampersand#97]
Consider ampersand-models\NVWA DTV\Referentielijsten.adl [ampersand-models, master 8d2b84d], which is compilable with Ampersand v3.1.0[ampersand master:1b6bd7c*].

After generating a prototype with the new front-end, I am not able to delete a variable anymore. This used to work before transactions were operational.

**Comment by Michiel-s** [comment]
Covered by tickets #60 (not yet fixed)
