### ISSUE TITLE
Feature request: allow files to be commented out in .ampersand file

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/Ampersand#976]
After discussing with @hanjoosten, it was decided to close #965 and replace it with this feature request.

Currently, the `.ampersand`-files that are used in conjunction with the `--daemon` switch contain a list of files to be processed. Also, such files can be edited 'dynamically', which means that any changes that are made are instantly seen and processed by the daemon.

When a developer wants to temporarily 'switch contexts', e.g. when creating an ampersand script to demonstrate an issue, it is helpful to have this script listed in the `.ampersand` file and not being bothered by any other scripts that are under development and may produce errors. One way to accommodate for this is to allow files listed in the .ampersand script to be commented out.

Summary: this issue calls for a feature where (a) file(s) that is referenced in a `.ampersand` file can be annotated such that it is ignored (=treated as comment) by the ampersand daemon.

**Comment by hanjoosten** [comment]
Lines in --deamon configuration file can be commented out by prepending such line with "#" or "--" (MUST be at beginning of line)

**Comment by Michiel-s** [comment]
Nice solution!
