### ISSUE TITLE
Database transaction timeout settings

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/Ampersand#983]
Currently, we can specify the timeout for database transaction by setting `global.scriptTimeout` in `customizations/config/project.yaml`. Its default value of 30 seconds works well for smaller projects.

For large projects, developers that do not have very fast machines run into the problem that database initialization takes longer than 30 seconds. To resolve this, they have to increase the timeout. An unwanted consequence is that the timeout is now also increased for regular transactions, for which the default timeout of 30 seconds is already way too high.

This issue calls for the implementation of a timeout setting that is specific for initializating the database. A good default value for that might be 60 seconds. The default value for regular transactions can then be reduced to 15 (or 10) seconds.

**Comment by Michiel-s** [comment]
I’ll implement this and increase the timeout for initializing the database (reinstall application method) to 5 min, just to be sure. The default timeout can stay at 30 sec. if you want less for eg a production app, you can specify this already with the config param you mentioned.
