### ISSUE TITLE
Feature request to suppress warnings in --daemon context

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/Ampersand#988]
When developing a script in VSCode, I use the Ampersand Checker (ampersand with `--daemon` switch) to locate the obvious mistakes I make - this is a real asset.

The `--daemon` switch also provides warnings. Some of these warnings (e.g. CRUD-related warnings that indicate a possible misunderstanding of the developer) are easily fixed. However, other warnings exist that may be helpful to beginners, but are a nuisance for expert developers. 

Here is an example:
~~~
sbiNNnnn   :: SBIEntry * SBIDigits   [UNI] -- first digit pair of SBI code.
sbinnNNn   :: SBIEntry * SBIDigits   [UNI] -- second digit pair (if it exists).
sbinnnnN   :: SBIEntry * SBIDigits   [UNI] -- fifth digit (if it exists).
sbiNNxNNxN :: SBIEntry * SBICode [UNI,INJ] -- all digits, pairs are separated with dots.
~~~
where the relations all contain one part of a so-called SBICode. Note that the names of the relations precisely indicate which part of the code is intended, and therefore should remain as they are. However, this leads to the daemon continuously providing the following messages:
~~~
Unknown origin warning:
  Ampersand is case sensitive. you might have meant that the following are equal:
      Relation`sbiNNnnn` and `sbinnNNn`.
Unknown origin warning:
  Ampersand is case sensitive. you might have meant that the following are equal:
      Relation`sbiNNnnn` and `sbinnnnN`.
Unknown origin warning:
  Ampersand is case sensitive. you might have meant that the following are equal:
      Relation`sbinnNNn` and `sbinnnnN`.
~~~

This issue calls for a means that allows developers to (selectively) turn of warnings in daemon mode.

One possibility might be to introduce a switch `--noWarnings` that would simply not provide warnings. Note that this issue does not (necessarily) call for adaptation of the VSCode stuff. It just calls for something like this option.

**Comment by hanjoosten** [comment]
The switch is called `--no-warnigns`.
