### ISSUE TITLE
What scripts should we select for regressiontesting?

### ISSUE THREAD

**Issue by hanjoosten** [AmpersandTarski/Ampersand#99]
Currently, we only have automatic regression test done by Sentinel. Sentinel uses a hand-picked list of ampersand scripts to test. 
With [Travis-ci] (https://travis-ci.org/AmpersandTarski/ampersand/branches) we could do a lot more, or at least also other testing. 

To enable this, we need to be able to automatically select Ampersand scripts to test, based on the file and/or location. of the file. 

The idea is that the test-suite contains a *walker*, that travels over every file in ampersand-models. For each directory and/or file that is in it, we need some way to decide wether or not that file is a test candidate. 

In the branch called *parsec*, this is currently implemented in a very rough way: ampersand-models is traversed, and each file in it with an extension ".adl" is taken as test candidate. 
Whenever the test is triggerd, it result can be viewd at Travis-ci, as you can see by following [this link](https://travis-ci.org/AmpersandTarski/ampersand/builds/65237965).

If we think this testing is usefull, we need to come up with a way to decide what scripts to test. Each script candidate selected that way should pass the test...

Suggestions please!

**Comment by hanjoosten** [comment]
I have improved the testing at Travis a bit. Whenever the .adl file is in a folder, where somewhere in the path the word ***shouldFail*** exists, the test will pass iff the script fails. 

There still are quite a lof of old scripts that fail. We should cleanup, so we could do more with the result of the testing. As long as there are old scripts that fail, it is useless to signal failure.
Anyone suggestions?

**Comment by sjcjoosten** [comment]
Maybe rename the old scripts to .adl.old for now?

**Comment by hanjoosten** [comment]
Ongoing mainenance. No reason to have an issue for this any longer.
