### ISSUE TITLE
Introducing commands

### ISSUE THREAD

**Issue by hanjoosten** [AmpersandTarski/Ampersand#991]
When running ampersand, we can use loads of switches that do something. Sometimes these switches conflict with each other, or combinations do not make sense. Also, internally, in the Haskell code it would simplify things if we would add commands. There are a lot of good examples around of programs that use commands as well (e.g. Git, stack, pandoc etc). 

The step towards commands will cause the current command line behaviour to be not valid any more, and we will take the oportunity to rethink some switches as we see fit. To simplify the implementation we do not plan to be backwards compatible.

**Comment by hanjoosten** [comment]
Related issues:

- #980 and #971 Give user full control about what metamodel stuff to take into account
- #959 Use a well-chosen default of metamodel stuff with the `daemon` command.
- #921 The RIO stuff is the basis for making all this stuff possible.

**Comment by hanjoosten** [comment]
@Michiel-s , @stefjoosten : For those interested, I have made an [overview of changes on the command line interface](https://github.com/AmpersandTarski/Ampersand/blob/feature/commands/commands.md). This is work in progress, and as long as the feature branch exists, the link will work.

**Comment by Michiel-s** [comment]
Commands are introduced in v4.0.0 which is in alpha release. We might make changes to the CLI based on our experience the upcoming months.
