### ISSUE TITLE
Runtime error: "Interface 'Administrator' is not defined"

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/Ampersand#994]
When I succesfully compile an arbitrary script, e.g. the `ButtonCRUD` application from the ampersand-models repo, and generate a prototype using Ampersand-v3.17.2 [development:254cacd10], using the options `prototype-framework-version=development` and `force-reinstall-framework`, I expect that the prototype can properly install. 

However, when I try to install the prototype, this is what I get:

![afbeelding](https://user-images.githubusercontent.com/8522589/61596529-25c51e00-ac05-11e9-951f-f46947072d6d.png)

I expect the development branch of Ampersand to be useable for normal scripts that do not do anything special. Experimenting with other stuff should be in separate branches and tested before being merged in the development branch. That goes for the Ampersand repo as well as for the Prototype repo.

**Comment by hanjoosten** [comment]
There is no interface named `Administrator` in the script. I wonder where this error comes from. It must be the frontend. @Michiel-s ?

**Comment by Michiel-s** [comment]
Hi @RieksJ could you click on the error message and copy the error stack here. Knowing where the error is thrown helps me to diagnose.

**Comment by RieksJ** [comment]
![afbeelding](https://user-images.githubusercontent.com/8522589/61611895-533db600-ac5d-11e9-86c4-94e08b15a344.png)

**Comment by hanjoosten** [comment]
This is quite obvious: There is an (active) role `Administrator`. However, in AmpersandApp.php you start looking for an interface with the same name, which doesn't exist.

**Comment by Michiel-s** [comment]
Sorry @RieksJ, this bug shouldn’t have found its way into the development branch. My bad.

I’ll try to figure out which line of code you can change to fix it.
