### ISSUE TITLE
ExecEngine log should contain atom-id when _NEW is set

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/Ampersand#998]
It would be helpful when the ExecEngine log file would show **all** references to atoms at the `EXECENGINE.INFO` level. Currently, this is done for all functions except for `InsAtom` (which is understandable, but not desired).

So rather than having:
~~~
[2019-07-25 15:24:32] EXECENGINE.INFO: InsAtom(XXContext) [] []
~~~
I would like to see something that at least also shows the created atom-identifier, e.g. like
~~~
[2019-07-25 15:24:32] EXECENGINE.INFO: InsAtom(XXContext) [] [] XXContext_1564061072_00598418
~~~

**Comment by Michiel-s** [comment]
Is fixed. The core of the prototype framework. Where the actual atom is inserted now logs these things. You should see them on de log flow.
